Magick++: demo.cpp File Reference
demo.cpp File Reference
#include <Magick++.h>
#include <string>
#include <iostream>
#include <list>
Macros
#define MakeLabel(image, text)
Functions
int main (int, char **argv)
Macro Definition Documentation
MakeLabel
#define MakeLabel (image, text)
Definition at line 28 of file demo.cpp.
Referenced by main().
Function Documentation
main()
int main (int , char ** argv)
Definition at line 31 of file demo.cpp.
References Magick::Image::addNoise(), Magick::Image::addNoiseChannel(), Magick::Image::alpha(), Magick::Image::annotate(), Magick::Image::backgroundColor(), Magick::Image::blur(), Magick::Image::blurChannel(), Magick::Image::border(), Magick::Image::borderColor(), Magick::Image::channel(), Magick::Image::charcoal(), Magick::Color, Magick::Image::columns(), Magick::Image::composite(), Magick::Image::contrast(), Magick::Image::convolve(), Magick::Image::crop(), Magick::Image::density(), Magick::Image::despeckle(), Magick::Image::draw(), Magick::Image::edge(), Magick::Image::emboss(), Magick::Image::equalize(), Magick::Image::evaluate(), Magick::Image::fillColor(), Magick::Image::flip(), Magick::Image::flop(), Magick::Image::font(), Magick::Image::fontPointsize(), Magick::Image::frame(), Magick::Image::gamma(), Magick::Image::gaussianBlur(), Magick::Image::gaussianBlurChannel(), Magick::Geometry, Magick::Montage::geometry(), Magick::Image::implode(), Magick::InitializeMagick(), Magick::Image::level(), Magick::Image::levelChannel(), MakeLabel, Magick::Image::medianFilter(), Magick::Image::modulate(), Magick::montageImages(), Magick::Image::motionBlur(), Magick::Image::negate(), Magick::Image::normalize(), Magick::Image::oilPaint(), Magick::Image::quantize(), Magick::Image::quantizeColors(), Magick::Image::quantizeColorSpace(), Magick::Image::quantizeDither(), Magick::Image::raise(), Magick::Image::randomThreshold(), Magick::Image::randomThresholdChannel(), Magick::Image::read(), Magick::Image::reduceNoise(), Magick::Image::roll(), Magick::Image::rotate(), Magick::Image::scale(), Magick::Image::segment(), Magick::Image::shade(), Magick::Image::sharpen(), Magick::Image::shave(), Magick::Image::shear(), Magick::Image::size(), Magick::Image::solarize(), Magick::Image::spread(), Magick::Image::strokeColor(), Magick::Image::strokeWidth(), Magick::Image::swirl(), Magick::Image::threshold(), Magick::Image::transparent(), Magick::Image::unsharpmask(), Magick::Image::wave(), Magick::writeImages(), and Magick::Image::zoom().