Magick++: shapes.cpp File Reference
shapes.cpp File Reference
#include <Magick++.h>
#include <string>
#include <iostream>
Functions
int main (int, char **argv)
Function Documentation
main()
int main (int , char ** argv)
Definition at line 21 of file shapes.cpp.
References Magick::Image::annotate(), Magick::Color, Magick::Image::colorFuzz(), Magick::Image::compressType(), Magick::Image::depth(), Magick::Image::draw(), Magick::Image::fillColor(), Magick::Image::fillPattern(), Magick::Image::floodFillColor(), Magick::Image::font(), Magick::Image::fontPointsize(), Magick::InitializeMagick(), Magick::Image::isValid(), Magick::Image::strokeColor(), Magick::Image::strokeWidth(), and Magick::Image::write().