/*
  Copyright @ 1999 ImageMagick Studio LLC, a non-profit organization
  dedicated to making software imaging solutions freely available.

  You may not use this file except in compliance with the License.  You may
  obtain a copy of the License at

    https://imagemagick.org/license/

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.

  MagickCore private Metal kernels.
*/

#ifndef MAGICKCORE_ACCELERATE_KERNELS_METAL_H
#define MAGICKCORE_ACCELERATE_KERNELS_METAL_H

#if defined(MAGICKCORE_METAL_SUPPORT)

/*
  Metal helper functions — shared by all Metal kernels.
  All pixel values are normalized [0,1] float4 (RGBA).
*/
static const char *metalHelperFunctions =
"#include <metal_stdlib>\n"
"using namespace metal;\n"
"\n"
"/* Constants */\n"
"constant float MagickPI = 3.14159265358979323846;\n"
"constant float MagickEpsilon = 1.0e-12;\n"
"\n"
"/* Colorspace enum (must match ImageMagick values) */\n"
"enum {\n"
"  UndefinedColorspace = 0,\n"
"  GRAYColorspace = 3,\n"
"  RGBColorspace = 21,\n"
"  sRGBColorspace = 23,\n"
"  LinearGRAYColorspace = 34\n"
"};\n"
"\n"
"/* Pixel intensity method enum */\n"
"enum {\n"
"  UndefinedPixelIntensityMethod = 0,\n"
"  AveragePixelIntensityMethod,\n"
"  BrightnessPixelIntensityMethod,\n"
"  LightnessPixelIntensityMethod,\n"
"  MSPixelIntensityMethod,\n"
"  Rec601LumaPixelIntensityMethod,\n"
"  Rec601LuminancePixelIntensityMethod,\n"
"  Rec709LumaPixelIntensityMethod,\n"
"  Rec709LuminancePixelIntensityMethod,\n"
"  RMSPixelIntensityMethod\n"
"};\n"
"\n"
"/* MagickFunction enum */\n"
"enum {\n"
"  UndefinedFunction = 0,\n"
"  ArcsinFunction,\n"
"  ArctanFunction,\n"
"  PolynomialFunction,\n"
"  SinusoidFunction\n"
"};\n"
"\n"
"/* Utility functions */\n"
"inline int ClampToCanvas(int x, int width) {\n"
"  return clamp(x, 0, width - 1);\n"
"}\n"
"\n"
"inline float MagickSafeReciprocal(float x) {\n"
"  float s = (x < 0.0f) ? -1.0f : 1.0f;\n"
"  return (s * x) >= MagickEpsilon ? 1.0f / x : s * (1.0f / MagickEpsilon);\n"
"}\n"
"\n"
"/* Pixel intensity — all inputs normalized [0,1] */\n"
"inline float GetPixelIntensity(uint colorspace, uint method,\n"
"                               float red, float green, float blue) {\n"
"  if (colorspace == GRAYColorspace || colorspace == LinearGRAYColorspace)\n"
"    return red;\n"
"\n"
"  switch (method) {\n"
"    case AveragePixelIntensityMethod:\n"
"      return (red + green + blue) / 3.0f;\n"
"    case BrightnessPixelIntensityMethod:\n"
"      return max(max(red, green), blue);\n"
"    case LightnessPixelIntensityMethod:\n"
"      return (min(min(red, green), blue) + max(max(red, green), blue)) / 2.0f;\n"
"    case MSPixelIntensityMethod:\n"
"      return (red * red + green * green + blue * blue) / 3.0f;\n"
"    case Rec601LumaPixelIntensityMethod:\n"
"    case Rec601LuminancePixelIntensityMethod:\n"
"      return 0.298839f * red + 0.586811f * green + 0.114350f * blue;\n"
"    case Rec709LuminancePixelIntensityMethod:\n"
"      return 0.212656f * red + 0.715158f * green + 0.072186f * blue;\n"
"    case RMSPixelIntensityMethod:\n"
"      return sqrt((red * red + green * green + blue * blue) / 3.0f);\n"
"    case Rec709LumaPixelIntensityMethod:\n"
"    default:\n"
"      return 0.212656f * red + 0.715158f * green + 0.072186f * blue;\n"
"  }\n"
"}\n"
"\n"
"/* RGB <-> HSB conversion — all values normalized [0,1] */\n"
"inline float4 ConvertRGBToHSB(float4 pixel) {\n"
"  float4 result = float4(0.0f);\n"
"  result.w = pixel.w;\n"
"  float tmax = max(max(pixel.x, pixel.y), pixel.z);\n"
"  if (tmax != 0.0f) {\n"
"    float tmin = min(min(pixel.x, pixel.y), pixel.z);\n"
"    float delta = tmax - tmin;\n"
"    result.y = delta / tmax;\n"
"    result.z = tmax;\n"
"    if (delta != 0.0f) {\n"
"      result.x = (pixel.x == tmax) ? 0.0f : ((pixel.y == tmax) ? 2.0f : 4.0f);\n"
"      result.x += (pixel.x == tmax) ? (pixel.y - pixel.z) / delta :\n"
"                  ((pixel.y == tmax) ? (pixel.z - pixel.x) / delta :\n"
"                                       (pixel.x - pixel.y) / delta);\n"
"      result.x /= 6.0f;\n"
"      if (result.x < 0.0f) result.x += 1.0f;\n"
"    }\n"
"  }\n"
"  return result;\n"
"}\n"
"\n"
"inline float4 ConvertHSBToRGB(float4 pixel) {\n"
"  float hue = pixel.x;\n"
"  float saturation = pixel.y;\n"
"  float brightness = pixel.z;\n"
"  float4 result = pixel;\n"
"  if (saturation == 0.0f) {\n"
"    result.x = result.y = result.z = brightness;\n"
"  } else {\n"
"    float h = 6.0f * (hue - floor(hue));\n"
"    float f = h - floor(h);\n"
"    float p = brightness * (1.0f - saturation);\n"
"    float q = brightness * (1.0f - saturation * f);\n"
"    float t = brightness * (1.0f - saturation * (1.0f - f));\n"
"    int ih = (int)h;\n"
"    if (ih == 1)      { result.x = q;          result.y = brightness; result.z = p; }\n"
"    else if (ih == 2) { result.x = p;          result.y = brightness; result.z = t; }\n"
"    else if (ih == 3) { result.x = p;          result.y = q;          result.z = brightness; }\n"
"    else if (ih == 4) { result.x = t;          result.y = p;          result.z = brightness; }\n"
"    else if (ih == 5) { result.x = brightness; result.y = p;          result.z = q; }\n"
"    else              { result.x = brightness; result.y = t;          result.z = p; }\n"
"  }\n"
"  return result;\n"
"}\n"
"\n"
"/* RGB <-> HSL conversion — all values normalized [0,1] */\n"
"inline void ConvertRGBToHSL(float red, float green, float blue,\n"
"                            thread float *hue, thread float *saturation,\n"
"                            thread float *lightness) {\n"
"  float tmax = max(max(red, green), blue);\n"
"  float tmin = min(min(red, green), blue);\n"
"  float c = tmax - tmin;\n"
"  *lightness = (tmax + tmin) / 2.0f;\n"
"  if (c <= 0.0f) {\n"
"    *hue = 0.0f;\n"
"    *saturation = 0.0f;\n"
"    return;\n"
"  }\n"
"  if (tmax == red) {\n"
"    *hue = (green - blue) / c;\n"
"    if (green < blue) *hue += 6.0f;\n"
"  } else if (tmax == green)\n"
"    *hue = 2.0f + (blue - red) / c;\n"
"  else\n"
"    *hue = 4.0f + (red - green) / c;\n"
"  *hue *= 60.0f / 360.0f;\n"
"  if (*lightness <= 0.5f)\n"
"    *saturation = c / (2.0f * (*lightness));\n"
"  else\n"
"    *saturation = c / (2.0f - 2.0f * (*lightness));\n"
"}\n"
"\n"
"inline void ConvertHSLToRGB(float hue, float saturation, float lightness,\n"
"                            thread float *red, thread float *green,\n"
"                            thread float *blue) {\n"
"  float c, h, tmin, x, r, g, b;\n"
"  h = hue * 360.0f;\n"
"  if (lightness <= 0.5f)\n"
"    c = 2.0f * lightness * saturation;\n"
"  else\n"
"    c = (2.0f - 2.0f * lightness) * saturation;\n"
"  tmin = lightness - 0.5f * c;\n"
"  h -= 360.0f * floor(h / 360.0f);\n"
"  h /= 60.0f;\n"
"  x = c * (1.0f - fabs(h - 2.0f * floor(h / 2.0f) - 1.0f));\n"
"  switch ((int)floor(h) % 6) {\n"
"    case 0: default: r = tmin + c; g = tmin + x; b = tmin;     break;\n"
"    case 1:          r = tmin + x; g = tmin + c; b = tmin;     break;\n"
"    case 2:          r = tmin;     g = tmin + c; b = tmin + x; break;\n"
"    case 3:          r = tmin;     g = tmin + x; b = tmin + c; break;\n"
"    case 4:          r = tmin + x; g = tmin;     b = tmin + c; break;\n"
"    case 5:          r = tmin + c; g = tmin;     b = tmin + x; break;\n"
"  }\n"
"  *red = clamp(r, 0.0f, 1.0f);\n"
"  *green = clamp(g, 0.0f, 1.0f);\n"
"  *blue = clamp(b, 0.0f, 1.0f);\n"
"}\n"
"\n"
"inline void ModulateHSL(float percent_hue, float percent_saturation,\n"
"                        float percent_lightness,\n"
"                        thread float *red, thread float *green,\n"
"                        thread float *blue) {\n"
"  float hue, saturation, lightness;\n"
"  ConvertRGBToHSL(*red, *green, *blue, &hue, &saturation, &lightness);\n"
"  hue += 0.5f * (0.01f * percent_hue - 1.0f);\n"
"  while (hue < 0.0f) hue += 1.0f;\n"
"  while (hue >= 1.0f) hue -= 1.0f;\n"
"  saturation *= 0.01f * percent_saturation;\n"
"  lightness *= 0.01f * percent_lightness;\n"
"  ConvertHSLToRGB(hue, saturation, lightness, red, green, blue);\n"
"}\n"
"\n"
"/* ApplyFunction — pixel values normalized [0,1] */\n"
"inline float ApplyFunction(float pixel, uint function,\n"
"                           uint number_parameters,\n"
"                           constant float *parameters) {\n"
"  float result = 0.0f;\n"
"  switch (function) {\n"
"    case PolynomialFunction: {\n"
"      for (uint i = 0; i < number_parameters; i++)\n"
"        result = result * pixel + parameters[i];\n"
"      break;\n"
"    }\n"
"    case SinusoidFunction: {\n"
"      float freq  = (number_parameters >= 1) ? parameters[0] : 1.0f;\n"
"      float phase = (number_parameters >= 2) ? parameters[1] : 0.0f;\n"
"      float ampl  = (number_parameters >= 3) ? parameters[2] : 0.5f;\n"
"      float bias  = (number_parameters >= 4) ? parameters[3] : 0.5f;\n"
"      result = ampl * sin(2.0f * MagickPI * (freq * pixel + phase / 360.0f)) + bias;\n"
"      break;\n"
"    }\n"
"    case ArcsinFunction: {\n"
"      float width  = (number_parameters >= 1) ? parameters[0] : 1.0f;\n"
"      float center = (number_parameters >= 2) ? parameters[1] : 0.5f;\n"
"      float range  = (number_parameters >= 3) ? parameters[2] : 1.0f;\n"
"      float bias   = (number_parameters >= 4) ? parameters[3] : 0.5f;\n"
"      float v = 2.0f / width * (pixel - center);\n"
"      v = clamp(v, -1.0f, 1.0f);\n"
"      result = range / MagickPI * asin(v) + bias;\n"
"      break;\n"
"    }\n"
"    case ArctanFunction: {\n"
"      float slope  = (number_parameters >= 1) ? parameters[0] : 1.0f;\n"
"      float center = (number_parameters >= 2) ? parameters[1] : 0.5f;\n"
"      float range  = (number_parameters >= 3) ? parameters[2] : 1.0f;\n"
"      float bias   = (number_parameters >= 4) ? parameters[3] : 0.5f;\n"
"      result = range / MagickPI * atan(MagickPI * slope * (pixel - center)) + bias;\n"
"      break;\n"
"    }\n"
"    default:\n"
"      result = pixel;\n"
"      break;\n"
"  }\n"
"  return clamp(result, 0.0f, 1.0f);\n"
"}\n"
"\n";

/*
  Contrast kernel — operates directly on the Quantum pixel cache.
  Pixels are float values in [0, QuantumRange] with variable channel count.
*/
static const char *metalContrastKernelSrc =
"kernel void Contrast(device float *image [[buffer(0)]],\n"
"                     constant int &sign [[buffer(1)]],\n"
"                     constant uint &columns [[buffer(2)]],\n"
"                     constant uint &number_channels [[buffer(3)]],\n"
"                     constant float &quantum_scale [[buffer(4)]],\n"
"                     uint2 gid [[thread_position_in_grid]])\n"
"{\n"
"  uint base = (gid.y * columns + gid.x) * number_channels;\n"
"  float red   = image[base + 0] * quantum_scale;\n"
"  float green = (number_channels > 2) ? image[base + 1] * quantum_scale : red;\n"
"  float blue  = (number_channels > 2) ? image[base + 2] * quantum_scale : red;\n"
"\n"
"  float4 pixel = float4(red, green, blue, 0.0f);\n"
"  float4 hsb = ConvertRGBToHSB(pixel);\n"
"  float brightness = hsb.z;\n"
"  brightness += 0.5f * (float)sign *\n"
"    (0.5f * (sin(MagickPI * (brightness - 0.5f)) + 1.0f) - brightness);\n"
"  hsb.z = clamp(brightness, 0.0f, 1.0f);\n"
"  pixel = ConvertHSBToRGB(hsb);\n"
"\n"
"  float qs_inv = 1.0f / quantum_scale;\n"
"  image[base + 0] = pixel.x * qs_inv;\n"
"  if (number_channels > 2) {\n"
"    image[base + 1] = pixel.y * qs_inv;\n"
"    image[base + 2] = pixel.z * qs_inv;\n"
"  }\n"
"}\n";

/*
  Blur kernels — separable 2-pass Gaussian blur.
  Operates directly on Quantum pixel cache with variable channel count.
*/
static const char *metalBlurKernelSrc =
"kernel void BlurRow(device const float *image [[buffer(0)]],\n"
"                    device float *tempImage [[buffer(1)]],\n"
"                    constant float *filter [[buffer(2)]],\n"
"                    constant uint &width [[buffer(3)]],\n"
"                    constant uint &imageColumns [[buffer(4)]],\n"
"                    constant uint &imageRows [[buffer(5)]],\n"
"                    constant uint &number_channels [[buffer(6)]],\n"
"                    uint2 gid [[thread_position_in_grid]],\n"
"                    uint2 lid [[thread_position_in_threadgroup]],\n"
"                    uint2 group_id [[threadgroup_position_in_grid]],\n"
"                    uint2 lsize [[threads_per_threadgroup]],\n"
"                    threadgroup float *temp [[threadgroup(0)]])\n"
"{\n"
"  int x = gid.x;\n"
"  int y = gid.y;\n"
"  int columns = imageColumns;\n"
"  int nc = number_channels;\n"
"  int w = width;\n"
"  int radius = (w - 1) / 2;\n"
"  int groupX = lsize.x * group_id.x;\n"
"  int loadSize = lsize.x + w;\n"
"  for (int i = lid.x; i < loadSize; i += lsize.x) {\n"
"    int cx = ClampToCanvas(i + groupX - radius, columns);\n"
"    int src = (y * columns + cx) * nc;\n"
"    int dst = i * nc;\n"
"    for (int c = 0; c < nc; c++)\n"
"      temp[dst + c] = image[src + c];\n"
"  }\n"
"  threadgroup_barrier(mem_flags::mem_threadgroup);\n"
"  if (x < columns) {\n"
"    int outBase = (y * columns + x) * nc;\n"
"    for (int c = 0; c < nc; c++) {\n"
"      float result = 0.0f;\n"
"      for (int i = 0; i < w; i++)\n"
"        result += filter[i] * temp[(i + lid.x) * nc + c];\n"
"      tempImage[outBase + c] = result;\n"
"    }\n"
"  }\n"
"}\n"
"\n"
"kernel void BlurColumn(device const float *blurRowData [[buffer(0)]],\n"
"                       device float *filteredImage [[buffer(1)]],\n"
"                       constant float *filter [[buffer(2)]],\n"
"                       constant uint &width [[buffer(3)]],\n"
"                       constant uint &imageColumns [[buffer(4)]],\n"
"                       constant uint &imageRows [[buffer(5)]],\n"
"                       constant uint &number_channels [[buffer(6)]],\n"
"                       uint2 gid [[thread_position_in_grid]],\n"
"                       uint2 lid [[thread_position_in_threadgroup]],\n"
"                       uint2 group_id [[threadgroup_position_in_grid]],\n"
"                       uint2 lsize [[threads_per_threadgroup]],\n"
"                       threadgroup float *temp [[threadgroup(0)]])\n"
"{\n"
"  int x = gid.x;\n"
"  int y = gid.y;\n"
"  int columns = imageColumns;\n"
"  int rows = imageRows;\n"
"  int nc = number_channels;\n"
"  int w = width;\n"
"  int radius = (w - 1) / 2;\n"
"  int groupY = lsize.y * group_id.y;\n"
"  int loadSize = lsize.y + w;\n"
"  for (int i = lid.y; i < loadSize; i += lsize.y) {\n"
"    int cy = ClampToCanvas(i + groupY - radius, rows);\n"
"    int src = (cy * columns + x) * nc;\n"
"    int dst = i * nc;\n"
"    for (int c = 0; c < nc; c++)\n"
"      temp[dst + c] = blurRowData[src + c];\n"
"  }\n"
"  threadgroup_barrier(mem_flags::mem_threadgroup);\n"
"  if (y < rows) {\n"
"    int outBase = (y * columns + x) * nc;\n"
"    for (int c = 0; c < nc; c++) {\n"
"      float result = 0.0f;\n"
"      for (int i = 0; i < w; i++)\n"
"        result += filter[i] * temp[(i + lid.y) * nc + c];\n"
"      filteredImage[outBase + c] = result;\n"
"    }\n"
"  }\n"
"}\n";

/*
  Grayscale kernel — operates on Quantum pixel cache directly.
*/
static const char *metalGrayscaleKernelSrc =
"kernel void Grayscale(device float *image [[buffer(0)]],\n"
"                      constant uint &colorspace [[buffer(1)]],\n"
"                      constant uint &method [[buffer(2)]],\n"
"                      constant uint &columns [[buffer(3)]],\n"
"                      constant uint &number_channels [[buffer(4)]],\n"
"                      constant float &quantum_scale [[buffer(5)]],\n"
"                      uint2 gid [[thread_position_in_grid]])\n"
"{\n"
"  uint base = (gid.y * columns + gid.x) * number_channels;\n"
"  float red   = image[base + 0] * quantum_scale;\n"
"  float green = (number_channels > 2) ? image[base + 1] * quantum_scale : red;\n"
"  float blue  = (number_channels > 2) ? image[base + 2] * quantum_scale : red;\n"
"  float intensity = GetPixelIntensity(colorspace, method, red, green, blue);\n"
"  float qs_inv = 1.0f / quantum_scale;\n"
"  image[base + 0] = intensity * qs_inv;\n"
"  if (number_channels > 2) {\n"
"    image[base + 1] = intensity * qs_inv;\n"
"    image[base + 2] = intensity * qs_inv;\n"
"  }\n"
"}\n";

/*
  ComputeFunction kernel — operates on Quantum pixel cache directly.
*/
static const char *metalFunctionKernelSrc =
"kernel void ComputeFunction(device float *image [[buffer(0)]],\n"
"                            constant uint &function [[buffer(1)]],\n"
"                            constant uint &number_parameters [[buffer(2)]],\n"
"                            constant float *parameters [[buffer(3)]],\n"
"                            constant uint &columns [[buffer(4)]],\n"
"                            constant uint &number_channels [[buffer(5)]],\n"
"                            constant float &quantum_scale [[buffer(6)]],\n"
"                            uint2 gid [[thread_position_in_grid]])\n"
"{\n"
"  uint base = (gid.y * columns + gid.x) * number_channels;\n"
"  float qs = quantum_scale;\n"
"  float qs_inv = 1.0f / qs;\n"
"  for (uint c = 0; c < number_channels; c++) {\n"
"    float val = image[base + c] * qs;\n"
"    val = ApplyFunction(val, function, number_parameters, parameters);\n"
"    image[base + c] = val * qs_inv;\n"
"  }\n"
"}\n";

/*
  Modulate kernel — operates on Quantum pixel cache directly.
*/
static const char *metalModulateKernelSrc =
"kernel void Modulate(device float *image [[buffer(0)]],\n"
"                     constant float &percent_brightness [[buffer(1)]],\n"
"                     constant float &percent_hue [[buffer(2)]],\n"
"                     constant float &percent_saturation [[buffer(3)]],\n"
"                     constant uint &columns [[buffer(4)]],\n"
"                     constant uint &number_channels [[buffer(5)]],\n"
"                     constant float &quantum_scale [[buffer(6)]],\n"
"                     uint2 gid [[thread_position_in_grid]])\n"
"{\n"
"  uint base = (gid.y * columns + gid.x) * number_channels;\n"
"  float qs = quantum_scale;\n"
"  float qs_inv = 1.0f / qs;\n"
"  float red   = image[base + 0] * qs;\n"
"  float green = image[base + 1] * qs;\n"
"  float blue  = image[base + 2] * qs;\n"
"  ModulateHSL(percent_hue, percent_saturation, percent_brightness,\n"
"              &red, &green, &blue);\n"
"  image[base + 0] = red * qs_inv;\n"
"  image[base + 1] = green * qs_inv;\n"
"  image[base + 2] = blue * qs_inv;\n"
"}\n";

/*
  MotionBlur kernel — weighted directional blur with offset array.
  Operates on Quantum pixel cache. Produces output in a separate buffer.
*/
static const char *metalMotionBlurKernelSrc =
"kernel void MotionBlur(device const float *input [[buffer(0)]],\n"
"                       device float *output [[buffer(1)]],\n"
"                       constant float *filter [[buffer(2)]],\n"
"                       constant int2 *offset [[buffer(3)]],\n"
"                       constant uint &imageWidth [[buffer(4)]],\n"
"                       constant uint &imageHeight [[buffer(5)]],\n"
"                       constant uint &width [[buffer(6)]],\n"
"                       constant uint &number_channels [[buffer(7)]],\n"
"                       constant uint &has_alpha [[buffer(8)]],\n"
"                       uint2 gid [[thread_position_in_grid]])\n"
"{\n"
"  if (gid.x >= imageWidth || gid.y >= imageHeight) return;\n"
"  uint nc = number_channels;\n"
"  uint outBase = (gid.y * imageWidth + gid.x) * nc;\n"
"\n"
"  if (has_alpha == 0 || nc < 4) {\n"
"    for (uint c = 0; c < nc; c++) {\n"
"      float sum = 0.0f;\n"
"      for (uint i = 0; i < width; i++) {\n"
"        int sx = clamp((int)gid.x + offset[i].x, 0, (int)imageWidth - 1);\n"
"        int sy = clamp((int)gid.y + offset[i].y, 0, (int)imageHeight - 1);\n"
"        sum += filter[i] * input[(sy * imageWidth + sx) * nc + c];\n"
"      }\n"
"      output[outBase + c] = sum;\n"
"    }\n"
"  } else {\n"
"    float3 rgb = float3(0.0f);\n"
"    float alpha_sum = 0.0f;\n"
"    float gamma = 0.0f;\n"
"    for (uint i = 0; i < width; i++) {\n"
"      int sx = clamp((int)gid.x + offset[i].x, 0, (int)imageWidth - 1);\n"
"      int sy = clamp((int)gid.y + offset[i].y, 0, (int)imageHeight - 1);\n"
"      uint sBase = (sy * imageWidth + sx) * nc;\n"
"      float a = input[sBase + 3];\n"
"      float k = filter[i];\n"
"      float ka = k * a;\n"
"      rgb.x += ka * input[sBase + 0];\n"
"      rgb.y += ka * input[sBase + 1];\n"
"      rgb.z += ka * input[sBase + 2];\n"
"      alpha_sum += ka;\n"
"      gamma += ka;\n"
"    }\n"
"    gamma = (fabs(gamma) > MagickEpsilon) ? 1.0f / gamma : 0.0f;\n"
"    output[outBase + 0] = rgb.x * gamma;\n"
"    output[outBase + 1] = rgb.y * gamma;\n"
"    output[outBase + 2] = rgb.z * gamma;\n"
"    output[outBase + 3] = alpha_sum;\n"
"  }\n"
"}\n";

/*
  RotationalBlur kernel — radial spin blur with sin/cos lookup tables.
  Operates on Quantum pixel cache. Produces output in a separate buffer.
*/
static const char *metalRotationalBlurKernelSrc =
"kernel void RotationalBlur(device const float *input [[buffer(0)]],\n"
"                           device float *output [[buffer(1)]],\n"
"                           constant float *cos_theta [[buffer(2)]],\n"
"                           constant float *sin_theta [[buffer(3)]],\n"
"                           constant uint &cossin_theta_size [[buffer(4)]],\n"
"                           constant float2 &blurCenter [[buffer(5)]],\n"
"                           constant uint &columns [[buffer(6)]],\n"
"                           constant uint &rows [[buffer(7)]],\n"
"                           constant uint &number_channels [[buffer(8)]],\n"
"                           uint2 gid [[thread_position_in_grid]])\n"
"{\n"
"  if (gid.x >= columns || gid.y >= rows) return;\n"
"  uint nc = number_channels;\n"
"  float center_x = (float)gid.x - blurCenter.x;\n"
"  float center_y = (float)gid.y - blurCenter.y;\n"
"  float radius = sqrt(center_x * center_x + center_y * center_y);\n"
"  float blur_radius = sqrt(blurCenter.x * blurCenter.x + blurCenter.y * blurCenter.y);\n"
"\n"
"  uint step = 1;\n"
"  if (radius > MagickEpsilon) {\n"
"    step = (uint)(blur_radius / radius);\n"
"    if (step == 0) step = 1;\n"
"    if (step >= cossin_theta_size) step = cossin_theta_size - 1;\n"
"  }\n"
"\n"
"  float4 result = float4(0.0f);\n"
"  float normalize = 0.0f;\n"
"  float gamma = 0.0f;\n"
"  bool has_alpha = (nc == 4 || nc == 2);\n"
"\n"
"  for (uint i = 0; i < cossin_theta_size; i += step) {\n"
"    int cx = clamp((int)(blurCenter.x + center_x * cos_theta[i] -\n"
"                         center_y * sin_theta[i] + 0.5f), 0, (int)columns - 1);\n"
"    int cy = clamp((int)(blurCenter.y + center_x * sin_theta[i] +\n"
"                         center_y * cos_theta[i] + 0.5f), 0, (int)rows - 1);\n"
"    uint sBase = (cy * columns + cx) * nc;\n"
"    float px = input[sBase + 0];\n"
"    float py = (nc > 2) ? input[sBase + 1] : 0.0f;\n"
"    float pz = (nc > 2) ? input[sBase + 2] : 0.0f;\n"
"    float pw = has_alpha ? input[sBase + nc - 1] : 0.0f;\n"
"\n"
"    if (has_alpha) {\n"
"      float alpha = pw;\n"
"      gamma += alpha;\n"
"      result.x += alpha * px;\n"
"      result.y += alpha * py;\n"
"      result.z += alpha * pz;\n"
"      result.w += pw;\n"
"    } else {\n"
"      result.x += px;\n"
"      result.y += py;\n"
"      result.z += pz;\n"
"    }\n"
"    normalize += 1.0f;\n"
"  }\n"
"\n"
"  normalize = (normalize > 0.0f) ? 1.0f / normalize : 0.0f;\n"
"  uint outBase = (gid.y * columns + gid.x) * nc;\n"
"\n"
"  if (has_alpha) {\n"
"    gamma = (fabs(gamma) > MagickEpsilon) ? 1.0f / gamma : 0.0f;\n"
"    output[outBase + 0] = result.x * gamma;\n"
"    if (nc > 2) {\n"
"      output[outBase + 1] = result.y * gamma;\n"
"      output[outBase + 2] = result.z * gamma;\n"
"    }\n"
"    output[outBase + nc - 1] = result.w * normalize;\n"
"  } else {\n"
"    output[outBase + 0] = result.x * normalize;\n"
"    if (nc > 2) {\n"
"      output[outBase + 1] = result.y * normalize;\n"
"      output[outBase + 2] = result.z * normalize;\n"
"    }\n"
"  }\n"
"}\n";

/*
  Despeckle kernels — hull algorithm with 4 directions x 2 polarities.
  Operates on Quantum pixel cache. threshold/increment are ScaleCharToQuantum(2)/(1).
*/
static const char *metalDespeckleKernelSrc =
"kernel void HullPass1(device const float *input [[buffer(0)]],\n"
"                      device float *output [[buffer(1)]],\n"
"                      constant uint &imageWidth [[buffer(2)]],\n"
"                      constant uint &imageHeight [[buffer(3)]],\n"
"                      constant int2 &offset [[buffer(4)]],\n"
"                      constant int &polarity [[buffer(5)]],\n"
"                      constant uint &number_channels [[buffer(6)]],\n"
"                      constant float &threshold [[buffer(7)]],\n"
"                      constant float &increment [[buffer(8)]],\n"
"                      uint2 gid [[thread_position_in_grid]])\n"
"{\n"
"  if (gid.x >= imageWidth || gid.y >= imageHeight) return;\n"
"  uint nc = number_channels;\n"
"  uint base = (gid.y * imageWidth + gid.x) * nc;\n"
"  int nx = (int)gid.x + offset.x;\n"
"  int ny = (int)gid.y + offset.y;\n"
"  bool valid = (nx >= 0 && nx < (int)imageWidth && ny >= 0 && ny < (int)imageHeight);\n"
"  uint nbase = valid ? (ny * imageWidth + nx) * nc : 0;\n"
"  for (uint c = 0; c < nc; c++) {\n"
"    float v = input[base + c];\n"
"    float r = valid ? input[nbase + c] : 0.0f;\n"
"    if (polarity > 0)\n"
"      v = (r >= (v + threshold)) ? (v + increment) : v;\n"
"    else\n"
"      v = (r <= (v - threshold)) ? (v - increment) : v;\n"
"    output[base + c] = v;\n"
"  }\n"
"}\n"
"\n"
"kernel void HullPass2(device const float *input [[buffer(0)]],\n"
"                      device float *output [[buffer(1)]],\n"
"                      constant uint &imageWidth [[buffer(2)]],\n"
"                      constant uint &imageHeight [[buffer(3)]],\n"
"                      constant int2 &offset [[buffer(4)]],\n"
"                      constant int &polarity [[buffer(5)]],\n"
"                      constant uint &number_channels [[buffer(6)]],\n"
"                      constant float &threshold [[buffer(7)]],\n"
"                      constant float &increment [[buffer(8)]],\n"
"                      uint2 gid [[thread_position_in_grid]])\n"
"{\n"
"  if (gid.x >= imageWidth || gid.y >= imageHeight) return;\n"
"  uint nc = number_channels;\n"
"  uint base = (gid.y * imageWidth + gid.x) * nc;\n"
"  int nx1 = (int)gid.x + offset.x;\n"
"  int ny1 = (int)gid.y + offset.y;\n"
"  bool valid1 = (nx1 >= 0 && nx1 < (int)imageWidth && ny1 >= 0 && ny1 < (int)imageHeight);\n"
"  uint nbase1 = valid1 ? (ny1 * imageWidth + nx1) * nc : 0;\n"
"  int nx2 = (int)gid.x - offset.x;\n"
"  int ny2 = (int)gid.y - offset.y;\n"
"  bool valid2 = (nx2 >= 0 && nx2 < (int)imageWidth && ny2 >= 0 && ny2 < (int)imageHeight);\n"
"  uint nbase2 = valid2 ? (ny2 * imageWidth + nx2) * nc : 0;\n"
"  for (uint c = 0; c < nc; c++) {\n"
"    float v = input[base + c];\n"
"    float r = valid1 ? input[nbase1 + c] : 0.0f;\n"
"    float s = valid2 ? input[nbase2 + c] : 0.0f;\n"
"    if (polarity > 0)\n"
"      v = ((s < (v + threshold)) + (r <= v) != 0) ? v : (v + increment);\n"
"    else\n"
"      v = ((s > (v - threshold)) + (r >= v) != 0) ? v : (v - increment);\n"
"    output[base + c] = v;\n"
"  }\n"
"}\n";

/*
  UnsharpMask kernel — applies unsharp mask given original and blurred data.
  Uses existing Blur kernels for the blur pass, then this kernel for the mask.
*/
static const char *metalUnsharpMaskApplyKernelSrc =
"kernel void UnsharpMaskApply(device const float *original [[buffer(0)]],\n"
"                             device const float *blurred [[buffer(1)]],\n"
"                             device float *output [[buffer(2)]],\n"
"                             constant uint &columns [[buffer(3)]],\n"
"                             constant uint &rows [[buffer(4)]],\n"
"                             constant uint &number_channels [[buffer(5)]],\n"
"                             constant float &gain [[buffer(6)]],\n"
"                             constant float &threshold [[buffer(7)]],\n"
"                             constant float &quantum_range [[buffer(8)]],\n"
"                             uint2 gid [[thread_position_in_grid]])\n"
"{\n"
"  if (gid.x >= columns || gid.y >= rows) return;\n"
"  uint nc = number_channels;\n"
"  uint base = (gid.y * columns + gid.x) * nc;\n"
"  float qt = quantum_range * threshold;\n"
"  for (uint c = 0; c < nc; c++) {\n"
"    float orig = original[base + c];\n"
"    float blur = blurred[base + c];\n"
"    float diff = orig - blur;\n"
"    float result = (fabs(2.0f * diff) < qt) ? orig : (orig + diff * gain);\n"
"    output[base + c] = result;\n"
"  }\n"
"}\n";

/*
  LocalContrast kernels — luminance-based local contrast enhancement.
  Uses triangular weighted blur on luminance, then applies strength modulation.
*/
static const char *metalLocalContrastKernelSrc =
"inline int mirrorBottom(int value) { return (value < 0) ? -value : value; }\n"
"inline int mirrorTop(int value, int width) { return (value >= width) ? (2 * width - value - 1) : value; }\n"
"\n"
"kernel void LocalContrastBlurRow(device const float *srcImage [[buffer(0)]],\n"
"                                 device float *tmpImage [[buffer(1)]],\n"
"                                 constant int &radius [[buffer(2)]],\n"
"                                 constant uint &imageWidth [[buffer(3)]],\n"
"                                 constant uint &imageHeight [[buffer(4)]],\n"
"                                 constant uint &number_channels [[buffer(5)]],\n"
"                                 uint2 gid [[thread_position_in_grid]])\n"
"{\n"
"  uint x = gid.x;\n"
"  uint y = gid.y;\n"
"  if (x >= imageWidth || y >= imageHeight) return;\n"
"  uint nc = number_channels;\n"
"  float3 RGB = float3(0.2126f, 0.7152f, 0.0722f);\n"
"  float sum = 0.0f;\n"
"  float weight = 1.0f;\n"
"  for (int j = (int)x - radius; j < (int)x; j++) {\n"
"    int sx = mirrorBottom(j);\n"
"    sx = (sx >= (int)imageWidth) ? mirrorTop(sx, (int)imageWidth) : sx;\n"
"    uint sBase = (y * imageWidth + sx) * nc;\n"
"    float lum = RGB.x * srcImage[sBase] + RGB.y * srcImage[sBase+1] + RGB.z * srcImage[sBase+2];\n"
"    sum += weight * lum;\n"
"    weight += 1.0f;\n"
"  }\n"
"  for (int j = (int)x; j < (int)x + radius; j++) {\n"
"    int sx = (j >= (int)imageWidth) ? mirrorTop(j, (int)imageWidth) : j;\n"
"    sx = mirrorBottom(sx);\n"
"    uint sBase = (y * imageWidth + sx) * nc;\n"
"    float lum = RGB.x * srcImage[sBase] + RGB.y * srcImage[sBase+1] + RGB.z * srcImage[sBase+2];\n"
"    sum += weight * lum;\n"
"    weight -= 1.0f;\n"
"  }\n"
"  tmpImage[y * imageWidth + x] = sum / ((float)(radius + 1) * (float)(radius + 1));\n"
"}\n"
"\n"
"kernel void LocalContrastBlurApplyColumn(device const float *srcImage [[buffer(0)]],\n"
"                                         device float *dstImage [[buffer(1)]],\n"
"                                         device const float *blurImage [[buffer(2)]],\n"
"                                         constant int &radius [[buffer(3)]],\n"
"                                         constant float &strength [[buffer(4)]],\n"
"                                         constant uint &imageWidth [[buffer(5)]],\n"
"                                         constant uint &imageHeight [[buffer(6)]],\n"
"                                         constant uint &number_channels [[buffer(7)]],\n"
"                                         uint2 gid [[thread_position_in_grid]])\n"
"{\n"
"  uint x = gid.x;\n"
"  uint y = gid.y;\n"
"  if (x >= imageWidth || y >= imageHeight) return;\n"
"  uint nc = number_channels;\n"
"  float3 RGB = float3(0.2126f, 0.7152f, 0.0722f);\n"
"  float sum = 0.0f;\n"
"  float weight = 1.0f;\n"
"  for (int j = (int)y - radius; j < (int)y; j++) {\n"
"    int sy = mirrorBottom(j);\n"
"    sy = (sy >= (int)imageHeight) ? mirrorTop(sy, (int)imageHeight) : sy;\n"
"    sum += weight * blurImage[sy * imageWidth + x];\n"
"    weight += 1.0f;\n"
"  }\n"
"  for (int j = (int)y; j < (int)y + radius; j++) {\n"
"    int sy = (j >= (int)imageHeight) ? mirrorTop(j, (int)imageHeight) : j;\n"
"    sy = mirrorBottom(sy);\n"
"    sum += weight * blurImage[sy * imageWidth + x];\n"
"    weight -= 1.0f;\n"
"  }\n"
"  float blurVal = sum / ((float)(radius + 1) * (float)(radius + 1));\n"
"  uint base = (y * imageWidth + x) * nc;\n"
"  float srcVal = RGB.x * srcImage[base] + RGB.y * srcImage[base+1] + RGB.z * srcImage[base+2];\n"
"  float mult = (srcVal - blurVal) * (strength / 100.0f);\n"
"  mult = (srcVal > MagickEpsilon) ? (srcVal + mult) / srcVal : 1.0f;\n"
"  for (uint c = 0; c < nc; c++)\n"
"    dstImage[base + c] = srcImage[base + c] * mult;\n"
"}\n";

/*
  ContrastStretch kernel — applies a pre-computed stretch map per channel.
  The histogram computation and stretch map are built on the CPU.
*/
static const char *metalContrastStretchKernelSrc =
"kernel void ContrastStretchApply(device float *image [[buffer(0)]],\n"
"                                 constant float *stretch_map [[buffer(1)]],\n"
"                                 constant uint &columns [[buffer(2)]],\n"
"                                 constant uint &number_channels [[buffer(3)]],\n"
"                                 constant uint &map_size [[buffer(4)]],\n"
"                                 uint2 gid [[thread_position_in_grid]])\n"
"{\n"
"  if (gid.x >= columns) return;\n"
"  uint nc = number_channels;\n"
"  uint base = (gid.y * columns + gid.x) * nc;\n"
"  for (uint c = 0; c < min(nc, 3u); c++) {\n"
"    uint pos = clamp((uint)image[base + c], 0u, map_size - 1);\n"
"    image[base + c] = stretch_map[pos];\n"
"  }\n"
"}\n";

/*
  Equalize kernel — applies a pre-computed equalization map per channel.
*/
static const char *metalEqualizeKernelSrc =
"kernel void EqualizeApply(device float *image [[buffer(0)]],\n"
"                          constant float *equalize_map [[buffer(1)]],\n"
"                          constant uint &columns [[buffer(2)]],\n"
"                          constant uint &number_channels [[buffer(3)]],\n"
"                          constant uint &map_size [[buffer(4)]],\n"
"                          uint2 gid [[thread_position_in_grid]])\n"
"{\n"
"  if (gid.x >= columns) return;\n"
"  uint nc = number_channels;\n"
"  uint base = (gid.y * columns + gid.x) * nc;\n"
"  for (uint c = 0; c < min(nc, 3u); c++) {\n"
"    uint pos = clamp((uint)image[base + c], 0u, map_size - 1);\n"
"    image[base + c] = equalize_map[pos];\n"
"  }\n"
"}\n";

/*
  Resize kernels — separable horizontal/vertical resampling.
  Supports Box, Triangle, Hann, Hamming, Blackman, CubicBC, Sinc filters.
*/
static const char *metalResizeKernelSrc =
"/* Filter functions */\n"
"inline float BoxResizeFilter(float x) { return 1.0f; }\n"
"inline float TriangleResizeFilter(float x) { return (x < 1.0f) ? (1.0f - x) : 0.0f; }\n"
"inline float HannResizeFilter(float x) { return 0.5f + 0.5f * cos(MagickPI * x); }\n"
"inline float HammingResizeFilter(float x) { return 0.54f + 0.46f * cos(MagickPI * x); }\n"
"inline float BlackmanResizeFilter(float x) { float c = cos(MagickPI * x); return 0.34f + c * (0.5f + c * 0.16f); }\n"
"\n"
"inline float SincResizeFilter(float x) {\n"
"  if (x == 0.0f) return 1.0f;\n"
"  float pix = MagickPI * x;\n"
"  return sin(pix) / pix;\n"
"}\n"
"\n"
"inline float CubicBCResizeFilter(float x, constant float *c) {\n"
"  if (x < 1.0f) return c[0] + x * x * (c[1] + x * c[2]);\n"
"  if (x < 2.0f) return c[3] + x * (c[4] + x * (c[5] + x * c[6]));\n"
"  return 0.0f;\n"
"}\n"
"\n"
"inline float applyFilter(float x, int filterType, constant float *coeffs) {\n"
"  switch (filterType) {\n"
"    case 0: return BoxResizeFilter(x);\n"
"    case 1: return TriangleResizeFilter(x);\n"
"    case 2: return CubicBCResizeFilter(x, coeffs);\n"
"    case 3: return HannResizeFilter(x);\n"
"    case 4: return HammingResizeFilter(x);\n"
"    case 5: return BlackmanResizeFilter(x);\n"
"    case 9: case 10: return SincResizeFilter(x);\n"
"    default: return TriangleResizeFilter(x);\n"
"  }\n"
"}\n"
"\n"
"inline float getWeight(float x, int filterType, int windowType,\n"
"                       constant float *coeffs, float filterScale,\n"
"                       float filterBlur) {\n"
"  float xBlur = fabs(x) / filterBlur;\n"
"  float scale = 1.0f;\n"
"  if (windowType != filterType) {\n"
"    scale = filterScale;\n"
"    scale *= applyFilter(xBlur * scale, windowType, coeffs);\n"
"  }\n"
"  return scale * applyFilter(xBlur, filterType, coeffs);\n"
"}\n"
"\n"
"kernel void ResizeHorizontalFilter(\n"
"  device const float *input [[buffer(0)]],\n"
"  device float *output [[buffer(1)]],\n"
"  constant uint &inputColumns [[buffer(2)]],\n"
"  constant uint &inputRows [[buffer(3)]],\n"
"  constant uint &outputColumns [[buffer(4)]],\n"
"  constant uint &number_channels [[buffer(5)]],\n"
"  constant float &xFactor [[buffer(6)]],\n"
"  constant int &filterType [[buffer(7)]],\n"
"  constant int &windowType [[buffer(8)]],\n"
"  constant float *coefficients [[buffer(9)]],\n"
"  constant float &filterScale [[buffer(10)]],\n"
"  constant float &filterSupport [[buffer(11)]],\n"
"  constant float &filterBlur [[buffer(12)]],\n"
"  uint2 gid [[thread_position_in_grid]])\n"
"{\n"
"  uint x = gid.x;\n"
"  uint y = gid.y;\n"
"  if (x >= outputColumns || y >= inputRows) return;\n"
"  uint nc = number_channels;\n"
"  float center = ((float)x + 0.5f) / xFactor;\n"
"  float support = filterSupport / xFactor;\n"
"  if (support < 0.5f) support = 0.5f;\n"
"  float scale = 1.0f / support;\n"
"  int start = (int)(center - support + 0.5f);\n"
"  int stop = (int)(center + support + 0.5f);\n"
"  float density = 0.0f;\n"
"  float4 result = float4(0.0f);\n"
"  for (int i = start; i < stop; i++) {\n"
"    int sx = clamp(i, 0, (int)inputColumns - 1);\n"
"    float weight = getWeight(scale * ((float)i - center + 0.5f),\n"
"                             filterType, windowType, coefficients,\n"
"                             filterScale, filterBlur);\n"
"    uint sBase = (y * inputColumns + sx) * nc;\n"
"    for (uint c = 0; c < min(nc, 4u); c++)\n"
"      result[c] += weight * input[sBase + c];\n"
"    density += weight;\n"
"  }\n"
"  if (fabs(density) > MagickEpsilon) result *= (1.0f / density);\n"
"  uint dBase = (y * outputColumns + x) * nc;\n"
"  for (uint c = 0; c < nc; c++)\n"
"    output[dBase + c] = result[c];\n"
"}\n"
"\n"
"kernel void ResizeVerticalFilter(\n"
"  device const float *input [[buffer(0)]],\n"
"  device float *output [[buffer(1)]],\n"
"  constant uint &inputColumns [[buffer(2)]],\n"
"  constant uint &inputRows [[buffer(3)]],\n"
"  constant uint &outputRows [[buffer(4)]],\n"
"  constant uint &number_channels [[buffer(5)]],\n"
"  constant float &yFactor [[buffer(6)]],\n"
"  constant int &filterType [[buffer(7)]],\n"
"  constant int &windowType [[buffer(8)]],\n"
"  constant float *coefficients [[buffer(9)]],\n"
"  constant float &filterScale [[buffer(10)]],\n"
"  constant float &filterSupport [[buffer(11)]],\n"
"  constant float &filterBlur [[buffer(12)]],\n"
"  uint2 gid [[thread_position_in_grid]])\n"
"{\n"
"  uint x = gid.x;\n"
"  uint y = gid.y;\n"
"  if (x >= inputColumns || y >= outputRows) return;\n"
"  uint nc = number_channels;\n"
"  float center = ((float)y + 0.5f) / yFactor;\n"
"  float support = filterSupport / yFactor;\n"
"  if (support < 0.5f) support = 0.5f;\n"
"  float scale = 1.0f / support;\n"
"  int start = (int)(center - support + 0.5f);\n"
"  int stop = (int)(center + support + 0.5f);\n"
"  float density = 0.0f;\n"
"  float4 result = float4(0.0f);\n"
"  for (int i = start; i < stop; i++) {\n"
"    int sy = clamp(i, 0, (int)inputRows - 1);\n"
"    float weight = getWeight(scale * ((float)i - center + 0.5f),\n"
"                             filterType, windowType, coefficients,\n"
"                             filterScale, filterBlur);\n"
"    uint sBase = (sy * inputColumns + x) * nc;\n"
"    for (uint c = 0; c < min(nc, 4u); c++)\n"
"      result[c] += weight * input[sBase + c];\n"
"    density += weight;\n"
"  }\n"
"  if (fabs(density) > MagickEpsilon) result *= (1.0f / density);\n"
"  uint dBase = (y * inputColumns + x) * nc;\n"
"  for (uint c = 0; c < nc; c++)\n"
"    output[dBase + c] = result[c];\n"
"}\n";

/*
  WaveletDenoise kernel — 5-pass tile-based wavelet transform with soft thresholding.
  Uses 64x64 tiles with 16-pixel padding. Workgroup size: (64, 4).
*/
static const char *metalWaveletDenoiseKernelSrc =
"inline int mirrorBottom(int value) { return (value < 0) ? -value : value; }\n"
"inline int mirrorTop(int value, int width) { return (value >= width) ? (2 * width - value - 1) : value; }\n"
"\n"
"kernel void WaveletDenoise(device const float *srcImage [[buffer(0)]],\n"
"                           device float *dstImage [[buffer(1)]],\n"
"                           constant uint &number_channels [[buffer(2)]],\n"
"                           constant uint &max_channels [[buffer(3)]],\n"
"                           constant float &threshold [[buffer(4)]],\n"
"                           constant int &passes [[buffer(5)]],\n"
"                           constant uint &imageWidth [[buffer(6)]],\n"
"                           constant uint &imageHeight [[buffer(7)]],\n"
"                           uint2 gid [[thread_position_in_grid]],\n"
"                           uint2 lid [[thread_position_in_threadgroup]],\n"
"                           uint2 group_id [[threadgroup_position_in_grid]])\n"
"{\n"
"  const float noise[] = { 0.8002f, 0.2735f, 0.1202f, 0.0585f, 0.0291f, 0.0152f, 0.0080f, 0.0044f };\n"
"  const int tileSize = 64;\n"
"  const int pad = 1 << (passes - 1);\n"
"  threadgroup float buffer[64 * 64];\n"
"\n"
"  int srcx = (int)group_id.x * (tileSize - 2 * pad) - pad + (int)lid.x;\n"
"  int srcy = (int)group_id.y * (tileSize - 2 * pad) - pad;\n"
"\n"
"  for (uint channel = 0; channel < max_channels; channel++) {\n"
"    /* Load tile into threadgroup memory */\n"
"    for (int i = (int)lid.y; i < tileSize; i += (int)4) {\n"
"      int sx = mirrorTop(mirrorBottom(srcx), (int)imageWidth);\n"
"      int sy = mirrorTop(mirrorBottom(srcy + i), (int)imageHeight);\n"
"      buffer[lid.x + i * tileSize] = srcImage[(sy * imageWidth + sx) * number_channels + channel];\n"
"    }\n"
"    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
"\n"
"    float tmp[16];\n"
"    float accum[16];\n"
"    for (int i = 0; i < 16; i++) accum[i] = 0.0f;\n"
"\n"
"    for (int pass = 0; pass < passes; pass++) {\n"
"      int radius = 1 << pass;\n"
"      float thresh = threshold * noise[pass];\n"
"      int x = (int)lid.x;\n"
"\n"
"      /* Horizontal hat filter */\n"
"      for (int i = (int)lid.y; i < tileSize; i += 4) {\n"
"        int offset = i * tileSize;\n"
"        if (pass == 0) tmp[i / 4] = buffer[x + offset];\n"
"        float pixel = 0.5f * tmp[i / 4] +\n"
"          0.25f * (buffer[mirrorBottom(x - radius) + offset] +\n"
"                   buffer[mirrorTop(x + radius, tileSize) + offset]);\n"
"        threadgroup_barrier(mem_flags::mem_threadgroup);\n"
"        buffer[x + offset] = pixel;\n"
"      }\n"
"      threadgroup_barrier(mem_flags::mem_threadgroup);\n"
"\n"
"      /* Vertical hat filter + soft threshold */\n"
"      for (int i = (int)lid.y; i < tileSize; i += 4) {\n"
"        float pixel = 0.5f * buffer[x + i * tileSize] +\n"
"          0.25f * (buffer[x + mirrorBottom(i - radius) * tileSize] +\n"
"                   buffer[x + mirrorTop(i + radius, tileSize) * tileSize]);\n"
"        float delta = tmp[i / 4] - pixel;\n"
"        tmp[i / 4] = pixel;\n"
"        if (delta < -thresh) delta += thresh;\n"
"        else if (delta > thresh) delta -= thresh;\n"
"        else delta = 0.0f;\n"
"        accum[i / 4] += delta;\n"
"      }\n"
"      threadgroup_barrier(mem_flags::mem_threadgroup);\n"
"\n"
"      if (pass < passes - 1) {\n"
"        for (int i = (int)lid.y; i < tileSize; i += 4)\n"
"          buffer[(int)lid.x + i * tileSize] = tmp[i / 4];\n"
"      } else {\n"
"        for (int i = (int)lid.y; i < tileSize; i += 4)\n"
"          accum[i / 4] += tmp[i / 4];\n"
"      }\n"
"      threadgroup_barrier(mem_flags::mem_threadgroup);\n"
"    }\n"
"\n"
"    /* Write output (excluding padding) */\n"
"    if (lid.x >= (uint)pad && lid.x < (uint)(tileSize - pad) &&\n"
"        srcx >= 0 && srcx < (int)imageWidth) {\n"
"      for (int i = (int)lid.y; i < tileSize; i += 4) {\n"
"        if (i >= pad && i < tileSize - pad &&\n"
"            srcy + i >= 0 && srcy + i < (int)imageHeight) {\n"
"          uint pos = ((srcy + i) * imageWidth + srcx) * number_channels + channel;\n"
"          dstImage[pos] = accum[i / 4];\n"
"        }\n"
"      }\n"
"    }\n"
"    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
"  }\n"
"}\n";

#endif

#endif
