.Dd July 13, 2015
.Dt MAGICKCORE-CONFIG 1
.Os
.Sh NAME
.Nm MagickCore-config
.Nd get information about the installed version of ImageMagick
.Sh SYNOPSIS
.Nm MagickCore-config
.Op Fl -cflags
.Op Fl -cppflags
.Op Fl -exec-prefix
.Op Fl -ldflags
.Op Fl -libs
.Op Fl -prefix
.Op Fl -version
.Sh DESCRIPTION
The
.Nm MagickCore-config
utility prints the compiler and linker flags required
to compile and link programs that use the
.Nm ImageMagick "Core"
Application Programmer Interface.
.Pp
The following options are available:
.Bl -tag -width Fl
.It Fl -cppflags , -cflags , -cxxflags
Print the compiler flags that are needed to find the
.Xr ImageMagick 1
C include files and defines to ensure that the ImageMagick data structures match between
your program and the installed libraries.
.It Fl -prefix , -exec-prefix
Print the directory under which target specific binaries and executables are installed.
.It Fl -ldflags , -libs
Print the linker flags that are needed to link with the
.Xr ImageMagick 1
library.
.It Fl -version
Print the version of the
.Xr ImageMagick 1
distribution to standard output.
.It Fl -coder-path
Print the path where the
.Xr ImageMagick 1
coder modules are installed.
.It Fl -filter-path
Print the path where the
.Xr ImageMagick 1
filter modules are installed.
.El
.Sh EXAMPLES
To print the version of the installed distribution of
.Nm ImageMagick
use:

.Dl MagickCore-config --version
.sp
To compile a program that calls the
.Xr ImageMagick 1
Application Programmer Interface, use:

.Dl cc `MagickCore-config --cppflags --ldflags` program.c
.Sh SEE ALSO
.Xr ImageMagick 1
.Sh LICENSE
.Nm ImageMagick
is licensed with the Apache license 2.0. See
http://www.imagemagick.org/script/license.php for more details.
.Sh AUTHORS
.An -nosplit
The
.Nm ImageMagick
suite and this manual page where written by
.An Cristy, ImageMagick Studio LLC <development-team@imagemagick.org>.
