.TH conjure 1 "Date: 2009/01/10 01:00:00" "ImageMagick"
.SH NAME
conjure \- interprets and executes scripts written in the Magick Scripting Language (MSL).
.SH SYNOPSIS
.TP
\fBconjure\fP [\fIoptions\fP] \fIscript.msl\fP
.SH OVERVIEW
The \fBconjure\fP program is a member of the ImageMagick(1) suite of tools.  Use it to process a Magick Scripting Language (MSL) script. The Magick scripting language (MSL) will primarily benefit those that want to accomplish custom image processing tasks but do not wish to program, or those that do not have access to a Perl interpreter or a compiler.

For more information about the conjure command, point your browser to file:///usr/local/share/doc/ImageMagick-6/www/conjure.html or http://www.imagemagick.org/script/conjure.php.
.SH DESCRIPTION
Image Settings:
  \-monitor             monitor progress
  \-quiet               suppress all warning messages
  \-regard-warnings     pay attention to warning messages
  \-seed value          seed a new sequence of pseudo-random numbers
  \-verbose             print detailed information about the image

Miscellaneous Options:
  \-debug events        display copious debugging information
  \-help                print program options
  \-log format          format of debugging information
  \-list type           print a list of supported option arguments
  \-version             print version information

In additiion, define any key value pairs required by your script.  For example,

    conjure \-size 100x100 \-color blue \-foo bar script.msl
.SH SEE ALSO
ImageMagick(1)

.SH COPYRIGHT

\fBCopyright (C) 1999-2014 ImageMagick Studio LLC. Additional copyrights and licenses apply to this software, see file:///usr/local/share/doc/ImageMagick-6/www/license.html or http://www.imagemagick.org/script/license.php\fP
