MagickCore: annotate.h File Reference
annotate.h File Reference
#include "MagickCore/draw.h"
Functions
MagickExport MagickBooleanType AnnotateImage (Image *, const DrawInfo *, ExceptionInfo *)
MagickExport MagickBooleanType GetMultilineTypeMetrics (Image *, const DrawInfo *, TypeMetric *, ExceptionInfo *)
MagickExport MagickBooleanType GetTypeMetrics (Image *, const DrawInfo *, TypeMetric *, ExceptionInfo *)
MagickExport ssize_t FormatMagickCaption (Image *, DrawInfo *, const MagickBooleanType, TypeMetric *, char **, ExceptionInfo *)
Function Documentation
MagickExport MagickBooleanType AnnotateImage (Image * , const DrawInfo * , ExceptionInfo *)
MagickExport ssize_t FormatMagickCaption (Image * , DrawInfo * , const MagickBooleanType , TypeMetric * , char ** , ExceptionInfo *)
Definition at line 550 of file annotate.c.
References AcquireString(), ConcatenateMagickString(), CopyMagickString(), DestroyString(), GetTypeMetrics(), GetUTFCode(), GetUTFOctets(), IsUTFSpace(), MagickFalse, _DrawInfo::stroke_width, _DrawInfo::text, and _TypeMetric::width.
Referenced by PolaroidImage().
MagickExport MagickBooleanType GetMultilineTypeMetrics (Image * , const DrawInfo * , TypeMetric * , ExceptionInfo *)
MagickExport MagickBooleanType GetTypeMetrics (Image * , const DrawInfo * , TypeMetric * , ExceptionInfo *)
Definition at line 787 of file annotate.c.
References AnnotateEvent, _TypeMetric::ascent, _TypeMetric::bounds, CloneDrawInfo(), _Image::debug, _TypeMetric::descent, DestroyDrawInfo(), _DrawInfo::direction, _Image::filename, GetMagickModule, _TypeMetric::height, LogMagickEvent(), MagickFalse, MagickSignature, _TypeMetric::max_advance, _TypeMetric::origin, _TypeMetric::pixels_per_em, _DrawInfo::render, RenderType(), ResetMagickMemory(), _DrawInfo::signature, _Image::signature, _DrawInfo::text, TraceEvent, UndefinedDirection, _TypeMetric::underline_position, _TypeMetric::underline_thickness, _TypeMetric::width, _PointInfo::x, _SegmentInfo::x1, _SegmentInfo::x2, _PointInfo::y, _SegmentInfo::y1, and _SegmentInfo::y2.
Referenced by AnnotateImage(), FormatMagickCaption(), GetMultilineTypeMetrics(), and MontageImageList().