MagickCore: annotate.c File Reference
annotate.c File Reference
#include "MagickCore/studio.h"
#include "MagickCore/annotate.h"
#include "MagickCore/annotate-private.h"
#include "MagickCore/attribute.h"
#include "MagickCore/cache-view.h"
#include "MagickCore/channel.h"
#include "MagickCore/client.h"
#include "MagickCore/color.h"
#include "MagickCore/color-private.h"
#include "MagickCore/colorspace-private.h"
#include "MagickCore/composite.h"
#include "MagickCore/composite-private.h"
#include "MagickCore/constitute.h"
#include "MagickCore/draw.h"
#include "MagickCore/draw-private.h"
#include "MagickCore/enhance.h"
#include "MagickCore/exception.h"
#include "MagickCore/exception-private.h"
#include "MagickCore/gem.h"
#include "MagickCore/geometry.h"
#include "MagickCore/image-private.h"
#include "MagickCore/log.h"
#include "MagickCore/quantum.h"
#include "MagickCore/quantum-private.h"
#include "MagickCore/pixel-accessor.h"
#include "MagickCore/property.h"
#include "MagickCore/resource_.h"
#include "MagickCore/semaphore.h"
#include "MagickCore/statistic.h"
#include "MagickCore/string_.h"
#include "MagickCore/token-private.h"
#include "MagickCore/transform.h"
#include "MagickCore/type.h"
#include "MagickCore/utility.h"
#include "MagickCore/utility-private.h"
#include "MagickCore/xwindow.h"
#include "MagickCore/xwindow-private.h"
Functions
static MagickBooleanType RenderType (Image *, const DrawInfo *, const PointInfo *, TypeMetric *, ExceptionInfo *)
static MagickBooleanType RenderPostscript (Image *, const DrawInfo *, const PointInfo *, TypeMetric *, ExceptionInfo *)
static MagickBooleanType RenderFreetype (Image *, const DrawInfo *, const char *, const PointInfo *, TypeMetric *, ExceptionInfo *)
static MagickBooleanType RenderX11 (Image *, const DrawInfo *, const PointInfo *, TypeMetric *, ExceptionInfo *)
MagickPrivate MagickBooleanType AnnotateComponentGenesis (void)
MagickPrivate void AnnotateComponentTerminus (void)
MagickExport MagickBooleanType AnnotateImage (Image *image, const DrawInfo *draw_info, ExceptionInfo *exception)
MagickExport ssize_t FormatMagickCaption (Image *image, DrawInfo *draw_info, const MagickBooleanType split, TypeMetric *metrics, char **caption, ExceptionInfo *exception)
MagickExport MagickBooleanType GetMultilineTypeMetrics (Image *image, const DrawInfo *draw_info, TypeMetric *metrics, ExceptionInfo *exception)
MagickExport MagickBooleanType GetTypeMetrics (Image *image, const DrawInfo *draw_info, TypeMetric *metrics, ExceptionInfo *exception)
static MagickBooleanType RenderFreetype (Image *image, const DrawInfo *draw_info, const char *magick_unused(encoding), const PointInfo *offset, TypeMetric *metrics, ExceptionInfo *exception)
static size_t MagickMin (const size_t x, const size_t y)
static char * EscapeParenthesis (const char *text)
Variables
static SemaphoreInfo * annotate_semaphore = (SemaphoreInfo *) NULL
Function Documentation
MagickPrivate MagickBooleanType AnnotateComponentGenesis (void)
Definition at line 146 of file annotate.c.
References AcquireSemaphoreInfo(), annotate_semaphore, and MagickTrue.
Referenced by MagickCoreGenesis().
MagickPrivate void AnnotateComponentTerminus (void)
Definition at line 170 of file annotate.c.
References AcquireSemaphoreInfo(), annotate_semaphore, and DestroySemaphoreInfo().
Referenced by MagickCoreTerminus().
MagickExport MagickBooleanType AnnotateImage (Image * image, const DrawInfo * draw_info, ExceptionInfo * exception)
Definition at line 228 of file annotate.c.
References _DrawInfo::affine, _DrawInfo::align, _PixelInfo::alpha, _TypeMetric::ascent, _TypeMetric::bounds, CenterAlign, CenterGravity, CloneDrawInfo(), CloneString(), _Image::colorspace, _Image::debug, _DrawInfo::decorate, _TypeMetric::descent, DestroyDrawInfo(), DestroyString(), DirectClass, DrawImage(), EastGravity, _Image::filename, _DrawInfo::fill, FormatLocaleString(), _DrawInfo::geometry, GetMagickModule, GetTypeMetrics(), _DrawInfo::gravity, _RectangleInfo::height, _DrawInfo::interline_spacing, IsGrayColorspace(), LeftAlign, LineThroughDecoration, LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, MaxTextExtent, NorthEastGravity, NorthGravity, NorthWestGravity, _TypeMetric::origin, OverlineDecoration, _Image::page, ParseGeometry(), ParsePageGeometry(), _DrawInfo::primitive, _GeometryInfo::psi, RelinquishMagickMemory(), RenderType(), RightAlign, _AffineMatrix::rx, _AffineMatrix::ry, SetGeometry(), SetGeometryInfo(), SetImageColorspace(), SetImageStorageClass(), _DrawInfo::signature, _Image::signature, SouthEastGravity, SouthGravity, SouthWestGravity, sRGBColorspace, StringToList(), _AffineMatrix::sx, _AffineMatrix::sy, _DrawInfo::text, TraceEvent, TransparentAlpha, _AffineMatrix::tx, _AffineMatrix::ty, UndefinedGravity, _DrawInfo::undercolor, _TypeMetric::underline_position, _TypeMetric::underline_thickness, UnderlineDecoration, WestGravity, _RectangleInfo::width, _TypeMetric::width, _PointInfo::x, _RectangleInfo::x, _SegmentInfo::x1, _GeometryInfo::xi, _PointInfo::y, and _RectangleInfo::y.
Referenced by DrawPrimitive(), MontageImageList(), and PolaroidImage().
static char* EscapeParenthesis (const char * text) static
Definition at line 1601 of file annotate.c.
References AcquireString(), MagickMin(), and MaxTextExtent.
Referenced by RenderPostscript().
MagickExport ssize_t FormatMagickCaption (Image * image, DrawInfo * draw_info, const MagickBooleanType split, TypeMetric * metrics, char ** caption, ExceptionInfo * exception)
Definition at line 550 of file annotate.c.
References AcquireString(), ConcatenateMagickString(), CopyMagickString(), DestroyString(), GetTypeMetrics(), GetUTFCode(), GetUTFOctets(), IsUTFSpace(), MagickFalse, _DrawInfo::stroke_width, _DrawInfo::text, and _TypeMetric::width.
Referenced by PolaroidImage().
MagickExport MagickBooleanType GetMultilineTypeMetrics (Image * image, const DrawInfo * draw_info, TypeMetric * metrics, ExceptionInfo * exception)
Definition at line 676 of file annotate.c.
References _TypeMetric::ascent, CloneDrawInfo(), _Image::debug, _TypeMetric::descent, DestroyDrawInfo(), DestroyString(), _DrawInfo::direction, _Image::filename, GetMagickModule, GetTypeMetrics(), _TypeMetric::height, _DrawInfo::interline_spacing, LogMagickEvent(), MagickFalse, MagickSignature, RelinquishMagickMemory(), _DrawInfo::render, ResetMagickMemory(), _DrawInfo::signature, _Image::signature, StringToList(), _DrawInfo::text, TraceEvent, UndefinedDirection, and _TypeMetric::width.
MagickExport MagickBooleanType GetTypeMetrics (Image * image, const DrawInfo * draw_info, TypeMetric * metrics, ExceptionInfo * exception)
Definition at line 787 of file annotate.c.
References AnnotateEvent, _TypeMetric::ascent, _TypeMetric::bounds, CloneDrawInfo(), _Image::debug, _TypeMetric::descent, DestroyDrawInfo(), _DrawInfo::direction, _Image::filename, GetMagickModule, _TypeMetric::height, LogMagickEvent(), MagickFalse, MagickSignature, _TypeMetric::max_advance, _TypeMetric::origin, _TypeMetric::pixels_per_em, _DrawInfo::render, RenderType(), ResetMagickMemory(), _DrawInfo::signature, _Image::signature, _DrawInfo::text, TraceEvent, UndefinedDirection, _TypeMetric::underline_position, _TypeMetric::underline_thickness, _TypeMetric::width, _PointInfo::x, _SegmentInfo::x1, _SegmentInfo::x2, _PointInfo::y, _SegmentInfo::y1, and _SegmentInfo::y2.
Referenced by AnnotateImage(), FormatMagickCaption(), GetMultilineTypeMetrics(), and MontageImageList().
static size_t MagickMin (const size_t x, const size_t y) inline static
Definition at line 1594 of file annotate.c.
Referenced by EscapeParenthesis().
static MagickBooleanType RenderFreetype (Image * , const DrawInfo * , const char * , const PointInfo * , TypeMetric * , ExceptionInfo *)
Referenced by RenderType().
static MagickBooleanType RenderFreetype (Image * image, const DrawInfo * draw_info, const char * magick_unusedencoding, const PointInfo * offset, TypeMetric * metrics, ExceptionInfo * exception) static
Definition at line 1550 of file annotate.c.
References _DrawInfo::font, GetMagickModule, MissingDelegateWarning, RenderPostscript(), and ThrowMagickException().
static MagickBooleanType RenderPostscript (Image * image, const DrawInfo * draw_info, const PointInfo * offset, TypeMetric * metrics, ExceptionInfo * exception)
Definition at line 1631 of file annotate.c.
References AcquireAuthenticCacheView(), AcquireImageInfo(), AcquireUniqueFileResource(), _DrawInfo::affine, _PixelInfo::alpha, _Image::alpha_trait, AnnotateEvent, _ImageInfo::antialias, _TypeMetric::ascent, BlendPixelTrait, _PixelInfo::blue, _TypeMetric::bounds, CatchException(), ClampToQuantum(), CloneString(), _Image::columns, CompositeImage(), _Image::debug, DefaultResolution, _DrawInfo::density, _ImageInfo::density, _TypeMetric::descent, DestroyCacheView(), DestroyImage(), DestroyImageInfo(), DestroyString(), EscapeParenthesis(), ExpandAffine(), _ImageInfo::filename, FileOpenError, _DrawInfo::fill, _DrawInfo::font, FormatLocaleFile(), FormatLocaleString(), GetCacheViewAuthenticPixels(), GetFillColor(), GetImageBoundingBox(), GetMagickModule, GetPixelChannels(), GetPixelIntensity(), _PixelInfo::green, _RectangleInfo::height, _TypeMetric::height, LogMagickEvent(), MagickEpsilon, MagickFalse, MagickTrue, _TypeMetric::max_advance, MaxTextExtent, NegateImage(), OpaqueAlphaChannel, OverCompositeOp, _ImageInfo::page, ParseGeometry(), _TypeMetric::pixels_per_em, _DrawInfo::pointsize, QuantumScale, ReadImage(), _PixelInfo::red, RelinquishUniqueFileResource(), _DrawInfo::render, _GeometryInfo::rho, _Image::rows, _AffineMatrix::rx, _AffineMatrix::ry, SetImageAlphaChannel(), SetPixelAlpha(), SetPixelBlue(), SetPixelGreen(), SetPixelRed(), _GeometryInfo::sigma, SigmaValue, _AffineMatrix::sx, _AffineMatrix::sy, SyncCacheViewAuthenticPixels(), _DrawInfo::text, _DrawInfo::text_antialias, ThrowFileException, TransformImage(), TransparentAlpha, _TypeMetric::underline_position, _TypeMetric::underline_thickness, _RectangleInfo::width, _TypeMetric::width, _PointInfo::x, _RectangleInfo::x, _SegmentInfo::x1, _SegmentInfo::x2, _PointInfo::y, _RectangleInfo::y, _SegmentInfo::y1, and _SegmentInfo::y2.
Referenced by RenderFreetype().
static MagickBooleanType RenderType (Image * image, const DrawInfo * draw_info, const PointInfo * offset, TypeMetric * metrics, ExceptionInfo * exception) static
Definition at line 859 of file annotate.c.
References CloneDrawInfo(), CloneString(), DestroyDrawInfo(), _TypeInfo::encoding, _DrawInfo::encoding, _TypeInfo::face, _DrawInfo::face, _DrawInfo::family, _DrawInfo::font, GetMagickModule, GetTypeInfo(), GetTypeInfoByFamily(), _TypeInfo::glyphs, IsPathAccessible(), MagickFalse, _TypeInfo::metrics, _DrawInfo::metrics, RenderFreetype(), RenderX11(), _DrawInfo::stretch, _DrawInfo::style, ThrowMagickException(), TypeWarning, and _DrawInfo::weight.
Referenced by AnnotateImage(), and GetTypeMetrics().
static MagickBooleanType RenderX11 (Image * image, const DrawInfo * draw_info, const PointInfo * offset, TypeMetric * metrics, ExceptionInfo * exception)
Definition at line 1894 of file annotate.c.
References AcquireSemaphoreInfo(), annotate_semaphore, LockSemaphoreInfo(), UnlockSemaphoreInfo(), and XRenderImage().
Referenced by RenderType().
Variable Documentation
SemaphoreInfo* annotate_semaphore = (SemaphoreInfo *) NULL static
Definition at line 113 of file annotate.c.
Referenced by AnnotateComponentGenesis(), AnnotateComponentTerminus(), and RenderX11().