MagickCore: blob.h File Reference
blob.h File Reference
#include "MagickCore/image.h"
#include "MagickCore/stream.h"
Macros
#define MagickMaxBufferExtent (32*8192-2)
Typedefs
typedef int *(* BlobFifo)(const Image *, const void *, const size_t)
Enumerations
enum BlobMode {
UndefinedBlobMode, ReadBlobMode, ReadBinaryBlobMode, WriteBlobMode,
WriteBinaryBlobMode, AppendBlobMode, AppendBinaryBlobMode
}
enum MapMode { ReadMode, WriteMode, IOMode }
Functions
MagickExport BlobInfo * CloneBlobInfo (const BlobInfo *)
MagickExport BlobInfo * ReferenceBlob (BlobInfo *)
MagickExport char * ReadBlobString (Image *, char *)
MagickExport double ReadBlobDouble (Image *)
MagickExport FILE * GetBlobFileHandle (const Image *)
MagickExport float ReadBlobFloat (Image *)
MagickExport Image * BlobToImage (const ImageInfo *, const void *, const size_t, ExceptionInfo *)
MagickExport Image * PingBlob (const ImageInfo *, const void *, const size_t, ExceptionInfo *)
MagickExport int EOFBlob (const Image *)
MagickExport int ReadBlobByte (Image *)
MagickExport MagickBooleanType BlobToFile (char *, const void *, const size_t, ExceptionInfo *)
MagickExport MagickBooleanType CloseBlob (Image *)
MagickExport MagickBooleanType DiscardBlobBytes (Image *, const MagickSizeType)
MagickExport MagickBooleanType FileToImage (Image *, const char *, ExceptionInfo *)
MagickExport MagickBooleanType ImageToFile (Image *, char *, ExceptionInfo *)
MagickExport MagickBooleanType InjectImageBlob (const ImageInfo *, Image *, Image *, const char *, ExceptionInfo *)
MagickExport MagickBooleanType OpenBlob (const ImageInfo *, Image *, const BlobMode, ExceptionInfo *)
MagickExport MagickBooleanType UnmapBlob (void *, const size_t)
MagickExport MagickOffsetType SeekBlob (Image *, const MagickOffsetType, const int)
MagickExport MagickOffsetType TellBlob (const Image *)
MagickExport MagickSizeType GetBlobSize (const Image *)
MagickExport MagickSizeType ReadBlobLongLong (Image *)
MagickExport MagickSizeType ReadBlobMSBLongLong (Image *)
MagickExport ssize_t ReadBlob (Image *, const size_t, unsigned char *)
MagickExport ssize_t WriteBlob (Image *, const size_t, const unsigned char *)
MagickExport ssize_t WriteBlobByte (Image *, const unsigned char)
MagickExport ssize_t WriteBlobFloat (Image *, const float)
MagickExport ssize_t WriteBlobLong (Image *, const unsigned int)
MagickExport ssize_t WriteBlobShort (Image *, const unsigned short)
MagickExport ssize_t WriteBlobLSBLong (Image *, const unsigned int)
MagickExport ssize_t WriteBlobLSBShort (Image *, const unsigned short)
MagickExport ssize_t WriteBlobMSBLong (Image *, const unsigned int)
MagickExport ssize_t WriteBlobMSBLongLong (Image *, const MagickSizeType)
MagickExport ssize_t WriteBlobMSBShort (Image *, const unsigned short)
MagickExport ssize_t WriteBlobString (Image *, const char *)
MagickExport unsigned char * DetachBlob (BlobInfo *)
MagickExport unsigned char * FileToBlob (const char *, const size_t, size_t *, ExceptionInfo *)
MagickExport unsigned char * GetBlobStreamData (const Image *)
MagickExport unsigned char * ImageToBlob (const ImageInfo *, Image *, size_t *, ExceptionInfo *)
MagickExport unsigned char * ImagesToBlob (const ImageInfo *, Image *, size_t *, ExceptionInfo *)
MagickExport unsigned char * MapBlob (int, const MapMode, const MagickOffsetType, const size_t)
MagickExport unsigned int ReadBlobLong (Image *)
MagickExport unsigned int ReadBlobLSBLong (Image *)
MagickExport unsigned int ReadBlobMSBLong (Image *)
MagickExport unsigned short ReadBlobShort (Image *)
MagickExport unsigned short ReadBlobLSBShort (Image *)
MagickExport unsigned short ReadBlobMSBShort (Image *)
MagickExport void AttachBlob (BlobInfo *, const void *, const size_t)
MagickExport void DestroyBlob (Image *)
MagickExport void DuplicateBlob (Image *, const Image *)
MagickExport void MSBOrderLong (unsigned char *, const size_t)
MagickExport void MSBOrderShort (unsigned char *, const size_t)
Macro Definition Documentation
#define MagickMaxBufferExtent (32*8192-2)
Definition at line 28 of file blob.h.
Referenced by AcquireUniqueSymbolicLink(), CopyDelegateFile(), FileToBlob(), FileToImage(), ImageToFile(), InjectImageBlob(), OpenBlob(), ReadPixelCacheMetacontent(), ReadPixelCachePixels(), ShredFile(), WritePixelCacheMetacontent(), and WritePixelCachePixels().
Typedef Documentation
typedef int*(* BlobFifo)(const Image *, const void *, const size_t)
Definition at line 49 of file blob.h.
Enumeration Type Documentation
enum BlobMode
Enumerator
UndefinedBlobMode
ReadBlobMode
ReadBinaryBlobMode
WriteBlobMode
WriteBinaryBlobMode
AppendBlobMode
AppendBinaryBlobMode
Definition at line 30 of file blob.h.
enum MapMode
Enumerator
ReadMode
WriteMode
IOMode
Definition at line 41 of file blob.h.
Function Documentation
MagickExport void AttachBlob (BlobInfo * , const void * , const size_t)
MagickExport MagickBooleanType BlobToFile (char * , const void * , const size_t , ExceptionInfo *)
MagickExport Image* BlobToImage (const ImageInfo * , const void * , const size_t , ExceptionInfo *)
MagickExport BlobInfo* CloneBlobInfo (const BlobInfo *)
MagickExport MagickBooleanType CloseBlob (Image *)
MagickExport void DestroyBlob (Image *)
MagickExport unsigned char* DetachBlob (BlobInfo *)
MagickExport MagickBooleanType DiscardBlobBytes (Image * , const MagickSizeType)
MagickExport void DuplicateBlob (Image * , const Image *)
MagickExport int EOFBlob (const Image *)
MagickExport unsigned char * FileToBlob (const char * , const size_t , size_t * , ExceptionInfo *)
MagickExport MagickBooleanType FileToImage (Image * , const char * , ExceptionInfo *)
MagickExport FILE* GetBlobFileHandle (const Image *)
Definition at line 1245 of file blob.c.
References _Image::blob, FileInfo::file, _BlobInfo::file_info, MagickSignature, and _Image::signature.
MagickExport MagickSizeType GetBlobSize (const Image *)
MagickExport unsigned char * GetBlobStreamData (const Image *)
MagickExport unsigned char * ImagesToBlob (const ImageInfo * , Image * , size_t * , ExceptionInfo *)
MagickExport unsigned char * ImageToBlob (const ImageInfo * , Image * , size_t * , ExceptionInfo *)
MagickExport MagickBooleanType ImageToFile (Image * , char * , ExceptionInfo *)
MagickExport MagickBooleanType InjectImageBlob (const ImageInfo * , Image * , Image * , const char * , ExceptionInfo *)
MagickExport unsigned char * MapBlob (int , const MapMode , const MagickOffsetType , const size_t)
Definition at line 2142 of file blob.c.
References IOMode, MAP_FAILED, ReadMode, and WriteMode.
Referenced by AcquireCacheNexusPixels(), AcquireRadonInfo(), AcquireStreamPixels(), AllocatePixelCachePixels(), ConfigureFileToStringInfo(), FileToBlob(), OpenBlob(), OpenPixelCache(), and SetBlobExtent().
MagickExport void MSBOrderLong (unsigned char * , const size_t)
MagickExport void MSBOrderShort (unsigned char * , const size_t)
Definition at line 2285 of file blob.c.
MagickExport MagickBooleanType OpenBlob (const ImageInfo * , Image * , const BlobMode , ExceptionInfo *)
MagickExport Image * PingBlob (const ImageInfo * , const void * , const size_t , ExceptionInfo *)
Definition at line 2692 of file blob.c.
References AcquireQuantumMemory(), _ImageInfo::blob, BlobError, CloneImageInfo(), _ImageInfo::debug, DestroyImageInfo(), _ImageInfo::filename, GetMagickModule, _ImageInfo::length, LogMagickEvent(), _ImageInfo::magick, MagickFalse, MagickSignature, MagickTrue, _ImageInfo::ping, PingStream(), ReadStream(), RelinquishMagickMemory(), ResourceLimitFatalError, _ImageInfo::signature, ThrowMagickException(), and TraceEvent.
MagickExport ssize_t ReadBlob (Image * , const size_t , unsigned char *)
MagickExport int ReadBlobByte (Image *)
Definition at line 2923 of file blob.c.
References MagickSignature, ReadBlobStream(), and _Image::signature.
MagickExport double ReadBlobDouble (Image *)
Definition at line 2965 of file blob.c.
References ReadBlobLongLong().
MagickExport float ReadBlobFloat (Image *)
Definition at line 3004 of file blob.c.
References ReadBlobLong().
MagickExport unsigned int ReadBlobLong (Image *)
MagickExport MagickSizeType ReadBlobLongLong (Image *)
MagickExport unsigned int ReadBlobLSBLong (Image *)
MagickExport unsigned short ReadBlobLSBShort (Image *)
MagickExport unsigned int ReadBlobMSBLong (Image *)
Definition at line 3319 of file blob.c.
References MagickSignature, ReadBlobStream(), and _Image::signature.
MagickExport MagickSizeType ReadBlobMSBLongLong (Image *)
Definition at line 3369 of file blob.c.
References MagickSignature, MagickULLConstant, ReadBlobStream(), and _Image::signature.
MagickExport unsigned short ReadBlobMSBShort (Image *)
Definition at line 3423 of file blob.c.
References MagickSignature, ReadBlobStream(), and _Image::signature.
MagickExport unsigned short ReadBlobShort (Image *)
MagickExport char* ReadBlobString (Image * , char *)
Definition at line 3473 of file blob.c.
References MagickSignature, MaxTextExtent, ReadBlobStream(), and _Image::signature.
MagickExport BlobInfo * ReferenceBlob (BlobInfo *)
Definition at line 3531 of file blob.c.
References _BlobInfo::debug, GetMagickModule, LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, MagickSignature, _BlobInfo::reference_count, _BlobInfo::semaphore, _BlobInfo::signature, TraceEvent, and UnlockSemaphoreInfo().
Referenced by AcquireNextImage(), CloneImage(), DuplicateBlob(), and SyncNextImageInList().
MagickExport MagickOffsetType SeekBlob (Image * , const MagickOffsetType , const int)
MagickExport MagickOffsetType TellBlob (const Image *)
Definition at line 3934 of file blob.c.
References _Image::blob, BlobStream, BZipStream, _Image::debug, FifoStream, FileInfo::file, _BlobInfo::file_info, _Image::filename, FileStream, GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, _BlobInfo::offset, PipeStream, _Image::signature, StandardStream, TraceEvent, _BlobInfo::type, UndefinedStream, and ZipStream.
Referenced by SeekBlob().
MagickExport MagickBooleanType UnmapBlob (void * , const size_t)
Definition at line 4003 of file blob.c.
References MagickFalse, and MagickTrue.
Referenced by ConfigureFileToStringInfo(), DestroyBlob(), DestroyMagickMemory(), DestroyRadonInfo(), DetachBlob(), FileToBlob(), RelinquishCacheNexusPixels(), RelinquishPixelCachePixels(), RelinquishStreamPixels(), and SetBlobExtent().
MagickExport ssize_t WriteBlob (Image * , const size_t , const unsigned char *)
MagickExport ssize_t WriteBlobByte (Image * , const unsigned char)
MagickExport ssize_t WriteBlobFloat (Image * , const float)
MagickExport ssize_t WriteBlobLong (Image * , const unsigned int)
MagickExport ssize_t WriteBlobLSBLong (Image * , const unsigned int)
MagickExport ssize_t WriteBlobLSBShort (Image * , const unsigned short)
MagickExport ssize_t WriteBlobMSBLong (Image * , const unsigned int)
MagickExport ssize_t WriteBlobMSBLongLong (Image * , const MagickSizeType)
MagickExport ssize_t WriteBlobMSBShort (Image * , const unsigned short)
MagickExport ssize_t WriteBlobShort (Image * , const unsigned short)
MagickExport ssize_t WriteBlobString (Image * , const char *)
Definition at line 4567 of file blob.c.
References MagickSignature, _Image::signature, and WriteBlobStream().