MagickCore: blob-private.h File Reference
blob-private.h File Reference
#include "MagickCore/nt-feature.h"
Macros
#define MagickMinBlobExtent 32767L
Enumerations
enum StreamType {
UndefinedStream, StandardStream, FileStream, PipeStream,
ZipStream, BZipStream, FifoStream, BlobStream
}
Functions
MagickPrivate MagickBooleanType GetBlobError (const Image *)
MagickPrivate MagickBooleanType IsBlobExempt (const Image *)
MagickPrivate MagickBooleanType IsBlobSeekable (const Image *)
MagickPrivate MagickBooleanType IsBlobTemporary (const Image *)
MagickPrivate MagickBooleanType SetBlobExtent (Image *, const MagickSizeType)
MagickPrivate struct stat * GetBlobProperties (const Image *)
MagickPrivate StreamHandler GetBlobStreamHandler (const Image *)
MagickPrivate void GetBlobInfo (BlobInfo *)
MagickPrivate void SetBlobExempt (Image *, const MagickBooleanType)
Macro Definition Documentation
#define MagickMinBlobExtent 32767L
Definition at line 27 of file blob-private.h.
Enumeration Type Documentation
enum StreamType
Enumerator
UndefinedStream
StandardStream
FileStream
PipeStream
ZipStream
BZipStream
FifoStream
BlobStream
Definition at line 33 of file blob-private.h.
Function Documentation
MagickPrivate MagickBooleanType GetBlobError (const Image *)
Referenced by ReadImage(), and WriteImage().
MagickPrivate void GetBlobInfo (BlobInfo *)
Referenced by CloneBlobInfo().
MagickPrivate struct stat* GetBlobProperties (const Image *) read
Definition at line 1310 of file blob.c.
References _Image::blob, _Image::debug, _Image::filename, GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, _BlobInfo::properties, _Image::signature, and TraceEvent.
Referenced by ReadImage().
MagickPrivate StreamHandler GetBlobStreamHandler (const Image *)
Definition at line 1449 of file blob.c.
References _Image::blob, _Image::debug, _Image::filename, GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, _Image::signature, _BlobInfo::stream, and TraceEvent.
Referenced by QueueAuthenticPixelsStream(), and SyncAuthenticPixelsStream().
MagickPrivate MagickBooleanType IsBlobExempt (const Image *)
Referenced by SetImageInfo().
MagickPrivate MagickBooleanType IsBlobSeekable (const Image *)
Referenced by ReadImage(), SetImageInfo(), and WriteImage().
MagickPrivate MagickBooleanType IsBlobTemporary (const Image *)
Referenced by ReadImage().
MagickPrivate void SetBlobExempt (Image * , const MagickBooleanType)
Definition at line 3690 of file blob.c.
References _Image::blob, _Image::debug, _BlobInfo::exempt, _Image::filename, GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, _Image::signature, and TraceEvent.
Referenced by AcquireImage().
MagickPrivate MagickBooleanType SetBlobExtent (Image * , const MagickSizeType)
Definition at line 3725 of file blob.c.
References AcquireMagickResource(), _Image::blob, BlobStream, BZipStream, _BlobInfo::data, _Image::debug, DetachBlob(), _BlobInfo::extent, FifoStream, FileInfo::file, _BlobInfo::file_info, _Image::filename, FileStream, GetMagickModule, _BlobInfo::length, LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, MapBlob(), _BlobInfo::mapped, MapResource, PipeStream, RelinquishMagickResource(), ResizeQuantumMemory(), SeekBlob(), _Image::signature, StandardStream, SyncBlob(), _BlobInfo::synchronize, TraceEvent, _BlobInfo::type, UndefinedStream, UnmapBlob(), WriteMode, and ZipStream.
Referenced by WriteBlobStream().