MagickCore: blob.c File Reference
blob.c File Reference
#include "MagickCore/studio.h"
#include "MagickCore/nt-base-private.h"
#include "MagickCore/blob.h"
#include "MagickCore/blob-private.h"
#include "MagickCore/cache.h"
#include "MagickCore/client.h"
#include "MagickCore/constitute.h"
#include "MagickCore/delegate.h"
#include "MagickCore/exception.h"
#include "MagickCore/exception-private.h"
#include "MagickCore/image-private.h"
#include "MagickCore/list.h"
#include "MagickCore/locale_.h"
#include "MagickCore/log.h"
#include "MagickCore/magick.h"
#include "MagickCore/memory_.h"
#include "MagickCore/policy.h"
#include "MagickCore/resource_.h"
#include "MagickCore/semaphore.h"
#include "MagickCore/string_.h"
#include "MagickCore/string-private.h"
#include "MagickCore/token.h"
#include "MagickCore/utility.h"
#include "MagickCore/utility-private.h"
Data Structures
union FileInfo
struct _BlobInfo
Macros
#define MagickMaxBlobExtent 65541
#define MAP_FAILED ((void *) -1)
Typedefs
typedef union FileInfo FileInfo
Functions
static int SyncBlob (Image *)
MagickExport void AttachBlob (BlobInfo *blob_info, const void *blob, const size_t length)
static MagickSizeType MagickMin (const MagickSizeType x, const MagickSizeType y)
MagickExport MagickBooleanType BlobToFile (char *filename, const void *blob, const size_t length, ExceptionInfo *exception)
MagickExport Image * BlobToImage (const ImageInfo *image_info, const void *blob, const size_t length, ExceptionInfo *exception)
MagickExport BlobInfo * CloneBlobInfo (const BlobInfo *blob_info)
MagickExport MagickBooleanType CloseBlob (Image *image)
MagickExport void DestroyBlob (Image *image)
MagickExport unsigned char * DetachBlob (BlobInfo *blob_info)
static const unsigned char * ReadBlobStream (Image *image, const size_t length, unsigned char *data, ssize_t *count)
MagickExport MagickBooleanType DiscardBlobBytes (Image *image, const MagickSizeType length)
MagickExport void DuplicateBlob (Image *image, const Image *duplicate)
MagickExport int EOFBlob (const Image *image)
MagickExport unsigned char * FileToBlob (const char *filename, const size_t extent, size_t *length, ExceptionInfo *exception)
static ssize_t WriteBlobStream (Image *image, const size_t length, const unsigned char *data)
MagickExport MagickBooleanType FileToImage (Image *image, const char *filename, ExceptionInfo *exception)
MagickPrivate MagickBooleanType GetBlobError (const Image *image)
MagickExport FILE * GetBlobFileHandle (const Image *image)
MagickPrivate void GetBlobInfo (BlobInfo *blob_info)
MagickPrivate struct stat * GetBlobProperties (const Image *image)
MagickExport MagickSizeType GetBlobSize (const Image *image)
MagickExport unsigned char * GetBlobStreamData (const Image *image)
MagickPrivate StreamHandler GetBlobStreamHandler (const Image *image)
MagickExport unsigned char * ImageToBlob (const ImageInfo *image_info, Image *image, size_t *length, ExceptionInfo *exception)
MagickExport MagickBooleanType ImageToFile (Image *image, char *filename, ExceptionInfo *exception)
MagickExport unsigned char * ImagesToBlob (const ImageInfo *image_info, Image *images, size_t *length, ExceptionInfo *exception)
MagickExport MagickBooleanType InjectImageBlob (const ImageInfo *image_info, Image *image, Image *inject_image, const char *format, ExceptionInfo *exception)
MagickPrivate MagickBooleanType IsBlobExempt (const Image *image)
MagickPrivate MagickBooleanType IsBlobSeekable (const Image *image)
MagickPrivate MagickBooleanType IsBlobTemporary (const Image *image)
MagickExport unsigned char * MapBlob (int file, const MapMode mode, const MagickOffsetType offset, const size_t length)
MagickExport void MSBOrderLong (unsigned char *buffer, const size_t length)
MagickExport void MSBOrderShort (unsigned char *p, const size_t length)
MagickExport MagickBooleanType OpenBlob (const ImageInfo *image_info, Image *image, const BlobMode mode, ExceptionInfo *exception)
static size_t PingStream (const Image *magick_unused(image), const void *magick_unused(pixels), const size_t columns)
MagickExport Image * PingBlob (const ImageInfo *image_info, const void *blob, const size_t length, ExceptionInfo *exception)
MagickExport ssize_t ReadBlob (Image *image, const size_t length, unsigned char *data)
MagickExport int ReadBlobByte (Image *image)
MagickExport double ReadBlobDouble (Image *image)
MagickExport float ReadBlobFloat (Image *image)
MagickExport unsigned int ReadBlobLong (Image *image)
MagickExport MagickSizeType ReadBlobLongLong (Image *image)
MagickExport unsigned short ReadBlobShort (Image *image)
MagickExport unsigned int ReadBlobLSBLong (Image *image)
MagickExport unsigned short ReadBlobLSBShort (Image *image)
MagickExport unsigned int ReadBlobMSBLong (Image *image)
MagickExport MagickSizeType ReadBlobMSBLongLong (Image *image)
MagickExport unsigned short ReadBlobMSBShort (Image *image)
MagickExport char * ReadBlobString (Image *image, char *string)
MagickExport BlobInfo * ReferenceBlob (BlobInfo *blob)
MagickExport MagickOffsetType SeekBlob (Image *image, const MagickOffsetType offset, const int whence)
MagickPrivate void SetBlobExempt (Image *image, const MagickBooleanType exempt)
MagickPrivate MagickBooleanType SetBlobExtent (Image *image, const MagickSizeType extent)
MagickExport MagickOffsetType TellBlob (const Image *image)
MagickExport MagickBooleanType UnmapBlob (void *map, const size_t length)
MagickExport ssize_t WriteBlob (Image *image, const size_t length, const unsigned char *data)
MagickExport ssize_t WriteBlobByte (Image *image, const unsigned char value)
MagickExport ssize_t WriteBlobFloat (Image *image, const float value)
MagickExport ssize_t WriteBlobLong (Image *image, const unsigned int value)
MagickExport ssize_t WriteBlobShort (Image *image, const unsigned short value)
MagickExport ssize_t WriteBlobLSBLong (Image *image, const unsigned int value)
MagickExport ssize_t WriteBlobLSBShort (Image *image, const unsigned short value)
MagickExport ssize_t WriteBlobMSBLong (Image *image, const unsigned int value)
MagickExport ssize_t WriteBlobMSBLongLong (Image *image, const MagickSizeType value)
MagickExport ssize_t WriteBlobMSBShort (Image *image, const unsigned short value)
MagickExport ssize_t WriteBlobString (Image *image, const char *string)
Macro Definition Documentation
#define MagickMaxBlobExtent 65541
Definition at line 77 of file blob.c.
Referenced by AttachBlob(), GetBlobInfo(), ImagesToBlob(), and ImageToBlob().
#define MAP_FAILED ((void *) -1)
Definition at line 82 of file blob.c.
Referenced by MapBlob().
Typedef Documentation
typedef union FileInfo FileInfo
Function Documentation
MagickExport void AttachBlob (BlobInfo * blob_info, const void * blob, const size_t length)
Definition at line 192 of file blob.c.
References BlobStream, _BlobInfo::data, _BlobInfo::debug, _BlobInfo::extent, FileInfo::file, _BlobInfo::file_info, GetMagickModule, _BlobInfo::length, LogMagickEvent(), MagickFalse, MagickMaxBlobExtent, _BlobInfo::mapped, _BlobInfo::offset, _BlobInfo::quantum, TraceEvent, and _BlobInfo::type.
Referenced by OpenBlob().
MagickExport MagickBooleanType BlobToFile (char * filename, const void * blob, const size_t length, ExceptionInfo * exception)
Definition at line 247 of file blob.c.
References AcquireUniqueFileResource(), BlobError, GetMagickModule, LogMagickEvent(), MagickFalse, MagickMin(), MagickTrue, O_BINARY, open_utf8(), S_MODE, ThrowFileException, and TraceEvent.
Referenced by BlobToImage().
MagickExport Image* BlobToImage (const ImageInfo * image_info, const void * blob, const size_t length, ExceptionInfo * exception)
Definition at line 322 of file blob.c.
References _Image::blob, _ImageInfo::blob, BlobError, BlobToFile(), CloneImageInfo(), CopyMagickMemory(), CopyMagickString(), _ImageInfo::debug, DestroyImageInfo(), DetachBlob(), _Image::filename, _ImageInfo::filename, FormatLocaleString(), GetFirstImageInList(), GetMagickBlobSupport(), GetMagickInfo(), GetMagickModule, GetNextImageInList(), _ImageInfo::length, LogMagickEvent(), _ImageInfo::magick, _Image::magick_filename, MagickFalse, MagickSignature, MaxTextExtent, MissingDelegateError, ReadImage(), RelinquishUniqueFileResource(), SetImageInfo(), _ImageInfo::signature, ThrowMagickException(), and TraceEvent.
Referenced by ClipImagePath(), and ReadInlineImage().
MagickExport BlobInfo* CloneBlobInfo (const BlobInfo * blob_info)
Definition at line 442 of file blob.c.
References AcquireMagickMemory(), _BlobInfo::data, _BlobInfo::debug, _BlobInfo::eof, _BlobInfo::exempt, _BlobInfo::extent, FileInfo::file, _BlobInfo::file_info, GetBlobInfo(), IsEventLogging(), _BlobInfo::length, _BlobInfo::mapped, _BlobInfo::offset, _BlobInfo::properties, _BlobInfo::quantum, _BlobInfo::reference_count, ResourceLimitFatalError, _BlobInfo::size, _BlobInfo::status, _BlobInfo::stream, _BlobInfo::synchronize, _BlobInfo::temporary, ThrowFatalException, and _BlobInfo::type.
Referenced by AcquireImage(), CloneImage(), InjectImageBlob(), and WriteImages().
MagickExport MagickBooleanType CloseBlob (Image * image)
Definition at line 496 of file blob.c.
References _Image::blob, BlobStream, BZipStream, _Image::debug, DetachBlob(), _BlobInfo::eof, _BlobInfo::exempt, _Image::extent, FifoStream, FileInfo::file, _BlobInfo::file_info, _Image::filename, FileStream, GetBlobSize(), GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, PipeStream, _Image::signature, _BlobInfo::size, StandardStream, _BlobInfo::status, SyncBlob(), _BlobInfo::synchronize, TraceEvent, _BlobInfo::type, UndefinedStream, and ZipStream.
Referenced by DestroyBlob(), DestroyStreamInfo(), ImageToBlob(), ReadImage(), SetImageInfo(), and WriteImage().
MagickExport void DestroyBlob (Image * image)
Definition at line 628 of file blob.c.
References _Image::blob, CloseBlob(), _BlobInfo::data, _Image::debug, DestroySemaphoreInfo(), _Image::filename, GetMagickModule, _BlobInfo::length, LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, _BlobInfo::mapped, MapResource, _BlobInfo::reference_count, RelinquishMagickMemory(), RelinquishMagickResource(), _BlobInfo::semaphore, _BlobInfo::signature, _Image::signature, TraceEvent, UnlockSemaphoreInfo(), and UnmapBlob().
Referenced by AcquireNextImage(), DestroyImage(), DuplicateBlob(), InjectImageBlob(), SyncNextImageInList(), and WriteImages().
MagickExport unsigned char* DetachBlob (BlobInfo * blob_info)
Definition at line 682 of file blob.c.
References _BlobInfo::data, _BlobInfo::debug, _BlobInfo::eof, _BlobInfo::exempt, FileInfo::file, _BlobInfo::file_info, GetMagickModule, _BlobInfo::length, LogMagickEvent(), MagickFalse, _BlobInfo::mapped, MapResource, _BlobInfo::offset, RelinquishMagickResource(), _BlobInfo::stream, TraceEvent, _BlobInfo::type, UndefinedStream, and UnmapBlob().
Referenced by BlobToImage(), CloseBlob(), DisassociateImageStream(), ImagesToBlob(), ImageToBlob(), OpenBlob(), SeekBlob(), SetBlobExtent(), and WriteBlob().
MagickExport MagickBooleanType DiscardBlobBytes (Image * image, const MagickSizeType length)
Definition at line 758 of file blob.c.
References MagickFalse, MagickMin(), MagickSignature, MagickTrue, ReadBlobStream(), and _Image::signature.
MagickExport void DuplicateBlob (Image * image, const Image * duplicate)
Definition at line 814 of file blob.c.
References _Image::blob, _Image::debug, DestroyBlob(), _Image::filename, GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, ReferenceBlob(), _Image::signature, and TraceEvent.
MagickExport int EOFBlob (const Image * image)
Definition at line 849 of file blob.c.
References _Image::blob, BlobStream, BZipStream, _Image::debug, _BlobInfo::eof, FifoStream, FileInfo::file, _BlobInfo::file_info, FileStream, GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, PipeStream, _Image::signature, StandardStream, TraceEvent, _BlobInfo::type, UndefinedStream, and ZipStream.
MagickExport unsigned char* FileToBlob (const char * filename, const size_t extent, size_t * length, ExceptionInfo * exception)
Definition at line 932 of file blob.c.
References AcquireQuantumMemory(), BlobError, GetMagickModule, LocaleCompare(), LogMagickEvent(), MagickMaxBufferExtent, MagickMin(), MapBlob(), MaxTextExtent, O_BINARY, open_utf8(), ReadMode, RelinquishMagickMemory(), ResizeQuantumMemory(), ResourceLimitError, ThrowFileException, ThrowMagickException(), TraceEvent, and UnmapBlob().
Referenced by FileToString(), FileToStringInfo(), ImagesToBlob(), and ImageToBlob().
MagickExport MagickBooleanType FileToImage (Image * image, const char * filename, ExceptionInfo * exception)
Definition at line 1126 of file blob.c.
References AcquireQuantumMemory(), BlobError, GetMagickModule, LocaleCompare(), LogMagickEvent(), MagickFalse, MagickMaxBufferExtent, MagickMin(), MagickSignature, MagickTrue, O_BINARY, open_utf8(), RelinquishMagickMemory(), ResourceLimitError, _Image::signature, ThrowFileException, TraceEvent, and WriteBlobStream().
MagickPrivate MagickBooleanType GetBlobError (const Image * image)
Definition at line 1214 of file blob.c.
References _Image::blob, _Image::debug, _Image::filename, GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, _Image::signature, _BlobInfo::status, and TraceEvent.
MagickExport FILE* GetBlobFileHandle (const Image * image)
Definition at line 1245 of file blob.c.
References _Image::blob, FileInfo::file, _BlobInfo::file_info, MagickSignature, and _Image::signature.
MagickPrivate void GetBlobInfo (BlobInfo * blob_info)
Definition at line 1274 of file blob.c.
References AllocateSemaphoreInfo(), _BlobInfo::debug, IsEventLogging(), MagickMaxBlobExtent, MagickSignature, _BlobInfo::properties, _BlobInfo::quantum, _BlobInfo::reference_count, ResetMagickMemory(), _BlobInfo::semaphore, _BlobInfo::signature, _BlobInfo::type, and UndefinedStream.
MagickPrivate struct stat* GetBlobProperties (const Image * image) read
Definition at line 1310 of file blob.c.
References _Image::blob, _Image::debug, _Image::filename, GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, _BlobInfo::properties, _Image::signature, and TraceEvent.
Referenced by ReadImage().
MagickExport MagickSizeType GetBlobSize (const Image * image)
Definition at line 1342 of file blob.c.
References _Image::blob, BlobStream, BZipStream, _Image::debug, FifoStream, FileInfo::file, _BlobInfo::file_info, _Image::filename, FileStream, GetMagickModule, GetPathAttributes(), _BlobInfo::length, LogMagickEvent(), MagickFalse, MagickSignature, PipeStream, _BlobInfo::properties, _Image::signature, _BlobInfo::size, StandardStream, TraceEvent, _BlobInfo::type, UndefinedStream, and ZipStream.
Referenced by CloseBlob(), GetMagickProperty(), IdentifyImage(), OpenBlob(), PreviewImage(), and ThumbnailImage().
MagickExport unsigned char* GetBlobStreamData (const Image * image)
Definition at line 1420 of file blob.c.
References _Image::blob, _BlobInfo::data, MagickSignature, and _Image::signature.
MagickPrivate StreamHandler GetBlobStreamHandler (const Image * image)
Definition at line 1449 of file blob.c.
References _Image::blob, _Image::debug, _Image::filename, GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, _Image::signature, _BlobInfo::stream, and TraceEvent.
Referenced by QueueAuthenticPixelsStream(), and SyncAuthenticPixelsStream().
MagickExport unsigned char* ImagesToBlob (const ImageInfo * image_info, Image * images, size_t * length, ExceptionInfo * exception)
Definition at line 1742 of file blob.c.
References AcquireQuantumMemory(), AcquireUniqueFileResource(), _ImageInfo::adjoin, _Image::blob, _ImageInfo::blob, CloneImageInfo(), CopyMagickString(), _ImageInfo::debug, DestroyImageInfo(), DetachBlob(), _BlobInfo::exempt, _ImageInfo::file, _Image::filename, _ImageInfo::filename, FileOpenError, FileToBlob(), FormatLocaleString(), GetImageListLength(), GetMagickBlobSupport(), GetMagickInfo(), GetMagickModule, ImageToBlob(), _BlobInfo::length, _ImageInfo::length, LogMagickEvent(), _Image::magick, _ImageInfo::magick, MagickFalse, MagickMaxBlobExtent, MagickSignature, MagickTrue, MaxTextExtent, MissingDelegateError, RelinquishUniqueFileResource(), ResizeQuantumMemory(), ResourceLimitError, SetImageInfo(), _Image::signature, _ImageInfo::signature, ThrowFileException, ThrowMagickException(), TraceEvent, and WriteImages().
MagickExport unsigned char* ImageToBlob (const ImageInfo * image_info, Image * image, size_t * length, ExceptionInfo * exception)
Definition at line 1492 of file blob.c.
References AcquireQuantumMemory(), AcquireUniqueFileResource(), _ImageInfo::adjoin, _Image::blob, _ImageInfo::blob, BlobError, CloneImageInfo(), CloseBlob(), CopyMagickString(), _ImageInfo::debug, DestroyImageInfo(), DetachBlob(), _BlobInfo::exempt, _ImageInfo::file, _Image::filename, _ImageInfo::filename, FileToBlob(), FormatLocaleString(), GetMagickBlobSupport(), GetMagickInfo(), GetMagickModule, _BlobInfo::length, _ImageInfo::length, LogMagickEvent(), _Image::magick, _ImageInfo::magick, MagickFalse, MagickMaxBlobExtent, MagickSignature, MagickTrue, MaxTextExtent, MissingDelegateError, RelinquishMagickMemory(), RelinquishUniqueFileResource(), ResizeQuantumMemory(), ResourceLimitError, SetImageInfo(), _Image::signature, _ImageInfo::signature, ThrowFileException, ThrowMagickException(), TraceEvent, and WriteImage().
Referenced by ImagesToBlob().
MagickExport MagickBooleanType ImageToFile (Image * image, char * filename, ExceptionInfo * exception)
Definition at line 1621 of file blob.c.
References AcquireQuantumMemory(), AcquireUniqueFileResource(), _Image::blob, BlobError, _Image::debug, GetMagickModule, LocaleCompare(), LogMagickEvent(), MagickFalse, MagickMaxBufferExtent, MagickMin(), MagickSignature, MagickTrue, O_BINARY, open_utf8(), ReadBlobStream(), RelinquishMagickMemory(), ResourceLimitError, S_MODE, _Image::signature, ThrowFileException, ThrowMagickException(), TraceEvent, _BlobInfo::type, and UndefinedStream.
Referenced by ReadImage(), SetImageInfo(), and WriteImage().
MagickExport MagickBooleanType InjectImageBlob (const ImageInfo * image_info, Image * image, Image * inject_image, const char * format, ExceptionInfo * exception)
Definition at line 1880 of file blob.c.
References AcquireQuantumMemory(), AcquireUniqueFileResource(), _Image::blob, CloneBlobInfo(), CloneImage(), CloneImageInfo(), CopyMagickString(), _Image::debug, DestroyBlob(), DestroyImage(), DestroyImageInfo(), _Image::filename, _ImageInfo::filename, FileOpenError, FormatLocaleString(), GetMagickModule, LogMagickEvent(), MagickFalse, MagickMaxBufferExtent, MagickMin(), MagickSignature, MagickTrue, MaxTextExtent, O_BINARY, open_utf8(), RelinquishMagickMemory(), RelinquishUniqueFileResource(), ResourceLimitError, SetImageInfoFile(), _Image::signature, _ImageInfo::signature, ThrowBinaryException, ThrowFileException, TraceEvent, WriteBlobStream(), and WriteImage().
MagickPrivate MagickBooleanType IsBlobExempt (const Image * image)
Definition at line 2024 of file blob.c.
References _Image::blob, _Image::debug, _BlobInfo::exempt, _Image::filename, GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, _Image::signature, and TraceEvent.
MagickPrivate MagickBooleanType IsBlobSeekable (const Image * image)
Definition at line 2055 of file blob.c.
References _Image::blob, BlobStream, _Image::debug, _Image::filename, FileStream, GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, _Image::signature, TraceEvent, _BlobInfo::type, and ZipStream.
MagickPrivate MagickBooleanType IsBlobTemporary (const Image * image)
Definition at line 2104 of file blob.c.
References _Image::blob, _Image::debug, _Image::filename, GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, _Image::signature, _BlobInfo::temporary, and TraceEvent.
static MagickSizeType MagickMin (const MagickSizeType x, const MagickSizeType y) inline static
Definition at line 239 of file blob.c.
Referenced by BlobToFile(), DiscardBlobBytes(), FileToBlob(), FileToImage(), ImageToFile(), InjectImageBlob(), ReadBlob(), and ReadBlobStream().
MagickExport unsigned char* MapBlob (int file, const MapMode mode, const MagickOffsetType offset, const size_t length)
Definition at line 2142 of file blob.c.
References IOMode, MAP_FAILED, ReadMode, and WriteMode.
Referenced by AcquireCacheNexusPixels(), AcquireRadonInfo(), AcquireStreamPixels(), AllocatePixelCachePixels(), ConfigureFileToStringInfo(), FileToBlob(), OpenBlob(), OpenPixelCache(), and SetBlobExtent().
MagickExport void MSBOrderLong (unsigned char * buffer, const size_t length)
Definition at line 2235 of file blob.c.
MagickExport void MSBOrderShort (unsigned char * p, const size_t length)
Definition at line 2285 of file blob.c.
MagickExport MagickBooleanType OpenBlob (const ImageInfo * image_info, Image * image, const BlobMode mode, ExceptionInfo * exception)
Definition at line 2335 of file blob.c.
References AcquireExceptionInfo(), AcquireMagickResource(), _ImageInfo::adjoin, AppendBinaryBlobMode, AppendBlobMode, AttachBlob(), _Image::blob, _ImageInfo::blob, BlobError, BlobEvent, BZipStream, CopyMagickString(), _ImageInfo::debug, DestroyExceptionInfo(), DetachBlob(), _BlobInfo::exempt, ExtensionPath, FifoStream, FileInfo::file, _ImageInfo::file, _BlobInfo::file_info, _Image::filename, _ImageInfo::filename, FileStream, fopen_utf8(), FormatLocaleString(), GetBlobSize(), GetMagickBlobSupport(), GetMagickInfo(), GetMagickModule, GetNextImageInList(), GetPathAttributes(), GetPathComponent(), GetPreviousImageInList(), InterpretImageFilename(), IsRightsAuthorized(), _ImageInfo::length, LocaleCompare(), LocaleNCompare(), LogMagickEvent(), _ImageInfo::magick, MagickFalse, MagickMaxBufferExtent, MagickSignature, MagickTrue, MapBlob(), _BlobInfo::mapped, MapResource, MaxTextExtent, PathPolicyDomain, PipeStream, PolicyError, popen_utf8(), _BlobInfo::properties, ReadBinaryBlobMode, ReadBlobMode, ReadMode, ReadPolicyRights, RelinquishMagickResource(), ResetMagickMemory(), RootPath, _Image::scene, SetApplicationType(), _Image::signature, _ImageInfo::signature, _BlobInfo::size, StandardStream, _BlobInfo::status, _BlobInfo::stream, _ImageInfo::stream, StringToLong(), _BlobInfo::synchronize, _ImageInfo::synchronize, ThrowFileException, ThrowMagickException(), TraceEvent, _BlobInfo::type, UndefinedStream, WriteBinaryBlobMode, WriteBlobMode, WritePolicyRights, and ZipStream.
Referenced by OpenStream(), ReadImage(), SetImageInfo(), and WriteImage().
MagickExport Image* PingBlob (const ImageInfo * image_info, const void * blob, const size_t length, ExceptionInfo * exception)
Definition at line 2692 of file blob.c.
References AcquireQuantumMemory(), _ImageInfo::blob, BlobError, CloneImageInfo(), _ImageInfo::debug, DestroyImageInfo(), _ImageInfo::filename, GetMagickModule, _ImageInfo::length, LogMagickEvent(), _ImageInfo::magick, MagickFalse, MagickSignature, MagickTrue, _ImageInfo::ping, PingStream(), ReadStream(), RelinquishMagickMemory(), ResourceLimitFatalError, _ImageInfo::signature, ThrowMagickException(), and TraceEvent.
static size_t PingStream (const Image * magick_unusedimage, const void * magick_unusedpixels, const size_t columns) static
Definition at line 2682 of file blob.c.
Referenced by PingBlob().
MagickExport ssize_t ReadBlob (Image * image, const size_t length, unsigned char * data)
Definition at line 2761 of file blob.c.
References _Image::blob, BlobStream, BZipStream, _BlobInfo::data, _BlobInfo::eof, FifoStream, FileInfo::file, _BlobInfo::file_info, FileStream, _BlobInfo::length, MagickMin(), MagickSignature, MagickTrue, _BlobInfo::offset, PipeStream, _Image::signature, StandardStream, _BlobInfo::type, UndefinedStream, and ZipStream.
Referenced by ReadBlobStream(), and SetImageInfo().
MagickExport int ReadBlobByte (Image * image)
Definition at line 2923 of file blob.c.
References MagickSignature, ReadBlobStream(), and _Image::signature.
MagickExport double ReadBlobDouble (Image * image)
Definition at line 2965 of file blob.c.
References ReadBlobLongLong().
MagickExport float ReadBlobFloat (Image * image)
Definition at line 3004 of file blob.c.
References ReadBlobLong().
MagickExport unsigned int ReadBlobLong (Image * image)
Definition at line 3043 of file blob.c.
References _Image::endian, LSBEndian, MagickSignature, ReadBlobStream(), and _Image::signature.
Referenced by ReadBlobFloat().
MagickExport MagickSizeType ReadBlobLongLong (Image * image)
Definition at line 3101 of file blob.c.
References _Image::endian, LSBEndian, MagickSignature, MagickULLConstant, ReadBlobStream(), and _Image::signature.
Referenced by ReadBlobDouble().
MagickExport unsigned int ReadBlobLSBLong (Image * image)
Definition at line 3221 of file blob.c.
References MagickSignature, ReadBlobStream(), and _Image::signature.
MagickExport unsigned short ReadBlobLSBShort (Image * image)
Definition at line 3271 of file blob.c.
References MagickSignature, ReadBlobStream(), and _Image::signature.
MagickExport unsigned int ReadBlobMSBLong (Image * image)
Definition at line 3319 of file blob.c.
References MagickSignature, ReadBlobStream(), and _Image::signature.
MagickExport MagickSizeType ReadBlobMSBLongLong (Image * image)
Definition at line 3369 of file blob.c.
References MagickSignature, MagickULLConstant, ReadBlobStream(), and _Image::signature.
MagickExport unsigned short ReadBlobMSBShort (Image * image)
Definition at line 3423 of file blob.c.
References MagickSignature, ReadBlobStream(), and _Image::signature.
MagickExport unsigned short ReadBlobShort (Image * image)
Definition at line 3167 of file blob.c.
References _Image::endian, LSBEndian, MagickSignature, ReadBlobStream(), and _Image::signature.
static const unsigned char* ReadBlobStream (Image * image, const size_t length, unsigned char * data, ssize_t * count) inline static
Definition at line 733 of file blob.c.
References _Image::blob, BlobStream, _BlobInfo::data, _BlobInfo::eof, _BlobInfo::length, MagickMin(), MagickTrue, _BlobInfo::offset, ReadBlob(), and _BlobInfo::type.
Referenced by DiscardBlobBytes(), ImageToFile(), ReadBlobByte(), ReadBlobLong(), ReadBlobLongLong(), ReadBlobLSBLong(), ReadBlobLSBShort(), ReadBlobMSBLong(), ReadBlobMSBLongLong(), ReadBlobMSBShort(), ReadBlobShort(), and ReadBlobString().
MagickExport char* ReadBlobString (Image * image, char * string)
Definition at line 3473 of file blob.c.
References MagickSignature, MaxTextExtent, ReadBlobStream(), and _Image::signature.
MagickExport BlobInfo* ReferenceBlob (BlobInfo * blob)
Definition at line 3531 of file blob.c.
References _BlobInfo::debug, GetMagickModule, LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, MagickSignature, _BlobInfo::reference_count, _BlobInfo::semaphore, _BlobInfo::signature, TraceEvent, and UnlockSemaphoreInfo().
Referenced by AcquireNextImage(), CloneImage(), DuplicateBlob(), and SyncNextImageInList().
MagickExport MagickOffsetType SeekBlob (Image * image, const MagickOffsetType offset, const int whence)
Definition at line 3576 of file blob.c.
References _Image::blob, BlobStream, BZipStream, _BlobInfo::data, _Image::debug, DetachBlob(), _BlobInfo::eof, _BlobInfo::extent, FifoStream, FileInfo::file, _BlobInfo::file_info, _Image::filename, FileStream, GetMagickModule, _BlobInfo::length, LogMagickEvent(), MagickFalse, MagickSignature, _BlobInfo::mapped, _BlobInfo::offset, PipeStream, _BlobInfo::quantum, ResizeQuantumMemory(), _Image::signature, StandardStream, SyncBlob(), TellBlob(), TraceEvent, _BlobInfo::type, UndefinedStream, and ZipStream.
Referenced by SetBlobExtent(), and SetImageInfo().
MagickPrivate void SetBlobExempt (Image * image, const MagickBooleanType exempt)
Definition at line 3690 of file blob.c.
References _Image::blob, _Image::debug, _BlobInfo::exempt, _Image::filename, GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, _Image::signature, and TraceEvent.
Referenced by AcquireImage().
MagickPrivate MagickBooleanType SetBlobExtent (Image * image, const MagickSizeType extent)
Definition at line 3725 of file blob.c.
References AcquireMagickResource(), _Image::blob, BlobStream, BZipStream, _BlobInfo::data, _Image::debug, DetachBlob(), _BlobInfo::extent, FifoStream, FileInfo::file, _BlobInfo::file_info, _Image::filename, FileStream, GetMagickModule, _BlobInfo::length, LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, MapBlob(), _BlobInfo::mapped, MapResource, PipeStream, RelinquishMagickResource(), ResizeQuantumMemory(), SeekBlob(), _Image::signature, StandardStream, SyncBlob(), _BlobInfo::synchronize, TraceEvent, _BlobInfo::type, UndefinedStream, UnmapBlob(), WriteMode, and ZipStream.
Referenced by WriteBlobStream().
static int SyncBlob (Image * image) static
Definition at line 3867 of file blob.c.
References _Image::blob, BlobStream, BZipStream, _Image::debug, FifoStream, FileInfo::file, _BlobInfo::file_info, _Image::filename, FileStream, GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, PipeStream, _Image::signature, StandardStream, TraceEvent, _BlobInfo::type, UndefinedStream, and ZipStream.
Referenced by CloseBlob(), SeekBlob(), SetBlobExtent(), and WriteBlob().
MagickExport MagickOffsetType TellBlob (const Image * image)
Definition at line 3934 of file blob.c.
References _Image::blob, BlobStream, BZipStream, _Image::debug, FifoStream, FileInfo::file, _BlobInfo::file_info, _Image::filename, FileStream, GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, _BlobInfo::offset, PipeStream, _Image::signature, StandardStream, TraceEvent, _BlobInfo::type, UndefinedStream, and ZipStream.
Referenced by SeekBlob().
MagickExport MagickBooleanType UnmapBlob (void * map, const size_t length)
Definition at line 4003 of file blob.c.
References MagickFalse, and MagickTrue.
Referenced by ConfigureFileToStringInfo(), DestroyBlob(), DestroyMagickMemory(), DestroyRadonInfo(), DetachBlob(), FileToBlob(), RelinquishCacheNexusPixels(), RelinquishPixelCachePixels(), RelinquishStreamPixels(), and SetBlobExtent().
MagickExport ssize_t WriteBlob (Image * image, const size_t length, const unsigned char * data)
Definition at line 4047 of file blob.c.
References _Image::blob, BlobStream, BZipStream, _BlobInfo::data, DetachBlob(), _BlobInfo::extent, FifoStream, FileInfo::file, _BlobInfo::file_info, FileStream, _BlobInfo::length, MagickFalse, MagickSignature, _BlobInfo::mapped, _BlobInfo::offset, PipeStream, _BlobInfo::quantum, ResizeQuantumMemory(), _Image::signature, StandardStream, _BlobInfo::stream, SyncBlob(), _BlobInfo::type, UndefinedStream, and ZipStream.
Referenced by Ascii85Flush(), WriteBlobStream(), and WriteStreamImage().
MagickExport ssize_t WriteBlobByte (Image * image, const unsigned char value)
Definition at line 4208 of file blob.c.
References MagickSignature, _Image::signature, and WriteBlobStream().
Referenced by Ascii85Encode(), Ascii85Flush(), HuffmanEncodeImage(), LZWEncodeImage(), and PackbitsEncodeImage().
MagickExport ssize_t WriteBlobFloat (Image * image, const float value)
Definition at line 4240 of file blob.c.
References WriteBlobLong().
MagickExport ssize_t WriteBlobLong (Image * image, const unsigned int value)
Definition at line 4281 of file blob.c.
References _Image::endian, LSBEndian, MagickSignature, _Image::signature, and WriteBlobStream().
Referenced by WriteBlobFloat().
MagickExport ssize_t WriteBlobLSBLong (Image * image, const unsigned int value)
Definition at line 4371 of file blob.c.
References MagickSignature, _Image::signature, and WriteBlobStream().
MagickExport ssize_t WriteBlobLSBShort (Image * image, const unsigned short value)
Definition at line 4410 of file blob.c.
References MagickSignature, _Image::signature, and WriteBlobStream().
MagickExport ssize_t WriteBlobMSBLong (Image * image, const unsigned int value)
Definition at line 4447 of file blob.c.
References MagickSignature, _Image::signature, and WriteBlobStream().
MagickExport ssize_t WriteBlobMSBLongLong (Image * image, const MagickSizeType value)
Definition at line 4486 of file blob.c.
References MagickSignature, _Image::signature, and WriteBlobStream().
MagickExport ssize_t WriteBlobMSBShort (Image * image, const unsigned short value)
Definition at line 4530 of file blob.c.
References MagickSignature, _Image::signature, and WriteBlobStream().
MagickExport ssize_t WriteBlobShort (Image * image, const unsigned short value)
Definition at line 4328 of file blob.c.
References _Image::endian, LSBEndian, MagickSignature, _Image::signature, and WriteBlobStream().
static ssize_t WriteBlobStream (Image * image, const size_t length, const unsigned char * data) inline static
Definition at line 1096 of file blob.c.
References _Image::blob, BlobStream, _BlobInfo::data, _BlobInfo::extent, _BlobInfo::length, MagickFalse, _BlobInfo::offset, _BlobInfo::quantum, SetBlobExtent(), _BlobInfo::type, UndefinedStream, and WriteBlob().
Referenced by FileToImage(), InjectImageBlob(), WriteBlobByte(), WriteBlobLong(), WriteBlobLSBLong(), WriteBlobLSBShort(), WriteBlobMSBLong(), WriteBlobMSBLongLong(), WriteBlobMSBShort(), WriteBlobShort(), and WriteBlobString().
MagickExport ssize_t WriteBlobString (Image * image, const char * string)
Definition at line 4567 of file blob.c.
References MagickSignature, _Image::signature, and WriteBlobStream().