MagickCore: cache-private.h File Reference
cache-private.h File Reference
#include <time.h>
#include "MagickCore/cache.h"
#include "MagickCore/distribute-cache.h"
#include "MagickCore/pixel.h"
#include "MagickCore/random_.h"
#include "MagickCore/thread-private.h"
#include "MagickCore/semaphore.h"
Data Structures
struct _CacheMethods
struct _NexusInfo
struct _CacheInfo
Typedefs
typedef void * Cache
typedef MagickBooleanType(* GetOneAuthenticPixelFromHandler)(Image *, const ssize_t, const ssize_t, Quantum *, ExceptionInfo *)
typedef MagickBooleanType(*)(* GetOneVirtualPixelFromHandler)(const Image *, const VirtualPixelMethod, const ssize_t, const ssize_t, Quantum *, ExceptionInfo *)
typedef MagickBooleanType(*)(*)(* SyncAuthenticPixelsHandler)(Image *, ExceptionInfo *)
typedef const Quantum *(* GetVirtualPixelHandler)(const Image *, const VirtualPixelMethod, const ssize_t, const ssize_t, const size_t, const size_t, ExceptionInfo *)
typedef const Quantum *(*)*(* GetVirtualPixelsHandler)(const Image *)
typedef const void *(* GetVirtualMetacontentFromHandler)(const Image *)
typedef Quantum *(* GetAuthenticPixelsHandler)(Image *, const ssize_t, const ssize_t, const size_t, const size_t, ExceptionInfo *)
typedef Quantum *(* GetAuthenticPixelsFromHandler)(const Image *)
typedef Quantum *(* QueueAuthenticPixelsHandler)(Image *, const ssize_t, const ssize_t, const size_t, const size_t, ExceptionInfo *)
typedef void(* DestroyPixelHandler)(Image *)
typedef void *(* GetAuthenticMetacontentFromHandler)(const Image *)
typedef struct _CacheMethods CacheMethods
typedef struct _NexusInfo NexusInfo
typedef struct _CacheInfo CacheInfo
Functions
MagickPrivate Cache AcquirePixelCache (const size_t)
MagickPrivate Cache ClonePixelCache (const Cache)
MagickPrivate Cache DestroyPixelCache (Cache)
MagickPrivate Cache ReferencePixelCache (Cache)
MagickPrivate ClassType GetPixelCacheStorageClass (const Cache)
MagickPrivate ColorspaceType GetPixelCacheColorspace (const Cache)
MagickPrivate const Quantum * GetVirtualPixelsFromNexus (const Image *, const VirtualPixelMethod, const ssize_t, const ssize_t, const size_t, const size_t, NexusInfo *, ExceptionInfo *) magick_hot_spot
MagickPrivate const Quantum * GetVirtualPixelsNexus (const Cache, NexusInfo *)
MagickPrivate const void * AcquirePixelCachePixels (const Image *, MagickSizeType *, ExceptionInfo *)
MagickPrivate const void * GetVirtualMetacontentFromNexus (const Cache, NexusInfo *)
MagickPrivate MagickBooleanType CacheComponentGenesis (void)
MagickPrivate MagickBooleanType SyncAuthenticPixelCacheNexus (Image *, NexusInfo *, ExceptionInfo *) magick_hot_spot
MagickPrivate MagickBooleanType SyncImagePixelCache (Image *, ExceptionInfo *)
MagickPrivate MagickSizeType GetPixelCacheNexusExtent (const Cache, NexusInfo *)
MagickPrivate NexusInfo ** AcquirePixelCacheNexus (const size_t)
MagickPrivate NexusInfo ** DestroyPixelCacheNexus (NexusInfo **, const size_t)
MagickPrivate Quantum * GetAuthenticPixelCacheNexus (Image *, const ssize_t, const ssize_t, const size_t, const size_t, NexusInfo *, ExceptionInfo *) magick_hot_spot
MagickPrivate Quantum * QueueAuthenticPixelCacheNexus (Image *, const ssize_t, const ssize_t, const size_t, const size_t, const MagickBooleanType, NexusInfo *, ExceptionInfo *) magick_hot_spot
MagickPrivate size_t GetPixelCacheChannels (const Cache)
MagickPrivate VirtualPixelMethod GetPixelCacheVirtualMethod (const Image *)
MagickPrivate VirtualPixelMethod SetPixelCacheVirtualMethod (Image *, const VirtualPixelMethod, ExceptionInfo *)
MagickPrivate void CacheComponentTerminus (void)
MagickPrivate void ClonePixelCacheMethods (Cache, const Cache)
MagickPrivate void * GetPixelCachePixels (Image *, MagickSizeType *, ExceptionInfo *)
MagickPrivate void GetPixelCacheTileSize (const Image *, size_t *, size_t *)
MagickPrivate void GetPixelCacheMethods (CacheMethods *)
MagickPrivate void SetPixelCacheMethods (Cache, CacheMethods *)
Typedef Documentation
typedef void* Cache
Definition at line 34 of file cache-private.h.
typedef struct _CacheInfo CacheInfo
typedef struct _CacheMethods CacheMethods
typedef void(* DestroyPixelHandler)(Image *)
Definition at line 63 of file cache-private.h.
typedef void*(* GetAuthenticMetacontentFromHandler)(const Image *)
Definition at line 66 of file cache-private.h.
typedef Quantum*(* GetAuthenticPixelsFromHandler)(const Image *)
Definition at line 56 of file cache-private.h.
typedef Quantum*(* GetAuthenticPixelsHandler)(Image *, const ssize_t, const ssize_t, const size_t, const size_t, ExceptionInfo *)
Definition at line 52 of file cache-private.h.
typedef MagickBooleanType(* GetOneAuthenticPixelFromHandler)(Image *, const ssize_t, const ssize_t, Quantum *, ExceptionInfo *)
Definition at line 37 of file cache-private.h.
typedef MagickBooleanType(*)(* GetOneVirtualPixelFromHandler)(const Image *, const VirtualPixelMethod, const ssize_t, const ssize_t, Quantum *, ExceptionInfo *)
Definition at line 39 of file cache-private.h.
typedef const void*(* GetVirtualMetacontentFromHandler)(const Image *)
Definition at line 49 of file cache-private.h.
typedef const Quantum*(* GetVirtualPixelHandler)(const Image *, const VirtualPixelMethod, const ssize_t, const ssize_t, const size_t, const size_t, ExceptionInfo *)
Definition at line 44 of file cache-private.h.
typedef const Quantum*(*) *(* GetVirtualPixelsHandler)(const Image *)
Definition at line 46 of file cache-private.h.
typedef struct _NexusInfo NexusInfo
typedef Quantum*(* QueueAuthenticPixelsHandler)(Image *, const ssize_t, const ssize_t, const size_t, const size_t, ExceptionInfo *)
Definition at line 59 of file cache-private.h.
typedef MagickBooleanType(*)(*)(* SyncAuthenticPixelsHandler)(Image *, ExceptionInfo *)
Definition at line 41 of file cache-private.h.
Function Documentation
MagickPrivate Cache AcquirePixelCache (const size_t)
Referenced by AcquireImage(), ClonePixelCache(), and ReadStream().
MagickPrivate NexusInfo** AcquirePixelCacheNexus (const size_t)
Referenced by AcquireVirtualCacheView(), CloneCacheView(), ClonePixelCacheRepository(), and GetVirtualPixelsFromNexus().
MagickPrivate const void* AcquirePixelCachePixels (const Image * , MagickSizeType * , ExceptionInfo *)
Referenced by AccelerateConvolveImage().
MagickPrivate MagickBooleanType CacheComponentGenesis (void)
Referenced by MagickCoreGenesis().
MagickPrivate void CacheComponentTerminus (void)
Referenced by MagickCoreTerminus().
MagickPrivate Cache ClonePixelCache (const Cache)
Referenced by CloneImage(), and PersistPixelCache().
MagickPrivate void ClonePixelCacheMethods (Cache , const Cache)
Referenced by AcquireImage().
MagickPrivate Cache DestroyPixelCache (Cache)
Referenced by DestroyImageInfo(), DestroyImagePixelCache(), DestroyImagePixels(), and PersistPixelCache().
MagickPrivate NexusInfo ** DestroyPixelCacheNexus (NexusInfo ** , const size_t)
Definition at line 938 of file cache.c.
References MagickSignature, RelinquishAlignedMemory(), RelinquishCacheNexusPixels(), RelinquishMagickMemory(), and _NexusInfo::signature.
Referenced by ClonePixelCacheRepository(), DestroyCacheView(), DestroyPixelCache(), DestroyPixelStream(), and GetVirtualPixelsFromNexus().
MagickPrivate Quantum* GetAuthenticPixelCacheNexus (Image * , const ssize_t , const ssize_t , const size_t , const size_t , NexusInfo * , ExceptionInfo *)
Referenced by GetAuthenticPixels(), GetAuthenticPixelsCache(), GetCacheViewAuthenticPixels(), GetOneAuthenticPixelFromCache(), and GetOneCacheViewAuthenticPixel().
MagickPrivate size_t GetPixelCacheChannels (const Cache)
MagickPrivate ColorspaceType GetPixelCacheColorspace (const Cache)
Definition at line 1945 of file cache.c.
References GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, and TraceEvent.
Referenced by GetCacheViewColorspace(), and QueueAuthenticPixelsStream().
MagickPrivate void GetPixelCacheMethods (CacheMethods *)
Referenced by ReadStream().
MagickPrivate MagickSizeType GetPixelCacheNexusExtent (const Cache , NexusInfo *)
Referenced by GetCacheViewExtent(), and GetImageExtent().
MagickPrivate void * GetPixelCachePixels (Image * , MagickSizeType * , ExceptionInfo *)
Referenced by AccelerateConvolveImage().
MagickPrivate ClassType GetPixelCacheStorageClass (const Cache)
Definition at line 2116 of file cache.c.
References GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, and TraceEvent.
Referenced by GetCacheViewStorageClass(), and QueueAuthenticPixelsStream().
MagickPrivate void GetPixelCacheTileSize (const Image * , size_t * , size_t *)
Referenced by IntegralRotateImage().
MagickPrivate VirtualPixelMethod GetPixelCacheVirtualMethod (const Image *)
Referenced by GetImageVirtualPixelMethod(), GetOneVirtualPixel(), and GetVirtualPixels().
MagickPrivate const void * GetVirtualMetacontentFromNexus (const Cache , NexusInfo *)
Referenced by GetCacheViewVirtualMetacontent(), GetVirtualMetacontent(), GetVirtualMetacontentFromCache(), and GetVirtualPixelsFromNexus().
MagickPrivate const Quantum* GetVirtualPixelsFromNexus (const Image * , const VirtualPixelMethod , const ssize_t , const ssize_t , const size_t , const size_t , NexusInfo * , ExceptionInfo *)
Referenced by GetCacheViewVirtualPixels(), GetOneCacheViewVirtualMethodPixel(), GetOneCacheViewVirtualPixel(), GetOneCacheViewVirtualPixelInfo(), GetOneVirtualPixel(), GetOneVirtualPixelFromCache(), GetOneVirtualPixelInfo(), GetVirtualPixelCache(), GetVirtualPixels(), and GetVirtualPixelsFromNexus().
MagickPrivate const Quantum * GetVirtualPixelsNexus (const Cache , NexusInfo *)
Referenced by GetCacheViewVirtualPixelQueue(), GetVirtualPixelQueue(), and GetVirtualPixelsCache().
MagickPrivate Quantum * QueueAuthenticPixelCacheNexus (Image * , const ssize_t , const ssize_t , const size_t , const size_t , const MagickBooleanType , NexusInfo * , ExceptionInfo *)
Definition at line 3742 of file cache.c.
References _Image::cache, CacheError, _Image::filename, GetImagePixelCache(), GetMagickModule, _RectangleInfo::height, MagickSignature, SetPixelCacheNexusPixels(), _Image::signature, ThrowMagickException(), _RectangleInfo::width, WriteMode, _RectangleInfo::x, and _RectangleInfo::y.
Referenced by GetAuthenticPixelCacheNexus(), QueueAuthenticPixels(), QueueAuthenticPixelsCache(), and QueueCacheViewAuthenticPixels().
MagickPrivate Cache ReferencePixelCache (Cache)
Definition at line 4336 of file cache.c.
References LockSemaphoreInfo(), MagickSignature, and UnlockSemaphoreInfo().
Referenced by CloneImage(), CloneImageInfo(), and PersistPixelCache().
MagickPrivate void SetPixelCacheMethods (Cache , CacheMethods *)
Definition at line 4374 of file cache.c.
References _CacheMethods::destroy_pixel_handler, _CacheMethods::get_authentic_metacontent_from_handler, _CacheMethods::get_authentic_pixels_from_handler, _CacheMethods::get_authentic_pixels_handler, _CacheMethods::get_one_authentic_pixel_from_handler, _CacheMethods::get_one_virtual_pixel_from_handler, _CacheMethods::get_virtual_metacontent_from_handler, _CacheMethods::get_virtual_pixel_handler, GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, _CacheMethods::queue_authentic_pixels_handler, _CacheMethods::sync_authentic_pixels_handler, and TraceEvent.
Referenced by ReadStream().
MagickPrivate VirtualPixelMethod SetPixelCacheVirtualMethod (Image * , const VirtualPixelMethod , ExceptionInfo *)
Definition at line 4708 of file cache.c.
References _PixelInfo::alpha_trait, _Image::alpha_trait, _Image::background_color, BackgroundVirtualPixelMethod, BlendPixelTrait, _Image::cache, _Image::colorspace, _Image::columns, _Image::debug, _Image::filename, GetMagickModule, IsGrayColorspace(), IsPixelInfoGray(), LogMagickEvent(), MagickFalse, MagickSignature, OpaqueAlpha, _Image::rows, SetCacheAlphaChannel(), SetImageColorspace(), _Image::signature, sRGBColorspace, TraceEvent, and TransparentVirtualPixelMethod.
Referenced by SetImageVirtualPixelMethod().
MagickPrivate MagickBooleanType SyncAuthenticPixelCacheNexus (Image * , NexusInfo * , ExceptionInfo *)
Referenced by SyncAuthenticPixels(), SyncAuthenticPixelsCache(), and SyncCacheViewAuthenticPixels().
MagickPrivate MagickBooleanType SyncImagePixelCache (Image * , ExceptionInfo *)
Definition at line 4944 of file cache.c.
References GetImagePixelCache(), MagickFalse, and MagickTrue.
Referenced by AcquireAuthenticCacheView(), IsImageGray(), IsImageMonochrome(), OpenDistributeCache(), SetImageAlphaChannel(), SetImageColorspace(), SetImageExtent(), SetImageMask(), SetImageStorageClass(), and SetPixelMetaChannels().