MagickCore: cache-view.c File Reference
cache-view.c File Reference
#include "MagickCore/studio.h"
#include "MagickCore/cache.h"
#include "MagickCore/cache-private.h"
#include "MagickCore/cache-view.h"
#include "MagickCore/memory_.h"
#include "MagickCore/memory-private.h"
#include "MagickCore/exception.h"
#include "MagickCore/exception-private.h"
#include "MagickCore/pixel-accessor.h"
#include "MagickCore/resource_.h"
#include "MagickCore/string_.h"
#include "MagickCore/thread-private.h"
Data Structures
struct _CacheView
Functions
MagickExport CacheView * AcquireAuthenticCacheView (const Image *image, ExceptionInfo *exception)
MagickExport CacheView * AcquireVirtualCacheView (const Image *image, ExceptionInfo *exception)
MagickExport CacheView * CloneCacheView (const CacheView *cache_view)
MagickExport CacheView * DestroyCacheView (CacheView *cache_view)
MagickExport Quantum * GetCacheViewAuthenticPixels (CacheView *cache_view, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, ExceptionInfo *exception)
MagickExport void * GetCacheViewAuthenticMetacontent (CacheView *cache_view)
MagickExport Quantum * GetCacheViewAuthenticPixelQueue (CacheView *cache_view)
MagickExport ColorspaceType GetCacheViewColorspace (const CacheView *cache_view)
MagickExport MagickSizeType GetCacheViewExtent (const CacheView *cache_view)
MagickExport const Image * GetCacheViewImage (const CacheView *cache_view)
MagickExport ClassType GetCacheViewStorageClass (const CacheView *cache_view)
MagickExport const void * GetCacheViewVirtualMetacontent (const CacheView *cache_view)
MagickExport const Quantum * GetCacheViewVirtualPixelQueue (const CacheView *cache_view)
MagickExport const Quantum * GetCacheViewVirtualPixels (const CacheView *cache_view, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, ExceptionInfo *exception)
MagickExport MagickBooleanType GetOneCacheViewAuthenticPixel (const CacheView *cache_view, const ssize_t x, const ssize_t y, Quantum *pixel, ExceptionInfo *exception)
MagickExport MagickBooleanType GetOneCacheViewVirtualPixel (const CacheView *cache_view, const ssize_t x, const ssize_t y, Quantum *pixel, ExceptionInfo *exception)
MagickExport MagickBooleanType GetOneCacheViewVirtualPixelInfo (const CacheView *cache_view, const ssize_t x, const ssize_t y, PixelInfo *pixel, ExceptionInfo *exception)
MagickExport MagickBooleanType GetOneCacheViewVirtualMethodPixel (const CacheView *cache_view, const VirtualPixelMethod virtual_pixel_method, const ssize_t x, const ssize_t y, Quantum *pixel, ExceptionInfo *exception)
MagickExport Quantum * QueueCacheViewAuthenticPixels (CacheView *cache_view, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, ExceptionInfo *exception)
MagickExport MagickBooleanType SetCacheViewStorageClass (CacheView *cache_view, const ClassType storage_class, ExceptionInfo *exception)
MagickExport MagickBooleanType SetCacheViewVirtualPixelMethod (CacheView *cache_view, const VirtualPixelMethod virtual_pixel_method)
MagickExport MagickBooleanType SyncCacheViewAuthenticPixels (CacheView *cache_view, ExceptionInfo *exception)
Function Documentation
MagickExport CacheView* AcquireAuthenticCacheView (const Image * image, ExceptionInfo * exception)
Definition at line 112 of file cache-view.c.
References AcquireVirtualCacheView(), _CacheView::image, and SyncImagePixelCache().
Referenced by AdaptiveBlurImage(), AdaptiveSharpenImage(), AdaptiveThresholdImage(), AddNoiseImage(), AppendImages(), AssignImageColors(), BilevelImage(), BlackThresholdImage(), BlueShiftImage(), ChannelImage(), ChopImage(), ClampImage(), Classify(), ClutImage(), ColorDecisionListImage(), ColorizeImage(), ColorMatrixImage(), CombineImages(), CompareImages(), CompositeImage(), CompositeOverImage(), ConsolidateCMYKImages(), ContrastImage(), ContrastStretchImage(), CopyImageRegion(), CropImage(), CycleColormapImage(), DespeckleImage(), DirectToColormapImage(), DistortImage(), DitherImage(), DrawAffineImage(), DrawGradientImage(), DrawPolygonPrimitive(), DrawPrimitive(), EnhanceImage(), EqualizeImage(), EvaluateImage(), EvaluateImages(), ExcerptImage(), FlipImage(), FloodfillPaintImage(), FlopImage(), FloydSteinbergDither(), FrameImage(), FunctionImage(), FxImage(), GammaImage(), GetImageMask(), HaldClutImage(), HorizontalFilter(), HuffmanDecodeImage(), ImplodeImage(), IntegralRotateImage(), InterpolativeResizeImage(), LevelImage(), LevelizeImage(), ModulateImage(), MorphImages(), MorphologyPrimitive(), MorphologyPrimitiveDirect(), MotionBlurImage(), NegateImage(), NewMagickImage(), OilPaintImage(), OpaquePaintImage(), OrderedPosterizeImage(), PerceptibleImage(), PlasmaImage(), PolynomialImage(), PosterizeImage(), ProfileImage(), RadialBlurImage(), RaiseImage(), RandomThresholdImage(), RenderPostscript(), SampleImage(), ScaleImage(), SelectiveBlurImage(), SeparateImage(), SepiaToneImage(), SetGrayscaleImage(), SetImageAlpha(), SetImageAlphaChannel(), SetImageBackgroundColor(), SetImageColor(), SetImageDepth(), SetImageMask(), ShadeImage(), ShadowImage(), SigmoidalContrastImage(), SimilarityImage(), SketchImage(), SolarizeImage(), SortColormapByIntensity(), SparseColorImage(), SpliceImage(), SpreadImage(), sRGBTransformImage(), StatisticImage(), SteganoImage(), SwirlImage(), SyncImage(), TextureImage(), TintImage(), TransformsRGBImage(), TransparentPaintImage(), TransparentPaintImageChroma(), TransposeImage(), TransverseImage(), UniqueImageColors(), UnsharpMaskImage(), VerticalFilter(), WaveImage(), WhiteThresholdImage(), XShearImage(), and YShearImage().
MagickExport CacheView* AcquireVirtualCacheView (const Image * image, ExceptionInfo * exception)
Definition at line 150 of file cache-view.c.
References AcquireAlignedMemory(), AcquirePixelCacheNexus(), CacheFatalError, _CacheView::debug, _Image::debug, _Image::filename, GetImageVirtualPixelMethod(), GetMagickModule, GetMagickResourceLimit(), GetOpenMPMaximumThreads(), _CacheView::image, IsEventLogging(), LogMagickEvent(), MagickAssumeAligned, MagickFalse, MagickSignature, _CacheView::nexus_info, _CacheView::number_threads, ReferenceImage(), ResetMagickMemory(), ResourceLimitFatalError, _CacheView::signature, _Image::signature, ThreadResource, ThrowFatalException, TraceEvent, and _CacheView::virtual_pixel_method.
Referenced by AcquireAuthenticCacheView(), AcquireFxInfo(), AcquireResampleFilter(), AdaptiveBlurImage(), AdaptiveSharpenImage(), AdaptiveThresholdImage(), AddNoiseImage(), AppendImages(), BlueShiftImage(), ChannelImage(), ChopImage(), Classify(), ClassifyImageColors(), ClutImage(), ColorizeImage(), ColorMatrixImage(), CombineImages(), CompareImages(), CompositeImage(), CompositeOverImage(), ConsolidateCMYKImages(), ContrastStretchImage(), CopyImageRegion(), CropImage(), DespeckleImage(), DrawAffineImage(), EnhanceImage(), EqualizeImage(), EvaluateImages(), ExcerptImage(), FlipImage(), FloodfillPaintImage(), FlopImage(), FrameImage(), FxImage(), GetAbsoluteDistortion(), GetFuzzDistortion(), GetImageBackgroundColor(), GetImageBoundingBox(), GetImageDepth(), GetImageFeatures(), GetImageKurtosis(), GetImageMask(), GetImageQuantizeError(), GetImageRange(), GetImageTotalInkDensity(), GetMeanAbsoluteDistortion(), GetMeanErrorPerPixel(), GetMeanSquaredDistortion(), GetNormalizedCrossCorrelationDistortion(), GetPeakAbsoluteDistortion(), HaldClutImage(), HorizontalFilter(), ImplodeImage(), IntegralRotateImage(), InterpolatePixelChannel(), InterpolatePixelChannels(), InterpolatePixelInfo(), InterpolativeResizeImage(), IsEquivalentImage(), IsHighDynamicRangeImage(), IsHistogramImage(), IsImageGray(), IsImageMonochrome(), IsImageOpaque(), IsImagesEqual(), IsPaletteImage(), LinearStretchImage(), MorphImages(), MorphologyPrimitive(), MorphologyPrimitiveDirect(), MotionBlurImage(), NewImageView(), NewImageViewRegion(), OilPaintImage(), PlasmaImage(), PolynomialImage(), RadialBlurImage(), RadonTransform(), ResamplePixelColor(), SampleImage(), ScaleImage(), SelectiveBlurImage(), SeparateImage(), SepiaToneImage(), SetCacheAlphaChannel(), SetImageMask(), ShadeImage(), SignatureImage(), SmushXGap(), SmushYGap(), SpliceImage(), SpreadImage(), StatisticImage(), SteganoImage(), SwirlImage(), TextureImage(), TintImage(), TransposeImage(), TransverseImage(), UnsharpMaskImage(), VerticalFilter(), and WaveImage().
MagickExport CacheView* CloneCacheView (const CacheView * cache_view)
Definition at line 203 of file cache-view.c.
References AcquireAlignedMemory(), AcquirePixelCacheNexus(), _CacheView::debug, _Image::filename, GetMagickModule, _CacheView::image, LogMagickEvent(), MagickAssumeAligned, MagickFalse, MagickSignature, _CacheView::nexus_info, _CacheView::number_threads, ReferenceImage(), ResetMagickMemory(), ResourceLimitFatalError, _CacheView::signature, ThrowFatalException, TraceEvent, and _CacheView::virtual_pixel_method.
Referenced by CloneImageView().
MagickExport CacheView* DestroyCacheView (CacheView * cache_view)
Definition at line 250 of file cache-view.c.
References _CacheView::debug, DestroyImage(), DestroyPixelCacheNexus(), _Image::filename, GetMagickModule, _CacheView::image, LogMagickEvent(), MagickFalse, MagickSignature, _CacheView::nexus_info, _CacheView::number_threads, RelinquishAlignedMemory(), _CacheView::signature, and TraceEvent.
Referenced by AdaptiveBlurImage(), AdaptiveSharpenImage(), AdaptiveThresholdImage(), AddNoiseImage(), AppendImages(), AssignImageColors(), BilevelImage(), BlackThresholdImage(), BlueShiftImage(), ChannelImage(), ChopImage(), ClampImage(), Classify(), ClassifyImageColors(), ClutImage(), ColorDecisionListImage(), ColorizeImage(), ColorMatrixImage(), CombineImages(), CompareImages(), CompositeImage(), CompositeOverImage(), ConsolidateCMYKImages(), ContrastImage(), ContrastStretchImage(), CopyImageRegion(), CropImage(), CycleColormapImage(), DespeckleImage(), DestroyFxInfo(), DestroyImageView(), DestroyResampleFilter(), DirectToColormapImage(), DistortImage(), DitherImage(), DrawAffineImage(), DrawPolygonPrimitive(), DrawPrimitive(), EnhanceImage(), EqualizeImage(), EvaluateImage(), EvaluateImages(), ExcerptImage(), FlipImage(), FloodfillPaintImage(), FlopImage(), FloydSteinbergDither(), FrameImage(), FunctionImage(), FxImage(), GammaImage(), GetAbsoluteDistortion(), GetFuzzDistortion(), GetImageBackgroundColor(), GetImageBoundingBox(), GetImageDepth(), GetImageFeatures(), GetImageKurtosis(), GetImageMask(), GetImageQuantizeError(), GetImageRange(), GetImageTotalInkDensity(), GetMeanAbsoluteDistortion(), GetMeanErrorPerPixel(), GetMeanSquaredDistortion(), GetNormalizedCrossCorrelationDistortion(), GetPeakAbsoluteDistortion(), HaldClutImage(), HorizontalFilter(), HuffmanDecodeImage(), ImplodeImage(), IntegralRotateImage(), InterpolatePixelChannel(), InterpolatePixelChannels(), InterpolatePixelInfo(), InterpolativeResizeImage(), IsEquivalentImage(), IsHighDynamicRangeImage(), IsImageGray(), IsImageMonochrome(), IsImageOpaque(), IsImagesEqual(), LevelImage(), LevelizeImage(), LinearStretchImage(), ModulateImage(), MorphImages(), MorphologyPrimitive(), MorphologyPrimitiveDirect(), MotionBlurImage(), NegateImage(), NewMagickImage(), OilPaintImage(), OpaquePaintImage(), OrderedPosterizeImage(), PerceptibleImage(), PlasmaImage(), PolynomialImage(), PosterizeImage(), ProfileImage(), RadialBlurImage(), RadonTransform(), RaiseImage(), RandomThresholdImage(), RenderPostscript(), ResamplePixelColor(), SampleImage(), ScaleImage(), SelectiveBlurImage(), SeparateImage(), SepiaToneImage(), SetCacheAlphaChannel(), SetGrayscaleImage(), SetImageAlpha(), SetImageAlphaChannel(), SetImageBackgroundColor(), SetImageColor(), SetImageDepth(), SetImageMask(), ShadowImage(), SigmoidalContrastImage(), SignatureImage(), SimilarityImage(), SketchImage(), SmushXGap(), SmushYGap(), SolarizeImage(), SortColormapByIntensity(), SparseColorImage(), SpliceImage(), SpreadImage(), sRGBTransformImage(), StatisticImage(), SteganoImage(), SwirlImage(), SyncImage(), TextureImage(), TintImage(), TransformsRGBImage(), TransparentPaintImage(), TransparentPaintImageChroma(), TransposeImage(), TransverseImage(), UniqueImageColors(), UnsharpMaskImage(), VerticalFilter(), WaveImage(), WhiteThresholdImage(), XShearImage(), and YShearImage().
MagickExport void* GetCacheViewAuthenticMetacontent (CacheView * cache_view)
Definition at line 340 of file cache-view.c.
References _Image::cache, GetOpenMPThreadId(), GetPixelCacheNexusMetacontent(), _CacheView::image, MagickSignature, _CacheView::nexus_info, _CacheView::number_threads, and _CacheView::signature.
Referenced by GetImageViewAuthenticMetacontent().
MagickExport Quantum* GetCacheViewAuthenticPixelQueue (CacheView * cache_view)
Definition at line 382 of file cache-view.c.
References _Image::cache, GetOpenMPThreadId(), GetPixelCacheNexusPixels(), _CacheView::image, MagickSignature, _CacheView::nexus_info, _CacheView::number_threads, and _CacheView::signature.
Referenced by ExportQuantumPixels(), GetImageViewAuthenticPixels(), and ImportQuantumPixels().
MagickExport Quantum* GetCacheViewAuthenticPixels (CacheView * cache_view, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, ExceptionInfo * exception)
Definition at line 297 of file cache-view.c.
References GetAuthenticPixelCacheNexus(), GetOpenMPThreadId(), _CacheView::image, MagickSignature, _CacheView::nexus_info, _CacheView::number_threads, and _CacheView::signature.
Referenced by AssignImageColors(), BilevelImage(), BlackThresholdImage(), ChannelImage(), ClampImage(), Classify(), ClutImage(), ColorDecisionListImage(), ColorMatrixImage(), CombineImages(), CompositeImage(), CompositeOverImage(), ContrastImage(), ContrastStretchImage(), CopyImageRegion(), CycleColormapImage(), DespeckleImage(), DirectToColormapImage(), DrawAffineImage(), DrawGradientImage(), DrawPolygonPrimitive(), DrawPrimitive(), DuplexTransferImageViewIterator(), EqualizeImage(), EvaluateImage(), ExcerptImage(), FloodfillPaintImage(), FloydSteinbergDither(), FunctionImage(), GammaImage(), GetImageMask(), HaldClutImage(), ImplodeImage(), LevelImage(), LevelizeImage(), ModulateImage(), MorphImages(), MorphologyPrimitive(), MorphologyPrimitiveDirect(), NegateImage(), OpaquePaintImage(), OrderedPosterizeImage(), PerceptibleImage(), PosterizeImage(), ProfileImage(), RaiseImage(), RandomThresholdImage(), RenderPostscript(), RiemersmaDither(), SepiaToneImage(), SetCacheAlphaChannel(), SetGrayscaleImage(), SetImageAlpha(), SetImageAlphaChannel(), SetImageDepth(), SetImageMask(), SetImageViewIterator(), SigmoidalContrastImage(), SimilarityImage(), SolarizeImage(), SortColormapByIntensity(), SparseColorImage(), sRGBTransformImage(), SteganoImage(), SwirlImage(), SyncImage(), TransferImageViewIterator(), TransformsRGBImage(), TransparentPaintImage(), TransparentPaintImageChroma(), UpdateImageViewIterator(), WhiteThresholdImage(), XShearImage(), and YShearImage().
MagickExport ColorspaceType GetCacheViewColorspace (const CacheView * cache_view)
Definition at line 422 of file cache-view.c.
References _Image::cache, _CacheView::debug, _Image::filename, GetMagickModule, GetPixelCacheColorspace(), _CacheView::image, LogMagickEvent(), MagickFalse, MagickSignature, _CacheView::signature, and TraceEvent.
MagickExport MagickSizeType GetCacheViewExtent (const CacheView * cache_view)
Definition at line 456 of file cache-view.c.
References _Image::cache, _CacheView::debug, _Image::filename, GetMagickModule, GetOpenMPThreadId(), GetPixelCacheNexusExtent(), _CacheView::image, LogMagickEvent(), MagickFalse, MagickSignature, _CacheView::nexus_info, _CacheView::number_threads, _CacheView::signature, and TraceEvent.
Referenced by ExportQuantumPixels(), and ImportQuantumPixels().
MagickExport const Image* GetCacheViewImage (const CacheView * cache_view)
Definition at line 498 of file cache-view.c.
References _CacheView::debug, _Image::filename, GetMagickModule, _CacheView::image, LogMagickEvent(), MagickFalse, MagickSignature, _CacheView::signature, and TraceEvent.
MagickExport ClassType GetCacheViewStorageClass (const CacheView * cache_view)
Definition at line 531 of file cache-view.c.
References _Image::cache, _CacheView::debug, _Image::filename, GetMagickModule, GetPixelCacheStorageClass(), _CacheView::image, LogMagickEvent(), MagickFalse, MagickSignature, _CacheView::signature, and TraceEvent.
MagickExport const void* GetCacheViewVirtualMetacontent (const CacheView * cache_view)
Definition at line 566 of file cache-view.c.
References _Image::cache, GetOpenMPThreadId(), GetVirtualMetacontentFromNexus(), _CacheView::image, MagickSignature, _CacheView::nexus_info, _CacheView::number_threads, and _CacheView::signature.
Referenced by GetImageViewVirtualMetacontent().
MagickExport const Quantum* GetCacheViewVirtualPixelQueue (const CacheView * cache_view)
Definition at line 609 of file cache-view.c.
References _Image::cache, GetOpenMPThreadId(), GetVirtualPixelsNexus(), _CacheView::image, MagickSignature, _CacheView::nexus_info, _CacheView::number_threads, and _CacheView::signature.
Referenced by ExportQuantumPixels(), and GetImageViewVirtualPixels().
MagickExport const Quantum* GetCacheViewVirtualPixels (const CacheView * cache_view, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, ExceptionInfo * exception)
Definition at line 659 of file cache-view.c.
References GetOpenMPThreadId(), GetVirtualPixelsFromNexus(), _CacheView::image, MagickSignature, _CacheView::nexus_info, _CacheView::number_threads, _CacheView::signature, and _CacheView::virtual_pixel_method.
Referenced by AdaptiveBlurImage(), AdaptiveSharpenImage(), AdaptiveThresholdImage(), AddNoiseImage(), AppendImages(), BlueShiftImage(), ChannelImage(), ChopImage(), Classify(), ClassifyImageColors(), ColorizeImage(), ColorMatrixImage(), CombineImages(), CompareImages(), CompositeImage(), CompositeOverImage(), ConsolidateCMYKImages(), ContrastStretchImage(), CopyImageRegion(), CropImage(), DespeckleImage(), DuplexTransferImageViewIterator(), EnhanceImage(), EqualizeImage(), EvaluateImages(), ExcerptImage(), FlipImage(), FloodfillPaintImage(), FlopImage(), FrameImage(), FxImage(), GetAbsoluteDistortion(), GetFuzzDistortion(), GetImageBackgroundColor(), GetImageBoundingBox(), GetImageDepth(), GetImageFeatures(), GetImageKurtosis(), GetImageMask(), GetImageQuantizeError(), GetImageRange(), GetImageTotalInkDensity(), GetImageViewIterator(), GetMeanAbsoluteDistortion(), GetMeanErrorPerPixel(), GetMeanSquaredDistortion(), GetNormalizedCrossCorrelationDistortion(), GetPeakAbsoluteDistortion(), HorizontalFilter(), IntegralRotateImage(), InterpolatePixelChannel(), InterpolatePixelChannels(), InterpolatePixelInfo(), IsEquivalentImage(), IsHighDynamicRangeImage(), IsHistogramImage(), IsImageGray(), IsImageMonochrome(), IsImageOpaque(), IsImagesEqual(), IsPaletteImage(), LinearStretchImage(), MorphImages(), MorphologyPrimitive(), MorphologyPrimitiveDirect(), MotionBlurImage(), OilPaintImage(), PlasmaImageProxy(), PolynomialImage(), RadialBlurImage(), RadonTransform(), ResamplePixelColor(), SampleImage(), ScaleImage(), SelectiveBlurImage(), SeparateImage(), SepiaToneImage(), SetImageMask(), ShadeImage(), SignatureImage(), SmushXGap(), SmushYGap(), SpliceImage(), SpreadImage(), StatisticImage(), TextureImage(), TintImage(), TransferImageViewIterator(), TransposeImage(), TransverseImage(), UnsharpMaskImage(), and VerticalFilter().
MagickExport MagickBooleanType GetOneCacheViewAuthenticPixel (const CacheView * cache_view, const ssize_t x, const ssize_t y, Quantum * pixel, ExceptionInfo * exception)
Definition at line 709 of file cache-view.c.
References _PixelInfo::alpha, AlphaPixelChannel, _Image::background_color, _PixelInfo::black, BlackPixelChannel, _PixelInfo::blue, BluePixelChannel, ClampToQuantum(), GetAuthenticPixelCacheNexus(), GetOpenMPThreadId(), GetPixelChannelChannel(), GetPixelChannels(), _PixelInfo::green, GreenPixelChannel, _CacheView::image, MagickFalse, MagickSignature, MagickTrue, MaxPixelChannels, _CacheView::nexus_info, _CacheView::number_threads, _PixelInfo::red, RedPixelChannel, and _CacheView::signature.
MagickExport MagickBooleanType GetOneCacheViewVirtualMethodPixel (const CacheView * cache_view, const VirtualPixelMethod virtual_pixel_method, const ssize_t x, const ssize_t y, Quantum * pixel, ExceptionInfo * exception)
Definition at line 913 of file cache-view.c.
References _PixelInfo::alpha, AlphaPixelChannel, _Image::background_color, _PixelInfo::black, BlackPixelChannel, _PixelInfo::blue, BluePixelChannel, ClampToQuantum(), GetOpenMPThreadId(), GetPixelChannelChannel(), GetPixelChannels(), GetVirtualPixelsFromNexus(), _PixelInfo::green, GreenPixelChannel, _CacheView::image, MagickFalse, MagickSignature, MagickTrue, MaxPixelChannels, _CacheView::nexus_info, _CacheView::number_threads, _PixelInfo::red, RedPixelChannel, and _CacheView::signature.
MagickExport MagickBooleanType GetOneCacheViewVirtualPixel (const CacheView * cache_view, const ssize_t x, const ssize_t y, Quantum * pixel, ExceptionInfo * exception)
Definition at line 781 of file cache-view.c.
References _PixelInfo::alpha, AlphaPixelChannel, _Image::background_color, _PixelInfo::black, BlackPixelChannel, _PixelInfo::blue, BluePixelChannel, ClampToQuantum(), GetOpenMPThreadId(), GetPixelChannelChannel(), GetPixelChannels(), GetVirtualPixelsFromNexus(), _PixelInfo::green, GreenPixelChannel, _CacheView::image, MagickFalse, MagickSignature, MagickTrue, MaxPixelChannels, _CacheView::nexus_info, _CacheView::number_threads, _PixelInfo::red, RedPixelChannel, _CacheView::signature, and _CacheView::virtual_pixel_method.
MagickExport MagickBooleanType GetOneCacheViewVirtualPixelInfo (const CacheView * cache_view, const ssize_t x, const ssize_t y, PixelInfo * pixel, ExceptionInfo * exception)
Definition at line 854 of file cache-view.c.
References GetOpenMPThreadId(), GetPixelInfo(), GetPixelInfoPixel(), GetVirtualPixelsFromNexus(), _CacheView::image, MagickFalse, MagickSignature, MagickTrue, _CacheView::nexus_info, _CacheView::number_threads, _CacheView::signature, and _CacheView::virtual_pixel_method.
Referenced by DrawPrimitive(), and SteganoImage().
MagickExport Quantum* QueueCacheViewAuthenticPixels (CacheView * cache_view, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, ExceptionInfo * exception)
Definition at line 985 of file cache-view.c.
References GetOpenMPThreadId(), _CacheView::image, MagickFalse, MagickSignature, _CacheView::nexus_info, _CacheView::number_threads, QueueAuthenticPixelCacheNexus(), and _CacheView::signature.
Referenced by AdaptiveBlurImage(), AdaptiveSharpenImage(), AdaptiveThresholdImage(), AddNoiseImage(), AppendImages(), BlueShiftImage(), ChopImage(), ColorizeImage(), CompareImages(), CompositeImage(), ConsolidateCMYKImages(), CropImage(), DistortImage(), EnhanceImage(), EvaluateImages(), FlipImage(), FlopImage(), FrameImage(), FxImage(), HorizontalFilter(), HuffmanDecodeImage(), ImplodeImage(), IntegralRotateImage(), InterpolativeResizeImage(), MotionBlurImage(), NewMagickImage(), OilPaintImage(), PlasmaImageProxy(), PolynomialImage(), RadialBlurImage(), SampleImage(), ScaleImage(), SelectiveBlurImage(), SeparateImage(), SetImageBackgroundColor(), SetImageColor(), ShadeImage(), ShadowImage(), SketchImage(), SpliceImage(), SpreadImage(), StatisticImage(), SwirlImage(), TextureImage(), TintImage(), TransposeImage(), TransverseImage(), UniqueColorsToImage(), UnsharpMaskImage(), VerticalFilter(), and WaveImage().
MagickExport MagickBooleanType SetCacheViewStorageClass (CacheView * cache_view, const ClassType storage_class, ExceptionInfo * exception)
Definition at line 1031 of file cache-view.c.
References _CacheView::debug, _Image::filename, GetMagickModule, _CacheView::image, LogMagickEvent(), MagickFalse, MagickSignature, SetImageStorageClass(), _CacheView::signature, and TraceEvent.
MagickExport MagickBooleanType SetCacheViewVirtualPixelMethod (CacheView * cache_view, const VirtualPixelMethod virtual_pixel_method)
Definition at line 1068 of file cache-view.c.
References _CacheView::debug, _Image::filename, GetMagickModule, _CacheView::image, LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, _CacheView::signature, TraceEvent, and _CacheView::virtual_pixel_method.
Referenced by SetResampleFilterVirtualPixelMethod(), and WaveImage().
MagickExport MagickBooleanType SyncCacheViewAuthenticPixels (CacheView * cache_view, ExceptionInfo * exception)
Definition at line 1107 of file cache-view.c.
References GetOpenMPThreadId(), _CacheView::image, MagickSignature, _CacheView::nexus_info, _CacheView::number_threads, _CacheView::signature, and SyncAuthenticPixelCacheNexus().
Referenced by AdaptiveBlurImage(), AdaptiveSharpenImage(), AdaptiveThresholdImage(), AddNoiseImage(), AppendImages(), AssignImageColors(), BilevelImage(), BlackThresholdImage(), BlueShiftImage(), ChannelImage(), ChopImage(), ClampImage(), Classify(), ClutImage(), ColorDecisionListImage(), ColorizeImage(), ColorMatrixImage(), CombineImages(), CompareImages(), CompositeImage(), CompositeOverImage(), ConsolidateCMYKImages(), ContrastImage(), ContrastStretchImage(), CopyImageRegion(), CropImage(), CycleColormapImage(), DespeckleImage(), DirectToColormapImage(), DistortImage(), DrawAffineImage(), DrawPolygonPrimitive(), DrawPrimitive(), DuplexTransferImageViewIterator(), EnhanceImage(), EqualizeImage(), EvaluateImage(), EvaluateImages(), ExcerptImage(), FlipImage(), FloodfillPaintImage(), FlopImage(), FloydSteinbergDither(), FrameImage(), FunctionImage(), FxImage(), GammaImage(), GetImageMask(), HaldClutImage(), HorizontalFilter(), HuffmanDecodeImage(), ImplodeImage(), IntegralRotateImage(), InterpolativeResizeImage(), LevelImage(), LevelizeImage(), ModulateImage(), MorphImages(), MorphologyPrimitive(), MorphologyPrimitiveDirect(), MotionBlurImage(), NegateImage(), NewMagickImage(), OilPaintImage(), OpaquePaintImage(), OrderedPosterizeImage(), PerceptibleImage(), PlasmaImageProxy(), PolynomialImage(), PosterizeImage(), ProfileImage(), RadialBlurImage(), RaiseImage(), RandomThresholdImage(), RenderPostscript(), RiemersmaDither(), SampleImage(), ScaleImage(), SelectiveBlurImage(), SeparateImage(), SepiaToneImage(), SetCacheAlphaChannel(), SetGrayscaleImage(), SetImageAlpha(), SetImageAlphaChannel(), SetImageBackgroundColor(), SetImageColor(), SetImageDepth(), SetImageMask(), SetImageViewIterator(), ShadeImage(), ShadowImage(), SigmoidalContrastImage(), SimilarityImage(), SketchImage(), SolarizeImage(), SortColormapByIntensity(), SparseColorImage(), SpliceImage(), SpreadImage(), sRGBTransformImage(), StatisticImage(), SteganoImage(), SwirlImage(), SyncImage(), TextureImage(), TintImage(), TransferImageViewIterator(), TransformsRGBImage(), TransparentPaintImage(), TransparentPaintImageChroma(), TransposeImage(), TransverseImage(), UniqueColorsToImage(), UnsharpMaskImage(), UpdateImageViewIterator(), VerticalFilter(), WaveImage(), WhiteThresholdImage(), XShearImage(), and YShearImage().