MagickCore: cache.h File Reference
cache.h File Reference
#include "MagickCore/blob.h"
Enumerations
enum CacheType {
UndefinedCache, DiskCache, DistributedCache, MapCache,
MemoryCache, PingCache
}
Functions
MagickExport CacheType GetImagePixelCacheType (const Image *)
MagickExport const Quantum * GetVirtualPixels (const Image *, const ssize_t, const ssize_t, const size_t, const size_t, ExceptionInfo *) magick_hot_spot
MagickExport const Quantum * GetVirtualPixelQueue (const Image *) magick_hot_spot
MagickExport const void * GetVirtualMetacontent (const Image *)
MagickExport MagickBooleanType GetOneAuthenticPixel (Image *, const ssize_t, const ssize_t, Quantum *, ExceptionInfo *)
MagickExport MagickBooleanType GetOneVirtualPixel (const Image *, const ssize_t, const ssize_t, Quantum *, ExceptionInfo *)
MagickExport MagickBooleanType GetOneVirtualPixelInfo (const Image *, const VirtualPixelMethod, const ssize_t, const ssize_t, PixelInfo *, ExceptionInfo *)
MagickExport MagickBooleanType PersistPixelCache (Image *, const char *, const MagickBooleanType, MagickOffsetType *, ExceptionInfo *)
MagickExport MagickBooleanType SyncAuthenticPixels (Image *, ExceptionInfo *) magick_hot_spot
MagickExport MagickSizeType GetImageExtent (const Image *)
MagickExport Quantum * GetAuthenticPixels (Image *, const ssize_t, const ssize_t, const size_t, const size_t, ExceptionInfo *) magick_hot_spot
MagickExport Quantum * GetAuthenticPixelQueue (const Image *) magick_hot_spot
MagickExport Quantum * QueueAuthenticPixels (Image *, const ssize_t, const ssize_t, const size_t, const size_t, ExceptionInfo *) magick_hot_spot
MagickExport void * GetAuthenticMetacontent (const Image *)
Enumeration Type Documentation
enum CacheType
Enumerator
UndefinedCache
DiskCache
DistributedCache
MapCache
MemoryCache
PingCache
Definition at line 27 of file cache.h.
Function Documentation
MagickExport void* GetAuthenticMetacontent (const Image *)
Definition at line 1001 of file cache.c.
References _Image::cache, _CacheMethods::get_authentic_metacontent_from_handler, GetOpenMPThreadId(), GetPixelCacheNexusMetacontent(), MagickSignature, _CacheInfo::methods, _CacheInfo::nexus_info, _CacheInfo::number_threads, _CacheInfo::signature, and _Image::signature.
Referenced by WriteDistributeCacheMetacontent().
MagickExport Quantum * GetAuthenticPixelQueue (const Image *)
MagickExport Quantum* GetAuthenticPixels (Image * , const ssize_t , const ssize_t , const size_t , const size_t , ExceptionInfo *)
MagickExport MagickSizeType GetImageExtent (const Image *)
Definition at line 1399 of file cache.c.
References _Image::cache, _Image::debug, _Image::filename, GetMagickModule, GetOpenMPThreadId(), GetPixelCacheNexusExtent(), LogMagickEvent(), MagickFalse, MagickSignature, _CacheInfo::nexus_info, _CacheInfo::number_threads, _CacheInfo::signature, _Image::signature, and TraceEvent.
Referenced by ExportQuantumPixels(), ImportQuantumPixels(), and StreamImagePixels().
MagickExport CacheType GetImagePixelCacheType (const Image *)
Definition at line 1599 of file cache.c.
References _Image::cache, MagickSignature, _CacheInfo::signature, _Image::signature, and _CacheInfo::type.
Referenced by GetPixelCacheTileSize().
MagickExport MagickBooleanType GetOneAuthenticPixel (Image * , const ssize_t , const ssize_t , Quantum * , ExceptionInfo *)
MagickExport MagickBooleanType GetOneVirtualPixel (const Image * , const ssize_t , const ssize_t , Quantum * , ExceptionInfo *)
MagickExport MagickBooleanType GetOneVirtualPixelInfo (const Image * , const VirtualPixelMethod , const ssize_t , const ssize_t , PixelInfo * , ExceptionInfo *)
MagickExport const void* GetVirtualMetacontent (const Image *)
Definition at line 2446 of file cache.c.
References _Image::cache, _CacheMethods::get_virtual_metacontent_from_handler, GetOpenMPThreadId(), GetVirtualMetacontentFromNexus(), MagickSignature, _CacheInfo::methods, _CacheInfo::nexus_info, _CacheInfo::number_threads, _CacheInfo::signature, and _Image::signature.
Referenced by ReadDistributeCacheMetacontent().
MagickExport const Quantum * GetVirtualPixelQueue (const Image *)
Definition at line 3070 of file cache.c.
References _Image::cache, _CacheMethods::get_virtual_pixels_handler, GetOpenMPThreadId(), GetVirtualPixelsNexus(), MagickSignature, _CacheInfo::methods, _CacheInfo::nexus_info, _CacheInfo::number_threads, _CacheInfo::signature, and _Image::signature.
Referenced by ExportQuantumPixels().
MagickExport const Quantum* GetVirtualPixels (const Image * , const ssize_t , const ssize_t , const size_t , const size_t , ExceptionInfo *)
MagickExport MagickBooleanType PersistPixelCache (Image * , const char * , const MagickBooleanType , MagickOffsetType * , ExceptionInfo *)
MagickExport Quantum * QueueAuthenticPixels (Image * , const ssize_t , const ssize_t , const size_t , const size_t , ExceptionInfo *)
Definition at line 4035 of file cache.c.
References _Image::cache, GetOpenMPThreadId(), MagickFalse, MagickSignature, _CacheInfo::methods, _CacheInfo::nexus_info, _CacheInfo::number_threads, _CacheMethods::queue_authentic_pixels_handler, QueueAuthenticPixelCacheNexus(), _CacheInfo::signature, and _Image::signature.
Referenced by StereoAnaglyphImage().
MagickExport MagickBooleanType SyncAuthenticPixels (Image * , ExceptionInfo *)
Definition at line 4985 of file cache.c.
References _Image::cache, GetOpenMPThreadId(), MagickSignature, _CacheInfo::methods, _CacheInfo::nexus_info, _CacheInfo::number_threads, _CacheInfo::signature, _Image::signature, _CacheMethods::sync_authentic_pixels_handler, and SyncAuthenticPixelCacheNexus().
Referenced by ClearBounds(), ImportCharPixel(), ImportDoublePixel(), ImportFloatPixel(), ImportLongLongPixel(), ImportLongPixel(), ImportQuantumPixel(), ImportShortPixel(), StereoAnaglyphImage(), WriteDistributeCacheMetacontent(), and WriteDistributeCachePixels().