MagickCore: cache-view.h File Reference
cache-view.h File Reference
#include "MagickCore/pixel.h"
Typedefs
typedef struct _CacheView CacheView
Enumerations
enum VirtualPixelMethod {
UndefinedVirtualPixelMethod, BackgroundVirtualPixelMethod, DitherVirtualPixelMethod, EdgeVirtualPixelMethod,
MirrorVirtualPixelMethod, RandomVirtualPixelMethod, TileVirtualPixelMethod, TransparentVirtualPixelMethod,
MaskVirtualPixelMethod, BlackVirtualPixelMethod, GrayVirtualPixelMethod, WhiteVirtualPixelMethod,
HorizontalTileVirtualPixelMethod, VerticalTileVirtualPixelMethod, HorizontalTileEdgeVirtualPixelMethod, VerticalTileEdgeVirtualPixelMethod,
CheckerTileVirtualPixelMethod
}
Functions
MagickExport CacheView * AcquireAuthenticCacheView (const Image *, ExceptionInfo *)
MagickExport CacheView * AcquireVirtualCacheView (const Image *, ExceptionInfo *)
MagickExport CacheView * CloneCacheView (const CacheView *)
MagickExport CacheView * DestroyCacheView (CacheView *)
MagickExport ClassType GetCacheViewStorageClass (const CacheView *)
MagickExport ColorspaceType GetCacheViewColorspace (const CacheView *)
MagickExport const Image * GetCacheViewImage (const CacheView *)
MagickExport const Quantum * GetCacheViewVirtualPixels (const CacheView *, const ssize_t, const ssize_t, const size_t, const size_t, ExceptionInfo *) magick_hot_spot
MagickExport const Quantum * GetCacheViewVirtualPixelQueue (const CacheView *) magick_hot_spot
MagickExport const void * GetCacheViewVirtualMetacontent (const CacheView *)
MagickExport MagickBooleanType GetOneCacheViewAuthenticPixel (const CacheView *, const ssize_t, const ssize_t, Quantum *, ExceptionInfo *)
MagickExport MagickBooleanType GetOneCacheViewVirtualMethodPixel (const CacheView *, const VirtualPixelMethod, const ssize_t, const ssize_t, Quantum *, ExceptionInfo *)
MagickExport MagickBooleanType GetOneCacheViewVirtualPixel (const CacheView *, const ssize_t, const ssize_t, Quantum *, ExceptionInfo *)
MagickExport MagickBooleanType GetOneCacheViewVirtualPixelInfo (const CacheView *, const ssize_t, const ssize_t, PixelInfo *, ExceptionInfo *)
MagickExport MagickBooleanType SetCacheViewStorageClass (CacheView *, const ClassType, ExceptionInfo *)
MagickExport MagickBooleanType SetCacheViewVirtualPixelMethod (CacheView *, const VirtualPixelMethod)
MagickExport MagickBooleanType SyncCacheViewAuthenticPixels (CacheView *, ExceptionInfo *) magick_hot_spot
MagickExport MagickSizeType GetCacheViewExtent (const CacheView *)
MagickExport Quantum * GetCacheViewAuthenticPixelQueue (CacheView *) magick_hot_spot
MagickExport Quantum * GetCacheViewAuthenticPixels (CacheView *, const ssize_t, const ssize_t, const size_t, const size_t, ExceptionInfo *) magick_hot_spot
MagickExport Quantum * QueueCacheViewAuthenticPixels (CacheView *, const ssize_t, const ssize_t, const size_t, const size_t, ExceptionInfo *) magick_hot_spot
MagickExport void * GetCacheViewAuthenticMetacontent (CacheView *)
Typedef Documentation
typedef struct _CacheView CacheView
Definition at line 48 of file cache-view.h.
Enumeration Type Documentation
enum VirtualPixelMethod
Enumerator
UndefinedVirtualPixelMethod
BackgroundVirtualPixelMethod
DitherVirtualPixelMethod
EdgeVirtualPixelMethod
MirrorVirtualPixelMethod
RandomVirtualPixelMethod
TileVirtualPixelMethod
TransparentVirtualPixelMethod
MaskVirtualPixelMethod
BlackVirtualPixelMethod
GrayVirtualPixelMethod
WhiteVirtualPixelMethod
HorizontalTileVirtualPixelMethod
VerticalTileVirtualPixelMethod
HorizontalTileEdgeVirtualPixelMethod
VerticalTileEdgeVirtualPixelMethod
CheckerTileVirtualPixelMethod
Definition at line 27 of file cache-view.h.
Function Documentation
MagickExport CacheView* AcquireAuthenticCacheView (const Image * , ExceptionInfo *)
MagickExport CacheView * AcquireVirtualCacheView (const Image * , ExceptionInfo *)
MagickExport CacheView * CloneCacheView (const CacheView *)
MagickExport CacheView * DestroyCacheView (CacheView *)
Definition at line 250 of file cache-view.c.
References _CacheView::debug, DestroyImage(), DestroyPixelCacheNexus(), _Image::filename, GetMagickModule, _CacheView::image, LogMagickEvent(), MagickFalse, MagickSignature, _CacheView::nexus_info, _CacheView::number_threads, RelinquishAlignedMemory(), _CacheView::signature, and TraceEvent.
Referenced by AdaptiveBlurImage(), AdaptiveSharpenImage(), AdaptiveThresholdImage(), AddNoiseImage(), AppendImages(), AssignImageColors(), BilevelImage(), BlackThresholdImage(), BlueShiftImage(), ChannelImage(), ChopImage(), ClampImage(), Classify(), ClassifyImageColors(), ClutImage(), ColorDecisionListImage(), ColorizeImage(), ColorMatrixImage(), CombineImages(), CompareImages(), CompositeImage(), CompositeOverImage(), ConsolidateCMYKImages(), ContrastImage(), ContrastStretchImage(), CopyImageRegion(), CropImage(), CycleColormapImage(), DespeckleImage(), DestroyFxInfo(), DestroyImageView(), DestroyResampleFilter(), DirectToColormapImage(), DistortImage(), DitherImage(), DrawAffineImage(), DrawPolygonPrimitive(), DrawPrimitive(), EnhanceImage(), EqualizeImage(), EvaluateImage(), EvaluateImages(), ExcerptImage(), FlipImage(), FloodfillPaintImage(), FlopImage(), FloydSteinbergDither(), FrameImage(), FunctionImage(), FxImage(), GammaImage(), GetAbsoluteDistortion(), GetFuzzDistortion(), GetImageBackgroundColor(), GetImageBoundingBox(), GetImageDepth(), GetImageFeatures(), GetImageKurtosis(), GetImageMask(), GetImageQuantizeError(), GetImageRange(), GetImageTotalInkDensity(), GetMeanAbsoluteDistortion(), GetMeanErrorPerPixel(), GetMeanSquaredDistortion(), GetNormalizedCrossCorrelationDistortion(), GetPeakAbsoluteDistortion(), HaldClutImage(), HorizontalFilter(), HuffmanDecodeImage(), ImplodeImage(), IntegralRotateImage(), InterpolatePixelChannel(), InterpolatePixelChannels(), InterpolatePixelInfo(), InterpolativeResizeImage(), IsEquivalentImage(), IsHighDynamicRangeImage(), IsImageGray(), IsImageMonochrome(), IsImageOpaque(), IsImagesEqual(), LevelImage(), LevelizeImage(), LinearStretchImage(), ModulateImage(), MorphImages(), MorphologyPrimitive(), MorphologyPrimitiveDirect(), MotionBlurImage(), NegateImage(), NewMagickImage(), OilPaintImage(), OpaquePaintImage(), OrderedPosterizeImage(), PerceptibleImage(), PlasmaImage(), PolynomialImage(), PosterizeImage(), ProfileImage(), RadialBlurImage(), RadonTransform(), RaiseImage(), RandomThresholdImage(), RenderPostscript(), ResamplePixelColor(), SampleImage(), ScaleImage(), SelectiveBlurImage(), SeparateImage(), SepiaToneImage(), SetCacheAlphaChannel(), SetGrayscaleImage(), SetImageAlpha(), SetImageAlphaChannel(), SetImageBackgroundColor(), SetImageColor(), SetImageDepth(), SetImageMask(), ShadowImage(), SigmoidalContrastImage(), SignatureImage(), SimilarityImage(), SketchImage(), SmushXGap(), SmushYGap(), SolarizeImage(), SortColormapByIntensity(), SparseColorImage(), SpliceImage(), SpreadImage(), sRGBTransformImage(), StatisticImage(), SteganoImage(), SwirlImage(), SyncImage(), TextureImage(), TintImage(), TransformsRGBImage(), TransparentPaintImage(), TransparentPaintImageChroma(), TransposeImage(), TransverseImage(), UniqueImageColors(), UnsharpMaskImage(), VerticalFilter(), WaveImage(), WhiteThresholdImage(), XShearImage(), and YShearImage().
MagickExport void* GetCacheViewAuthenticMetacontent (CacheView *)
Definition at line 340 of file cache-view.c.
References _Image::cache, GetOpenMPThreadId(), GetPixelCacheNexusMetacontent(), _CacheView::image, MagickSignature, _CacheView::nexus_info, _CacheView::number_threads, and _CacheView::signature.
Referenced by GetImageViewAuthenticMetacontent().
MagickExport Quantum* GetCacheViewAuthenticPixelQueue (CacheView *)
MagickExport Quantum * GetCacheViewAuthenticPixels (CacheView * , const ssize_t , const ssize_t , const size_t , const size_t , ExceptionInfo *)
MagickExport ColorspaceType GetCacheViewColorspace (const CacheView *)
Definition at line 422 of file cache-view.c.
References _Image::cache, _CacheView::debug, _Image::filename, GetMagickModule, GetPixelCacheColorspace(), _CacheView::image, LogMagickEvent(), MagickFalse, MagickSignature, _CacheView::signature, and TraceEvent.
MagickExport MagickSizeType GetCacheViewExtent (const CacheView *)
Definition at line 456 of file cache-view.c.
References _Image::cache, _CacheView::debug, _Image::filename, GetMagickModule, GetOpenMPThreadId(), GetPixelCacheNexusExtent(), _CacheView::image, LogMagickEvent(), MagickFalse, MagickSignature, _CacheView::nexus_info, _CacheView::number_threads, _CacheView::signature, and TraceEvent.
Referenced by ExportQuantumPixels(), and ImportQuantumPixels().
MagickExport const Image* GetCacheViewImage (const CacheView *)
Definition at line 498 of file cache-view.c.
References _CacheView::debug, _Image::filename, GetMagickModule, _CacheView::image, LogMagickEvent(), MagickFalse, MagickSignature, _CacheView::signature, and TraceEvent.
MagickExport ClassType GetCacheViewStorageClass (const CacheView *)
Definition at line 531 of file cache-view.c.
References _Image::cache, _CacheView::debug, _Image::filename, GetMagickModule, GetPixelCacheStorageClass(), _CacheView::image, LogMagickEvent(), MagickFalse, MagickSignature, _CacheView::signature, and TraceEvent.
MagickExport const void* GetCacheViewVirtualMetacontent (const CacheView *)
Definition at line 566 of file cache-view.c.
References _Image::cache, GetOpenMPThreadId(), GetVirtualMetacontentFromNexus(), _CacheView::image, MagickSignature, _CacheView::nexus_info, _CacheView::number_threads, and _CacheView::signature.
Referenced by GetImageViewVirtualMetacontent().
MagickExport const Quantum * GetCacheViewVirtualPixelQueue (const CacheView *)
Definition at line 609 of file cache-view.c.
References _Image::cache, GetOpenMPThreadId(), GetVirtualPixelsNexus(), _CacheView::image, MagickSignature, _CacheView::nexus_info, _CacheView::number_threads, and _CacheView::signature.
Referenced by ExportQuantumPixels(), and GetImageViewVirtualPixels().
MagickExport const Quantum* GetCacheViewVirtualPixels (const CacheView * , const ssize_t , const ssize_t , const size_t , const size_t , ExceptionInfo *)
MagickExport MagickBooleanType GetOneCacheViewAuthenticPixel (const CacheView * , const ssize_t , const ssize_t , Quantum * , ExceptionInfo *)
MagickExport MagickBooleanType GetOneCacheViewVirtualMethodPixel (const CacheView * , const VirtualPixelMethod , const ssize_t , const ssize_t , Quantum * , ExceptionInfo *)
MagickExport MagickBooleanType GetOneCacheViewVirtualPixel (const CacheView * , const ssize_t , const ssize_t , Quantum * , ExceptionInfo *)
MagickExport MagickBooleanType GetOneCacheViewVirtualPixelInfo (const CacheView * , const ssize_t , const ssize_t , PixelInfo * , ExceptionInfo *)
MagickExport Quantum * QueueCacheViewAuthenticPixels (CacheView * , const ssize_t , const ssize_t , const size_t , const size_t , ExceptionInfo *)
Definition at line 985 of file cache-view.c.
References GetOpenMPThreadId(), _CacheView::image, MagickFalse, MagickSignature, _CacheView::nexus_info, _CacheView::number_threads, QueueAuthenticPixelCacheNexus(), and _CacheView::signature.
Referenced by AdaptiveBlurImage(), AdaptiveSharpenImage(), AdaptiveThresholdImage(), AddNoiseImage(), AppendImages(), BlueShiftImage(), ChopImage(), ColorizeImage(), CompareImages(), CompositeImage(), ConsolidateCMYKImages(), CropImage(), DistortImage(), EnhanceImage(), EvaluateImages(), FlipImage(), FlopImage(), FrameImage(), FxImage(), HorizontalFilter(), HuffmanDecodeImage(), ImplodeImage(), IntegralRotateImage(), InterpolativeResizeImage(), MotionBlurImage(), NewMagickImage(), OilPaintImage(), PlasmaImageProxy(), PolynomialImage(), RadialBlurImage(), SampleImage(), ScaleImage(), SelectiveBlurImage(), SeparateImage(), SetImageBackgroundColor(), SetImageColor(), ShadeImage(), ShadowImage(), SketchImage(), SpliceImage(), SpreadImage(), StatisticImage(), SwirlImage(), TextureImage(), TintImage(), TransposeImage(), TransverseImage(), UniqueColorsToImage(), UnsharpMaskImage(), VerticalFilter(), and WaveImage().
MagickExport MagickBooleanType SetCacheViewStorageClass (CacheView * , const ClassType , ExceptionInfo *)
MagickExport MagickBooleanType SetCacheViewVirtualPixelMethod (CacheView * , const VirtualPixelMethod)
MagickExport MagickBooleanType SyncCacheViewAuthenticPixels (CacheView * , ExceptionInfo *)
Definition at line 1107 of file cache-view.c.
References GetOpenMPThreadId(), _CacheView::image, MagickSignature, _CacheView::nexus_info, _CacheView::number_threads, _CacheView::signature, and SyncAuthenticPixelCacheNexus().
Referenced by AdaptiveBlurImage(), AdaptiveSharpenImage(), AdaptiveThresholdImage(), AddNoiseImage(), AppendImages(), AssignImageColors(), BilevelImage(), BlackThresholdImage(), BlueShiftImage(), ChannelImage(), ChopImage(), ClampImage(), Classify(), ClutImage(), ColorDecisionListImage(), ColorizeImage(), ColorMatrixImage(), CombineImages(), CompareImages(), CompositeImage(), CompositeOverImage(), ConsolidateCMYKImages(), ContrastImage(), ContrastStretchImage(), CopyImageRegion(), CropImage(), CycleColormapImage(), DespeckleImage(), DirectToColormapImage(), DistortImage(), DrawAffineImage(), DrawPolygonPrimitive(), DrawPrimitive(), DuplexTransferImageViewIterator(), EnhanceImage(), EqualizeImage(), EvaluateImage(), EvaluateImages(), ExcerptImage(), FlipImage(), FloodfillPaintImage(), FlopImage(), FloydSteinbergDither(), FrameImage(), FunctionImage(), FxImage(), GammaImage(), GetImageMask(), HaldClutImage(), HorizontalFilter(), HuffmanDecodeImage(), ImplodeImage(), IntegralRotateImage(), InterpolativeResizeImage(), LevelImage(), LevelizeImage(), ModulateImage(), MorphImages(), MorphologyPrimitive(), MorphologyPrimitiveDirect(), MotionBlurImage(), NegateImage(), NewMagickImage(), OilPaintImage(), OpaquePaintImage(), OrderedPosterizeImage(), PerceptibleImage(), PlasmaImageProxy(), PolynomialImage(), PosterizeImage(), ProfileImage(), RadialBlurImage(), RaiseImage(), RandomThresholdImage(), RenderPostscript(), RiemersmaDither(), SampleImage(), ScaleImage(), SelectiveBlurImage(), SeparateImage(), SepiaToneImage(), SetCacheAlphaChannel(), SetGrayscaleImage(), SetImageAlpha(), SetImageAlphaChannel(), SetImageBackgroundColor(), SetImageColor(), SetImageDepth(), SetImageMask(), SetImageViewIterator(), ShadeImage(), ShadowImage(), SigmoidalContrastImage(), SimilarityImage(), SketchImage(), SolarizeImage(), SortColormapByIntensity(), SparseColorImage(), SpliceImage(), SpreadImage(), sRGBTransformImage(), StatisticImage(), SteganoImage(), SwirlImage(), SyncImage(), TextureImage(), TintImage(), TransferImageViewIterator(), TransformsRGBImage(), TransparentPaintImage(), TransparentPaintImageChroma(), TransposeImage(), TransverseImage(), UniqueColorsToImage(), UnsharpMaskImage(), UpdateImageViewIterator(), VerticalFilter(), WaveImage(), WhiteThresholdImage(), XShearImage(), and YShearImage().