MagickCore: cache.c File Reference
cache.c File Reference
#include "MagickCore/studio.h"
#include "MagickCore/blob.h"
#include "MagickCore/blob-private.h"
#include "MagickCore/cache.h"
#include "MagickCore/cache-private.h"
#include "MagickCore/color-private.h"
#include "MagickCore/colorspace-private.h"
#include "MagickCore/composite-private.h"
#include "MagickCore/distribute-cache-private.h"
#include "MagickCore/exception.h"
#include "MagickCore/exception-private.h"
#include "MagickCore/geometry.h"
#include "MagickCore/list.h"
#include "MagickCore/log.h"
#include "MagickCore/magick.h"
#include "MagickCore/memory_.h"
#include "MagickCore/memory-private.h"
#include "MagickCore/nt-base-private.h"
#include "MagickCore/option.h"
#include "MagickCore/pixel.h"
#include "MagickCore/pixel-accessor.h"
#include "MagickCore/policy.h"
#include "MagickCore/quantum.h"
#include "MagickCore/random_.h"
#include "MagickCore/registry.h"
#include "MagickCore/resource_.h"
#include "MagickCore/semaphore.h"
#include "MagickCore/splay-tree.h"
#include "MagickCore/string_.h"
#include "MagickCore/string-private.h"
#include "MagickCore/thread-private.h"
#include "MagickCore/utility.h"
#include "MagickCore/utility-private.h"
Data Structures
struct _MagickModulo
Macros
#define CacheTick(offset, extent) QuantumTick((MagickOffsetType) offset,extent)
#define IsFileDescriptorLimitExceeded()
#define MaxCacheThreads 2
#define cache_threads(source, destination, chunk)
Typedefs
typedef struct _MagickModulo MagickModulo
Functions
static Cache GetImagePixelCache (Image *, const MagickBooleanType, ExceptionInfo *)
MagickPrivate NexusInfo ** AcquirePixelCacheNexus (const size_t number_threads)
MagickPrivate const void * AcquirePixelCachePixels (const Image *image, MagickSizeType *length, ExceptionInfo *exception)
MagickPrivate MagickBooleanType CacheComponentGenesis (void)
MagickPrivate void CacheComponentTerminus (void)
MagickPrivate Cache ClonePixelCache (const Cache cache)
MagickPrivate void ClonePixelCacheMethods (Cache clone, const Cache cache)
static MagickSizeType MagickMin (const MagickSizeType x, const MagickSizeType y)
static MagickBooleanType ClonePixelCacheRepository (CacheInfo *restrict clone_info, CacheInfo *restrict cache_info, ExceptionInfo *exception)
static void DestroyImagePixelCache (Image *image)
MagickExport void DestroyImagePixels (Image *image)
static MagickBooleanType ClosePixelCacheOnDisk (CacheInfo *cache_info)
static void RelinquishPixelCachePixels (CacheInfo *cache_info)
MagickPrivate Cache DestroyPixelCache (Cache cache)
static void RelinquishCacheNexusPixels (NexusInfo *nexus_info)
MagickPrivate NexusInfo ** DestroyPixelCacheNexus (NexusInfo **nexus_info, const size_t number_threads)
MagickExport void * GetAuthenticMetacontent (const Image *image)
static void * GetAuthenticMetacontentFromCache (const Image *image)
MagickPrivate Quantum * GetAuthenticPixelCacheNexus (Image *image, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, NexusInfo *nexus_info, ExceptionInfo *exception)
static Quantum * GetAuthenticPixelsFromCache (const Image *image)
MagickExport Quantum * GetAuthenticPixelQueue (const Image *image)
MagickExport Quantum * GetAuthenticPixels (Image *image, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, ExceptionInfo *exception)
static Quantum * GetAuthenticPixelsCache (Image *image, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, ExceptionInfo *exception)
MagickExport MagickSizeType GetImageExtent (const Image *image)
static MagickBooleanType ValidatePixelCacheMorphology (const Image *restrict image)
MagickExport CacheType GetImagePixelCacheType (const Image *image)
MagickExport MagickBooleanType GetOneAuthenticPixel (Image *image, const ssize_t x, const ssize_t y, Quantum *pixel, ExceptionInfo *exception)
static MagickBooleanType GetOneAuthenticPixelFromCache (Image *image, const ssize_t x, const ssize_t y, Quantum *pixel, ExceptionInfo *exception)
MagickExport MagickBooleanType GetOneVirtualPixel (const Image *image, const ssize_t x, const ssize_t y, Quantum *pixel, ExceptionInfo *exception)
static MagickBooleanType GetOneVirtualPixelFromCache (const Image *image, const VirtualPixelMethod virtual_pixel_method, const ssize_t x, const ssize_t y, Quantum *pixel, ExceptionInfo *exception)
MagickExport MagickBooleanType GetOneVirtualPixelInfo (const Image *image, const VirtualPixelMethod virtual_pixel_method, const ssize_t x, const ssize_t y, PixelInfo *pixel, ExceptionInfo *exception)
MagickPrivate ColorspaceType GetPixelCacheColorspace (const Cache cache)
MagickPrivate void GetPixelCacheMethods (CacheMethods *cache_methods)
MagickPrivate MagickSizeType GetPixelCacheNexusExtent (const Cache cache, NexusInfo *restrict nexus_info)
MagickPrivate void * GetPixelCachePixels (Image *image, MagickSizeType *length, ExceptionInfo *exception)
MagickPrivate ClassType GetPixelCacheStorageClass (const Cache cache)
MagickPrivate void GetPixelCacheTileSize (const Image *image, size_t *width, size_t *height)
MagickPrivate VirtualPixelMethod GetPixelCacheVirtualMethod (const Image *image)
static const void * GetVirtualMetacontentFromCache (const Image *image)
MagickPrivate const void * GetVirtualMetacontentFromNexus (const Cache cache, NexusInfo *restrict nexus_info)
MagickExport const void * GetVirtualMetacontent (const Image *image)
static ssize_t DitherX (const ssize_t x, const size_t columns)
static ssize_t DitherY (const ssize_t y, const size_t rows)
static ssize_t EdgeX (const ssize_t x, const size_t columns)
static ssize_t EdgeY (const ssize_t y, const size_t rows)
static ssize_t RandomX (RandomInfo *random_info, const size_t columns)
static ssize_t RandomY (RandomInfo *random_info, const size_t rows)
static MagickModulo VirtualPixelModulo (const ssize_t offset, const size_t extent)
MagickPrivate const Quantum * GetVirtualPixelsFromNexus (const Image *image, const VirtualPixelMethod virtual_pixel_method, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, NexusInfo *nexus_info, ExceptionInfo *exception)
static const Quantum * GetVirtualPixelCache (const Image *image, const VirtualPixelMethod virtual_pixel_method, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, ExceptionInfo *exception)
MagickExport const Quantum * GetVirtualPixelQueue (const Image *image)
MagickExport const Quantum * GetVirtualPixels (const Image *image, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, ExceptionInfo *exception)
static const Quantum * GetVirtualPixelsCache (const Image *image)
MagickPrivate const Quantum * GetVirtualPixelsNexus (const Cache cache, NexusInfo *restrict nexus_info)
static void AllocatePixelCachePixels (CacheInfo *cache_info)
static MagickBooleanType OpenPixelCacheOnDisk (CacheInfo *cache_info, const MapMode mode)
static MagickOffsetType WritePixelCacheRegion (const CacheInfo *restrict cache_info, const MagickOffsetType offset, const MagickSizeType length, const unsigned char *restrict buffer)
static MagickBooleanType SetPixelCacheExtent (Image *image, MagickSizeType length)
static MagickBooleanType OpenPixelCache (Image *image, const MapMode mode, ExceptionInfo *exception)
MagickExport MagickBooleanType PersistPixelCache (Image *image, const char *filename, const MagickBooleanType attach, MagickOffsetType *offset, ExceptionInfo *exception)
MagickPrivate Quantum * QueueAuthenticPixelCacheNexus (Image *image, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, const MagickBooleanType clone, NexusInfo *nexus_info, ExceptionInfo *exception)
static Quantum * QueueAuthenticPixelsCache (Image *image, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, ExceptionInfo *exception)
MagickExport Quantum * QueueAuthenticPixels (Image *image, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, ExceptionInfo *exception)
static MagickOffsetType ReadPixelCacheRegion (const CacheInfo *restrict cache_info, const MagickOffsetType offset, const MagickSizeType length, unsigned char *restrict buffer)
static MagickBooleanType ReadPixelCacheMetacontent (CacheInfo *restrict cache_info, NexusInfo *restrict nexus_info, ExceptionInfo *exception)
static MagickBooleanType ReadPixelCachePixels (CacheInfo *restrict cache_info, NexusInfo *restrict nexus_info, ExceptionInfo *exception)
MagickPrivate Cache ReferencePixelCache (Cache cache)
MagickPrivate void SetPixelCacheMethods (Cache cache, CacheMethods *cache_methods)
static MagickBooleanType AcquireCacheNexusPixels (const CacheInfo *restrict cache_info, NexusInfo *nexus_info, ExceptionInfo *exception)
static MagickBooleanType IsPixelCacheAuthentic (const CacheInfo *restrict cache_info, const NexusInfo *restrict nexus_info)
static void PrefetchPixelCacheNexusPixels (const NexusInfo *nexus_info, const MapMode mode)
static Quantum * SetPixelCacheNexusPixels (const CacheInfo *cache_info, const MapMode mode, const RectangleInfo *region, NexusInfo *nexus_info, ExceptionInfo *exception)
static MagickBooleanType SetCacheAlphaChannel (Image *image, const Quantum alpha, ExceptionInfo *exception)
MagickPrivate VirtualPixelMethod SetPixelCacheVirtualMethod (Image *image, const VirtualPixelMethod virtual_pixel_method, ExceptionInfo *exception)
MagickPrivate MagickBooleanType SyncAuthenticPixelCacheNexus (Image *image, NexusInfo *restrict nexus_info, ExceptionInfo *exception)
static MagickBooleanType SyncAuthenticPixelsCache (Image *image, ExceptionInfo *exception)
MagickExport MagickBooleanType SyncAuthenticPixels (Image *image, ExceptionInfo *exception)
MagickPrivate MagickBooleanType SyncImagePixelCache (Image *image, ExceptionInfo *exception)
static MagickBooleanType WritePixelCacheMetacontent (CacheInfo *cache_info, NexusInfo *restrict nexus_info, ExceptionInfo *exception)
static MagickBooleanType WritePixelCachePixels (CacheInfo *restrict cache_info, NexusInfo *restrict nexus_info, ExceptionInfo *exception)
Variables
static ssize_t DitherMatrix [64]
Macro Definition Documentation
#define cache_threads (source, destination, chunk)
Value:
num_threads((chunk) < (16*GetMagickResourceLimit(ThreadResource)) ? 1 : \
    GetMagickResourceLimit(ThreadResource) < MaxCacheThreads ? \
    GetMagickResourceLimit(ThreadResource) : MaxCacheThreads)
#define CacheTick (offset, extent) QuantumTick((MagickOffsetType) offset,extent)
Definition at line 83 of file cache.c.
Referenced by ReadPixelCacheMetacontent(), ReadPixelCachePixels(), WritePixelCacheMetacontent(), and WritePixelCachePixels().
#define IsFileDescriptorLimitExceeded ()
Value:
(GetMagickResource(FileResource) > \
  GetMagickResourceLimit(FileResource) ? MagickTrue : MagickFalse)
Definition at line 84 of file cache.c.
Referenced by ReadPixelCacheMetacontent(), ReadPixelCachePixels(), WritePixelCacheMetacontent(), and WritePixelCachePixels().
#define MaxCacheThreads 2
Referenced by ClonePixelCacheRepository().
Typedef Documentation
typedef struct _MagickModulo MagickModulo
Function Documentation
static MagickBooleanType AcquireCacheNexusPixels (const CacheInfo *restrict cache_info, NexusInfo * nexus_info, ExceptionInfo * exception) inline static
Definition at line 4474 of file cache.c.
References AcquireAlignedMemory(), _NexusInfo::cache, GetMagickModule, IOMode, _NexusInfo::length, MagickAssumeAligned, MagickFalse, MagickTrue, MapBlob(), _NexusInfo::mapped, ResourceLimitError, and ThrowMagickException().
Referenced by SetPixelCacheNexusPixels().
MagickPrivate NexusInfo** AcquirePixelCacheNexus (const size_t number_threads)
Definition at line 234 of file cache.c.
References AcquireAlignedMemory(), AcquireQuantumMemory(), MagickAssumeAligned, MagickSignature, ResetMagickMemory(), ResourceLimitFatalError, and ThrowFatalException.
MagickPrivate const void* AcquirePixelCachePixels (const Image * image, MagickSizeType * length, ExceptionInfo * exception)
Definition at line 287 of file cache.c.
References _Image::cache, MagickSignature, MapCache, MemoryCache, _ExceptionInfo::signature, and _Image::signature.
static void AllocatePixelCachePixels (CacheInfo * cache_info) inline static
Definition at line 3152 of file cache.c.
References AcquireAlignedMemory(), IOMode, _CacheInfo::length, MagickAssumeAligned, MagickFalse, MagickTrue, MapBlob(), _CacheInfo::mapped, and _CacheInfo::pixels.
Referenced by OpenPixelCache().
MagickPrivate MagickBooleanType CacheComponentGenesis (void)
Definition at line 325 of file cache.c.
References AcquireSemaphoreInfo(), and MagickTrue.
MagickPrivate void CacheComponentTerminus (void)
Definition at line 349 of file cache.c.
References AcquireSemaphoreInfo(), DestroySemaphoreInfo(), LockSemaphoreInfo(), MagickFalse, and UnlockSemaphoreInfo().
MagickPrivate Cache ClonePixelCache (const Cache cache)
Definition at line 381 of file cache.c.
References AcquirePixelCache(), GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, and TraceEvent.
MagickPrivate void ClonePixelCacheMethods (Cache clone, const Cache cache)
Definition at line 427 of file cache.c.
References GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, and TraceEvent.
static MagickBooleanType ClonePixelCacheRepository (CacheInfo *restrict clone_info, CacheInfo *restrict cache_info, ExceptionInfo * exception) static
Definition at line 481 of file cache.c.
References AcquirePixelCacheNexus(), CacheEvent, CommandOptionToMnemonic(), DestroyPixelCacheNexus(), FormatLocaleString(), GetMagickModule, GetOpenMPThreadId(), _RectangleInfo::height, LogMagickEvent(), MagickCacheOptions, MagickFalse, MagickMin(), MagickTrue, MapCache, MaxCacheThreads, MaxTextExtent, MemoryCache, PingCache, ReadMode, ReadPixelCacheMetacontent(), ReadPixelCachePixels(), ResourceLimitFatalError, SetPixelCacheNexusPixels(), ThrowFatalException, UndefinedPixelTrait, _RectangleInfo::width, WriteMode, WritePixelCacheMetacontent(), WritePixelCachePixels(), _RectangleInfo::x, and _RectangleInfo::y.
Referenced by OpenPixelCache(), and PersistPixelCache().
static MagickBooleanType ClosePixelCacheOnDisk (CacheInfo * cache_info) static
Definition at line 788 of file cache.c.
References _CacheInfo::file, FileResource, MagickFalse, MagickTrue, and RelinquishMagickResource().
Referenced by OpenPixelCache(), ReadPixelCacheMetacontent(), ReadPixelCachePixels(), RelinquishPixelCachePixels(), WritePixelCacheMetacontent(), and WritePixelCachePixels().
static void DestroyImagePixelCache (Image * image) static
Definition at line 712 of file cache.c.
References _Image::cache, _Image::debug, DestroyPixelCache(), _Image::filename, GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, _Image::signature, and TraceEvent.
Referenced by GetPixelCacheMethods().
MagickExport void DestroyImagePixels (Image * image)
Definition at line 745 of file cache.c.
References _Image::cache, _Image::debug, DestroyPixelCache(), _Image::filename, GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, _Image::signature, and TraceEvent.
Referenced by DestroyImage().
MagickPrivate Cache DestroyPixelCache (Cache cache)
Definition at line 852 of file cache.c.
References CacheEvent, DestroyDistributeCacheInfo(), DestroyPixelCacheNexus(), DestroyRandomInfo(), DestroySemaphoreInfo(), FormatLocaleString(), GetMagickModule, LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, MagickSignature, MaxTextExtent, RelinquishMagickMemory(), RelinquishPixelCachePixels(), TraceEvent, and UnlockSemaphoreInfo().
MagickPrivate NexusInfo** DestroyPixelCacheNexus (NexusInfo ** nexus_info, const size_t number_threads)
Definition at line 938 of file cache.c.
References MagickSignature, RelinquishAlignedMemory(), RelinquishCacheNexusPixels(), RelinquishMagickMemory(), and _NexusInfo::signature.
Referenced by ClonePixelCacheRepository(), DestroyCacheView(), DestroyPixelCache(), DestroyPixelStream(), and GetVirtualPixelsFromNexus().
static ssize_t DitherX (const ssize_t x, const size_t columns) inline static
Definition at line 2396 of file cache.c.
References DitherMatrix.
Referenced by GetVirtualPixelsFromNexus().
static ssize_t DitherY (const ssize_t y, const size_t rows) inline static
Definition at line 2409 of file cache.c.
References DitherMatrix.
Referenced by GetVirtualPixelsFromNexus().
static ssize_t EdgeX (const ssize_t x, const size_t columns) inline static
Definition at line 2422 of file cache.c.
Referenced by GetVirtualPixelsFromNexus().
static ssize_t EdgeY (const ssize_t y, const size_t rows) inline static
Definition at line 2431 of file cache.c.
Referenced by GetVirtualPixelsFromNexus().
MagickExport void* GetAuthenticMetacontent (const Image * image)
Definition at line 980 of file cache.c.
References _Image::cache, GetOpenMPThreadId(), MagickSignature, and _Image::signature.
Referenced by WriteDistributeCacheMetacontent().
static void* GetAuthenticMetacontentFromCache (const Image * image) static
Definition at line 1031 of file cache.c.
References _Image::cache, GetOpenMPThreadId(), MagickSignature, and _Image::signature.
Referenced by GetPixelCacheMethods().
MagickPrivate Quantum* GetAuthenticPixelCacheNexus (Image * image, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, NexusInfo * nexus_info, ExceptionInfo * exception)
Definition at line 1083 of file cache.c.
References _NexusInfo::authentic_pixel_cache, _Image::cache, MagickFalse, MagickSignature, MagickTrue, QueueAuthenticPixelCacheNexus(), ReadPixelCacheMetacontent(), ReadPixelCachePixels(), and _Image::signature.
MagickExport Quantum* GetAuthenticPixelQueue (const Image * image)
Definition at line 1178 of file cache.c.
References _Image::cache, GetOpenMPThreadId(), MagickSignature, and _Image::signature.
Referenced by ExportQuantumPixels(), ImportQuantumPixels(), and StreamImagePixels().
MagickExport Quantum* GetAuthenticPixels (Image * image, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, ExceptionInfo * exception)
Definition at line 1242 of file cache.c.
References _Image::cache, GetAuthenticPixelCacheNexus(), GetOpenMPThreadId(), MagickSignature, and _Image::signature.
Referenced by ClearBounds(), ImportCharPixel(), ImportDoublePixel(), ImportFloatPixel(), ImportLongLongPixel(), ImportLongPixel(), ImportQuantumPixel(), ImportShortPixel(), WriteDistributeCacheMetacontent(), and WriteDistributeCachePixels().
static Quantum* GetAuthenticPixelsCache (Image * image, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, ExceptionInfo * exception) static
Definition at line 1304 of file cache.c.
References _Image::cache, GetAuthenticPixelCacheNexus(), GetOpenMPThreadId(), MagickSignature, and _Image::signature.
Referenced by GetOneAuthenticPixel(), and GetPixelCacheMethods().
static Quantum* GetAuthenticPixelsFromCache (const Image * image) static
Definition at line 1137 of file cache.c.
References _Image::cache, GetOpenMPThreadId(), MagickSignature, and _Image::signature.
Referenced by GetPixelCacheMethods().
MagickExport MagickSizeType GetImageExtent (const Image * image)
Definition at line 1353 of file cache.c.
References _Image::cache, _Image::debug, _Image::filename, GetMagickModule, GetOpenMPThreadId(), GetPixelCacheNexusExtent(), LogMagickEvent(), MagickFalse, MagickSignature, _Image::signature, and TraceEvent.
Referenced by ExportQuantumPixels(), ImportQuantumPixels(), and StreamImagePixels().
static Cache GetImagePixelCache (Image * image, const MagickBooleanType clone, ExceptionInfo * exception) static
Definition at line 105 of file cache.c.
Referenced by QueueAuthenticPixelCacheNexus(), and SyncImagePixelCache().
MagickExport CacheType GetImagePixelCacheType (const Image * image)
Definition at line 1554 of file cache.c.
References _Image::cache, MagickSignature, and _Image::signature.
Referenced by GetPixelCacheTileSize().
MagickExport MagickBooleanType GetOneAuthenticPixel (Image * image, const ssize_t x, const ssize_t y, Quantum * pixel, ExceptionInfo * exception)
Definition at line 1597 of file cache.c.
References _PixelInfo::alpha, AlphaPixelChannel, _Image::background_color, _PixelInfo::black, BlackPixelChannel, _PixelInfo::blue, BluePixelChannel, _Image::cache, ClampToQuantum(), GetAuthenticPixelsCache(), GetPixelChannelChannel(), GetPixelChannels(), _PixelInfo::green, GreenPixelChannel, MagickFalse, MagickSignature, MagickTrue, MaxPixelChannels, _PixelInfo::red, RedPixelChannel, and _Image::signature.
static MagickBooleanType GetOneAuthenticPixelFromCache (Image * image, const ssize_t x, const ssize_t y, Quantum * pixel, ExceptionInfo * exception) static
Definition at line 1668 of file cache.c.
References _PixelInfo::alpha, AlphaPixelChannel, _Image::background_color, _PixelInfo::black, BlackPixelChannel, _PixelInfo::blue, BluePixelChannel, _Image::cache, ClampToQuantum(), GetAuthenticPixelCacheNexus(), GetOpenMPThreadId(), GetPixelChannelChannel(), GetPixelChannels(), _PixelInfo::green, GreenPixelChannel, MagickFalse, MagickSignature, MagickTrue, MaxPixelChannels, _PixelInfo::red, RedPixelChannel, and _Image::signature.
Referenced by GetPixelCacheMethods().
MagickExport MagickBooleanType GetOneVirtualPixel (const Image * image, const ssize_t x, const ssize_t y, Quantum * pixel, ExceptionInfo * exception)
Definition at line 1740 of file cache.c.
References _PixelInfo::alpha, AlphaPixelChannel, _Image::background_color, _PixelInfo::black, BlackPixelChannel, _PixelInfo::blue, BluePixelChannel, _Image::cache, ClampToQuantum(), GetOpenMPThreadId(), GetPixelCacheVirtualMethod(), GetPixelChannelChannel(), GetPixelChannels(), GetVirtualPixelsFromNexus(), _PixelInfo::green, GreenPixelChannel, MagickFalse, MagickSignature, MagickTrue, MaxPixelChannels, _PixelInfo::red, RedPixelChannel, and _Image::signature.
Referenced by CompositeImage(), and CompositeOverImage().
static MagickBooleanType GetOneVirtualPixelFromCache (const Image * image, const VirtualPixelMethod virtual_pixel_method, const ssize_t x, const ssize_t y, Quantum * pixel, ExceptionInfo * exception) static
Definition at line 1819 of file cache.c.
References _PixelInfo::alpha, AlphaPixelChannel, _Image::background_color, _PixelInfo::black, BlackPixelChannel, _PixelInfo::blue, BluePixelChannel, _Image::cache, ClampToQuantum(), GetOpenMPThreadId(), GetPixelChannelChannel(), GetPixelChannels(), GetVirtualPixelsFromNexus(), _PixelInfo::green, GreenPixelChannel, MagickFalse, MagickSignature, MagickTrue, MaxPixelChannels, _PixelInfo::red, RedPixelChannel, and _Image::signature.
Referenced by GetPixelCacheMethods().
MagickExport MagickBooleanType GetOneVirtualPixelInfo (const Image * image, const VirtualPixelMethod virtual_pixel_method, const ssize_t x, const ssize_t y, PixelInfo * pixel, ExceptionInfo * exception)
Definition at line 1895 of file cache.c.
References _Image::cache, GetOpenMPThreadId(), GetPixelInfo(), GetPixelInfoPixel(), GetVirtualPixelsFromNexus(), MagickFalse, MagickSignature, MagickTrue, and _Image::signature.
Referenced by DrawPrimitive(), GetFillColor(), and GetStrokeColor().
MagickPrivate ColorspaceType GetPixelCacheColorspace (const Cache cache)
Definition at line 1945 of file cache.c.
References GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, and TraceEvent.
Referenced by GetCacheViewColorspace(), and QueueAuthenticPixelsStream().
MagickPrivate void GetPixelCacheMethods (CacheMethods * cache_methods)
Definition at line 1981 of file cache.c.
References _CacheMethods::destroy_pixel_handler, DestroyImagePixelCache(), _CacheMethods::get_authentic_metacontent_from_handler, _CacheMethods::get_authentic_pixels_from_handler, _CacheMethods::get_authentic_pixels_handler, _CacheMethods::get_one_authentic_pixel_from_handler, _CacheMethods::get_one_virtual_pixel_from_handler, _CacheMethods::get_virtual_metacontent_from_handler, _CacheMethods::get_virtual_pixel_handler, _CacheMethods::get_virtual_pixels_handler, GetAuthenticMetacontentFromCache(), GetAuthenticPixelsCache(), GetAuthenticPixelsFromCache(), GetOneAuthenticPixelFromCache(), GetOneVirtualPixelFromCache(), GetVirtualMetacontentFromCache(), GetVirtualPixelCache(), GetVirtualPixelsCache(), _CacheMethods::queue_authentic_pixels_handler, QueueAuthenticPixelsCache(), ResetMagickMemory(), _CacheMethods::sync_authentic_pixels_handler, and SyncAuthenticPixelsCache().
MagickPrivate MagickSizeType GetPixelCacheNexusExtent (const Cache cache, NexusInfo *restrict nexus_info)
Definition at line 2026 of file cache.c.
References MagickSignature.
MagickPrivate void* GetPixelCachePixels (Image * image, MagickSizeType * length, ExceptionInfo * exception)
Definition at line 2071 of file cache.c.
References _Image::cache, MagickSignature, MapCache, MemoryCache, _ExceptionInfo::signature, and _Image::signature.
MagickPrivate ClassType GetPixelCacheStorageClass (const Cache cache)
Definition at line 2116 of file cache.c.
References GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, and TraceEvent.
Referenced by GetCacheViewStorageClass(), and QueueAuthenticPixelsStream().
MagickPrivate void GetPixelCacheTileSize (const Image * image, size_t * width, size_t * height)
Definition at line 2157 of file cache.c.
References _Image::cache, _Image::debug, DiskCache, _Image::filename, GetImagePixelCacheType(), GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, _Image::signature, and TraceEvent.
MagickPrivate VirtualPixelMethod GetPixelCacheVirtualMethod (const Image * image)
Definition at line 2199 of file cache.c.
References _Image::cache, MagickSignature, and _Image::signature.
MagickExport const void* GetVirtualMetacontent (const Image * image)
Definition at line 2321 of file cache.c.
References _Image::cache, GetOpenMPThreadId(), GetVirtualMetacontentFromNexus(), MagickSignature, and _Image::signature.
Referenced by ReadDistributeCacheMetacontent().
static const void* GetVirtualMetacontentFromCache (const Image * image) static
Definition at line 2235 of file cache.c.
References _Image::cache, GetOpenMPThreadId(), GetVirtualMetacontentFromNexus(), MagickSignature, and _Image::signature.
Referenced by GetPixelCacheMethods().
MagickPrivate const void* GetVirtualMetacontentFromNexus (const Cache cache, NexusInfo *restrict nexus_info)
Definition at line 2283 of file cache.c.
References MagickSignature, and UndefinedClass.
static const Quantum* GetVirtualPixelCache (const Image * image, const VirtualPixelMethod virtual_pixel_method, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, ExceptionInfo * exception) static
Definition at line 2898 of file cache.c.
References _Image::cache, GetOpenMPThreadId(), GetVirtualPixelsFromNexus(), MagickSignature, and _Image::signature.
Referenced by GetPixelCacheMethods().
MagickExport const Quantum* GetVirtualPixelQueue (const Image * image)
Definition at line 2945 of file cache.c.
References _Image::cache, GetOpenMPThreadId(), GetVirtualPixelsNexus(), MagickSignature, and _Image::signature.
Referenced by ExportQuantumPixels().
MagickExport const Quantum* GetVirtualPixels (const Image * image, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, ExceptionInfo * exception)
Definition at line 3013 of file cache.c.
References _Image::cache, GetOpenMPThreadId(), GetPixelCacheVirtualMethod(), GetVirtualPixelsFromNexus(), MagickSignature, and _Image::signature.
Referenced by CompareImagesBounds(), ExportCharPixel(), ExportDoublePixel(), ExportFloatPixel(), ExportLongLongPixel(), ExportLongPixel(), ExportQuantumPixel(), ExportShortPixel(), GetImageDynamicThreshold(), GetImageStatistics(), HuffmanEncodeImage(), IdentifyImage(), InitializeHistogram(), IsBoundsCleared(), ReadDistributeCacheMetacontent(), ReadDistributeCachePixels(), and StereoAnaglyphImage().
static const Quantum* GetVirtualPixelsCache (const Image * image) static
Definition at line 3064 of file cache.c.
References _Image::cache, GetOpenMPThreadId(), GetVirtualPixelsNexus(), MagickSignature, and _Image::signature.
Referenced by GetPixelCacheMethods().
MagickPrivate const Quantum* GetVirtualPixelsFromNexus (const Image * image, const VirtualPixelMethod virtual_pixel_method, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, NexusInfo * nexus_info, ExceptionInfo * exception)
Definition at line 2470 of file cache.c.
References AcquirePixelCacheNexus(), AcquireQuantumMemory(), AcquireRandomInfo(), _PixelInfo::alpha, _NexusInfo::authentic_pixel_cache, _Image::background_color, BackgroundVirtualPixelMethod, _PixelInfo::black, BlackVirtualPixelMethod, _PixelInfo::blue, _Image::cache, CacheError, CheckerTileVirtualPixelMethod, ClampToQuantum(), DestroyPixelCacheNexus(), DitherVirtualPixelMethod, DitherX(), DitherY(), EdgeVirtualPixelMethod, EdgeX(), EdgeY(), _Image::filename, GetMagickModule, GetVirtualMetacontentFromNexus(), GetVirtualPixelsFromNexus(), GrayVirtualPixelMethod, _PixelInfo::green, _RectangleInfo::height, HorizontalTileEdgeVirtualPixelMethod, HorizontalTileVirtualPixelMethod, MagickFalse, MagickMin(), MagickSignature, MaskVirtualPixelMethod, MaxPixelChannels, _NexusInfo::metacontent, MirrorVirtualPixelMethod, OpaqueAlpha, QuantumRange, _MagickModulo::quotient, RandomVirtualPixelMethod, RandomX(), RandomY(), ReadMode, ReadPixelCacheMetacontent(), ReadPixelCachePixels(), _PixelInfo::red, _NexusInfo::region, RelinquishMagickMemory(), _MagickModulo::remainder, ResetMagickMemory(), SetPixelAlpha(), SetPixelBlack(), SetPixelBlue(), SetPixelCacheNexusPixels(), SetPixelChannel(), SetPixelGreen(), SetPixelRed(), _Image::signature, ThrowMagickException(), TileVirtualPixelMethod, TransparentAlpha, TransparentVirtualPixelMethod, UndefinedCache, UndefinedVirtualPixelMethod, VerticalTileEdgeVirtualPixelMethod, VerticalTileVirtualPixelMethod, VirtualPixelModulo(), WhiteVirtualPixelMethod, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
MagickPrivate const Quantum* GetVirtualPixelsNexus (const Cache cache, NexusInfo *restrict nexus_info)
Definition at line 3107 of file cache.c.
References MagickSignature, and UndefinedClass.
static MagickBooleanType IsPixelCacheAuthentic (const CacheInfo *restrict cache_info, const NexusInfo *restrict nexus_info) inline static
Definition at line 4499 of file cache.c.
References MagickFalse, MagickTrue, and PingCache.
Referenced by SetPixelCacheNexusPixels().
static MagickSizeType MagickMin (const MagickSizeType x, const MagickSizeType y) inline static
Definition at line 473 of file cache.c.
Referenced by ClonePixelCacheRepository(), GetVirtualPixelsFromNexus(), ReadPixelCacheRegion(), and WritePixelCacheRegion().
static MagickBooleanType OpenPixelCache (Image * image, const MapMode mode, ExceptionInfo * exception) static
Definition at line 3292 of file cache.c.
References AcquireDistributeCacheInfo(), AcquireMagickResource(), AllocatePixelCachePixels(), _Image::alpha_trait, AreaResource, _Image::cache, CacheError, CacheEvent, _Image::channel_map, ClonePixelCacheRepository(), ClosePixelCacheOnDisk(), _Image::colorspace, _Image::columns, CommandOptionToMnemonic(), _Image::debug, DestroyDistributeCacheInfo(), DiskCache, DiskResource, DistributedCache, _Image::filename, FormatLocaleString(), FormatMagickSize(), GetDistributeCacheFile(), GetDistributeCacheHostname(), GetDistributeCachePort(), GetImageIndexInList(), GetMagickModule, GetPixelChannels(), InitializePixelChannelMap(), LogMagickEvent(), MagickCacheOptions, MagickFalse, MagickSignature, MagickTrue, MapBlob(), MapCache, MapResource, MaxPixelChannels, MaxTextExtent, MemoryCache, MemoryResource, _Image::metacontent_extent, _Image::offset, OpenDistributePixelCache(), OpenPixelCacheOnDisk(), _Image::ping, PingCache, _Image::read_mask, ReadMode, RelinquishMagickResource(), RelinquishPixelCachePixels(), ResourceLimitError, _Image::rows, SetPixelCacheExtent(), _Image::signature, _Image::storage_class, ThrowBinaryException, ThrowFileException, ThrowMagickException(), TraceEvent, UndefinedCache, UndefinedClass, and _Image::write_mask.
Referenced by PersistPixelCache().
static MagickBooleanType OpenPixelCacheOnDisk (CacheInfo * cache_info, const MapMode mode) static
Definition at line 3165 of file cache.c.
References AcquireMagickResource(), AcquireUniqueFileResource(), _CacheInfo::cache_filename, _CacheInfo::file, FileResource, IOMode, MagickFalse, MagickTrue, _CacheInfo::mode, O_BINARY, open_utf8(), ReadMode, S_MODE, and WriteMode.
Referenced by OpenPixelCache(), ReadPixelCacheMetacontent(), ReadPixelCachePixels(), WritePixelCacheMetacontent(), and WritePixelCachePixels().
MagickExport MagickBooleanType PersistPixelCache (Image * image, const char * filename, const MagickBooleanType attach, MagickOffsetType * offset, ExceptionInfo * exception)
Definition at line 3609 of file cache.c.
References _Image::cache, CacheEvent, ClonePixelCache(), ClonePixelCacheRepository(), CopyMagickString(), _Image::debug, DestroyPixelCache(), DiskCache, _Image::filename, GetMagickModule, GetMagickPageSize(), IOMode, LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, MapCache, MaxTextExtent, OpenPixelCache(), ReadMode, ReferencePixelCache(), rename_utf8(), _Image::signature, TraceEvent, and UnlockSemaphoreInfo().
static void PrefetchPixelCacheNexusPixels (const NexusInfo * nexus_info, const MapMode mode) inline static
Definition at line 4520 of file cache.c.
References MagickCachePrefetch, _NexusInfo::pixels, and ReadMode.
Referenced by SetPixelCacheNexusPixels().
MagickPrivate Quantum* QueueAuthenticPixelCacheNexus (Image * image, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, const MagickBooleanType clone, NexusInfo * nexus_info, ExceptionInfo * exception)
Definition at line 3742 of file cache.c.
References _Image::cache, CacheError, _Image::filename, GetImagePixelCache(), GetMagickModule, _RectangleInfo::height, MagickSignature, SetPixelCacheNexusPixels(), _Image::signature, ThrowMagickException(), _RectangleInfo::width, WriteMode, _RectangleInfo::x, and _RectangleInfo::y.
Referenced by GetAuthenticPixelCacheNexus(), QueueAuthenticPixels(), QueueAuthenticPixelsCache(), and QueueCacheViewAuthenticPixels().
MagickExport Quantum* QueueAuthenticPixels (Image * image, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, ExceptionInfo * exception)
Definition at line 3911 of file cache.c.
References _Image::cache, GetOpenMPThreadId(), MagickFalse, MagickSignature, QueueAuthenticPixelCacheNexus(), and _Image::signature.
Referenced by StereoAnaglyphImage().
static Quantum* QueueAuthenticPixelsCache (Image * image, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, ExceptionInfo * exception) static
Definition at line 3831 of file cache.c.
References _Image::cache, GetOpenMPThreadId(), MagickFalse, MagickSignature, QueueAuthenticPixelCacheNexus(), and _Image::signature.
Referenced by GetPixelCacheMethods().
static ssize_t RandomX (RandomInfo * random_info, const size_t columns) inline static
Definition at line 2440 of file cache.c.
References GetPseudoRandomValue().
Referenced by GetVirtualPixelsFromNexus().
static ssize_t RandomY (RandomInfo * random_info, const size_t rows) inline static
Definition at line 2445 of file cache.c.
References GetPseudoRandomValue().
Referenced by GetVirtualPixelsFromNexus().
static MagickBooleanType ReadPixelCacheMetacontent (CacheInfo *restrict cache_info, NexusInfo *restrict nexus_info, ExceptionInfo * exception) static
Definition at line 4005 of file cache.c.
References CacheError, CacheEvent, CacheTick, ClosePixelCacheOnDisk(), DiskCache, DistributedCache, FileOpenError, GetMagickModule, _RectangleInfo::height, IOMode, IsFileDescriptorLimitExceeded, LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, MagickMaxBufferExtent, MagickTrue, MapCache, MemoryCache, OpenPixelCacheOnDisk(), ReadDistributePixelCacheMetacontent(), ReadPixelCacheRegion(), ThrowFileException, UnlockSemaphoreInfo(), and _RectangleInfo::y.
Referenced by ClonePixelCacheRepository(), GetAuthenticPixelCacheNexus(), and GetVirtualPixelsFromNexus().
static MagickBooleanType ReadPixelCachePixels (CacheInfo *restrict cache_info, NexusInfo *restrict nexus_info, ExceptionInfo * exception) static
Definition at line 4176 of file cache.c.
References CacheError, CacheEvent, CacheTick, ClosePixelCacheOnDisk(), DiskCache, DistributedCache, FileOpenError, GetMagickModule, _RectangleInfo::height, IOMode, IsFileDescriptorLimitExceeded, LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, MagickMaxBufferExtent, MagickTrue, MapCache, MemoryCache, OpenPixelCacheOnDisk(), ReadDistributePixelCachePixels(), ReadPixelCacheRegion(), ThrowFileException, UnlockSemaphoreInfo(), and _RectangleInfo::y.
Referenced by ClonePixelCacheRepository(), GetAuthenticPixelCacheNexus(), and GetVirtualPixelsFromNexus().
static MagickOffsetType ReadPixelCacheRegion (const CacheInfo *restrict cache_info, const MagickOffsetType offset, const MagickSizeType length, unsigned char *restrict buffer) inline static
Definition at line 3971 of file cache.c.
References MagickMin().
Referenced by ReadPixelCacheMetacontent(), and ReadPixelCachePixels().
MagickPrivate Cache ReferencePixelCache (Cache cache)
Definition at line 4336 of file cache.c.
References LockSemaphoreInfo(), MagickSignature, and UnlockSemaphoreInfo().
Referenced by CloneImage(), CloneImageInfo(), and PersistPixelCache().
static void RelinquishCacheNexusPixels (NexusInfo * nexus_info) inline static
Definition at line 925 of file cache.c.
References _NexusInfo::cache, _NexusInfo::length, MagickFalse, _NexusInfo::mapped, _NexusInfo::metacontent, _NexusInfo::pixels, RelinquishAlignedMemory(), and UnmapBlob().
Referenced by DestroyPixelCacheNexus(), and SetPixelCacheNexusPixels().
static void RelinquishPixelCachePixels (CacheInfo * cache_info) inline static
Definition at line 803 of file cache.c.
References _CacheInfo::cache_filename, ClosePixelCacheOnDisk(), DiskCache, DiskResource, DistributedCache, _CacheInfo::file, _CacheInfo::length, MagickFalse, MapCache, _CacheInfo::mapped, MapResource, MemoryCache, MemoryResource, _CacheInfo::metacontent, _CacheInfo::mode, _CacheInfo::pixels, ReadMode, RelinquishAlignedMemory(), RelinquishDistributePixelCache(), RelinquishMagickResource(), RelinquishUniqueFileResource(), _CacheInfo::server_info, _CacheInfo::type, UndefinedCache, and UnmapBlob().
Referenced by DestroyPixelCache(), and OpenPixelCache().
static MagickBooleanType SetCacheAlphaChannel (Image * image, const Quantum alpha, ExceptionInfo * exception) static
Definition at line 4652 of file cache.c.
References AcquireVirtualCacheView(), _Image::alpha_trait, BlendPixelTrait, _Image::cache, _Image::columns, _Image::debug, DestroyCacheView(), _Image::filename, GetCacheViewAuthenticPixels(), GetMagickModule, GetPixelChannels(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, _Image::rows, SetPixelAlpha(), _Image::signature, SyncCacheViewAuthenticPixels(), and TraceEvent.
Referenced by SetPixelCacheVirtualMethod().
static MagickBooleanType SetPixelCacheExtent (Image * image, MagickSizeType length) static
Definition at line 3246 of file cache.c.
References _Image::cache, CacheEvent, _Image::debug, FormatLocaleString(), FormatMagickSize(), GetMagickModule, LogMagickEvent(), MagickFalse, MagickTrue, MaxTextExtent, and WritePixelCacheRegion().
Referenced by OpenPixelCache().
MagickPrivate void SetPixelCacheMethods (Cache cache, CacheMethods * cache_methods)
Definition at line 4374 of file cache.c.
References _CacheMethods::destroy_pixel_handler, _CacheMethods::get_authentic_metacontent_from_handler, _CacheMethods::get_authentic_pixels_from_handler, _CacheMethods::get_authentic_pixels_handler, _CacheMethods::get_one_authentic_pixel_from_handler, _CacheMethods::get_one_virtual_pixel_from_handler, _CacheMethods::get_virtual_metacontent_from_handler, _CacheMethods::get_virtual_pixel_handler, GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, _CacheMethods::queue_authentic_pixels_handler, _CacheMethods::sync_authentic_pixels_handler, and TraceEvent.
Referenced by ReadStream().
static Quantum* SetPixelCacheNexusPixels (const CacheInfo * cache_info, const MapMode mode, const RectangleInfo * region, NexusInfo * nexus_info, ExceptionInfo * exception) static
Definition at line 4531 of file cache.c.
References AcquireCacheNexusPixels(), _NexusInfo::authentic_pixel_cache, _NexusInfo::cache, _CacheInfo::columns, _RectangleInfo::height, IsPixelCacheAuthentic(), _NexusInfo::length, MagickFalse, MagickSignature, MapCache, MemoryCache, _NexusInfo::metacontent, _CacheInfo::metacontent, _CacheInfo::metacontent_extent, _CacheInfo::number_channels, _NexusInfo::pixels, _CacheInfo::pixels, PrefetchPixelCacheNexusPixels(), _NexusInfo::region, RelinquishCacheNexusPixels(), _CacheInfo::rows, _CacheInfo::signature, _CacheInfo::type, UndefinedCache, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
Referenced by ClonePixelCacheRepository(), GetVirtualPixelsFromNexus(), and QueueAuthenticPixelCacheNexus().
MagickPrivate VirtualPixelMethod SetPixelCacheVirtualMethod (Image * image, const VirtualPixelMethod virtual_pixel_method, ExceptionInfo * exception)
Definition at line 4708 of file cache.c.
References _PixelInfo::alpha_trait, _Image::alpha_trait, _Image::background_color, BackgroundVirtualPixelMethod, BlendPixelTrait, _Image::cache, _Image::colorspace, _Image::columns, _Image::debug, _Image::filename, GetMagickModule, IsGrayColorspace(), IsPixelInfoGray(), LogMagickEvent(), MagickFalse, MagickSignature, OpaqueAlpha, _Image::rows, SetCacheAlphaChannel(), SetImageColorspace(), _Image::signature, sRGBColorspace, TraceEvent, and TransparentVirtualPixelMethod.
Referenced by SetImageVirtualPixelMethod().
MagickPrivate MagickBooleanType SyncAuthenticPixelCacheNexus (Image * image, NexusInfo *restrict nexus_info, ExceptionInfo * exception)
Definition at line 4780 of file cache.c.
References _Image::cache, CacheError, _Image::filename, MagickFalse, MagickSignature, MagickTrue, _Image::signature, ThrowBinaryException, UndefinedCache, WritePixelCacheMetacontent(), and WritePixelCachePixels().
MagickExport MagickBooleanType SyncAuthenticPixels (Image * image, ExceptionInfo * exception)
Definition at line 4887 of file cache.c.
References _Image::cache, GetOpenMPThreadId(), MagickSignature, _Image::signature, and SyncAuthenticPixelCacheNexus().
Referenced by ClearBounds(), ImportCharPixel(), ImportDoublePixel(), ImportFloatPixel(), ImportLongLongPixel(), ImportLongPixel(), ImportQuantumPixel(), ImportShortPixel(), StereoAnaglyphImage(), WriteDistributeCacheMetacontent(), and WriteDistributeCachePixels().
static MagickBooleanType SyncAuthenticPixelsCache (Image * image, ExceptionInfo * exception) static
Definition at line 4837 of file cache.c.
References _Image::cache, GetOpenMPThreadId(), MagickSignature, _Image::signature, and SyncAuthenticPixelCacheNexus().
Referenced by GetPixelCacheMethods().
MagickPrivate MagickBooleanType SyncImagePixelCache (Image * image, ExceptionInfo * exception)
Definition at line 4944 of file cache.c.
References GetImagePixelCache(), MagickFalse, and MagickTrue.
Referenced by AcquireAuthenticCacheView(), IsImageGray(), IsImageMonochrome(), OpenDistributeCache(), SetImageAlphaChannel(), SetImageColorspace(), SetImageExtent(), SetImageMask(), SetImageStorageClass(), and SetPixelMetaChannels().
static MagickBooleanType ValidatePixelCacheMorphology (const Image *restrict image) inline static
Definition at line 1402 of file cache.c.
References MagickFalse, and MagickTrue.
static MagickModulo VirtualPixelModulo (const ssize_t offset, const size_t extent) inline static
Definition at line 2450 of file cache.c.
References _MagickModulo::quotient, and _MagickModulo::remainder.
Referenced by GetVirtualPixelsFromNexus().
static MagickBooleanType WritePixelCacheMetacontent (CacheInfo * cache_info, NexusInfo *restrict nexus_info, ExceptionInfo * exception) static
Definition at line 4984 of file cache.c.
References _CacheInfo::cache_filename, CacheError, CacheEvent, CacheTick, ClosePixelCacheOnDisk(), _CacheInfo::columns, _CacheInfo::debug, DiskCache, DistributedCache, _CacheInfo::file_semaphore, _CacheInfo::filename, FileOpenError, GetMagickModule, _RectangleInfo::height, IOMode, IsFileDescriptorLimitExceeded, LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, MagickMaxBufferExtent, MagickTrue, MapCache, MemoryCache, _CacheInfo::metacontent, _CacheInfo::metacontent_extent, _CacheInfo::number_channels, _CacheInfo::offset, OpenPixelCacheOnDisk(), _CacheInfo::rows, _CacheInfo::server_info, ThrowFileException, _CacheInfo::type, UnlockSemaphoreInfo(), WriteDistributePixelCacheMetacontent(), WritePixelCacheRegion(), and _RectangleInfo::y.
Referenced by ClonePixelCacheRepository(), and SyncAuthenticPixelCacheNexus().
static MagickBooleanType WritePixelCachePixels (CacheInfo *restrict cache_info, NexusInfo *restrict nexus_info, ExceptionInfo * exception) static
Definition at line 5154 of file cache.c.
References CacheError, CacheEvent, CacheTick, ClosePixelCacheOnDisk(), DiskCache, DistributedCache, FileOpenError, GetMagickModule, _RectangleInfo::height, IOMode, IsFileDescriptorLimitExceeded, LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, MagickMaxBufferExtent, MagickTrue, MapCache, MemoryCache, OpenPixelCacheOnDisk(), ThrowFileException, UnlockSemaphoreInfo(), WriteDistributePixelCachePixels(), WritePixelCacheRegion(), and _RectangleInfo::y.
Referenced by ClonePixelCacheRepository(), and SyncAuthenticPixelCacheNexus().
static MagickOffsetType WritePixelCacheRegion (const CacheInfo *restrict cache_info, const MagickOffsetType offset, const MagickSizeType length, const unsigned char *restrict buffer) inline static
Definition at line 3212 of file cache.c.
References MagickMin().
Referenced by SetPixelCacheExtent(), WritePixelCacheMetacontent(), and WritePixelCachePixels().
Variable Documentation
ssize_t DitherMatrix[64] static
Initial value:
=
  {
     0,  48,  12,  60,   3,  51,  15,  63,
    32,  16,  44,  28,  35,  19,  47,  31,
     8,  56,   4,  52,  11,  59,   7,  55,
    40,  24,  36,  20,  43,  27,  39,  23,
     2,  50,  14,  62,   1,  49,  13,  61,
    34,  18,  46,  30,  33,  17,  45,  29,
    10,  58,   6,  54,   9,  57,   5,  53,
    42,  26,  38,  22,  41,  25,  37,  21
  }
Definition at line 2384 of file cache.c.
Referenced by DitherX(), and DitherY().