MagickCore: client.c File Reference
client.c File Reference
#include "MagickCore/studio.h"
#include "MagickCore/client.h"
#include "MagickCore/string_.h"
Functions
MagickExport const char * GetClientName (void)
MagickExport const char * GetClientPath (void)
MagickExport const char * SetClientName (const char *name)
MagickExport const char * SetClientPath (const char *path)
Function Documentation
MagickExport const char* GetClientName (void)
Definition at line 64 of file client.c.
References SetClientName().
Referenced by DefaultErrorHandler(), DefaultFatalErrorHandler(), DefaultWarningHandler(), LocaleFatalErrorHandler(), TranslateEvent(), and TranslateFilename().
MagickExport const char* GetClientPath (void)
Definition at line 87 of file client.c.
References SetClientPath().
Referenced by GetConfigurePaths().
MagickExport const char* SetClientName (const char * name)
Definition at line 114 of file client.c.
References CopyMagickString(), and MaxTextExtent.
Referenced by GetClientName(), and MagickCoreGenesis().
MagickExport const char* SetClientPath (const char * path)
Definition at line 148 of file client.c.
References CopyMagickString(), and MaxTextExtent.
Referenced by GetClientPath(), and MagickCoreGenesis().