MagickCore: coder.c File Reference
coder.c File Reference
#include "MagickCore/studio.h"
#include "MagickCore/blob.h"
#include "MagickCore/client.h"
#include "MagickCore/coder.h"
#include "MagickCore/coder-private.h"
#include "MagickCore/configure.h"
#include "MagickCore/draw.h"
#include "MagickCore/exception.h"
#include "MagickCore/exception-private.h"
#include "MagickCore/hashmap.h"
#include "MagickCore/log.h"
#include "MagickCore/memory_.h"
#include "MagickCore/option.h"
#include "MagickCore/semaphore.h"
#include "MagickCore/string_.h"
#include "MagickCore/splay-tree.h"
#include "MagickCore/token.h"
#include "MagickCore/utility.h"
#include "MagickCore/utility-private.h"
#include "MagickCore/xml-tree.h"
Data Structures
struct _CoderMapInfo
Macros
#define MagickCoderFilename "coder.xml"
Typedefs
typedef struct _CoderMapInfo CoderMapInfo
Functions
static MagickBooleanType InitializeCoderList (ExceptionInfo *)
static MagickBooleanType LoadCoderLists (const char *, ExceptionInfo *)
MagickPrivate MagickBooleanType CoderComponentGenesis (void)
MagickPrivate void CoderComponentTerminus (void)
MagickExport const CoderInfo * GetCoderInfo (const char *name, ExceptionInfo *exception)
static int CoderInfoCompare (const void *x, const void *y)
MagickExport const CoderInfo ** GetCoderInfoList (const char *pattern, size_t *number_coders, ExceptionInfo *exception)
static int CoderCompare (const void *x, const void *y)
MagickExport char ** GetCoderList (const char *pattern, size_t *number_coders, ExceptionInfo *exception)
MagickExport MagickBooleanType ListCoderInfo (FILE *file, ExceptionInfo *exception)
static void * DestroyCoderNode (void *coder_info)
static MagickBooleanType LoadCoderList (const char *xml, const char *filename, const size_t depth, ExceptionInfo *exception)
Variables
static const CoderMapInfo CoderMap []
static SemaphoreInfo * coder_semaphore = (SemaphoreInfo *) NULL
static SplayTreeInfo * coder_list = (SplayTreeInfo *) NULL
static volatile MagickBooleanType instantiate_coder = MagickFalse
Macro Definition Documentation
#define MagickCoderFilename "coder.xml"
Definition at line 66 of file coder.c.
Referenced by InitializeCoderList().
Typedef Documentation
typedef struct _CoderMapInfo CoderMapInfo
Function Documentation
static int CoderCompare (const void * x, const void * y) static
Definition at line 457 of file coder.c.
References LocaleCompare().
Referenced by GetCoderList().
MagickPrivate MagickBooleanType CoderComponentGenesis (void)
Definition at line 263 of file coder.c.
References AcquireSemaphoreInfo(), coder_semaphore, and MagickTrue.
Referenced by MagickCoreGenesis().
MagickPrivate void CoderComponentTerminus (void)
Definition at line 287 of file coder.c.
References AcquireSemaphoreInfo(), coder_list, coder_semaphore, DestroySemaphoreInfo(), DestroySplayTree(), instantiate_coder, LockSemaphoreInfo(), MagickFalse, and UnlockSemaphoreInfo().
Referenced by MagickCoreTerminus().
static int CoderInfoCompare (const void * x, const void * y) static
Definition at line 370 of file coder.c.
References LocaleCompare().
Referenced by GetCoderInfoList().
static void* DestroyCoderNode (void * coder_info) static
Definition at line 661 of file coder.c.
References DestroyString(), _CoderInfo::exempt, _CoderInfo::magick, MagickFalse, _CoderInfo::name, _CoderInfo::path, and RelinquishMagickMemory().
Referenced by LoadCoderList(), and LoadCoderLists().
MagickExport const CoderInfo* GetCoderInfo (const char * name, ExceptionInfo * exception)
Definition at line 324 of file coder.c.
References coder_list, GetNextValueInSplayTree(), GetNumberOfNodesInSplayTree(), GetValueFromSplayTree(), InitializeCoderList(), instantiate_coder, LocaleCompare(), MagickFalse, and ResetSplayTreeIterator().
Referenced by GetCoderInfoList(), and GetCoderList().
MagickExport const CoderInfo** GetCoderInfoList (const char * pattern, size_t * number_coders, ExceptionInfo * exception)
Definition at line 383 of file coder.c.
References AcquireQuantumMemory(), coder_list, coder_semaphore, CoderInfoCompare(), GetCoderInfo(), GetMagickModule, GetNextValueInSplayTree(), GetNumberOfNodesInSplayTree(), GlobExpression(), LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, _CoderInfo::name, ResetSplayTreeIterator(), _CoderInfo::stealth, TraceEvent, and UnlockSemaphoreInfo().
Referenced by ListCoderInfo().
MagickExport char** GetCoderList (const char * pattern, size_t * number_coders, ExceptionInfo * exception)
Definition at line 468 of file coder.c.
References AcquireQuantumMemory(), coder_list, coder_semaphore, CoderCompare(), ConstantString(), GetCoderInfo(), GetMagickModule, GetNextValueInSplayTree(), GetNumberOfNodesInSplayTree(), GlobExpression(), LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, _CoderInfo::name, ResetSplayTreeIterator(), _CoderInfo::stealth, TraceEvent, and UnlockSemaphoreInfo().
static MagickBooleanType InitializeCoderList (ExceptionInfo * exception) static
Definition at line 536 of file coder.c.
References AcquireSemaphoreInfo(), coder_list, coder_semaphore, instantiate_coder, LoadCoderLists(), LockSemaphoreInfo(), MagickCoderFilename, MagickFalse, MagickTrue, and UnlockSemaphoreInfo().
Referenced by GetCoderInfo().
MagickExport MagickBooleanType ListCoderInfo (FILE * file, ExceptionInfo * exception)
Definition at line 579 of file coder.c.
References FormatLocaleFile(), GetCoderInfoList(), LocaleCompare(), MagickFalse, MagickTrue, _CoderInfo::path, and RelinquishMagickMemory().
static MagickBooleanType LoadCoderList (const char * xml, const char * filename, const size_t depth, ExceptionInfo * exception) static
Definition at line 679 of file coder.c.
References AcquireMagickMemory(), AcquireString(), AddValueToSplayTree(), coder_list, CompareSplayTreeString(), ConcatenateMagickString(), ConfigureError, ConfigureEvent, ConstantString(), CopyMagickString(), DestroyCoderNode(), DirectorySeparator, _CoderInfo::exempt, FileToString(), GetMagickModule, GetMagickToken(), GetPathComponent(), HeadPath, IsStringTrue(), LocaleCompare(), LocaleNCompare(), LogMagickEvent(), _CoderInfo::magick, MagickFalse, MagickSignature, MagickTrue, MaxTextExtent, _CoderInfo::name, NewSplayTree(), _CoderInfo::path, RelinquishMagickMemory(), ResetMagickMemory(), ResourceLimitError, ResourceLimitFatalError, _CoderInfo::signature, _CoderInfo::stealth, ThrowFatalException, ThrowFileException, and ThrowMagickException().
Referenced by LoadCoderLists().
static MagickBooleanType LoadCoderLists (const char * filename, ExceptionInfo * exception)
Definition at line 882 of file coder.c.
References AcquireMagickMemory(), AddValueToSplayTree(), coder_list, CoderMap, CompareSplayTreeString(), ConstantString(), DestroyCoderNode(), DestroyConfigureOptions(), _CoderInfo::exempt, GetConfigureOptions(), GetMagickModule, GetNextValueInLinkedList(), GetStringInfoDatum(), GetStringInfoPath(), LoadCoderList(), _CoderInfo::magick, _CoderMapInfo::magick, MagickFalse, MagickSignature, MagickTrue, _CoderInfo::name, _CoderMapInfo::name, NewSplayTree(), _CoderInfo::path, RelinquishMagickMemory(), ResetMagickMemory(), ResourceLimitError, _CoderInfo::signature, ThrowFileException, and ThrowMagickException().
Referenced by InitializeCoderList().
Variable Documentation
SplayTreeInfo* coder_list = (SplayTreeInfo *) NULL static
Definition at line 233 of file coder.c.
Referenced by CoderComponentTerminus(), GetCoderInfo(), GetCoderInfoList(), GetCoderList(), InitializeCoderList(), LoadCoderList(), and LoadCoderLists().
SemaphoreInfo* coder_semaphore = (SemaphoreInfo *) NULL static
Definition at line 230 of file coder.c.
Referenced by CoderComponentGenesis(), CoderComponentTerminus(), GetCoderInfoList(), GetCoderList(), and InitializeCoderList().
const CoderMapInfo CoderMap[] static
Definition at line 82 of file coder.c.
Referenced by LoadCoderLists().
volatile MagickBooleanType instantiate_coder = MagickFalse static
Definition at line 236 of file coder.c.
Referenced by CoderComponentTerminus(), GetCoderInfo(), and InitializeCoderList().