MagickCore: coder.h File Reference
coder.h File Reference
Data Structures
struct _CoderInfo
Typedefs
typedef struct _CoderInfo CoderInfo
Functions
MagickExport char ** GetCoderList (const char *, size_t *, ExceptionInfo *)
MagickExport const CoderInfo * GetCoderInfo (const char *, ExceptionInfo *)
MagickExport const CoderInfo ** GetCoderInfoList (const char *, size_t *, ExceptionInfo *)
MagickExport MagickBooleanType ListCoderInfo (FILE *, ExceptionInfo *)
Typedef Documentation
typedef struct _CoderInfo CoderInfo
Function Documentation
MagickExport const CoderInfo* GetCoderInfo (const char * , ExceptionInfo *)
MagickExport const CoderInfo ** GetCoderInfoList (const char * , size_t * , ExceptionInfo *)
Definition at line 383 of file coder.c.
References AcquireQuantumMemory(), coder_list, coder_semaphore, CoderInfoCompare(), GetCoderInfo(), GetMagickModule, GetNextValueInSplayTree(), GetNumberOfNodesInSplayTree(), GlobExpression(), LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, _CoderInfo::name, ResetSplayTreeIterator(), _CoderInfo::stealth, TraceEvent, and UnlockSemaphoreInfo().
Referenced by ListCoderInfo().
MagickExport char** GetCoderList (const char * , size_t * , ExceptionInfo *)
Definition at line 468 of file coder.c.
References AcquireQuantumMemory(), coder_list, coder_semaphore, CoderCompare(), ConstantString(), GetCoderInfo(), GetMagickModule, GetNextValueInSplayTree(), GetNumberOfNodesInSplayTree(), GlobExpression(), LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, _CoderInfo::name, ResetSplayTreeIterator(), _CoderInfo::stealth, TraceEvent, and UnlockSemaphoreInfo().
MagickExport MagickBooleanType ListCoderInfo (FILE * , ExceptionInfo *)
Definition at line 579 of file coder.c.
References FormatLocaleFile(), GetCoderInfoList(), LocaleCompare(), MagickFalse, MagickTrue, _CoderInfo::path, and RelinquishMagickMemory().