MagickCore: colorspace-private.h File Reference
colorspace-private.h File Reference
#include "MagickCore/image.h"
#include "MagickCore/image-private.h"
#include "MagickCore/pixel.h"
#include "MagickCore/pixel-accessor.h"
Functions
static void ConvertRGBToCMYK (PixelInfo *pixel)
static MagickBooleanType IsCMYKColorspace (const ColorspaceType colorspace)
static MagickBooleanType IsGrayColorspace (const ColorspaceType colorspace)
static MagickBooleanType IsRGBColorspace (const ColorspaceType colorspace)
static MagickBooleanType IssRGBColorspace (const ColorspaceType colorspace)
static MagickBooleanType IssRGBCompatibleColorspace (const ColorspaceType colorspace)
Function Documentation
static void ConvertRGBToCMYK (PixelInfo * pixel) inline static
Definition at line 30 of file colorspace-private.h.
References _PixelInfo::black, _PixelInfo::blue, CMYKColorspace, _PixelInfo::colorspace, DecodePixelGamma(), _PixelInfo::green, MagickEpsilon, QuantumRange, QuantumScale, _PixelInfo::red, and sRGBColorspace.
Referenced by DistortImage(), and sRGBTransformImage().
static MagickBooleanType IsCMYKColorspace (const ColorspaceType colorspace) inline static
Definition at line 77 of file colorspace-private.h.
References CMYKColorspace, MagickFalse, and MagickTrue.
static MagickBooleanType IsGrayColorspace (const ColorspaceType colorspace) inline static
Definition at line 85 of file colorspace-private.h.
References GRAYColorspace, MagickFalse, and MagickTrue.
Referenced by AnnotateImage(), BilevelImage(), BlackThresholdImage(), ChannelFxImage(), ClutImage(), ColorizeImage(), CompositeImage(), DistortImage(), DrawPrimitive(), FloodfillPaintImage(), FrameImage(), IsImageGray(), IsImageMonochrome(), LevelImageColors(), OpaquePaintImage(), SetImageBackgroundColor(), SetImageColorspace(), SetPixelCacheVirtualMethod(), ShadowImage(), SolarizeImage(), TintImage(), and WhiteThresholdImage().
static MagickBooleanType IsRGBColorspace (const ColorspaceType colorspace) inline static
Definition at line 93 of file colorspace-private.h.
References MagickFalse, MagickTrue, RGBColorspace, and scRGBColorspace.
Referenced by SetImageColorspace().
static MagickBooleanType IssRGBColorspace (const ColorspaceType colorspace) inline static
Definition at line 100 of file colorspace-private.h.
References MagickFalse, MagickTrue, sRGBColorspace, and TransparentColorspace.
Referenced by QueryColorname(), SetImageProperty(), and TransformImageColorspace().
static MagickBooleanType IssRGBCompatibleColorspace (const ColorspaceType colorspace) inline static
Definition at line 108 of file colorspace-private.h.
References GRAYColorspace, MagickFalse, MagickTrue, RGBColorspace, scRGBColorspace, sRGBColorspace, and TransparentColorspace.
Referenced by AssignImageColors(), ClassifyImageColors(), IsImageGray(), IsImageMonochrome(), ModulateImage(), ProfileImage(), and SetImageType().