MagickCore: colorspace.h File Reference
colorspace.h File Reference
Enumerations
enum ColorspaceType {
UndefinedColorspace, CMYColorspace, CMYKColorspace, GRAYColorspace,
HCLColorspace, HSBColorspace, HSLColorspace, HWBColorspace,
LabColorspace, LCHColorspace, LogColorspace, LMSColorspace,
LuvColorspace, OHTAColorspace, Rec601LumaColorspace, Rec601YCbCrColorspace,
Rec709LumaColorspace, Rec709YCbCrColorspace, RGBColorspace, sRGBColorspace,
TransparentColorspace, XYZColorspace, YCbCrColorspace, YCCColorspace,
YIQColorspace, YPbPrColorspace, YUVColorspace
}
Functions
MagickExport MagickBooleanType SetImageColorspace (Image *, const ColorspaceType, ExceptionInfo *)
MagickExport MagickBooleanType TransformImageColorspace (Image *, const ColorspaceType, ExceptionInfo *)
Enumeration Type Documentation
enum ColorspaceType
Enumerator
UndefinedColorspace
CMYColorspace
CMYKColorspace
GRAYColorspace
HCLColorspace
HSBColorspace
HSLColorspace
HWBColorspace
LabColorspace
LCHColorspace
LogColorspace
LMSColorspace
LuvColorspace
OHTAColorspace
Rec601LumaColorspace
Rec601YCbCrColorspace
Rec709LumaColorspace
Rec709YCbCrColorspace
RGBColorspace
sRGBColorspace
TransparentColorspace
XYZColorspace
YCbCrColorspace
YCCColorspace
YIQColorspace
YPbPrColorspace
YUVColorspace
Definition at line 25 of file colorspace.h.
Function Documentation
MagickExport MagickBooleanType SetImageColorspace (Image * , const ColorspaceType , ExceptionInfo *)
MagickExport MagickBooleanType TransformImageColorspace (Image * , const ColorspaceType , ExceptionInfo *)
Definition at line 1774 of file colorspace.c.
References _Image::colorspace, _Image::debug, DeleteImageProfile(), _Image::filename, GetMagickModule, IssRGBColorspace(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, SetImageColorspace(), _Image::signature, sRGBTransformImage(), TraceEvent, TransformsRGBImage(), and UndefinedColorspace.
Referenced by AddNoiseImage(), AnnotateImage(), AppendImages(), AssignImageColors(), BilevelImage(), BlackThresholdImage(), ChannelFxImage(), ClassifyImageColors(), ClutImage(), CombineImages(), DistortImage(), FloodfillPaintImage(), HaldClutImage(), ModulateImage(), OilPaintImage(), OpaquePaintImage(), SegmentImage(), SelectiveBlurImage(), SetGrayscaleImage(), SetImageBackgroundColor(), SetImageType(), SetPixelCacheVirtualMethod(), ShadeImage(), ShadowImage(), TextureImage(), VignetteImage(), and WhiteThresholdImage().