MagickCore: color-private.h File Reference
color-private.h File Reference
#include "MagickCore/image.h"
Functions
MagickPrivate MagickBooleanType ColorComponentGenesis (void)
MagickPrivate void ColorComponentTerminus (void)
Function Documentation
MagickPrivate MagickBooleanType ColorComponentGenesis (void)
Definition at line 821 of file color.c.
References AcquireSemaphoreInfo(), color_semaphore, and MagickTrue.
Referenced by MagickCoreGenesis().
MagickPrivate void ColorComponentTerminus (void)
Definition at line 863 of file color.c.
References AcquireSemaphoreInfo(), color_list, color_semaphore, DestroyColorElement(), DestroyLinkedList(), DestroySemaphoreInfo(), instantiate_color, LockSemaphoreInfo(), MagickFalse, and UnlockSemaphoreInfo().
Referenced by MagickCoreTerminus().