MagickCore: color.h File Reference
color.h File Reference
#include "MagickCore/pixel.h"
#include "MagickCore/exception.h"
Data Structures
struct _ColorInfo
struct _ErrorInfo
Typedefs
typedef struct _ColorInfo ColorInfo
typedef struct _ErrorInfo ErrorInfo
Enumerations
enum ComplianceType {
UndefinedCompliance, NoCompliance = 0x0000, SVGCompliance = 0x0001, X11Compliance = 0x0002,
XPMCompliance = 0x0004, AllCompliance = 0x7fffffff
}
Functions
MagickExport char ** GetColorList (const char *, size_t *, ExceptionInfo *)
MagickExport const ColorInfo * GetColorInfo (const char *, ExceptionInfo *)
MagickExport const ColorInfo ** GetColorInfoList (const char *, size_t *, ExceptionInfo *)
MagickExport MagickBooleanType IsEquivalentAlpha (const Image *, const PixelInfo *, const PixelInfo *)
MagickExport MagickBooleanType IsEquivalentImage (const Image *, const Image *, ssize_t *x, ssize_t *y, ExceptionInfo *)
MagickExport MagickBooleanType ListColorInfo (FILE *, ExceptionInfo *)
MagickExport MagickBooleanType QueryColorCompliance (const char *, const ComplianceType, PixelInfo *, ExceptionInfo *)
MagickExport MagickBooleanType QueryColorname (const Image *, const PixelInfo *, const ComplianceType, char *, ExceptionInfo *)
MagickExport void ConcatenateColorComponent (const PixelInfo *, const PixelChannel, const ComplianceType, char *)
MagickExport void GetColorTuple (const PixelInfo *, const MagickBooleanType, char *)
Typedef Documentation
typedef struct _ColorInfo ColorInfo
typedef struct _ErrorInfo ErrorInfo
Enumeration Type Documentation
enum ComplianceType
Enumerator
UndefinedCompliance
NoCompliance
SVGCompliance
X11Compliance
XPMCompliance
AllCompliance
Definition at line 28 of file color.h.
Function Documentation
MagickExport void ConcatenateColorComponent (const PixelInfo * , const PixelChannel , const ComplianceType , char *)
MagickExport const ColorInfo* GetColorInfo (const char * , ExceptionInfo *)
MagickExport const ColorInfo ** GetColorInfoList (const char * , size_t * , ExceptionInfo *)
Definition at line 1163 of file color.c.
References AcquireQuantumMemory(), color_list, color_semaphore, ColorInfoCompare(), GetColorInfo(), GetMagickModule, GetNextValueInLinkedList(), GetNumberOfElementsInLinkedList(), GlobExpression(), LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, _ColorInfo::name, ResetLinkedListIterator(), _ColorInfo::stealth, TraceEvent, and UnlockSemaphoreInfo().
Referenced by ListColorInfo().
MagickExport char** GetColorList (const char * , size_t * , ExceptionInfo *)
Definition at line 1256 of file color.c.
References AcquireQuantumMemory(), color_list, color_semaphore, ColorCompare(), ConstantString(), GetColorInfo(), GetMagickModule, GetNextValueInLinkedList(), GetNumberOfElementsInLinkedList(), GlobExpression(), LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, _ColorInfo::name, ResetLinkedListIterator(), _ColorInfo::stealth, TraceEvent, and UnlockSemaphoreInfo().
MagickExport void GetColorTuple (const PixelInfo * , const MagickBooleanType , char *)
Definition at line 1399 of file color.c.
References _PixelInfo::alpha, _PixelInfo::alpha_trait, AlphaPixelChannel, _PixelInfo::black, BlackPixelChannel, BlendPixelTrait, _PixelInfo::blue, BluePixelChannel, CMYKColorspace, _PixelInfo::colorspace, CommandOptionToMnemonic(), ConcatenateColorComponent(), ConcatenateMagickString(), ConcatentateHexColorComponent(), _PixelInfo::depth, GetMagickModule, GRAYColorspace, GrayPixelChannel, _PixelInfo::green, GreenPixelChannel, LocaleLower(), LogMagickEvent(), MagickColorspaceOptions, MagickEpsilon, MagickFalse, MagickTrue, MaxTextExtent, OpaqueAlpha, _PixelInfo::red, RedPixelChannel, SVGCompliance, SVGCompliant, and TraceEvent.
Referenced by GetNumberColors(), IdentifyImage(), ListColorInfo(), and QueryColorname().
MagickExport MagickBooleanType IsEquivalentAlpha (const Image * , const PixelInfo * , const PixelInfo *)
MagickExport MagickBooleanType IsEquivalentImage (const Image * , const Image * , ssize_t * x, ssize_t * y, ExceptionInfo *)
MagickExport MagickBooleanType ListColorInfo (FILE * , ExceptionInfo *)
MagickExport MagickBooleanType QueryColorCompliance (const char * , const ComplianceType , PixelInfo * , ExceptionInfo *)
MagickExport MagickBooleanType QueryColorname (const Image * , const PixelInfo * , const ComplianceType , char * , ExceptionInfo *)
Definition at line 2500 of file color.c.
References _PixelInfo::alpha, _PixelInfo::alpha_trait, _Image::alpha_trait, BlendPixelTrait, _PixelInfo::blue, _ColorInfo::color, color_list, _PixelInfo::colorspace, _ColorInfo::compliance, CopyMagickString(), _PixelInfo::depth, _Image::depth, GetColorInfo(), GetColorTuple(), GetNextValueInLinkedList(), _PixelInfo::green, IssRGBColorspace(), MagickEpsilon, MagickFalse, MagickMin(), MagickTrue, MaxTextExtent, _ColorInfo::name, OpaqueAlpha, _PixelInfo::red, ResetLinkedListIterator(), SVGCompliance, UndefinedPixelTrait, and XPMCompliance.
Referenced by GetImageProperty(), GetNumberColors(), and IdentifyImage().