MagickCore: colorspace.c File Reference
colorspace.c File Reference
#include "MagickCore/studio.h"
#include "MagickCore/property.h"
#include "MagickCore/cache.h"
#include "MagickCore/cache-private.h"
#include "MagickCore/cache-view.h"
#include "MagickCore/color.h"
#include "MagickCore/color-private.h"
#include "MagickCore/colorspace.h"
#include "MagickCore/colorspace-private.h"
#include "MagickCore/exception.h"
#include "MagickCore/exception-private.h"
#include "MagickCore/image.h"
#include "MagickCore/image-private.h"
#include "MagickCore/gem.h"
#include "MagickCore/gem-private.h"
#include "MagickCore/memory_.h"
#include "MagickCore/monitor.h"
#include "MagickCore/monitor-private.h"
#include "MagickCore/pixel-accessor.h"
#include "MagickCore/pixel-private.h"
#include "MagickCore/quantize.h"
#include "MagickCore/quantum.h"
#include "MagickCore/quantum-private.h"
#include "MagickCore/resource_.h"
#include "MagickCore/string_.h"
#include "MagickCore/string-private.h"
#include "MagickCore/utility.h"
Data Structures
struct _TransformPacket
Macros
#define sRGBTransformImageTag "RGBTransform/Image"
#define DisplayGamma (1.0/1.7)
#define FilmGamma 0.6
#define ReferenceBlack 95.0
#define ReferenceWhite 685.0
#define TransformsRGBImageTag "Transform/Image"
Typedefs
typedef struct _TransformPacket TransformPacket
Functions
static MagickBooleanType TransformsRGBImage (Image *, ExceptionInfo *)
static void ConvertRGBToCMY (const double red, const double green, const double blue, double *cyan, double *magenta, double *yellow)
static void ConvertXYZToLMS (const double x, const double y, const double z, double *L, double *M, double *S)
static void ConvertRGBToLMS (const double red, const double green, const double blue, double *L, double *M, double *S)
static void ConvertRGBToLab (const double red, const double green, const double blue, double *L, double *a, double *b)
static void ConvertRGBToLuv (const double red, const double green, const double blue, double *L, double *u, double *v)
static void ConvertRGBToYDbDr (const double red, const double green, const double blue, double *Y, double *Db, double *Dr)
static void ConvertRGBToYIQ (const double red, const double green, const double blue, double *Y, double *I, double *Q)
static void ConvertRGBToYPbPr (const double red, const double green, const double blue, double *Y, double *Pb, double *Pr)
static void ConvertRGBToYCbCr (const double red, const double green, const double blue, double *Y, double *Cb, double *Cr)
static void ConvertRGBToYUV (const double red, const double green, const double blue, double *Y, double *U, double *V)
static MagickBooleanType sRGBTransformImage (Image *image, const ColorspaceType colorspace, ExceptionInfo *exception)
MagickExport MagickBooleanType SetImageColorspace (Image *image, const ColorspaceType colorspace, ExceptionInfo *exception)
MagickExport MagickBooleanType TransformImageColorspace (Image *image, const ColorspaceType colorspace, ExceptionInfo *exception)
static void ConvertCMYToRGB (const double cyan, const double magenta, const double yellow, double *red, double *green, double *blue)
static void ConvertLMSToXYZ (const double L, const double M, const double S, double *X, double *Y, double *Z)
static void ConvertLMSToRGB (const double L, const double M, const double S, double *red, double *green, double *blue)
static void ConvertLuvToRGB (const double L, const double u, const double v, double *red, double *green, double *blue)
static ssize_t RoundToYCC (const double value)
static void ConvertCMYKToRGB (PixelInfo *pixel)
static void ConvertLabToRGB (const double L, const double a, const double b, double *red, double *green, double *blue)
static void ConvertYPbPrToRGB (const double Y, const double Pb, const double Pr, double *red, double *green, double *blue)
static void ConvertYCbCrToRGB (const double Y, const double Cb, const double Cr, double *red, double *green, double *blue)
static void ConvertYIQToRGB (const double Y, const double I, const double Q, double *red, double *green, double *blue)
static void ConvertYDbDrToRGB (const double Y, const double Db, const double Dr, double *red, double *green, double *blue)
static void ConvertYUVToRGB (const double Y, const double U, const double V, double *red, double *green, double *blue)
Macro Definition Documentation
#define DisplayGamma (1.0/1.7)
Referenced by sRGBTransformImage(), and TransformsRGBImage().
#define FilmGamma 0.6
Referenced by sRGBTransformImage(), and TransformsRGBImage().
#define ReferenceBlack 95.0
Referenced by sRGBTransformImage(), and TransformsRGBImage().
#define ReferenceWhite 685.0
Referenced by sRGBTransformImage(), and TransformsRGBImage().
#define sRGBTransformImageTag "RGBTransform/Image"
Referenced by sRGBTransformImage().
#define TransformsRGBImageTag "Transform/Image"
Referenced by TransformsRGBImage().
Typedef Documentation
typedef struct _TransformPacket TransformPacket
Function Documentation
static void ConvertCMYKToRGB (PixelInfo * pixel) inline static
Definition at line 1225 of file colorspace.c.
References _PixelInfo::black, _PixelInfo::blue, _PixelInfo::green, QuantumRange, QuantumScale, and _PixelInfo::red.
Referenced by TransformsRGBImage().
static void ConvertCMYToRGB (const double cyan, const double magenta, const double yellow, double * red, double * green, double * blue) inline static
Definition at line 1176 of file colorspace.c.
References QuantumRange.
Referenced by TransformsRGBImage().
static void ConvertLabToRGB (const double L, const double a, const double b, double * red, double * green, double * blue) inline static
Definition at line 1235 of file colorspace.c.
References ConvertLabToXYZ(), and ConvertXYZToRGB().
Referenced by TransformsRGBImage().
static void ConvertLMSToRGB (const double L, const double M, const double S, double * red, double * green, double * blue) inline static
Definition at line 1192 of file colorspace.c.
References ConvertLMSToXYZ(), and ConvertXYZToRGB().
Referenced by TransformsRGBImage().
static void ConvertLMSToXYZ (const double L, const double M, const double S, double * X, double * Y, double * Z) inline static
Definition at line 1184 of file colorspace.c.
Referenced by ConvertLMSToRGB().
static void ConvertLuvToRGB (const double L, const double u, const double v, double * red, double * green, double * blue) inline static
Definition at line 1204 of file colorspace.c.
References ConvertLuvToXYZ(), and ConvertXYZToRGB().
Referenced by TransformsRGBImage().
static void ConvertRGBToCMY (const double red, const double green, const double blue, double * cyan, double * magenta, double * yellow) inline static
Definition at line 118 of file colorspace.c.
References QuantumRange, and QuantumScale.
Referenced by sRGBTransformImage().
static void ConvertRGBToLab (const double red, const double green, const double blue, double * L, double * a, double * b) static
Definition at line 146 of file colorspace.c.
References ConvertRGBToXYZ(), and ConvertXYZToLab().
Referenced by sRGBTransformImage().
static void ConvertRGBToLMS (const double red, const double green, const double blue, double * L, double * M, double * S) static
Definition at line 134 of file colorspace.c.
References ConvertRGBToXYZ(), and ConvertXYZToLMS().
Referenced by sRGBTransformImage().
static void ConvertRGBToLuv (const double red, const double green, const double blue, double * L, double * u, double * v) static
Definition at line 158 of file colorspace.c.
References ConvertRGBToXYZ(), and ConvertXYZToLuv().
Referenced by sRGBTransformImage().
static void ConvertRGBToYCbCr (const double red, const double green, const double blue, double * Y, double * Cb, double * Cr) static
Definition at line 194 of file colorspace.c.
References ConvertRGBToYPbPr().
Referenced by sRGBTransformImage().
static void ConvertRGBToYDbDr (const double red, const double green, const double blue, double * Y, double * Db, double * Dr) static
Definition at line 170 of file colorspace.c.
References QuantumScale.
Referenced by sRGBTransformImage().
static void ConvertRGBToYIQ (const double red, const double green, const double blue, double * Y, double * I, double * Q) static
Definition at line 178 of file colorspace.c.
References QuantumScale.
Referenced by sRGBTransformImage().
static void ConvertRGBToYPbPr (const double red, const double green, const double blue, double * Y, double * Pb, double * Pr) static
Definition at line 186 of file colorspace.c.
References QuantumScale.
Referenced by ConvertRGBToYCbCr(), and sRGBTransformImage().
static void ConvertRGBToYUV (const double red, const double green, const double blue, double * Y, double * U, double * V) static
Definition at line 200 of file colorspace.c.
References QuantumScale.
Referenced by sRGBTransformImage().
static void ConvertXYZToLMS (const double x, const double y, const double z, double * L, double * M, double * S) inline static
Definition at line 126 of file colorspace.c.
Referenced by ConvertRGBToLMS().
static void ConvertYCbCrToRGB (const double Y, const double Cb, const double Cr, double * red, double * green, double * blue) static
Definition at line 1258 of file colorspace.c.
References ConvertYPbPrToRGB().
Referenced by TransformsRGBImage().
static void ConvertYDbDrToRGB (const double Y, const double Db, const double Dr, double * red, double * green, double * blue) static
Definition at line 1275 of file colorspace.c.
References QuantumRange.
Referenced by TransformsRGBImage().
static void ConvertYIQToRGB (const double Y, const double I, const double Q, double * red, double * green, double * blue) static
Definition at line 1264 of file colorspace.c.
References QuantumRange.
Referenced by TransformsRGBImage().
static void ConvertYPbPrToRGB (const double Y, const double Pb, const double Pr, double * red, double * green, double * blue) static
Definition at line 1247 of file colorspace.c.
References QuantumRange.
Referenced by ConvertYCbCrToRGB(), and TransformsRGBImage().
static void ConvertYUVToRGB (const double Y, const double U, const double V, double * red, double * green, double * blue) static
Definition at line 1286 of file colorspace.c.
References QuantumRange.
Referenced by TransformsRGBImage().
static ssize_t RoundToYCC (const double value) inline static
Definition at line 1216 of file colorspace.c.
Referenced by TransformsRGBImage().
MagickExport MagickBooleanType SetImageColorspace (Image * image, const ColorspaceType colorspace, ExceptionInfo * exception)
Definition at line 1046 of file colorspace.c.
References _ChromaticityInfo::blue_primary, _Image::chromaticity, _Image::colorspace, _Image::gamma, GrayscaleType, _ChromaticityInfo::green_primary, _Image::intensity, IsGrayColorspace(), IsRGBColorspace(), MagickFalse, MagickTrue, PerceptualIntent, Rec601LuminancePixelIntensityMethod, Rec709LuminancePixelIntensityMethod, _ChromaticityInfo::red_primary, _Image::rendering_intent, ResetMagickMemory(), SyncImagePixelCache(), _Image::type, UndefinedIntent, _ChromaticityInfo::white_point, _PrimaryInfo::x, _PrimaryInfo::y, and _PrimaryInfo::z.
Referenced by AnnotateImage(), BilevelImage(), BlackThresholdImage(), ChannelFxImage(), ClutImage(), ColorizeImage(), CombineImages(), CompositeImage(), ConsolidateCMYKImages(), ContrastStretchImage(), DistortImage(), DrawPrimitive(), FloodfillPaintImage(), FrameImage(), GetImageMask(), GradientImage(), GrayscaleImage(), ImportImagePixels(), LevelImageColors(), ModulateImage(), OpaquePaintImage(), ProfileImage(), SeparateImage(), SetPixelCacheVirtualMethod(), ShadowImage(), SolarizeImage(), sRGBTransformImage(), StereoAnaglyphImage(), TintImage(), TransformImageColorspace(), and TransformsRGBImage().
static MagickBooleanType sRGBTransformImage (Image * image, const ColorspaceType colorspace, ExceptionInfo * exception) static
Definition at line 208 of file colorspace.c.
References AcquireAuthenticCacheView(), AcquireQuantumMemory(), _Image::alpha_trait, BlendPixelTrait, _PixelInfo::blue, ClampToQuantum(), CMYColorspace, CMYKColorspace, _Image::colormap, _Image::colors, ColorSeparationMatteType, ColorSeparationType, _Image::columns, ConvertRGBToCMY(), ConvertRGBToCMYK(), ConvertRGBToHCL(), ConvertRGBToHCLp(), ConvertRGBToHSB(), ConvertRGBToHSI(), ConvertRGBToHSL(), ConvertRGBToHSV(), ConvertRGBToHWB(), ConvertRGBToLab(), ConvertRGBToLCHab(), ConvertRGBToLCHuv(), ConvertRGBToLMS(), ConvertRGBToLuv(), ConvertRGBToXYZ(), ConvertRGBToYCbCr(), ConvertRGBToYDbDr(), ConvertRGBToYIQ(), ConvertRGBToYPbPr(), ConvertRGBToYUV(), _Image::debug, DecodePixelGamma(), DestroyCacheView(), DirectClass, DisplayGamma, _Image::filename, FilmGamma, GetCacheViewAuthenticPixels(), GetImageProperty(), GetMagickModule, GetPixelBlue(), GetPixelChannels(), GetPixelGreen(), GetPixelInfo(), GetPixelInfoPixel(), GetPixelIntensity(), GetPixelRed(), GRAYColorspace, GrayscaleType, _PixelInfo::green, HCLColorspace, HCLpColorspace, HSBColorspace, HSIColorspace, HSLColorspace, HSVColorspace, HWBColorspace, LabColorspace, LCHabColorspace, LCHColorspace, LCHuvColorspace, LMSColorspace, LogColorspace, LogMagickEvent(), LuvColorspace, MagickFalse, MagickSignature, MagickTrue, MaxMap, OHTAColorspace, PerceptibleReciprocal(), _Image::progress_monitor, PseudoClass, QuantumRange, Rec601YCbCrColorspace, Rec709YCbCrColorspace, _PixelInfo::red, ReferenceBlack, ReferenceWhite, RelinquishMagickMemory(), ResetMagickMemory(), ResourceLimitError, RGBColorspace, _Image::rows, scRGBColorspace, SetImageColorspace(), SetImageProgress(), SetImageStorageClass(), SetPixelBlue(), SetPixelGray(), SetPixelGreen(), SetPixelInfoPixel(), SetPixelRed(), _Image::signature, sRGBColorspace, sRGBTransformImageTag, _Image::storage_class, StringToDouble(), SyncCacheViewAuthenticPixels(), SyncImage(), ThrowBinaryException, TraceEvent, TransparentColorspace, _Image::type, UndefinedColorspace, _TransformPacket::x, _PrimaryInfo::x, XYZColorspace, _TransformPacket::y, _PrimaryInfo::y, YCbCrColorspace, YCCColorspace, YDbDrColorspace, YIQColorspace, YPbPrColorspace, YUVColorspace, _TransformPacket::z, and _PrimaryInfo::z.
Referenced by TransformImageColorspace().
MagickExport MagickBooleanType TransformImageColorspace (Image * image, const ColorspaceType colorspace, ExceptionInfo * exception)
Definition at line 1113 of file colorspace.c.
References _Image::colorspace, _Image::debug, DeleteImageProfile(), _Image::filename, GetMagickModule, IssRGBColorspace(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, SetImageColorspace(), _Image::signature, sRGBTransformImage(), TraceEvent, TransformsRGBImage(), and UndefinedColorspace.
Referenced by AppendImages(), AssignImageColors(), ClassifyImageColors(), SegmentImage(), SelectiveBlurImage(), SetGrayscaleImage(), SetImageBackgroundColor(), SetImageType(), TextureImage(), VignetteImage(), and WhiteThresholdImage().
static MagickBooleanType TransformsRGBImage (Image * image, ExceptionInfo * exception) static
Definition at line 1297 of file colorspace.c.
References AcquireAuthenticCacheView(), AcquireQuantumMemory(), _PixelInfo::blue, ClampToQuantum(), CMYColorspace, CMYKColorspace, _Image::colormap, _Image::colors, _Image::colorspace, _Image::columns, ConvertCMYKToRGB(), ConvertCMYToRGB(), ConvertHCLpToRGB(), ConvertHCLToRGB(), ConvertHSBToRGB(), ConvertHSIToRGB(), ConvertHSLToRGB(), ConvertHSVToRGB(), ConvertHWBToRGB(), ConvertLabToRGB(), ConvertLCHabToRGB(), ConvertLCHuvToRGB(), ConvertLMSToRGB(), ConvertLuvToRGB(), ConvertXYZToRGB(), ConvertYCbCrToRGB(), ConvertYDbDrToRGB(), ConvertYIQToRGB(), ConvertYPbPrToRGB(), ConvertYUVToRGB(), _Image::debug, DestroyCacheView(), DirectClass, DisplayGamma, EncodePixelGamma(), _Image::filename, FilmGamma, GetCacheViewAuthenticPixels(), GetImageProperty(), GetMagickModule, GetPixelBlue(), GetPixelChannels(), GetPixelGray(), GetPixelGreen(), GetPixelInfo(), GetPixelInfoPixel(), GetPixelRed(), GRAYColorspace, _PixelInfo::green, HCLColorspace, HCLpColorspace, HSBColorspace, HSIColorspace, HSLColorspace, HSVColorspace, HWBColorspace, LabColorspace, LCHabColorspace, LCHColorspace, LCHuvColorspace, LMSColorspace, LogColorspace, LogMagickEvent(), LuvColorspace, MagickFalse, MagickSignature, MagickTrue, MaxMap, OHTAColorspace, PerceptibleReciprocal(), _Image::progress_monitor, PseudoClass, QuantumRange, QuantumScale, Rec601YCbCrColorspace, Rec709YCbCrColorspace, _PixelInfo::red, ReferenceBlack, ReferenceWhite, RelinquishMagickMemory(), ResourceLimitError, RGBColorspace, RoundToYCC(), _Image::rows, scRGBColorspace, SetImageColorspace(), SetImageProgress(), SetImageStorageClass(), SetPixelBlue(), SetPixelGreen(), SetPixelInfoPixel(), SetPixelRed(), _Image::signature, sRGBColorspace, _Image::storage_class, StringToDouble(), SyncCacheViewAuthenticPixels(), SyncImage(), ThrowBinaryException, TraceEvent, TransformsRGBImageTag, _TransformPacket::x, XYZColorspace, _TransformPacket::y, YCbCrColorspace, YCCColorspace, YDbDrColorspace, YIQColorspace, YPbPrColorspace, YUVColorspace, and _TransformPacket::z.
Referenced by TransformImageColorspace().