MagickCore: composite.c File Reference
composite.c File Reference
#include "MagickCore/studio.h"
#include "MagickCore/artifact.h"
#include "MagickCore/cache.h"
#include "MagickCore/cache-private.h"
#include "MagickCore/cache-view.h"
#include "MagickCore/channel.h"
#include "MagickCore/client.h"
#include "MagickCore/color.h"
#include "MagickCore/color-private.h"
#include "MagickCore/colorspace.h"
#include "MagickCore/colorspace-private.h"
#include "MagickCore/composite.h"
#include "MagickCore/composite-private.h"
#include "MagickCore/constitute.h"
#include "MagickCore/draw.h"
#include "MagickCore/fx.h"
#include "MagickCore/gem.h"
#include "MagickCore/geometry.h"
#include "MagickCore/image.h"
#include "MagickCore/image-private.h"
#include "MagickCore/list.h"
#include "MagickCore/log.h"
#include "MagickCore/monitor.h"
#include "MagickCore/monitor-private.h"
#include "MagickCore/memory_.h"
#include "MagickCore/option.h"
#include "MagickCore/pixel-accessor.h"
#include "MagickCore/property.h"
#include "MagickCore/quantum.h"
#include "MagickCore/resample.h"
#include "MagickCore/resource_.h"
#include "MagickCore/string_.h"
#include "MagickCore/thread-private.h"
#include "MagickCore/threshold.h"
#include "MagickCore/token.h"
#include "MagickCore/utility.h"
#include "MagickCore/utility-private.h"
#include "MagickCore/version.h"
Macros
#define CompositeImageTag "Composite/Image"
#define CompositeImageTag "Composite/Image"
#define TextureImageTag "Texture/Image"
Functions
static MagickRealType MagickMin (const MagickRealType x, const MagickRealType y)
static MagickRealType MagickMax (const MagickRealType x, const MagickRealType y)
static MagickRealType ConvertHueToRGB (MagickRealType m1, MagickRealType m2, MagickRealType hue)
static void HCLComposite (const MagickRealType hue, const MagickRealType chroma, const MagickRealType luma, MagickRealType *red, MagickRealType *green, MagickRealType *blue)
static void CompositeHCL (const MagickRealType red, const MagickRealType green, const MagickRealType blue, MagickRealType *hue, MagickRealType *chroma, MagickRealType *luma)
static MagickBooleanType CompositeOverImage (Image *image, const Image *composite_image, const MagickBooleanType clip_to_self, const ssize_t x_offset, const ssize_t y_offset, ExceptionInfo *exception)
MagickExport MagickBooleanType CompositeImage (Image *image, const Image *composite, const CompositeOperator compose, const MagickBooleanType clip_to_self, const ssize_t x_offset, const ssize_t y_offset, ExceptionInfo *exception)
MagickExport MagickBooleanType TextureImage (Image *image, const Image *texture, ExceptionInfo *exception)
Macro Definition Documentation
#define CompositeImageTag "Composite/Image"
Referenced by CompositeImage(), and CompositeOverImage().
#define CompositeImageTag "Composite/Image"
#define TextureImageTag "Texture/Image"
Referenced by TextureImage().
Function Documentation
static void CompositeHCL (const MagickRealType red, const MagickRealType green, const MagickRealType blue, MagickRealType * hue, MagickRealType * chroma, MagickRealType * luma) static
Definition at line 292 of file composite.c.
References MagickMax(), MagickMin(), and QuantumScale.
Referenced by CompositeImage().
MagickExport MagickBooleanType CompositeImage (Image * image, const Image * composite, const CompositeOperator compose, const MagickBooleanType clip_to_self, const ssize_t x_offset, const ssize_t y_offset, ExceptionInfo * exception)
Definition at line 547 of file composite.c.
References AcquireAuthenticCacheView(), AcquireResampleFilter(), AcquireVirtualCacheView(), _PixelInfo::alpha, _Image::alpha_trait, AlphaCompositeOp, AlphaPixelChannel, AspectValue, AtopCompositeOp, BlackPixelChannel, BlendCompositeOp, BlendPixelTrait, _PixelInfo::blue, BluePixelChannel, BlurCompositeOp, BumpmapCompositeOp, ChangeMaskCompositeOp, ClampToQuantum(), ClearCompositeOp, CloneImage(), ColorBurnCompositeOp, ColorDodgeCompositeOp, ColorizeCompositeOp, _Image::colorspace, _Image::columns, CompositeHCL(), CompositeImageTag, CompositeOverImage(), CopyAlphaCompositeOp, CopyBlackCompositeOp, CopyBlueCompositeOp, CopyCompositeOp, CopyCyanCompositeOp, CopyGreenCompositeOp, CopyMagentaCompositeOp, CopyPixelTrait, CopyRedCompositeOp, CopyYellowCompositeOp, DarkenCompositeOp, DarkenIntensityCompositeOp, _Image::debug, DegreesToRadians(), DestroyCacheView(), DestroyImage(), DestroyResampleFilter(), DifferenceCompositeOp, DirectClass, DisplaceCompositeOp, DissolveCompositeOp, DistortCompositeOp, DivideDstCompositeOp, DivideSrcCompositeOp, DstAtopCompositeOp, DstCompositeOp, DstInCompositeOp, DstOutCompositeOp, DstOverCompositeOp, ExclusionCompositeOp, _Image::filename, GaussianFilter, GetCacheViewAuthenticPixels(), GetCacheViewVirtualPixels(), GetImageArtifact(), GetMagickModule, GetOneVirtualPixel(), GetPixelAlpha(), GetPixelBlack(), GetPixelBlue(), GetPixelChannel(), GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelGreen(), GetPixelInfo(), GetPixelInfoPixel(), GetPixelIntensity(), GetPixelReadMask(), GetPixelRed(), _PixelInfo::green, GreenPixelChannel, HardLightCompositeOp, HCLComposite(), HeightValue, HueCompositeOp, InCompositeOp, IntensityCompositeOp, InterpolatePixelInfo(), IsFuzzyEquivalencePixel(), IsGrayColorspace(), LightenCompositeOp, LightenIntensityCompositeOp, LinearBurnCompositeOp, LinearDodgeCompositeOp, LinearLightCompositeOp, LogMagickEvent(), LuminizeCompositeOp, MagickEpsilon, MagickFalse, MagickMin(), MagickSignature, MagickTrue, MathematicsCompositeOp, MaxPixelChannels, MinusDstCompositeOp, MinusSrcCompositeOp, ModulateCompositeOp, ModulusAddCompositeOp, ModulusSubtractCompositeOp, MultiplyCompositeOp, NoCompositeOp, NoValue, OpaqueAlpha, OpaqueAlphaChannel, OptionWarning, OutCompositeOp, OverCompositeOp, OverlayCompositeOp, ParseGeometry(), PegtopLightCompositeOp, PercentValue, PerceptibleReciprocal(), PinLightCompositeOp, PlusCompositeOp, _Image::progress_monitor, _GeometryInfo::psi, QuantumRange, QuantumScale, QueueCacheViewAuthenticPixels(), _PixelInfo::red, RedPixelChannel, ReplaceCompositeOp, ResamplePixelColor(), _GeometryInfo::rho, RoundToUnity(), _Image::rows, SaturateCompositeOp, ScaleResampleFilter(), ScreenCompositeOp, SetAlphaChannel, SetGeometryInfo(), SetImageAlphaChannel(), SetImageColorspace(), SetImageProgress(), SetImageStorageClass(), SetPixelChannel(), SetPixelInfoPixel(), SetResampleFilter(), _GeometryInfo::sigma, SigmaValue, _Image::signature, SoftLightCompositeOp, SrcAtopCompositeOp, SrcCompositeOp, SrcInCompositeOp, SrcOutCompositeOp, SrcOverCompositeOp, sRGBColorspace, SyncCacheViewAuthenticPixels(), ThresholdCompositeOp, ThrowMagickException(), TraceEvent, TransparentAlpha, UndefinedInterpolatePixel, UndefinedPixelTrait, VividLightCompositeOp, WidthValue, _PointInfo::x, _SegmentInfo::x1, _SegmentInfo::x2, _GeometryInfo::xi, XorCompositeOp, XValue, _PointInfo::y, _SegmentInfo::y1, _SegmentInfo::y2, and YValue.
Referenced by CoalesceImages(), CompareImages(), CompareImagesLayers(), CompositeCanvas(), DisposeImages(), DistortResizeImage(), DrawPrimitive(), ExtentImage(), FrameImage(), MergeImageLayers(), MontageImageList(), MorphologyApply(), OptimizeImageTransparency(), PolaroidImage(), RenderPostscript(), SetImageAlphaChannel(), SketchImage(), SmushImages(), TextureImage(), and VignetteImage().
static MagickBooleanType CompositeOverImage (Image * image, const Image * composite_image, const MagickBooleanType clip_to_self, const ssize_t x_offset, const ssize_t y_offset, ExceptionInfo * exception) static
Definition at line 332 of file composite.c.
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), AlphaPixelChannel, ClampToQuantum(), _Image::columns, CompositeImageTag, CopyPixelTrait, DestroyCacheView(), GetCacheViewAuthenticPixels(), GetCacheViewVirtualPixels(), GetOneVirtualPixel(), GetPixelAlpha(), GetPixelChannel(), GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelReadMask(), MagickFalse, MagickTrue, MaxPixelChannels, PerceptibleReciprocal(), _Image::progress_monitor, QuantumRange, QuantumScale, _Image::rows, SetImageProgress(), SyncCacheViewAuthenticPixels(), and UndefinedPixelTrait.
Referenced by CompositeImage().
static MagickRealType ConvertHueToRGB (MagickRealType m1, MagickRealType m2, MagickRealType hue) inline static
Definition at line 197 of file composite.c.
static void HCLComposite (const MagickRealType hue, const MagickRealType chroma, const MagickRealType luma, MagickRealType * red, MagickRealType * green, MagickRealType * blue) static
Definition at line 213 of file composite.c.
References QuantumRange.
Referenced by CompositeImage().
static MagickRealType MagickMax (const MagickRealType x, const MagickRealType y) inline static
Definition at line 189 of file composite.c.
Referenced by CompositeHCL().
static MagickRealType MagickMin (const MagickRealType x, const MagickRealType y) inline static
Definition at line 181 of file composite.c.
Referenced by CompositeHCL(), and CompositeImage().
MagickExport MagickBooleanType TextureImage (Image * image, const Image * texture, ExceptionInfo * exception)
Definition at line 2348 of file composite.c.
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), _Image::alpha_trait, BlendPixelTrait, CloneImage(), _Image::colorspace, _Image::columns, _Image::compose, CompositeImage(), CopyCompositeOp, _Image::debug, DestroyCacheView(), DestroyImage(), DirectClass, GetCacheViewVirtualPixels(), GetMagickModule, GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelReadMask(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, OverCompositeOp, _Image::progress_monitor, QueueCacheViewAuthenticPixels(), _Image::rows, SetImageProgress(), SetImageStorageClass(), SetImageVirtualPixelMethod(), SetPixelChannel(), _Image::signature, SyncCacheViewAuthenticPixels(), TextureImageTag, _Image::tile_offset, TileVirtualPixelMethod, TraceEvent, TransformImageColorspace(), UndefinedPixelTrait, _RectangleInfo::x, and _RectangleInfo::y.
Referenced by MontageImageList().