MagickCore: composite-private.h File Reference
composite-private.h File Reference
#include "MagickCore/color.h"
#include "MagickCore/image.h"
#include "MagickCore/image-private.h"
#include "MagickCore/pixel-accessor.h"
#include "MagickCore/pixel-private.h"
Functions
static double MagickOver_ (const double p, const double alpha, const double q, const double beta)
static void CompositePixelOver (const Image *image, const PixelInfo *p, const double alpha, const Quantum *q, const double beta, Quantum *composite)
static void CompositePixelInfoOver (const PixelInfo *p, const double alpha, const PixelInfo *q, const double beta, PixelInfo *composite)
static double RoundToUnity (const double value)
static void CompositePixelInfoPlus (const PixelInfo *p, const double alpha, const PixelInfo *q, const double beta, PixelInfo *composite)
static void CompositePixelInfoAreaBlend (const PixelInfo *p, const double alpha, const PixelInfo *q, const double beta, const double area, PixelInfo *composite)
static void CompositePixelInfoBlend (const PixelInfo *p, const double alpha, const PixelInfo *q, const double beta, PixelInfo *composite)
Function Documentation
static void CompositePixelInfoAreaBlend (const PixelInfo * p, const double alpha, const PixelInfo * q, const double beta, const double area, PixelInfo * composite) inline static
Definition at line 178 of file composite-private.h.
References CompositePixelInfoPlus().
Referenced by HaldClutImage(), XShearImage(), and YShearImage().
static void CompositePixelInfoBlend (const PixelInfo * p, const double alpha, const PixelInfo * q, const double beta, PixelInfo * composite) inline static
Definition at line 189 of file composite-private.h.
References _PixelInfo::alpha, and CompositePixelInfoPlus().
Referenced by DistortImage(), and DrawGradientImage().
static void CompositePixelInfoOver (const PixelInfo * p, const double alpha, const PixelInfo * q, const double beta, PixelInfo * composite) inline static
Definition at line 122 of file composite-private.h.
References _PixelInfo::alpha, _PixelInfo::black, _PixelInfo::blue, CMYKColorspace, _PixelInfo::colorspace, _PixelInfo::green, MagickEpsilon, MagickOver_(), PerceptibleReciprocal(), QuantumRange, QuantumScale, _PixelInfo::red, and TransparentAlpha.
Referenced by DrawAffineImage().
static void CompositePixelInfoPlus (const PixelInfo * p, const double alpha, const PixelInfo * q, const double beta, PixelInfo * composite) inline static
Definition at line 155 of file composite-private.h.
References _PixelInfo::alpha, _PixelInfo::black, _PixelInfo::blue, CMYKColorspace, _PixelInfo::colorspace, _PixelInfo::green, PerceptibleReciprocal(), QuantumRange, QuantumScale, _PixelInfo::red, and RoundToUnity().
Referenced by CompositePixelInfoAreaBlend(), and CompositePixelInfoBlend().
static void CompositePixelOver (const Image * image, const PixelInfo * p, const double alpha, const Quantum * q, const double beta, Quantum * composite) inline static
Definition at line 47 of file composite-private.h.
References AlphaPixelChannel, _PixelInfo::black, BlackPixelChannel, _PixelInfo::blue, BluePixelChannel, ClampToQuantum(), GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), _PixelInfo::green, GreenPixelChannel, MagickEpsilon, MagickOver_(), PerceptibleReciprocal(), QuantumRange, QuantumScale, _PixelInfo::red, RedPixelChannel, TransparentAlpha, and UndefinedPixelTrait.
Referenced by DrawPolygonPrimitive(), and DrawPrimitive().
static double MagickOver_ (const double p, const double alpha, const double q, const double beta) inline static
Definition at line 35 of file composite-private.h.
References QuantumScale.
Referenced by CompositePixelInfoOver(), CompositePixelOver(), and FlattenPixelInfo().
static double RoundToUnity (const double value) inline static
Definition at line 150 of file composite-private.h.
Referenced by CompositeImage(), and CompositePixelInfoPlus().