MagickCore: composite.h File Reference
composite.h File Reference
Enumerations
enum CompositeOperator {
AlphaCompositeOp, AtopCompositeOp, BlendCompositeOp, BlurCompositeOp,
BumpmapCompositeOp, ChangeMaskCompositeOp, ClearCompositeOp, ColorBurnCompositeOp,
ColorDodgeCompositeOp, ColorizeCompositeOp, CopyBlackCompositeOp, CopyBlueCompositeOp,
CopyCompositeOp, CopyCyanCompositeOp, CopyGreenCompositeOp, CopyMagentaCompositeOp,
CopyAlphaCompositeOp, CopyRedCompositeOp, CopyYellowCompositeOp, DarkenCompositeOp,
DarkenIntensityCompositeOp, DifferenceCompositeOp, DisplaceCompositeOp, DissolveCompositeOp,
DistortCompositeOp, DivideDstCompositeOp, DivideSrcCompositeOp, DstAtopCompositeOp,
DstCompositeOp, DstInCompositeOp, DstOutCompositeOp, DstOverCompositeOp,
ExclusionCompositeOp, HardLightCompositeOp, HueCompositeOp, InCompositeOp,
IntensityCompositeOp, LightenCompositeOp, LightenIntensityCompositeOp, LinearBurnCompositeOp,
LinearDodgeCompositeOp, LinearLightCompositeOp, LuminizeCompositeOp, MathematicsCompositeOp,
MinusDstCompositeOp, MinusSrcCompositeOp, ModulateCompositeOp, ModulusAddCompositeOp,
ModulusSubtractCompositeOp, MultiplyCompositeOp, NoCompositeOp, OutCompositeOp,
OverCompositeOp, OverlayCompositeOp, PegtopLightCompositeOp, PinLightCompositeOp,
PlusCompositeOp, ReplaceCompositeOp, SaturateCompositeOp, ScreenCompositeOp,
SoftLightCompositeOp, SrcAtopCompositeOp, SrcCompositeOp, SrcInCompositeOp,
SrcOutCompositeOp, SrcOverCompositeOp, ThresholdCompositeOp, UndefinedCompositeOp,
VividLightCompositeOp, XorCompositeOp
}
Functions
MagickExport MagickBooleanType CompositeImage (Image *, const Image *, const CompositeOperator, const MagickBooleanType, const ssize_t, const ssize_t, ExceptionInfo *)
MagickExport MagickBooleanType TextureImage (Image *, const Image *, ExceptionInfo *)
Enumeration Type Documentation
enum CompositeOperator
Enumerator
AlphaCompositeOp
AtopCompositeOp
BlendCompositeOp
BlurCompositeOp
BumpmapCompositeOp
ChangeMaskCompositeOp
ClearCompositeOp
ColorBurnCompositeOp
ColorDodgeCompositeOp
ColorizeCompositeOp
CopyBlackCompositeOp
CopyBlueCompositeOp
CopyCompositeOp
CopyCyanCompositeOp
CopyGreenCompositeOp
CopyMagentaCompositeOp
CopyAlphaCompositeOp
CopyRedCompositeOp
CopyYellowCompositeOp
DarkenCompositeOp
DarkenIntensityCompositeOp
DifferenceCompositeOp
DisplaceCompositeOp
DissolveCompositeOp
DistortCompositeOp
DivideDstCompositeOp
DivideSrcCompositeOp
DstAtopCompositeOp
DstCompositeOp
DstInCompositeOp
DstOutCompositeOp
DstOverCompositeOp
ExclusionCompositeOp
HardLightCompositeOp
HueCompositeOp
InCompositeOp
IntensityCompositeOp
LightenCompositeOp
LightenIntensityCompositeOp
LinearBurnCompositeOp
LinearDodgeCompositeOp
LinearLightCompositeOp
LuminizeCompositeOp
MathematicsCompositeOp
MinusDstCompositeOp
MinusSrcCompositeOp
ModulateCompositeOp
ModulusAddCompositeOp
ModulusSubtractCompositeOp
MultiplyCompositeOp
NoCompositeOp
OutCompositeOp
OverCompositeOp
OverlayCompositeOp
PegtopLightCompositeOp
PinLightCompositeOp
PlusCompositeOp
ReplaceCompositeOp
SaturateCompositeOp
ScreenCompositeOp
SoftLightCompositeOp
SrcAtopCompositeOp
SrcCompositeOp
SrcInCompositeOp
SrcOutCompositeOp
SrcOverCompositeOp
ThresholdCompositeOp
UndefinedCompositeOp
VividLightCompositeOp
XorCompositeOp
Definition at line 25 of file composite.h.
Function Documentation
MagickExport MagickBooleanType CompositeImage (Image * , const Image * , const CompositeOperator , const MagickBooleanType , const ssize_t , const ssize_t , ExceptionInfo *)
MagickExport MagickBooleanType TextureImage (Image * , const Image * , ExceptionInfo *)
Definition at line 2348 of file composite.c.
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), _Image::alpha_trait, BlendPixelTrait, CloneImage(), _Image::colorspace, _Image::columns, _Image::compose, CompositeImage(), CopyCompositeOp, _Image::debug, DestroyCacheView(), DestroyImage(), DirectClass, GetCacheViewVirtualPixels(), GetMagickModule, GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelReadMask(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, OverCompositeOp, _Image::progress_monitor, QueueCacheViewAuthenticPixels(), _Image::rows, SetImageProgress(), SetImageStorageClass(), SetImageVirtualPixelMethod(), SetPixelChannel(), _Image::signature, SyncCacheViewAuthenticPixels(), TextureImageTag, _Image::tile_offset, TileVirtualPixelMethod, TraceEvent, TransformImageColorspace(), UndefinedPixelTrait, _RectangleInfo::x, and _RectangleInfo::y.
Referenced by MontageImageList().