MagickCore: compare.h File Reference
compare.h File Reference
#include "MagickCore/image.h"
Enumerations
enum MetricType {
UndefinedMetric, AbsoluteErrorMetric, MeanAbsoluteErrorMetric, MeanErrorPerPixelMetric,
MeanSquaredErrorMetric, PeakAbsoluteErrorMetric, PeakSignalToNoiseRatioMetric, RootMeanSquaredErrorMetric,
NormalizedCrossCorrelationErrorMetric, FuzzErrorMetric
}
Functions
MagickExport double * GetImageDistortions (Image *, const Image *, const MetricType, ExceptionInfo *)
MagickExport Image * CompareImages (Image *, const Image *, const MetricType, double *, ExceptionInfo *)
MagickExport Image * SimilarityImage (Image *, const Image *, const MetricType, const double, RectangleInfo *, double *, ExceptionInfo *)
MagickExport MagickBooleanType GetImageDistortion (Image *, const Image *, const MetricType, double *, ExceptionInfo *)
MagickExport MagickBooleanType IsImagesEqual (Image *, const Image *, ExceptionInfo *)
Enumeration Type Documentation
enum MetricType
Enumerator
UndefinedMetric
AbsoluteErrorMetric
MeanAbsoluteErrorMetric
MeanErrorPerPixelMetric
MeanSquaredErrorMetric
PeakAbsoluteErrorMetric
PeakSignalToNoiseRatioMetric
RootMeanSquaredErrorMetric
NormalizedCrossCorrelationErrorMetric
FuzzErrorMetric
Definition at line 27 of file compare.h.
Function Documentation
MagickExport Image* CompareImages (Image * , const Image * , const MetricType , double * , ExceptionInfo *)
MagickExport MagickBooleanType GetImageDistortion (Image * , const Image * , const MetricType , double * , ExceptionInfo *)
MagickExport double* GetImageDistortions (Image * , const Image * , const MetricType , ExceptionInfo *)
Definition at line 1238 of file compare.c.
References AbsoluteErrorMetric, AcquireQuantumMemory(), _Image::columns, _Image::debug, _Image::filename, FuzzErrorMetric, GetAbsoluteDistortion(), GetFuzzDistortion(), GetMagickModule, GetMeanAbsoluteDistortion(), GetMeanErrorPerPixel(), GetMeanSquaredDistortion(), GetNormalizedCrossCorrelationDistortion(), GetPeakAbsoluteDistortion(), GetPeakSignalToNoiseRatio(), GetRootMeanSquaredDistortion(), ImageError, LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, MaxPixelChannels, MeanAbsoluteErrorMetric, MeanErrorPerPixelMetric, MeanSquaredErrorMetric, NormalizedCrossCorrelationErrorMetric, PeakAbsoluteErrorMetric, PeakSignalToNoiseRatioMetric, RelinquishMagickMemory(), ResetMagickMemory(), ResourceLimitFatalError, RootMeanSquaredErrorMetric, _Image::rows, _Image::signature, ThrowFatalException, ThrowMagickException(), and TraceEvent.
MagickExport MagickBooleanType IsImagesEqual (Image * , const Image * , ExceptionInfo *)
Definition at line 1392 of file compare.c.
References AcquireVirtualCacheView(), _Image::columns, DestroyCacheView(), _Image::error, _Image::filename, GetCacheViewVirtualPixels(), GetPixelChannel(), GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelReadMask(), ImageError, MagickFalse, MagickSignature, MagickTrue, _ErrorInfo::mean_error_per_pixel, _ErrorInfo::normalized_maximum_error, _ErrorInfo::normalized_mean_error, QuantumScale, _Image::rows, _Image::signature, ThrowBinaryException, UndefinedPixelTrait, and UpdatePixelTrait.
MagickExport Image * SimilarityImage (Image * , const Image * , const MetricType , const double , RectangleInfo * , double * , ExceptionInfo *)
Definition at line 1555 of file compare.c.
References AcquireAuthenticCacheView(), ClampToQuantum(), CloneImage(), _Image::columns, DeactivateAlphaChannel, _Image::debug, DestroyCacheView(), DestroyImage(), DirectClass, _Image::filename, GetCacheViewAuthenticPixels(), GetMagickModule, GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelReadMask(), GetSimilarityMetric(), ImageError, LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, _Image::progress_monitor, QuantumRange, _Image::rows, SetGeometry(), SetImageAlphaChannel(), SetImageProgress(), SetImageStorageClass(), SetPixelChannel(), _ExceptionInfo::signature, _Image::signature, SimilarityImageTag, SyncCacheViewAuthenticPixels(), ThrowImageException, TraceEvent, UndefinedPixelTrait, UpdatePixelTrait, _RectangleInfo::x, and _RectangleInfo::y.