MagickCore: configure.c File Reference
configure.c File Reference
#include "MagickCore/studio.h"
#include "MagickCore/blob.h"
#include "MagickCore/client.h"
#include "MagickCore/configure.h"
#include "MagickCore/configure-private.h"
#include "MagickCore/exception.h"
#include "MagickCore/exception-private.h"
#include "MagickCore/hashmap.h"
#include "MagickCore/log.h"
#include "MagickCore/memory_.h"
#include "MagickCore/semaphore.h"
#include "MagickCore/string_.h"
#include "MagickCore/string-private.h"
#include "MagickCore/token.h"
#include "MagickCore/utility.h"
#include "MagickCore/utility-private.h"
#include "MagickCore/xml-tree.h"
Data Structures
struct _ConfigureMapInfo
Macros
#define ConfigureFilename "configure.xml"
#define MAGICKCORE_FEATURE_OPENMP_STR ""
#define MAGICKCORE_FEATURE_OPENCL_STR ""
#define MAGICKCORE_FEATURE_ZERO_CONFIGURATION_STR ""
#define MAGICKCORE_FEATURE_HDRI_STR ""
#define MAGICKCORE_FEATURES_STR MAGICKCORE_FEATURE_OPENMP_STR MAGICKCORE_FEATURE_OPENCL_STR MAGICKCORE_FEATURE_ZERO_CONFIGURATION_STR MAGICKCORE_FEATURE_HDRI_STR
#define RegistryKey "ConfigurePath"
#define MagickCoreDLL "CORE_RL_MagickCore_.dll"
#define MagickCoreDebugDLL "CORE_DB_MagickCore_.dll"
Typedefs
typedef struct _ConfigureMapInfo ConfigureMapInfo
Functions
static MagickBooleanType InitializeConfigureList (ExceptionInfo *)
static MagickBooleanType LoadConfigureLists (const char *, ExceptionInfo *)
MagickPrivate MagickBooleanType ConfigureComponentGenesis (void)
static void * DestroyConfigureElement (void *configure_info)
MagickPrivate void ConfigureComponentTerminus (void)
static void * DestroyOptions (void *option)
MagickExport LinkedListInfo * DestroyConfigureOptions (LinkedListInfo *options)
MagickExport const ConfigureInfo * GetConfigureInfo (const char *name, ExceptionInfo *exception)
static int ConfigureInfoCompare (const void *x, const void *y)
MagickExport const ConfigureInfo ** GetConfigureInfoList (const char *pattern, size_t *number_options, ExceptionInfo *exception)
static int ConfigureCompare (const void *x, const void *y)
MagickExport char ** GetConfigureList (const char *pattern, size_t *number_options, ExceptionInfo *exception)
MagickExport char * GetConfigureOption (const char *option)
MagickExport LinkedListInfo * GetConfigureOptions (const char *filename, ExceptionInfo *exception)
MagickExport LinkedListInfo * GetConfigurePaths (const char *filename, ExceptionInfo *exception)
MagickExport const char * GetConfigureValue (const ConfigureInfo *configure_info)
MagickExport MagickBooleanType ListConfigureInfo (FILE *file, ExceptionInfo *exception)
static MagickBooleanType LoadConfigureList (const char *xml, const char *filename, const size_t depth, ExceptionInfo *exception)
Variables
static const ConfigureMapInfo ConfigureMap []
static LinkedListInfo * configure_list = (LinkedListInfo *) NULL
static SemaphoreInfo * configure_semaphore = (SemaphoreInfo *) NULL
static volatile MagickBooleanType instantiate_configure = MagickFalse
Macro Definition Documentation
#define ConfigureFilename "configure.xml"
Definition at line 63 of file configure.c.
Referenced by InitializeConfigureList().
#define MAGICKCORE_FEATURE_HDRI_STR ""
Definition at line 83 of file configure.c.
#define MAGICKCORE_FEATURE_OPENCL_STR ""
Definition at line 73 of file configure.c.
#define MAGICKCORE_FEATURE_OPENMP_STR ""
Definition at line 68 of file configure.c.
#define MAGICKCORE_FEATURE_ZERO_CONFIGURATION_STR ""
Definition at line 78 of file configure.c.
#define MAGICKCORE_FEATURES_STR MAGICKCORE_FEATURE_OPENMP_STR MAGICKCORE_FEATURE_OPENCL_STR MAGICKCORE_FEATURE_ZERO_CONFIGURATION_STR MAGICKCORE_FEATURE_HDRI_STR
Definition at line 86 of file configure.c.
#define MagickCoreDebugDLL "CORE_DB_MagickCore_.dll"
Referenced by GetConfigurePaths().
#define MagickCoreDLL "CORE_RL_MagickCore_.dll"
Referenced by GetConfigurePaths().
#define RegistryKey "ConfigurePath"
Referenced by GetConfigurePaths().
Typedef Documentation
typedef struct _ConfigureMapInfo ConfigureMapInfo
Function Documentation
static int ConfigureCompare (const void * x, const void * y) static
Definition at line 430 of file configure.c.
References LocaleCompare().
Referenced by GetConfigureList().
MagickPrivate MagickBooleanType ConfigureComponentGenesis (void)
Definition at line 143 of file configure.c.
References AcquireSemaphoreInfo(), configure_semaphore, and MagickTrue.
Referenced by MagickCoreGenesis().
MagickPrivate void ConfigureComponentTerminus (void)
Definition at line 187 of file configure.c.
References AcquireSemaphoreInfo(), configure_list, configure_semaphore, DestroyConfigureElement(), DestroyLinkedList(), DestroySemaphoreInfo(), instantiate_configure, LockSemaphoreInfo(), MagickFalse, and UnlockSemaphoreInfo().
Referenced by MagickCoreTerminus().
static int ConfigureInfoCompare (const void * x, const void * y) static
Definition at line 334 of file configure.c.
References LocaleCompare().
Referenced by GetConfigureInfoList().
static void* DestroyConfigureElement (void * configure_info) static
Definition at line 168 of file configure.c.
References DestroyString(), _ConfigureInfo::exempt, MagickFalse, _ConfigureInfo::name, _ConfigureInfo::path, RelinquishMagickMemory(), and _ConfigureInfo::value.
Referenced by ConfigureComponentTerminus().
MagickExport LinkedListInfo* DestroyConfigureOptions (LinkedListInfo * options)
Definition at line 229 of file configure.c.
References DestroyLinkedList(), DestroyOptions(), GetMagickModule, LogMagickEvent(), and TraceEvent.
Referenced by GetThresholdMap(), ListThresholdMaps(), LoadCoderLists(), LoadColorLists(), LoadConfigureLists(), LoadDelegateLists(), LoadLogLists(), LoadMagicLists(), LoadMimeLists(), LoadPolicyLists(), and LoadTypeLists().
static void* DestroyOptions (void * option) static
Definition at line 224 of file configure.c.
References DestroyStringInfo().
Referenced by DestroyConfigureOptions().
MagickExport const ConfigureInfo* GetConfigureInfo (const char * name, ExceptionInfo * exception)
Definition at line 265 of file configure.c.
References configure_list, configure_semaphore, GetNextValueInLinkedList(), GetValueFromLinkedList(), InitializeConfigureList(), InsertValueInLinkedList(), instantiate_configure, IsLinkedListEmpty(), LocaleCompare(), LockSemaphoreInfo(), MagickFalse, _ConfigureInfo::name, RemoveElementByValueFromLinkedList(), ResetLinkedListIterator(), and UnlockSemaphoreInfo().
Referenced by GetConfigureInfoList(), GetConfigureList(), and GetConfigureOption().
MagickExport const ConfigureInfo** GetConfigureInfoList (const char * pattern, size_t * number_options, ExceptionInfo * exception)
Definition at line 351 of file configure.c.
References AcquireQuantumMemory(), configure_list, configure_semaphore, ConfigureInfoCompare(), GetConfigureInfo(), GetMagickModule, GetNextValueInLinkedList(), GetNumberOfElementsInLinkedList(), GlobExpression(), LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, _ConfigureInfo::name, ResetLinkedListIterator(), _ConfigureInfo::stealth, TraceEvent, and UnlockSemaphoreInfo().
Referenced by ListConfigureInfo().
MagickExport char** GetConfigureList (const char * pattern, size_t * number_options, ExceptionInfo * exception)
Definition at line 445 of file configure.c.
References AcquireQuantumMemory(), configure_list, configure_semaphore, ConfigureCompare(), ConstantString(), GetConfigureInfo(), GetMagickModule, GetNextValueInLinkedList(), GetNumberOfElementsInLinkedList(), GlobExpression(), LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, _ConfigureInfo::name, ResetLinkedListIterator(), _ConfigureInfo::stealth, TraceEvent, and UnlockSemaphoreInfo().
MagickExport char* GetConfigureOption (const char * option)
Definition at line 510 of file configure.c.
References AcquireExceptionInfo(), ConstantString(), DestroyExceptionInfo(), GetConfigureInfo(), GetConfigureValue(), GetMagickModule, LogMagickEvent(), and TraceEvent.
MagickExport LinkedListInfo* GetConfigureOptions (const char * filename, ExceptionInfo * exception)
Definition at line 560 of file configure.c.
References AcquireStringInfo(), AppendValueToLinkedList(), ConfigureEvent, ConfigureFileToStringInfo(), ConfigureWarning, CopyMagickString(), DestroyLinkedList(), FormatLocaleString(), GetConfigurePaths(), GetMagickModule, GetNextValueInLinkedList(), GetNumberOfElementsInLinkedList(), LogMagickEvent(), MaxTextExtent, NewLinkedList(), RelinquishMagickMemory(), ResetLinkedListIterator(), SetStringInfoDatum(), SetStringInfoLength(), SetStringInfoPath(), ThrowMagickException(), and TraceEvent.
Referenced by GetThresholdMap(), ListThresholdMaps(), LoadCoderLists(), LoadColorLists(), LoadConfigureLists(), LoadDelegateLists(), LoadLogLists(), LoadMagicLists(), LoadMimeLists(), LoadPolicyLists(), and LoadTypeLists().
MagickExport LinkedListInfo* GetConfigurePaths (const char * filename, ExceptionInfo * exception)
Definition at line 651 of file configure.c.
References AppendValueToLinkedList(), ChopPathComponents(), ConcatenateMagickString(), ConstantString(), CopyMagickString(), DestroyString(), DirectoryListSeparator, DirectorySeparator, FormatLocaleString(), GetClientPath(), GetEnvironmentValue(), GetMagickModule, LogMagickEvent(), MAGICKCORE_CONFIGURE_PATH, MAGICKCORE_CONFIGURE_RELATIVE_PATH, MAGICKCORE_DOCUMENTATION_PATH, MAGICKCORE_SHARE_PATH, MAGICKCORE_SHARE_RELATIVE_PATH, MagickCoreDebugDLL, MagickCoreDLL, MagickFalse, MaxTextExtent, NewLinkedList(), RegistryKey, RelinquishMagickMemory(), and TraceEvent.
Referenced by GetConfigureOptions(), GetLocaleOptions(), and GetMagickHomeURL().
MagickExport const char* GetConfigureValue (const ConfigureInfo * configure_info)
Definition at line 872 of file configure.c.
References GetMagickModule, LogMagickEvent(), MagickSignature, _ConfigureInfo::signature, TraceEvent, and _ConfigureInfo::value.
Referenced by GetConfigureOption().
static MagickBooleanType InitializeConfigureList (ExceptionInfo * exception) static
Definition at line 902 of file configure.c.
References AcquireSemaphoreInfo(), configure_list, configure_semaphore, ConfigureFilename, instantiate_configure, LoadConfigureLists(), LockSemaphoreInfo(), MagickFalse, MagickTrue, and UnlockSemaphoreInfo().
Referenced by GetConfigureInfo().
MagickExport MagickBooleanType ListConfigureInfo (FILE * file, ExceptionInfo * exception)
Definition at line 945 of file configure.c.
References FormatLocaleFile(), GetConfigureInfoList(), LocaleCompare(), MagickFalse, MagickTrue, _ConfigureInfo::path, and RelinquishMagickMemory().
static MagickBooleanType LoadConfigureList (const char * xml, const char * filename, const size_t depth, ExceptionInfo * exception) static
Definition at line 1036 of file configure.c.
References AcquireMagickMemory(), AcquireString(), AppendValueToLinkedList(), ConcatenateMagickString(), configure_list, ConfigureError, ConfigureEvent, ConstantString(), CopyMagickString(), DirectorySeparator, _ConfigureInfo::exempt, FileToString(), GetMagickModule, GetMagickToken(), GetPathComponent(), HeadPath, IsStringTrue(), LocaleCompare(), LocaleNCompare(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, MaxTextExtent, _ConfigureInfo::name, NewLinkedList(), _ConfigureInfo::path, RelinquishMagickMemory(), ResetMagickMemory(), ResourceLimitError, ResourceLimitFatalError, _ConfigureInfo::signature, _ConfigureInfo::stealth, ThrowFatalException, ThrowFileException, ThrowMagickException(), and _ConfigureInfo::value.
Referenced by LoadConfigureLists().
static MagickBooleanType LoadConfigureLists (const char * filename, ExceptionInfo * exception)
Definition at line 1239 of file configure.c.
References AcquireMagickMemory(), AppendValueToLinkedList(), configure_list, ConfigureMap, DestroyConfigureOptions(), _ConfigureInfo::exempt, GetConfigureOptions(), GetMagickModule, GetNextValueInLinkedList(), GetStringInfoDatum(), GetStringInfoPath(), LoadConfigureList(), MagickFalse, MagickSignature, MagickTrue, _ConfigureInfo::name, _ConfigureMapInfo::name, NewLinkedList(), _ConfigureInfo::path, ResetMagickMemory(), ResourceLimitError, _ConfigureInfo::signature, ThrowFileException, ThrowMagickException(), _ConfigureInfo::value, and _ConfigureMapInfo::value.
Referenced by InitializeConfigureList().
Variable Documentation
LinkedListInfo* configure_list = (LinkedListInfo *) NULL static
Definition at line 110 of file configure.c.
Referenced by ConfigureComponentTerminus(), GetConfigureInfo(), GetConfigureInfoList(), GetConfigureList(), InitializeConfigureList(), LoadConfigureList(), and LoadConfigureLists().
SemaphoreInfo* configure_semaphore = (SemaphoreInfo *) NULL static
Definition at line 113 of file configure.c.
Referenced by ConfigureComponentGenesis(), ConfigureComponentTerminus(), GetConfigureInfo(), GetConfigureInfoList(), GetConfigureList(), and InitializeConfigureList().
const ConfigureMapInfo ConfigureMap[] static
Initial value:
=
  {
    { "NAME", "ImageMagick" },
    { "QuantumDepth", MAGICKCORE_STRING_XQUOTE(MAGICKCORE_QUANTUM_DEPTH) } ,
    { "FEATURES", MAGICKCORE_FEATURES_STR }
  }
Definition at line 102 of file configure.c.
Referenced by LoadConfigureLists().
volatile MagickBooleanType instantiate_configure = MagickFalse static
Definition at line 116 of file configure.c.
Referenced by ConfigureComponentTerminus(), GetConfigureInfo(), and InitializeConfigureList().