MagickCore: configure.h File Reference
configure.h File Reference
#include "MagickCore/hashmap.h"
Data Structures
struct _ConfigureInfo
Typedefs
typedef struct _ConfigureInfo ConfigureInfo
Functions
MagickExport char ** GetConfigureList (const char *, size_t *, ExceptionInfo *)
MagickExport char * GetConfigureOption (const char *)
MagickExport const char * GetConfigureValue (const ConfigureInfo *)
MagickExport const ConfigureInfo * GetConfigureInfo (const char *, ExceptionInfo *)
MagickExport const ConfigureInfo ** GetConfigureInfoList (const char *, size_t *, ExceptionInfo *)
MagickExport LinkedListInfo * DestroyConfigureOptions (LinkedListInfo *)
MagickExport LinkedListInfo * GetConfigurePaths (const char *, ExceptionInfo *)
MagickExport LinkedListInfo * GetConfigureOptions (const char *, ExceptionInfo *)
MagickExport MagickBooleanType ListConfigureInfo (FILE *, ExceptionInfo *)
Typedef Documentation
typedef struct _ConfigureInfo ConfigureInfo
Function Documentation
MagickExport LinkedListInfo* DestroyConfigureOptions (LinkedListInfo *)
MagickExport const ConfigureInfo* GetConfigureInfo (const char * , ExceptionInfo *)
MagickExport const ConfigureInfo ** GetConfigureInfoList (const char * , size_t * , ExceptionInfo *)
Definition at line 351 of file configure.c.
References AcquireQuantumMemory(), configure_list, configure_semaphore, ConfigureInfoCompare(), GetConfigureInfo(), GetMagickModule, GetNextValueInLinkedList(), GetNumberOfElementsInLinkedList(), GlobExpression(), LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, _ConfigureInfo::name, ResetLinkedListIterator(), _ConfigureInfo::stealth, TraceEvent, and UnlockSemaphoreInfo().
Referenced by ListConfigureInfo().
MagickExport char** GetConfigureList (const char * , size_t * , ExceptionInfo *)
MagickExport char * GetConfigureOption (const char *)
Definition at line 510 of file configure.c.
References AcquireExceptionInfo(), ConstantString(), DestroyExceptionInfo(), GetConfigureInfo(), GetConfigureValue(), GetMagickModule, LogMagickEvent(), and TraceEvent.
MagickExport LinkedListInfo * GetConfigureOptions (const char * , ExceptionInfo *)
Definition at line 560 of file configure.c.
References AcquireStringInfo(), AppendValueToLinkedList(), ConfigureEvent, ConfigureFileToStringInfo(), ConfigureWarning, CopyMagickString(), DestroyLinkedList(), FormatLocaleString(), GetConfigurePaths(), GetMagickModule, GetNextValueInLinkedList(), GetNumberOfElementsInLinkedList(), LogMagickEvent(), MaxTextExtent, NewLinkedList(), RelinquishMagickMemory(), ResetLinkedListIterator(), SetStringInfoDatum(), SetStringInfoLength(), SetStringInfoPath(), ThrowMagickException(), and TraceEvent.
Referenced by GetThresholdMap(), ListThresholdMaps(), LoadCoderLists(), LoadColorLists(), LoadConfigureLists(), LoadDelegateLists(), LoadLogLists(), LoadMagicLists(), LoadMimeLists(), LoadPolicyLists(), and LoadTypeLists().
MagickExport LinkedListInfo * GetConfigurePaths (const char * , ExceptionInfo *)
MagickExport const char* GetConfigureValue (const ConfigureInfo *)
Definition at line 872 of file configure.c.
References GetMagickModule, LogMagickEvent(), MagickSignature, _ConfigureInfo::signature, TraceEvent, and _ConfigureInfo::value.
Referenced by GetConfigureOption().
MagickExport MagickBooleanType ListConfigureInfo (FILE * , ExceptionInfo *)
Definition at line 945 of file configure.c.
References FormatLocaleFile(), GetConfigureInfoList(), LocaleCompare(), MagickFalse, MagickTrue, _ConfigureInfo::path, and RelinquishMagickMemory().