MagickCore: constitute.c File Reference
constitute.c File Reference
#include "MagickCore/studio.h"
#include "MagickCore/attribute.h"
#include "MagickCore/blob.h"
#include "MagickCore/blob-private.h"
#include "MagickCore/exception.h"
#include "MagickCore/exception-private.h"
#include "MagickCore/cache.h"
#include "MagickCore/client.h"
#include "MagickCore/colorspace-private.h"
#include "MagickCore/constitute.h"
#include "MagickCore/constitute-private.h"
#include "MagickCore/delegate.h"
#include "MagickCore/geometry.h"
#include "MagickCore/identify.h"
#include "MagickCore/image-private.h"
#include "MagickCore/list.h"
#include "MagickCore/magick.h"
#include "MagickCore/memory_.h"
#include "MagickCore/monitor.h"
#include "MagickCore/monitor-private.h"
#include "MagickCore/option.h"
#include "MagickCore/pixel.h"
#include "MagickCore/pixel-accessor.h"
#include "MagickCore/policy.h"
#include "MagickCore/profile.h"
#include "MagickCore/profile-private.h"
#include "MagickCore/property.h"
#include "MagickCore/quantum.h"
#include "MagickCore/resize.h"
#include "MagickCore/resource_.h"
#include "MagickCore/semaphore.h"
#include "MagickCore/statistic.h"
#include "MagickCore/stream.h"
#include "MagickCore/string_.h"
#include "MagickCore/string-private.h"
#include "MagickCore/timer.h"
#include "MagickCore/token.h"
#include "MagickCore/transform.h"
#include "MagickCore/utility.h"
#include "MagickCore/utility-private.h"
Macros
#define WriteImageTag "Write/Image"
Functions
MagickPrivate MagickBooleanType ConstituteComponentGenesis (void)
MagickPrivate void ConstituteComponentTerminus (void)
MagickExport Image * ConstituteImage (const size_t columns, const size_t rows, const char *map, const StorageType storage, const void *pixels, ExceptionInfo *exception)
static size_t PingStream (const Image *magick_unused(image), const void *magick_unused(pixels), const size_t columns)
MagickExport Image * PingImage (const ImageInfo *image_info, ExceptionInfo *exception)
MagickExport Image * PingImages (ImageInfo *image_info, const char *filename, ExceptionInfo *exception)
MagickExport Image * ReadImage (const ImageInfo *image_info, ExceptionInfo *exception)
MagickExport Image * ReadImages (ImageInfo *image_info, const char *filename, ExceptionInfo *exception)
MagickExport Image * ReadInlineImage (const ImageInfo *image_info, const char *content, ExceptionInfo *exception)
MagickExport MagickBooleanType WriteImage (const ImageInfo *image_info, Image *image, ExceptionInfo *exception)
MagickExport MagickBooleanType WriteImages (const ImageInfo *image_info, Image *images, const char *filename, ExceptionInfo *exception)
Variables
static SemaphoreInfo * constitute_semaphore = (SemaphoreInfo *) NULL
Macro Definition Documentation
#define WriteImageTag "Write/Image"
Referenced by WriteImages().
Function Documentation
MagickPrivate MagickBooleanType ConstituteComponentGenesis (void)
Definition at line 104 of file constitute.c.
References AcquireSemaphoreInfo(), constitute_semaphore, and MagickTrue.
Referenced by MagickCoreGenesis().
MagickPrivate void ConstituteComponentTerminus (void)
Definition at line 128 of file constitute.c.
References AcquireSemaphoreInfo(), constitute_semaphore, and DestroySemaphoreInfo().
Referenced by MagickCoreTerminus().
MagickExport Image* ConstituteImage (const size_t columns, const size_t rows, const char * map, const StorageType storage, const void * pixels, ExceptionInfo * exception)
Definition at line 184 of file constitute.c.
References AcquireImage(), _Image::columns, DestroyImage(), GetMagickModule, ImportImagePixels(), LogMagickEvent(), MagickFalse, MagickSignature, OptionError, _Image::rows, SetImageBackgroundColor(), _ExceptionInfo::signature, ThrowImageException, and TraceEvent.
MagickExport Image* PingImage (const ImageInfo * image_info, ExceptionInfo * exception)
Definition at line 259 of file constitute.c.
References CloneImageInfo(), _ImageInfo::debug, DestroyImageInfo(), _ImageInfo::filename, GetMagickModule, IdentifyImage(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, _ImageInfo::ping, PingStream(), ReadStream(), ResetTimer(), _ImageInfo::signature, _Image::timer, TraceEvent, and _ImageInfo::verbose.
Referenced by PingImages().
MagickExport Image* PingImages (ImageInfo * image_info, const char * filename, ExceptionInfo * exception)
Definition at line 314 of file constitute.c.
References AcquireExceptionInfo(), AppendImageToList(), CloneImageInfo(), CopyMagickString(), _ImageInfo::debug, DestroyExceptionInfo(), DestroyImageInfo(), _ImageInfo::filename, GetMagickModule, InterpretImageFilename(), LocaleCompare(), LogMagickEvent(), MagickFalse, MagickSignature, MaxTextExtent, NewImageList(), _ImageInfo::number_scenes, PingImage(), _ImageInfo::scene, SetImageInfo(), SetImageOption(), _ImageInfo::signature, and TraceEvent.
static size_t PingStream (const Image * magick_unusedimage, const void * magick_unusedpixels, const size_t columns) static
Definition at line 249 of file constitute.c.
Referenced by PingImage().
MagickExport Image* ReadImage (const ImageInfo * image_info, ExceptionInfo * exception)
Definition at line 407 of file constitute.c.
References AcquireExceptionInfo(), AcquireImage(), AcquireSemaphoreInfo(), CloneImageInfo(), CloneImages(), CloseBlob(), CoderPolicyDomain, _Image::columns, constitute_semaphore, CopyMagickString(), CropImage(), _ImageInfo::debug, DecoderThreadSupport, _Image::delay, DeleteImageProperty(), DestroyExceptionInfo(), DestroyImage(), DestroyImageInfo(), DestroyImageList(), DestroyString(), _Image::dispose, _ImageInfo::endian, ErrorException, ExceptionEvent, _ImageInfo::extract, _Image::filename, _ImageInfo::filename, FileOpenError, _Image::filter, FormatMagickTime(), GetBlobError(), GetBlobProperties(), GetDelegateInfo(), GetDelegateThreadSupport(), GetFirstImageInList(), GetImageDecoder(), GetImageOption(), GetImageProfile(), GetImageProperty(), GetMagickEndianSupport(), GetMagickInfo(), GetMagickModule, GetMagickRawSupport(), GetMagickSeekableStream(), GetMagickThreadSupport(), GetNextImageInList(), GetPathComponent(), GreaterValue, _RectangleInfo::height, HeightValue, IdentifyImage(), ImageToFile(), InterpretImageProperties(), InvokeDelegate(), IsBlobSeekable(), IsBlobTemporary(), IsPathAccessible(), IsRightsAuthorized(), IsSceneGeometry(), LessValue, LocaleCompare(), LockSemaphoreInfo(), LogMagickEvent(), LSBEndian, _Image::magick, _ImageInfo::magick, _Image::magick_columns, _Image::magick_filename, _Image::magick_rows, MagickDisposeOptions, MagickFalse, MagickPath, MagickSignature, MagickTrue, MaxTextExtent, MissingDelegateError, MSBEndian, NewImageList(), OpenBlob(), OptionError, _Image::orientation, _Image::page, ParseAbsoluteGeometry(), ParseCommandOption(), ParseGeometry(), ParseRegionGeometry(), PolicyError, ReadBinaryBlobMode, ReadPolicyRights, RelinquishUniqueFileResource(), ReplaceImageInList(), ResizeImage(), _Image::resolution, _GeometryInfo::rho, _Image::rows, _ImageInfo::scenes, SetImageInfo(), SetImageProperty(), _ExceptionInfo::severity, _GeometryInfo::sigma, SigmaValue, _ImageInfo::signature, _ImageInfo::stream, StringToLong(), _Image::taint, _ImageInfo::temporary, ThrowFileException, ThrowMagickException(), _Image::ticks_per_second, TraceEvent, UndefinedEndian, _Image::units, UnlockSemaphoreInfo(), _ImageInfo::verbose, _RectangleInfo::width, WidthValue, _PointInfo::x, XValue, _PointInfo::y, and YValue.
Referenced by BlobToImage(), DrawImage(), DrawPrimitive(), IdentifyImage(), MontageImageList(), PreviewImage(), ReadImages(), ReadStream(), and RenderPostscript().
MagickExport Image* ReadImages (ImageInfo * image_info, const char * filename, ExceptionInfo * exception)
Definition at line 843 of file constitute.c.
References AcquireExceptionInfo(), AppendImageToList(), CloneImageInfo(), CopyMagickString(), _ImageInfo::debug, DestroyExceptionInfo(), DestroyImageInfo(), _ImageInfo::filename, GetMagickModule, InterpretImageFilename(), LocaleCompare(), LogMagickEvent(), MagickFalse, MagickSignature, MaxTextExtent, NewImageList(), _ImageInfo::number_scenes, ReadImage(), _ImageInfo::scene, SetImageInfo(), SetImageOption(), _ImageInfo::signature, and TraceEvent.
MagickExport Image* ReadInlineImage (const ImageInfo * image_info, const char * content, ExceptionInfo * exception)
Definition at line 938 of file constitute.c.
References Base64Decode(), BlobToImage(), CloneImageInfo(), CorruptImageError, DestroyImageInfo(), _ImageInfo::filename, _ImageInfo::magick, NewImageList(), RelinquishMagickMemory(), SetImageInfoProgressMonitor(), and ThrowReaderException.
Referenced by DrawPrimitive().
MagickExport MagickBooleanType WriteImage (const ImageInfo * image_info, Image * image, ExceptionInfo * exception)
Definition at line 1010 of file constitute.c.
References AcquireExceptionInfo(), AcquireSemaphoreInfo(), AcquireUniqueFilename(), _ImageInfo::adjoin, _ImageInfo::affirm, CloneImageInfo(), CloseBlob(), CoderPolicyDomain, constitute_semaphore, CopyMagickString(), _Image::debug, DestroyExceptionInfo(), DestroyImageInfo(), EncoderThreadSupport, _Image::endian, _ImageInfo::endian, ExtensionPath, _Image::filename, _ImageInfo::filename, FileOpenError, GetBlobError(), GetDelegateInfo(), GetDelegateMode(), GetDelegateThreadSupport(), GetImageEncoder(), GetImageOption(), GetMagickEndianSupport(), GetMagickInfo(), GetMagickModule, GetMagickRawSupport(), GetMagickSeekableStream(), GetMagickThreadSupport(), GetNextImageInList(), GetPathComponent(), GetPreviousImageInList(), IdentifyImage(), IfMagickFalse, IfMagickTrue, ImageToFile(), InvokeDelegate(), IsBlobSeekable(), IsPathAccessible(), IsRightsAuthorized(), IsStringTrue(), IsTaintImage(), LocaleCompare(), LockSemaphoreInfo(), LogMagickEvent(), LSBEndian, _Image::magick, _ImageInfo::magick, _Image::magick_filename, MagickFalse, MagickSignature, MagickTrue, MaxTextExtent, MissingDelegateError, MissingDelegateWarning, MSBEndian, OpenBlob(), _ImageInfo::page, PolicyError, ReadBinaryBlobMode, RelinquishUniqueFileResource(), SetImageInfo(), _Image::signature, _ImageInfo::signature, SyncImageProfiles(), ThrowBinaryException, ThrowFileException, ThrowMagickException(), TraceEvent, UndefinedEndian, UnlockSemaphoreInfo(), _ImageInfo::verbose, WriteBinaryBlobMode, and WritePolicyRights.
Referenced by ImageToBlob(), InjectImageBlob(), InvokeDelegate(), PreviewImage(), WriteImages(), and WriteStream().
MagickExport MagickBooleanType WriteImages (const ImageInfo * image_info, Image * images, const char * filename, ExceptionInfo * exception)
Definition at line 1292 of file constitute.c.
References AcquireExceptionInfo(), _ImageInfo::adjoin, _Image::blob, _Image::client_data, CloneBlobInfo(), CloneImageInfo(), CopyMagickString(), _Image::debug, DestroyBlob(), DestroyExceptionInfo(), DestroyImageInfo(), _Image::filename, _ImageInfo::filename, GetFirstImageInList(), GetImageListLength(), GetMagickModule, GetNextImageInList(), LogMagickEvent(), _Image::magick, _ImageInfo::magick, MagickFalse, MagickSignature, MagickTrue, MaxTextExtent, _Image::scene, SetImageInfo(), SetImageProgress(), SetImageProgressMonitor(), _Image::signature, _ImageInfo::signature, TraceEvent, WriteImage(), and WriteImageTag.
Referenced by ImagesToBlob().
Variable Documentation
SemaphoreInfo* constitute_semaphore = (SemaphoreInfo *) NULL static
Definition at line 84 of file constitute.c.
Referenced by ConstituteComponentGenesis(), ConstituteComponentTerminus(), ReadImage(), and WriteImage().