MagickCore: decorate.c File Reference
decorate.c File Reference
#include "MagickCore/studio.h"
#include "MagickCore/cache-view.h"
#include "MagickCore/color-private.h"
#include "MagickCore/colorspace-private.h"
#include "MagickCore/composite.h"
#include "MagickCore/decorate.h"
#include "MagickCore/exception.h"
#include "MagickCore/exception-private.h"
#include "MagickCore/image.h"
#include "MagickCore/memory_.h"
#include "MagickCore/monitor.h"
#include "MagickCore/monitor-private.h"
#include "MagickCore/pixel-accessor.h"
#include "MagickCore/quantum.h"
#include "MagickCore/quantum-private.h"
#include "MagickCore/resource_.h"
#include "MagickCore/thread-private.h"
#include "MagickCore/transform.h"
Macros
#define AccentuateModulate ScaleCharToQuantum(80)
#define HighlightModulate ScaleCharToQuantum(125)
#define ShadowModulate ScaleCharToQuantum(135)
#define DepthModulate ScaleCharToQuantum(185)
#define TroughModulate ScaleCharToQuantum(110)
#define FrameImageTag "Frame/Image"
#define AccentuateFactor ScaleCharToQuantum(135)
#define HighlightFactor ScaleCharToQuantum(190)
#define ShadowFactor ScaleCharToQuantum(190)
#define RaiseImageTag "Raise/Image"
#define TroughFactor ScaleCharToQuantum(135)
Functions
MagickExport Image * BorderImage (const Image *image, const RectangleInfo *border_info, const CompositeOperator compose, ExceptionInfo *exception)
MagickExport Image * FrameImage (const Image *image, const FrameInfo *frame_info, const CompositeOperator compose, ExceptionInfo *exception)
MagickExport MagickBooleanType RaiseImage (Image *image, const RectangleInfo *raise_info, const MagickBooleanType raise, ExceptionInfo *exception)
Macro Definition Documentation
#define AccentuateFactor ScaleCharToQuantum(135)
Referenced by RaiseImage().
#define AccentuateModulate ScaleCharToQuantum(80)
Definition at line 65 of file decorate.c.
Referenced by FrameImage().
#define DepthModulate ScaleCharToQuantum(185)
Definition at line 68 of file decorate.c.
#define FrameImageTag "Frame/Image"
Referenced by FrameImage().
#define HighlightFactor ScaleCharToQuantum(190)
Referenced by RaiseImage().
#define HighlightModulate ScaleCharToQuantum(125)
Definition at line 66 of file decorate.c.
Referenced by FrameImage().
#define RaiseImageTag "Raise/Image"
Referenced by RaiseImage().
#define ShadowFactor ScaleCharToQuantum(190)
Referenced by RaiseImage().
#define ShadowModulate ScaleCharToQuantum(135)
Definition at line 67 of file decorate.c.
Referenced by FrameImage().
#define TroughFactor ScaleCharToQuantum(135)
Referenced by RaiseImage().
#define TroughModulate ScaleCharToQuantum(110)
Definition at line 69 of file decorate.c.
Referenced by FrameImage().
Function Documentation
MagickExport Image* BorderImage (const Image * image, const RectangleInfo * border_info, const CompositeOperator compose, ExceptionInfo * exception)
Definition at line 103 of file decorate.c.
References _Image::border_color, CloneImage(), _Image::columns, _Image::debug, DestroyImage(), _Image::filename, FrameImage(), GetMagickModule, _FrameInfo::height, _RectangleInfo::height, _FrameInfo::inner_bevel, LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, _Image::matte_color, _FrameInfo::outer_bevel, _Image::rows, _Image::signature, TraceEvent, _FrameInfo::width, _RectangleInfo::width, _FrameInfo::x, and _FrameInfo::y.
Referenced by MontageImageList(), ShadowImage(), ShearImage(), and ShearRotateImage().
MagickExport Image* FrameImage (const Image * image, const FrameInfo * frame_info, const CompositeOperator compose, ExceptionInfo * exception)
Definition at line 169 of file decorate.c.
References AccentuateModulate, AcquireAuthenticCacheView(), AcquireVirtualCacheView(), _PixelInfo::alpha, _PixelInfo::alpha_trait, _Image::alpha_trait, _PixelInfo::black, BlendPixelTrait, _PixelInfo::blue, _Image::border_color, CloneImage(), _Image::colorspace, _Image::columns, CompositeImage(), CopyCompositeOp, CopyPixelTrait, _Image::debug, DestroyCacheView(), DestroyImage(), DirectClass, _Image::filename, FrameImageTag, GetCacheViewVirtualPixels(), GetMagickModule, GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelReadMask(), _PixelInfo::green, _FrameInfo::height, _RectangleInfo::height, HighlightModulate, _FrameInfo::inner_bevel, IsGrayColorspace(), IsPixelInfoGray(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, _Image::matte_color, OpaqueAlpha, OptionError, _FrameInfo::outer_bevel, OverCompositeOp, _Image::page, _Image::progress_monitor, QuantumRange, QuantumScale, QueueCacheViewAuthenticPixels(), _PixelInfo::red, _Image::rows, SetImageAlpha(), SetImageColorspace(), SetImageProgress(), SetImageStorageClass(), SetPixelInfoPixel(), ShadowModulate, _Image::signature, sRGBColorspace, SyncCacheViewAuthenticPixels(), ThrowImageException, TraceEvent, TroughModulate, UpdatePixelTrait, _FrameInfo::width, _RectangleInfo::width, _FrameInfo::x, and _FrameInfo::y.
Referenced by BorderImage(), and MontageImageList().
MagickExport MagickBooleanType RaiseImage (Image * image, const RectangleInfo * raise_info, const MagickBooleanType raise, ExceptionInfo * exception)
Definition at line 650 of file decorate.c.
References AccentuateFactor, AcquireAuthenticCacheView(), ClampToQuantum(), _Image::columns, _Image::debug, DestroyCacheView(), DirectClass, _Image::filename, GetCacheViewAuthenticPixels(), GetMagickModule, GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelReadMask(), _RectangleInfo::height, HighlightFactor, LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, OptionError, _Image::progress_monitor, QuantumRange, QuantumScale, RaiseImageTag, _Image::rows, SetImageProgress(), SetImageStorageClass(), ShadowFactor, _Image::signature, SyncCacheViewAuthenticPixels(), ThrowBinaryException, TraceEvent, TroughFactor, UpdatePixelTrait, and _RectangleInfo::width.
Referenced by PreviewImage().