MagickCore: decorate.h File Reference
decorate.h File Reference
#include "MagickCore/image.h"
Data Structures
struct _FrameInfo
Typedefs
typedef struct _FrameInfo FrameInfo
Functions
MagickExport Image * BorderImage (const Image *, const RectangleInfo *, const CompositeOperator, ExceptionInfo *)
MagickExport Image * FrameImage (const Image *, const FrameInfo *, const CompositeOperator, ExceptionInfo *)
MagickExport MagickBooleanType RaiseImage (Image *, const RectangleInfo *, const MagickBooleanType, ExceptionInfo *)
Typedef Documentation
typedef struct _FrameInfo FrameInfo
Function Documentation
MagickExport Image* BorderImage (const Image * , const RectangleInfo * , const CompositeOperator , ExceptionInfo *)
MagickExport Image * FrameImage (const Image * , const FrameInfo * , const CompositeOperator , ExceptionInfo *)
Definition at line 169 of file decorate.c.
References AccentuateModulate, AcquireAuthenticCacheView(), AcquireVirtualCacheView(), _PixelInfo::alpha, _PixelInfo::alpha_trait, _Image::alpha_trait, _PixelInfo::black, BlendPixelTrait, _PixelInfo::blue, _Image::border_color, CloneImage(), _Image::colorspace, _Image::columns, CompositeImage(), CopyCompositeOp, CopyPixelTrait, _Image::debug, DestroyCacheView(), DestroyImage(), DirectClass, _Image::filename, FrameImageTag, GetCacheViewVirtualPixels(), GetMagickModule, GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelReadMask(), _PixelInfo::green, _FrameInfo::height, _RectangleInfo::height, HighlightModulate, _FrameInfo::inner_bevel, IsGrayColorspace(), IsPixelInfoGray(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, _Image::matte_color, OpaqueAlpha, OptionError, _FrameInfo::outer_bevel, OverCompositeOp, _Image::page, _Image::progress_monitor, QuantumRange, QuantumScale, QueueCacheViewAuthenticPixels(), _PixelInfo::red, _Image::rows, SetImageAlpha(), SetImageColorspace(), SetImageProgress(), SetImageStorageClass(), SetPixelInfoPixel(), ShadowModulate, _Image::signature, sRGBColorspace, SyncCacheViewAuthenticPixels(), ThrowImageException, TraceEvent, TroughModulate, UpdatePixelTrait, _FrameInfo::width, _RectangleInfo::width, _FrameInfo::x, and _FrameInfo::y.
Referenced by BorderImage(), and MontageImageList().
MagickExport MagickBooleanType RaiseImage (Image * , const RectangleInfo * , const MagickBooleanType , ExceptionInfo *)
Definition at line 650 of file decorate.c.
References AccentuateFactor, AcquireAuthenticCacheView(), ClampToQuantum(), _Image::columns, _Image::debug, DestroyCacheView(), DirectClass, _Image::filename, GetCacheViewAuthenticPixels(), GetMagickModule, GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelReadMask(), _RectangleInfo::height, HighlightFactor, LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, OptionError, _Image::progress_monitor, QuantumRange, QuantumScale, RaiseImageTag, _Image::rows, SetImageProgress(), SetImageStorageClass(), ShadowFactor, _Image::signature, SyncCacheViewAuthenticPixels(), ThrowBinaryException, TraceEvent, TroughFactor, UpdatePixelTrait, and _RectangleInfo::width.
Referenced by PreviewImage().