MagickCore: delegate.c File Reference
delegate.c File Reference
#include "MagickCore/studio.h"
#include "MagickCore/property.h"
#include "MagickCore/blob.h"
#include "MagickCore/client.h"
#include "MagickCore/configure.h"
#include "MagickCore/constitute.h"
#include "MagickCore/delegate.h"
#include "MagickCore/delegate-private.h"
#include "MagickCore/exception.h"
#include "MagickCore/exception-private.h"
#include "MagickCore/hashmap.h"
#include "MagickCore/list.h"
#include "MagickCore/memory_.h"
#include "MagickCore/policy.h"
#include "MagickCore/resource_.h"
#include "MagickCore/semaphore.h"
#include "MagickCore/string_.h"
#include "MagickCore/token.h"
#include "MagickCore/utility.h"
#include "MagickCore/utility-private.h"
#include "MagickCore/xml-tree.h"
Macros
#define DelegateFilename "delegates.xml"
Functions
static MagickBooleanType InitializeDelegateList (ExceptionInfo *)
static MagickBooleanType LoadDelegateLists (const char *, ExceptionInfo *)
MagickPrivate MagickBooleanType DelegateComponentGenesis (void)
static void * DestroyDelegate (void *delegate_info)
MagickPrivate void DelegateComponentTerminus (void)
MagickExport char * GetDelegateCommand (const ImageInfo *image_info, Image *image, const char *decode, const char *encode, ExceptionInfo *exception)
MagickExport const char * GetDelegateCommands (const DelegateInfo *delegate_info)
MagickExport const DelegateInfo * GetDelegateInfo (const char *decode, const char *encode, ExceptionInfo *exception)
static int DelegateInfoCompare (const void *x, const void *y)
MagickExport const DelegateInfo ** GetDelegateInfoList (const char *pattern, size_t *number_delegates, ExceptionInfo *exception)
static int DelegateCompare (const void *x, const void *y)
MagickExport char ** GetDelegateList (const char *pattern, size_t *number_delegates, ExceptionInfo *exception)
MagickExport ssize_t GetDelegateMode (const DelegateInfo *delegate_info)
MagickExport MagickBooleanType GetDelegateThreadSupport (const DelegateInfo *delegate_info)
static size_t MagickMin (const size_t x, const size_t y)
static MagickBooleanType CopyDelegateFile (const char *source, const char *destination)
MagickExport MagickBooleanType InvokeDelegate (ImageInfo *image_info, Image *image, const char *decode, const char *encode, ExceptionInfo *exception)
MagickExport MagickBooleanType ListDelegateInfo (FILE *file, ExceptionInfo *exception)
static MagickBooleanType LoadDelegateList (const char *xml, const char *filename, const size_t depth, ExceptionInfo *exception)
Variables
static const char * DelegateMap
static LinkedListInfo * delegate_list = (LinkedListInfo *) NULL
static SemaphoreInfo * delegate_semaphore = (SemaphoreInfo *) NULL
static volatile MagickBooleanType instantiate_delegate = MagickFalse
Macro Definition Documentation
#define DelegateFilename "delegates.xml"
Definition at line 73 of file delegate.c.
Referenced by InitializeDelegateList().
Function Documentation
static MagickBooleanType CopyDelegateFile (const char * source, const char * destination) static
Definition at line 766 of file delegate.c.
References AcquireQuantumMemory(), GetPathAttributes(), IfMagickTrue, IsMagickTrue, MagickFalse, MagickMaxBufferExtent, MagickMin(), MagickTrue, O_BINARY, open_utf8(), RelinquishMagickMemory(), and S_MODE.
Referenced by InvokeDelegate().
static int DelegateCompare (const void * x, const void * y) static
Definition at line 561 of file delegate.c.
References LocaleCompare().
Referenced by GetDelegateList().
MagickPrivate MagickBooleanType DelegateComponentGenesis (void)
Definition at line 164 of file delegate.c.
References AcquireSemaphoreInfo(), delegate_semaphore, and MagickTrue.
Referenced by MagickCoreGenesis().
MagickPrivate void DelegateComponentTerminus (void)
Definition at line 207 of file delegate.c.
References AcquireSemaphoreInfo(), delegate_list, delegate_semaphore, DestroyDelegate(), DestroyLinkedList(), DestroySemaphoreInfo(), instantiate_delegate, LockSemaphoreInfo(), MagickFalse, and UnlockSemaphoreInfo().
Referenced by MagickCoreTerminus().
static int DelegateInfoCompare (const void * x, const void * y) static
Definition at line 454 of file delegate.c.
References LocaleCompare().
Referenced by GetDelegateInfoList().
static void* DestroyDelegate (void * delegate_info) static
Definition at line 189 of file delegate.c.
References _DelegateInfo::commands, _DelegateInfo::decode, DestroyString(), _DelegateInfo::encode, _DelegateInfo::path, and RelinquishMagickMemory().
Referenced by DelegateComponentTerminus().
MagickExport char* GetDelegateCommand (const ImageInfo * image_info, Image * image, const char * decode, const char * encode, ExceptionInfo * exception)
Definition at line 256 of file delegate.c.
References _DelegateInfo::commands, _Image::debug, DelegateError, DestroyString(), _Image::filename, GetDelegateInfo(), GetMagickModule, IfMagickTrue, InterpretImageProperties(), LogMagickEvent(), MagickSignature, RelinquishMagickMemory(), ResourceLimitError, _Image::signature, _ImageInfo::signature, StringToList(), ThrowMagickException(), and TraceEvent.
MagickExport const char* GetDelegateCommands (const DelegateInfo * delegate_info)
Definition at line 327 of file delegate.c.
References _DelegateInfo::commands, GetMagickModule, LogMagickEvent(), MagickSignature, _DelegateInfo::signature, and TraceEvent.
MagickExport const DelegateInfo* GetDelegateInfo (const char * decode, const char * encode, ExceptionInfo * exception)
Definition at line 365 of file delegate.c.
References _DelegateInfo::decode, delegate_list, delegate_semaphore, _DelegateInfo::encode, GetNextValueInLinkedList(), GetValueFromLinkedList(), IfMagickFalse, IfMagickTrue, InitializeDelegateList(), InsertValueInLinkedList(), instantiate_delegate, IsLinkedListEmpty(), LocaleCompare(), LockSemaphoreInfo(), _DelegateInfo::mode, RemoveElementByValueFromLinkedList(), ResetLinkedListIterator(), and UnlockSemaphoreInfo().
Referenced by GetDelegateCommand(), GetDelegateInfoList(), GetDelegateList(), InvokeDelegate(), ReadImage(), and WriteImage().
MagickExport const DelegateInfo** GetDelegateInfoList (const char * pattern, size_t * number_delegates, ExceptionInfo * exception)
Definition at line 479 of file delegate.c.
References AcquireQuantumMemory(), _DelegateInfo::decode, delegate_list, delegate_semaphore, DelegateInfoCompare(), _DelegateInfo::encode, GetDelegateInfo(), GetMagickModule, GetNextValueInLinkedList(), GetNumberOfElementsInLinkedList(), GlobExpression(), IfMagickFalse, IfMagickTrue, LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, ResetLinkedListIterator(), _DelegateInfo::stealth, TraceEvent, and UnlockSemaphoreInfo().
Referenced by ListDelegateInfo().
MagickExport char** GetDelegateList (const char * pattern, size_t * number_delegates, ExceptionInfo * exception)
Definition at line 576 of file delegate.c.
References AcquireQuantumMemory(), ConstantString(), _DelegateInfo::decode, delegate_list, delegate_semaphore, DelegateCompare(), _DelegateInfo::encode, GetDelegateInfo(), GetMagickModule, GetNextValueInLinkedList(), GetNumberOfElementsInLinkedList(), GlobExpression(), IfMagickFalse, IfMagickTrue, LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, ResetLinkedListIterator(), _DelegateInfo::stealth, TraceEvent, and UnlockSemaphoreInfo().
MagickExport ssize_t GetDelegateMode (const DelegateInfo * delegate_info)
Definition at line 645 of file delegate.c.
References GetMagickModule, LogMagickEvent(), MagickSignature, _DelegateInfo::mode, _DelegateInfo::signature, and TraceEvent.
Referenced by WriteImage().
MagickExport MagickBooleanType GetDelegateThreadSupport (const DelegateInfo * delegate_info)
Definition at line 678 of file delegate.c.
References GetMagickModule, LogMagickEvent(), MagickSignature, _DelegateInfo::signature, _DelegateInfo::thread_support, and TraceEvent.
Referenced by ReadImage(), and WriteImage().
static MagickBooleanType InitializeDelegateList (ExceptionInfo * exception) static
Definition at line 710 of file delegate.c.
References AcquireSemaphoreInfo(), delegate_list, delegate_semaphore, DelegateFilename, IfMagickFalse, instantiate_delegate, IsMagickNotNULL, LoadDelegateLists(), LockSemaphoreInfo(), MagickTrue, and UnlockSemaphoreInfo().
Referenced by GetDelegateInfo().
MagickExport MagickBooleanType InvokeDelegate (ImageInfo * image_info, Image * image, const char * decode, const char * encode, ExceptionInfo * exception)
Definition at line 836 of file delegate.c.
References access_utf8(), AcquireUniqueFilename(), AcquireUniqueSymbolicLink(), _ImageInfo::adjoin, CloneImageInfo(), _DelegateInfo::commands, CopyDelegateFile(), CopyMagickString(), _Image::debug, _DelegateInfo::decode, DelegateError, DelegatePolicyDomain, DestroyImageInfo(), DestroyString(), _DelegateInfo::encode, ExecutePolicyRights, _Image::filename, _ImageInfo::filename, FileOpenError, FormatLocaleString(), GetDelegateInfo(), GetImageListLength(), GetMagickModule, GetNextImageInList(), IfMagickFalse, IfMagickTrue, InterpretImageProperties(), IsMagickFalse, IsMagickTrue, IsRightsAuthorized(), LocaleCompare(), LocaleUpper(), LogMagickEvent(), _Image::magick, _ImageInfo::magick, MagickDelay(), MagickFalse, MagickSignature, MagickTrue, MaxTextExtent, _DelegateInfo::mode, PolicyError, RelinquishMagickMemory(), RelinquishUniqueFileResource(), ResourceLimitError, SetImageInfo(), _Image::signature, _ImageInfo::signature, _DelegateInfo::spawn, StringToList(), SystemCommand(), _ImageInfo::temporary, ThrowFileException, ThrowMagickException(), TraceEvent, _ImageInfo::unique, _ImageInfo::verbose, WriteImage(), and _ImageInfo::zero.
Referenced by ReadImage(), and WriteImage().
MagickExport MagickBooleanType ListDelegateInfo (FILE * file, ExceptionInfo * exception)
Definition at line 1116 of file delegate.c.
References ConcatenateMagickString(), CopyMagickString(), DestroyString(), FormatLocaleFile(), GetDelegateInfoList(), IfMagickTrue, LocaleCompare(), MagickFalse, MagickTrue, MaxTextExtent, _DelegateInfo::path, RelinquishMagickMemory(), StringToList(), and StripString().
static MagickBooleanType LoadDelegateList (const char * xml, const char * filename, const size_t depth, ExceptionInfo * exception) static
Definition at line 1217 of file delegate.c.
References AcquireMagickMemory(), AcquireString(), AppendValueToLinkedList(), _DelegateInfo::commands, ConcatenateMagickString(), ConfigureError, ConfigureEvent, ConstantString(), CopyMagickString(), _DelegateInfo::decode, delegate_list, DirectorySeparator, _DelegateInfo::encode, FileToString(), GetMagickModule, GetMagickToken(), GetPathComponent(), HeadPath, IfMagickFalse, IsStringTrue(), LocaleCompare(), LocaleNCompare(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, MaxTextExtent, _DelegateInfo::mode, NewLinkedList(), _DelegateInfo::path, RelinquishMagickMemory(), ResetMagickMemory(), ResourceLimitError, ResourceLimitFatalError, _DelegateInfo::signature, _DelegateInfo::spawn, _DelegateInfo::stealth, SubstituteString(), _DelegateInfo::thread_support, ThrowFatalException, ThrowFileException, and ThrowMagickException().
Referenced by LoadDelegateLists().
static MagickBooleanType LoadDelegateLists (const char * filename, ExceptionInfo * exception)
Definition at line 1480 of file delegate.c.
References delegate_list, DelegateMap, DestroyConfigureOptions(), GetConfigureOptions(), GetNextValueInLinkedList(), GetStringInfoDatum(), GetStringInfoPath(), IfMagickTrue, IsLinkedListEmpty(), IsMagickTrue, LoadDelegateList(), and MagickFalse.
Referenced by InitializeDelegateList().
static size_t MagickMin (const size_t x, const size_t y) inline static
Definition at line 759 of file delegate.c.
Referenced by CopyDelegateFile().
Variable Documentation
LinkedListInfo* delegate_list = (LinkedListInfo *) NULL static
Definition at line 131 of file delegate.c.
Referenced by DelegateComponentTerminus(), GetDelegateInfo(), GetDelegateInfoList(), GetDelegateList(), InitializeDelegateList(), LoadDelegateList(), and LoadDelegateLists().
SemaphoreInfo* delegate_semaphore = (SemaphoreInfo *) NULL static
Definition at line 134 of file delegate.c.
Referenced by DelegateComponentGenesis(), DelegateComponentTerminus(), GetDelegateInfo(), GetDelegateInfoList(), GetDelegateList(), and InitializeDelegateList().
const char* DelegateMap static
Definition at line 79 of file delegate.c.
Referenced by LoadDelegateLists().
volatile MagickBooleanType instantiate_delegate = MagickFalse static
Definition at line 137 of file delegate.c.
Referenced by DelegateComponentTerminus(), GetDelegateInfo(), and InitializeDelegateList().