MagickCore: display.c File Reference
display.c File Reference
#include "MagickCore/studio.h"
#include "MagickCore/artifact.h"
#include "MagickCore/attribute.h"
#include "MagickCore/blob.h"
#include "MagickCore/cache.h"
#include "MagickCore/cache-private.h"
#include "MagickCore/channel.h"
#include "MagickCore/client.h"
#include "MagickCore/color.h"
#include "MagickCore/colorspace.h"
#include "MagickCore/composite.h"
#include "MagickCore/constitute.h"
#include "MagickCore/decorate.h"
#include "MagickCore/delegate.h"
#include "MagickCore/display.h"
#include "MagickCore/display-private.h"
#include "MagickCore/distort.h"
#include "MagickCore/draw.h"
#include "MagickCore/effect.h"
#include "MagickCore/enhance.h"
#include "MagickCore/exception.h"
#include "MagickCore/exception-private.h"
#include "MagickCore/fx.h"
#include "MagickCore/geometry.h"
#include "MagickCore/image.h"
#include "MagickCore/image-private.h"
#include "MagickCore/list.h"
#include "MagickCore/log.h"
#include "MagickCore/magick.h"
#include "MagickCore/memory_.h"
#include "MagickCore/monitor.h"
#include "MagickCore/monitor-private.h"
#include "MagickCore/montage.h"
#include "MagickCore/option.h"
#include "MagickCore/paint.h"
#include "MagickCore/pixel.h"
#include "MagickCore/pixel-accessor.h"
#include "MagickCore/PreRvIcccm.h"
#include "MagickCore/property.h"
#include "MagickCore/quantum.h"
#include "MagickCore/quantum-private.h"
#include "MagickCore/resize.h"
#include "MagickCore/resource_.h"
#include "MagickCore/shear.h"
#include "MagickCore/segment.h"
#include "MagickCore/statistic.h"
#include "MagickCore/string_.h"
#include "MagickCore/string-private.h"
#include "MagickCore/transform.h"
#include "MagickCore/threshold.h"
#include "MagickCore/utility.h"
#include "MagickCore/utility-private.h"
#include "MagickCore/version.h"
#include "MagickCore/widget.h"
#include "MagickCore/widget-private.h"
#include "MagickCore/xwindow.h"
#include "MagickCore/xwindow-private.h"
Functions
MagickExport MagickBooleanType DisplayImages (const ImageInfo *image_info, Image *image, ExceptionInfo *exception)
MagickExport MagickBooleanType RemoteDisplayCommand (const ImageInfo *image_info, const char *window, const char *filename, ExceptionInfo *exception)
Function Documentation
MagickExport MagickBooleanType DisplayImages (const ImageInfo * image_info, Image * image, ExceptionInfo * exception)
Definition at line 16193 of file display.c.
References _Image::debug, _Image::filename, GetMagickModule, IfMagickTrue, LogMagickEvent(), MagickFalse, MagickSignature, MissingDelegateError, _Image::signature, _ImageInfo::signature, ThrowMagickException(), and TraceEvent.
MagickExport MagickBooleanType RemoteDisplayCommand (const ImageInfo * image_info, const char * window, const char * filename, ExceptionInfo * exception)
Definition at line 16237 of file display.c.
References _ImageInfo::filename, GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, MissingDelegateError, _ImageInfo::signature, ThrowMagickException(), and TraceEvent.