MagickCore: distort.h File Reference
distort.h File Reference
Enumerations
enum DistortImageMethod {
UndefinedDistortion, AffineDistortion, AffineProjectionDistortion, ScaleRotateTranslateDistortion,
PerspectiveDistortion, PerspectiveProjectionDistortion, BilinearForwardDistortion, BilinearDistortion = BilinearForwardDistortion,
BilinearReverseDistortion, PolynomialDistortion, ArcDistortion, PolarDistortion,
DePolarDistortion, Cylinder2PlaneDistortion, Plane2CylinderDistortion, BarrelDistortion,
BarrelInverseDistortion, ShepardsDistortion, ResizeDistortion, SentinelDistortion
}
enum SparseColorMethod {
UndefinedColorInterpolate = UndefinedDistortion, BarycentricColorInterpolate = AffineDistortion, BilinearColorInterpolate = BilinearReverseDistortion, PolynomialColorInterpolate = PolynomialDistortion,
ShepardsColorInterpolate = ShepardsDistortion, VoronoiColorInterpolate = SentinelDistortion, InverseColorInterpolate
}
Functions
MagickExport Image * AffineTransformImage (const Image *, const AffineMatrix *, ExceptionInfo *)
MagickExport Image * DistortImage (const Image *, const DistortImageMethod, const size_t, const double *, MagickBooleanType, ExceptionInfo *exception)
MagickExport Image * DistortResizeImage (const Image *, const size_t, const size_t, ExceptionInfo *)
MagickExport Image * RotateImage (const Image *, const double, ExceptionInfo *)
MagickExport Image * SparseColorImage (const Image *, const SparseColorMethod, const size_t, const double *, ExceptionInfo *)
Enumeration Type Documentation
enum DistortImageMethod
Enumerator
UndefinedDistortion
AffineDistortion
AffineProjectionDistortion
ScaleRotateTranslateDistortion
PerspectiveDistortion
PerspectiveProjectionDistortion
BilinearForwardDistortion
BilinearDistortion
BilinearReverseDistortion
PolynomialDistortion
ArcDistortion
PolarDistortion
DePolarDistortion
Cylinder2PlaneDistortion
Plane2CylinderDistortion
BarrelDistortion
BarrelInverseDistortion
ShepardsDistortion
ResizeDistortion
SentinelDistortion
Definition at line 34 of file distort.h.
enum SparseColorMethod
Enumerator
UndefinedColorInterpolate
BarycentricColorInterpolate
BilinearColorInterpolate
PolynomialColorInterpolate
ShepardsColorInterpolate
VoronoiColorInterpolate
InverseColorInterpolate
Definition at line 58 of file distort.h.
Function Documentation
MagickExport Image* AffineTransformImage (const Image * , const AffineMatrix * , ExceptionInfo *)
MagickExport Image * DistortImage (const Image * , const DistortImageMethod , const size_t , const double * , MagickBooleanType , ExceptionInfo * exception)
MagickExport Image * DistortResizeImage (const Image * , const size_t , const size_t , ExceptionInfo *)
MagickExport Image * RotateImage (const Image * , const double , ExceptionInfo *)
MagickExport Image * SparseColorImage (const Image * , const SparseColorMethod , const size_t , const double * , ExceptionInfo *)
Definition at line 2895 of file distort.c.
References AcquireAuthenticCacheView(), _PixelInfo::alpha, _Image::alpha_trait, BarycentricColorInterpolate, BilinearColorInterpolate, _PixelInfo::black, BlendPixelTrait, _PixelInfo::blue, CloneImage(), CMYKColorspace, _Image::colorspace, _Image::columns, _Image::debug, DestroyCacheView(), DestroyImage(), DirectClass, _Image::filename, FormatLocaleFile(), GenerateCoefficients(), GetCacheViewAuthenticPixels(), GetImageArtifact(), GetMagickModule, GetPixelAlphaTraits(), GetPixelBlackTraits(), GetPixelBlueTraits(), GetPixelChannels(), GetPixelGreenTraits(), GetPixelInfo(), GetPixelInfoPixel(), GetPixelRedTraits(), _PixelInfo::green, IfStringTrue, InverseColorInterpolate, LogMagickEvent(), MagickFalse, MagickHuge, MagickSignature, MagickTrue, _Image::progress_monitor, QuantumRange, _PixelInfo::red, RelinquishMagickMemory(), _Image::rows, SentinelDistortion, SetImageProgress(), SetImageStorageClass(), SetPixelInfoPixel(), ShepardsColorInterpolate, ShepardsDistortion, _ExceptionInfo::signature, _Image::signature, SparseColorTag, SyncCacheViewAuthenticPixels(), TraceEvent, UpdatePixelTrait, and VoronoiColorInterpolate.