MagickCore: draw.h File Reference
draw.h File Reference
#include "MagickCore/geometry.h"
#include "MagickCore/image.h"
#include "MagickCore/pixel.h"
#include "MagickCore/type.h"
Data Structures
struct _StopInfo
struct _GradientInfo
struct _ElementReference
struct _DrawInfo
struct _PrimitiveInfo
struct _TypeMetric
Typedefs
typedef struct _StopInfo StopInfo
typedef struct _GradientInfo GradientInfo
typedef struct _ElementReference ElementReference
typedef struct _DrawInfo DrawInfo
typedef struct _PrimitiveInfo PrimitiveInfo
typedef struct _TypeMetric TypeMetric
Enumerations
enum AlignType { UndefinedAlign, LeftAlign, CenterAlign, RightAlign }
enum ClipPathUnits { UndefinedPathUnits, UserSpace, UserSpaceOnUse, ObjectBoundingBox }
enum DecorationType {
UndefinedDecoration, NoDecoration, UnderlineDecoration, OverlineDecoration,
LineThroughDecoration
}
enum DirectionType { UndefinedDirection, RightToLeftDirection, LeftToRightDirection }
enum FillRule { UndefinedRule, EvenOddRule, NonZeroRule }
enum GradientType { UndefinedGradient, LinearGradient, RadialGradient }
enum LineCap { UndefinedCap, ButtCap, RoundCap, SquareCap }
enum LineJoin { UndefinedJoin, MiterJoin, RoundJoin, BevelJoin }
enum PaintMethod {
UndefinedMethod, PointMethod, ReplaceMethod, FloodfillMethod,
FillToBorderMethod, ResetMethod
}
enum PrimitiveType {
UndefinedPrimitive, PointPrimitive, LinePrimitive, RectanglePrimitive,
RoundRectanglePrimitive, ArcPrimitive, EllipsePrimitive, CirclePrimitive,
PolylinePrimitive, PolygonPrimitive, BezierPrimitive, ColorPrimitive,
MattePrimitive, TextPrimitive, ImagePrimitive, PathPrimitive
}
enum ReferenceType { UndefinedReference, GradientReference }
enum SpreadMethod { UndefinedSpread, PadSpread, ReflectSpread, RepeatSpread }
Functions
MagickExport DrawInfo * AcquireDrawInfo (void)
MagickExport DrawInfo * CloneDrawInfo (const ImageInfo *, const DrawInfo *)
MagickExport DrawInfo * DestroyDrawInfo (DrawInfo *)
MagickExport MagickBooleanType DrawAffineImage (Image *, const Image *, const AffineMatrix *, ExceptionInfo *)
MagickExport MagickBooleanType DrawClipPath (Image *, const DrawInfo *, const char *, ExceptionInfo *)
MagickExport MagickBooleanType DrawGradientImage (Image *, const DrawInfo *, ExceptionInfo *)
MagickExport MagickBooleanType DrawImage (Image *, const DrawInfo *, ExceptionInfo *)
MagickExport MagickBooleanType DrawPatternPath (Image *, const DrawInfo *, const char *, Image **, ExceptionInfo *)
MagickExport MagickBooleanType DrawPrimitive (Image *, const DrawInfo *, const PrimitiveInfo *, ExceptionInfo *)
MagickExport void GetAffineMatrix (AffineMatrix *)
MagickExport void GetDrawInfo (const ImageInfo *, DrawInfo *)
Typedef Documentation
typedef struct _DrawInfo DrawInfo
typedef struct _ElementReference ElementReference
typedef struct _GradientInfo GradientInfo
typedef struct _PrimitiveInfo PrimitiveInfo
typedef struct _StopInfo StopInfo
typedef struct _TypeMetric TypeMetric
Enumeration Type Documentation
enum AlignType
Enumerator
UndefinedAlign
LeftAlign
CenterAlign
RightAlign
Definition at line 30 of file draw.h.
enum ClipPathUnits
Enumerator
UndefinedPathUnits
UserSpace
UserSpaceOnUse
ObjectBoundingBox
Definition at line 38 of file draw.h.
enum DecorationType
Enumerator
UndefinedDecoration
NoDecoration
UnderlineDecoration
OverlineDecoration
LineThroughDecoration
Definition at line 46 of file draw.h.
enum DirectionType
Enumerator
UndefinedDirection
RightToLeftDirection
LeftToRightDirection
Definition at line 55 of file draw.h.
enum FillRule
Enumerator
UndefinedRule
EvenOddRule
NonZeroRule
Definition at line 62 of file draw.h.
enum GradientType
Enumerator
UndefinedGradient
LinearGradient
RadialGradient
Definition at line 70 of file draw.h.
enum LineCap
Enumerator
UndefinedCap
ButtCap
RoundCap
SquareCap
Definition at line 77 of file draw.h.
enum LineJoin
Enumerator
UndefinedJoin
MiterJoin
RoundJoin
BevelJoin
Definition at line 85 of file draw.h.
enum PaintMethod
Enumerator
UndefinedMethod
PointMethod
ReplaceMethod
FloodfillMethod
FillToBorderMethod
ResetMethod
Definition at line 93 of file draw.h.
enum PrimitiveType
Enumerator
UndefinedPrimitive
PointPrimitive
LinePrimitive
RectanglePrimitive
RoundRectanglePrimitive
ArcPrimitive
EllipsePrimitive
CirclePrimitive
PolylinePrimitive
PolygonPrimitive
BezierPrimitive
ColorPrimitive
MattePrimitive
TextPrimitive
ImagePrimitive
PathPrimitive
Definition at line 103 of file draw.h.
enum ReferenceType
Enumerator
UndefinedReference
GradientReference
Definition at line 123 of file draw.h.
enum SpreadMethod
Enumerator
UndefinedSpread
PadSpread
ReflectSpread
RepeatSpread
Definition at line 129 of file draw.h.
Function Documentation
MagickExport DrawInfo* AcquireDrawInfo (void)
MagickExport DrawInfo * CloneDrawInfo (const ImageInfo * , const DrawInfo *)
MagickExport DrawInfo * DestroyDrawInfo (DrawInfo *)
Definition at line 809 of file draw.c.
References _DrawInfo::clip_mask, _DrawInfo::dash_pattern, _DrawInfo::debug, _DrawInfo::density, DestroyImage(), DestroyString(), _DrawInfo::encoding, _DrawInfo::family, _DrawInfo::fill_pattern, _DrawInfo::font, _DrawInfo::geometry, GetMagickModule, _DrawInfo::gradient, LogMagickEvent(), MagickFalse, MagickSignature, _DrawInfo::metrics, _DrawInfo::primitive, RelinquishMagickMemory(), _DrawInfo::server_name, _DrawInfo::signature, _GradientInfo::stops, _DrawInfo::stroke_pattern, _DrawInfo::text, and TraceEvent.
Referenced by AnnotateImage(), DrawBoundingRectangles(), DrawClipPath(), DrawDashPolygon(), DrawImage(), DrawPatternPath(), DrawPrimitive(), DrawStrokePolygon(), GetMultilineTypeMetrics(), GetTypeMetrics(), GradientImage(), MontageImageList(), PolaroidImage(), RenderType(), and VignetteImage().
MagickExport MagickBooleanType DrawAffineImage (Image * , const Image * , const AffineMatrix * , ExceptionInfo *)
MagickExport MagickBooleanType DrawClipPath (Image * , const DrawInfo * , const char * , ExceptionInfo *)
MagickExport MagickBooleanType DrawGradientImage (Image * , const DrawInfo * , ExceptionInfo *)
MagickExport MagickBooleanType DrawImage (Image * , const DrawInfo * , ExceptionInfo *)
MagickExport MagickBooleanType DrawPatternPath (Image * , const DrawInfo * , const char * , Image ** , ExceptionInfo *)
MagickExport MagickBooleanType DrawPrimitive (Image * , const DrawInfo * , const PrimitiveInfo * , ExceptionInfo *)
Definition at line 4123 of file draw.c.
References AcquireAuthenticCacheView(), AcquireImageInfo(), _DrawInfo::affine, _PixelInfo::alpha, _DrawInfo::alpha, _Image::alpha_trait, AlphaChannel, AnnotateImage(), BlendPixelTrait, _PixelInfo::blue, _DrawInfo::border_color, ClampToQuantum(), CloneDrawInfo(), CloneString(), ColorPrimitive, _Image::colorspace, _Image::columns, _DrawInfo::compose, CompositeImage(), CompositePixelOver(), CopyMagickString(), _DrawInfo::dash_pattern, _Image::debug, DestroyCacheView(), DestroyDrawInfo(), DestroyImage(), DestroyImageInfo(), DrawAffineImage(), DrawDashPolygon(), DrawEvent, DrawPolygonPrimitive(), DrawStrokePolygon(), ExpandAffine(), _ImageInfo::filename, _DrawInfo::fill, FillToBorderMethod, _Image::filter, FloodfillMethod, FloodfillPaintImage(), FormatLocaleString(), _DrawInfo::geometry, GetCacheViewAuthenticPixels(), GetFillColor(), GetMagickModule, GetOneCacheViewVirtualPixelInfo(), GetOneVirtualPixelInfo(), GetPixelAlpha(), GetPixelChannels(), GetPixelInfo(), GetPixelInfoPixel(), _Image::gravity, _DrawInfo::gravity, _PixelInfo::green, ImagePrimitive, _Image::interpolate, IsEventLogging(), IsFuzzyEquivalencePixelInfo(), IsGrayColorspace(), IsPixelInfoGray(), _DrawInfo::linecap, _DrawInfo::linejoin, LocaleNCompare(), LogMagickEvent(), LogPrimitiveInfo(), MagickEpsilon, MagickFalse, MagickTrue, MattePrimitive, MaxTextExtent, _PrimitiveInfo::method, OpaqueAlpha, OpaqueAlphaChannel, OverCompositeOp, ParseGravityGeometry(), _PrimitiveInfo::point, PointMethod, PointPrimitive, _PrimitiveInfo::primitive, ReadImage(), ReadInlineImage(), _PixelInfo::red, ReplaceMethod, ResetMethod, RoundCap, RoundJoin, _Image::rows, _AffineMatrix::rx, _AffineMatrix::ry, SetGeometry(), SetImageAlpha(), SetImageAlphaChannel(), SetImageChannelMask(), SetImageColorspace(), SetImageProgressMonitor(), SetPixelAlpha(), SetPixelInfoPixel(), sRGBColorspace, _DrawInfo::stroke, _DrawInfo::stroke_width, _AffineMatrix::sx, _AffineMatrix::sy, SyncCacheViewAuthenticPixels(), _DrawInfo::text, _PrimitiveInfo::text, TextPrimitive, TileVirtualPixelMethod, TransformImage(), TransparentAlpha, _AffineMatrix::tx, _AffineMatrix::ty, UndefinedPrimitive, _PointInfo::x, _RectangleInfo::x, _PointInfo::y, and _RectangleInfo::y.
Referenced by DrawBoundingRectangles(), and DrawImage().
MagickExport void GetAffineMatrix (AffineMatrix *)
MagickExport void GetDrawInfo (const ImageInfo * , DrawInfo *)
Definition at line 4752 of file draw.c.
References AcquireExceptionInfo(), AcquireString(), _DrawInfo::affine, AllCompliance, _PixelInfo::alpha, _DrawInfo::alpha, _ImageInfo::antialias, _DrawInfo::border_color, _ImageInfo::border_color, ButtCap, CloneString(), _DrawInfo::compose, _DrawInfo::debug, _DrawInfo::decorate, _DrawInfo::density, _ImageInfo::density, DestroyExceptionInfo(), _DrawInfo::direction, _DrawInfo::encoding, EvenOddRule, _DrawInfo::fill, _DrawInfo::fill_rule, _DrawInfo::font, _ImageInfo::font, GetAffineMatrix(), GetImageOption(), GetMagickModule, _DrawInfo::gravity, _DrawInfo::interline_spacing, _DrawInfo::interword_spacing, IsEventLogging(), _DrawInfo::kerning, _DrawInfo::linecap, _DrawInfo::linejoin, LogMagickEvent(), MagickDirectionOptions, MagickFalse, MagickGravityOptions, MagickSignature, MagickTrue, MiterJoin, _DrawInfo::miterlimit, NoDecoration, OpaqueAlpha, OverCompositeOp, ParseCommandOption(), _DrawInfo::pointsize, _ImageInfo::pointsize, QueryColorCompliance(), _DrawInfo::render, ResetMagickMemory(), _DrawInfo::server_name, _ImageInfo::server_name, _DrawInfo::signature, StringToDouble(), _DrawInfo::stroke, _DrawInfo::stroke_antialias, _DrawInfo::stroke_width, _DrawInfo::text_antialias, TraceEvent, TransparentAlpha, UndefinedDirection, and _DrawInfo::undercolor.
Referenced by AcquireDrawInfo(), and CloneDrawInfo().