MagickCore: draw-private.h File Reference
draw-private.h File Reference
#include "MagickCore/cache.h"
#include "MagickCore/image.h"
#include "MagickCore/memory_.h"
Functions
static MagickBooleanType GetFillColor (const DrawInfo *draw_info, const ssize_t x, const ssize_t y, PixelInfo *fill, ExceptionInfo *exception)
static MagickBooleanType GetStrokeColor (const DrawInfo *draw_info, const ssize_t x, const ssize_t y, PixelInfo *stroke, ExceptionInfo *exception)
Function Documentation
static MagickBooleanType GetFillColor (const DrawInfo * draw_info, const ssize_t x, const ssize_t y, PixelInfo * fill, ExceptionInfo * exception) inline static
Definition at line 29 of file draw-private.h.
References _DrawInfo::fill, _DrawInfo::fill_pattern, GetOneVirtualPixelInfo(), MagickTrue, _Image::tile_offset, TileVirtualPixelMethod, _RectangleInfo::x, and _RectangleInfo::y.
Referenced by DrawPolygonPrimitive(), DrawPrimitive(), FloodfillPaintImage(), and RenderPostscript().
static MagickBooleanType GetStrokeColor (const DrawInfo * draw_info, const ssize_t x, const ssize_t y, PixelInfo * stroke, ExceptionInfo * exception) inline static
Definition at line 51 of file draw-private.h.
References GetOneVirtualPixelInfo(), MagickTrue, _DrawInfo::stroke, _DrawInfo::stroke_pattern, _Image::tile_offset, TileVirtualPixelMethod, _RectangleInfo::x, and _RectangleInfo::y.
Referenced by DrawPolygonPrimitive().