MagickCore: effect.c File Reference
effect.c File Reference
#include "MagickCore/studio.h"
#include "MagickCore/accelerate.h"
#include "MagickCore/blob.h"
#include "MagickCore/cache-view.h"
#include "MagickCore/color.h"
#include "MagickCore/color-private.h"
#include "MagickCore/colorspace.h"
#include "MagickCore/constitute.h"
#include "MagickCore/decorate.h"
#include "MagickCore/distort.h"
#include "MagickCore/draw.h"
#include "MagickCore/enhance.h"
#include "MagickCore/exception.h"
#include "MagickCore/exception-private.h"
#include "MagickCore/effect.h"
#include "MagickCore/fx.h"
#include "MagickCore/gem.h"
#include "MagickCore/gem-private.h"
#include "MagickCore/geometry.h"
#include "MagickCore/image-private.h"
#include "MagickCore/list.h"
#include "MagickCore/log.h"
#include "MagickCore/memory_.h"
#include "MagickCore/memory-private.h"
#include "MagickCore/monitor.h"
#include "MagickCore/monitor-private.h"
#include "MagickCore/montage.h"
#include "MagickCore/morphology.h"
#include "MagickCore/paint.h"
#include "MagickCore/pixel-accessor.h"
#include "MagickCore/pixel-private.h"
#include "MagickCore/property.h"
#include "MagickCore/quantize.h"
#include "MagickCore/quantum.h"
#include "MagickCore/quantum-private.h"
#include "MagickCore/random_.h"
#include "MagickCore/random-private.h"
#include "MagickCore/resample.h"
#include "MagickCore/resample-private.h"
#include "MagickCore/resize.h"
#include "MagickCore/resource_.h"
#include "MagickCore/segment.h"
#include "MagickCore/shear.h"
#include "MagickCore/signature-private.h"
#include "MagickCore/statistic.h"
#include "MagickCore/string_.h"
#include "MagickCore/thread-private.h"
#include "MagickCore/transform.h"
#include "MagickCore/threshold.h"
Macros
#define AdaptiveBlurImageTag "Convolve/Image"
#define MagickSigma (fabs(sigma) < MagickEpsilon ? MagickEpsilon : sigma)
#define AdaptiveSharpenImageTag "Convolve/Image"
#define MagickSigma (fabs(sigma) < MagickEpsilon ? MagickEpsilon : sigma)
#define DespeckleImageTag "Despeckle/Image"
#define BlurImageTag "Blur/Image"
#define NumberTiles 9
#define PreviewImageTag "Preview/Image"
#define DefaultPreviewGeometry "204x204+10+10"
#define SelectiveBlurImageTag "SelectiveBlur/Image"
#define ShadeImageTag "Shade/Image"
#define SpreadImageTag "Spread/Image"
#define SharpenImageTag "Sharpen/Image"
Functions
MagickExport MagickBooleanType AdaptiveLevelImage (Image *image, const char *levels, ExceptionInfo *exception)
MagickExport Image * AdaptiveBlurImage (const Image *image, const double radius, const double sigma, ExceptionInfo *exception)
MagickExport Image * AdaptiveSharpenImage (const Image *image, const double radius, const double sigma, ExceptionInfo *exception)
MagickExport Image * BlurImage (const Image *image, const double radius, const double sigma, ExceptionInfo *exception)
MagickExport Image * ConvolveImage (const Image *image, const KernelInfo *kernel_info, ExceptionInfo *exception)
static void Hull (const Image *image, const ssize_t x_offset, const ssize_t y_offset, const size_t columns, const size_t rows, const int polarity, Quantum *restrict f, Quantum *restrict g)
MagickExport Image * DespeckleImage (const Image *image, ExceptionInfo *exception)
MagickExport Image * EdgeImage (const Image *image, const double radius, const double sigma, ExceptionInfo *exception)
MagickExport Image * EmbossImage (const Image *image, const double radius, const double sigma, ExceptionInfo *exception)
MagickExport Image * GaussianBlurImage (const Image *image, const double radius, const double sigma, ExceptionInfo *exception)
static MagickRealType * GetMotionBlurKernel (const size_t width, const double sigma)
MagickExport Image * MotionBlurImage (const Image *image, const double radius, const double sigma, const double angle, ExceptionInfo *exception)
MagickExport Image * PreviewImage (const Image *image, const PreviewType preview, ExceptionInfo *exception)
MagickExport Image * RadialBlurImage (const Image *image, const double angle, ExceptionInfo *exception)
MagickExport Image * SelectiveBlurImage (const Image *image, const double radius, const double sigma, const double threshold, ExceptionInfo *exception)
MagickExport Image * ShadeImage (const Image *image, const MagickBooleanType gray, const double azimuth, const double elevation, ExceptionInfo *exception)
MagickExport Image * SharpenImage (const Image *image, const double radius, const double sigma, ExceptionInfo *exception)
MagickExport Image * SpreadImage (const Image *image, const double radius, const PixelInterpolateMethod method, ExceptionInfo *exception)
MagickExport Image * UnsharpMaskImage (const Image *image, const double radius, const double sigma, const double amount, const double threshold, ExceptionInfo *exception)
Macro Definition Documentation
#define AdaptiveBlurImageTag "Convolve/Image"
Referenced by AdaptiveBlurImage().
#define AdaptiveSharpenImageTag "Convolve/Image"
Referenced by AdaptiveSharpenImage().
#define BlurImageTag "Blur/Image"
Referenced by MotionBlurImage(), and RadialBlurImage().
#define DefaultPreviewGeometry "204x204+10+10"
Referenced by PreviewImage().
#define DespeckleImageTag "Despeckle/Image"
Referenced by DespeckleImage().
#define MagickSigma (fabs(sigma) < MagickEpsilon ? MagickEpsilon : sigma)
Referenced by AdaptiveBlurImage(), AdaptiveSharpenImage(), BlurImage(), EmbossImage(), GaussianBlurImage(), GetMotionBlurKernel(), SelectiveBlurImage(), and SharpenImage().
#define MagickSigma (fabs(sigma) < MagickEpsilon ? MagickEpsilon : sigma)
#define NumberTiles 9
Referenced by PreviewImage().
#define PreviewImageTag "Preview/Image"
Referenced by PreviewImage().
#define SelectiveBlurImageTag "SelectiveBlur/Image"
Referenced by SelectiveBlurImage().
#define ShadeImageTag "Shade/Image"
Referenced by ShadeImage().
#define SharpenImageTag "Sharpen/Image"
Referenced by UnsharpMaskImage().
#define SpreadImageTag "Spread/Image"
Referenced by SpreadImage().
Function Documentation
MagickExport Image* AdaptiveBlurImage (const Image * image, const double radius, const double sigma, ExceptionInfo * exception)
Definition at line 172 of file effect.c.
References AcquireAlignedMemory(), AcquireAuthenticCacheView(), AcquireVirtualCacheView(), AdaptiveBlurImageTag, AdaptiveLevelImage(), BlendPixelTrait, ClampToQuantum(), CloneImage(), _Image::columns, CopyPixelTrait, _Image::debug, DestroyCacheView(), DestroyImage(), DirectClass, EdgeImage(), _Image::filename, GaussianBlurImage(), GetCacheViewVirtualPixels(), GetMagickModule, GetOptimalKernelWidth2D(), GetPixelAlpha(), GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelIntensity(), GetPixelMask(), LogMagickEvent(), MagickAssumeAligned, MagickEpsilon, MagickFalse, MagickPI, MagickSigma, MagickSignature, MagickTrue, PerceptibleReciprocal(), _Image::progress_monitor, QuantumScale, QueueCacheViewAuthenticPixels(), RelinquishAlignedMemory(), ResetMagickMemory(), ResourceLimitError, _Image::rows, SetImageProgress(), SetImageStorageClass(), SetPixelChannel(), _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), ThrowImageException, TraceEvent, _Image::type, and UndefinedPixelTrait.
MagickExport MagickBooleanType AdaptiveLevelImage (Image * image, const char * levels, ExceptionInfo * exception)
Definition at line 128 of file effect.c.
References AspectValue, _Image::columns, LevelImage(), LevelizeImage(), MagickFalse, ParseGeometry(), PercentValue, QuantumRange, _GeometryInfo::rho, _Image::rows, _GeometryInfo::sigma, SigmaValue, _GeometryInfo::xi, and XiValue.
Referenced by AdaptiveBlurImage(), and AdaptiveSharpenImage().
MagickExport Image* AdaptiveSharpenImage (const Image * image, const double radius, const double sigma, ExceptionInfo * exception)
Definition at line 497 of file effect.c.
References AcquireAlignedMemory(), AcquireAuthenticCacheView(), AcquireVirtualCacheView(), AdaptiveLevelImage(), AdaptiveSharpenImageTag, BlendPixelTrait, ClampToQuantum(), CloneImage(), _Image::columns, CopyPixelTrait, _Image::debug, DestroyCacheView(), DestroyImage(), DirectClass, EdgeImage(), _Image::filename, GaussianBlurImage(), GetCacheViewVirtualPixels(), GetMagickModule, GetOptimalKernelWidth2D(), GetPixelAlpha(), GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelIntensity(), GetPixelMask(), LogMagickEvent(), MagickAssumeAligned, MagickEpsilon, MagickFalse, MagickPI, MagickSigma, MagickSignature, MagickTrue, PerceptibleReciprocal(), _Image::progress_monitor, QuantumScale, QueueCacheViewAuthenticPixels(), RelinquishAlignedMemory(), ResetMagickMemory(), ResourceLimitError, _Image::rows, SetImageProgress(), SetImageStorageClass(), SetPixelChannel(), _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), ThrowImageException, TraceEvent, _Image::type, and UndefinedPixelTrait.
MagickExport Image* BlurImage (const Image * image, const double radius, const double sigma, ExceptionInfo * exception)
Definition at line 821 of file effect.c.
References AcquireAlignedMemory(), AcquireKernelInfo(), ConvolveImage(), _Image::debug, DestroyKernelInfo(), _Image::filename, GetMagickModule, GetOptimalKernelWidth2D(), _KernelInfo::height, LogMagickEvent(), MagickAssumeAligned, MagickFalse, MagickPI, MagickSigma, MagickSignature, ResetMagickMemory(), ResourceLimitError, _ExceptionInfo::signature, _KernelInfo::signature, _Image::signature, ThrowImageException, TraceEvent, _KernelInfo::values, _KernelInfo::width, _KernelInfo::x, and _KernelInfo::y.
Referenced by CharcoalImage(), PreviewImage(), ShadowImage(), UnsharpMaskImage(), and VignetteImage().
MagickExport Image* ConvolveImage (const Image * image, const KernelInfo * kernel_info, ExceptionInfo * exception)
Definition at line 914 of file effect.c.
References CorrelateMorphology, and MorphologyImage().
Referenced by BlurImage(), EdgeImage(), EmbossImage(), GaussianBlurImage(), and SharpenImage().
MagickExport Image* DespeckleImage (const Image * image, ExceptionInfo * exception)
Definition at line 1041 of file effect.c.
References AcquireAuthenticCacheView(), AcquireQuantumMemory(), AcquireVirtualCacheView(), CloneImage(), _Image::columns, CopyPixelTrait, _Image::debug, DespeckleImageTag, DestroyCacheView(), DestroyImage(), DirectClass, _Image::filename, GetCacheViewAuthenticPixels(), GetCacheViewVirtualPixels(), GetMagickModule, GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), Hull(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, _Image::progress_monitor, RelinquishMagickMemory(), ResetMagickMemory(), ResourceLimitError, _Image::rows, SetImageProgress(), SetImageStorageClass(), SetPixelChannel(), _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), ThrowImageException, TraceEvent, _Image::type, and UndefinedPixelTrait.
Referenced by PreviewImage().
MagickExport Image* EdgeImage (const Image * image, const double radius, const double sigma, ExceptionInfo * exception)
Definition at line 1243 of file effect.c.
References AcquireAlignedMemory(), AcquireKernelInfo(), ConvolveImage(), _Image::debug, DestroyKernelInfo(), _Image::filename, GetMagickModule, GetOptimalKernelWidth1D(), _KernelInfo::height, LogMagickEvent(), MagickAssumeAligned, MagickFalse, MagickSignature, ResourceLimitError, _ExceptionInfo::signature, _Image::signature, ThrowImageException, TraceEvent, _KernelInfo::values, _KernelInfo::width, _KernelInfo::x, and _KernelInfo::y.
Referenced by AdaptiveBlurImage(), AdaptiveSharpenImage(), CharcoalImage(), PreviewImage(), and SketchImage().
MagickExport Image* EmbossImage (const Image * image, const double radius, const double sigma, ExceptionInfo * exception)
Definition at line 1334 of file effect.c.
References AcquireAlignedMemory(), AcquireKernelInfo(), ConvolveImage(), _Image::debug, DestroyKernelInfo(), EqualizeImage(), _Image::filename, GetMagickModule, GetOptimalKernelWidth1D(), _KernelInfo::height, LogMagickEvent(), MagickAssumeAligned, MagickFalse, MagickPI, MagickSigma, MagickSignature, ResourceLimitError, _ExceptionInfo::signature, _Image::signature, ThrowImageException, TraceEvent, _KernelInfo::values, _KernelInfo::width, _KernelInfo::x, and _KernelInfo::y.
MagickExport Image* GaussianBlurImage (const Image * image, const double radius, const double sigma, ExceptionInfo * exception)
Definition at line 1433 of file effect.c.
References AcquireAlignedMemory(), AcquireKernelInfo(), ConvolveImage(), _Image::debug, DestroyKernelInfo(), _Image::filename, GetMagickModule, GetOptimalKernelWidth2D(), _KernelInfo::height, LogMagickEvent(), MagickAssumeAligned, MagickFalse, MagickPI, MagickSigma, MagickSignature, ResetMagickMemory(), ResourceLimitError, _ExceptionInfo::signature, _KernelInfo::signature, _Image::signature, ThrowImageException, TraceEvent, _KernelInfo::values, _KernelInfo::width, _KernelInfo::x, and _KernelInfo::y.
Referenced by AdaptiveBlurImage(), and AdaptiveSharpenImage().
static MagickRealType* GetMotionBlurKernel (const size_t width, const double sigma) static
Definition at line 1532 of file effect.c.
References AcquireAlignedMemory(), GetMagickModule, LogMagickEvent(), MagickAssumeAligned, MagickSigma, MagickSQ2PI, and TraceEvent.
Referenced by MotionBlurImage().
static void Hull (const Image * image, const ssize_t x_offset, const ssize_t y_offset, const size_t columns, const size_t rows, const int polarity, Quantum *restrict f, Quantum *restrict g) static
Definition at line 949 of file effect.c.
Referenced by DespeckleImage().
MagickExport Image* MotionBlurImage (const Image * image, const double radius, const double sigma, const double angle, ExceptionInfo * exception)
Definition at line 1562 of file effect.c.
References AcquireAuthenticCacheView(), AcquireQuantumMemory(), AcquireVirtualCacheView(), BlendPixelTrait, BlurImageTag, ClampToQuantum(), CloneImage(), _Image::columns, CopyPixelTrait, _Image::debug, DegreesToRadians(), DestroyCacheView(), DestroyImage(), DirectClass, _Image::filename, GetCacheViewVirtualPixels(), GetMagickModule, GetMotionBlurKernel(), GetOptimalKernelWidth1D(), GetPixelAlpha(), GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelMask(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, PerceptibleReciprocal(), _Image::progress_monitor, QuantumScale, QueueCacheViewAuthenticPixels(), RelinquishAlignedMemory(), RelinquishMagickMemory(), ResourceLimitError, _Image::rows, SetImageProgress(), SetImageStorageClass(), SetPixelChannel(), _Image::signature, SyncCacheViewAuthenticPixels(), ThrowImageException, TraceEvent, UndefinedPixelTrait, _OffsetInfo::x, _PointInfo::x, _OffsetInfo::y, and _PointInfo::y.
Referenced by SketchImage().
MagickExport Image* PreviewImage (const Image * image, const PreviewType preview, ExceptionInfo * exception)
Definition at line 1804 of file effect.c.
References AcquireImageInfo(), AcquireUniqueFileResource(), AddNoisePreview, AllCompliance, AppendImageToList(), BilevelImage(), BlurImage(), BlurPreview, BrightnessPreview, CharcoalDrawingPreview, CharcoalImage(), CloneImage(), CloneMontageInfo(), CloneString(), _QuantizeInfo::colorspace, _Image::columns, ContrastImage(), CopyMagickString(), _Image::debug, DefaultPreviewGeometry, DefaultTileFrame, DefaultTileLabel, DeleteImageProperty(), DespeckleImage(), DespecklePreview, DestroyImage(), DestroyImageInfo(), DestroyImageList(), DestroyMontageInfo(), _Image::directory, DullPreview, EdgeDetectPreview, EdgeImage(), _MontageInfo::filename, _Image::filename, _ImageInfo::filename, FormatLocaleString(), _MontageInfo::frame, GammaImage(), GammaPreview, _MontageInfo::geometry, GetBlobSize(), GetMagickModule, GetQuantizeInfo(), GRAYColorspace, GrayscalePreview, _RectangleInfo::height, HuePreview, ImplodeImage(), ImplodePreview, _Image::interpolate, JPEGPreview, LogMagickEvent(), _Image::magick, MagickFalse, MagickSignature, MagickTrue, _Image::matte_color, MaxTextExtent, ModulateImage(), _Image::montage, MontageImages(), NewImageList(), NonpeakStatistic, _QuantizeInfo::number_colors, NumberTiles, OilPaintImage(), OilPaintPreview, ParseMetaGeometry(), PreviewImageTag, _ImageInfo::quality, QuantizeImage(), QuantizePreview, QuantumRange, QueryColorCompliance(), RaiseImage(), RaisePreview, ReadImage(), ReduceNoisePreview, RelinquishMagickMemory(), RelinquishUniqueFileResource(), ResourceLimitError, RollImage(), RollPreview, RotateImage(), RotatePreview, _Image::rows, SaturationPreview, SegmentImage(), SegmentPreview, SetGeometry(), SetImageProgress(), SetImageProgressMonitor(), SetImageProperty(), ShadeImage(), ShadePreview, _MontageInfo::shadow, SharpenImage(), SharpenPreview, ShearImage(), ShearPreview, _Image::signature, SolarizeImage(), SolarizePreview, SpiffPreview, SpreadImage(), SpreadPreview, sRGBColorspace, StatisticImage(), SwirlImage(), SwirlPreview, ThresholdPreview, ThrowImageException, ThumbnailImage(), _MontageInfo::tile, TraceEvent, WaveImage(), WavePreview, _RectangleInfo::width, WriteImage(), _RectangleInfo::x, and _RectangleInfo::y.
MagickExport Image* RadialBlurImage (const Image * image, const double angle, ExceptionInfo * exception)
Definition at line 2335 of file effect.c.
References AcquireAuthenticCacheView(), AcquireQuantumMemory(), AcquireVirtualCacheView(), BlendPixelTrait, BlurImageTag, ClampToQuantum(), CloneImage(), _Image::columns, CopyPixelTrait, _Image::debug, DegreesToRadians(), DestroyCacheView(), DestroyImage(), DirectClass, _Image::filename, GetCacheViewVirtualPixels(), GetMagickModule, GetPixelAlpha(), GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelMask(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, PerceptibleReciprocal(), _Image::progress_monitor, QueueCacheViewAuthenticPixels(), RelinquishMagickMemory(), ResourceLimitError, _Image::rows, SetImageProgress(), SetImageStorageClass(), SetPixelChannel(), _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), ThrowImageException, TraceEvent, UndefinedPixelTrait, _PointInfo::x, and _PointInfo::y.
MagickExport Image* SelectiveBlurImage (const Image * image, const double radius, const double sigma, const double threshold, ExceptionInfo * exception)
Definition at line 2603 of file effect.c.
References AcquireAlignedMemory(), AcquireAuthenticCacheView(), AcquireString(), AcquireVirtualCacheView(), BlendPixelTrait, ClampToQuantum(), CloneImage(), _Image::columns, ConcatenateString(), CopyPixelTrait, _Image::debug, DestroyCacheView(), DestroyImage(), DestroyString(), DirectClass, _Image::filename, FormatLocaleString(), GetCacheViewVirtualPixels(), GetMagickModule, GetOptimalKernelWidth1D(), GetPixelAlpha(), GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelIntensity(), GetPixelMask(), GRAYColorspace, LogMagickEvent(), MagickAssumeAligned, MagickEpsilon, MagickFalse, MagickPI, MagickSigma, MagickSignature, MagickTrue, MaxTextExtent, PerceptibleReciprocal(), _Image::progress_monitor, QuantumScale, QueueCacheViewAuthenticPixels(), RelinquishAlignedMemory(), ResourceLimitError, _Image::rows, SelectiveBlurImageTag, SetImageProgress(), SetImageStorageClass(), SetPixelChannel(), _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), ThrowImageException, TraceEvent, TransformEvent, TransformImageColorspace(), _Image::type, and UndefinedPixelTrait.
MagickExport Image* ShadeImage (const Image * image, const MagickBooleanType gray, const double azimuth, const double elevation, ExceptionInfo * exception)
Definition at line 2935 of file effect.c.
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), ClampToQuantum(), CloneImage(), _Image::colorspace, _Image::columns, CopyPixelTrait, _Image::debug, DegreesToRadians(), DestroyImage(), DirectClass, _Image::filename, GetCacheViewVirtualPixels(), GetMagickModule, GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelIntensity(), GetPixelMask(), LogMagickEvent(), MagickEpsilon, MagickFalse, MagickSignature, MagickTrue, _Image::progress_monitor, QuantumRange, QuantumScale, QueueCacheViewAuthenticPixels(), RGBColorspace, _Image::rows, SetImageProgress(), SetImageStorageClass(), SetPixelChannel(), ShadeImageTag, _ExceptionInfo::signature, _Image::signature, sRGBColorspace, SyncCacheViewAuthenticPixels(), TraceEvent, TransformImageColorspace(), UndefinedPixelTrait, _PrimaryInfo::x, _PrimaryInfo::y, and _PrimaryInfo::z.
Referenced by PreviewImage().
MagickExport Image* SharpenImage (const Image * image, const double radius, const double sigma, ExceptionInfo * exception)
Definition at line 3179 of file effect.c.
References AcquireAlignedMemory(), AcquireKernelInfo(), ConvolveImage(), _Image::debug, DestroyKernelInfo(), _Image::filename, GetMagickModule, GetOptimalKernelWidth2D(), _KernelInfo::height, LogMagickEvent(), MagickAssumeAligned, MagickFalse, MagickPI, MagickSigma, MagickSignature, ResetMagickMemory(), ResourceLimitError, _ExceptionInfo::signature, _KernelInfo::signature, _Image::signature, ThrowImageException, TraceEvent, _KernelInfo::values, _KernelInfo::width, _KernelInfo::x, and _KernelInfo::y.
Referenced by PreviewImage().
MagickExport Image* SpreadImage (const Image * image, const double radius, const PixelInterpolateMethod method, ExceptionInfo * exception)
Definition at line 3275 of file effect.c.
References AcquireAuthenticCacheView(), AcquireRandomInfoThreadSet(), AcquireVirtualCacheView(), CloneImage(), _Image::columns, _Image::debug, DestroyCacheView(), DestroyImage(), DestroyRandomInfoThreadSet(), DirectClass, _Image::filename, GetCacheViewVirtualPixels(), GetMagickModule, GetOpenMPThreadId(), GetOptimalKernelWidth1D(), GetPixelChannels(), GetPseudoRandomValue(), GetRandomSecretKey(), InterpolatePixelChannels(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, _Image::progress_monitor, QueueCacheViewAuthenticPixels(), random_info, _Image::rows, SetImageProgress(), SetImageStorageClass(), _ExceptionInfo::signature, _Image::signature, SpreadImageTag, SyncCacheViewAuthenticPixels(), TraceEvent, _PointInfo::x, and _PointInfo::y.
Referenced by PreviewImage().
MagickExport Image* UnsharpMaskImage (const Image * image, const double radius, const double sigma, const double amount, const double threshold, ExceptionInfo * exception)
Definition at line 3436 of file effect.c.
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), BlurImage(), ClampToQuantum(), _Image::columns, CopyPixelTrait, _Image::debug, DestroyCacheView(), DestroyImage(), _Image::filename, GetCacheViewVirtualPixels(), GetMagickModule, GetPixelChannel(), GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelMask(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, _Image::progress_monitor, QuantumRange, QueueCacheViewAuthenticPixels(), _Image::rows, SetImageProgress(), SetPixelChannel(), SharpenImageTag, _Image::signature, SyncCacheViewAuthenticPixels(), TraceEvent, _Image::type, and UndefinedPixelTrait.