MagickCore: enhance.h File Reference
enhance.h File Reference
#include "MagickCore/pixel.h"
Functions
MagickExport MagickBooleanType AutoGammaImage (Image *, ExceptionInfo *)
MagickExport MagickBooleanType AutoLevelImage (Image *, ExceptionInfo *)
MagickExport MagickBooleanType BrightnessContrastImage (Image *, const double, const double, ExceptionInfo *)
MagickExport MagickBooleanType ClutImage (Image *, const Image *, const PixelInterpolateMethod, ExceptionInfo *)
MagickExport MagickBooleanType ColorDecisionListImage (Image *, const char *, ExceptionInfo *)
MagickExport MagickBooleanType ContrastImage (Image *, const MagickBooleanType, ExceptionInfo *)
MagickExport MagickBooleanType ContrastStretchImage (Image *, const double, const double, ExceptionInfo *)
MagickExport MagickBooleanType EqualizeImage (Image *image, ExceptionInfo *)
MagickExport MagickBooleanType GammaImage (Image *, const double, ExceptionInfo *)
MagickExport MagickBooleanType GrayscaleImage (Image *, const PixelIntensityMethod, ExceptionInfo *)
MagickExport MagickBooleanType HaldClutImage (Image *, const Image *, ExceptionInfo *)
MagickExport MagickBooleanType LevelImage (Image *, const double, const double, const double, ExceptionInfo *)
MagickExport MagickBooleanType LevelizeImage (Image *, const double, const double, const double, ExceptionInfo *)
MagickExport MagickBooleanType LevelImageColors (Image *, const PixelInfo *, const PixelInfo *, const MagickBooleanType, ExceptionInfo *)
MagickExport MagickBooleanType LinearStretchImage (Image *, const double, const double, ExceptionInfo *)
MagickExport MagickBooleanType ModulateImage (Image *, const char *, ExceptionInfo *)
MagickExport MagickBooleanType NegateImage (Image *, const MagickBooleanType, ExceptionInfo *)
MagickExport MagickBooleanType NormalizeImage (Image *, ExceptionInfo *)
MagickExport MagickBooleanType SigmoidalContrastImage (Image *, const MagickBooleanType, const double, const double, ExceptionInfo *)
MagickExport Image * EnhanceImage (const Image *, ExceptionInfo *)
Function Documentation
MagickExport MagickBooleanType AutoGammaImage (Image * , ExceptionInfo *)
MagickExport MagickBooleanType AutoLevelImage (Image * , ExceptionInfo *)
MagickExport MagickBooleanType BrightnessContrastImage (Image * , const double , const double , ExceptionInfo *)
MagickExport MagickBooleanType ClutImage (Image * , const Image * , const PixelInterpolateMethod , ExceptionInfo *)
MagickExport MagickBooleanType ColorDecisionListImage (Image * , const char * , ExceptionInfo *)
MagickExport MagickBooleanType ContrastImage (Image * , const MagickBooleanType , ExceptionInfo *)
MagickExport MagickBooleanType ContrastStretchImage (Image * , const double , const double , ExceptionInfo *)
MagickExport Image* EnhanceImage (const Image * , ExceptionInfo *)
Definition at line 1288 of file enhance.c.
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), ClampToQuantum(), CloneImage(), _Image::columns, CopyPixelTrait, _Image::debug, DestroyCacheView(), DestroyImage(), DirectClass, EnhanceImageTag, EnhancePixel, _Image::filename, GetCacheViewVirtualPixels(), GetMagickModule, GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelReadMask(), IfMagickFalse, IfMagickTrue, LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, _Image::progress_monitor, QueueCacheViewAuthenticPixels(), _Image::rows, SetImageProgress(), SetImageStorageClass(), SetPixelChannel(), _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), TraceEvent, and UndefinedPixelTrait.
MagickExport MagickBooleanType EqualizeImage (Image * image, ExceptionInfo *)
MagickExport MagickBooleanType GammaImage (Image * , const double , ExceptionInfo *)
MagickExport MagickBooleanType GrayscaleImage (Image * , const PixelIntensityMethod , ExceptionInfo *)
MagickExport MagickBooleanType HaldClutImage (Image * , const Image * , ExceptionInfo *)
MagickExport MagickBooleanType LevelImage (Image * , const double , const double , const double , ExceptionInfo *)
MagickExport MagickBooleanType LevelImageColors (Image * , const PixelInfo * , const PixelInfo * , const MagickBooleanType , ExceptionInfo *)
MagickExport MagickBooleanType LevelizeImage (Image * , const double , const double , const double , ExceptionInfo *)
MagickExport MagickBooleanType LinearStretchImage (Image * , const double , const double , ExceptionInfo *)
MagickExport MagickBooleanType ModulateImage (Image * , const char * , ExceptionInfo *)
MagickExport MagickBooleanType NegateImage (Image * , const MagickBooleanType , ExceptionInfo *)
MagickExport MagickBooleanType NormalizeImage (Image * , ExceptionInfo *)
MagickExport MagickBooleanType SigmoidalContrastImage (Image * , const MagickBooleanType , const double , const double , ExceptionInfo *)
Definition at line 3744 of file enhance.c.
References AcquireAuthenticCacheView(), _PixelInfo::alpha, _PixelInfo::blue, _Image::colormap, _Image::colors, _Image::columns, _Image::debug, DestroyCacheView(), _Image::filename, GetCacheViewAuthenticPixels(), GetMagickModule, GetPixelAlphaTraits(), GetPixelBlueTraits(), GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelGreenTraits(), GetPixelReadMask(), GetPixelRedTraits(), _PixelInfo::green, IfMagickFalse, IfMagickTrue, InverseScaledSig, LogMagickEvent(), MagickEpsilon, MagickFalse, MagickSignature, MagickTrue, _Image::progress_monitor, PseudoClass, _PixelInfo::red, _Image::rows, ScaledSig, SetImageProgress(), SigmoidalContrastImageTag, _Image::signature, _Image::storage_class, SyncCacheViewAuthenticPixels(), TraceEvent, and UpdatePixelTrait.