MagickCore: exception.h File Reference
exception.h File Reference
#include <stdarg.h>
#include "MagickCore/semaphore.h"
Data Structures
struct _ExceptionInfo
Typedefs
typedef void(* ErrorHandler)(const ExceptionType, const char *, const char *)
typedef void(* FatalErrorHandler)(const ExceptionType, const char *, const char *)
typedef void(* WarningHandler)(const ExceptionType, const char *, const char *)
Enumerations
enum ExceptionType {
UndefinedException, WarningException = 300, ResourceLimitWarning = 300, TypeWarning = 305,
OptionWarning = 310, DelegateWarning = 315, MissingDelegateWarning = 320, CorruptImageWarning = 325,
FileOpenWarning = 330, BlobWarning = 335, StreamWarning = 340, CacheWarning = 345,
CoderWarning = 350, FilterWarning = 352, ModuleWarning = 355, DrawWarning = 360,
ImageWarning = 365, WandWarning = 370, RandomWarning = 375, XServerWarning = 380,
MonitorWarning = 385, RegistryWarning = 390, ConfigureWarning = 395, PolicyWarning = 399,
ErrorException = 400, ResourceLimitError = 400, TypeError = 405, OptionError = 410,
DelegateError = 415, MissingDelegateError = 420, CorruptImageError = 425, FileOpenError = 430,
BlobError = 435, StreamError = 440, CacheError = 445, CoderError = 450,
FilterError = 452, ModuleError = 455, DrawError = 460, ImageError = 465,
WandError = 470, RandomError = 475, XServerError = 480, MonitorError = 485,
RegistryError = 490, ConfigureError = 495, PolicyError = 499, FatalErrorException = 700,
ResourceLimitFatalError = 700, TypeFatalError = 705, OptionFatalError = 710, DelegateFatalError = 715,
MissingDelegateFatalError = 720, CorruptImageFatalError = 725, FileOpenFatalError = 730, BlobFatalError = 735,
StreamFatalError = 740, CacheFatalError = 745, CoderFatalError = 750, FilterFatalError = 752,
ModuleFatalError = 755, DrawFatalError = 760, ImageFatalError = 765, WandFatalError = 770,
RandomFatalError = 775, XServerFatalError = 780, MonitorFatalError = 785, RegistryFatalError = 790,
ConfigureFatalError = 795, PolicyFatalError = 799
}
Functions
MagickExport char * GetExceptionMessage (const int)
MagickExport const char * GetLocaleExceptionMessage (const ExceptionType, const char *)
MagickExport ErrorHandler SetErrorHandler (ErrorHandler)
MagickExport ExceptionInfo * AcquireExceptionInfo (void)
MagickExport ExceptionInfo * CloneExceptionInfo (ExceptionInfo *)
MagickExport ExceptionInfo * DestroyExceptionInfo (ExceptionInfo *)
MagickExport FatalErrorHandler SetFatalErrorHandler (FatalErrorHandler)
MagickExport MagickBooleanType ThrowException (ExceptionInfo *, const ExceptionType, const char *, const char *)
MagickExport MagickBooleanType ThrowMagickExceptionList (ExceptionInfo *, const char *, const char *, const size_t, const ExceptionType, const char *, const char *, va_list)
MagickExport MagickBooleanType ThrowMagickException (ExceptionInfo *, const char *, const char *, const size_t, const ExceptionType, const char *, const char *,...) magick_attribute((__format__(__printf__
MagickExport MagickBooleanType
MagickExport void CatchException (ExceptionInfo *)
MagickExport MagickBooleanType
MagickExport void ClearMagickException (ExceptionInfo *)
MagickExport MagickBooleanType
MagickExport void GetExceptionInfo (ExceptionInfo *)
MagickExport MagickBooleanType
MagickExport void InheritException (ExceptionInfo *, const ExceptionInfo *)
MagickExport MagickBooleanType
MagickExport void MagickError (const ExceptionType, const char *, const char *)
MagickExport MagickBooleanType
MagickExport void MagickFatalError (const ExceptionType, const char *, const char *)
MagickExport MagickBooleanType
MagickExport void MagickWarning (const ExceptionType, const char *, const char *)
MagickExport WarningHandler SetWarningHandler (WarningHandler)
Typedef Documentation
typedef void(* ErrorHandler)(const ExceptionType, const char *, const char *)
Definition at line 128 of file exception.h.
typedef void(* FatalErrorHandler)(const ExceptionType, const char *, const char *)
Definition at line 131 of file exception.h.
typedef void(* WarningHandler)(const ExceptionType, const char *, const char *)
Definition at line 134 of file exception.h.
Enumeration Type Documentation
enum ExceptionType
Enumerator
UndefinedException
WarningException
ResourceLimitWarning
TypeWarning
OptionWarning
DelegateWarning
MissingDelegateWarning
CorruptImageWarning
FileOpenWarning
BlobWarning
StreamWarning
CacheWarning
CoderWarning
FilterWarning
ModuleWarning
DrawWarning
ImageWarning
WandWarning
RandomWarning
XServerWarning
MonitorWarning
RegistryWarning
ConfigureWarning
PolicyWarning
ErrorException
ResourceLimitError
TypeError
OptionError
DelegateError
MissingDelegateError
CorruptImageError
FileOpenError
BlobError
StreamError
CacheError
CoderError
FilterError
ModuleError
DrawError
ImageError
WandError
RandomError
XServerError
MonitorError
RegistryError
ConfigureError
PolicyError
FatalErrorException
ResourceLimitFatalError
TypeFatalError
OptionFatalError
DelegateFatalError
MissingDelegateFatalError
CorruptImageFatalError
FileOpenFatalError
BlobFatalError
StreamFatalError
CacheFatalError
CoderFatalError
FilterFatalError
ModuleFatalError
DrawFatalError
ImageFatalError
WandFatalError
RandomFatalError
XServerFatalError
MonitorFatalError
RegistryFatalError
ConfigureFatalError
PolicyFatalError
Definition at line 28 of file exception.h.
Function Documentation
MagickExport ExceptionInfo* AcquireExceptionInfo (void)
MagickExport MagickBooleanType MagickExport void CatchException (ExceptionInfo *)
MagickExport MagickBooleanType MagickExport void ClearMagickException (ExceptionInfo *)
MagickExport ExceptionInfo * CloneExceptionInfo (ExceptionInfo *)
MagickExport ExceptionInfo * DestroyExceptionInfo (ExceptionInfo *)
Definition at line 409 of file exception.c.
References AcquireSemaphoreInfo(), DestroyExceptionElement(), DestroyLinkedList(), DestroySemaphoreInfo(), _ExceptionInfo::exceptions, LockSemaphoreInfo(), MagickFalse, MagickSignature, _ExceptionInfo::relinquish, RelinquishMagickMemory(), _ExceptionInfo::semaphore, _ExceptionInfo::severity, _ExceptionInfo::signature, UndefinedException, and UnlockSemaphoreInfo().
Referenced by CatchImageException(), CloneDrawInfo(), CloseMagickLog(), DestroyFxInfo(), DestroyImageView(), DistributePixelCacheClient(), ExpandFilenames(), FormatImageProperty(), GetConfigureOption(), GetDrawInfo(), GetImageInfo(), GetImageMagick(), GetLocaleMessage(), GetMagickHomeURL(), GetPathTemplate(), GetPolicyValue(), GetXMPProperty(), GlobExpression(), IsEventLogging(), IsRightsAuthorized(), LoadTypeList(), LogMagickEventList(), MagickToMime(), OpenBlob(), OptimizeLayerFrames(), PingImages(), ReadImage(), ReadImages(), SetImageInfo(), SetLogEventMask(), SetLogFormat(), ShredFile(), TranslateEvent(), WriteImage(), and WriteImages().
MagickExport MagickBooleanType MagickExport void GetExceptionInfo (ExceptionInfo *)
MagickExport char* GetExceptionMessage (const int)
Definition at line 488 of file exception.c.
References ConstantString(), CopyMagickString(), and MaxTextExtent.
Referenced by InitializeMagickList().
MagickExport const char* GetLocaleExceptionMessage (const ExceptionType , const char *)
Definition at line 606 of file exception.c.
References ExceptionSeverityToTag(), FormatLocaleString(), GetLocaleMessage(), and MaxTextExtent.
Referenced by GetImageViewException(), and ThrowMagickExceptionList().
MagickExport MagickBooleanType MagickExport void InheritException (ExceptionInfo * , const ExceptionInfo *)
MagickExport MagickBooleanType MagickExport void MagickError (const ExceptionType , const char * , const char *)
MagickExport MagickBooleanType MagickExport void MagickFatalError (const ExceptionType , const char * , const char *)
MagickExport MagickBooleanType MagickExport void MagickWarning (const ExceptionType , const char * , const char *)
Definition at line 773 of file exception.c.
References warning_handler.
Referenced by CatchException().
MagickExport ErrorHandler SetErrorHandler (ErrorHandler)
Definition at line 803 of file exception.c.
References error_handler.
MagickExport FatalErrorHandler SetFatalErrorHandler (FatalErrorHandler)
Definition at line 836 of file exception.c.
References fatal_error_handler.
Referenced by LoadLocaleList().
MagickExport WarningHandler SetWarningHandler (WarningHandler)
Definition at line 869 of file exception.c.
References warning_handler.
Referenced by IdentifyImage().
MagickExport MagickBooleanType ThrowException (ExceptionInfo * , const ExceptionType , const char * , const char *)
MagickExport MagickBooleanType ThrowMagickException (ExceptionInfo * , const char * , const char * , const size_t , const ExceptionType , const char * , const char * , ...)
MagickExport MagickBooleanType ThrowMagickExceptionList (ExceptionInfo * , const char * , const char * , const size_t , const ExceptionType , const char * , const char * , va_list)