MagickCore: exception.c File Reference
exception.c File Reference
#include "MagickCore/studio.h"
#include "MagickCore/client.h"
#include "MagickCore/exception.h"
#include "MagickCore/exception-private.h"
#include "MagickCore/hashmap.h"
#include "MagickCore/locale_.h"
#include "MagickCore/log.h"
#include "MagickCore/magick.h"
#include "MagickCore/memory_.h"
#include "MagickCore/string_.h"
#include "MagickCore/utility.h"
#include "MagickCore/utility-private.h"
Functions
static void DefaultErrorHandler (const ExceptionType, const char *, const char *)
static void DefaultFatalErrorHandler (const ExceptionType, const char *, const char *)
static void DefaultWarningHandler (const ExceptionType, const char *, const char *)
MagickExport ExceptionInfo * AcquireExceptionInfo (void)
static void * DestroyExceptionElement (void *exception)
MagickExport void ClearMagickException (ExceptionInfo *exception)
MagickExport void CatchException (ExceptionInfo *exception)
MagickExport ExceptionInfo * CloneExceptionInfo (ExceptionInfo *exception)
static void DefaultErrorHandler (const ExceptionType magick_unused(severity), const char *reason, const char *description)
static void DefaultWarningHandler (const ExceptionType magick_unused(severity), const char *reason, const char *description)
MagickExport ExceptionInfo * DestroyExceptionInfo (ExceptionInfo *exception)
MagickExport void GetExceptionInfo (ExceptionInfo *exception)
MagickExport char * GetExceptionMessage (const int error)
static const char * ExceptionSeverityToTag (const ExceptionType severity)
MagickExport const char * GetLocaleExceptionMessage (const ExceptionType severity, const char *tag)
MagickExport void InheritException (ExceptionInfo *exception, const ExceptionInfo *relative)
MagickExport void MagickError (const ExceptionType error, const char *reason, const char *description)
MagickExport void MagickFatalError (const ExceptionType error, const char *reason, const char *description)
MagickExport void MagickWarning (const ExceptionType warning, const char *reason, const char *description)
MagickExport ErrorHandler SetErrorHandler (ErrorHandler handler)
MagickExport FatalErrorHandler SetFatalErrorHandler (FatalErrorHandler handler)
MagickExport WarningHandler SetWarningHandler (WarningHandler handler)
MagickExport MagickBooleanType ThrowException (ExceptionInfo *exception, const ExceptionType severity, const char *reason, const char *description)
MagickExport MagickBooleanType ThrowMagickExceptionList (ExceptionInfo *exception, const char *module, const char *function, const size_t line, const ExceptionType severity, const char *tag, const char *format, va_list operands)
MagickExport MagickBooleanType ThrowMagickException (ExceptionInfo *exception, const char *module, const char *function, const size_t line, const ExceptionType severity, const char *tag, const char *format,...)
Variables
static ErrorHandler error_handler = DefaultErrorHandler
static FatalErrorHandler fatal_error_handler = DefaultFatalErrorHandler
static WarningHandler warning_handler = DefaultWarningHandler
Function Documentation
MagickExport ExceptionInfo* AcquireExceptionInfo (void)
Definition at line 102 of file exception.c.
References AcquireMagickMemory(), GetExceptionInfo(), MagickTrue, _ExceptionInfo::relinquish, ResourceLimitFatalError, and ThrowFatalException.
Referenced by AcquireFxInfo(), CatchImageException(), CloneDrawInfo(), CloneImageView(), CloseMagickLog(), DistributePixelCacheClient(), ExpandFilenames(), FormatImageProperty(), GetConfigureOption(), GetDrawInfo(), GetImageInfo(), GetImageMagick(), GetLocaleMessage(), GetMagickHomeURL(), GetPathTemplate(), GetPolicyValue(), GetXMPProperty(), GlobExpression(), IsEventLogging(), IsRightsAuthorized(), LoadTypeList(), LogMagickEventList(), MagickToMime(), NewImageView(), NewImageViewRegion(), OpenBlob(), OptimizeLayerFrames(), PingImages(), ReadImage(), ReadImages(), SetImageInfo(), SetLogEventMask(), SetLogFormat(), ShredFile(), TranslateEvent(), WriteImage(), and WriteImages().
MagickExport void CatchException (ExceptionInfo * exception)
Definition at line 201 of file exception.c.
References ClearMagickException(), _ExceptionInfo::description, ErrorException, _ExceptionInfo::exceptions, FatalErrorException, GetNextValueInLinkedList(), LockSemaphoreInfo(), MagickError(), MagickFatalError(), MagickSignature, MagickWarning(), _ExceptionInfo::reason, ResetLinkedListIterator(), _ExceptionInfo::semaphore, _ExceptionInfo::severity, _ExceptionInfo::signature, UnlockSemaphoreInfo(), and WarningException.
Referenced by CatchImageException(), DrawImage(), and RenderPostscript().
MagickExport void ClearMagickException (ExceptionInfo * exception)
Definition at line 153 of file exception.c.
References _ExceptionInfo::description, DestroyExceptionElement(), _ExceptionInfo::exceptions, LockSemaphoreInfo(), MagickSignature, _ExceptionInfo::reason, RemoveLastElementFromLinkedList(), _ExceptionInfo::semaphore, _ExceptionInfo::severity, _ExceptionInfo::signature, UndefinedException, and UnlockSemaphoreInfo().
Referenced by CatchException(), CropImageToTiles(), FxEvaluateSubexpression(), ListMagickInfo(), and LoadMimeLists().
MagickExport ExceptionInfo* CloneExceptionInfo (ExceptionInfo * exception)
Definition at line 251 of file exception.c.
References AcquireMagickMemory(), GetExceptionInfo(), InheritException(), MagickTrue, _ExceptionInfo::relinquish, ResourceLimitFatalError, and ThrowFatalException.
static void DefaultErrorHandler (const ExceptionType , const char * , const char *) static
static void DefaultErrorHandler (const ExceptionType magick_unusedseverity, const char * reason, const char * description) static
Definition at line 293 of file exception.c.
References FormatLocaleFile(), and GetClientName().
static void DefaultFatalErrorHandler (const ExceptionType severity, const char * reason, const char * description)
Definition at line 333 of file exception.c.
References FatalErrorException, FormatLocaleFile(), GetClientName(), and MagickCoreTerminus().
static void DefaultWarningHandler (const ExceptionType , const char * , const char *)
static void DefaultWarningHandler (const ExceptionType magick_unusedseverity, const char * reason, const char * description) static
Definition at line 375 of file exception.c.
References FormatLocaleFile(), and GetClientName().
static void* DestroyExceptionElement (void * exception) static
Definition at line 139 of file exception.c.
References _ExceptionInfo::description, DestroyString(), _ExceptionInfo::reason, and RelinquishMagickMemory().
Referenced by ClearMagickException(), and DestroyExceptionInfo().
MagickExport ExceptionInfo* DestroyExceptionInfo (ExceptionInfo * exception)
Definition at line 409 of file exception.c.
References AcquireSemaphoreInfo(), DestroyExceptionElement(), DestroyLinkedList(), DestroySemaphoreInfo(), _ExceptionInfo::exceptions, LockSemaphoreInfo(), MagickFalse, MagickSignature, _ExceptionInfo::relinquish, RelinquishMagickMemory(), _ExceptionInfo::semaphore, _ExceptionInfo::severity, _ExceptionInfo::signature, UndefinedException, and UnlockSemaphoreInfo().
Referenced by CatchImageException(), CloneDrawInfo(), CloseMagickLog(), DestroyFxInfo(), DestroyImageView(), DistributePixelCacheClient(), ExpandFilenames(), FormatImageProperty(), GetConfigureOption(), GetDrawInfo(), GetImageInfo(), GetImageMagick(), GetLocaleMessage(), GetMagickHomeURL(), GetPathTemplate(), GetPolicyValue(), GetXMPProperty(), GlobExpression(), IsEventLogging(), IsRightsAuthorized(), LoadTypeList(), LogMagickEventList(), MagickToMime(), OpenBlob(), OptimizeLayerFrames(), PingImages(), ReadImage(), ReadImages(), SetImageInfo(), SetLogEventMask(), SetLogFormat(), ShredFile(), TranslateEvent(), WriteImage(), and WriteImages().
static const char* ExceptionSeverityToTag (const ExceptionType severity) static
Definition at line 534 of file exception.c.
References BlobError, BlobFatalError, BlobWarning, CacheError, CacheFatalError, CacheWarning, CoderError, CoderFatalError, CoderWarning, ConfigureError, ConfigureFatalError, ConfigureWarning, CorruptImageError, CorruptImageFatalError, CorruptImageWarning, DelegateError, DelegateFatalError, DelegateWarning, DrawError, DrawFatalError, DrawWarning, FileOpenError, FileOpenFatalError, FileOpenWarning, FilterError, FilterFatalError, FilterWarning, ImageError, ImageFatalError, ImageWarning, MissingDelegateError, MissingDelegateFatalError, MissingDelegateWarning, ModuleError, ModuleFatalError, ModuleWarning, MonitorError, MonitorFatalError, MonitorWarning, OptionError, OptionFatalError, OptionWarning, PolicyError, PolicyFatalError, PolicyWarning, RegistryError, RegistryFatalError, RegistryWarning, ResourceLimitError, ResourceLimitFatalError, ResourceLimitWarning, StreamError, StreamFatalError, StreamWarning, TypeError, TypeFatalError, TypeWarning, WandError, WandFatalError, WandWarning, XServerError, XServerFatalError, and XServerWarning.
Referenced by GetLocaleExceptionMessage().
MagickExport void GetExceptionInfo (ExceptionInfo * exception)
Definition at line 455 of file exception.c.
References AllocateSemaphoreInfo(), _ExceptionInfo::exceptions, MagickSignature, NewLinkedList(), ResetMagickMemory(), _ExceptionInfo::semaphore, _ExceptionInfo::severity, _ExceptionInfo::signature, and UndefinedException.
Referenced by AcquireExceptionInfo(), and CloneExceptionInfo().
MagickExport char* GetExceptionMessage (const int error)
Definition at line 488 of file exception.c.
References ConstantString(), CopyMagickString(), and MaxTextExtent.
Referenced by InitializeMagickList().
MagickExport const char* GetLocaleExceptionMessage (const ExceptionType severity, const char * tag)
Definition at line 606 of file exception.c.
References ExceptionSeverityToTag(), FormatLocaleString(), GetLocaleMessage(), and MaxTextExtent.
Referenced by GetImageViewException(), and ThrowMagickExceptionList().
MagickExport void InheritException (ExceptionInfo * exception, const ExceptionInfo * relative)
Definition at line 650 of file exception.c.
References _ExceptionInfo::description, _ExceptionInfo::exceptions, GetNextValueInLinkedList(), LockSemaphoreInfo(), MagickSignature, _ExceptionInfo::reason, ResetLinkedListIterator(), _ExceptionInfo::semaphore, _ExceptionInfo::severity, _ExceptionInfo::signature, ThrowException(), and UnlockSemaphoreInfo().
Referenced by CloneExceptionInfo(), and CloneImageView().
MagickExport void MagickError (const ExceptionType error, const char * reason, const char * description)
Definition at line 703 of file exception.c.
References error_handler.
Referenced by CatchException().
MagickExport void MagickFatalError (const ExceptionType error, const char * reason, const char * description)
Definition at line 739 of file exception.c.
References fatal_error_handler.
Referenced by CatchException().
MagickExport void MagickWarning (const ExceptionType warning, const char * reason, const char * description)
Definition at line 773 of file exception.c.
References warning_handler.
Referenced by CatchException().
MagickExport ErrorHandler SetErrorHandler (ErrorHandler handler)
Definition at line 803 of file exception.c.
References error_handler.
MagickExport FatalErrorHandler SetFatalErrorHandler (FatalErrorHandler handler)
Definition at line 836 of file exception.c.
References fatal_error_handler.
Referenced by LoadLocaleList().
MagickExport WarningHandler SetWarningHandler (WarningHandler handler)
Definition at line 869 of file exception.c.
References warning_handler.
Referenced by IdentifyImage().
MagickExport MagickBooleanType ThrowException (ExceptionInfo * exception, const ExceptionType severity, const char * reason, const char * description)
Definition at line 910 of file exception.c.
References AcquireMagickMemory(), AppendValueToLinkedList(), ConstantString(), _ExceptionInfo::description, _ExceptionInfo::exceptions, GetLastValueInLinkedList(), LocaleCompare(), LockSemaphoreInfo(), MagickSignature, MagickTrue, _ExceptionInfo::reason, ResetMagickMemory(), ResourceLimitFatalError, _ExceptionInfo::semaphore, _ExceptionInfo::severity, _ExceptionInfo::signature, ThrowFatalException, and UnlockSemaphoreInfo().
Referenced by InheritException(), and ThrowMagickExceptionList().
MagickExport MagickBooleanType ThrowMagickException (ExceptionInfo * exception, const char * module, const char * function, const size_t line, const ExceptionType severity, const char * tag, const char * format, ...)
Definition at line 1042 of file exception.c.
References ThrowMagickExceptionList().
Referenced by AccelerateConvolveImage(), AcquireCacheNexusPixels(), AcquireFxThreadSet(), AcquireRadonInfo(), AcquireStreamPixels(), AnimateImages(), BlobToImage(), ChannelFxImage(), ClassifyImageColors(), CompositeImage(), ConnectPixelCacheServer(), ConstrainColormapIndex(), CropImage(), DeleteImages(), DisplayImages(), DistortImage(), DrawImage(), EvaluateImages(), ExportBlackQuantum(), ExportCMYKAQuantum(), ExportCMYKQuantum(), ExportImagePixels(), ExportIndexAlphaQuantum(), ExportIndexQuantum(), FileToBlob(), ForwardFourierTransformImage(), FxEvaluateSubexpression(), FxGetSymbol(), FxSubexpression(), GenerateCoefficients(), GetColorCompliance(), GetConfigureOptions(), GetDelegateCommand(), GetImageBoundingBox(), GetImageDistortions(), GetImageDynamicThreshold(), GetImageFeatures(), GetImageHistogram(), GetImageRegistry(), GetImageTotalInkDensity(), GetThresholdMapFile(), GetTypeInfoByFamily(), GetVirtualPixelsFromNexus(), GetVirtualPixelStream(), HorizontalFilter(), ImageListToArray(), ImagesToBlob(), ImageToBlob(), ImageToFile(), ImportBlackQuantum(), ImportCMYKAQuantum(), ImportCMYKQuantum(), ImportImagePixels(), ImportIndexAlphaQuantum(), ImportIndexQuantum(), InterpretImageProperties(), InverseFourierTransformImage(), InvokeDelegate(), InvokeDynamicImageFilter(), IsHistogramImage(), IsPaletteImage(), LiquidRescaleImage(), ListThresholdMapFile(), LoadCoderList(), LoadCoderLists(), LoadColorList(), LoadColorLists(), LoadConfigureList(), LoadConfigureLists(), LoadDelegateList(), LoadLocaleList(), LoadLogList(), LoadLogLists(), LoadMagicList(), LoadMagicLists(), LoadMimeList(), LoadPolicyList(), LoadPolicyLists(), LoadTypeList(), MorphologyImage(), NewXMLTree(), OpenBlob(), OpenPixelCache(), OrderedPosterizeImage(), ParseAffineGeometry(), ParseCloseTag(), ParseGravityGeometry(), ParseInternalDoctype(), ParsePageGeometry(), ParseRegionGeometry(), PingBlob(), PolynomialImage(), ProfileImage(), QuantizeImages(), QueryColorCompliance(), QueueAuthenticPixelCacheNexus(), QueueAuthenticPixelsStream(), ReadImage(), RemoteDisplayCommand(), RemoveZeroDelayLayers(), RenderFreetype(), RenderType(), SetImageProperty(), SetImageRegistry(), SetResampleFilter(), StreamImagePixels(), SyncAuthenticPixelsStream(), SyncImage(), SystemCommand(), VerticalFilter(), WriteImage(), XRenderImage(), and ZLIBEncodeImage().
MagickExport MagickBooleanType ThrowMagickExceptionList (ExceptionInfo * exception, const char * module, const char * function, const size_t line, const ExceptionType severity, const char * tag, const char * format, va_list operands)
Definition at line 991 of file exception.c.
References ConcatenateMagickString(), CopyMagickString(), ErrorException, ExceptionEvent, FatalErrorException, FormatLocaleString(), GetLocaleExceptionMessage(), GetPathComponent(), LogMagickEvent(), MagickSignature, MaxTextExtent, _ExceptionInfo::signature, TailPath, ThrowException(), and WarningException.
Referenced by ThrowMagickException().
Variable Documentation
ErrorHandler error_handler = DefaultErrorHandler static
Definition at line 76 of file exception.c.
Referenced by MagickError(), and SetErrorHandler().
FatalErrorHandler fatal_error_handler = DefaultFatalErrorHandler static
Definition at line 79 of file exception.c.
Referenced by MagickFatalError(), and SetFatalErrorHandler().
WarningHandler warning_handler = DefaultWarningHandler static
Definition at line 82 of file exception.c.
Referenced by MagickWarning(), and SetWarningHandler().