MagickCore: fx-private.h File Reference
fx-private.h File Reference
Typedefs
typedef struct _FxInfo FxInfo
Functions
MagickPrivate FxInfo * AcquireFxInfo (const Image *, const char *, ExceptionInfo *)
MagickPrivate FxInfo * DestroyFxInfo (FxInfo *)
MagickPrivate MagickBooleanType FxEvaluateExpression (FxInfo *, double *, ExceptionInfo *)
MagickPrivate MagickBooleanType FxEvaluateChannelExpression (FxInfo *, const PixelChannel, const ssize_t, const ssize_t, double *, ExceptionInfo *)
Typedef Documentation
typedef struct _FxInfo FxInfo
Definition at line 25 of file fx-private.h.
Function Documentation
MagickPrivate FxInfo* AcquireFxInfo (const Image * , const char * , ExceptionInfo *)
Referenced by AcquireFxThreadSet(), and InterpretImageProperties().
MagickPrivate FxInfo * DestroyFxInfo (FxInfo *)
Definition at line 1058 of file fx.c.
References _FxInfo::colors, DestroyCacheView(), DestroyExceptionInfo(), DestroyRandomInfo(), DestroySplayTree(), DestroyString(), _FxInfo::exception, _FxInfo::expression, GetImageListLength(), _FxInfo::images, _FxInfo::random_info, RelinquishMagickMemory(), _FxInfo::symbols, and _FxInfo::view.
Referenced by DestroyFxThreadSet(), and InterpretImageProperties().
MagickPrivate MagickBooleanType FxEvaluateChannelExpression (FxInfo * , const PixelChannel , const ssize_t , const ssize_t , double * , ExceptionInfo *)
Definition at line 2907 of file fx.c.
References _FxInfo::expression, FxEvaluateSubexpression(), MagickFalse, MagickTrue, OptionError, and _ExceptionInfo::severity.
Referenced by FxEvaluateExpression(), FxImage(), FxPreprocessExpression(), and InterpretImageProperties().
MagickPrivate MagickBooleanType FxEvaluateExpression (FxInfo * , double * , ExceptionInfo *)