MagickCore: fx.c File Reference
fx.c File Reference
#include "MagickCore/studio.h"
#include "MagickCore/annotate.h"
#include "MagickCore/artifact.h"
#include "MagickCore/attribute.h"
#include "MagickCore/cache.h"
#include "MagickCore/cache-view.h"
#include "MagickCore/channel.h"
#include "MagickCore/color.h"
#include "MagickCore/color-private.h"
#include "MagickCore/colorspace-private.h"
#include "MagickCore/composite.h"
#include "MagickCore/decorate.h"
#include "MagickCore/distort.h"
#include "MagickCore/draw.h"
#include "MagickCore/effect.h"
#include "MagickCore/enhance.h"
#include "MagickCore/exception.h"
#include "MagickCore/exception-private.h"
#include "MagickCore/fx.h"
#include "MagickCore/fx-private.h"
#include "MagickCore/gem.h"
#include "MagickCore/gem-private.h"
#include "MagickCore/geometry.h"
#include "MagickCore/layer.h"
#include "MagickCore/list.h"
#include "MagickCore/log.h"
#include "MagickCore/image.h"
#include "MagickCore/image-private.h"
#include "MagickCore/magick.h"
#include "MagickCore/memory_.h"
#include "MagickCore/monitor.h"
#include "MagickCore/monitor-private.h"
#include "MagickCore/option.h"
#include "MagickCore/pixel.h"
#include "MagickCore/pixel-accessor.h"
#include "MagickCore/property.h"
#include "MagickCore/quantum.h"
#include "MagickCore/quantum-private.h"
#include "MagickCore/random_.h"
#include "MagickCore/random-private.h"
#include "MagickCore/resample.h"
#include "MagickCore/resample-private.h"
#include "MagickCore/resize.h"
#include "MagickCore/resource_.h"
#include "MagickCore/splay-tree.h"
#include "MagickCore/statistic.h"
#include "MagickCore/string_.h"
#include "MagickCore/string-private.h"
#include "MagickCore/thread-private.h"
#include "MagickCore/transform.h"
#include "MagickCore/utility.h"
Data Structures
struct _FxInfo
Macros
#define LeftShiftOperator 0xf5
#define RightShiftOperator 0xf6
#define LessThanEqualOperator 0xf7
#define GreaterThanEqualOperator 0xf8
#define EqualOperator 0xf9
#define NotEqualOperator 0xfa
#define LogicalAndOperator 0xfb
#define LogicalOrOperator 0xfc
#define ExponentialNotation 0xfd
#define AddNoiseImageTag "AddNoise/Image"
#define BlueShiftImageTag "BlueShift/Image"
#define ColorizeImageTag "Colorize/Image"
#define Colorize(pixel, blend_percentage, colorize) (((pixel)*(100.0-(blend_percentage))+(colorize)*(blend_percentage))/100.0)
#define ColorMatrixImageTag "ColorMatrix/Image"
#define FxImageTag "Fx/Image"
#define ImplodeImageTag "Implode/Image"
#define MorphImageTag "Morph/Image"
#define SepiaToneImageTag "SepiaTone/Image"
#define ShadowImageTag "Shadow/Image"
#define SolarizeImageTag "Solarize/Image"
#define GetBit(alpha, i) ((((size_t) (alpha) >> (size_t) (i)) & 0x01) != 0)
#define SetBit(alpha, i, set)
#define SteganoImageTag "Stegano/Image"
#define StereoImageTag "Stereo/Image"
#define SwirlImageTag "Swirl/Image"
#define TintImageTag "Tint/Image"
#define WaveImageTag "Wave/Image"
Functions
MagickPrivate FxInfo * AcquireFxInfo (const Image *image, const char *expression, ExceptionInfo *exception)
MagickExport Image * AddNoiseImage (const Image *image, const NoiseType noise_type, const double attenuate, ExceptionInfo *exception)
MagickExport Image * BlueShiftImage (const Image *image, const double factor, ExceptionInfo *exception)
MagickExport Image * CharcoalImage (const Image *image, const double radius, const double sigma, ExceptionInfo *exception)
MagickExport Image * ColorizeImage (const Image *image, const char *blend, const PixelInfo *colorize, ExceptionInfo *exception)
MagickExport Image * ColorMatrixImage (const Image *image, const KernelInfo *color_matrix, ExceptionInfo *exception)
MagickPrivate FxInfo * DestroyFxInfo (FxInfo *fx_info)
static double MagickMax (const double x, const double y)
static double MagickMin (const double x, const double y)
static double FxChannelStatistics (FxInfo *fx_info, Image *image, PixelChannel channel, const char *symbol, ExceptionInfo *exception)
static double FxEvaluateSubexpression (FxInfo *, const PixelChannel, const ssize_t, const ssize_t, const char *, double *, ExceptionInfo *)
static MagickOffsetType FxGCD (MagickOffsetType alpha, MagickOffsetType beta)
static const char * FxSubexpression (const char *expression, ExceptionInfo *exception)
static double FxGetSymbol (FxInfo *fx_info, const PixelChannel channel, const ssize_t x, const ssize_t y, const char *expression, ExceptionInfo *exception)
static const char * FxOperatorPrecedence (const char *expression, ExceptionInfo *exception)
MagickPrivate MagickBooleanType FxEvaluateExpression (FxInfo *fx_info, double *alpha, ExceptionInfo *exception)
MagickExport MagickBooleanType FxPreprocessExpression (FxInfo *fx_info, double *alpha, ExceptionInfo *exception)
MagickPrivate MagickBooleanType FxEvaluateChannelExpression (FxInfo *fx_info, const PixelChannel channel, const ssize_t x, const ssize_t y, double *alpha, ExceptionInfo *exception)
static FxInfo ** DestroyFxThreadSet (FxInfo **fx_info)
static FxInfo ** AcquireFxThreadSet (const Image *image, const char *expression, ExceptionInfo *exception)
MagickExport Image * FxImage (const Image *image, const char *expression, ExceptionInfo *exception)
MagickExport Image * ImplodeImage (const Image *image, const double amount, const PixelInterpolateMethod method, ExceptionInfo *exception)
MagickExport Image * MorphImages (const Image *image, const size_t number_frames, ExceptionInfo *exception)
static Quantum PlasmaPixel (RandomInfo *random_info, const double pixel, const double noise)
static MagickBooleanType PlasmaImageProxy (Image *image, CacheView *image_view, CacheView *u_view, CacheView *v_view, RandomInfo *random_info, const SegmentInfo *segment, size_t attenuate, size_t depth, ExceptionInfo *exception)
MagickExport MagickBooleanType PlasmaImage (Image *image, const SegmentInfo *segment, size_t attenuate, size_t depth, ExceptionInfo *exception)
MagickExport Image * PolaroidImage (const Image *image, const DrawInfo *draw_info, const char *caption, const double angle, const PixelInterpolateMethod method, ExceptionInfo *exception)
MagickExport Image * SepiaToneImage (const Image *image, const double threshold, ExceptionInfo *exception)
MagickExport Image * ShadowImage (const Image *image, const double alpha, const double sigma, const ssize_t x_offset, const ssize_t y_offset, ExceptionInfo *exception)
MagickExport Image * SketchImage (const Image *image, const double radius, const double sigma, const double angle, ExceptionInfo *exception)
MagickExport MagickBooleanType SolarizeImage (Image *image, const double threshold, ExceptionInfo *exception)
MagickExport Image * SteganoImage (const Image *image, const Image *watermark, ExceptionInfo *exception)
MagickExport Image * StereoImage (const Image *left_image, const Image *right_image, ExceptionInfo *exception)
MagickExport Image * StereoAnaglyphImage (const Image *left_image, const Image *right_image, const ssize_t x_offset, const ssize_t y_offset, ExceptionInfo *exception)
MagickExport Image * SwirlImage (const Image *image, double degrees, const PixelInterpolateMethod method, ExceptionInfo *exception)
MagickExport Image * TintImage (const Image *image, const char *blend, const PixelInfo *tint, ExceptionInfo *exception)
MagickExport Image * VignetteImage (const Image *image, const double radius, const double sigma, const ssize_t x, const ssize_t y, ExceptionInfo *exception)
MagickExport Image * WaveImage (const Image *image, const double amplitude, const double wave_length, const PixelInterpolateMethod method, ExceptionInfo *exception)
Macro Definition Documentation
#define AddNoiseImageTag "AddNoise/Image"
Referenced by AddNoiseImage().
#define BlueShiftImageTag "BlueShift/Image"
Referenced by BlueShiftImage().
#define Colorize (pixel, blend_percentage, colorize) (((pixel)*(100.0-(blend_percentage))+(colorize)*(blend_percentage))/100.0)
Referenced by ColorizeImage().
#define ColorizeImageTag "Colorize/Image"
Referenced by ColorizeImage().
#define ColorMatrixImageTag "ColorMatrix/Image"
Referenced by ColorMatrixImage().
#define EqualOperator 0xf9
Definition at line 102 of file fx.c.
Referenced by AcquireFxInfo(), FxEvaluateSubexpression(), and FxOperatorPrecedence().
#define ExponentialNotation 0xfd
Definition at line 106 of file fx.c.
Referenced by AcquireFxInfo(), FxEvaluateSubexpression(), and FxOperatorPrecedence().
#define FxImageTag "Fx/Image"
Referenced by FxImage().
#define GetBit (alpha, i) ((((size_t) (alpha) >> (size_t) (i)) & 0x01) != 0)
Referenced by SteganoImage().
#define GreaterThanEqualOperator 0xf8
Definition at line 101 of file fx.c.
Referenced by AcquireFxInfo(), FxEvaluateSubexpression(), and FxOperatorPrecedence().
#define ImplodeImageTag "Implode/Image"
Referenced by ImplodeImage().
#define LeftShiftOperator 0xf5
Definition at line 98 of file fx.c.
Referenced by AcquireFxInfo(), FxEvaluateSubexpression(), and FxOperatorPrecedence().
#define LessThanEqualOperator 0xf7
Definition at line 100 of file fx.c.
Referenced by AcquireFxInfo(), FxEvaluateSubexpression(), and FxOperatorPrecedence().
#define LogicalAndOperator 0xfb
Definition at line 104 of file fx.c.
Referenced by AcquireFxInfo(), FxEvaluateSubexpression(), and FxOperatorPrecedence().
#define LogicalOrOperator 0xfc
Definition at line 105 of file fx.c.
Referenced by AcquireFxInfo(), FxEvaluateSubexpression(), and FxOperatorPrecedence().
#define MorphImageTag "Morph/Image"
Referenced by MorphImages().
#define NotEqualOperator 0xfa
Definition at line 103 of file fx.c.
Referenced by AcquireFxInfo(), FxEvaluateSubexpression(), and FxOperatorPrecedence().
#define RightShiftOperator 0xf6
Definition at line 99 of file fx.c.
Referenced by AcquireFxInfo(), FxEvaluateSubexpression(), and FxOperatorPrecedence().
#define SepiaToneImageTag "SepiaTone/Image"
Referenced by SepiaToneImage().
#define SetBit (alpha, i, set)
Value:
(Quantum) ((set) != 0 ? (size_t) (alpha) \
  | (one << (size_t) (i)) : (size_t) (alpha) & ~(one << (size_t) (i)))
Referenced by SteganoImage().
#define ShadowImageTag "Shadow/Image"
#define SolarizeImageTag "Solarize/Image"
Referenced by SolarizeImage().
#define SteganoImageTag "Stegano/Image"
Referenced by SteganoImage().
#define StereoImageTag "Stereo/Image"
Referenced by StereoAnaglyphImage().
#define SwirlImageTag "Swirl/Image"
Referenced by SwirlImage().
#define TintImageTag "Tint/Image"
Referenced by TintImage().
#define WaveImageTag "Wave/Image"
Referenced by WaveImage().
Function Documentation
MagickPrivate FxInfo* AcquireFxInfo (const Image * image, const char * expression, ExceptionInfo * exception)
Definition at line 160 of file fx.c.
References AcquireExceptionInfo(), AcquireMagickMemory(), AcquireQuantumMemory(), AcquireRandomInfo(), AcquireVirtualCacheView(), _FxInfo::colors, CompareSplayTreeString(), ConstantString(), EqualOperator, _FxInfo::exception, ExponentialNotation, _FxInfo::expression, _FxInfo::file, GetFirstImageInList(), GetImageListLength(), GreaterThanEqualOperator, _FxInfo::images, LeftShiftOperator, LessThanEqualOperator, LogicalAndOperator, LogicalOrOperator, NewSplayTree(), _Image::next, NotEqualOperator, _FxInfo::random_info, RelinquishMagickMemory(), ResetMagickMemory(), ResourceLimitFatalError, RightShiftOperator, SubstituteString(), _FxInfo::symbols, ThrowFatalException, and _FxInfo::view.
static FxInfo** AcquireFxThreadSet (const Image * image, const char * expression, ExceptionInfo * exception) static
Definition at line 2961 of file fx.c.
References AcquireFxInfo(), AcquireQuantumMemory(), ConstantString(), DestroyFxThreadSet(), DestroyString(), _Image::filename, FileToString(), FxPreprocessExpression(), GetMagickModule, GetMagickResourceLimit(), MagickFalse, ResetMagickMemory(), ResourceLimitError, ThreadResource, and ThrowMagickException().
Referenced by FxImage().
MagickExport Image* AddNoiseImage (const Image * image, const NoiseType noise_type, const double attenuate, ExceptionInfo * exception)
Definition at line 264 of file fx.c.
References AcquireAuthenticCacheView(), AcquireRandomInfoThreadSet(), AcquireVirtualCacheView(), AddNoiseImageTag, ClampToQuantum(), CloneImage(), _Image::columns, CopyPixelTrait, _Image::debug, DestroyCacheView(), DestroyImage(), DestroyRandomInfoThreadSet(), DirectClass, _Image::filename, GenerateDifferentialNoise(), GetCacheViewVirtualPixels(), GetMagickModule, GetOpenMPThreadId(), GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelReadMask(), GetRandomSecretKey(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, _Image::progress_monitor, QueueCacheViewAuthenticPixels(), random_info, _Image::rows, SetImageProgress(), SetImageStorageClass(), SetPixelChannel(), _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), TraceEvent, and UndefinedPixelTrait.
MagickExport Image* BlueShiftImage (const Image * image, const double factor, ExceptionInfo * exception)
Definition at line 429 of file fx.c.
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), _PixelInfo::blue, BlueShiftImageTag, ClampToQuantum(), CloneImage(), _Image::columns, _Image::debug, DestroyCacheView(), DestroyImage(), DirectClass, _Image::filename, GetCacheViewVirtualPixels(), GetMagickModule, GetPixelBlue(), GetPixelChannels(), GetPixelGreen(), GetPixelRed(), _PixelInfo::green, LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, _Image::progress_monitor, QueueCacheViewAuthenticPixels(), _PixelInfo::red, _Image::rows, SetImageProgress(), SetImageStorageClass(), SetPixelBlue(), SetPixelGreen(), SetPixelRed(), _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), and TraceEvent.
MagickExport Image* CharcoalImage (const Image * image, const double radius, const double sigma, ExceptionInfo * exception)
Definition at line 587 of file fx.c.
References BlurImage(), CloneImage(), _Image::debug, DestroyImage(), EdgeImage(), _Image::filename, GetMagickModule, GrayscaleImage(), _Image::intensity, LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, NegateImage(), NormalizeImage(), _ExceptionInfo::signature, _Image::signature, and TraceEvent.
Referenced by PreviewImage().
MagickExport Image* ColorizeImage (const Image * image, const char * blend, const PixelInfo * colorize, ExceptionInfo * exception)
Definition at line 651 of file fx.c.
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), _PixelInfo::alpha, _PixelInfo::alpha_trait, _Image::alpha_trait, _PixelInfo::black, BlendPixelTrait, _PixelInfo::blue, _GeometryInfo::chi, ChiValue, ClampToQuantum(), CloneImage(), CMYKColorspace, Colorize, ColorizeImageTag, _Image::colorspace, _PixelInfo::colorspace, _Image::columns, CopyPixelTrait, _Image::debug, DestroyCacheView(), DestroyImage(), DirectClass, _Image::filename, GetCacheViewVirtualPixels(), GetMagickModule, GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelInfo(), GetPixelInfoChannel(), GetPixelReadMask(), _PixelInfo::green, IsGrayColorspace(), IsPixelInfoGray(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, OpaqueAlpha, ParseGeometry(), _Image::progress_monitor, _GeometryInfo::psi, PsiValue, QueueCacheViewAuthenticPixels(), _PixelInfo::red, _GeometryInfo::rho, _Image::rows, SetImageAlpha(), SetImageColorspace(), SetImageProgress(), SetImageStorageClass(), SetPixelChannel(), _GeometryInfo::sigma, SigmaValue, _ExceptionInfo::signature, _Image::signature, sRGBColorspace, SyncCacheViewAuthenticPixels(), TraceEvent, UndefinedPixelTrait, _GeometryInfo::xi, and XiValue.
MagickExport Image* ColorMatrixImage (const Image * image, const KernelInfo * color_matrix, ExceptionInfo * exception)
Definition at line 852 of file fx.c.
References AcquireAuthenticCacheView(), AcquireString(), AcquireVirtualCacheView(), _PixelInfo::alpha, _Image::alpha_trait, _PixelInfo::black, BlendPixelTrait, _PixelInfo::blue, CloneImage(), CMYKColorspace, ColorMatrixImageTag, _Image::colorspace, _Image::columns, ConcatenateString(), _Image::debug, DestroyCacheView(), DestroyImage(), DestroyString(), DirectClass, _Image::filename, FormatLocaleString(), GetCacheViewAuthenticPixels(), GetCacheViewVirtualPixels(), GetMagickModule, GetPixelAlpha(), GetPixelBlack(), GetPixelBlue(), GetPixelChannels(), GetPixelGreen(), GetPixelInfo(), GetPixelInfoPixel(), GetPixelRed(), _PixelInfo::green, _KernelInfo::height, LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, MaxTextExtent, _Image::progress_monitor, QuantumRange, _PixelInfo::red, _Image::rows, SetImageProgress(), SetImageStorageClass(), SetPixelInfoPixel(), _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), TraceEvent, TransformEvent, _KernelInfo::values, and _KernelInfo::width.
MagickPrivate FxInfo* DestroyFxInfo (FxInfo * fx_info)
Definition at line 1058 of file fx.c.
References _FxInfo::colors, DestroyCacheView(), DestroyExceptionInfo(), DestroyRandomInfo(), DestroySplayTree(), DestroyString(), _FxInfo::exception, _FxInfo::expression, GetImageListLength(), _FxInfo::images, _FxInfo::random_info, RelinquishMagickMemory(), _FxInfo::symbols, and _FxInfo::view.
Referenced by DestroyFxThreadSet(), and InterpretImageProperties().
static FxInfo** DestroyFxThreadSet (FxInfo ** fx_info) static
Definition at line 2948 of file fx.c.
References DestroyFxInfo(), GetMagickResourceLimit(), RelinquishMagickMemory(), and ThreadResource.
Referenced by AcquireFxThreadSet(), and FxImage().
static double FxChannelStatistics (FxInfo * fx_info, Image * image, PixelChannel channel, const char * symbol, ExceptionInfo * exception) static
Definition at line 1125 of file fx.c.
References AddValueToSplayTree(), ConstantString(), DeleteNodeFromSplayTree(), FormatLocaleString(), GetImageDepth(), GetImageKurtosis(), GetImageMean(), GetImageRange(), GetValueFromSplayTree(), LocaleNCompare(), MagickPixelChannelOptions, MagickTrue, MaxTextExtent, ParseCommandOption(), QuantumScale, SetPixelChannelMask(), StringToDouble(), _FxInfo::symbols, and UndefinedChannel.
Referenced by FxGetSymbol().
MagickPrivate MagickBooleanType FxEvaluateChannelExpression (FxInfo * fx_info, const PixelChannel channel, const ssize_t x, const ssize_t y, double * alpha, ExceptionInfo * exception)
Definition at line 2907 of file fx.c.
References _FxInfo::expression, FxEvaluateSubexpression(), MagickFalse, MagickTrue, OptionError, and _ExceptionInfo::severity.
Referenced by FxEvaluateExpression(), FxImage(), FxPreprocessExpression(), and InterpretImageProperties().
MagickPrivate MagickBooleanType FxEvaluateExpression (FxInfo * fx_info, double * alpha, ExceptionInfo * exception)
Definition at line 2879 of file fx.c.
References FxEvaluateChannelExpression(), and GrayPixelChannel.
static double FxEvaluateSubexpression (FxInfo * fx_info, const PixelChannel channel, const ssize_t x, const ssize_t y, const char * expression, double * beta, ExceptionInfo * exception) static
Definition at line 2093 of file fx.c.
References AddValueToSplayTree(), AlphaPixelChannel, BlackPixelChannel, BluePixelChannel, ClearMagickException(), CMYKColorspace, _Image::colorspace, ConstantString(), CopyMagickString(), CyanPixelChannel, DeleteNodeFromSplayTree(), EqualOperator, ExponentialNotation, _FxInfo::file, _Image::filename, FormatLocaleFile(), FormatLocaleString(), FxGCD(), FxGetSymbol(), FxOperatorPrecedence(), GetMagickModule, GetMagickPrecision(), GetPseudoRandomValue(), GreaterThanEqualOperator, GreenPixelChannel, _FxInfo::images, InterpretSiPrefixValue(), LeftShiftOperator, LessThanEqualOperator, LocaleCompare(), LocaleNCompare(), LogicalAndOperator, LogicalOrOperator, MagentaPixelChannel, MagickEpsilon, MagickPHI, MagickPI, MaxTextExtent, NotEqualOperator, OptionError, QuantumRange, QuantumScale, _FxInfo::random_info, RedPixelChannel, RightShiftOperator, _ExceptionInfo::severity, StringToken(), _FxInfo::symbols, ThrowMagickException(), UndefinedException, and YellowPixelChannel.
Referenced by FxEvaluateChannelExpression(), and FxGetSymbol().
static MagickOffsetType FxGCD (MagickOffsetType alpha, MagickOffsetType beta) static
Definition at line 1240 of file fx.c.
Referenced by FxEvaluateSubexpression().
static double FxGetSymbol (FxInfo * fx_info, const PixelChannel channel, const ssize_t x, const ssize_t y, const char * expression, ExceptionInfo * exception) static
Definition at line 1274 of file fx.c.
References AddValueToSplayTree(), AllCompliance, _PixelInfo::alpha, _PixelInfo::alpha_trait, AlphaPixelChannel, _PixelInfo::black, BlackPixelChannel, BlendPixelTrait, _PixelInfo::blue, BluePixelChannel, _GeometryInfo::chi, ChiValue, ClonePixelInfo(), CMYKColorspace, _FxInfo::colors, _Image::colorspace, _Image::columns, ConstantString(), ConvertRGBToHSL(), CopyMagickString(), CyanPixelChannel, _FxInfo::exception, _Image::filename, FxChannelStatistics(), FxEvaluateSubexpression(), GetImageDepth(), GetImageFromList(), GetImageIndexInList(), GetImageListLength(), GetMagickModule, GetPixelInfo(), GetPixelInfoIntensity(), GetValueFromSplayTree(), _PixelInfo::green, GreenPixelChannel, _RectangleInfo::height, ImageError, _FxInfo::images, IndexPixelChannel, IntensityPixelChannel, _Image::interpolate, InterpolatePixelInfo(), LocaleCompare(), LocaleNCompare(), MagentaPixelChannel, MagickFalse, MaxTextExtent, OptionError, _Image::page, ParseGeometry(), _GeometryInfo::psi, PsiValue, QuantumScale, QueryColorCompliance(), _PixelInfo::red, RedPixelChannel, _Image::resolution, _GeometryInfo::rho, RhoValue, _Image::rows, _GeometryInfo::sigma, SigmaValue, StringToDouble(), StripString(), _FxInfo::symbols, ThrowMagickException(), _FxInfo::view, _RectangleInfo::width, _PointInfo::x, _RectangleInfo::x, _GeometryInfo::xi, XiValue, _PointInfo::y, _RectangleInfo::y, and YellowPixelChannel.
Referenced by FxEvaluateSubexpression().
MagickExport Image* FxImage (const Image * image, const char * expression, ExceptionInfo * exception)
Definition at line 3010 of file fx.c.
References AcquireAuthenticCacheView(), AcquireFxThreadSet(), AcquireVirtualCacheView(), ClampToQuantum(), CloneImage(), _Image::columns, CopyPixelTrait, _Image::debug, DestroyCacheView(), DestroyFxThreadSet(), DestroyImage(), DirectClass, _Image::filename, FxEvaluateChannelExpression(), FxImageTag, GetCacheViewVirtualPixels(), GetMagickModule, GetOpenMPThreadId(), GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelReadMask(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, _Image::progress_monitor, QuantumRange, QueueCacheViewAuthenticPixels(), _Image::rows, SetImageProgress(), SetImageStorageClass(), SetPixelChannel(), _Image::signature, SyncCacheViewAuthenticPixels(), TraceEvent, and UndefinedPixelTrait.
static const char* FxOperatorPrecedence (const char * expression, ExceptionInfo * exception) static
Definition at line 1837 of file fx.c.
References EqualOperator, ExponentialNotation, FxSubexpression(), GreaterThanEqualOperator, LeftShiftOperator, LessThanEqualOperator, LocaleNCompare(), LogicalAndOperator, LogicalOrOperator, NotEqualOperator, and RightShiftOperator.
Referenced by FxEvaluateSubexpression().
MagickExport MagickBooleanType FxPreprocessExpression (FxInfo * fx_info, double * alpha, ExceptionInfo * exception)
Definition at line 2890 of file fx.c.
References _FxInfo::file, FxEvaluateChannelExpression(), and GrayPixelChannel.
Referenced by AcquireFxThreadSet().
static const char* FxSubexpression (const char * expression, ExceptionInfo * exception) inline static
Definition at line 1247 of file fx.c.
References GetMagickModule, OptionError, and ThrowMagickException().
Referenced by FxOperatorPrecedence().
MagickExport Image* ImplodeImage (const Image * image, const double amount, const PixelInterpolateMethod method, ExceptionInfo * exception)
Definition at line 3176 of file fx.c.
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), _PixelInfo::alpha, _Image::alpha_trait, _Image::background_color, BlendPixelTrait, CloneImage(), _Image::columns, _Image::debug, DestroyCacheView(), DestroyImage(), DirectClass, _Image::filename, GetCacheViewVirtualPixels(), GetMagickModule, GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelReadMask(), ImplodeImageTag, InterpolatePixelChannels(), LogMagickEvent(), MagickFalse, MagickPI, MagickSignature, MagickTrue, OpaqueAlpha, _Image::progress_monitor, QueueCacheViewAuthenticPixels(), _Image::rows, SetImageProgress(), SetImageStorageClass(), SetPixelChannel(), _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), TraceEvent, UndefinedPixelTrait, _PointInfo::x, and _PointInfo::y.
Referenced by PreviewImage().
static double MagickMax (const double x, const double y) inline static
Definition at line 1111 of file fx.c.
Referenced by PolaroidImage(), and SwirlImage().
static double MagickMin (const double x, const double y) inline static
Definition at line 1118 of file fx.c.
MagickExport Image* MorphImages (const Image * image, const size_t number_frames, ExceptionInfo * exception)
Definition at line 3381 of file fx.c.
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), AppendImageToList(), ClampToQuantum(), CloneImage(), _Image::columns, CopyPixelTrait, _Image::debug, DestroyCacheView(), DestroyImage(), DestroyImageList(), DirectClass, _Image::filename, _Image::filter, GetCacheViewAuthenticPixels(), GetCacheViewVirtualPixels(), GetFirstImageInList(), GetImageListLength(), GetLastImageInList(), GetMagickModule, GetNextImageInList(), GetPixelChannel(), GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelReadMask(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, MorphImageTag, _Image::progress_monitor, ResizeImage(), _Image::rows, SetImageProgress(), SetImageStorageClass(), SetPixelChannel(), _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), TraceEvent, and UndefinedPixelTrait.
MagickExport MagickBooleanType PlasmaImage (Image * image, const SegmentInfo * segment, size_t attenuate, size_t depth, ExceptionInfo * exception)
Definition at line 3829 of file fx.c.
References AcquireAuthenticCacheView(), AcquireRandomInfo(), AcquireVirtualCacheView(), _Image::debug, DestroyCacheView(), DestroyRandomInfo(), DirectClass, GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, PlasmaImageProxy(), random_info, SetImageStorageClass(), _Image::signature, and TraceEvent.
static MagickBooleanType PlasmaImageProxy (Image * image, CacheView * image_view, CacheView * u_view, CacheView * v_view, RandomInfo * random_info, const SegmentInfo * segment, size_t attenuate, size_t depth, ExceptionInfo * exception) static
Definition at line 3632 of file fx.c.
References GetCacheViewVirtualPixels(), GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), MagickFalse, MagickTrue, PlasmaPixel(), QuantumRange, QueueCacheViewAuthenticPixels(), SyncCacheViewAuthenticPixels(), UndefinedPixelTrait, _SegmentInfo::x1, _SegmentInfo::x2, _SegmentInfo::y1, and _SegmentInfo::y2.
Referenced by PlasmaImage().
static Quantum PlasmaPixel (RandomInfo * random_info, const double pixel, const double noise) inline static
Definition at line 3621 of file fx.c.
References ClampToQuantum(), and GetPseudoRandomValue().
Referenced by PlasmaImageProxy().
MagickExport Image* PolaroidImage (const Image * image, const DrawInfo * draw_info, const char * caption, const double angle, const PixelInterpolateMethod method, ExceptionInfo * exception)
Definition at line 3899 of file fx.c.
References AcquireImageInfo(), AcquireString(), AllCompliance, AnnotateImage(), _TypeMetric::ascent, _Image::background_color, _Image::border_color, CloneDrawInfo(), CloneImage(), CloneString(), _Image::columns, CompositeImage(), _Image::debug, _TypeMetric::descent, DestroyDrawInfo(), DestroyImage(), DestroyImageInfo(), DestroyString(), _Image::filename, FlopImage(), FormatLocaleString(), FormatMagickCaption(), _DrawInfo::geometry, GetMagickModule, _DrawInfo::gravity, InterpretImageProperties(), LogMagickEvent(), MagickFalse, MagickMax(), MagickSignature, MagickTrue, MaxTextExtent, OpaqueAlphaChannel, OverCompositeOp, QueryColorCompliance(), RotateImage(), _Image::rows, SetImageAlphaChannel(), SetImageBackgroundColor(), SetImageExtent(), ShadowImage(), _ExceptionInfo::signature, _Image::signature, _DrawInfo::text, TraceEvent, TrimImage(), UndefinedGravity, and WaveImage().
MagickExport Image* SepiaToneImage (const Image * image, const double threshold, ExceptionInfo * exception)
Definition at line 4087 of file fx.c.
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), ClampToQuantum(), CloneImage(), _Image::columns, ContrastImage(), _Image::debug, DestroyCacheView(), DestroyImage(), DirectClass, _Image::filename, GetCacheViewAuthenticPixels(), GetCacheViewVirtualPixels(), GetMagickModule, GetPixelBlue(), GetPixelChannels(), GetPixelGreen(), GetPixelIntensity(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, NormalizeImage(), _Image::progress_monitor, QuantumRange, _Image::rows, SepiaToneImageTag, SetImageProgress(), SetImageStorageClass(), SetPixelBlue(), SetPixelGreen(), SetPixelRed(), _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), and TraceEvent.
MagickExport Image* ShadowImage (const Image * image, const double alpha, const double sigma, const ssize_t x_offset, const ssize_t y_offset, ExceptionInfo * exception)
Definition at line 4239 of file fx.c.
References AcquireAuthenticCacheView(), AllCompliance, _PixelInfo::alpha, _PixelInfo::alpha_trait, _Image::alpha_trait, AlphaChannel, _Image::background_color, BlendPixelTrait, BlurImage(), _Image::border_color, BorderImage(), CloneImage(), _Image::colorspace, _Image::columns, _Image::debug, DestroyCacheView(), DestroyImage(), _Image::filename, GetMagickModule, GetPixelAlpha(), GetPixelChannels(), _RectangleInfo::height, IsGrayColorspace(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, OpaqueAlphaChannel, OverCompositeOp, _Image::page, QueryColorCompliance(), QueueCacheViewAuthenticPixels(), _Image::rows, SetImageAlphaChannel(), SetImageChannelMask(), SetImageColorspace(), SetImageVirtualPixelMethod(), SetPixelChannelMask(), SetPixelInfoPixel(), _ExceptionInfo::signature, _Image::signature, sRGBColorspace, SyncCacheViewAuthenticPixels(), TraceEvent, TransparentVirtualPixelMethod, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
Referenced by MontageImageList(), and PolaroidImage().
MagickExport Image* SketchImage (const Image * image, const double radius, const double sigma, const double angle, ExceptionInfo * exception)
Definition at line 4387 of file fx.c.
References AcquireAuthenticCacheView(), AcquireRandomInfoThreadSet(), BlendCompositeOp, ClampToQuantum(), CloneImage(), ColorDodgeCompositeOp, _Image::columns, CompositeImage(), DestroyCacheView(), DestroyImage(), DestroyRandomInfoThreadSet(), EdgeImage(), GetOpenMPThreadId(), GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelReadMask(), GetPseudoRandomValue(), GetRandomSecretKey(), MagickFalse, MagickTrue, MotionBlurImage(), NegateImage(), NormalizeImage(), QuantumRange, QueueCacheViewAuthenticPixels(), random_info, _Image::rows, SetImageArtifact(), SyncCacheViewAuthenticPixels(), TransformImage(), and UndefinedPixelTrait.
MagickExport MagickBooleanType SolarizeImage (Image * image, const double threshold, ExceptionInfo * exception)
Definition at line 4548 of file fx.c.
References AcquireAuthenticCacheView(), _PixelInfo::blue, _Image::colormap, _Image::colors, _Image::colorspace, _Image::columns, CopyPixelTrait, _Image::debug, DestroyCacheView(), _Image::filename, GetCacheViewAuthenticPixels(), GetMagickModule, GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelReadMask(), _PixelInfo::green, IsGrayColorspace(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, _Image::progress_monitor, PseudoClass, QuantumRange, _PixelInfo::red, _Image::rows, SetImageColorspace(), SetImageProgress(), _Image::signature, SolarizeImageTag, sRGBColorspace, _Image::storage_class, SyncCacheViewAuthenticPixels(), TraceEvent, and UndefinedPixelTrait.
Referenced by PreviewImage().
MagickExport Image* SteganoImage (const Image * image, const Image * watermark, ExceptionInfo * exception)
Definition at line 4687 of file fx.c.
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), CloneImage(), _Image::columns, _Image::debug, _Image::depth, DestroyCacheView(), DestroyImage(), DirectClass, _Image::filename, GetBit, GetCacheViewAuthenticPixels(), GetMagickModule, GetOneCacheViewVirtualPixelInfo(), GetPixelBlue(), GetPixelGreen(), GetPixelInfoIntensity(), GetPixelRed(), LogMagickEvent(), MAGICKCORE_QUANTUM_DEPTH, MagickFalse, MagickSignature, MagickTrue, _Image::offset, _Image::progress_monitor, _Image::rows, SetBit, SetImageProgress(), SetImageStorageClass(), SetPixelBlue(), SetPixelGreen(), SetPixelRed(), _ExceptionInfo::signature, _Image::signature, SteganoImageTag, SyncCacheViewAuthenticPixels(), and TraceEvent.
MagickExport Image* StereoAnaglyphImage (const Image * left_image, const Image * right_image, const ssize_t x_offset, const ssize_t y_offset, ExceptionInfo * exception)
Definition at line 4874 of file fx.c.
References CloneImage(), _Image::columns, CopyPixelTrait, _Image::debug, DestroyImage(), DirectClass, _Image::filename, GetMagickModule, GetPixelAlpha(), GetPixelAlphaTraits(), GetPixelBlue(), GetPixelChannels(), GetPixelGreen(), GetPixelRed(), GetVirtualPixels(), ImageError, LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, _Image::progress_monitor, QueueAuthenticPixels(), _Image::rows, SetImageColorspace(), SetImageProgress(), SetImageStorageClass(), SetPixelAlpha(), SetPixelBlue(), SetPixelGreen(), SetPixelRed(), _ExceptionInfo::signature, _Image::signature, sRGBColorspace, StereoImageTag, SyncAuthenticPixels(), ThrowImageException, and TraceEvent.
Referenced by StereoImage().
MagickExport Image* StereoImage (const Image * left_image, const Image * right_image, ExceptionInfo * exception)
Definition at line 4868 of file fx.c.
References StereoAnaglyphImage().
MagickExport Image* SwirlImage (const Image * image, double degrees, const PixelInterpolateMethod method, ExceptionInfo * exception)
Definition at line 5003 of file fx.c.
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), _PixelInfo::alpha, _Image::alpha_trait, _Image::background_color, BlendPixelTrait, CloneImage(), _Image::columns, _Image::debug, DegreesToRadians(), DestroyCacheView(), DestroyImage(), DirectClass, _Image::filename, GetCacheViewVirtualPixels(), GetMagickModule, GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelReadMask(), InterpolatePixelChannels(), LogMagickEvent(), MagickFalse, MagickMax(), MagickSignature, MagickTrue, OpaqueAlpha, _Image::progress_monitor, QueueCacheViewAuthenticPixels(), _Image::rows, SetImageProgress(), SetImageStorageClass(), SetPixelChannel(), _ExceptionInfo::signature, _Image::signature, SwirlImageTag, SyncCacheViewAuthenticPixels(), TraceEvent, UndefinedPixelTrait, _PointInfo::x, and _PointInfo::y.
Referenced by PreviewImage().
MagickExport Image* TintImage (const Image * image, const char * blend, const PixelInfo * tint, ExceptionInfo * exception)
Definition at line 5208 of file fx.c.
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), _PixelInfo::alpha, _PixelInfo::black, _PixelInfo::blue, _GeometryInfo::chi, ChiValue, CloneImage(), CMYKColorspace, _Image::colorspace, _Image::columns, CopyPixelTrait, _Image::debug, DestroyCacheView(), DestroyImage(), DirectClass, _Image::filename, GetCacheViewVirtualPixels(), GetMagickModule, GetPixelBlack(), GetPixelBlue(), GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelGreen(), GetPixelInfo(), GetPixelInfoIntensity(), GetPixelReadMask(), GetPixelRed(), _PixelInfo::green, IsGrayColorspace(), IsPixelInfoGray(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, OpaqueAlpha, ParseGeometry(), _Image::progress_monitor, _GeometryInfo::psi, PsiValue, QuantumScale, QueueCacheViewAuthenticPixels(), _PixelInfo::red, _GeometryInfo::rho, _Image::rows, SetImageColorspace(), SetImageProgress(), SetImageStorageClass(), SetPixelChannel(), SetPixelInfoPixel(), _GeometryInfo::sigma, SigmaValue, _ExceptionInfo::signature, _Image::signature, sRGBColorspace, SyncCacheViewAuthenticPixels(), TintImageTag, TraceEvent, UndefinedPixelTrait, _GeometryInfo::xi, and XiValue.
MagickExport Image* VignetteImage (const Image * image, const double radius, const double sigma, const ssize_t x, const ssize_t y, ExceptionInfo * exception)
Definition at line 5421 of file fx.c.
References AcquireString(), AllCompliance, _Image::alpha_trait, _Image::background_color, BlendPixelTrait, BlurImage(), CloneDrawInfo(), CloneImage(), _Image::colorspace, _Image::columns, CompositeImage(), _Image::debug, DestroyDrawInfo(), DestroyImage(), DirectClass, DrawImage(), _Image::filename, _DrawInfo::fill, FlattenLayer, FormatLocaleString(), GetMagickModule, IntensityCompositeOp, LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, MaxTextExtent, MergeImageLayers(), _DrawInfo::primitive, QueryColorCompliance(), _Image::rows, SetImageBackgroundColor(), SetImageStorageClass(), _ExceptionInfo::signature, _Image::signature, _DrawInfo::stroke, TraceEvent, TransformImageColorspace(), and UndefinedPixelTrait.
MagickExport Image* WaveImage (const Image * image, const double amplitude, const double wave_length, const PixelInterpolateMethod method, ExceptionInfo * exception)
Definition at line 5523 of file fx.c.
References AcquireAuthenticCacheView(), AcquireQuantumMemory(), AcquireVirtualCacheView(), _PixelInfo::alpha, _Image::alpha_trait, _Image::background_color, BackgroundVirtualPixelMethod, BlendPixelTrait, CloneImage(), _Image::columns, _Image::debug, DestroyCacheView(), DestroyImage(), DirectClass, _Image::filename, GetMagickModule, GetPixelChannels(), InterpolatePixelChannels(), LogMagickEvent(), MagickFalse, MagickPI, MagickSignature, MagickTrue, OpaqueAlpha, _Image::progress_monitor, QueueCacheViewAuthenticPixels(), RelinquishMagickMemory(), ResourceLimitError, _Image::rows, SetCacheViewVirtualPixelMethod(), SetImageProgress(), SetImageStorageClass(), _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), ThrowImageException, TraceEvent, and WaveImageTag.
Referenced by PolaroidImage(), and PreviewImage().