MagickCore: fx.h File Reference
fx.h File Reference
#include "MagickCore/draw.h"
Enumerations
enum NoiseType {
UndefinedNoise, UniformNoise, GaussianNoise, MultiplicativeGaussianNoise,
ImpulseNoise, LaplacianNoise, PoissonNoise, RandomNoise
}
Functions
MagickExport Image * AddNoiseImage (const Image *, const NoiseType, const double, ExceptionInfo *)
MagickExport Image * BlueShiftImage (const Image *, const double, ExceptionInfo *)
MagickExport Image * CharcoalImage (const Image *, const double, const double, ExceptionInfo *)
MagickExport Image * ColorizeImage (const Image *, const char *, const PixelInfo *, ExceptionInfo *)
MagickExport Image * ColorMatrixImage (const Image *, const KernelInfo *kernel, ExceptionInfo *)
MagickExport Image * FxImage (const Image *, const char *, ExceptionInfo *)
MagickExport Image * ImplodeImage (const Image *, const double, const PixelInterpolateMethod, ExceptionInfo *)
MagickExport Image * MorphImages (const Image *, const size_t, ExceptionInfo *)
MagickExport Image * PolaroidImage (const Image *, const DrawInfo *, const char *, const double, const PixelInterpolateMethod, ExceptionInfo *)
MagickExport Image * SepiaToneImage (const Image *, const double, ExceptionInfo *)
MagickExport Image * ShadowImage (const Image *, const double, const double, const ssize_t, const ssize_t, ExceptionInfo *)
MagickExport Image * SketchImage (const Image *, const double, const double, const double, ExceptionInfo *)
MagickExport Image * SteganoImage (const Image *, const Image *, ExceptionInfo *)
MagickExport Image * StereoImage (const Image *, const Image *, ExceptionInfo *)
MagickExport Image * StereoAnaglyphImage (const Image *, const Image *, const ssize_t, const ssize_t, ExceptionInfo *)
MagickExport Image * SwirlImage (const Image *, double, const PixelInterpolateMethod, ExceptionInfo *)
MagickExport Image * TintImage (const Image *, const char *, const PixelInfo *, ExceptionInfo *)
MagickExport Image * VignetteImage (const Image *, const double, const double, const ssize_t, const ssize_t, ExceptionInfo *)
MagickExport Image * WaveImage (const Image *, const double, const double, const PixelInterpolateMethod, ExceptionInfo *)
MagickExport MagickBooleanType PlasmaImage (Image *, const SegmentInfo *, size_t, size_t, ExceptionInfo *)
MagickExport MagickBooleanType SolarizeImage (Image *, const double, ExceptionInfo *)
Enumeration Type Documentation
enum NoiseType
Enumerator
UndefinedNoise
UniformNoise
GaussianNoise
MultiplicativeGaussianNoise
ImpulseNoise
LaplacianNoise
PoissonNoise
RandomNoise
Definition at line 27 of file fx.h.
Function Documentation
MagickExport Image* AddNoiseImage (const Image * , const NoiseType , const double , ExceptionInfo *)
MagickExport Image * BlueShiftImage (const Image * , const double , ExceptionInfo *)
MagickExport Image * CharcoalImage (const Image * , const double , const double , ExceptionInfo *)
MagickExport Image * ColorizeImage (const Image * , const char * , const PixelInfo * , ExceptionInfo *)
MagickExport Image * ColorMatrixImage (const Image * , const KernelInfo * kernel, ExceptionInfo *)
MagickExport Image * FxImage (const Image * , const char * , ExceptionInfo *)
MagickExport Image * ImplodeImage (const Image * , const double , const PixelInterpolateMethod , ExceptionInfo *)
MagickExport Image * MorphImages (const Image * , const size_t , ExceptionInfo *)
MagickExport MagickBooleanType PlasmaImage (Image * , const SegmentInfo * , size_t , size_t , ExceptionInfo *)
MagickExport Image * PolaroidImage (const Image * , const DrawInfo * , const char * , const double , const PixelInterpolateMethod , ExceptionInfo *)
MagickExport Image * SepiaToneImage (const Image * , const double , ExceptionInfo *)
MagickExport Image * ShadowImage (const Image * , const double , const double , const ssize_t , const ssize_t , ExceptionInfo *)
MagickExport Image * SketchImage (const Image * , const double , const double , const double , ExceptionInfo *)
MagickExport MagickBooleanType SolarizeImage (Image * , const double , ExceptionInfo *)
Definition at line 4548 of file fx.c.
References AcquireAuthenticCacheView(), _PixelInfo::blue, _Image::colormap, _Image::colors, _Image::colorspace, _Image::columns, CopyPixelTrait, _Image::debug, DestroyCacheView(), _Image::filename, GetCacheViewAuthenticPixels(), GetMagickModule, GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelReadMask(), _PixelInfo::green, IsGrayColorspace(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, _Image::progress_monitor, PseudoClass, QuantumRange, _PixelInfo::red, _Image::rows, SetImageColorspace(), SetImageProgress(), _Image::signature, SolarizeImageTag, sRGBColorspace, _Image::storage_class, SyncCacheViewAuthenticPixels(), TraceEvent, and UndefinedPixelTrait.
Referenced by PreviewImage().
MagickExport Image * SteganoImage (const Image * , const Image * , ExceptionInfo *)
MagickExport Image * StereoAnaglyphImage (const Image * , const Image * , const ssize_t , const ssize_t , ExceptionInfo *)
MagickExport Image * StereoImage (const Image * , const Image * , ExceptionInfo *)
MagickExport Image * SwirlImage (const Image * , double , const PixelInterpolateMethod , ExceptionInfo *)
MagickExport Image * TintImage (const Image * , const char * , const PixelInfo * , ExceptionInfo *)
MagickExport Image * VignetteImage (const Image * , const double , const double , const ssize_t , const ssize_t , ExceptionInfo *)
MagickExport Image * WaveImage (const Image * , const double , const double , const PixelInterpolateMethod , ExceptionInfo *)
Definition at line 5523 of file fx.c.
References AcquireAuthenticCacheView(), AcquireQuantumMemory(), AcquireVirtualCacheView(), _PixelInfo::alpha, _Image::alpha_trait, _Image::background_color, BackgroundVirtualPixelMethod, BlendPixelTrait, CloneImage(), _Image::columns, _Image::debug, DestroyCacheView(), DestroyImage(), DirectClass, _Image::filename, GetMagickModule, GetPixelChannels(), InterpolatePixelChannels(), LogMagickEvent(), MagickFalse, MagickPI, MagickSignature, MagickTrue, OpaqueAlpha, _Image::progress_monitor, QueueCacheViewAuthenticPixels(), RelinquishMagickMemory(), ResourceLimitError, _Image::rows, SetCacheViewVirtualPixelMethod(), SetImageProgress(), SetImageStorageClass(), _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), ThrowImageException, TraceEvent, and WaveImageTag.
Referenced by PolaroidImage(), and PreviewImage().