MagickCore: gem.h File Reference
gem.h File Reference
#include "MagickCore/fx.h"
#include "MagickCore/random_.h"
Functions
MagickExport double ExpandAffine (const AffineMatrix *)
MagickExport void ConvertHSLToRGB (const double, const double, const double, double *, double *, double *)
MagickExport void ConvertRGBToHSL (const double, const double, const double, double *, double *, double *)
Function Documentation
MagickExport void ConvertHSLToRGB (const double , const double , const double , double * , double * , double *)
MagickExport void ConvertRGBToHSL (const double , const double , const double , double * , double * , double *)
Definition at line 1132 of file gem.c.
References MagickMax(), MagickMin(), and QuantumScale.
Referenced by FxGetSymbol(), ModulateHSL(), and sRGBTransformImage().
MagickExport double ExpandAffine (const AffineMatrix *)
Definition at line 1457 of file gem.c.
References _AffineMatrix::rx, _AffineMatrix::ry, _AffineMatrix::sx, and _AffineMatrix::sy.
Referenced by DrawBoundingRectangles(), DrawDashPolygon(), DrawPolygonPrimitive(), DrawPrimitive(), RenderPostscript(), and TraceStrokePolygon().