MagickCore: identify.h File Reference
identify.h File Reference
Functions
MagickExport MagickBooleanType IdentifyImage (Image *, FILE *, const MagickBooleanType, ExceptionInfo *)
Function Documentation
MagickExport MagickBooleanType IdentifyImage (Image * , FILE * , const MagickBooleanType , ExceptionInfo *)
Definition at line 236 of file identify.c.
References AcquireImageInfo(), AcquireQuantumMemory(), _PixelInfo::alpha_trait, _Image::alpha_trait, AlphaPixelChannel, _Image::background_color, BlackPixelChannel, BlendPixelTrait, _ChromaticityInfo::blue_primary, BluePixelChannel, _Image::border_color, _Image::chromaticity, CloneString(), cmsUInt32Number, CMYKColorspace, _Image::colormap, _Image::colors, _Image::colorspace, _PixelInfo::colorspace, _Image::columns, CommandOptionToMnemonic(), _Image::compose, CompositePixelChannel, _Image::compression, ConcatenateColorComponent(), ConcatenateMagickString(), CopyMagickString(), CyanPixelChannel, _Image::debug, _Image::delay, _ChannelStatistics::depth, _Image::depth, DestroyImage(), DestroyImageInfo(), DestroyString(), DirectClass, _Image::directory, _Image::dispose, _Image::endian, _Image::error, _Image::extract_info, _Image::filename, _ImageInfo::filename, FormatLocaleFile(), FormatLocaleString(), FormatMagickSize(), _Image::gamma, GetBlobSize(), GetColorTuple(), GetElapsedTime(), GetImageArtifact(), GetImageDepth(), GetImageFeatures(), GetImageListLength(), GetImageProfile(), GetImageProperty(), GetImageRegistry(), GetImageStatistics(), GetImageTotalInkDensity(), GetImageType(), GetMagickDescription(), GetMagickInfo(), GetMagickModule, GetMagickVersion(), GetNextImageArtifact(), GetNextImageInList(), GetNextImageProfile(), GetNextImageProperty(), GetNextImageRegistry(), GetNumberColors(), GetPathComponent(), GetPixelAlpha(), GetPixelChannels(), GetPixelInfo(), GetPixelInfoPixel(), GetPreviousImageInList(), GetStringInfoDatum(), GetStringInfoLength(), GetTimerInfo(), GetUserTime(), GetVirtualPixels(), GRAYColorspace, GrayPixelChannel, _ChromaticityInfo::green_primary, GreenPixelChannel, _RectangleInfo::height, IfMagickTrue, _Image::intensity, _Image::interlace, IsHistogramImage(), IsImageGray(), IsStringTrue(), _Image::iterations, LocaleCompare(), LogMagickEvent(), MagentaPixelChannel, _Image::magick, _Image::magick_columns, _Image::magick_filename, _Image::magick_rows, MagickBooleanOptions, MagickClassOptions, MagickColorspaceOptions, MagickComposeOptions, MagickCompressOptions, MAGICKCORE_QUANTUM_DEPTH, MagickDisposeOptions, MagickEndianOptions, MagickFalse, MagickIntentOptions, MagickInterlaceOptions, MagickOrientationOptions, MagickPixelIntensityOptions, MagickResolutionOptions, MagickSignature, MagickTrue, MagickTypeOptions, _Image::matte_color, MaxPixelChannels, MaxTextExtent, _ErrorInfo::mean_error_per_pixel, _Image::montage, _Image::next, _ErrorInfo::normalized_maximum_error, _ErrorInfo::normalized_mean_error, _Image::orientation, _Image::page, _Image::previous, PrintChannelFeatures(), PrintChannelStatistics(), PrintStringInfo(), PseudoClass, _Image::quality, QuantumRange, QueryColorname(), ReadImage(), _ChromaticityInfo::red_primary, RedPixelChannel, registry, RelinquishMagickMemory(), _Image::rendering_intent, ResetImageArtifactIterator(), ResetImageProfileIterator(), ResetImagePropertyIterator(), ResetImageRegistryIterator(), _Image::resolution, RGBColorspace, _Image::rows, _Image::scene, sentinel, SetWarningHandler(), _Image::signature, SignatureImage(), _ImageInfo::size, _Image::storage_class, StringRegistryType, StringToList(), StringToUnsignedLong(), SVGCompliance, TailPath, _Image::taint, _Image::ticks_per_second, _Image::tile_offset, _Image::timer, _Image::total_colors, TraceEvent, _Image::transparent_color, TransparentAlpha, _Image::type, UndefinedColorspace, UndefinedCompressionQuality, UndefinedType, _Image::units, _ChromaticityInfo::white_point, _RectangleInfo::width, _PrimaryInfo::x, _PointInfo::x, _RectangleInfo::x, X11Compliance, _PrimaryInfo::y, _PointInfo::y, _RectangleInfo::y, and YellowPixelChannel.
Referenced by PingImage(), ReadImage(), and WriteImage().