MagickCore: image.c File Reference
image.c File Reference
#include "MagickCore/studio.h"
#include "MagickCore/animate.h"
#include "MagickCore/artifact.h"
#include "MagickCore/attribute.h"
#include "MagickCore/blob.h"
#include "MagickCore/blob-private.h"
#include "MagickCore/cache.h"
#include "MagickCore/cache-private.h"
#include "MagickCore/cache-view.h"
#include "MagickCore/client.h"
#include "MagickCore/color.h"
#include "MagickCore/color-private.h"
#include "MagickCore/colormap.h"
#include "MagickCore/colorspace.h"
#include "MagickCore/colorspace-private.h"
#include "MagickCore/composite.h"
#include "MagickCore/composite-private.h"
#include "MagickCore/compress.h"
#include "MagickCore/constitute.h"
#include "MagickCore/display.h"
#include "MagickCore/draw.h"
#include "MagickCore/enhance.h"
#include "MagickCore/exception.h"
#include "MagickCore/exception-private.h"
#include "MagickCore/gem.h"
#include "MagickCore/geometry.h"
#include "MagickCore/histogram.h"
#include "MagickCore/image-private.h"
#include "MagickCore/list.h"
#include "MagickCore/magic.h"
#include "MagickCore/magick.h"
#include "MagickCore/magick-private.h"
#include "MagickCore/memory_.h"
#include "MagickCore/module.h"
#include "MagickCore/monitor.h"
#include "MagickCore/monitor-private.h"
#include "MagickCore/option.h"
#include "MagickCore/paint.h"
#include "MagickCore/pixel-accessor.h"
#include "MagickCore/profile.h"
#include "MagickCore/property.h"
#include "MagickCore/quantize.h"
#include "MagickCore/random_.h"
#include "MagickCore/resource_.h"
#include "MagickCore/segment.h"
#include "MagickCore/semaphore.h"
#include "MagickCore/signature-private.h"
#include "MagickCore/statistic.h"
#include "MagickCore/string_.h"
#include "MagickCore/string-private.h"
#include "MagickCore/thread-private.h"
#include "MagickCore/threshold.h"
#include "MagickCore/timer.h"
#include "MagickCore/token.h"
#include "MagickCore/utility.h"
#include "MagickCore/utility-private.h"
#include "MagickCore/version.h"
#include "MagickCore/xwindow-private.h"
Macros
#define AppendImageTag "Append/Image"
#define ClipImagePathTag "ClipPath/Image"
#define SmushImageTag "Smush/Image"
Functions
MagickExport Image * AcquireImage (const ImageInfo *image_info, ExceptionInfo *exception)
MagickExport ImageInfo * AcquireImageInfo (void)
MagickExport void AcquireNextImage (const ImageInfo *image_info, Image *image, ExceptionInfo *exception)
MagickExport Image * AppendImages (const Image *images, const MagickBooleanType stack, ExceptionInfo *exception)
MagickExport ExceptionType CatchImageException (Image *image)
MagickExport MagickBooleanType ClipImage (Image *image, ExceptionInfo *exception)
MagickExport MagickBooleanType ClipImagePath (Image *image, const char *pathname, const MagickBooleanType inside, ExceptionInfo *exception)
MagickExport Image * CloneImage (const Image *image, const size_t columns, const size_t rows, const MagickBooleanType detach, ExceptionInfo *exception)
MagickExport ImageInfo * CloneImageInfo (const ImageInfo *image_info)
MagickExport Image * DestroyImage (Image *image)
MagickExport ImageInfo * DestroyImageInfo (ImageInfo *image_info)
MagickExport void DisassociateImageStream (Image *image)
MagickExport MagickBooleanType GetImageAlphaChannel (const Image *image)
MagickExport void GetImageInfo (ImageInfo *image_info)
MagickExport FILE * GetImageInfoFile (const ImageInfo *image_info)
MagickExport Image * GetImageMask (const Image *image, ExceptionInfo *exception)
MagickExport ssize_t GetImageReferenceCount (Image *image)
MagickExport VirtualPixelMethod GetImageVirtualPixelMethod (const Image *image)
MagickExport size_t InterpretImageFilename (const ImageInfo *image_info, Image *image, const char *format, int value, char *filename, ExceptionInfo *exception)
MagickExport MagickBooleanType IsHighDynamicRangeImage (const Image *image, ExceptionInfo *exception)
MagickExport MagickBooleanType IsImageObject (const Image *image)
MagickExport MagickBooleanType IsTaintImage (const Image *image)
MagickExport MagickBooleanType ModifyImage (Image **image, ExceptionInfo *exception)
MagickExport Image * NewMagickImage (const ImageInfo *image_info, const size_t width, const size_t height, const PixelInfo *background, ExceptionInfo *exception)
MagickExport Image * ReferenceImage (Image *image)
MagickExport MagickBooleanType ResetImagePage (Image *image, const char *page)
static void FlattenPixelInfo (const Image *image, const PixelInfo *p, const double alpha, const Quantum *q, const double beta, Quantum *composite)
MagickExport MagickBooleanType SetImageAlphaChannel (Image *image, const AlphaChannelOption alpha_type, ExceptionInfo *exception)
MagickExport MagickBooleanType SetImageBackgroundColor (Image *image, ExceptionInfo *exception)
MagickExport ChannelType SetImageChannelMask (Image *image, const ChannelType channel_mask)
MagickExport MagickBooleanType SetImageColor (Image *image, const PixelInfo *color, ExceptionInfo *exception)
MagickExport MagickBooleanType SetImageStorageClass (Image *image, const ClassType storage_class, ExceptionInfo *exception)
MagickExport MagickBooleanType SetImageExtent (Image *image, const size_t columns, const size_t rows, ExceptionInfo *exception)
MagickExport MagickBooleanType SetImageInfo (ImageInfo *image_info, const unsigned int frames, ExceptionInfo *exception)
MagickExport void SetImageInfoBlob (ImageInfo *image_info, const void *blob, const size_t length)
MagickExport void SetImageInfoFile (ImageInfo *image_info, FILE *file)
MagickExport MagickBooleanType SetImageMask (Image *image, const Image *mask, ExceptionInfo *exception)
MagickExport MagickBooleanType SetImageAlpha (Image *image, const Quantum alpha, ExceptionInfo *exception)
MagickExport VirtualPixelMethod SetImageVirtualPixelMethod (Image *image, const VirtualPixelMethod virtual_pixel_method, ExceptionInfo *exception)
static ssize_t SmushXGap (const Image *smush_image, const Image *images, const ssize_t offset, ExceptionInfo *exception)
static ssize_t SmushYGap (const Image *smush_image, const Image *images, const ssize_t offset, ExceptionInfo *exception)
MagickExport Image * SmushImages (const Image *images, const MagickBooleanType stack, const ssize_t offset, ExceptionInfo *exception)
MagickExport MagickBooleanType StripImage (Image *image, ExceptionInfo *exception)
static Quantum PushColormapIndex (Image *image, const Quantum index, MagickBooleanType *range_exception)
MagickExport MagickBooleanType SyncImage (Image *image, ExceptionInfo *exception)
MagickExport MagickBooleanType SyncImagesSettings (ImageInfo *image_info, Image *images, ExceptionInfo *exception)
MagickExport MagickBooleanType SyncImageSettings (const ImageInfo *image_info, Image *image, ExceptionInfo *exception)
Variables
const char BackgroundColor [] = "#ffffff"
const char BorderColor [] = "#dfdfdf"
const char DefaultTileFrame [] = "15x15+3+3"
const char DefaultTileGeometry [] = "120x120+4+3>"
const char DefaultTileLabel [] = "%f\n%G\n%b"
const char ForegroundColor [] = "#000"
const char LoadImageTag [] = "Load/Image"
const char LoadImagesTag [] = "Load/Images"
const char MatteColor [] = "#bdbdbd"
const char PSDensityGeometry [] = "72.0x72.0"
const char PSPageGeometry [] = "612x792"
const char SaveImageTag [] = "Save/Image"
const char SaveImagesTag [] = "Save/Images"
const char TransparentColor [] = "#00000000"
const double DefaultResolution = 72.0
Macro Definition Documentation
#define AppendImageTag "Append/Image"
Referenced by AppendImages().
#define ClipImagePathTag "ClipPath/Image"
#define SmushImageTag "Smush/Image"
Referenced by SmushImages().
Function Documentation
MagickExport Image* AcquireImage (const ImageInfo * image_info, ExceptionInfo * exception)
Definition at line 151 of file image.c.
References AcquireMagickMemory(), AcquirePixelCache(), AcquirePixelChannelMap(), AllCompliance, AllocateSemaphoreInfo(), _Image::background_color, _ImageInfo::background_color, BackgroundColor, _Image::blob, _ChromaticityInfo::blue_primary, _Image::border_color, _ImageInfo::border_color, BorderColor, _Image::cache, _ImageInfo::cache, _Image::channel_map, _Image::channel_mask, _Image::chromaticity, _Image::client_data, _ImageInfo::client_data, CloneBlobInfo(), ClonePixelCacheMethods(), _Image::colorspace, _Image::columns, _Image::compose, _Image::compression, _ImageInfo::compression, CopyMagickString(), _Image::debug, DefaultChannels, _Image::delay, _ImageInfo::density, _Image::depth, _ImageInfo::depth, DestroyString(), DirectClass, _Image::dispose, _Image::dither, _ImageInfo::dither, _Image::endian, _ImageInfo::endian, _ImageInfo::extract, _Image::extract_info, _ImageInfo::file, _Image::filename, _ImageInfo::filename, _Image::gamma, GetImageOption(), GetMagickModule, GetPageGeometry(), GetTimerInfo(), GreaterValue, _ChromaticityInfo::green_primary, _RectangleInfo::height, _ImageView::image, _Image::image_info, _Image::interlace, _ImageInfo::interlace, IsEventLogging(), LessValue, LogMagickEvent(), _Image::magick, _ImageInfo::magick, _Image::magick_filename, MAGICKCORE_QUANTUM_DEPTH, MagickDisposeOptions, MagickFalse, MagickSignature, MagickTrue, _Image::matte_color, _ImageInfo::matte_color, MatteColor, MaxTextExtent, NoInterlace, _Image::offset, OverCompositeOp, _Image::page, _ImageInfo::page, ParseAbsoluteGeometry(), ParseCommandOption(), ParseGeometry(), PerceptualIntent, _Image::ping, _ImageInfo::ping, _Image::progress_monitor, _ImageInfo::progress_monitor, _Image::quality, _ImageInfo::quality, QueryColorCompliance(), _ChromaticityInfo::red_primary, _Image::reference_count, _Image::rendering_intent, ResetMagickMemory(), _Image::resolution, ResourceLimitFatalError, _GeometryInfo::rho, _Image::rows, _Image::semaphore, SetBlobExempt(), _GeometryInfo::sigma, SigmaValue, _Image::signature, _ImageInfo::size, sRGBColorspace, _Image::storage_class, Swap, SyncImageSettings(), ThrowFatalException, _Image::ticks_per_second, _Image::timer, _Image::timestamp, TraceEvent, _Image::transparent_color, _ImageInfo::transparent_color, TransparentColor, UndefinedTicksPerSecond, _Image::units, _ImageInfo::units, _ChromaticityInfo::white_point, _RectangleInfo::width, _PrimaryInfo::x, _PointInfo::x, _RectangleInfo::x, XValue, _PrimaryInfo::y, _PointInfo::y, _RectangleInfo::y, YValue, and _PrimaryInfo::z.
Referenced by AcquireNextImage(), AcquireStreamInfo(), ConstituteImage(), DrawPatternPath(), MontageImageList(), NewMagickImage(), OpenDistributeCache(), ReadImage(), and SetImageInfo().
MagickExport ImageInfo* AcquireImageInfo (void)
Definition at line 340 of file image.c.
References AcquireMagickMemory(), GetImageInfo(), ResourceLimitFatalError, and ThrowFatalException.
Referenced by ClipImagePath(), CloneImageInfo(), DrawImage(), DrawPatternPath(), DrawPrimitive(), GlobExpression(), IdentifyImage(), MontageImages(), PreviewImage(), RenderPostscript(), SetImageProperty(), and SetImageType().
MagickExport void AcquireNextImage (const ImageInfo * image_info, Image * image, ExceptionInfo * exception)
Definition at line 383 of file image.c.
References AcquireImage(), _Image::blob, CopyMagickString(), _Image::debug, DestroyBlob(), _Image::endian, _Image::filename, _ImageInfo::filename, GetMagickModule, GetNextImageInList(), _ImageView::image, LogMagickEvent(), MagickFalse, MagickSignature, MaxTextExtent, _Image::next, _Image::previous, ReferenceBlob(), _Image::scene, _Image::signature, and TraceEvent.
Referenced by MontageImageList().
MagickExport Image* AppendImages (const Image * images, const MagickBooleanType stack, ExceptionInfo * exception)
Definition at line 440 of file image.c.
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), _Image::alpha_trait, AppendImageTag, BlendPixelTrait, CloneImage(), _Image::colorspace, _Image::columns, _Image::debug, DestroyCacheView(), DestroyImage(), DirectClass, _Image::filename, GetCacheViewVirtualPixels(), GetMagickModule, GetNextImageInList(), GetPixelChannels(), GetPixelInfo(), GetPixelInfoPixel(), GetPixelMask(), _Image::gravity, GravityAdjustGeometry(), _ImageView::image, LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, QueueCacheViewAuthenticPixels(), _Image::rows, SetGeometry(), SetImageBackgroundColor(), SetImageProgress(), SetImageStorageClass(), SetPixelInfoPixel(), _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), TraceEvent, TransformImageColorspace(), _RectangleInfo::x, and _RectangleInfo::y.
MagickExport ExceptionType CatchImageException (Image * image)
Definition at line 642 of file image.c.
References AcquireExceptionInfo(), CatchException(), _Image::debug, DestroyExceptionInfo(), _ImageView::exception, _Image::filename, GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, _ExceptionInfo::severity, _Image::signature, and TraceEvent.
MagickExport MagickBooleanType ClipImage (Image * image, ExceptionInfo * exception)
Definition at line 694 of file image.c.
References ClipImagePath(), and MagickTrue.
MagickExport MagickBooleanType ClipImagePath (Image * image, const char * pathname, const MagickBooleanType inside, ExceptionInfo * exception)
Definition at line 699 of file image.c.
References AcquireImageInfo(), AcquireString(), BlobToImage(), ConcatenateMagickString(), CopyMagickString(), _Image::debug, DestroyImage(), DestroyImageInfo(), DestroyString(), DirectClass, _Image::filename, _ImageInfo::filename, FormatLocaleString(), GetImageProperty(), GetMagickModule, LogMagickEvent(), _Image::magick_filename, MagickFalse, MagickSignature, MagickTrue, MaxTextExtent, NegateImage(), OptionError, PseudoClass, SetImageMask(), SetImageStorageClass(), _Image::signature, _Image::storage_class, SyncImage(), ThrowFileException, and TraceEvent.
Referenced by ClipImage().
MagickExport Image* CloneImage (const Image * image, const size_t columns, const size_t rows, const MagickBooleanType detach, ExceptionInfo * exception)
Definition at line 793 of file image.c.
References AcquireMagickMemory(), AcquireQuantumMemory(), AllocateSemaphoreInfo(), _Image::alpha_trait, _Image::ascii85, Ascii85Initialize(), _Image::blob, _Image::cache, _Image::channel_map, _Image::channel_mask, _Image::client_data, CloneBlobInfo(), CloneImageArtifacts(), CloneImageProfiles(), CloneImageProperties(), ClonePixelCache(), ClonePixelChannelMap(), CloneString(), _Image::colormap, _Image::colors, _Image::colorspace, _Image::columns, CopyMagickMemory(), CopyMagickString(), _Image::debug, _Image::directory, _Image::dither, _Image::filename, GetMagickModule, GetTimerInfo(), _RectangleInfo::height, IsEventLogging(), _Image::list, LogMagickEvent(), _Image::magick, _Image::magick_columns, _Image::magick_filename, _Image::magick_rows, MagickFalse, MagickSignature, _Image::mask, MaxTextExtent, _Image::metacontent_extent, _Image::montage, NewImageList(), _Image::next, _Image::number_channels, _Image::number_meta_channels, _Image::page, _Image::ping, _Image::previous, _Image::progress_monitor, _Image::reference_count, ReferenceBlob(), ReferencePixelCache(), ResetMagickMemory(), ResourceLimitError, _Image::rows, _Image::semaphore, _ExceptionInfo::signature, _Image::signature, _Image::storage_class, ThrowImageException, _Image::tile_offset, _Image::timer, TraceEvent, _Image::type, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
Referenced by AdaptiveBlurImage(), AdaptiveSharpenImage(), AdaptiveThresholdImage(), AddNoiseImage(), AppendImages(), AutoOrientImage(), BlueShiftImage(), BorderImage(), ChannelFxImage(), CharcoalImage(), ChopImage(), CloneDrawInfo(), CloneImageList(), CloneImages(), CoalesceImages(), ColorizeImage(), ColorMatrixImage(), CombineImages(), CompareImages(), CompareImagesLayers(), CompositeImage(), CompositeLayers(), ConsolidateCMYKImages(), CropImage(), CropImageToTiles(), DeskewImage(), DespeckleImage(), DisposeImages(), DistortImage(), DistortResizeImage(), DrawClipPath(), DrawStrokePolygon(), EnhanceImage(), EvaluateImages(), ExcerptImage(), ExtentImage(), FlipImage(), FloodfillPaintImage(), FlopImage(), ForwardFourierTransformImage(), FrameImage(), FxImage(), GetImageMask(), HuffmanEncodeImage(), ImplodeImage(), InjectImageBlob(), IntegralRotateImage(), InterpolativeResizeImage(), InverseFourierTransformImage(), MergeImageLayers(), ModifyImage(), MontageImageList(), MorphImages(), MorphologyApply(), MotionBlurImage(), OilPaintImage(), OptimizeImageTransparency(), OptimizeLayerFrames(), PolaroidImage(), PolynomialImage(), PreviewImage(), RadialBlurImage(), ResizeImage(), RollImage(), RotateImage(), SampleImage(), ScaleImage(), SelectiveBlurImage(), SeparateImage(), SepiaToneImage(), ShadeImage(), ShadowImage(), ShearImage(), SimilarityImage(), SketchImage(), SmushImages(), SparseColorImage(), SpliceImage(), SpreadImage(), StatisticImage(), SteganoImage(), StereoAnaglyphImage(), SwirlImage(), TextureImage(), TintImage(), TransformImage(), TransposeImage(), TransverseImage(), TrimImage(), UniqueImageColors(), VignetteImage(), and WaveImage().
MagickExport ImageInfo* CloneImageInfo (const ImageInfo * image_info)
Definition at line 922 of file image.c.
References AcquireImageInfo(), _ImageInfo::adjoin, _ImageInfo::antialias, _ImageInfo::background_color, _ImageInfo::blob, _ImageInfo::border_color, _ImageInfo::cache, _ImageInfo::channel, _ImageInfo::client_data, CloneImageOptions(), CloneString(), CloneStringInfo(), _ImageInfo::colorspace, _ImageInfo::compression, CopyMagickString(), _ImageInfo::debug, _ImageInfo::density, _ImageInfo::depth, _ImageInfo::dither, _ImageInfo::endian, _ImageInfo::extract, _ImageInfo::file, _ImageInfo::filename, _ImageInfo::font, _ImageInfo::fuzz, _ImageInfo::group, _ImageInfo::interlace, IsEventLogging(), _ImageInfo::length, _ImageInfo::magick, _ImageInfo::matte_color, MaxTextExtent, _ImageInfo::monochrome, _ImageInfo::number_scenes, _ImageInfo::orientation, _ImageInfo::page, _ImageInfo::ping, _ImageInfo::pointsize, _ImageInfo::preview_type, _ImageInfo::profile, _ImageInfo::progress_monitor, _ImageInfo::quality, ReferencePixelCache(), _ImageInfo::sampling_factor, _ImageInfo::scene, _ImageInfo::scenes, _ImageInfo::server_name, SetImageInfoBlob(), SetImageInfoFile(), _ImageInfo::signature, _ImageInfo::size, _ImageInfo::stream, _ImageInfo::temporary, _ImageInfo::texture, _ImageInfo::transparent_color, _ImageInfo::type, _ImageInfo::unique, _ImageInfo::units, _ImageInfo::verbose, _ImageInfo::view, and _ImageInfo::zero.
Referenced by BlobToImage(), GetImageRegistry(), ImagesToBlob(), ImageToBlob(), InjectImageBlob(), InvokeDelegate(), MontageImageList(), PingBlob(), PingImage(), PingImages(), ReadImage(), ReadImages(), ReadInlineImage(), ReadStream(), SetImageRegistry(), StreamImage(), WriteImage(), WriteImages(), WriteStream(), and WriteStreamImage().
MagickExport Image* DestroyImage (Image * image)
Definition at line 1012 of file image.c.
References _Image::ascii85, _Image::channel_map, _Image::colormap, _Image::debug, DestroyBlob(), DestroyImageArtifacts(), DestroyImagePixels(), DestroyImageProfiles(), DestroyImageProperties(), DestroyPixelChannelMap(), DestroySemaphoreInfo(), DestroyString(), _Image::directory, _Image::filename, _Image::geometry, GetMagickModule, LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, _Image::montage, _Image::reference_count, RelinquishMagickMemory(), _Image::semaphore, _Image::signature, TraceEvent, and UnlockSemaphoreInfo().
Referenced by AdaptiveBlurImage(), AdaptiveSharpenImage(), AdaptiveThresholdImage(), AddNoiseImage(), AppendImages(), BlueShiftImage(), BorderImage(), CharcoalImage(), ChopImage(), ClipImagePath(), CoalesceImages(), ColorizeImage(), ColorMatrixImage(), CombineImages(), CompareImages(), CompareImagesLayers(), CompositeImage(), CompositeLayers(), ConstituteImage(), CropImage(), CropToFitImage(), DeleteImageFromList(), DeskewImage(), DespeckleImage(), DestroyCacheView(), DestroyDrawInfo(), DestroyResampleFilter(), DestroyStreamInfo(), DisposeImages(), DistortImage(), DistortResizeImage(), DrawClipPath(), DrawPatternPath(), DrawPrimitive(), DrawStrokePolygon(), EnhanceImage(), EvaluateImages(), ExcerptImage(), ExtentImage(), FlipImage(), FloodfillPaintImage(), FlopImage(), ForwardFourierTransformImage(), FrameImage(), FxImage(), GetImageMask(), GetSimilarityMetric(), HuffmanEncodeImage(), IdentifyImage(), ImplodeImage(), InjectImageBlob(), IntegralRotateImage(), InterpolatePixelChannel(), InterpolatePixelChannels(), InterpolatePixelInfo(), InterpolativeResizeImage(), InverseFourierTransformImage(), MontageImageList(), MorphImages(), MorphologyApply(), MotionBlurImage(), NewMagickImage(), OilPaintImage(), OptimizeImageTransparency(), OptimizeLayerFrames(), PolaroidImage(), PolynomialImage(), PreviewImage(), RadialBlurImage(), ReadImage(), RenderPostscript(), ReplaceImageInList(), ReplaceImageInListReturnLast(), ResamplePixelColor(), ResizeImage(), RollImage(), RotateImage(), SampleImage(), ScaleImage(), SelectiveBlurImage(), SeparateImage(), SepiaToneImage(), SetImageInfo(), ShadeImage(), ShadowImage(), ShearImage(), ShearRotateImage(), SimilarityImage(), SketchImage(), SmushImages(), SparseColorImage(), SpliceImage(), SpreadImage(), StatisticImage(), SteganoImage(), StereoAnaglyphImage(), StreamImage(), SwirlImage(), TextureImage(), ThumbnailImage(), TintImage(), TransformImage(), TransposeImage(), TransverseImage(), UniqueImageColors(), UnsharpMaskImage(), VignetteImage(), and WaveImage().
MagickExport ImageInfo* DestroyImageInfo (ImageInfo * image_info)
Definition at line 1081 of file image.c.
References _ImageInfo::cache, _ImageInfo::debug, _ImageInfo::density, DestroyImageOptions(), DestroyPixelCache(), DestroyString(), DestroyStringInfo(), _ImageInfo::extract, _ImageInfo::filename, _ImageInfo::font, GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, _ImageInfo::page, _ImageInfo::profile, RelinquishMagickMemory(), _ImageInfo::sampling_factor, _ImageInfo::scenes, _ImageInfo::server_name, _ImageInfo::signature, _ImageInfo::size, _ImageInfo::texture, TraceEvent, and _ImageInfo::view.
Referenced by BlobToImage(), ClipImagePath(), DestroyRegistryNode(), DrawImage(), DrawPatternPath(), DrawPrimitive(), GlobExpression(), IdentifyImage(), ImagesToBlob(), ImageToBlob(), InjectImageBlob(), InvokeDelegate(), MontageImageList(), MontageImages(), PingBlob(), PingImage(), PingImages(), PreviewImage(), ReadImage(), ReadImages(), ReadInlineImage(), ReadStream(), RenderPostscript(), SetImageProperty(), SetImageType(), StreamImage(), WriteImage(), WriteImages(), WriteStream(), and WriteStreamImage().
MagickExport void DisassociateImageStream (Image * image)
Definition at line 1143 of file image.c.
References _Image::blob, _Image::debug, DetachBlob(), _Image::filename, GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, _Image::signature, and TraceEvent.
static void FlattenPixelInfo (const Image * image, const PixelInfo * p, const double alpha, const Quantum * q, const double beta, Quantum * composite) inline static
Definition at line 2089 of file image.c.
References AlphaPixelChannel, _PixelInfo::black, BlackPixelChannel, _PixelInfo::blue, BluePixelChannel, ClampToQuantum(), GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), _PixelInfo::green, GreenPixelChannel, MagickOver_(), PerceptibleReciprocal(), QuantumRange, QuantumScale, _PixelInfo::red, RedPixelChannel, and UndefinedPixelTrait.
Referenced by SetImageAlphaChannel().
MagickExport MagickBooleanType GetImageAlphaChannel (const Image * image)
Definition at line 1176 of file image.c.
References _Image::alpha_trait, BlendPixelTrait, _Image::debug, GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, _Image::signature, and TraceEvent.
MagickExport void GetImageInfo (ImageInfo * image_info)
Definition at line 1207 of file image.c.
References AcquireExceptionInfo(), _ImageInfo::adjoin, AllCompliance, _ImageInfo::antialias, _ImageInfo::background_color, BackgroundColor, _ImageInfo::border_color, BorderColor, _ImageInfo::channel, _ImageInfo::debug, DefaultChannels, DestroyExceptionInfo(), DestroyString(), _ImageInfo::dither, _ImageView::exception, GetEnvironmentValue(), GetMagickModule, _ImageInfo::interlace, IsEventLogging(), IsStringTrue(), LogMagickEvent(), MagickSignature, MagickTrue, _ImageInfo::matte_color, MatteColor, NoInterlace, _ImageInfo::quality, QueryColorCompliance(), ResetMagickMemory(), _ImageInfo::signature, _ImageInfo::synchronize, TraceEvent, _ImageInfo::transparent_color, TransparentColor, and UndefinedCompressionQuality.
Referenced by AcquireImageInfo().
MagickExport FILE* GetImageInfoFile (const ImageInfo * image_info)
Definition at line 1269 of file image.c.
References _ImageInfo::file.
MagickExport Image* GetImageMask (const Image * image, ExceptionInfo * exception)
Definition at line 1296 of file image.c.
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), CloneImage(), _Image::columns, _Image::debug, DestroyCacheView(), DestroyImage(), GetCacheViewAuthenticPixels(), GetCacheViewVirtualPixels(), GetMagickModule, GetPixelChannels(), GetPixelMask(), GRAYColorspace, LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, _Image::mask, _Image::rows, SetImageColorspace(), SetPixelGray(), _Image::signature, SyncCacheViewAuthenticPixels(), and TraceEvent.
MagickExport ssize_t GetImageReferenceCount (Image * image)
Definition at line 1385 of file image.c.
References _Image::debug, _Image::filename, GetMagickModule, LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, MagickSignature, _Image::reference_count, _Image::semaphore, _Image::signature, TraceEvent, and UnlockSemaphoreInfo().
Referenced by ModifyImage().
MagickExport VirtualPixelMethod GetImageVirtualPixelMethod (const Image * image)
Definition at line 1424 of file image.c.
References _Image::debug, _Image::filename, GetMagickModule, GetPixelCacheVirtualMethod(), LogMagickEvent(), MagickFalse, MagickSignature, _Image::signature, and TraceEvent.
Referenced by AccelerateConvolveImage(), AcquireResampleFilter(), AcquireVirtualCacheView(), and DistortResizeImage().
MagickExport size_t InterpretImageFilename (const ImageInfo * image_info, Image * image, const char * format, int value, char * filename, ExceptionInfo * exception)
Definition at line 1468 of file image.c.
References ConcatenateMagickString(), CopyMagickString(), FormatLocaleString(), GetImageArtifact(), GetImageOption(), GetImageProperty(), GetMagickProperty(), LocaleNCompare(), MagickFalse, MagickTrue, and MaxTextExtent.
Referenced by OpenBlob(), PingImages(), ReadImages(), and SetImageInfo().
MagickExport MagickBooleanType IsHighDynamicRangeImage (const Image * image, ExceptionInfo * exception)
Definition at line 1641 of file image.c.
References AcquireVirtualCacheView(), _Image::columns, _Image::debug, DestroyCacheView(), _Image::filename, GetCacheViewVirtualPixels(), GetMagickModule, GetPixelChannels(), GetPixelChannelTraits(), GetPixelMask(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, QuantumRange, _Image::rows, _Image::signature, TraceEvent, and UndefinedPixelTrait.
MagickExport MagickBooleanType IsImageObject (const Image * image)
Definition at line 1745 of file image.c.
References _Image::debug, GetMagickModule, GetNextImageInList(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, _Image::signature, and TraceEvent.
MagickExport MagickBooleanType IsTaintImage (const Image * image)
Definition at line 1782 of file image.c.
References CopyMagickString(), _Image::debug, _Image::filename, GetMagickModule, GetNextImageInList(), LocaleCompare(), LogMagickEvent(), _Image::magick, MagickFalse, MagickSignature, MagickTrue, MaxTextExtent, _Image::signature, _Image::taint, and TraceEvent.
Referenced by WriteImage().
MagickExport MagickBooleanType ModifyImage (Image ** image, ExceptionInfo * exception)
Definition at line 1835 of file image.c.
References CloneImage(), GetImageReferenceCount(), GetMagickModule, LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, TraceEvent, and UnlockSemaphoreInfo().
MagickExport Image* NewMagickImage (const ImageInfo * image_info, const size_t width, const size_t height, const PixelInfo * background, ExceptionInfo * exception)
Definition at line 1889 of file image.c.
References AcquireAuthenticCacheView(), AcquireImage(), _PixelInfo::alpha_trait, _Image::alpha_trait, _PixelInfo::colorspace, _Image::colorspace, _Image::columns, _ImageInfo::debug, _PixelInfo::depth, _Image::depth, DestroyCacheView(), DestroyImage(), _PixelInfo::fuzz, _Image::fuzz, GetMagickModule, GetPixelChannels(), _ImageView::image, LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, QueueCacheViewAuthenticPixels(), _Image::rows, SetPixelInfoPixel(), _ImageInfo::signature, SyncCacheViewAuthenticPixels(), and TraceEvent.
static Quantum PushColormapIndex (Image * image, const Quantum index, MagickBooleanType * range_exception) inline static
Definition at line 3590 of file image.c.
References MagickTrue.
Referenced by SyncImage().
MagickExport Image* ReferenceImage (Image * image)
Definition at line 1976 of file image.c.
References _Image::debug, GetMagickModule, LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, MagickSignature, _Image::reference_count, _Image::semaphore, _Image::signature, TraceEvent, and UnlockSemaphoreInfo().
Referenced by AcquireResampleFilter(), AcquireVirtualCacheView(), and CloneCacheView().
MagickExport MagickBooleanType ResetImagePage (Image * image, const char * page)
Definition at line 2012 of file image.c.
References AspectValue, _Image::columns, _Image::debug, _Image::filename, GetMagickModule, _RectangleInfo::height, HeightValue, LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, _Image::page, ParseAbsoluteGeometry(), _Image::rows, _Image::signature, TraceEvent, _RectangleInfo::width, WidthValue, _RectangleInfo::x, XValue, _RectangleInfo::y, and YValue.
MagickExport MagickBooleanType SetImageAlpha (Image * image, const Quantum alpha, ExceptionInfo * exception)
Definition at line 3129 of file image.c.
References AcquireAuthenticCacheView(), _Image::alpha_trait, BlendPixelTrait, _Image::columns, _Image::debug, DestroyCacheView(), GetCacheViewAuthenticPixels(), GetMagickModule, GetPixelChannels(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, _Image::rows, SetPixelAlpha(), _Image::signature, SyncCacheViewAuthenticPixels(), and TraceEvent.
Referenced by ChannelFxImage(), ColorizeImage(), DrawPrimitive(), FloodfillPaintImage(), FrameImage(), OpaquePaintImage(), SetImageAlphaChannel(), and SetImageBackgroundColor().
MagickExport MagickBooleanType SetImageAlphaChannel (Image * image, const AlphaChannelOption alpha_type, ExceptionInfo * exception)
Definition at line 2151 of file image.c.
MagickExport MagickBooleanType SetImageBackgroundColor (Image * image, ExceptionInfo * exception)
Definition at line 2348 of file image.c.
References AcquireAuthenticCacheView(), _PixelInfo::alpha_trait, _Image::alpha_trait, _Image::background_color, BlendPixelTrait, _Image::colorspace, _Image::columns, _Image::debug, DestroyCacheView(), DirectClass, GetMagickModule, GetPixelChannels(), IsGrayColorspace(), IsPixelInfoGray(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, OpaqueAlpha, QueueCacheViewAuthenticPixels(), RGBColorspace, _Image::rows, SetImageAlpha(), SetImageStorageClass(), SetPixelInfoPixel(), _Image::signature, SyncCacheViewAuthenticPixels(), TraceEvent, and TransformImageColorspace().
Referenced by AppendImages(), CoalesceImages(), CompareImagesLayers(), ConstituteImage(), CropImage(), DisposeImages(), DrawClipPath(), DrawPatternPath(), ExtentImage(), FloodfillPaintImage(), MergeImageLayers(), MontageImageList(), OptimizeImageTransparency(), OptimizeLayerFrames(), PolaroidImage(), SmushImages(), SpliceImage(), TrimImage(), and VignetteImage().
MagickExport ChannelType SetImageChannelMask (Image * image, const ChannelType channel_mask)
Definition at line 2431 of file image.c.
References _Image::channel_mask, and SetPixelChannelMask().
Referenced by AutoGammaImage(), DrawPrimitive(), InitializePixelChannelMap(), LevelImageColors(), MinMaxStretchImage(), SetImageType(), and ShadowImage().
MagickExport MagickBooleanType SetImageColor (Image * image, const PixelInfo * color, ExceptionInfo * exception)
Definition at line 2470 of file image.c.
References AcquireAuthenticCacheView(), _PixelInfo::alpha_trait, _Image::alpha_trait, _PixelInfo::colorspace, _Image::colorspace, _Image::columns, _Image::debug, _PixelInfo::depth, _Image::depth, DestroyCacheView(), _PixelInfo::fuzz, _Image::fuzz, GetMagickModule, GetPixelChannels(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, QueueCacheViewAuthenticPixels(), _Image::rows, SetPixelInfoPixel(), _Image::signature, SyncCacheViewAuthenticPixels(), and TraceEvent.
MagickExport MagickBooleanType SetImageExtent (Image * image, const size_t columns, const size_t rows, ExceptionInfo * exception)
Definition at line 2589 of file image.c.
References _Image::columns, MagickFalse, _Image::rows, and SyncImagePixelCache().
Referenced by PolaroidImage().
MagickExport MagickBooleanType SetImageInfo (ImageInfo * image_info, const unsigned int frames, ExceptionInfo * exception)
Definition at line 2633 of file image.c.
References AcquireExceptionInfo(), AcquireImage(), _ImageInfo::adjoin, _ImageInfo::affirm, CanonicalPath, CloneString(), CloseBlob(), CopyMagickString(), _ImageInfo::debug, DestroyExceptionInfo(), DestroyImage(), _ImageInfo::endian, ExplicitFormatType, ExtensionPath, _ImageInfo::extract, _Image::filename, _ImageInfo::filename, _MagickInfo::format_type, GetMagicInfo(), GetMagickAdjoin(), GetMagickEndianSupport(), GetMagickInfo(), GetMagickModule, GetMagicName(), GetPathComponent(), _ImageView::image, ImageToFile(), InterpretImageFilename(), IsBlobExempt(), IsBlobSeekable(), IsGeometry(), IsMagickConflict(), IsSceneGeometry(), LocaleCompare(), LocaleUpper(), LogMagickEvent(), _ImageInfo::magick, MagickFalse, MagickPath, MagickSignature, MagickTrue, MaxTextExtent, _ImageInfo::number_scenes, OpenBlob(), ReadBinaryBlobMode, ReadBlob(), ResetMagickMemory(), _ImageInfo::scene, _ImageInfo::scenes, SeekBlob(), SetImageInfoFile(), _ImageInfo::signature, StringToUnsignedLong(), SubimagePath, Swap, _ImageInfo::temporary, TraceEvent, UndefinedEndian, and UndefinedFormatType.
Referenced by BlobToImage(), GlobExpression(), ImagesToBlob(), ImageToBlob(), InvokeDelegate(), PingImages(), ReadImage(), ReadImages(), SetImageProperty(), WriteImage(), WriteImages(), and WriteStreamImage().
MagickExport void SetImageInfoBlob (ImageInfo * image_info, const void * blob, const size_t length)
Definition at line 2966 of file image.c.
References _ImageInfo::blob, _ImageInfo::debug, _ImageInfo::filename, GetMagickModule, _ImageInfo::length, LogMagickEvent(), MagickFalse, MagickSignature, _ImageInfo::signature, and TraceEvent.
Referenced by CloneImageInfo().
MagickExport void SetImageInfoFile (ImageInfo * image_info, FILE * file)
Definition at line 3002 of file image.c.
References _ImageInfo::debug, _ImageInfo::file, _ImageInfo::filename, GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, _ImageInfo::signature, and TraceEvent.
Referenced by CloneImageInfo(), InjectImageBlob(), and SetImageInfo().
MagickExport MagickBooleanType SetImageMask (Image * image, const Image * mask, ExceptionInfo * exception)
Definition at line 3040 of file image.c.
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), _Image::columns, _Image::debug, DestroyCacheView(), GetCacheViewAuthenticPixels(), GetCacheViewVirtualPixels(), GetMagickModule, GetPixelChannels(), GetPixelGray(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, _Image::mask, _Image::rows, SetPixelMask(), _Image::signature, SyncCacheViewAuthenticPixels(), and TraceEvent.
Referenced by ClipImagePath(), DrawClipPath(), and DrawImage().
MagickExport MagickBooleanType SetImageStorageClass (Image * image, const ClassType storage_class, ExceptionInfo * exception)
Definition at line 2553 of file image.c.
References _Image::storage_class, and SyncImagePixelCache().
Referenced by AcquireImageColormap(), AdaptiveBlurImage(), AdaptiveSharpenImage(), AdaptiveThresholdImage(), AddNoiseImage(), AnnotateImage(), AppendImages(), BilevelImage(), BlackThresholdImage(), BlueShiftImage(), ChannelFxImage(), ClipImagePath(), ClutImage(), ColorizeImage(), ColorMatrixImage(), CombineImages(), CompareImages(), CompositeImage(), ConsolidateCMYKImages(), DespeckleImage(), DistortImage(), DrawAffineImage(), DrawImage(), DuplexTransferImageViewIterator(), EnhanceImage(), EvaluateImage(), EvaluateImages(), ExtentImage(), FloodfillPaintImage(), FrameImage(), FunctionImage(), FxImage(), HaldClutImage(), HorizontalFilter(), ImplodeImage(), ImportImagePixels(), InterpolativeResizeImage(), MorphImages(), MorphologyApply(), MotionBlurImage(), OilPaintImage(), OpaquePaintImage(), OrderedPosterizeImage(), PlasmaImage(), PolynomialImage(), ProfileImage(), RadialBlurImage(), RaiseImage(), RandomThresholdImage(), ScaleImage(), SelectiveBlurImage(), SeparateImage(), SepiaToneImage(), SetCacheViewStorageClass(), SetImageAlphaChannel(), SetImageBackgroundColor(), SetImageType(), SetImageViewIterator(), ShadeImage(), ShearImage(), ShearRotateImage(), SimilarityImage(), SmushImages(), SparseColorImage(), SpliceImage(), SpreadImage(), sRGBTransformImage(), StatisticImage(), SteganoImage(), StereoAnaglyphImage(), SwirlImage(), TextureImage(), TintImage(), TransferImageViewIterator(), TransformsRGBImage(), TransparentPaintImage(), TransparentPaintImageChroma(), UniqueImageColors(), UpdateImageViewIterator(), VerticalFilter(), VignetteImage(), WaveImage(), and WhiteThresholdImage().
MagickExport VirtualPixelMethod SetImageVirtualPixelMethod (Image * image, const VirtualPixelMethod virtual_pixel_method, ExceptionInfo * exception)
Definition at line 3209 of file image.c.
References _Image::debug, _Image::filename, GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, SetPixelCacheVirtualMethod(), _Image::signature, and TraceEvent.
Referenced by DeskewImage(), DistortResizeImage(), RotateImage(), ShadowImage(), SyncImageSettings(), and TextureImage().
MagickExport Image* SmushImages (const Image * images, const MagickBooleanType stack, const ssize_t offset, ExceptionInfo * exception)
Definition at line 3396 of file image.c.
References _Image::alpha_trait, BlendPixelTrait, CloneImage(), _Image::columns, CompositeImage(), _Image::debug, DestroyImage(), DirectClass, _Image::filename, GetMagickModule, GetNextImageInList(), _Image::gravity, GravityAdjustGeometry(), _ImageView::image, LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, OverCompositeOp, _Image::previous, _Image::rows, SetGeometry(), SetImageBackgroundColor(), SetImageProgress(), SetImageStorageClass(), _ExceptionInfo::signature, _Image::signature, SmushImageTag, SmushXGap(), SmushYGap(), TraceEvent, _RectangleInfo::x, and _RectangleInfo::y.
static ssize_t SmushXGap (const Image * smush_image, const Image * images, const ssize_t offset, ExceptionInfo * exception) static
Definition at line 3254 of file image.c.
References AcquireVirtualCacheView(), _Image::columns, DestroyCacheView(), GetCacheViewVirtualPixels(), GetPixelAlpha(), _Image::gravity, GravityAdjustGeometry(), _Image::previous, _Image::rows, SetGeometry(), TransparentAlpha, and _RectangleInfo::y.
Referenced by SmushImages().
static ssize_t SmushYGap (const Image * smush_image, const Image * images, const ssize_t offset, ExceptionInfo * exception) static
Definition at line 3325 of file image.c.
References AcquireVirtualCacheView(), _Image::columns, DestroyCacheView(), GetCacheViewVirtualPixels(), GetPixelAlpha(), _Image::gravity, GravityAdjustGeometry(), _Image::previous, _Image::rows, SetGeometry(), TransparentAlpha, and _RectangleInfo::x.
Referenced by SmushImages().
MagickExport MagickBooleanType StripImage (Image * image, ExceptionInfo * exception)
Definition at line 3547 of file image.c.
References _Image::debug, DeleteImageProperty(), DestroyImageProfiles(), GetMagickModule, LogMagickEvent(), MagickFalse, SetImageArtifact(), and TraceEvent.
MagickExport MagickBooleanType SyncImage (Image * image, ExceptionInfo * exception)
Definition at line 3599 of file image.c.
References AcquireAuthenticCacheView(), _Image::colormap, _Image::columns, CorruptImageError, _Image::debug, DestroyCacheView(), DirectClass, _Image::filename, GetCacheViewAuthenticPixels(), GetMagickModule, GetPixelChannels(), GetPixelIndex(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, _Image::ping, PushColormapIndex(), _Image::rows, SetPixelInfoPixel(), _Image::signature, _Image::storage_class, SyncCacheViewAuthenticPixels(), ThrowMagickException(), and TraceEvent.
Referenced by AssignImageColors(), ClampImage(), Classify(), ClipImagePath(), PerceptibleImage(), sRGBTransformImage(), and TransformsRGBImage().
MagickExport MagickBooleanType SyncImageSettings (const ImageInfo * image_info, Image * image, ExceptionInfo * exception)
Definition at line 3715 of file image.c.
References AllCompliance, _Image::background_color, _Image::black_point_compensation, _ChromaticityInfo::blue_primary, _Image::border_color, _Image::chromaticity, _Image::compose, _Image::compression, _Image::debug, _Image::depth, DestroyString(), _Image::endian, _ImageView::exception, _Image::filename, _Image::filter, FormatLocaleString(), _Image::fuzz, GetImageOption(), GetMagickModule, GetNextImageOption(), GetPageGeometry(), _Image::gravity, _ChromaticityInfo::green_primary, _Image::image_info, _Image::interlace, _Image::interpolate, _Image::iterations, LogMagickEvent(), MagickBooleanOptions, MagickComposeOptions, MagickCompressOptions, MagickEndianOptions, MagickFalse, MagickFilterOptions, MagickGravityOptions, MagickIntentOptions, MagickInterlaceOptions, MagickInterpolateOptions, MagickOrientationOptions, MagickResolutionOptions, MagickSignature, MagickTrue, MagickTypeOptions, MagickVirtualPixelOptions, _Image::matte_color, MaxTextExtent, _Image::orientation, _Image::page, ParseAbsoluteGeometry(), ParseChannelOption(), ParseCommandOption(), ParseGeometry(), PixelsPerCentimeterResolution, PixelsPerInchResolution, _Image::quality, _ImageInfo::quality, QuantumRange, QueryColorCompliance(), _ChromaticityInfo::red_primary, _Image::rendering_intent, ResetImageOptionIterator(), _Image::resolution, _GeometryInfo::rho, _Image::scene, SetImageArtifact(), SetImageVirtualPixelMethod(), SetPixelChannelMask(), _GeometryInfo::sigma, SigmaValue, _Image::signature, _ImageInfo::signature, StringToDoubleInterval(), StringToUnsignedLong(), _Image::taint, _Image::tile_offset, TraceEvent, _Image::transparent_color, _Image::type, UndefinedCompressionQuality, UndefinedResolution, _Image::units, _ImageInfo::units, _ChromaticityInfo::white_point, _PrimaryInfo::x, _PointInfo::x, _PrimaryInfo::y, and _PointInfo::y.
Referenced by AcquireImage(), and SyncImagesSettings().
MagickExport MagickBooleanType SyncImagesSettings (ImageInfo * image_info, Image * images, ExceptionInfo * exception)
Definition at line 3696 of file image.c.
References _Image::debug, DeleteImageOption(), _Image::filename, GetMagickModule, GetNextImageInList(), _ImageView::image, LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, _Image::signature, _ImageInfo::signature, SyncImageSettings(), and TraceEvent.
Variable Documentation
const char BackgroundColor[] = "#ffffff"
Definition at line 106 of file image.c.
Referenced by AcquireImage(), GetImageInfo(), and QueryColorCompliance().
const char BorderColor[] = "#dfdfdf"
Definition at line 107 of file image.c.
Referenced by AcquireImage(), and GetImageInfo().
const double DefaultResolution = 72.0
Definition at line 122 of file image.c.
Referenced by DrawBoundingRectangles(), and RenderPostscript().
const char DefaultTileFrame[] = "15x15+3+3"
Definition at line 108 of file image.c.
Referenced by PreviewImage().
const char DefaultTileGeometry[] = "120x120+4+3>"
Definition at line 109 of file image.c.
Referenced by GetMontageInfo().
const char DefaultTileLabel[] = "%f\n%G\n%b"
Definition at line 110 of file image.c.
Referenced by PreviewImage().
const char ForegroundColor[] = "#000"
Definition at line 111 of file image.c.
const char LoadImagesTag[] = "Load/Images"
Definition at line 113 of file image.c.
const char LoadImageTag[] = "Load/Image"
Definition at line 112 of file image.c.
Referenced by HuffmanDecodeImage(), and HuffmanEncodeImage().
const char MatteColor[] = "#bdbdbd"
Definition at line 114 of file image.c.
Referenced by AcquireImage(), and GetImageInfo().
const char PSDensityGeometry[] = "72.0x72.0"
Definition at line 115 of file image.c.
const char PSPageGeometry[] = "612x792"
Definition at line 116 of file image.c.
const char SaveImagesTag[] = "Save/Images"
Definition at line 118 of file image.c.
const char SaveImageTag[] = "Save/Image"
Definition at line 117 of file image.c.
const char TransparentColor[] = "#00000000"
Definition at line 119 of file image.c.
Referenced by AcquireImage(), and GetImageInfo().