MagickCore: layer.c File Reference
layer.c File Reference
#include "MagickCore/studio.h"
#include "MagickCore/artifact.h"
#include "MagickCore/cache.h"
#include "MagickCore/channel.h"
#include "MagickCore/color.h"
#include "MagickCore/color-private.h"
#include "MagickCore/composite.h"
#include "MagickCore/effect.h"
#include "MagickCore/exception.h"
#include "MagickCore/exception-private.h"
#include "MagickCore/geometry.h"
#include "MagickCore/image.h"
#include "MagickCore/layer.h"
#include "MagickCore/list.h"
#include "MagickCore/memory_.h"
#include "MagickCore/monitor.h"
#include "MagickCore/monitor-private.h"
#include "MagickCore/option.h"
#include "MagickCore/pixel-accessor.h"
#include "MagickCore/property.h"
#include "MagickCore/profile.h"
#include "MagickCore/resource_.h"
#include "MagickCore/resize.h"
#include "MagickCore/statistic.h"
#include "MagickCore/string_.h"
#include "MagickCore/transform.h"
Macros
#define DupDispose ((DisposeType)9)
#define DelDispose ((DisposeType)8)
#define DEBUG_OPT_FRAME 0
#define MergeLayersTag "Merge/Layers"
Functions
static void ClearBounds (Image *image, RectangleInfo *bounds, ExceptionInfo *exception)
static MagickBooleanType IsBoundsCleared (const Image *image1, const Image *image2, RectangleInfo *bounds, ExceptionInfo *exception)
MagickExport Image * CoalesceImages (const Image *image, ExceptionInfo *exception)
MagickExport Image * DisposeImages (const Image *images, ExceptionInfo *exception)
static MagickBooleanType ComparePixels (const LayerMethod method, const PixelInfo *p, const PixelInfo *q)
static RectangleInfo CompareImagesBounds (const Image *image1, const Image *image2, const LayerMethod method, ExceptionInfo *exception)
MagickExport Image * CompareImagesLayers (const Image *image, const LayerMethod method, ExceptionInfo *exception)
static Image * OptimizeLayerFrames (const Image *image, const LayerMethod method, ExceptionInfo *exception)
MagickExport Image * OptimizeImageLayers (const Image *image, ExceptionInfo *exception)
MagickExport Image * OptimizePlusImageLayers (const Image *image, ExceptionInfo *exception)
MagickExport void OptimizeImageTransparency (const Image *image, ExceptionInfo *exception)
MagickExport void RemoveDuplicateLayers (Image **images, ExceptionInfo *exception)
MagickExport void RemoveZeroDelayLayers (Image **images, ExceptionInfo *exception)
static void CompositeCanvas (Image *destination, const CompositeOperator compose, Image *source, ssize_t x_offset, ssize_t y_offset, ExceptionInfo *exception)
MagickExport void CompositeLayers (Image *destination, const CompositeOperator compose, Image *source, const ssize_t x_offset, const ssize_t y_offset, ExceptionInfo *exception)
MagickExport Image * MergeImageLayers (Image *image, const LayerMethod method, ExceptionInfo *exception)
Macro Definition Documentation
#define DEBUG_OPT_FRAME 0
Definition at line 903 of file layer.c.
#define DelDispose ((DisposeType)8)
Definition at line 901 of file layer.c.
Referenced by OptimizeLayerFrames().
#define DupDispose ((DisposeType)9)
Definition at line 897 of file layer.c.
Referenced by OptimizeLayerFrames().
#define MergeLayersTag "Merge/Layers"
Referenced by MergeImageLayers().
Function Documentation
static void ClearBounds (Image * image, RectangleInfo * bounds, ExceptionInfo * exception) static
Definition at line 100 of file layer.c.
References _Image::alpha_trait, BlendPixelTrait, GetAuthenticPixels(), GetPixelChannels(), _RectangleInfo::height, MagickFalse, OpaqueAlphaChannel, SetImageAlphaChannel(), SetPixelAlpha(), SyncAuthenticPixels(), TransparentAlpha, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
Referenced by CoalesceImages(), DisposeImages(), OptimizeImageTransparency(), and OptimizeLayerFrames().
MagickExport Image* CoalesceImages (const Image * image, ExceptionInfo * exception)
Definition at line 229 of file layer.c.
References _Image::alpha_trait, BackgroundDispose, BlendPixelTrait, ClearBounds(), CloneImage(), CloneImageArtifacts(), CloneImageProfiles(), CloneImageProperties(), _Image::columns, CompositeImage(), CopyCompositeOp, _Image::debug, DestroyImage(), DestroyImageList(), _Image::dispose, _Image::filename, GetFirstImageInList(), GetMagickModule, GetNextImageInList(), GetPreviousImageInList(), _RectangleInfo::height, IsBoundsCleared(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, _Image::next, NoneDispose, OverCompositeOp, _Image::page, _Image::previous, PreviousDispose, _Image::rows, SetImageBackgroundColor(), _ExceptionInfo::signature, _Image::signature, TraceEvent, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
static RectangleInfo CompareImagesBounds (const Image * image1, const Image * image2, const LayerMethod method, ExceptionInfo * exception) static
Definition at line 589 of file layer.c.
References _Image::columns, ComparePixels(), GetPixelChannels(), GetPixelInfo(), GetPixelInfoPixel(), GetVirtualPixels(), _RectangleInfo::height, _Image::rows, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
Referenced by CompareImagesLayers(), OptimizeLayerFrames(), and RemoveDuplicateLayers().
MagickExport Image* CompareImagesLayers (const Image * image, const LayerMethod method, ExceptionInfo * exception)
Definition at line 746 of file layer.c.
References AcquireQuantumMemory(), _PixelInfo::alpha, AppendImageToList(), _Image::background_color, CloneImage(), CompareAnyLayer, CompareClearLayer, CompareImagesBounds(), CompareOverlayLayer, CompositeImage(), CopyCompositeOp, CropImage(), _Image::debug, DestroyImage(), DestroyImageList(), _Image::filename, GetFirstImageInList(), GetImageListLength(), GetMagickModule, GetNextImageInList(), _RectangleInfo::height, LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, _Image::page, RelinquishMagickMemory(), ResourceLimitError, SetImageBackgroundColor(), _ExceptionInfo::signature, _Image::signature, ThrowImageException, TraceEvent, TransparentAlpha, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
static MagickBooleanType ComparePixels (const LayerMethod method, const PixelInfo * p, const PixelInfo * q) static
Definition at line 521 of file layer.c.
References _PixelInfo::alpha, _PixelInfo::alpha_trait, BlendPixelTrait, CompareAnyLayer, CompareClearLayer, CompareOverlayLayer, IsFuzzyEquivalencePixelInfo(), MagickFalse, OpaqueAlpha, and QuantumRange.
Referenced by CompareImagesBounds().
static void CompositeCanvas (Image * destination, const CompositeOperator compose, Image * source, ssize_t x_offset, ssize_t y_offset, ExceptionInfo * exception) inline static
Definition at line 1751 of file layer.c.
References CompositeImage(), MagickTrue, _Image::page, _RectangleInfo::x, and _RectangleInfo::y.
Referenced by CompositeLayers().
MagickExport void CompositeLayers (Image * destination, const CompositeOperator compose, Image * source, const ssize_t x_offset, const ssize_t y_offset, ExceptionInfo * exception)
Definition at line 1761 of file layer.c.
References AppendImageToList(), CloneImage(), CompositeCanvas(), _Image::debug, _Image::delay, DestroyImage(), _Image::filename, GetLastImageInList(), GetMagickModule, GetNextImageInList(), _Image::iterations, LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, _Image::next, _ExceptionInfo::signature, _Image::signature, and TraceEvent.
MagickExport Image* DisposeImages (const Image * images, ExceptionInfo * exception)
Definition at line 376 of file layer.c.
References _PixelInfo::alpha, _Image::alpha_trait, AppendImageToList(), _Image::background_color, BackgroundDispose, BlendPixelTrait, ClearBounds(), CloneImage(), CloneImageArtifacts(), CloneImageProfiles(), CloneImageProperties(), _Image::columns, CompositeImage(), CopyCompositeOp, _Image::debug, DestroyImage(), DestroyImageList(), _Image::dispose, _Image::filename, GetFirstImageInList(), GetMagickModule, GetNextImageInList(), _RectangleInfo::height, LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, NewImageList(), NoneDispose, OverCompositeOp, _Image::page, PreviousDispose, _Image::rows, SetImageBackgroundColor(), _ExceptionInfo::signature, _Image::signature, TraceEvent, TransparentAlpha, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
static MagickBooleanType IsBoundsCleared (const Image * image1, const Image * image2, RectangleInfo * bounds, ExceptionInfo * exception) static
Definition at line 165 of file layer.c.
References GetPixelAlpha(), GetPixelChannels(), GetVirtualPixels(), _RectangleInfo::height, MagickFalse, MagickTrue, QuantumRange, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
Referenced by CoalesceImages(), and OptimizeLayerFrames().
MagickExport Image* MergeImageLayers (Image * image, const LayerMethod method, ExceptionInfo * exception)
Definition at line 1889 of file layer.c.
References CloneImage(), _Image::columns, _Image::compose, CompositeImage(), _Image::debug, _Image::dispose, _Image::filename, FlattenLayer, GetImageListLength(), GetMagickModule, GetNextImageInList(), _RectangleInfo::height, LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, MergeLayer, MergeLayersTag, MosaicLayer, _Image::page, _Image::rows, SetImageBackgroundColor(), SetImageProgress(), _ExceptionInfo::signature, _Image::signature, TraceEvent, TrimBoundsLayer, UndefinedDispose, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
Referenced by VignetteImage().
MagickExport Image* OptimizeImageLayers (const Image * image, ExceptionInfo * exception)
Definition at line 1383 of file layer.c.
References OptimizeImageLayer, and OptimizeLayerFrames().
MagickExport void OptimizeImageTransparency (const Image * image, ExceptionInfo * exception)
Definition at line 1453 of file layer.c.
References _PixelInfo::alpha, _Image::alpha_trait, _Image::background_color, BackgroundDispose, BlendPixelTrait, ChangeMaskCompositeOp, ClearBounds(), CloneImage(), _Image::columns, CompositeImage(), CopyCompositeOp, _Image::debug, DestroyImage(), _Image::dispose, _Image::filename, GetFirstImageInList(), GetMagickModule, GetNextImageInList(), _RectangleInfo::height, LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, NoneDispose, OverCompositeOp, _Image::page, PreviousDispose, _Image::rows, SetImageBackgroundColor(), _ExceptionInfo::signature, _Image::signature, TraceEvent, TransparentAlpha, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
static Image* OptimizeLayerFrames (const Image * image, const LayerMethod method, ExceptionInfo * exception) static
Definition at line 905 of file layer.c.
References AcquireExceptionInfo(), AcquireQuantumMemory(), _PixelInfo::alpha, AppendImageToList(), _Image::background_color, BackgroundDispose, ClearBounds(), CloneImage(), _Image::columns, CommandOptionToMnemonic(), CompareAnyLayer, CompareClearLayer, CompareImagesBounds(), CompareOverlayLayer, CropImage(), _Image::debug, _Image::delay, DelDispose, DestroyExceptionInfo(), DestroyImage(), DestroyImageList(), _Image::dispose, DupDispose, _Image::filename, FormatLocaleFile(), GetFirstImageInList(), GetImageListLength(), GetMagickModule, GetNextImageInList(), _RectangleInfo::height, IsBoundsCleared(), LogMagickEvent(), MagickDisposeOptions, MagickFalse, MagickSignature, MagickTrue, NewImageList(), NoneDispose, OptimizeImageLayer, OptimizeLayer, OptimizePlusLayer, OptionError, _Image::page, _Image::previous, PreviousDispose, RelinquishMagickMemory(), ResourceLimitError, _Image::rows, SetImageBackgroundColor(), _ExceptionInfo::signature, _Image::signature, ThrowImageException, _Image::ticks_per_second, TraceEvent, TransparentAlpha, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
Referenced by OptimizeImageLayers(), and OptimizePlusImageLayers().
MagickExport Image* OptimizePlusImageLayers (const Image * image, ExceptionInfo * exception)
Definition at line 1416 of file layer.c.
References OptimizeLayerFrames(), and OptimizePlusLayer.
MagickExport void RemoveDuplicateLayers (Image ** images, ExceptionInfo * exception)
Definition at line 1580 of file layer.c.
References _Image::columns, CompareAnyLayer, CompareImagesBounds(), _Image::delay, DeleteImageFromList(), GetFirstImageInList(), GetMagickModule, GetNextImageInList(), _Image::iterations, LogMagickEvent(), MagickFalse, MagickSignature, _Image::page, _Image::rows, _ExceptionInfo::signature, _Image::ticks_per_second, TraceEvent, _RectangleInfo::x, and _RectangleInfo::y.
MagickExport void RemoveZeroDelayLayers (Image ** images, ExceptionInfo * exception)
Definition at line 1661 of file layer.c.
References _Image::delay, DeleteImageFromList(), _Image::filename, GetFirstImageInList(), GetMagickModule, GetNextImageInList(), LogMagickEvent(), MagickFalse, MagickSignature, OptionWarning, _ExceptionInfo::signature, ThrowMagickException(), and TraceEvent.