MagickCore: list.c File Reference
list.c File Reference
#include "MagickCore/studio.h"
#include "MagickCore/blob.h"
#include "MagickCore/blob-private.h"
#include "MagickCore/exception.h"
#include "MagickCore/exception-private.h"
#include "MagickCore/list.h"
#include "MagickCore/memory_.h"
#include "MagickCore/string_.h"
Functions
MagickExport void AppendImageToList (Image **images, const Image *append)
MagickExport Image * CloneImageList (const Image *images, ExceptionInfo *exception)
MagickExport Image * CloneImages (const Image *images, const char *scenes, ExceptionInfo *exception)
MagickExport void DeleteImageFromList (Image **images)
MagickExport void DeleteImages (Image **images, const char *scenes, ExceptionInfo *exception)
MagickExport Image * DestroyImageList (Image *images)
MagickExport Image * DuplicateImages (Image *images, const size_t number_duplicates, const char *scenes, ExceptionInfo *exception)
MagickExport Image * GetFirstImageInList (const Image *images)
MagickExport Image * GetImageFromList (const Image *images, const ssize_t index)
MagickExport ssize_t GetImageIndexInList (const Image *images)
MagickExport size_t GetImageListLength (const Image *images)
MagickExport Image * GetLastImageInList (const Image *images)
MagickExport Image * GetNextImageInList (const Image *images)
MagickExport Image * GetPreviousImageInList (const Image *images)
MagickExport Image ** ImageListToArray (const Image *images, ExceptionInfo *exception)
MagickExport void InsertImageInList (Image **images, Image *insert)
MagickExport Image * NewImageList (void)
MagickExport void PrependImageToList (Image **images, Image *prepend)
MagickExport Image * RemoveImageFromList (Image **images)
MagickExport Image * RemoveFirstImageFromList (Image **images)
MagickExport Image * RemoveLastImageFromList (Image **images)
MagickExport void ReplaceImageInList (Image **images, Image *replace)
MagickExport void ReplaceImageInListReturnLast (Image **images, Image *replace)
MagickExport void ReverseImageList (Image **images)
MagickExport Image * SpliceImageIntoList (Image **images, const size_t length, const Image *splice)
MagickExport Image * SplitImageList (Image *images)
MagickExport void SyncImageList (Image *images)
MagickExport Image * SyncNextImageInList (const Image *images)
Function Documentation
MagickExport void AppendImageToList (Image ** images, const Image * append)
Definition at line 77 of file list.c.
References _Image::debug, _Image::filename, GetFirstImageInList(), GetLastImageInList(), GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, _Image::next, _Image::previous, _Image::signature, and TraceEvent.
Referenced by ChannelFxImage(), CloneImages(), CompareImagesLayers(), CompositeLayers(), ConsolidateCMYKImages(), CropImageToTiles(), DisposeImages(), DuplicateImages(), ForwardFourierTransformImage(), InsertImageInList(), MorphImages(), OptimizeLayerFrames(), PingImages(), PrependImageToList(), PreviewImage(), ReadImages(), SeparateImages(), SpliceImageIntoList(), and TransformImages().
MagickExport Image* CloneImageList (const Image * images, ExceptionInfo * exception)
Definition at line 125 of file list.c.
References CloneImage(), DestroyImageList(), MagickSignature, MagickTrue, _Image::next, _Image::previous, and _Image::signature.
Referenced by GetImageRegistry(), and SetImageRegistry().
MagickExport Image* CloneImages (const Image * images, const char * scenes, ExceptionInfo * exception)
Definition at line 199 of file list.c.
References AppendImageToList(), CloneImage(), _Image::debug, _Image::filename, GetFirstImageInList(), GetImageListLength(), GetMagickModule, GetNextImageInList(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, NewImageList(), _ExceptionInfo::signature, _Image::signature, and TraceEvent.
Referenced by DuplicateImages(), and ReadImage().
MagickExport void DeleteImageFromList (Image ** images)
Definition at line 291 of file list.c.
References DestroyImage(), and RemoveImageFromList().
Referenced by DeleteImages(), DestroyImageList(), RemoveDuplicateLayers(), and RemoveZeroDelayLayers().
MagickExport void DeleteImages (Image ** images, const char * scenes, ExceptionInfo * exception)
Definition at line 337 of file list.c.
References AcquireQuantumMemory(), DeleteImageFromList(), GetFirstImageInList(), GetImageListLength(), GetMagickModule, GetNextImageInList(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, RelinquishMagickMemory(), ResourceLimitError, _ExceptionInfo::signature, ThrowMagickException(), and TraceEvent.
MagickExport Image* DestroyImageList (Image * images)
Definition at line 443 of file list.c.
References _Image::debug, DeleteImageFromList(), _Image::filename, GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, _Image::signature, and TraceEvent.
Referenced by ChannelFxImage(), CloneImageList(), CoalesceImages(), CompareImagesLayers(), DestroyRegistryNode(), DisposeImages(), ForwardFourierTransformImage(), MontageImageList(), MorphImages(), OptimizeLayerFrames(), PreviewImage(), ReadImage(), and RelinquishImageRegistry().
MagickExport Image* DuplicateImages (Image * images, const size_t number_duplicates, const char * scenes, ExceptionInfo * exception)
Definition at line 491 of file list.c.
References AppendImageToList(), CloneImages(), _Image::debug, _Image::filename, GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, NewImageList(), _ExceptionInfo::signature, _Image::signature, and TraceEvent.
MagickExport Image* GetFirstImageInList (const Image * images)
Definition at line 542 of file list.c.
References MagickSignature, _Image::previous, and _Image::signature.
Referenced by AcquireFxInfo(), AppendImageToList(), BlobToImage(), ChannelFxImage(), CloneImages(), CoalesceImages(), CompareImagesLayers(), DeleteImages(), DisposeImages(), GetImageFromList(), ImageListToArray(), MontageImageList(), MorphImages(), OptimizeImageTransparency(), OptimizeLayerFrames(), ReadImage(), RemoveDuplicateLayers(), RemoveZeroDelayLayers(), ReplaceImageInList(), ReplaceImageInListReturnLast(), TransformImage(), and WriteImages().
MagickExport Image* GetImageFromList (const Image * images, const ssize_t index)
Definition at line 586 of file list.c.
References _Image::debug, _Image::filename, GetFirstImageInList(), GetLastImageInList(), GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, _Image::next, _Image::previous, _Image::signature, and TraceEvent.
Referenced by FxGetSymbol().
MagickExport ssize_t GetImageIndexInList (const Image * images)
Definition at line 645 of file list.c.
References MagickSignature, _Image::previous, and _Image::signature.
Referenced by FxGetSymbol(), GetMagickPropertyLetter(), and OpenPixelCache().
MagickExport size_t GetImageListLength (const Image * images)
Definition at line 681 of file list.c.
References _Image::debug, _Image::filename, GetLastImageInList(), GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, _Image::previous, _Image::signature, and TraceEvent.
Referenced by AcquireFxInfo(), CloneImages(), CompareImagesLayers(), ConsolidateCMYKImages(), DeleteImages(), DestroyFxInfo(), EvaluateImages(), FxGetSymbol(), GetMagickProperty(), GetMagickPropertyLetter(), IdentifyImage(), ImageListToArray(), ImagesToBlob(), InvokeDelegate(), MergeImageLayers(), MontageImageList(), MorphImages(), OptimizeLayerFrames(), PolynomialImage(), QuantizeImages(), ThumbnailImage(), and WriteImages().
MagickExport Image* GetLastImageInList (const Image * images)
Definition at line 719 of file list.c.
References MagickSignature, _Image::next, and _Image::signature.
Referenced by AppendImageToList(), ChannelFxImage(), CompositeLayers(), GetImageFromList(), GetImageListLength(), MorphImages(), ReplaceImageInList(), and ReplaceImageInListReturnLast().
MagickExport Image* GetNextImageInList (const Image * images)
Definition at line 753 of file list.c.
References _Image::debug, _Image::filename, GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, _Image::next, _Image::signature, and TraceEvent.
Referenced by AcquireNextImage(), AppendImages(), BlobToImage(), ChannelFxImage(), CloneImages(), CoalesceImages(), CombineImages(), CompareImagesLayers(), CompositeLayers(), ConsolidateCMYKImages(), DeleteImages(), DisposeImages(), EvaluateImages(), IdentifyImage(), InvokeDelegate(), IsImageObject(), IsTaintImage(), MergeImageLayers(), MontageImageList(), MorphImages(), OpenBlob(), OptimizeImageTransparency(), OptimizeLayerFrames(), PolynomialImage(), QuantizeImages(), ReadImage(), RemapImages(), RemoveDuplicateLayers(), RemoveZeroDelayLayers(), SmushImages(), SyncImagesSettings(), WriteImage(), and WriteImages().
MagickExport Image* GetPreviousImageInList (const Image * images)
Definition at line 785 of file list.c.
References MagickSignature, _Image::previous, and _Image::signature.
Referenced by CoalesceImages(), HuffmanEncodeImage(), IdentifyImage(), OpenBlob(), and WriteImage().
MagickExport Image** ImageListToArray (const Image * images, ExceptionInfo * exception)
Definition at line 826 of file list.c.
References AcquireQuantumMemory(), _Image::debug, _Image::filename, GetFirstImageInList(), GetImageListLength(), GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, _Image::next, ResourceLimitError, _Image::signature, ThrowMagickException(), and TraceEvent.
Referenced by MontageImageList(), and TransformImages().
MagickExport void InsertImageInList (Image ** images, Image * insert)
Definition at line 881 of file list.c.
References AppendImageToList(), _Image::debug, _Image::filename, GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, _Image::signature, SplitImageList(), and TraceEvent.
MagickExport Image* NewImageList (void)
Definition at line 917 of file list.c.
Referenced by CloneImage(), CloneImages(), ConsolidateCMYKImages(), CropImageToTiles(), DisposeImages(), DrawPatternPath(), DuplicateImages(), ForwardFourierTransformImage(), MontageImageList(), OptimizeLayerFrames(), PingImages(), PreviewImage(), ReadImage(), ReadImages(), ReadInlineImage(), SeparateImages(), and TransformImages().
MagickExport void PrependImageToList (Image ** images, Image * prepend)
Definition at line 946 of file list.c.
References AppendImageToList().
MagickExport Image* RemoveFirstImageFromList (Image ** images)
Definition at line 1041 of file list.c.
References GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, _Image::next, _Image::previous, and TraceEvent.
MagickExport Image* RemoveImageFromList (Image ** images)
Definition at line 982 of file list.c.
References GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, _Image::next, _Image::previous, and TraceEvent.
Referenced by DeleteImageFromList(), and SpliceImageIntoList().
MagickExport Image* RemoveLastImageFromList (Image ** images)
Definition at line 1092 of file list.c.
References GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, _Image::next, _Image::previous, and TraceEvent.
MagickExport void ReplaceImageInList (Image ** images, Image * replace)
Definition at line 1145 of file list.c.
References _Image::debug, DestroyImage(), _Image::filename, GetFirstImageInList(), GetLastImageInList(), GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, _Image::next, _Image::previous, _Image::signature, and TraceEvent.
Referenced by ReadImage().
MagickExport void ReplaceImageInListReturnLast (Image ** images, Image * replace)
Definition at line 1203 of file list.c.
References _Image::debug, DestroyImage(), _Image::filename, GetFirstImageInList(), GetLastImageInList(), GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, _Image::next, _Image::previous, _Image::signature, and TraceEvent.
MagickExport void ReverseImageList (Image ** images)
Definition at line 1254 of file list.c.
References GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, _Image::next, _Image::previous, and TraceEvent.
MagickExport Image* SpliceImageIntoList (Image ** images, const size_t length, const Image * splice)
Definition at line 1307 of file list.c.
References AppendImageToList(), GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, RemoveImageFromList(), _Image::signature, SplitImageList(), and TraceEvent.
MagickExport Image* SplitImageList (Image * images)
Definition at line 1358 of file list.c.
References _Image::next, and _Image::previous.
Referenced by InsertImageInList(), and SpliceImageIntoList().
MagickExport void SyncImageList (Image * images)
Definition at line 1390 of file list.c.
References MagickSignature, _Image::next, _Image::previous, _Image::scene, and _Image::signature.
MagickExport Image* SyncNextImageInList (const Image * images)
Definition at line 1436 of file list.c.
References _Image::blob, _Image::compression, DestroyBlob(), _Image::endian, MagickSignature, _Image::next, ReferenceBlob(), and _Image::signature.