MagickCore: locale_.h File Reference
locale_.h File Reference
#include "MagickCore/hashmap.h"
Data Structures
struct _LocaleInfo
Typedefs
typedef struct _LocaleInfo LocaleInfo
Functions
MagickExport char ** GetLocaleList (const char *, size_t *, ExceptionInfo *)
MagickExport const char * GetLocaleMessage (const char *)
MagickExport const LocaleInfo * GetLocaleInfo_ (const char *, ExceptionInfo *)
MagickExport const LocaleInfo ** GetLocaleInfoList (const char *, size_t *, ExceptionInfo *)
MagickExport double InterpretLocaleValue (const char *restrict, char **restrict)
MagickExport LinkedListInfo * DestroyLocaleOptions (LinkedListInfo *)
MagickExport LinkedListInfo * GetLocaleOptions (const char *, ExceptionInfo *)
MagickExport MagickBooleanType ListLocaleInfo (FILE *, ExceptionInfo *)
MagickExport ssize_t FormatLocaleFile (FILE *, const char *restrict,...) magick_attribute((__format__(__printf__
MagickExport ssize_t FormatLocaleString (char *restrict, const size_t, const char *restrict,...) magick_attribute((__format__(__printf__
Typedef Documentation
typedef struct _LocaleInfo LocaleInfo
Function Documentation
MagickExport LinkedListInfo* DestroyLocaleOptions (LinkedListInfo *)
MagickExport ssize_t FormatLocaleFile (FILE * , const char * restrict, ...)
MagickExport ssize_t FormatLocaleString (char * restrict, const size_t , const char * restrict, ...)
MagickExport const LocaleInfo* GetLocaleInfo_ (const char * , ExceptionInfo *)
MagickExport const LocaleInfo ** GetLocaleInfoList (const char * , size_t * , ExceptionInfo *)
Definition at line 493 of file locale.c.
References AcquireQuantumMemory(), GetLocaleInfo_(), GetMagickModule, GetNextValueInSplayTree(), GetNumberOfNodesInSplayTree(), GlobExpression(), locale_list, locale_semaphore, LocaleInfoCompare(), LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, MagickTrue, ResetSplayTreeIterator(), _LocaleInfo::stealth, _LocaleInfo::tag, TraceEvent, and UnlockSemaphoreInfo().
Referenced by ListLocaleInfo().
MagickExport char** GetLocaleList (const char * , size_t * , ExceptionInfo *)
Definition at line 588 of file locale.c.
References AcquireQuantumMemory(), ConstantString(), GetLocaleInfo_(), GetMagickModule, GetNextValueInSplayTree(), GetNumberOfNodesInSplayTree(), GlobExpression(), locale_list, locale_semaphore, LocaleTagCompare(), LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, MagickTrue, _LocaleInfo::stealth, _LocaleInfo::tag, TraceEvent, and UnlockSemaphoreInfo().
MagickExport const char* GetLocaleMessage (const char *)
Definition at line 653 of file locale.c.
References AcquireExceptionInfo(), DestroyExceptionInfo(), FormatLocaleString(), GetLocaleInfo_(), MaxTextExtent, and _LocaleInfo::message.
Referenced by GetLocaleExceptionMessage().
MagickExport LinkedListInfo * GetLocaleOptions (const char * , ExceptionInfo *)
Definition at line 701 of file locale.c.
References AcquireStringInfo(), AppendValueToLinkedList(), ConfigureFileToStringInfo(), CopyMagickString(), DestroyLinkedList(), FormatLocaleString(), GetConfigurePaths(), GetMagickModule, GetNextValueInLinkedList(), LocaleEvent, LogMagickEvent(), MaxTextExtent, NewLinkedList(), RelinquishMagickMemory(), ResetLinkedListIterator(), SetStringInfoDatum(), SetStringInfoLength(), SetStringInfoPath(), and TraceEvent.
Referenced by LoadLocaleLists().
MagickExport double InterpretLocaleValue (const char * restrict, char ** restrict)
MagickExport MagickBooleanType ListLocaleInfo (FILE * , ExceptionInfo *)
Definition at line 938 of file locale.c.
References FormatLocaleFile(), GetLocaleInfoList(), LocaleCompare(), MagickFalse, MagickTrue, _LocaleInfo::path, and RelinquishMagickMemory().