MagickCore: magick.c File Reference
magick.c File Reference
#include "MagickCore/studio.h"
#include "MagickCore/annotate-private.h"
#include "MagickCore/blob.h"
#include "MagickCore/blob-private.h"
#include "MagickCore/cache.h"
#include "MagickCore/cache-private.h"
#include "MagickCore/coder-private.h"
#include "MagickCore/client.h"
#include "MagickCore/color-private.h"
#include "MagickCore/configure-private.h"
#include "MagickCore/constitute-private.h"
#include "MagickCore/delegate-private.h"
#include "MagickCore/draw.h"
#include "MagickCore/exception.h"
#include "MagickCore/exception-private.h"
#include "MagickCore/locale-private.h"
#include "MagickCore/log-private.h"
#include "MagickCore/magic-private.h"
#include "MagickCore/magick.h"
#include "MagickCore/magick-private.h"
#include "MagickCore/memory_.h"
#include "MagickCore/mime-private.h"
#include "MagickCore/module.h"
#include "MagickCore/module-private.h"
#include "MagickCore/nt-base-private.h"
#include "MagickCore/random-private.h"
#include "MagickCore/registry.h"
#include "MagickCore/registry-private.h"
#include "MagickCore/resource_.h"
#include "MagickCore/resource-private.h"
#include "MagickCore/policy.h"
#include "MagickCore/policy-private.h"
#include "MagickCore/semaphore.h"
#include "MagickCore/semaphore-private.h"
#include "MagickCore/signature-private.h"
#include "MagickCore/splay-tree.h"
#include "MagickCore/string_.h"
#include "MagickCore/string-private.h"
#include "MagickCore/thread_.h"
#include "MagickCore/thread-private.h"
#include "MagickCore/type-private.h"
#include "MagickCore/token.h"
#include "MagickCore/utility.h"
#include "MagickCore/utility-private.h"
#include "MagickCore/xwindow-private.h"
Macros
#define MAGICKCORE_RETSIGTYPE void
#define SIG_DFL ((SignalHandler *) 0)
#define SIG_ERR ((SignalHandler *) -1)
#define SIGMAX 64
#define MagickPrecision 6
Typedefs
typedef MAGICKCORE_RETSIGTYPE SignalHandler (int)
Functions
static MagickBooleanType InitializeMagickList (ExceptionInfo *)
MagickExport DecodeImageHandler * GetImageDecoder (const MagickInfo *magick_info)
MagickExport EncodeImageHandler * GetImageEncoder (const MagickInfo *magick_info)
MagickExport MagickBooleanType GetImageMagick (const unsigned char *magick, const size_t length, char *format)
MagickExport MagickBooleanType GetMagickAdjoin (const MagickInfo *magick_info)
MagickExport MagickBooleanType GetMagickBlobSupport (const MagickInfo *magick_info)
MagickExport const char * GetMagickDescription (const MagickInfo *magick_info)
MagickExport MagickBooleanType GetMagickEndianSupport (const MagickInfo *magick_info)
MagickExport const MagickInfo * GetMagickInfo (const char *name, ExceptionInfo *exception)
static int MagickInfoCompare (const void *x, const void *y)
MagickExport const MagickInfo ** GetMagickInfoList (const char *pattern, size_t *number_formats, ExceptionInfo *exception)
static int MagickCompare (const void *x, const void *y)
MagickExport char ** GetMagickList (const char *pattern, size_t *number_formats, ExceptionInfo *exception)
MagickExport int GetMagickPrecision (void)
MagickExport MagickBooleanType GetMagickRawSupport (const MagickInfo *magick_info)
MagickExport MagickBooleanType GetMagickSeekableStream (const MagickInfo *magick_info)
MagickExport MagickStatusType GetMagickThreadSupport (const MagickInfo *magick_info)
static void * DestroyMagickNode (void *magick_info)
MagickPrivate MagickBooleanType IsMagickConflict (const char *magick)
MagickExport MagickBooleanType ListMagickInfo (FILE *file, ExceptionInfo *exception)
MagickExport MagickBooleanType IsMagickInstantiated (void)
MagickPrivate MagickBooleanType MagickComponentGenesis (void)
MagickPrivate void MagickComponentTerminus (void)
static SignalHandler * SetMagickSignalHandler (int signal_number, SignalHandler *handler)
static void MagickSignalHandler (int signal_number)
static SignalHandler * RegisterMagickSignalHandler (int signal_number)
MagickExport void MagickCoreGenesis (const char *path, const MagickBooleanType establish_signal_handlers)
MagickExport void MagickCoreTerminus (void)
MagickExport MagickInfo * RegisterMagickInfo (MagickInfo *magick_info)
MagickExport MagickInfo * SetMagickInfo (const char *name)
MagickExport int SetMagickPrecision (const int precision)
MagickExport MagickBooleanType UnregisterMagickInfo (const char *name)
Variables
static SemaphoreInfo * magick_semaphore = (SemaphoreInfo *) NULL
static SignalHandler * signal_handlers [SIGMAX] = { (SignalHandler *) NULL }
static SplayTreeInfo * magick_list = (SplayTreeInfo *) NULL
static volatile MagickBooleanType instantiate_magick = MagickFalse
static volatile MagickBooleanType instantiate_magickcore = MagickFalse
Macro Definition Documentation
#define MAGICKCORE_RETSIGTYPE void
Definition at line 93 of file magick.c.
#define MagickPrecision 6
Referenced by SetMagickPrecision().
#define SIG_DFL ((SignalHandler *) 0)
Definition at line 96 of file magick.c.
Referenced by RegisterMagickSignalHandler().
#define SIG_ERR ((SignalHandler *) -1)
Definition at line 99 of file magick.c.
Referenced by RegisterMagickSignalHandler(), and SetMagickSignalHandler().
#define SIGMAX 64
Definition at line 102 of file magick.c.
Typedef Documentation
typedef MAGICKCORE_RETSIGTYPE SignalHandler(int)
Definition at line 109 of file magick.c.
Function Documentation
static void* DestroyMagickNode (void * magick_info) static
Definition at line 789 of file magick.c.
References _MagickInfo::description, DestroyString(), _MagickInfo::module, _MagickInfo::name, _MagickInfo::note, RelinquishMagickMemory(), and _MagickInfo::version.
Referenced by InitializeMagickList().
MagickExport DecodeImageHandler* GetImageDecoder (const MagickInfo * magick_info)
Definition at line 155 of file magick.c.
References _MagickInfo::decoder, GetMagickModule, LogMagickEvent(), MagickSignature, _MagickInfo::signature, and TraceEvent.
Referenced by ReadImage().
MagickExport EncodeImageHandler* GetImageEncoder (const MagickInfo * magick_info)
Definition at line 185 of file magick.c.
References _MagickInfo::encoder, GetMagickModule, LogMagickEvent(), MagickSignature, _MagickInfo::signature, and TraceEvent.
Referenced by WriteImage().
MagickExport MagickBooleanType GetImageMagick (const unsigned char * magick, const size_t length, char * format)
Definition at line 222 of file magick.c.
References AcquireExceptionInfo(), CopyMagickString(), DestroyExceptionInfo(), GetMagickInfo(), GetMagickModule, GetNextValueInSplayTree(), LockSemaphoreInfo(), LogMagickEvent(), _MagickInfo::magick, magick_list, magick_semaphore, MagickFalse, MagickTrue, MaxTextExtent, _MagickInfo::name, ResetSplayTreeIterator(), TraceEvent, and UnlockSemaphoreInfo().
MagickExport MagickBooleanType GetMagickAdjoin (const MagickInfo * magick_info)
Definition at line 282 of file magick.c.
References _MagickInfo::adjoin, GetMagickModule, LogMagickEvent(), MagickSignature, _MagickInfo::signature, and TraceEvent.
Referenced by SetImageInfo().
MagickExport MagickBooleanType GetMagickBlobSupport (const MagickInfo * magick_info)
Definition at line 312 of file magick.c.
References _MagickInfo::blob_support, GetMagickModule, LogMagickEvent(), MagickSignature, _MagickInfo::signature, and TraceEvent.
Referenced by BlobToImage(), ImagesToBlob(), ImageToBlob(), and OpenBlob().
MagickExport const char* GetMagickDescription (const MagickInfo * magick_info)
Definition at line 343 of file magick.c.
References _MagickInfo::description, GetMagickModule, LogMagickEvent(), MagickSignature, _MagickInfo::signature, and TraceEvent.
Referenced by IdentifyImage().
MagickExport MagickBooleanType GetMagickEndianSupport (const MagickInfo * magick_info)
Definition at line 374 of file magick.c.
References _MagickInfo::endian_support, GetMagickModule, LogMagickEvent(), MagickSignature, _MagickInfo::signature, and TraceEvent.
Referenced by ReadImage(), SetImageInfo(), and WriteImage().
MagickExport const MagickInfo* GetMagickInfo (const char * name, ExceptionInfo * exception)
Definition at line 409 of file magick.c.
References GetNextValueInSplayTree(), InitializeMagickList(), instantiate_magick, LocaleCompare(), LockSemaphoreInfo(), magick_list, magick_semaphore, MagickFalse, _MagickInfo::name, OpenModule(), OpenModules(), ResetSplayTreeIterator(), and UnlockSemaphoreInfo().
Referenced by BlobToImage(), GetImageMagick(), GetMagickInfoList(), GetMagickList(), IdentifyImage(), ImagesToBlob(), ImageToBlob(), OpenBlob(), ReadImage(), SetImageInfo(), and WriteImage().
MagickExport const MagickInfo** GetMagickInfoList (const char * pattern, size_t * number_formats, ExceptionInfo * exception)
Definition at line 511 of file magick.c.
References AcquireQuantumMemory(), GetMagickInfo(), GetMagickModule, GetNextValueInSplayTree(), GetNumberOfNodesInSplayTree(), GlobExpression(), LockSemaphoreInfo(), LogMagickEvent(), magick_list, magick_semaphore, MagickFalse, MagickInfoCompare(), _MagickInfo::name, ResetSplayTreeIterator(), _MagickInfo::stealth, TraceEvent, and UnlockSemaphoreInfo().
Referenced by ListMagickInfo().
MagickExport char** GetMagickList (const char * pattern, size_t * number_formats, ExceptionInfo * exception)
Definition at line 604 of file magick.c.
References AcquireQuantumMemory(), ConstantString(), GetMagickInfo(), GetMagickModule, GetNextValueInSplayTree(), GetNumberOfNodesInSplayTree(), GlobExpression(), LockSemaphoreInfo(), LogMagickEvent(), magick_list, magick_semaphore, MagickCompare(), MagickFalse, _MagickInfo::name, ResetSplayTreeIterator(), _MagickInfo::stealth, TraceEvent, and UnlockSemaphoreInfo().
MagickExport int GetMagickPrecision (void)
Definition at line 666 of file magick.c.
References GetMagickModule, LogMagickEvent(), SetMagickPrecision(), and TraceEvent.
Referenced by AcquireResizeFilter(), FxEvaluateSubexpression(), GetMagickProperty(), InterpretImageProperties(), SetResampleFilter(), and ShowKernelInfo().
MagickExport MagickBooleanType GetMagickRawSupport (const MagickInfo * magick_info)
Definition at line 694 of file magick.c.
References GetMagickModule, LogMagickEvent(), MagickSignature, _MagickInfo::raw, _MagickInfo::signature, and TraceEvent.
Referenced by ReadImage(), and WriteImage().
MagickExport MagickBooleanType GetMagickSeekableStream (const MagickInfo * magick_info)
Definition at line 726 of file magick.c.
References GetMagickModule, LogMagickEvent(), MagickSignature, _MagickInfo::seekable_stream, _MagickInfo::signature, and TraceEvent.
Referenced by ReadImage(), and WriteImage().
MagickExport MagickStatusType GetMagickThreadSupport (const MagickInfo * magick_info)
Definition at line 757 of file magick.c.
References GetMagickModule, LogMagickEvent(), MagickSignature, _MagickInfo::signature, _MagickInfo::thread_support, and TraceEvent.
Referenced by ReadImage(), and WriteImage().
static MagickBooleanType InitializeMagickList (ExceptionInfo * exception) static
Definition at line 808 of file magick.c.
References AcquireSemaphoreInfo(), AddValueToSplayTree(), CompareSplayTreeString(), DestroyMagickNode(), DestroyString(), GetExceptionMessage(), GetModuleInfo(), instantiate_magick, LockSemaphoreInfo(), magick_list, magick_semaphore, MagickFalse, MagickTrue, _MagickInfo::name, NewSplayTree(), RegisterStaticModules(), ResourceLimitFatalError, SetMagickInfo(), _MagickInfo::stealth, ThrowFatalException, and UnlockSemaphoreInfo().
Referenced by GetMagickInfo().
MagickPrivate MagickBooleanType IsMagickConflict (const char * magick)
Definition at line 886 of file magick.c.
References MACIsMagickConflict(), MagickFalse, NTIsMagickConflict(), and VMSIsMagickConflict().
MagickExport MagickBooleanType IsMagickInstantiated (void)
Definition at line 1028 of file magick.c.
References instantiate_magick.
MagickExport MagickBooleanType ListMagickInfo (FILE * file, ExceptionInfo * exception)
Definition at line 924 of file magick.c.
References _ImageInfo::adjoin, _MagickInfo::blob_support, ClearMagickException(), ConcatenateMagickString(), CopyMagickString(), DestroyString(), FormatLocaleFile(), GetMagickInfoList(), MagickFalse, MagickTrue, MaxTextExtent, _MagickInfo::name, RelinquishMagickMemory(), and StringToList().
static int MagickCompare (const void * x, const void * y) static
Definition at line 589 of file magick.c.
References LocaleCompare().
Referenced by GetMagickList().
MagickPrivate MagickBooleanType MagickComponentGenesis (void)
Definition at line 1051 of file magick.c.
References AcquireSemaphoreInfo(), magick_semaphore, and MagickTrue.
Referenced by MagickCoreGenesis().
MagickPrivate void MagickComponentTerminus (void)
Definition at line 1075 of file magick.c.
References AcquireSemaphoreInfo(), DestroySemaphoreInfo(), DestroySplayTree(), instantiate_magick, LockSemaphoreInfo(), magick_list, magick_semaphore, MagickFalse, and UnlockSemaphoreInfo().
Referenced by MagickCoreTerminus().
MagickExport void MagickCoreGenesis (const char * path, const MagickBooleanType establish_signal_handlers)
Definition at line 1218 of file magick.c.
References AnnotateComponentGenesis(), CacheComponentGenesis(), CoderComponentGenesis(), ColorComponentGenesis(), ConfigureComponentGenesis(), ConstituteComponentGenesis(), CopyMagickString(), DelegateComponentGenesis(), DestroyString(), DirectorySeparator, GetEnvironmentValue(), GetExecutionPath(), GetPathComponent(), HeadPath, instantiate_magickcore, IsEventLogging(), IsPathAccessible(), LocaleComponentGenesis(), LockMagickMutex(), LogComponentGenesis(), MagicComponentGenesis(), MagickComponentGenesis(), MagickFalse, MagickTrue, MaxTextExtent, MimeComponentGenesis(), ModuleComponentGenesis(), PolicyComponentGenesis(), RandomComponentGenesis(), RegisterMagickSignalHandler(), RegistryComponentGenesis(), ResourceComponentGenesis(), SemaphoreComponentGenesis(), SetClientName(), SetClientPath(), SetLogEventMask(), signal_handlers, TailPath, TypeComponentGenesis(), UnlockMagickMutex(), and XComponentGenesis().
MagickExport void MagickCoreTerminus (void)
Definition at line 1361 of file magick.c.
References AnnotateComponentTerminus(), CacheComponentTerminus(), CoderComponentTerminus(), ColorComponentTerminus(), ConfigureComponentTerminus(), ConstituteComponentTerminus(), DelegateComponentTerminus(), instantiate_magickcore, LocaleComponentTerminus(), LockMagickMutex(), LogComponentTerminus(), MagicComponentTerminus(), MagickComponentTerminus(), MagickFalse, MimeComponentTerminus(), ModuleComponentTerminus(), PolicyComponentTerminus(), RandomComponentTerminus(), RegistryComponentTerminus(), ResourceComponentTerminus(), SemaphoreComponentTerminus(), TypeComponentTerminus(), UnlockMagickMutex(), and UnregisterStaticModules().
Referenced by DefaultFatalErrorHandler().
static int MagickInfoCompare (const void * x, const void * y) static
Definition at line 496 of file magick.c.
References LocaleCompare().
Referenced by GetMagickInfoList().
static void MagickSignalHandler (int signal_number) static
Definition at line 1147 of file magick.c.
References AsynchronousResourceComponentTerminus(), instantiate_magick, MagickFalse, SetMagickSignalHandler(), and signal_handlers.
Referenced by RegisterMagickSignalHandler().
MagickExport MagickInfo* RegisterMagickInfo (MagickInfo * magick_info)
Definition at line 1429 of file magick.c.
References AddValueToSplayTree(), GetMagickModule, LogMagickEvent(), magick_list, MagickFalse, MagickSignature, _MagickInfo::name, ResourceLimitFatalError, _MagickInfo::signature, ThrowFatalException, and TraceEvent.
static SignalHandler* RegisterMagickSignalHandler (int signal_number) static
Definition at line 1202 of file magick.c.
References ConfigureEvent, GetMagickModule, LogMagickEvent(), MagickSignalHandler(), SetMagickSignalHandler(), SIG_DFL, and SIG_ERR.
Referenced by MagickCoreGenesis().
MagickExport MagickInfo* SetMagickInfo (const char * name)
Definition at line 1475 of file magick.c.
References AcquireMagickMemory(), _MagickInfo::adjoin, _MagickInfo::blob_support, ConstantString(), DecoderThreadSupport, EncoderThreadSupport, GetMagickModule, LogMagickEvent(), MagickSignature, MagickTrue, _MagickInfo::name, ResetMagickMemory(), ResourceLimitFatalError, _MagickInfo::signature, _MagickInfo::thread_support, ThrowFatalException, and TraceEvent.
Referenced by InitializeMagickList().
MagickExport int SetMagickPrecision (const int precision)
Definition at line 1524 of file magick.c.
References DestroyString(), GetEnvironmentValue(), GetMagickModule, GetPolicyValue(), LogMagickEvent(), MagickPrecision, StringToInteger(), and TraceEvent.
Referenced by GetMagickPrecision().
static SignalHandler* SetMagickSignalHandler (int signal_number, SignalHandler * handler) static
Definition at line 1114 of file magick.c.
References SIG_ERR.
Referenced by MagickSignalHandler(), and RegisterMagickSignalHandler().
MagickExport MagickBooleanType UnregisterMagickInfo (const char * name)
Definition at line 1579 of file magick.c.
References DeleteNodeByValueFromSplayTree(), GetNextValueInSplayTree(), GetNumberOfNodesInSplayTree(), LocaleCompare(), LockSemaphoreInfo(), magick_list, magick_semaphore, MagickFalse, _MagickInfo::name, ResetSplayTreeIterator(), and UnlockSemaphoreInfo().
Variable Documentation
volatile MagickBooleanType instantiate_magick = MagickFalse static
Definition at line 124 of file magick.c.
Referenced by GetMagickInfo(), InitializeMagickList(), IsMagickInstantiated(), MagickComponentTerminus(), and MagickSignalHandler().
volatile MagickBooleanType instantiate_magickcore = MagickFalse static
Definition at line 125 of file magick.c.
Referenced by MagickCoreGenesis(), and MagickCoreTerminus().
SplayTreeInfo* magick_list = (SplayTreeInfo *) NULL static
Definition at line 121 of file magick.c.
Referenced by GetImageMagick(), GetMagickInfo(), GetMagickInfoList(), GetMagickList(), InitializeMagickList(), MagickComponentTerminus(), RegisterMagickInfo(), and UnregisterMagickInfo().
SemaphoreInfo* magick_semaphore = (SemaphoreInfo *) NULL static
Definition at line 115 of file magick.c.
Referenced by GetImageMagick(), GetMagickInfo(), GetMagickInfoList(), GetMagickList(), InitializeMagickList(), MagickComponentGenesis(), MagickComponentTerminus(), and UnregisterMagickInfo().
SignalHandler* signal_handlers[SIGMAX] = { (SignalHandler *) NULL } static
Definition at line 118 of file magick.c.
Referenced by MagickCoreGenesis(), and MagickSignalHandler().