MagickCore: magic.c File Reference
magic.c File Reference
#include "MagickCore/studio.h"
#include "MagickCore/blob.h"
#include "MagickCore/client.h"
#include "MagickCore/configure.h"
#include "MagickCore/configure-private.h"
#include "MagickCore/exception.h"
#include "MagickCore/exception-private.h"
#include "MagickCore/hashmap.h"
#include "MagickCore/magic.h"
#include "MagickCore/magic-private.h"
#include "MagickCore/memory_.h"
#include "MagickCore/semaphore.h"
#include "MagickCore/string_.h"
#include "MagickCore/string-private.h"
#include "MagickCore/token.h"
#include "MagickCore/utility.h"
#include "MagickCore/utility-private.h"
#include "MagickCore/xml-tree.h"
Data Structures
struct _MagicMapInfo
Macros
#define MagicFilename "magic.xml"
#define MagickString(magic) (const unsigned char *) (magic), sizeof(magic)-1
Typedefs
typedef struct _MagicMapInfo MagicMapInfo
Functions
static MagickBooleanType InitializeMagicList (ExceptionInfo *)
static MagickBooleanType LoadMagicLists (const char *, ExceptionInfo *)
MagickExport const MagicInfo * GetMagicInfo (const unsigned char *magic, const size_t length, ExceptionInfo *exception)
static int MagicInfoCompare (const void *x, const void *y)
MagickExport const MagicInfo ** GetMagicInfoList (const char *pattern, size_t *number_aliases, ExceptionInfo *exception)
static int MagicCompare (const void *x, const void *y)
MagickExport char ** GetMagicList (const char *pattern, size_t *number_aliases, ExceptionInfo *exception)
MagickExport const char * GetMagicName (const MagicInfo *magic_info)
MagickExport MagickBooleanType ListMagicInfo (FILE *file, ExceptionInfo *exception)
static MagickBooleanType LoadMagicList (const char *xml, const char *filename, const size_t depth, ExceptionInfo *exception)
MagickPrivate MagickBooleanType MagicComponentGenesis (void)
static void * DestroyMagicElement (void *magic_info)
MagickPrivate void MagicComponentTerminus (void)
Variables
static const MagicMapInfo MagicMap []
static LinkedListInfo * magic_list = (LinkedListInfo *) NULL
static SemaphoreInfo * magic_semaphore = (SemaphoreInfo *) NULL
static volatile MagickBooleanType instantiate_magic = MagickFalse
Macro Definition Documentation
#define MagicFilename "magic.xml"
Definition at line 64 of file magic.c.
Referenced by InitializeMagicList().
#define MagickString (magic) (const unsigned char *) (magic), sizeof(magic)-1
Definition at line 65 of file magic.c.
Typedef Documentation
typedef struct _MagicMapInfo MagicMapInfo
Function Documentation
static void* DestroyMagicElement (void * magic_info) static
Definition at line 1048 of file magic.c.
References DestroyString(), _MagicInfo::exempt, _MagicInfo::magic, MagickFalse, _MagicInfo::name, _MagicInfo::path, RelinquishMagickMemory(), and _MagicInfo::target.
Referenced by MagicComponentTerminus().
MagickExport const MagicInfo* GetMagicInfo (const unsigned char * magic, const size_t length, ExceptionInfo * exception)
Definition at line 250 of file magic.c.
References GetNextValueInLinkedList(), GetValueFromLinkedList(), InitializeMagicList(), InsertValueInLinkedList(), instantiate_magic, IsLinkedListEmpty(), _MagicInfo::length, LockSemaphoreInfo(), _MagicInfo::magic, magic_list, magic_semaphore, MagickFalse, _MagicInfo::offset, RemoveElementByValueFromLinkedList(), ResetLinkedListIterator(), and UnlockSemaphoreInfo().
Referenced by GetMagicInfoList(), GetMagicList(), and SetImageInfo().
MagickExport const MagicInfo** GetMagicInfoList (const char * pattern, size_t * number_aliases, ExceptionInfo * exception)
Definition at line 339 of file magic.c.
References AcquireQuantumMemory(), GetMagicInfo(), GetMagickModule, GetNextValueInLinkedList(), GetNumberOfElementsInLinkedList(), GlobExpression(), LockSemaphoreInfo(), LogMagickEvent(), magic_list, magic_semaphore, MagicInfoCompare(), MagickFalse, _MagicInfo::name, ResetLinkedListIterator(), _MagicInfo::stealth, TraceEvent, and UnlockSemaphoreInfo().
Referenced by ListMagicInfo().
MagickExport char** GetMagicList (const char * pattern, size_t * number_aliases, ExceptionInfo * exception)
Definition at line 434 of file magic.c.
References AcquireQuantumMemory(), ConstantString(), GetMagicInfo(), GetMagickModule, GetNextValueInLinkedList(), GetNumberOfElementsInLinkedList(), GlobExpression(), LockSemaphoreInfo(), LogMagickEvent(), magic_list, magic_semaphore, MagicCompare(), MagickFalse, _MagicInfo::name, ResetLinkedListIterator(), _MagicInfo::stealth, TraceEvent, and UnlockSemaphoreInfo().
MagickExport const char* GetMagicName (const MagicInfo * magic_info)
Definition at line 499 of file magic.c.
References GetMagickModule, LogMagickEvent(), MagickSignature, _MagicInfo::name, _MagicInfo::signature, and TraceEvent.
Referenced by SetImageInfo().
static MagickBooleanType InitializeMagicList (ExceptionInfo * exception) static
Definition at line 529 of file magic.c.
References AcquireSemaphoreInfo(), instantiate_magic, LoadMagicLists(), LockSemaphoreInfo(), magic_list, magic_semaphore, MagicFilename, MagickFalse, MagickTrue, and UnlockSemaphoreInfo().
Referenced by GetMagicInfo().
MagickExport MagickBooleanType ListMagicInfo (FILE * file, ExceptionInfo * exception)
Definition at line 572 of file magic.c.
References FormatLocaleFile(), GetMagicInfoList(), LocaleCompare(), MagickFalse, MagickTrue, _MagicInfo::offset, _MagicInfo::path, RelinquishMagickMemory(), and _MagicInfo::target.
static MagickBooleanType LoadMagicList (const char * xml, const char * filename, const size_t depth, ExceptionInfo * exception) static
Definition at line 665 of file magic.c.
References AcquireMagickMemory(), AcquireString(), AppendValueToLinkedList(), ConcatenateMagickString(), ConfigureError, ConfigureEvent, ConstantString(), CopyMagickString(), DirectorySeparator, _MagicInfo::exempt, FileToString(), GetMagickModule, GetMagickToken(), GetPathComponent(), HeadPath, IsStringTrue(), _MagicInfo::length, LocaleCompare(), LocaleNCompare(), LogMagickEvent(), _MagicInfo::magic, magic_list, MagickFalse, MagickSignature, MagickTrue, MaxTextExtent, _MagicInfo::name, NewLinkedList(), _MagicInfo::offset, _MagicInfo::path, RelinquishMagickMemory(), ResetMagickMemory(), ResourceLimitError, ResourceLimitFatalError, _MagicInfo::signature, _MagicInfo::stealth, StringToLong(), _MagicInfo::target, ThrowFatalException, ThrowFileException, and ThrowMagickException().
Referenced by LoadMagicLists().
static MagickBooleanType LoadMagicLists (const char * filename, ExceptionInfo * exception)
Definition at line 926 of file magic.c.
References AcquireMagickMemory(), AppendValueToLinkedList(), CopyMagickString(), DestroyConfigureOptions(), _MagicInfo::exempt, GetConfigureOptions(), GetMagickModule, GetNextValueInLinkedList(), GetStringInfoDatum(), GetStringInfoPath(), _MagicInfo::length, _MagicMapInfo::length, LoadMagicList(), _MagicInfo::magic, _MagicMapInfo::magic, magic_list, MagickFalse, MagickSignature, MagickTrue, MagicMap, MaxTextExtent, _MagicInfo::name, _MagicMapInfo::name, NewLinkedList(), _MagicInfo::offset, _MagicMapInfo::offset, _MagicInfo::path, ResetMagickMemory(), ResourceLimitError, _MagicInfo::signature, _MagicInfo::target, ThrowFileException, and ThrowMagickException().
Referenced by InitializeMagicList().
static int MagicCompare (const void * x, const void * y) static
Definition at line 419 of file magic.c.
References LocaleCompare().
Referenced by GetMagicList().
MagickPrivate MagickBooleanType MagicComponentGenesis (void)
Definition at line 1023 of file magic.c.
References AcquireSemaphoreInfo(), magic_semaphore, and MagickTrue.
Referenced by MagickCoreGenesis().
MagickPrivate void MagicComponentTerminus (void)
Definition at line 1069 of file magic.c.
References AcquireSemaphoreInfo(), DestroyLinkedList(), DestroyMagicElement(), DestroySemaphoreInfo(), instantiate_magic, LockSemaphoreInfo(), magic_list, magic_semaphore, MagickFalse, and UnlockSemaphoreInfo().
Referenced by MagickCoreTerminus().
static int MagicInfoCompare (const void * x, const void * y) static
Definition at line 322 of file magic.c.
References LocaleCompare().
Referenced by GetMagicInfoList().
Variable Documentation
volatile MagickBooleanType instantiate_magic = MagickFalse static
Definition at line 212 of file magic.c.
Referenced by GetMagicInfo(), InitializeMagicList(), and MagicComponentTerminus().
LinkedListInfo* magic_list = (LinkedListInfo *) NULL static
Definition at line 206 of file magic.c.
Referenced by GetMagicInfo(), GetMagicInfoList(), GetMagicList(), InitializeMagicList(), LoadMagicList(), LoadMagicLists(), and MagicComponentTerminus().
SemaphoreInfo* magic_semaphore = (SemaphoreInfo *) NULL static
Definition at line 209 of file magic.c.
Referenced by GetMagicInfo(), GetMagicInfoList(), GetMagicList(), InitializeMagicList(), MagicComponentGenesis(), and MagicComponentTerminus().
const MagicMapInfo MagicMap[] static
Definition at line 89 of file magic.c.
Referenced by LoadMagicLists().