MagickCore: matrix.c File Reference
matrix.c File Reference
#include "MagickCore/studio.h"
#include "MagickCore/matrix.h"
#include "MagickCore/matrix-private.h"
#include "MagickCore/pixel-private.h"
#include "MagickCore/memory_.h"
Macros
#define GaussJordanSwap(x, y)
Functions
MagickExport double ** AcquireMagickMatrix (const size_t number_rows, const size_t size)
MagickPrivate MagickBooleanType GaussJordanElimination (double **matrix, double **vectors, const size_t rank, const size_t number_vectors)
MagickPrivate void LeastSquaresAddTerms (double **matrix, double **vectors, const double *terms, const double *results, const size_t rank, const size_t number_vectors)
MagickExport double ** RelinquishMagickMatrix (double **matrix, const size_t number_rows)
Macro Definition Documentation
#define GaussJordanSwap (x, y)
Value:
{ \
  if ((x) != (y)) \
    { \
      (x)+=(y); \
      (y)=(x)-(y); \
      (x)=(x)-(y); \
    } \
}
Referenced by GaussJordanElimination().
Function Documentation
MagickExport double** AcquireMagickMatrix (const size_t number_rows, const size_t size)
Definition at line 82 of file matrix.c.
References AcquireQuantumMemory(), and RelinquishMagickMemory().
Referenced by GenerateCoefficients().
MagickPrivate MagickBooleanType GaussJordanElimination (double ** matrix, double ** vectors, const size_t rank, const size_t number_vectors)
Definition at line 191 of file matrix.c.
References AcquireQuantumMemory(), GaussJordanSwap, MagickFalse, MagickTrue, PerceptibleReciprocal(), RelinquishMagickMemory(), and ResetMagickMemory().
Referenced by GenerateCoefficients().
MagickPrivate void LeastSquaresAddTerms (double ** matrix, double ** vectors, const double * terms, const double * results, const size_t rank, const size_t number_vectors)
Definition at line 371 of file matrix.c.
Referenced by GenerateCoefficients().
MagickExport double** RelinquishMagickMatrix (double ** matrix, const size_t number_rows)
Definition at line 415 of file matrix.c.
References RelinquishMagickMemory().
Referenced by GenerateCoefficients().