MagickCore: mime.c File Reference
mime.c File Reference
#include "MagickCore/studio.h"
#include "MagickCore/blob.h"
#include "MagickCore/client.h"
#include "MagickCore/configure.h"
#include "MagickCore/configure-private.h"
#include "MagickCore/exception.h"
#include "MagickCore/exception-private.h"
#include "MagickCore/hashmap.h"
#include "MagickCore/memory_.h"
#include "MagickCore/mime.h"
#include "MagickCore/mime-private.h"
#include "MagickCore/option.h"
#include "MagickCore/semaphore.h"
#include "MagickCore/string_.h"
#include "MagickCore/token.h"
#include "MagickCore/utility.h"
#include "MagickCore/utility-private.h"
#include "MagickCore/xml-tree.h"
#include "MagickCore/xml-tree-private.h"
Data Structures
struct _MimeInfo
Macros
#define MimeFilename "mime.xml"
Functions
static MagickBooleanType InitializeMimeList (ExceptionInfo *)
MagickExport const MimeInfo * GetMimeInfo (const char *filename, const unsigned char *magic, const size_t length, ExceptionInfo *exception)
static int MimeInfoCompare (const void *x, const void *y)
MagickExport const MimeInfo ** GetMimeInfoList (const char *pattern, size_t *number_aliases, ExceptionInfo *exception)
static int MimeCompare (const void *x, const void *y)
MagickExport char ** GetMimeList (const char *pattern, size_t *number_aliases, ExceptionInfo *exception)
MagickExport const char * GetMimeDescription (const MimeInfo *mime_info)
MagickExport const char * GetMimeType (const MimeInfo *mime_info)
MagickExport MagickBooleanType ListMimeInfo (FILE *file, ExceptionInfo *exception)
static MagickBooleanType LoadMimeList (const char *xml, const char *filename, const size_t depth, ExceptionInfo *exception)
MagickExport MagickBooleanType LoadMimeLists (const char *filename, ExceptionInfo *exception)
MagickExport char * MagickToMime (const char *magick)
MagickPrivate MagickBooleanType MimeComponentGenesis (void)
static void * DestroyMimeElement (void *mime_info)
MagickPrivate void MimeComponentTerminus (void)
Variables
static const char * MimeMap
static LinkedListInfo * mime_list = (LinkedListInfo *) NULL
static SemaphoreInfo * mime_semaphore = (SemaphoreInfo *) NULL
static volatile MagickBooleanType instantiate_mime = MagickFalse
Macro Definition Documentation
#define MimeFilename "mime.xml"
Definition at line 63 of file mime.c.
Referenced by InitializeMimeList().
Function Documentation
static void* DestroyMimeElement (void * mime_info) static
Definition at line 1082 of file mime.c.
References _MimeInfo::description, DestroyString(), _MimeInfo::magic, _MimeInfo::path, _MimeInfo::pattern, RelinquishMagickMemory(), and _MimeInfo::type.
Referenced by MimeComponentTerminus().
MagickExport const char* GetMimeDescription (const MimeInfo * mime_info)
Definition at line 545 of file mime.c.
References _MimeInfo::description, GetMagickModule, LogMagickEvent(), MagickSignature, _MimeInfo::signature, and TraceEvent.
MagickExport const MimeInfo* GetMimeInfo (const char * filename, const unsigned char * magic, const size_t length, ExceptionInfo * exception)
Definition at line 165 of file mime.c.
References ByteData, _MimeInfo::data_type, _MimeInfo::endian, _MimeInfo::extent, GetNextValueInLinkedList(), GetValueFromLinkedList(), GlobExpression(), InitializeMimeList(), InsertValueInLinkedList(), instantiate_mime, IsLinkedListEmpty(), _MimeInfo::length, LockSemaphoreInfo(), LongData, LSBEndian, _MimeInfo::magic, MagickFalse, _MimeInfo::mask, mime_list, mime_semaphore, MSBEndian, _MimeInfo::offset, _MimeInfo::pattern, _MimeInfo::priority, RemoveElementByValueFromLinkedList(), ResetLinkedListIterator(), ShortData, StringData, UndefinedEndian, UnlockSemaphoreInfo(), and _MimeInfo::value.
Referenced by GetMimeInfoList(), GetMimeList(), and MagickToMime().
MagickExport const MimeInfo** GetMimeInfoList (const char * pattern, size_t * number_aliases, ExceptionInfo * exception)
Definition at line 385 of file mime.c.
References AcquireQuantumMemory(), GetMagickModule, GetMimeInfo(), GetNextValueInLinkedList(), GetNumberOfElementsInLinkedList(), GlobExpression(), LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, mime_list, mime_semaphore, MimeInfoCompare(), ResetLinkedListIterator(), _MimeInfo::stealth, TraceEvent, _MimeInfo::type, and UnlockSemaphoreInfo().
Referenced by ListMimeInfo().
MagickExport char** GetMimeList (const char * pattern, size_t * number_aliases, ExceptionInfo * exception)
Definition at line 480 of file mime.c.
References AcquireQuantumMemory(), ConstantString(), GetMagickModule, GetMimeInfo(), GetNextValueInLinkedList(), GetNumberOfElementsInLinkedList(), GlobExpression(), LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, mime_list, mime_semaphore, MimeCompare(), ResetLinkedListIterator(), _MimeInfo::stealth, TraceEvent, _MimeInfo::type, and UnlockSemaphoreInfo().
MagickExport const char* GetMimeType (const MimeInfo * mime_info)
Definition at line 575 of file mime.c.
References GetMagickModule, LogMagickEvent(), MagickSignature, _MimeInfo::signature, TraceEvent, and _MimeInfo::type.
Referenced by MagickToMime().
static MagickBooleanType InitializeMimeList (ExceptionInfo * exception) static
Definition at line 605 of file mime.c.
References AcquireSemaphoreInfo(), instantiate_mime, LoadMimeLists(), LockSemaphoreInfo(), MagickFalse, MagickTrue, mime_list, mime_semaphore, MimeFilename, and UnlockSemaphoreInfo().
Referenced by GetMimeInfo().
MagickExport MagickBooleanType ListMimeInfo (FILE * file, ExceptionInfo * exception)
Definition at line 648 of file mime.c.
References FormatLocaleFile(), GetMimeInfoList(), MagickFalse, MagickTrue, _MimeInfo::path, and RelinquishMagickMemory().
static MagickBooleanType LoadMimeList (const char * xml, const char * filename, const size_t depth, ExceptionInfo * exception) static
Definition at line 738 of file mime.c.
References AcquireMagickMemory(), AcquireString(), AppendValueToLinkedList(), ConcatenateMagickString(), ConfigureError, ConfigureEvent, ConstantString(), CopyMagickString(), _MimeInfo::data_type, _MimeInfo::description, DestroyString(), DestroyXMLTree(), DirectorySeparator, _MimeInfo::endian, _MimeInfo::extent, FileToString(), GetMagickModule, GetNextXMLTreeTag(), GetPathComponent(), GetXMLTreeAttribute(), GetXMLTreeChild(), HeadPath, IsStringTrue(), _MimeInfo::length, LogMagickEvent(), _MimeInfo::magic, MagickDataTypeOptions, MagickEndianOptions, MagickFalse, MagickSignature, MagickTrue, _MimeInfo::mask, MaxTextExtent, mime_list, NewLinkedList(), NewXMLTree(), _MimeInfo::offset, ParseCommandOption(), _MimeInfo::path, _MimeInfo::pattern, _MimeInfo::priority, ResetMagickMemory(), ResourceLimitError, ResourceLimitFatalError, _MimeInfo::signature, _MimeInfo::stealth, StringData, SubstituteString(), ThrowFatalException, ThrowFileException, ThrowMagickException(), _MimeInfo::type, and _MimeInfo::value.
Referenced by LoadMimeLists().
MagickExport MagickBooleanType LoadMimeLists (const char * filename, ExceptionInfo * exception)
Definition at line 956 of file mime.c.
References ClearMagickException(), DestroyConfigureOptions(), GetConfigureOptions(), GetNextValueInLinkedList(), GetStringInfoDatum(), GetStringInfoPath(), IsLinkedListEmpty(), LoadMimeList(), MagickFalse, MagickTrue, mime_list, and MimeMap.
Referenced by InitializeMimeList().
MagickExport char* MagickToMime (const char * magick)
Definition at line 1015 of file mime.c.
References AcquireExceptionInfo(), ConstantString(), DestroyExceptionInfo(), FormatLocaleString(), GetMimeInfo(), GetMimeType(), LocaleLower(), and MaxTextExtent.
static int MimeCompare (const void * x, const void * y) static
Definition at line 465 of file mime.c.
Referenced by GetMimeList().
MagickPrivate MagickBooleanType MimeComponentGenesis (void)
Definition at line 1057 of file mime.c.
References AcquireSemaphoreInfo(), MagickTrue, and mime_semaphore.
Referenced by MagickCoreGenesis().
MagickPrivate void MimeComponentTerminus (void)
Definition at line 1102 of file mime.c.
References AcquireSemaphoreInfo(), DestroyLinkedList(), DestroyMimeElement(), DestroySemaphoreInfo(), instantiate_mime, LockSemaphoreInfo(), MagickFalse, mime_list, mime_semaphore, and UnlockSemaphoreInfo().
Referenced by MagickCoreTerminus().
static int MimeInfoCompare (const void * x, const void * y) static
Definition at line 368 of file mime.c.
Referenced by GetMimeInfoList().
Variable Documentation
volatile MagickBooleanType instantiate_mime = MagickFalse static
Definition at line 124 of file mime.c.
Referenced by GetMimeInfo(), InitializeMimeList(), and MimeComponentTerminus().
LinkedListInfo* mime_list = (LinkedListInfo *) NULL static
Definition at line 118 of file mime.c.
Referenced by GetMimeInfo(), GetMimeInfoList(), GetMimeList(), InitializeMimeList(), LoadMimeList(), LoadMimeLists(), and MimeComponentTerminus().
SemaphoreInfo* mime_semaphore = (SemaphoreInfo *) NULL static
Definition at line 121 of file mime.c.
Referenced by GetMimeInfo(), GetMimeInfoList(), GetMimeList(), InitializeMimeList(), MimeComponentGenesis(), and MimeComponentTerminus().
const char* MimeMap static
Initial value:
= (char *)
    "<?xml version=\"1.0\"?>"
    "<mimemap>"
    "</mimemap>"
Definition at line 112 of file mime.c.
Referenced by LoadMimeLists().