MagickCore: mime-private.h File Reference
mime-private.h File Reference
Enumerations
enum DataType {
UndefinedData, StringData, ByteData, ShortData,
LongData
}
Functions
MagickPrivate MagickBooleanType MimeComponentGenesis (void)
MagickPrivate void MimeComponentTerminus (void)
Enumeration Type Documentation
enum DataType
Enumerator
UndefinedData
StringData
ByteData
ShortData
LongData
Definition at line 25 of file mime-private.h.
Function Documentation
MagickPrivate MagickBooleanType MimeComponentGenesis (void)
Definition at line 1057 of file mime.c.
References AcquireSemaphoreInfo(), MagickTrue, and mime_semaphore.
Referenced by MagickCoreGenesis().
MagickPrivate void MimeComponentTerminus (void)
Definition at line 1102 of file mime.c.
References AcquireSemaphoreInfo(), DestroyLinkedList(), DestroyMimeElement(), DestroySemaphoreInfo(), instantiate_mime, LockSemaphoreInfo(), MagickFalse, mime_list, mime_semaphore, and UnlockSemaphoreInfo().
Referenced by MagickCoreTerminus().