MagickCore: module.h File Reference
module.h File Reference
#include <time.h>
#include "MagickCore/version.h"
Data Structures
struct _ModuleInfo
Macros
#define MagickImageCoderSignature
#define MagickImageFilterSignature
Typedefs
typedef struct _ModuleInfo ModuleInfo
typedef size_t ImageFilterHandler (Image **, const int, const char **, ExceptionInfo *)
Enumerations
enum MagickModuleType { MagickImageCoderModule, MagickImageFilterModule }
Functions
MagickExport char ** GetModuleList (const char *, const MagickModuleType, size_t *, ExceptionInfo *)
MagickExport const ModuleInfo ** GetModuleInfoList (const char *, size_t *, ExceptionInfo *)
MagickExport MagickBooleanType InvokeDynamicImageFilter (const char *, Image **, const int, const char **, ExceptionInfo *)
MagickExport MagickBooleanType ListModuleInfo (FILE *, ExceptionInfo *)
MagickExport ModuleInfo * GetModuleInfo (const char *, ExceptionInfo *)
MagickExport void DestroyModuleList (void)
MagickExport void RegisterStaticModules (void)
MagickExport void UnregisterStaticModules (void)
Macro Definition Documentation
#define MagickImageCoderSignature
Value:
((size_t) \
  (((MagickLibVersion) << 8) | MAGICKCORE_QUANTUM_DEPTH))
Definition at line 28 of file module.h.
#define MagickImageFilterSignature
Value:
((size_t) \
  (((MagickLibVersion) << 8) | MAGICKCORE_QUANTUM_DEPTH))
Definition at line 30 of file module.h.
Referenced by InvokeDynamicImageFilter().
Typedef Documentation
typedef size_t ImageFilterHandler(Image **, const int, const char **, ExceptionInfo *)
Definition at line 63 of file module.h.
typedef struct _ModuleInfo ModuleInfo
Enumeration Type Documentation
enum MagickModuleType
Enumerator
MagickImageCoderModule
MagickImageFilterModule
Definition at line 33 of file module.h.
Function Documentation
MagickExport void DestroyModuleList (void)
MagickExport ModuleInfo* GetModuleInfo (const char * , ExceptionInfo *)
Referenced by InitializeMagickList().
MagickExport const ModuleInfo** GetModuleInfoList (const char * , size_t * , ExceptionInfo *)
MagickExport char** GetModuleList (const char * , const MagickModuleType , size_t * , ExceptionInfo *)
MagickExport MagickBooleanType InvokeDynamicImageFilter (const char * , Image ** , const int , const char ** , ExceptionInfo *)
MagickExport MagickBooleanType ListModuleInfo (FILE * , ExceptionInfo *)
MagickExport void RegisterStaticModules (void)
Referenced by InitializeMagickList().
MagickExport void UnregisterStaticModules (void)
Definition at line 344 of file static.c.
References UnregisterAAIImage(), UnregisterARTImage(), UnregisterAVSImage(), UnregisterBMPImage(), UnregisterBRAILLEImage(), UnregisterCALSImage(), UnregisterCAPTIONImage(), UnregisterCINImage(), UnregisterCIPImage(), UnregisterCLIPBOARDImage(), UnregisterCLIPImage(), UnregisterCMYKImage(), UnregisterCUTImage(), UnregisterDCMImage(), UnregisterDDSImage(), UnregisterDEBUGImage(), UnregisterDIBImage(), UnregisterDJVUImage(), UnregisterDNGImage(), UnregisterDPSImage(), UnregisterDPXImage(), UnregisterEMFImage(), UnregisterEPTImage(), UnregisterEXRImage(), UnregisterFAXImage(), UnregisterFDImage(), UnregisterFITSImage(), UnregisterFPXImage(), UnregisterGIFImage(), UnregisterGRADIENTImage(), UnregisterGRAYImage(), UnregisterHALDImage(), UnregisterHDRImage(), UnregisterHISTOGRAMImage(), UnregisterHRZImage(), UnregisterHTMLImage(), UnregisterICONImage(), UnregisterINFOImage(), UnregisterINLINEImage(), UnregisterIPLImage(), UnregisterJBIGImage(), UnregisterJP2Image(), UnregisterJPEGImage(), UnregisterLABELImage(), UnregisterMACImage(), UnregisterMAGICKImage(), UnregisterMAPImage(), UnregisterMATImage(), UnregisterMATTEImage(), UnregisterMETAImage(), UnregisterMIFFImage(), UnregisterMONOImage(), UnregisterMPCImage(), UnregisterMPEGImage(), UnregisterMPRImage(), UnregisterMSLImage(), UnregisterMTVImage(), UnregisterMVGImage(), UnregisterNULLImage(), UnregisterOTBImage(), UnregisterPALMImage(), UnregisterPANGOImage(), UnregisterPATTERNImage(), UnregisterPCDImage(), UnregisterPCLImage(), UnregisterPCXImage(), UnregisterPDBImage(), UnregisterPDFImage(), UnregisterPESImage(), UnregisterPICTImage(), UnregisterPIXImage(), UnregisterPLASMAImage(), UnregisterPNGImage(), UnregisterPNMImage(), UnregisterPREVIEWImage(), UnregisterPS2Image(), UnregisterPS3Image(), UnregisterPSDImage(), UnregisterPSImage(), UnregisterPWPImage(), UnregisterRAWImage(), UnregisterRGBImage(), UnregisterRLAImage(), UnregisterRLEImage(), UnregisterSCRImage(), UnregisterSCTImage(), UnregisterSFWImage(), UnregisterSGIImage(), UnregisterSTEGANOImage(), UnregisterSUNImage(), UnregisterSVGImage(), UnregisterTGAImage(), UnregisterTHUMBNAILImage(), UnregisterTIFFImage(), UnregisterTILEImage(), UnregisterTIMImage(), UnregisterTTFImage(), UnregisterTXTImage(), UnregisterUILImage(), UnregisterURLImage(), UnregisterUYVYImage(), UnregisterVICARImage(), UnregisterVIDImage(), UnregisterVIFFImage(), UnregisterWBMPImage(), UnregisterWEBPImage(), UnregisterWMFImage(), UnregisterWPGImage(), UnregisterXBMImage(), UnregisterXCFImage(), UnregisterXCImage(), UnregisterXImage(), UnregisterXPMImage(), UnregisterXPSImage(), UnregisterXTRNImage(), UnregisterXWDImage(), UnregisterYCBCRImage(), and UnregisterYUVImage().
Referenced by MagickCoreTerminus().