MagickCore: monitor.c File Reference
monitor.c File Reference
#include "MagickCore/studio.h"
#include "MagickCore/image.h"
#include "MagickCore/log.h"
#include "MagickCore/monitor.h"
Functions
MagickExport MagickProgressMonitor SetImageProgressMonitor (Image *image, const MagickProgressMonitor progress_monitor, void *client_data)
MagickExport MagickProgressMonitor SetImageInfoProgressMonitor (ImageInfo *image_info, const MagickProgressMonitor progress_monitor, void *client_data)
Function Documentation
MagickExport MagickProgressMonitor SetImageInfoProgressMonitor (ImageInfo * image_info, const MagickProgressMonitor progress_monitor, void * client_data)
Definition at line 134 of file monitor.c.
References _ImageInfo::client_data, and _ImageInfo::progress_monitor.
Referenced by ReadInlineImage().
MagickExport MagickProgressMonitor SetImageProgressMonitor (Image * image, const MagickProgressMonitor progress_monitor, void * client_data)
Definition at line 85 of file monitor.c.
References _Image::client_data, and _Image::progress_monitor.
Referenced by DrawPrimitive(), MontageImageList(), PreviewImage(), QuantizeImages(), and WriteImages().