MagickCore: montage.h File Reference
montage.h File Reference
Data Structures
struct _MontageInfo
Typedefs
typedef struct _MontageInfo MontageInfo
Enumerations
enum MontageMode { UndefinedMode, FrameMode, UnframeMode, ConcatenateMode }
Functions
MagickExport Image * MontageImages (const Image *, const MontageInfo *, ExceptionInfo *)
MagickExport Image * MontageImageList (const ImageInfo *, const MontageInfo *, const Image *, ExceptionInfo *)
MagickExport MontageInfo * CloneMontageInfo (const ImageInfo *, const MontageInfo *)
MagickExport MontageInfo * DestroyMontageInfo (MontageInfo *)
MagickExport void GetMontageInfo (const ImageInfo *, MontageInfo *)
Typedef Documentation
typedef struct _MontageInfo MontageInfo
Enumeration Type Documentation
enum MontageMode
Enumerator
UndefinedMode
FrameMode
UnframeMode
ConcatenateMode
Definition at line 25 of file montage.h.
Function Documentation
MagickExport MontageInfo* CloneMontageInfo (const ImageInfo * , const MontageInfo *)
MagickExport MontageInfo * DestroyMontageInfo (MontageInfo *)
Definition at line 165 of file montage.c.
References _MontageInfo::debug, DestroyString(), _MontageInfo::font, _MontageInfo::frame, _MontageInfo::geometry, GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, RelinquishMagickMemory(), _MontageInfo::signature, _MontageInfo::texture, _MontageInfo::tile, _MontageInfo::title, and TraceEvent.
Referenced by PreviewImage().
MagickExport void GetMontageInfo (const ImageInfo * , MontageInfo *)
Definition at line 215 of file montage.c.
References AcquireString(), _PixelInfo::alpha, _MontageInfo::background_color, _ImageInfo::background_color, _MontageInfo::border_color, _ImageInfo::border_color, CenterGravity, CopyMagickString(), _MontageInfo::debug, _ImageInfo::debug, DefaultTileGeometry, _MontageInfo::filename, _ImageInfo::filename, _MontageInfo::fill, _MontageInfo::font, _ImageInfo::font, _MontageInfo::geometry, GetMagickModule, _MontageInfo::gravity, IsEventLogging(), LogMagickEvent(), MagickFalse, MagickSignature, _MontageInfo::matte_color, _ImageInfo::matte_color, MaxTextExtent, OpaqueAlpha, _MontageInfo::pointsize, _ImageInfo::pointsize, ResetMagickMemory(), _MontageInfo::signature, _ImageInfo::signature, _MontageInfo::stroke, TraceEvent, and TransparentAlpha.
Referenced by CloneMontageInfo().
MagickExport Image * MontageImageList (const ImageInfo * , const MontageInfo * , const Image * , ExceptionInfo *)
Definition at line 338 of file montage.c.
References AcquireImage(), AcquireNextImage(), AcquireQuantumMemory(), AcquireString(), AllCompliance, AlphaChannel, AnnotateImage(), _TypeMetric::ascent, _MontageInfo::background_color, _Image::background_color, _ImageInfo::background_color, _MontageInfo::border_color, _ImageInfo::border_color, _MontageInfo::border_width, BorderImage(), CenterGravity, _Image::client_data, CloneDrawInfo(), CloneImage(), CloneImageInfo(), CloneString(), _Image::columns, _Image::compose, CompositeImage(), ConcatenateMagickString(), CopyMagickString(), _Image::debug, DefaultChannels, _TypeMetric::descent, DestroyDrawInfo(), DestroyImage(), DestroyImageInfo(), DestroyImageList(), DestroyString(), _Image::directory, DstOutCompositeOp, _MontageInfo::filename, _Image::filename, _ImageInfo::filename, _MontageInfo::fill, _DrawInfo::fill, _MontageInfo::font, _DrawInfo::font, FormatLocaleString(), _MontageInfo::frame, FrameImage(), _MontageInfo::geometry, _DrawInfo::geometry, GetFirstImageInList(), GetGeometry(), GetImageListLength(), GetImageProperty(), GetMagickModule, GetMontageGeometry(), GetNextImageInList(), GetTypeMetrics(), _MontageInfo::gravity, _Image::gravity, _DrawInfo::gravity, _FrameInfo::height, _RectangleInfo::height, HeightValue, ImageListToArray(), _FrameInfo::inner_bevel, InterpretImageProperties(), LocaleCompare(), LogMagickEvent(), _Image::magick, MagickFalse, MagickMax(), MagickMin(), MagickSignature, MagickTrue, MaxTextExtent, _Image::montage, MontageImageTag, MultilineCensus(), NegateImage(), NewImageList(), _FrameInfo::outer_bevel, OverCompositeOp, _Image::page, ParseAbsoluteGeometry(), ParseGravityGeometry(), ParseMetaGeometry(), ParseRegionGeometry(), _MontageInfo::pointsize, _DrawInfo::pointsize, _Image::progress_monitor, PsiValue, QueryColorCompliance(), ReadImage(), RelinquishMagickMemory(), ResetMagickMemory(), ResourceLimitError, RhoValue, _Image::rows, _Image::scene, SceneCompare(), SetGeometry(), SetImageBackgroundColor(), SetImageProgress(), SetImageProgressMonitor(), SetPixelChannelMask(), _MontageInfo::shadow, ShadowImage(), SigmaValue, _MontageInfo::signature, _ExceptionInfo::signature, _Image::signature, _MontageInfo::stroke, _DrawInfo::stroke, _DrawInfo::text, _MontageInfo::texture, TextureImage(), ThrowImageException, ThumbnailImage(), _MontageInfo::tile, TileImageTag, _MontageInfo::title, TraceEvent, UndefinedGravity, _FrameInfo::width, _RectangleInfo::width, _FrameInfo::x, _RectangleInfo::x, XiValue, _FrameInfo::y, and _RectangleInfo::y.
Referenced by MontageImages().
MagickExport Image* MontageImages (const Image * , const MontageInfo * , ExceptionInfo *)