MagickCore: montage.c File Reference
montage.c File Reference
#include "MagickCore/studio.h"
#include "MagickCore/annotate.h"
#include "MagickCore/client.h"
#include "MagickCore/color.h"
#include "MagickCore/composite.h"
#include "MagickCore/constitute.h"
#include "MagickCore/decorate.h"
#include "MagickCore/draw.h"
#include "MagickCore/effect.h"
#include "MagickCore/enhance.h"
#include "MagickCore/exception.h"
#include "MagickCore/exception-private.h"
#include "MagickCore/fx.h"
#include "MagickCore/gem.h"
#include "MagickCore/geometry.h"
#include "MagickCore/image.h"
#include "MagickCore/image-private.h"
#include "MagickCore/list.h"
#include "MagickCore/memory_.h"
#include "MagickCore/monitor.h"
#include "MagickCore/monitor-private.h"
#include "MagickCore/montage.h"
#include "MagickCore/option.h"
#include "MagickCore/pixel.h"
#include "MagickCore/quantize.h"
#include "MagickCore/property.h"
#include "MagickCore/resize.h"
#include "MagickCore/resource_.h"
#include "MagickCore/string_.h"
#include "MagickCore/utility.h"
#include "MagickCore/utility-private.h"
#include "MagickCore/version.h"
Macros
#define MontageImageTag "Montage/Image"
#define TileImageTag "Tile/Image"
Functions
MagickExport MontageInfo * CloneMontageInfo (const ImageInfo *image_info, const MontageInfo *montage_info)
MagickExport MontageInfo * DestroyMontageInfo (MontageInfo *montage_info)
MagickExport void GetMontageInfo (const ImageInfo *image_info, MontageInfo *montage_info)
static void GetMontageGeometry (char *geometry, const size_t number_images, ssize_t *x_offset, ssize_t *y_offset, size_t *tiles_per_column, size_t *tiles_per_row)
static ssize_t MagickMax (const ssize_t x, const ssize_t y)
static ssize_t MagickMin (const ssize_t x, const ssize_t y)
static int SceneCompare (const void *x, const void *y)
MagickExport Image * MontageImages (const Image *images, const MontageInfo *montage_info, ExceptionInfo *exception)
MagickExport Image * MontageImageList (const ImageInfo *image_info, const MontageInfo *montage_info, const Image *images, ExceptionInfo *exception)
Macro Definition Documentation
#define MontageImageTag "Montage/Image"
Referenced by MontageImageList().
#define TileImageTag "Tile/Image"
Referenced by MontageImageList().
Function Documentation
MagickExport MontageInfo* CloneMontageInfo (const ImageInfo * image_info, const MontageInfo * montage_info)
Definition at line 103 of file montage.c.
References AcquireMagickMemory(), AcquireString(), _MontageInfo::background_color, _MontageInfo::border_color, _MontageInfo::border_width, CopyMagickString(), _MontageInfo::debug, _MontageInfo::filename, _MontageInfo::fill, _MontageInfo::font, _MontageInfo::frame, _MontageInfo::geometry, GetMontageInfo(), _MontageInfo::gravity, IsEventLogging(), _MontageInfo::matte_color, MaxTextExtent, _MontageInfo::pointsize, ResourceLimitFatalError, _MontageInfo::shadow, _MontageInfo::stroke, _MontageInfo::texture, ThrowFatalException, _MontageInfo::tile, and _MontageInfo::title.
Referenced by PreviewImage().
MagickExport MontageInfo* DestroyMontageInfo (MontageInfo * montage_info)
Definition at line 165 of file montage.c.
References _MontageInfo::debug, DestroyString(), _MontageInfo::font, _MontageInfo::frame, _MontageInfo::geometry, GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, RelinquishMagickMemory(), _MontageInfo::signature, _MontageInfo::texture, _MontageInfo::tile, _MontageInfo::title, and TraceEvent.
Referenced by PreviewImage().
static void GetMontageGeometry (char * geometry, const size_t number_images, ssize_t * x_offset, ssize_t * y_offset, size_t * tiles_per_column, size_t * tiles_per_row) static
Definition at line 273 of file montage.c.
References GetGeometry().
Referenced by MontageImageList().
MagickExport void GetMontageInfo (const ImageInfo * image_info, MontageInfo * montage_info)
Definition at line 215 of file montage.c.
References AcquireString(), _PixelInfo::alpha, _MontageInfo::background_color, _ImageInfo::background_color, _MontageInfo::border_color, _ImageInfo::border_color, CenterGravity, CopyMagickString(), _MontageInfo::debug, _ImageInfo::debug, DefaultTileGeometry, _MontageInfo::filename, _ImageInfo::filename, _MontageInfo::fill, _MontageInfo::font, _ImageInfo::font, _MontageInfo::geometry, GetMagickModule, _MontageInfo::gravity, IsEventLogging(), LogMagickEvent(), MagickFalse, MagickSignature, _MontageInfo::matte_color, _ImageInfo::matte_color, MaxTextExtent, OpaqueAlpha, _MontageInfo::pointsize, _ImageInfo::pointsize, ResetMagickMemory(), _MontageInfo::signature, _ImageInfo::signature, _MontageInfo::stroke, TraceEvent, and TransparentAlpha.
Referenced by CloneMontageInfo().
static ssize_t MagickMax (const ssize_t x, const ssize_t y) inline static
Definition at line 290 of file montage.c.
Referenced by MontageImageList().
static ssize_t MagickMin (const ssize_t x, const ssize_t y) inline static
Definition at line 297 of file montage.c.
Referenced by MontageImageList().
MagickExport Image* MontageImageList (const ImageInfo * image_info, const MontageInfo * montage_info, const Image * images, ExceptionInfo * exception)
Definition at line 338 of file montage.c.
References AcquireImage(), AcquireNextImage(), AcquireQuantumMemory(), AcquireString(), AllCompliance, AlphaChannel, AnnotateImage(), _TypeMetric::ascent, _MontageInfo::background_color, _Image::background_color, _ImageInfo::background_color, _MontageInfo::border_color, _ImageInfo::border_color, _MontageInfo::border_width, BorderImage(), CenterGravity, _Image::client_data, CloneDrawInfo(), CloneImage(), CloneImageInfo(), CloneString(), _Image::columns, _Image::compose, CompositeImage(), ConcatenateMagickString(), CopyMagickString(), _Image::debug, DefaultChannels, _TypeMetric::descent, DestroyDrawInfo(), DestroyImage(), DestroyImageInfo(), DestroyImageList(), DestroyString(), _Image::directory, DstOutCompositeOp, _MontageInfo::filename, _Image::filename, _ImageInfo::filename, _MontageInfo::fill, _DrawInfo::fill, _MontageInfo::font, _DrawInfo::font, FormatLocaleString(), _MontageInfo::frame, FrameImage(), _MontageInfo::geometry, _DrawInfo::geometry, GetFirstImageInList(), GetGeometry(), GetImageListLength(), GetImageProperty(), GetMagickModule, GetMontageGeometry(), GetNextImageInList(), GetTypeMetrics(), _MontageInfo::gravity, _Image::gravity, _DrawInfo::gravity, _FrameInfo::height, _RectangleInfo::height, HeightValue, ImageListToArray(), _FrameInfo::inner_bevel, InterpretImageProperties(), LocaleCompare(), LogMagickEvent(), _Image::magick, MagickFalse, MagickMax(), MagickMin(), MagickSignature, MagickTrue, MaxTextExtent, _Image::montage, MontageImageTag, MultilineCensus(), NegateImage(), NewImageList(), _FrameInfo::outer_bevel, OverCompositeOp, _Image::page, ParseAbsoluteGeometry(), ParseGravityGeometry(), ParseMetaGeometry(), ParseRegionGeometry(), _MontageInfo::pointsize, _DrawInfo::pointsize, _Image::progress_monitor, PsiValue, QueryColorCompliance(), ReadImage(), RelinquishMagickMemory(), ResetMagickMemory(), ResourceLimitError, RhoValue, _Image::rows, _Image::scene, SceneCompare(), SetGeometry(), SetImageBackgroundColor(), SetImageProgress(), SetImageProgressMonitor(), SetPixelChannelMask(), _MontageInfo::shadow, ShadowImage(), SigmaValue, _MontageInfo::signature, _ExceptionInfo::signature, _Image::signature, _MontageInfo::stroke, _DrawInfo::stroke, _DrawInfo::text, _MontageInfo::texture, TextureImage(), ThrowImageException, ThumbnailImage(), _MontageInfo::tile, TileImageTag, _MontageInfo::title, TraceEvent, UndefinedGravity, _FrameInfo::width, _RectangleInfo::width, _FrameInfo::x, _RectangleInfo::x, XiValue, _FrameInfo::y, and _RectangleInfo::y.
Referenced by MontageImages().
MagickExport Image* MontageImages (const Image * images, const MontageInfo * montage_info, ExceptionInfo * exception)
Definition at line 323 of file montage.c.
References AcquireImageInfo(), DestroyImageInfo(), and MontageImageList().
Referenced by PreviewImage().
static int SceneCompare (const void * x, const void * y) static
Definition at line 308 of file montage.c.
Referenced by MontageImageList().