MagickCore: option.h File Reference
option.h File Reference
Data Structures
struct _OptionInfo
Typedefs
typedef struct _OptionInfo OptionInfo
Enumerations
enum CommandOption {
MagickUndefinedOptions = -1, MagickAlignOptions = 0, MagickAlphaChannelOptions, MagickBooleanOptions,
MagickCacheOptions, MagickChannelOptions, MagickClassOptions, MagickClipPathOptions,
MagickCoderOptions, MagickColorOptions, MagickColorspaceOptions, MagickCommandOptions,
MagickComposeOptions, MagickCompressOptions, MagickConfigureOptions, MagickDataTypeOptions,
MagickDebugOptions, MagickDecorateOptions, MagickDelegateOptions, MagickDirectionOptions,
MagickDisposeOptions, MagickDistortOptions, MagickDitherOptions, MagickEndianOptions,
MagickEvaluateOptions, MagickFillRuleOptions, MagickFilterOptions, MagickFontOptions,
MagickFontsOptions, MagickFormatOptions, MagickFunctionOptions, MagickGravityOptions,
MagickIntentOptions, MagickInterlaceOptions, MagickInterpolateOptions, MagickKernelOptions,
MagickLayerOptions, MagickLineCapOptions, MagickLineJoinOptions, MagickListOptions,
MagickLocaleOptions, MagickLogEventOptions, MagickLogOptions, MagickMagicOptions,
MagickMethodOptions, MagickMetricOptions, MagickMimeOptions, MagickModeOptions,
MagickModuleOptions, MagickMorphologyOptions, MagickNoiseOptions, MagickOrientationOptions,
MagickPixelChannelOptions, MagickPixelIntensityOptions, MagickPixelMaskOptions, MagickPixelTraitOptions,
MagickPolicyOptions, MagickPolicyDomainOptions, MagickPolicyRightsOptions, MagickPreviewOptions,
MagickPrimitiveOptions, MagickQuantumFormatOptions, MagickResolutionOptions, MagickResourceOptions,
MagickSparseColorOptions, MagickStatisticOptions, MagickStorageOptions, MagickStretchOptions,
MagickStyleOptions, MagickThresholdOptions, MagickTypeOptions, MagickValidateOptions,
MagickVirtualPixelOptions
}
enum ValidateType {
UndefinedValidate, NoValidate = 0x00000, ColorspaceValidate = 0x00001, CompareValidate = 0x00002,
CompositeValidate = 0x00004, ConvertValidate = 0x00008, FormatsDiskValidate = 0x00010, FormatsMapValidate = 0x00020,
FormatsMemoryValidate = 0x00040, IdentifyValidate = 0x00080, ImportExportValidate = 0x00100, MontageValidate = 0x00200,
StreamValidate = 0x00400, AllValidate = 0x7fffffff
}
enum CommandOptionFlags {
UndefinedOptionFlag = 0x0000, ImageInfoOptionFlag = 0x0001, DrawInfoOptionFlag = 0x0002, QuantizeInfoOptionFlag = 0x0004,
GlobalOptionFlag = 0x0008, SettingOptionFlags = 0x000F, NoImageOperatorFlag = 0x0010, SimpleOperatorFlag = 0x0020,
ListOperatorFlag = 0x0040, GenesisOptionFlag = 0x0080, SpecialOptionFlag = 0x0100, AlwaysInterpretArgsFlag = 0x0400,
NeverInterpretArgsFlag = 0x0800, NonMagickOptionFlag = 0x1000, FireOptionFlag = 0x2000, DeprecateOptionFlag = 0x4000,
ReplacedOptionFlag = 0x8800
}
Functions
MagickExport char ** GetCommandOptions (const CommandOption)
MagickExport char * GetNextImageOption (const ImageInfo *)
MagickExport char * RemoveImageOption (ImageInfo *, const char *)
MagickExport const char * CommandOptionToMnemonic (const CommandOption, const ssize_t)
MagickExport const char * GetImageOption (const ImageInfo *, const char *)
MagickExport MagickBooleanType CloneImageOptions (ImageInfo *, const ImageInfo *)
MagickExport MagickBooleanType DefineImageOption (ImageInfo *, const char *)
MagickExport MagickBooleanType DeleteImageOption (ImageInfo *, const char *)
MagickExport MagickBooleanType IsCommandOption (const char *)
MagickExport MagickBooleanType ListCommandOptions (FILE *, const CommandOption, ExceptionInfo *)
MagickExport MagickBooleanType SetImageOption (ImageInfo *, const char *, const char *)
MagickExport ssize_t GetCommandOptionFlags (const CommandOption, const MagickBooleanType, const char *)
MagickExport ssize_t ParseChannelOption (const char *)
MagickExport ssize_t ParsePixelChannelOption (const char *)
MagickExport ssize_t ParseCommandOption (const CommandOption, const MagickBooleanType, const char *)
MagickExport void DestroyImageOptions (ImageInfo *)
MagickExport void ResetImageOptions (const ImageInfo *)
MagickExport void ResetImageOptionIterator (const ImageInfo *)
MagickExport const OptionInfo * GetCommandOptionInfo (const char *value)
Typedef Documentation
typedef struct _OptionInfo OptionInfo
Enumeration Type Documentation
enum CommandOption
Enumerator
MagickUndefinedOptions
MagickAlignOptions
MagickAlphaChannelOptions
MagickBooleanOptions
MagickCacheOptions
MagickChannelOptions
MagickClassOptions
MagickClipPathOptions
MagickCoderOptions
MagickColorOptions
MagickColorspaceOptions
MagickCommandOptions
MagickComposeOptions
MagickCompressOptions
MagickConfigureOptions
MagickDataTypeOptions
MagickDebugOptions
MagickDecorateOptions
MagickDelegateOptions
MagickDirectionOptions
MagickDisposeOptions
MagickDistortOptions
MagickDitherOptions
MagickEndianOptions
MagickEvaluateOptions
MagickFillRuleOptions
MagickFilterOptions
MagickFontOptions
MagickFontsOptions
MagickFormatOptions
MagickFunctionOptions
MagickGravityOptions
MagickIntentOptions
MagickInterlaceOptions
MagickInterpolateOptions
MagickKernelOptions
MagickLayerOptions
MagickLineCapOptions
MagickLineJoinOptions
MagickListOptions
MagickLocaleOptions
MagickLogEventOptions
MagickLogOptions
MagickMagicOptions
MagickMethodOptions
MagickMetricOptions
MagickMimeOptions
MagickModeOptions
MagickModuleOptions
MagickMorphologyOptions
MagickNoiseOptions
MagickOrientationOptions
MagickPixelChannelOptions
MagickPixelIntensityOptions
MagickPixelMaskOptions
MagickPixelTraitOptions
MagickPolicyOptions
MagickPolicyDomainOptions
MagickPolicyRightsOptions
MagickPreviewOptions
MagickPrimitiveOptions
MagickQuantumFormatOptions
MagickResolutionOptions
MagickResourceOptions
MagickSparseColorOptions
MagickStatisticOptions
MagickStorageOptions
MagickStretchOptions
MagickStyleOptions
MagickThresholdOptions
MagickTypeOptions
MagickValidateOptions
MagickVirtualPixelOptions
Definition at line 25 of file option.h.
enum CommandOptionFlags
Enumerator
UndefinedOptionFlag
ImageInfoOptionFlag
DrawInfoOptionFlag
QuantizeInfoOptionFlag
GlobalOptionFlag
SettingOptionFlags
NoImageOperatorFlag
SimpleOperatorFlag
ListOperatorFlag
GenesisOptionFlag
SpecialOptionFlag
AlwaysInterpretArgsFlag
NeverInterpretArgsFlag
NonMagickOptionFlag
FireOptionFlag
DeprecateOptionFlag
ReplacedOptionFlag
Definition at line 125 of file option.h.
enum ValidateType
Enumerator
UndefinedValidate
NoValidate
ColorspaceValidate
CompareValidate
CompositeValidate
ConvertValidate
FormatsDiskValidate
FormatsMapValidate
FormatsMemoryValidate
IdentifyValidate
ImportExportValidate
MontageValidate
StreamValidate
AllValidate
Definition at line 102 of file option.h.
Function Documentation
MagickExport MagickBooleanType CloneImageOptions (ImageInfo * , const ImageInfo *)
MagickExport const char* CommandOptionToMnemonic (const CommandOption , const ssize_t)
MagickExport MagickBooleanType DefineImageOption (ImageInfo * , const char *)
MagickExport MagickBooleanType DeleteImageOption (ImageInfo * , const char *)
MagickExport void DestroyImageOptions (ImageInfo *)
MagickExport ssize_t GetCommandOptionFlags (const CommandOption , const MagickBooleanType , const char *)
MagickExport const OptionInfo* GetCommandOptionInfo (const char * value)
Definition at line 2118 of file option.c.
References CommandOptions, FormatLocaleFile(), LocaleCompare(), _OptionInfo::mnemonic, and _GhostInfo::void().
MagickExport char** GetCommandOptions (const CommandOption)
MagickExport const char * GetImageOption (const ImageInfo * , const char *)
Definition at line 1960 of file option.c.
References _ImageInfo::debug, _ImageInfo::filename, GetMagickModule, GetValueFromSplayTree(), LogMagickEvent(), MagickFalse, MagickSignature, _ImageInfo::options, _ImageInfo::signature, TraceEvent, and _GhostInfo::void().
Referenced by AcquireImage(), AcquireQuantizeInfo(), GetDrawInfo(), GetMagickProperty(), GetMagickPropertyLetter(), GetQuantumInfo(), InterpretImageFilename(), InterpretImageProperties(), ReadImage(), SyncImageSettings(), and WriteImage().
MagickExport char * GetNextImageOption (const ImageInfo *)
MagickExport MagickBooleanType IsCommandOption (const char *)
MagickExport MagickBooleanType ListCommandOptions (FILE * , const CommandOption , ExceptionInfo *)
MagickExport ssize_t ParseChannelOption (const char *)
MagickExport ssize_t ParseCommandOption (const CommandOption , const MagickBooleanType , const char *)
Definition at line 2525 of file option.c.
References CopyMagickString(), GetOptionInfo(), LocaleCompare(), MagickFalse, MagickTrue, MaxTextExtent, _OptionInfo::mnemonic, sentinel, _OptionInfo::type, and _GhostInfo::void().
Referenced by AcquireImage(), AcquireQuantizeInfo(), AcquireResizeFilter(), DrawImage(), ExpandFilenames(), FxChannelStatistics(), GetDrawInfo(), GetQuantumInfo(), LoadLogList(), LoadMimeList(), LoadPolicyList(), LoadTypeList(), ModulateImage(), MorphologyImage(), ParseChannelOption(), ParseKernelName(), ParsePixelChannelOption(), QueryColorCompliance(), ReadImage(), SetImageProperty(), SetLogEventMask(), and SyncImageSettings().
MagickExport ssize_t ParsePixelChannelOption (const char *)
MagickExport char * RemoveImageOption (ImageInfo * , const char *)
Definition at line 2683 of file option.c.
References _ImageInfo::debug, _ImageInfo::filename, GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, _ImageInfo::options, RemoveNodeFromSplayTree(), _ImageInfo::signature, TraceEvent, and _GhostInfo::void().
MagickExport void ResetImageOptionIterator (const ImageInfo *)
Definition at line 2759 of file option.c.
References _ImageInfo::debug, _ImageInfo::filename, GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, _ImageInfo::options, ResetSplayTreeIterator(), _ImageInfo::signature, TraceEvent, and _GhostInfo::void().
Referenced by InterpretImageProperties(), and SyncImageSettings().
MagickExport void ResetImageOptions (const ImageInfo *)
MagickExport MagickBooleanType SetImageOption (ImageInfo * , const char * , const char *)
Definition at line 2798 of file option.c.
References AddValueToSplayTree(), CloneString(), CompareSplayTreeString(), ConstantString(), _ImageInfo::debug, DeleteImageOption(), _ImageInfo::filename, GetMagickModule, LocaleCompare(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, NewSplayTree(), _ImageInfo::options, RelinquishMagickMemory(), _ImageInfo::signature, _ImageInfo::size, TraceEvent, and _GhostInfo::void().
Referenced by DefineImageOption(), GetMagickProperty(), GetMagickPropertyLetter(), PingImages(), ReadImages(), and SetImageType().