MagickCore: paint.h File Reference
paint.h File Reference
#include "MagickCore/color.h"
#include "MagickCore/draw.h"
Functions
MagickExport Image * OilPaintImage (const Image *, const double, const double, ExceptionInfo *)
MagickExport MagickBooleanType FloodfillPaintImage (Image *, const DrawInfo *, const PixelInfo *, const ssize_t, const ssize_t, const MagickBooleanType, ExceptionInfo *)
MagickExport MagickBooleanType GradientImage (Image *, const GradientType, const SpreadMethod, const PixelInfo *, const PixelInfo *, ExceptionInfo *)
MagickExport MagickBooleanType OpaquePaintImage (Image *, const PixelInfo *, const PixelInfo *, const MagickBooleanType, ExceptionInfo *)
MagickExport MagickBooleanType TransparentPaintImage (Image *, const PixelInfo *, const Quantum, const MagickBooleanType, ExceptionInfo *)
MagickExport MagickBooleanType TransparentPaintImageChroma (Image *, const PixelInfo *, const PixelInfo *, const Quantum, const MagickBooleanType, ExceptionInfo *)
Function Documentation
MagickExport MagickBooleanType FloodfillPaintImage (Image * , const DrawInfo * , const PixelInfo * , const ssize_t , const ssize_t , const MagickBooleanType , ExceptionInfo *)
MagickExport MagickBooleanType GradientImage (Image * , const GradientType , const SpreadMethod , const PixelInfo * , const PixelInfo * , ExceptionInfo *)
MagickExport Image* OilPaintImage (const Image * , const double , const double , ExceptionInfo *)
Definition at line 534 of file paint.c.
References AcquireAuthenticCacheView(), AcquireHistogramThreadSet(), AcquireVirtualCacheView(), ClampToQuantum(), CloneImage(), _Image::columns, CopyPixelTrait, _Image::debug, DestroyCacheView(), DestroyHistogramThreadSet(), DestroyImage(), DirectClass, _Image::filename, GetCacheViewVirtualPixels(), GetMagickModule, GetOpenMPThreadId(), GetOptimalKernelWidth2D(), GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelIntensity(), GetPixelReadMask(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, NumberPaintBins, OilPaintImageTag, _Image::progress_monitor, QueueCacheViewAuthenticPixels(), ResetMagickMemory(), ResourceLimitError, _Image::rows, SetImageProgress(), SetImageStorageClass(), SetPixelChannel(), _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), ThrowImageException, TraceEvent, and UndefinedPixelTrait.
Referenced by PreviewImage().
MagickExport MagickBooleanType OpaquePaintImage (Image * , const PixelInfo * , const PixelInfo * , const MagickBooleanType , ExceptionInfo *)
MagickExport MagickBooleanType TransparentPaintImage (Image * , const PixelInfo * , const Quantum , const MagickBooleanType , ExceptionInfo *)
MagickExport MagickBooleanType TransparentPaintImageChroma (Image * , const PixelInfo * , const PixelInfo * , const Quantum , const MagickBooleanType , ExceptionInfo *)
Definition at line 1017 of file paint.c.
References AcquireAuthenticCacheView(), _Image::alpha_trait, BlendPixelTrait, _PixelInfo::blue, _Image::columns, _Image::debug, DestroyCacheView(), DirectClass, _Image::filename, GetCacheViewAuthenticPixels(), GetMagickModule, GetPixelChannels(), GetPixelInfo(), GetPixelInfoPixel(), _PixelInfo::green, LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, OpaqueAlphaChannel, _Image::progress_monitor, _PixelInfo::red, _Image::rows, SetImageAlphaChannel(), SetImageProgress(), SetImageStorageClass(), SetPixelAlpha(), _Image::signature, SyncCacheViewAuthenticPixels(), TraceEvent, and TransparentPaintImageTag.