MagickCore: paint.c File Reference
paint.c File Reference
#include "MagickCore/studio.h"
#include "MagickCore/channel.h"
#include "MagickCore/color.h"
#include "MagickCore/color-private.h"
#include "MagickCore/colorspace-private.h"
#include "MagickCore/composite.h"
#include "MagickCore/composite-private.h"
#include "MagickCore/draw.h"
#include "MagickCore/draw-private.h"
#include "MagickCore/exception.h"
#include "MagickCore/exception-private.h"
#include "MagickCore/gem.h"
#include "MagickCore/gem-private.h"
#include "MagickCore/monitor.h"
#include "MagickCore/monitor-private.h"
#include "MagickCore/paint.h"
#include "MagickCore/pixel-accessor.h"
#include "MagickCore/resource_.h"
#include "MagickCore/statistic.h"
#include "MagickCore/string_.h"
#include "MagickCore/thread-private.h"
Macros
#define MaxStacksize 131072UL
#define PushSegmentStack(up, left, right, delta)
#define NumberPaintBins 256
#define OilPaintImageTag "OilPaint/Image"
#define OpaquePaintImageTag "Opaque/Image"
#define TransparentPaintImageTag "Transparent/Image"
#define TransparentPaintImageTag "Transparent/Image"
Functions
MagickExport MagickBooleanType FloodfillPaintImage (Image *image, const DrawInfo *draw_info, const PixelInfo *target, const ssize_t x_offset, const ssize_t y_offset, const MagickBooleanType invert, ExceptionInfo *exception)
static double MagickMax (const double x, const double y)
MagickExport MagickBooleanType GradientImage (Image *image, const GradientType type, const SpreadMethod method, const PixelInfo *start_color, const PixelInfo *stop_color, ExceptionInfo *exception)
static size_t ** DestroyHistogramThreadSet (size_t **histogram)
static size_t ** AcquireHistogramThreadSet (const size_t count)
MagickExport Image * OilPaintImage (const Image *image, const double radius, const double sigma, ExceptionInfo *exception)
MagickExport MagickBooleanType OpaquePaintImage (Image *image, const PixelInfo *target, const PixelInfo *fill, const MagickBooleanType invert, ExceptionInfo *exception)
MagickExport MagickBooleanType TransparentPaintImage (Image *image, const PixelInfo *target, const Quantum opacity, const MagickBooleanType invert, ExceptionInfo *exception)
MagickExport MagickBooleanType TransparentPaintImageChroma (Image *image, const PixelInfo *low, const PixelInfo *high, const Quantum opacity, const MagickBooleanType invert, ExceptionInfo *exception)
Macro Definition Documentation
#define MaxStacksize 131072UL
Referenced by FloodfillPaintImage().
#define NumberPaintBins 256
Referenced by OilPaintImage().
#define OilPaintImageTag "OilPaint/Image"
Referenced by OilPaintImage().
#define OpaquePaintImageTag "Opaque/Image"
Referenced by OpaquePaintImage().
#define PushSegmentStack (up, left, right, delta)
Value:
{ \
  if (s >= (segment_stack+MaxStacksize)) \
    ThrowBinaryException(DrawError,"SegmentStackOverflow",image->filename) \
  else \
    { \
      if ((((up)+(delta)) >= 0) && (((up)+(delta)) < (ssize_t) image->rows)) \
        { \
          s->x1=(double) (left); \
          s->y1=(double) (up); \
          s->x2=(double) (right); \
          s->y2=(double) (delta); \
          s++; \
        } \
    } \
}
Referenced by FloodfillPaintImage().
#define TransparentPaintImageTag "Transparent/Image"
Referenced by TransparentPaintImage(), and TransparentPaintImageChroma().
#define TransparentPaintImageTag "Transparent/Image"
Function Documentation
static size_t** AcquireHistogramThreadSet (const size_t count) static
Definition at line 511 of file paint.c.
References AcquireQuantumMemory(), DestroyHistogramThreadSet(), GetMagickResourceLimit(), ResetMagickMemory(), and ThreadResource.
Referenced by OilPaintImage().
static size_t** DestroyHistogramThreadSet (size_t ** histogram) static
Definition at line 498 of file paint.c.
References GetMagickResourceLimit(), RelinquishMagickMemory(), and ThreadResource.
Referenced by AcquireHistogramThreadSet(), and OilPaintImage().
MagickExport MagickBooleanType FloodfillPaintImage (Image * image, const DrawInfo * draw_info, const PixelInfo * target, const ssize_t x_offset, const ssize_t y_offset, const MagickBooleanType invert, ExceptionInfo * exception)
Definition at line 109 of file paint.c.
References AcquireAuthenticCacheView(), AcquireQuantumMemory(), AcquireVirtualCacheView(), AllCompliance, _PixelInfo::alpha_trait, _Image::alpha_trait, _Image::background_color, BlendPixelTrait, CloneImage(), _Image::colorspace, _Image::columns, _Image::debug, DestroyCacheView(), DestroyImage(), DirectClass, _Image::filename, _DrawInfo::fill, GetCacheViewAuthenticPixels(), GetCacheViewVirtualPixels(), GetFillColor(), GetMagickModule, GetPixelChannels(), GetPixelGray(), GetPixelInfo(), GetPixelInfoPixel(), GRAYColorspace, IsFuzzyEquivalencePixelInfo(), IsGrayColorspace(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, MaxStacksize, OpaqueAlpha, PushSegmentStack, QuantumRange, QueryColorCompliance(), RelinquishMagickMemory(), ResourceLimitError, _Image::rows, SetImageAlpha(), SetImageBackgroundColor(), SetImageColorspace(), SetImageStorageClass(), SetPixelGray(), SetPixelInfoPixel(), _DrawInfo::signature, _Image::signature, sRGBColorspace, SyncCacheViewAuthenticPixels(), ThrowBinaryException, TraceEvent, UndefinedPixelTrait, _SegmentInfo::x1, _SegmentInfo::x2, _SegmentInfo::y1, and _SegmentInfo::y2.
Referenced by DrawPrimitive().
MagickExport MagickBooleanType GradientImage (Image * image, const GradientType type, const SpreadMethod method, const PixelInfo * start_color, const PixelInfo * stop_color, ExceptionInfo * exception)
Definition at line 401 of file paint.c.
References AcquireDrawInfo(), AcquireQuantumMemory(), _GradientInfo::bounding_box, _GradientInfo::center, _StopInfo::color, _PixelInfo::colorspace, _Image::columns, _Image::debug, DestroyDrawInfo(), DrawGradientImage(), _Image::filename, GetMagickModule, GetPixelInfo(), _DrawInfo::gradient, _GradientInfo::gradient_vector, _RectangleInfo::height, LinearGradient, LogMagickEvent(), MagickFalse, MagickMax(), MagickSignature, _GradientInfo::number_stops, _StopInfo::offset, _GradientInfo::radius, ResetMagickMemory(), ResourceLimitError, _Image::rows, SetImageColorspace(), _Image::signature, _GradientInfo::spread, _GradientInfo::stops, ThrowBinaryException, TraceEvent, _GradientInfo::type, _RectangleInfo::width, _PointInfo::x, _SegmentInfo::x2, _PointInfo::y, and _SegmentInfo::y2.
Referenced by DrawImage().
static double MagickMax (const double x, const double y) inline static
Definition at line 396 of file paint.c.
Referenced by GradientImage().
MagickExport Image* OilPaintImage (const Image * image, const double radius, const double sigma, ExceptionInfo * exception)
Definition at line 534 of file paint.c.
References AcquireAuthenticCacheView(), AcquireHistogramThreadSet(), AcquireVirtualCacheView(), ClampToQuantum(), CloneImage(), _Image::columns, CopyPixelTrait, _Image::debug, DestroyCacheView(), DestroyHistogramThreadSet(), DestroyImage(), DirectClass, _Image::filename, GetCacheViewVirtualPixels(), GetMagickModule, GetOpenMPThreadId(), GetOptimalKernelWidth2D(), GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelIntensity(), GetPixelReadMask(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, NumberPaintBins, OilPaintImageTag, _Image::progress_monitor, QueueCacheViewAuthenticPixels(), ResetMagickMemory(), ResourceLimitError, _Image::rows, SetImageProgress(), SetImageStorageClass(), SetPixelChannel(), _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), ThrowImageException, TraceEvent, and UndefinedPixelTrait.
Referenced by PreviewImage().
MagickExport MagickBooleanType OpaquePaintImage (Image * image, const PixelInfo * target, const PixelInfo * fill, const MagickBooleanType invert, ExceptionInfo * exception)
Definition at line 755 of file paint.c.
References AcquireAuthenticCacheView(), _PixelInfo::alpha_trait, _Image::alpha_trait, BlendPixelTrait, _Image::colorspace, _Image::columns, _Image::debug, DestroyCacheView(), DirectClass, _Image::filename, GetCacheViewAuthenticPixels(), GetMagickModule, GetPixelChannels(), GetPixelInfo(), GetPixelInfoPixel(), IsFuzzyEquivalencePixelInfo(), IsGrayColorspace(), IsPixelInfoGray(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, OpaqueAlpha, OpaquePaintImageTag, _Image::progress_monitor, _Image::rows, SetImageAlpha(), SetImageColorspace(), SetImageProgress(), SetImageStorageClass(), SetPixelInfoPixel(), _Image::signature, sRGBColorspace, SyncCacheViewAuthenticPixels(), and TraceEvent.
MagickExport MagickBooleanType TransparentPaintImage (Image * image, const PixelInfo * target, const Quantum opacity, const MagickBooleanType invert, ExceptionInfo * exception)
Definition at line 887 of file paint.c.
References AcquireAuthenticCacheView(), _Image::alpha_trait, BlendPixelTrait, _Image::columns, _Image::debug, DestroyCacheView(), DirectClass, _Image::filename, GetCacheViewAuthenticPixels(), GetMagickModule, GetPixelChannels(), GetPixelInfo(), GetPixelInfoPixel(), IsFuzzyEquivalencePixelInfo(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, OpaqueAlphaChannel, _Image::progress_monitor, _Image::rows, SetImageAlphaChannel(), SetImageProgress(), SetImageStorageClass(), SetPixelAlpha(), _Image::signature, SyncCacheViewAuthenticPixels(), TraceEvent, and TransparentPaintImageTag.
MagickExport MagickBooleanType TransparentPaintImageChroma (Image * image, const PixelInfo * low, const PixelInfo * high, const Quantum opacity, const MagickBooleanType invert, ExceptionInfo * exception)
Definition at line 1017 of file paint.c.
References AcquireAuthenticCacheView(), _Image::alpha_trait, BlendPixelTrait, _PixelInfo::blue, _Image::columns, _Image::debug, DestroyCacheView(), DirectClass, _Image::filename, GetCacheViewAuthenticPixels(), GetMagickModule, GetPixelChannels(), GetPixelInfo(), GetPixelInfoPixel(), _PixelInfo::green, LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, OpaqueAlphaChannel, _Image::progress_monitor, _PixelInfo::red, _Image::rows, SetImageAlphaChannel(), SetImageProgress(), SetImageStorageClass(), SetPixelAlpha(), _Image::signature, SyncCacheViewAuthenticPixels(), TraceEvent, and TransparentPaintImageTag.