MagickCore: pixel-private.h File Reference
pixel-private.h File Reference
Functions
static double PerceptibleReciprocal (const double x)
Function Documentation
static double PerceptibleReciprocal (const double x) inline static
Definition at line 25 of file pixel-private.h.
References MagickEpsilon.
Referenced by AcquireResizeFilter(), AdaptiveBlurImage(), AdaptiveSharpenImage(), CompositeImage(), CompositeOverImage(), CompositePixelInfoOver(), CompositePixelInfoPlus(), CompositePixelOver(), ConvertXYZToLuv(), DefineImageColormap(), DistortImage(), EmbossImage(), FlattenPixelInfo(), GaussJordanElimination(), GetCubeInfo(), GetImageFeatures(), GetImageStatistics(), GetNormalizedCrossCorrelationDistortion(), GetOptimalKernelWidth1D(), GetOptimalKernelWidth2D(), GetStopColorOffset(), HorizontalFilter(), ImportQuantumPixels(), InterpolatePixelChannel(), InterpolatePixelChannels(), InterpolatePixelInfo(), InverseAffineMatrix(), InvertAffineCoefficients(), InvertPerspectiveCoefficients(), MotionBlurImage(), RadialBlurImage(), ScaleImage(), ScaleSpace(), SelectiveBlurImage(), SharpenImage(), sRGBTransformImage(), TraceArcPath(), TransformsRGBImage(), and VerticalFilter().