MagickCore: pixel.h File Reference
pixel.h File Reference
#include "MagickCore/colorspace.h"
Data Structures
struct _PixelChannelMap
struct _PixelInfo
struct _PixelPacket
Macros
#define MaxPixelChannels 32
Typedefs
typedef struct _PixelChannelMap PixelChannelMap
typedef struct _PixelInfo PixelInfo
typedef struct _PixelPacket PixelPacket
typedef struct _CacheView CacheView_
Enumerations
enum ChannelType {
UndefinedChannel = 0x0000, RedChannel = 0x0001, GrayChannel = 0x0001, CyanChannel = 0x0001,
GreenChannel = 0x0002, MagentaChannel = 0x0002, BlueChannel = 0x0004, YellowChannel = 0x0004,
BlackChannel = 0x0008, AlphaChannel = 0x0010, OpacityChannel = 0x0010, IndexChannel = 0x0020,
ReadMaskChannel = 0x0040, WriteMaskChannel = 0x0080, MetaChannel = 0x0100, CompositeChannels = 0x002F,
AllChannels = 0x7ffffff, TrueAlphaChannel = 0x0100, RGBChannels = 0x0200, GrayChannels = 0x0400,
SyncChannels = 0x20000, DefaultChannels = ((AllChannels | SyncChannels) &~ AlphaChannel)
}
enum PixelChannel {
UndefinedPixelChannel = 0, RedPixelChannel = 0, CyanPixelChannel = 0, GrayPixelChannel = 0,
LPixelChannel = 0, YPixelChannel = 0, aPixelChannel = 1, GreenPixelChannel = 1,
MagentaPixelChannel = 1, CbPixelChannel = 1, bPixelChannel = 2, BluePixelChannel = 2,
YellowPixelChannel = 2, CrPixelChannel = 2, BlackPixelChannel = 3, AlphaPixelChannel = 4,
IndexPixelChannel = 5, ReadMaskPixelChannel = 6, WriteMaskPixelChannel = 7, MetaPixelChannel = 8,
IntensityPixelChannel = MaxPixelChannels, CompositePixelChannel = MaxPixelChannels, SyncPixelChannel = MaxPixelChannels+1
}
enum PixelIntensityMethod {
UndefinedPixelIntensityMethod = 0, AveragePixelIntensityMethod, BrightnessPixelIntensityMethod, LightnessPixelIntensityMethod,
MSPixelIntensityMethod, Rec601LumaPixelIntensityMethod, Rec601LuminancePixelIntensityMethod, Rec709LumaPixelIntensityMethod,
Rec709LuminancePixelIntensityMethod, RMSPixelIntensityMethod
}
enum PixelInterpolateMethod {
UndefinedInterpolatePixel, AverageInterpolatePixel, Average9InterpolatePixel, Average16InterpolatePixel,
BackgroundInterpolatePixel, BilinearInterpolatePixel, BlendInterpolatePixel, CatromInterpolatePixel,
IntegerInterpolatePixel, MeshInterpolatePixel, NearestInterpolatePixel, SplineInterpolatePixel
}
enum PixelMask { UndefinedPixelMask = 0x000000, ReadPixelMask = 0x000001, WritePixelMask = 0x000002 }
enum PixelTrait { UndefinedPixelTrait = 0x000000, CopyPixelTrait = 0x000001, UpdatePixelTrait = 0x000002, BlendPixelTrait = 0x000004 }
enum StorageType {
UndefinedPixel, CharPixel, DoublePixel, FloatPixel,
LongPixel, LongLongPixel, QuantumPixel, ShortPixel
}
Functions
MagickExport MagickBooleanType ExportImagePixels (Image *, const ssize_t, const ssize_t, const size_t, const size_t, const char *, const StorageType, void *, ExceptionInfo *)
MagickExport MagickBooleanType ImportImagePixels (Image *, const ssize_t, const ssize_t, const size_t, const size_t, const char *, const StorageType, const void *, ExceptionInfo *)
MagickExport MagickBooleanType InterpolatePixelChannel (const Image *, const CacheView_ *, const PixelChannel, const PixelInterpolateMethod, const double, const double, double *, ExceptionInfo *)
MagickExport MagickBooleanType InterpolatePixelChannels (const Image *, const CacheView_ *, const Image *, const PixelInterpolateMethod, const double, const double, Quantum *, ExceptionInfo *)
MagickExport MagickBooleanType InterpolatePixelInfo (const Image *, const CacheView_ *, const PixelInterpolateMethod, const double, const double, PixelInfo *, ExceptionInfo *)
MagickExport MagickBooleanType IsFuzzyEquivalencePixel (const Image *, const Quantum *, const Image *, const Quantum *)
MagickExport MagickBooleanType IsFuzzyEquivalencePixelInfo (const PixelInfo *, const PixelInfo *)
MagickExport MagickBooleanType SetPixelMetaChannels (Image *, const size_t, ExceptionInfo *)
MagickExport MagickRealType GetPixelIntensity (const Image *restrict, const Quantum *restrict) magick_hot_spot
MagickExport PixelChannelMap * AcquirePixelChannelMap (void)
MagickExport PixelChannelMap * ClonePixelChannelMap (PixelChannelMap *)
MagickExport PixelChannelMap * DestroyPixelChannelMap (PixelChannelMap *)
MagickExport PixelInfo * ClonePixelInfo (const PixelInfo *)
MagickExport MagickRealType DecodePixelGamma (const MagickRealType) magick_hot_spot
MagickExport MagickRealType EncodePixelGamma (const MagickRealType) magick_hot_spot
MagickExport void InitializePixelChannelMap (Image *)
MagickExport void GetPixelInfo (const Image *, PixelInfo *)
MagickExport void SetPixelChannelMask (Image *, const ChannelType)
Macro Definition Documentation
#define MaxPixelChannels 32
Definition at line 27 of file pixel.h.
Referenced by AcquirePixelChannelMap(), AcquirePixelThreadSet(), AdaptiveThresholdImage(), ClonePixelChannelMap(), CompositeImage(), CompositeOverImage(), EvaluateImages(), GetAbsoluteDistortion(), GetFuzzDistortion(), GetImageDistortion(), GetImageDistortions(), GetImageStatistics(), GetMeanAbsoluteDistortion(), GetMeanSquaredDistortion(), GetNormalizedCrossCorrelationDistortion(), GetOneAuthenticPixel(), GetOneAuthenticPixelFromCache(), GetOneAuthenticPixelFromStream(), GetOneCacheViewAuthenticPixel(), GetOneCacheViewVirtualMethodPixel(), GetOneCacheViewVirtualPixel(), GetOneVirtualPixel(), GetOneVirtualPixelFromCache(), GetOneVirtualPixelFromStream(), GetPeakAbsoluteDistortion(), GetPeakSignalToNoiseRatio(), GetRootMeanSquaredDistortion(), GetVirtualPixelsFromNexus(), IdentifyImage(), InitializePixelChannelMap(), IntensityCompare(), OpenDistributeCache(), OpenDistributePixelCache(), OpenPixelCache(), OrderedPosterizeImage(), ParsePixelChannelOption(), PolynomialImage(), ScaleImage(), and SetQuantumDepth().
Typedef Documentation
typedef struct _CacheView CacheView_
Definition at line 205 of file pixel.h.
typedef struct _PixelChannelMap PixelChannelMap
typedef struct _PixelInfo PixelInfo
typedef struct _PixelPacket PixelPacket
Enumeration Type Documentation
enum ChannelType
Enumerator
UndefinedChannel
RedChannel
GrayChannel
CyanChannel
GreenChannel
MagentaChannel
BlueChannel
YellowChannel
BlackChannel
AlphaChannel
OpacityChannel
IndexChannel
ReadMaskChannel
WriteMaskChannel
MetaChannel
CompositeChannels
AllChannels
TrueAlphaChannel
RGBChannels
GrayChannels
SyncChannels
DefaultChannels
Definition at line 33 of file pixel.h.
enum PixelChannel
Enumerator
UndefinedPixelChannel
RedPixelChannel
CyanPixelChannel
GrayPixelChannel
LPixelChannel
YPixelChannel
aPixelChannel
GreenPixelChannel
MagentaPixelChannel
CbPixelChannel
bPixelChannel
BluePixelChannel
YellowPixelChannel
CrPixelChannel
BlackPixelChannel
AlphaPixelChannel
IndexPixelChannel
ReadMaskPixelChannel
WriteMaskPixelChannel
MetaPixelChannel
IntensityPixelChannel
CompositePixelChannel
SyncPixelChannel
Definition at line 66 of file pixel.h.
enum PixelIntensityMethod
Enumerator
UndefinedPixelIntensityMethod
AveragePixelIntensityMethod
BrightnessPixelIntensityMethod
LightnessPixelIntensityMethod
MSPixelIntensityMethod
Rec601LumaPixelIntensityMethod
Rec601LuminancePixelIntensityMethod
Rec709LumaPixelIntensityMethod
Rec709LuminancePixelIntensityMethod
RMSPixelIntensityMethod
Definition at line 93 of file pixel.h.
enum PixelInterpolateMethod
Enumerator
UndefinedInterpolatePixel
AverageInterpolatePixel
Average9InterpolatePixel
Average16InterpolatePixel
BackgroundInterpolatePixel
BilinearInterpolatePixel
BlendInterpolatePixel
CatromInterpolatePixel
IntegerInterpolatePixel
MeshInterpolatePixel
NearestInterpolatePixel
SplineInterpolatePixel
Definition at line 107 of file pixel.h.
enum PixelMask
Enumerator
UndefinedPixelMask
ReadPixelMask
WritePixelMask
Definition at line 124 of file pixel.h.
enum PixelTrait
Enumerator
UndefinedPixelTrait
CopyPixelTrait
UpdatePixelTrait
BlendPixelTrait
Definition at line 131 of file pixel.h.
enum StorageType
Enumerator
UndefinedPixel
CharPixel
DoublePixel
FloatPixel
LongPixel
LongLongPixel
QuantumPixel
ShortPixel
Definition at line 139 of file pixel.h.
Function Documentation
MagickExport PixelChannelMap* AcquirePixelChannelMap (void)
MagickExport PixelChannelMap * ClonePixelChannelMap (PixelChannelMap *)
MagickExport PixelInfo* ClonePixelInfo (const PixelInfo *)
Definition at line 168 of file pixel.c.
References AcquireQuantumMemory(), ResourceLimitFatalError, and ThrowFatalException.
Referenced by FxGetSymbol().
MagickExport MagickRealType DecodePixelGamma (const MagickRealType)
MagickExport PixelChannelMap * DestroyPixelChannelMap (PixelChannelMap *)
Definition at line 292 of file pixel.c.
References RelinquishMagickMemory().
Referenced by DestroyImage().
MagickExport MagickRealType EncodePixelGamma (const MagickRealType)
Definition at line 388 of file pixel.c.
References EncodeGamma(), QuantumRange, and QuantumScale.
Referenced by ConvertXYZToRGB(), GetPixelIntensity(), GrayscaleImage(), and TransformsRGBImage().
MagickExport MagickBooleanType ExportImagePixels (Image * , const ssize_t , const ssize_t , const size_t , const size_t , const char * , const StorageType , void * , ExceptionInfo *)
MagickExport void GetPixelInfo (const Image * , PixelInfo *)
MagickExport MagickRealType GetPixelIntensity (const Image * restrict, const Quantum * restrict)
MagickExport MagickBooleanType ImportImagePixels (Image * , const ssize_t , const ssize_t , const size_t , const size_t , const char * , const StorageType , const void * , ExceptionInfo *)
MagickExport void InitializePixelChannelMap (Image *)
MagickExport MagickBooleanType InterpolatePixelChannel (const Image * , const CacheView_ * , const PixelChannel , const PixelInterpolateMethod , const double , const double , double * , ExceptionInfo *)
MagickExport MagickBooleanType InterpolatePixelChannels (const Image * , const CacheView_ * , const Image * , const PixelInterpolateMethod , const double , const double , Quantum * , ExceptionInfo *)
MagickExport MagickBooleanType InterpolatePixelInfo (const Image * , const CacheView_ * , const PixelInterpolateMethod , const double , const double , PixelInfo * , ExceptionInfo *)
MagickExport MagickBooleanType IsFuzzyEquivalencePixel (const Image * , const Quantum * , const Image * , const Quantum *)
MagickExport MagickBooleanType IsFuzzyEquivalencePixelInfo (const PixelInfo * , const PixelInfo *)
MagickExport void SetPixelChannelMask (Image * , const ChannelType)
Definition at line 6075 of file pixel.c.
References _Image::alpha_trait, AlphaPixelChannel, BlendPixelTrait, CopyPixelTrait, _Image::debug, GetChannelBit, GetMagickModule, GetPixelChannelChannel(), GetPixelChannels(), IndexPixelChannel, LogMagickEvent(), LogPixelChannels(), MagickFalse, PixelEvent, PseudoClass, _Image::read_mask, ReadMaskPixelChannel, SetPixelChannelTraits(), _Image::storage_class, UpdatePixelTrait, _Image::write_mask, and WriteMaskPixelChannel.
Referenced by ChannelFxImage(), FxChannelStatistics(), MontageImageList(), SetImageChannelMask(), ShadowImage(), and SyncImageSettings().
MagickExport MagickBooleanType SetPixelMetaChannels (Image * , const size_t , ExceptionInfo *)
Definition at line 6132 of file pixel.c.
References _Image::number_meta_channels, and SyncImagePixelCache().
Referenced by ChannelFxImage().