MagickCore: pixel.c File Reference
pixel.c File Reference
#include "MagickCore/studio.h"
#include "MagickCore/property.h"
#include "MagickCore/blob.h"
#include "MagickCore/blob-private.h"
#include "MagickCore/cache-private.h"
#include "MagickCore/color-private.h"
#include "MagickCore/draw.h"
#include "MagickCore/exception.h"
#include "MagickCore/exception-private.h"
#include "MagickCore/cache.h"
#include "MagickCore/constitute.h"
#include "MagickCore/delegate.h"
#include "MagickCore/geometry.h"
#include "MagickCore/image-private.h"
#include "MagickCore/list.h"
#include "MagickCore/magick.h"
#include "MagickCore/memory_.h"
#include "MagickCore/monitor.h"
#include "MagickCore/option.h"
#include "MagickCore/pixel.h"
#include "MagickCore/pixel-accessor.h"
#include "MagickCore/pixel-private.h"
#include "MagickCore/quantum.h"
#include "MagickCore/quantum-private.h"
#include "MagickCore/resource_.h"
#include "MagickCore/semaphore.h"
#include "MagickCore/statistic.h"
#include "MagickCore/stream.h"
#include "MagickCore/string_.h"
#include "MagickCore/transform.h"
#include "MagickCore/utility.h"
Macros
#define GetChannelBit(mask, bit) (((size_t) (mask) >> (size_t) (bit)) & 0x01)
Functions
MagickExport PixelChannelMap * AcquirePixelChannelMap (void)
MagickExport PixelChannelMap * ClonePixelChannelMap (PixelChannelMap *channel_map)
MagickExport PixelInfo * ClonePixelInfo (const PixelInfo *pixel)
static double DecodeGamma (const double x)
MagickExport MagickRealType DecodePixelGamma (const MagickRealType pixel)
MagickExport PixelChannelMap * DestroyPixelChannelMap (PixelChannelMap *channel_map)
static double EncodeGamma (const double x)
MagickExport MagickRealType EncodePixelGamma (const MagickRealType pixel)
static void ExportCharPixel (Image *image, const RectangleInfo *roi, const char *restrict map, const QuantumType *quantum_map, void *pixels, ExceptionInfo *exception)
static void ExportDoublePixel (Image *image, const RectangleInfo *roi, const char *restrict map, const QuantumType *quantum_map, void *pixels, ExceptionInfo *exception)
static void ExportFloatPixel (Image *image, const RectangleInfo *roi, const char *restrict map, const QuantumType *quantum_map, void *pixels, ExceptionInfo *exception)
static void ExportLongPixel (Image *image, const RectangleInfo *roi, const char *restrict map, const QuantumType *quantum_map, void *pixels, ExceptionInfo *exception)
static void ExportLongLongPixel (Image *image, const RectangleInfo *roi, const char *restrict map, const QuantumType *quantum_map, void *pixels, ExceptionInfo *exception)
static void ExportQuantumPixel (Image *image, const RectangleInfo *roi, const char *restrict map, const QuantumType *quantum_map, void *pixels, ExceptionInfo *exception)
static void ExportShortPixel (Image *image, const RectangleInfo *roi, const char *restrict map, const QuantumType *quantum_map, void *pixels, ExceptionInfo *exception)
MagickExport MagickBooleanType ExportImagePixels (Image *image, const ssize_t x, const ssize_t y, const size_t width, const size_t height, const char *map, const StorageType type, void *pixels, ExceptionInfo *exception)
MagickExport void GetPixelInfo (const Image *image, PixelInfo *pixel)
static MagickRealType MagickMax (const MagickRealType x, const MagickRealType y)
static MagickRealType MagickMin (const MagickRealType x, const MagickRealType y)
MagickExport MagickRealType GetPixelIntensity (const Image *restrict image, const Quantum *restrict pixel)
static void ImportCharPixel (Image *image, const RectangleInfo *roi, const char *restrict map, const QuantumType *quantum_map, const void *pixels, ExceptionInfo *exception)
static void ImportDoublePixel (Image *image, const RectangleInfo *roi, const char *restrict map, const QuantumType *quantum_map, const void *pixels, ExceptionInfo *exception)
static void ImportFloatPixel (Image *image, const RectangleInfo *roi, const char *restrict map, const QuantumType *quantum_map, const void *pixels, ExceptionInfo *exception)
static void ImportLongPixel (Image *image, const RectangleInfo *roi, const char *restrict map, const QuantumType *quantum_map, const void *pixels, ExceptionInfo *exception)
static void ImportLongLongPixel (Image *image, const RectangleInfo *roi, const char *restrict map, const QuantumType *quantum_map, const void *pixels, ExceptionInfo *exception)
static void ImportQuantumPixel (Image *image, const RectangleInfo *roi, const char *restrict map, const QuantumType *quantum_map, const void *pixels, ExceptionInfo *exception)
static void ImportShortPixel (Image *image, const RectangleInfo *roi, const char *restrict map, const QuantumType *quantum_map, const void *pixels, ExceptionInfo *exception)
MagickExport MagickBooleanType ImportImagePixels (Image *image, const ssize_t x, const ssize_t y, const size_t width, const size_t height, const char *map, const StorageType type, const void *pixels, ExceptionInfo *exception)
static void LogPixelChannels (const Image *image)
MagickExport void InitializePixelChannelMap (Image *image)
static void CatromWeights (const double x, double(*weights)[4])
static void SplineWeights (const double x, double(*weights)[4])
static double MeshInterpolate (const PointInfo *delta, const double p, const double x, const double y)
MagickExport MagickBooleanType InterpolatePixelChannel (const Image *image, const CacheView *image_view, const PixelChannel channel, const PixelInterpolateMethod method, const double x, const double y, double *pixel, ExceptionInfo *exception)
MagickExport MagickBooleanType InterpolatePixelChannels (const Image *source, const CacheView *source_view, const Image *destination, const PixelInterpolateMethod method, const double x, const double y, Quantum *pixel, ExceptionInfo *exception)
static void AlphaBlendPixelInfo (const Image *image, const Quantum *pixel, PixelInfo *pixel_info, double *alpha)
MagickExport MagickBooleanType InterpolatePixelInfo (const Image *image, const CacheView *image_view, const PixelInterpolateMethod method, const double x, const double y, PixelInfo *pixel, ExceptionInfo *exception)
MagickExport MagickBooleanType IsFuzzyEquivalencePixel (const Image *source, const Quantum *p, const Image *destination, const Quantum *q)
MagickExport MagickBooleanType IsFuzzyEquivalencePixelInfo (const PixelInfo *p, const PixelInfo *q)
MagickExport void SetPixelChannelMask (Image *image, const ChannelType channel_mask)
MagickExport MagickBooleanType SetPixelMetaChannels (Image *image, const size_t number_meta_channels, ExceptionInfo *exception)
Macro Definition Documentation
#define GetChannelBit (mask, bit) (((size_t) (mask) >> (size_t) (bit)) & 0x01)
Function Documentation
MagickExport PixelChannelMap* AcquirePixelChannelMap (void)
Definition at line 91 of file pixel.c.
References AcquireQuantumMemory(), MaxPixelChannels, ResetMagickMemory(), ResourceLimitFatalError, and ThrowFatalException.
Referenced by AcquireImage(), and ClonePixelChannelMap().
static void AlphaBlendPixelInfo (const Image * image, const Quantum * pixel, PixelInfo * pixel_info, double * alpha) inline static
Definition at line 5356 of file pixel.c.
References _PixelInfo::alpha, _Image::alpha_trait, _PixelInfo::black, BlendPixelTrait, _PixelInfo::blue, CMYKColorspace, _Image::colorspace, GetPixelAlpha(), GetPixelBlack(), GetPixelBlue(), GetPixelGreen(), GetPixelRed(), _PixelInfo::green, QuantumScale, and _PixelInfo::red.
Referenced by InterpolatePixelInfo().
static void CatromWeights (const double x, double(*) weights[4]) inline static
Definition at line 4329 of file pixel.c.
Referenced by InterpolatePixelChannel(), InterpolatePixelChannels(), and InterpolatePixelInfo().
MagickExport PixelChannelMap* ClonePixelChannelMap (PixelChannelMap * channel_map)
Definition at line 131 of file pixel.c.
References AcquirePixelChannelMap(), CopyMagickMemory(), and MaxPixelChannels.
Referenced by CloneImage().
MagickExport PixelInfo* ClonePixelInfo (const PixelInfo * pixel)
Definition at line 168 of file pixel.c.
References AcquireQuantumMemory(), ResourceLimitFatalError, and ThrowFatalException.
Referenced by FxGetSymbol().
static double DecodeGamma (const double x) inline static
Definition at line 203 of file pixel.c.
Referenced by DecodePixelGamma().
MagickExport MagickRealType DecodePixelGamma (const MagickRealType pixel)
Definition at line 261 of file pixel.c.
References DecodeGamma(), QuantumRange, and QuantumScale.
Referenced by ConvertRGBToCMYK(), ConvertRGBToXYZ(), GetPixelInfoIntensity(), GetPixelInfoLuminance(), GetPixelIntensity(), GetPixelLuminance(), GrayscaleImage(), and sRGBTransformImage().
MagickExport PixelChannelMap* DestroyPixelChannelMap (PixelChannelMap * channel_map)
Definition at line 292 of file pixel.c.
References RelinquishMagickMemory().
Referenced by DestroyImage().
static double EncodeGamma (const double x) inline static
Definition at line 323 of file pixel.c.
Referenced by EncodePixelGamma().
MagickExport MagickRealType EncodePixelGamma (const MagickRealType pixel)
Definition at line 388 of file pixel.c.
References EncodeGamma(), QuantumRange, and QuantumScale.
Referenced by ConvertXYZToRGB(), GetPixelIntensity(), GrayscaleImage(), and TransformsRGBImage().
static void ExportCharPixel (Image * image, const RectangleInfo * roi, const char *restrict map, const QuantumType * quantum_map, void * pixels, ExceptionInfo * exception) static
Definition at line 451 of file pixel.c.
References AlphaQuantum, BlackQuantum, BlueQuantum, ClampToQuantum(), CMYKColorspace, _Image::colorspace, CyanQuantum, GetPixelAlpha(), GetPixelBlack(), GetPixelBlue(), GetPixelChannels(), GetPixelGreen(), GetPixelIntensity(), GetPixelRed(), GetVirtualPixels(), GreenQuantum, _RectangleInfo::height, IndexQuantum, LocaleCompare(), MagentaQuantum, OpacityQuantum, RedQuantum, _RectangleInfo::width, _RectangleInfo::x, _RectangleInfo::y, and YellowQuantum.
Referenced by ExportImagePixels().
static void ExportDoublePixel (Image * image, const RectangleInfo * roi, const char *restrict map, const QuantumType * quantum_map, void * pixels, ExceptionInfo * exception) static
Definition at line 657 of file pixel.c.
References AlphaQuantum, BlackQuantum, BlueQuantum, CMYKColorspace, _Image::colorspace, CyanQuantum, GetPixelAlpha(), GetPixelBlack(), GetPixelBlue(), GetPixelChannels(), GetPixelGreen(), GetPixelIntensity(), GetPixelRed(), GetVirtualPixels(), GreenQuantum, _RectangleInfo::height, IndexQuantum, LocaleCompare(), MagentaQuantum, OpacityQuantum, QuantumScale, RedQuantum, _RectangleInfo::width, _RectangleInfo::x, _RectangleInfo::y, and YellowQuantum.
Referenced by ExportImagePixels().
static void ExportFloatPixel (Image * image, const RectangleInfo * roi, const char *restrict map, const QuantumType * quantum_map, void * pixels, ExceptionInfo * exception) static
Definition at line 864 of file pixel.c.
References AlphaQuantum, BlackQuantum, BlueQuantum, CMYKColorspace, _Image::colorspace, CyanQuantum, GetPixelAlpha(), GetPixelBlack(), GetPixelBlue(), GetPixelChannels(), GetPixelGreen(), GetPixelIntensity(), GetPixelRed(), GetVirtualPixels(), GreenQuantum, _RectangleInfo::height, IndexQuantum, LocaleCompare(), MagentaQuantum, OpacityQuantum, QuantumScale, RedQuantum, _RectangleInfo::width, _RectangleInfo::x, _RectangleInfo::y, and YellowQuantum.
Referenced by ExportImagePixels().
MagickExport MagickBooleanType ExportImagePixels (Image * image, const ssize_t x, const ssize_t y, const size_t width, const size_t height, const char * map, const StorageType type, void * pixels, ExceptionInfo * exception)
Definition at line 1898 of file pixel.c.
References AcquireQuantumMemory(), AlphaQuantum, BlackQuantum, BlueQuantum, CharPixel, CMYKColorspace, _Image::colorspace, CyanQuantum, _Image::debug, DoublePixel, ExportCharPixel(), ExportDoublePixel(), ExportFloatPixel(), ExportLongLongPixel(), ExportLongPixel(), ExportQuantumPixel(), ExportShortPixel(), _Image::filename, FloatPixel, GetMagickModule, GreenQuantum, _RectangleInfo::height, ImageError, IndexQuantum, LogMagickEvent(), LongLongPixel, LongPixel, MagentaQuantum, MagickFalse, MagickSignature, MagickTrue, OpacityQuantum, OptionError, QuantumPixel, RedQuantum, RelinquishMagickMemory(), ResourceLimitError, ShortPixel, _Image::signature, ThrowMagickException(), TraceEvent, UndefinedQuantum, _RectangleInfo::width, _RectangleInfo::x, _RectangleInfo::y, and YellowQuantum.
static void ExportLongLongPixel (Image * image, const RectangleInfo * roi, const char *restrict map, const QuantumType * quantum_map, void * pixels, ExceptionInfo * exception) static
Definition at line 1276 of file pixel.c.
References AlphaQuantum, BlackQuantum, BlueQuantum, ClampToQuantum(), CMYKColorspace, _Image::colorspace, CyanQuantum, GetPixelAlpha(), GetPixelBlack(), GetPixelBlue(), GetPixelChannels(), GetPixelGreen(), GetPixelIntensity(), GetPixelRed(), GetVirtualPixels(), GreenQuantum, _RectangleInfo::height, IndexQuantum, LocaleCompare(), MagentaQuantum, OpacityQuantum, RedQuantum, _RectangleInfo::width, _RectangleInfo::x, _RectangleInfo::y, and YellowQuantum.
Referenced by ExportImagePixels().
static void ExportLongPixel (Image * image, const RectangleInfo * roi, const char *restrict map, const QuantumType * quantum_map, void * pixels, ExceptionInfo * exception) static
Definition at line 1070 of file pixel.c.
References AlphaQuantum, BlackQuantum, BlueQuantum, ClampToQuantum(), CMYKColorspace, _Image::colorspace, CyanQuantum, GetPixelAlpha(), GetPixelBlack(), GetPixelBlue(), GetPixelChannels(), GetPixelGreen(), GetPixelIntensity(), GetPixelRed(), GetVirtualPixels(), GreenQuantum, _RectangleInfo::height, IndexQuantum, LocaleCompare(), MagentaQuantum, OpacityQuantum, RedQuantum, _RectangleInfo::width, _RectangleInfo::x, _RectangleInfo::y, and YellowQuantum.
Referenced by ExportImagePixels().
static void ExportQuantumPixel (Image * image, const RectangleInfo * roi, const char *restrict map, const QuantumType * quantum_map, void * pixels, ExceptionInfo * exception) static
Definition at line 1483 of file pixel.c.
References AlphaQuantum, BlackQuantum, BlueQuantum, ClampToQuantum(), CMYKColorspace, _Image::colorspace, CyanQuantum, GetPixelAlpha(), GetPixelBlack(), GetPixelBlue(), GetPixelChannels(), GetPixelGreen(), GetPixelIntensity(), GetPixelRed(), GetVirtualPixels(), GreenQuantum, _RectangleInfo::height, IndexQuantum, LocaleCompare(), MagentaQuantum, OpacityQuantum, RedQuantum, _RectangleInfo::width, _RectangleInfo::x, _RectangleInfo::y, and YellowQuantum.
Referenced by ExportImagePixels().
static void ExportShortPixel (Image * image, const RectangleInfo * roi, const char *restrict map, const QuantumType * quantum_map, void * pixels, ExceptionInfo * exception) static
Definition at line 1692 of file pixel.c.
References AlphaQuantum, BlackQuantum, BlueQuantum, ClampToQuantum(), CMYKColorspace, _Image::colorspace, CyanQuantum, GetPixelAlpha(), GetPixelBlack(), GetPixelBlue(), GetPixelChannels(), GetPixelGreen(), GetPixelIntensity(), GetPixelRed(), GetVirtualPixels(), GreenQuantum, _RectangleInfo::height, IndexQuantum, LocaleCompare(), MagentaQuantum, OpacityQuantum, RedQuantum, _RectangleInfo::width, _RectangleInfo::x, _RectangleInfo::y, and YellowQuantum.
Referenced by ExportImagePixels().
MagickExport void GetPixelInfo (const Image * image, PixelInfo * pixel)
Definition at line 2102 of file pixel.c.
References _PixelInfo::alpha, _PixelInfo::alpha_trait, _Image::alpha_trait, _PixelInfo::black, _PixelInfo::blue, _Image::colorspace, _PixelInfo::colorspace, _Image::depth, _PixelInfo::depth, DirectClass, _PixelInfo::fuzz, _Image::fuzz, _PixelInfo::green, _PixelInfo::index, MAGICKCORE_QUANTUM_DEPTH, OpaqueAlpha, _PixelInfo::red, sRGBColorspace, _Image::storage_class, _PixelInfo::storage_class, and UndefinedPixelTrait.
Referenced by AcquireImageColormap(), AppendImages(), BlackThresholdImage(), ClassifyImageColors(), ClutImage(), ColorizeImage(), ColorMatrixImage(), CompareImagesBounds(), CompositeImage(), DistortImage(), DrawAffineImage(), DrawGradientImage(), DrawPolygonPrimitive(), DrawPrimitive(), FloodfillPaintImage(), FxGetSymbol(), GetImageBackgroundColor(), GetImageBoundingBox(), GetImageDynamicThreshold(), GetNumberColors(), GetOneCacheViewVirtualPixelInfo(), GetOneVirtualPixelInfo(), GradientImage(), HaldClutImage(), IdentifyImage(), InterpretImageProperties(), IsEquivalentImage(), IsHistogramImage(), IsPaletteImage(), LoadColorLists(), OpaquePaintImage(), QueryColorCompliance(), RandomThresholdImage(), ResamplePixelColor(), SparseColorImage(), sRGBTransformImage(), TintImage(), TransformsRGBImage(), TransparentPaintImage(), TransparentPaintImageChroma(), WhiteThresholdImage(), XShearImage(), and YShearImage().
MagickExport MagickRealType GetPixelIntensity (const Image *restrict image, const Quantum *restrict pixel)
Definition at line 2178 of file pixel.c.
References AveragePixelIntensityMethod, BrightnessPixelIntensityMethod, DecodePixelGamma(), EncodePixelGamma(), GetPixelBlue(), GetPixelGray(), GetPixelGreen(), GetPixelRed(), GRAYColorspace, LightnessPixelIntensityMethod, MagickMax(), MagickMin(), MSPixelIntensityMethod, QuantumRange, Rec601LumaPixelIntensityMethod, Rec601LuminancePixelIntensityMethod, Rec709LumaPixelIntensityMethod, Rec709LuminancePixelIntensityMethod, RGBColorspace, RMSPixelIntensityMethod, and sRGBColorspace.
Referenced by AdaptiveBlurImage(), AdaptiveSharpenImage(), BilevelImage(), BlackThresholdImage(), CompositeImage(), ConsolidateCMYKImages(), ContrastStretchImage(), ExportCharPixel(), ExportDoublePixel(), ExportFloatPixel(), ExportLongLongPixel(), ExportLongPixel(), ExportQuantumPixel(), ExportShortPixel(), HuffmanEncodeImage(), LinearStretchImage(), MagnifyImage(), MorphologyPrimitive(), OilPaintImage(), RadonTransform(), RenderPostscript(), SelectiveBlurImage(), SepiaToneImage(), SetImageMask(), ShadeImage(), sRGBTransformImage(), StreamImagePixels(), and WhiteThresholdImage().
static void ImportCharPixel (Image * image, const RectangleInfo * roi, const char *restrict map, const QuantumType * quantum_map, const void * pixels, ExceptionInfo * exception) static
Definition at line 2327 of file pixel.c.
References AlphaQuantum, BlackQuantum, BlueQuantum, CyanQuantum, GetAuthenticPixels(), GetPixelChannels(), GreenQuantum, _RectangleInfo::height, IndexQuantum, LocaleCompare(), MagentaQuantum, MagickFalse, OpacityQuantum, RedQuantum, SetPixelAlpha(), SetPixelBlack(), SetPixelBlue(), SetPixelGray(), SetPixelGreen(), SetPixelRed(), SyncAuthenticPixels(), _RectangleInfo::width, _RectangleInfo::x, _RectangleInfo::y, and YellowQuantum.
Referenced by ImportImagePixels().
static void ImportDoublePixel (Image * image, const RectangleInfo * roi, const char *restrict map, const QuantumType * quantum_map, const void * pixels, ExceptionInfo * exception) static
Definition at line 2587 of file pixel.c.
References AlphaQuantum, BlackQuantum, BlueQuantum, ClampToQuantum(), CyanQuantum, GetAuthenticPixels(), GetPixelChannels(), GreenQuantum, _RectangleInfo::height, IndexQuantum, LocaleCompare(), MagentaQuantum, MagickFalse, OpacityQuantum, QuantumRange, RedQuantum, SetPixelAlpha(), SetPixelBlack(), SetPixelBlue(), SetPixelGray(), SetPixelGreen(), SetPixelRed(), SyncAuthenticPixels(), _RectangleInfo::width, _RectangleInfo::x, _RectangleInfo::y, and YellowQuantum.
Referenced by ImportImagePixels().
static void ImportFloatPixel (Image * image, const RectangleInfo * roi, const char *restrict map, const QuantumType * quantum_map, const void * pixels, ExceptionInfo * exception) static
Definition at line 2827 of file pixel.c.
References AlphaQuantum, BlackQuantum, BlueQuantum, ClampToQuantum(), CyanQuantum, GetAuthenticPixels(), GetPixelChannels(), GreenQuantum, _RectangleInfo::height, IndexQuantum, LocaleCompare(), MagentaQuantum, MagickFalse, OpacityQuantum, QuantumRange, RedQuantum, SetPixelAlpha(), SetPixelBlack(), SetPixelBlue(), SetPixelGray(), SetPixelGreen(), SetPixelRed(), SyncAuthenticPixels(), _RectangleInfo::width, _RectangleInfo::x, _RectangleInfo::y, and YellowQuantum.
Referenced by ImportImagePixels().
MagickExport MagickBooleanType ImportImagePixels (Image * image, const ssize_t x, const ssize_t y, const size_t width, const size_t height, const char * map, const StorageType type, const void * pixels, ExceptionInfo * exception)
Definition at line 3947 of file pixel.c.
References AcquireQuantumMemory(), _Image::alpha_trait, AlphaQuantum, BlackQuantum, BlendPixelTrait, BlueQuantum, CharPixel, CMYKColorspace, CyanQuantum, _Image::debug, DirectClass, DoublePixel, _Image::filename, FloatPixel, GetMagickModule, GRAYColorspace, GreenQuantum, _RectangleInfo::height, ImportCharPixel(), ImportDoublePixel(), ImportFloatPixel(), ImportLongLongPixel(), ImportLongPixel(), ImportQuantumPixel(), ImportShortPixel(), IndexQuantum, LogMagickEvent(), LongLongPixel, LongPixel, MagentaQuantum, MagickFalse, MagickSignature, MagickTrue, OpacityQuantum, OptionError, QuantumPixel, RedQuantum, RelinquishMagickMemory(), ResourceLimitError, SetImageColorspace(), SetImageStorageClass(), ShortPixel, _Image::signature, ThrowBinaryException, ThrowMagickException(), TraceEvent, UndefinedQuantum, _RectangleInfo::width, _RectangleInfo::x, _RectangleInfo::y, and YellowQuantum.
Referenced by ConstituteImage().
static void ImportLongLongPixel (Image * image, const RectangleInfo * roi, const char *restrict map, const QuantumType * quantum_map, const void * pixels, ExceptionInfo * exception) static
Definition at line 3287 of file pixel.c.
References AlphaQuantum, BlackQuantum, BlueQuantum, CyanQuantum, GetAuthenticPixels(), GetPixelChannels(), GreenQuantum, _RectangleInfo::height, IndexQuantum, LocaleCompare(), MagentaQuantum, MagickFalse, OpacityQuantum, RedQuantum, SetPixelAlpha(), SetPixelBlack(), SetPixelBlue(), SetPixelGray(), SetPixelGreen(), SetPixelRed(), SyncAuthenticPixels(), _RectangleInfo::width, _RectangleInfo::x, _RectangleInfo::y, and YellowQuantum.
Referenced by ImportImagePixels().
static void ImportLongPixel (Image * image, const RectangleInfo * roi, const char *restrict map, const QuantumType * quantum_map, const void * pixels, ExceptionInfo * exception) static
Definition at line 3067 of file pixel.c.
References AlphaQuantum, BlackQuantum, BlueQuantum, CyanQuantum, GetAuthenticPixels(), GetPixelChannels(), GreenQuantum, _RectangleInfo::height, IndexQuantum, LocaleCompare(), MagentaQuantum, MagickFalse, OpacityQuantum, RedQuantum, SetPixelAlpha(), SetPixelBlack(), SetPixelBlue(), SetPixelGray(), SetPixelGreen(), SetPixelRed(), SyncAuthenticPixels(), _RectangleInfo::width, _RectangleInfo::x, _RectangleInfo::y, and YellowQuantum.
Referenced by ImportImagePixels().
static void ImportQuantumPixel (Image * image, const RectangleInfo * roi, const char *restrict map, const QuantumType * quantum_map, const void * pixels, ExceptionInfo * exception) static
Definition at line 3507 of file pixel.c.
References AlphaQuantum, BlackQuantum, BlueQuantum, CyanQuantum, GetAuthenticPixels(), GetPixelChannels(), GreenQuantum, _RectangleInfo::height, IndexQuantum, LocaleCompare(), MagentaQuantum, MagickFalse, OpacityQuantum, RedQuantum, SetPixelAlpha(), SetPixelBlack(), SetPixelBlue(), SetPixelGray(), SetPixelGreen(), SetPixelRed(), SyncAuthenticPixels(), _RectangleInfo::width, _RectangleInfo::x, _RectangleInfo::y, and YellowQuantum.
Referenced by ImportImagePixels().
static void ImportShortPixel (Image * image, const RectangleInfo * roi, const char *restrict map, const QuantumType * quantum_map, const void * pixels, ExceptionInfo * exception) static
Definition at line 3727 of file pixel.c.
References AlphaQuantum, BlackQuantum, BlueQuantum, CyanQuantum, GetAuthenticPixels(), GetPixelChannels(), GreenQuantum, _RectangleInfo::height, IndexQuantum, LocaleCompare(), MagentaQuantum, MagickFalse, OpacityQuantum, RedQuantum, SetPixelAlpha(), SetPixelBlack(), SetPixelBlue(), SetPixelGray(), SetPixelGreen(), SetPixelRed(), SyncAuthenticPixels(), _RectangleInfo::width, _RectangleInfo::x, _RectangleInfo::y, and YellowQuantum.
Referenced by ImportImagePixels().
MagickExport void InitializePixelChannelMap (Image * image)
Definition at line 4236 of file pixel.c.
References _Image::alpha_trait, AlphaPixelChannel, BlackPixelChannel, BlendPixelTrait, BluePixelChannel, _Image::channel_map, _Image::channel_mask, CMYKColorspace, _Image::colorspace, CopyPixelTrait, _Image::debug, GRAYColorspace, GreenPixelChannel, IndexPixelChannel, LogPixelChannels(), MagickFalse, MagickSignature, MaxPixelChannels, MetaPixelChannel, _Image::number_channels, _Image::number_meta_channels, PseudoClass, _Image::read_mask, ReadMaskPixelChannel, RedPixelChannel, ResetMagickMemory(), SetImageChannelMask(), SetPixelChannelAttributes(), _Image::signature, _Image::storage_class, UndefinedPixelTrait, UpdatePixelTrait, _Image::write_mask, and WriteMaskPixelChannel.
Referenced by OpenPixelCache().
MagickExport MagickBooleanType InterpolatePixelChannel (const Image * image, const CacheView * image_view, const PixelChannel channel, const PixelInterpolateMethod method, const double x, const double y, double * pixel, ExceptionInfo * exception)
Definition at line 4391 of file pixel.c.
References AlphaPixelChannel, Average16InterpolatePixel, Average9InterpolatePixel, AverageInterpolatePixel, BilinearInterpolatePixel, BlendInterpolatePixel, BlendPixelTrait, CatromInterpolatePixel, CatromWeights(), GetCacheViewVirtualPixels(), GetPixelAlpha(), GetPixelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelLuminance(), IntegerInterpolatePixel, _Image::interpolate, MagickFalse, MagickSignature, MagickTrue, MeshInterpolate(), MeshInterpolatePixel, NearestInterpolatePixel, PerceptibleReciprocal(), QuantumScale, _Image::signature, SplineInterpolatePixel, SplineWeights(), UndefinedInterpolatePixel, _PointInfo::x, and _PointInfo::y.
MagickExport MagickBooleanType InterpolatePixelChannels (const Image * source, const CacheView * source_view, const Image * destination, const PixelInterpolateMethod method, const double x, const double y, Quantum * pixel, ExceptionInfo * exception)
Definition at line 4816 of file pixel.c.
References Average16InterpolatePixel, Average9InterpolatePixel, AverageInterpolatePixel, BilinearInterpolatePixel, BlendInterpolatePixel, BlendPixelTrait, CatromInterpolatePixel, CatromWeights(), ClampToQuantum(), GetCacheViewVirtualPixels(), GetPixelAlpha(), GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelLuminance(), IntegerInterpolatePixel, _Image::interpolate, MagickFalse, MagickSignature, MagickTrue, MeshInterpolate(), MeshInterpolatePixel, NearestInterpolatePixel, PerceptibleReciprocal(), QuantumScale, SetPixelChannel(), _Image::signature, SplineInterpolatePixel, SplineWeights(), UndefinedInterpolatePixel, UndefinedPixelTrait, _PointInfo::x, and _PointInfo::y.
Referenced by ImplodeImage(), InterpolativeResizeImage(), SpreadImage(), SwirlImage(), and WaveImage().
MagickExport MagickBooleanType InterpolatePixelInfo (const Image * image, const CacheView * image_view, const PixelInterpolateMethod method, const double x, const double y, PixelInfo * pixel, ExceptionInfo * exception)
Definition at line 5381 of file pixel.c.
References _PixelInfo::alpha, AlphaBlendPixelInfo(), Average16InterpolatePixel, Average9InterpolatePixel, AverageInterpolatePixel, _Image::background_color, BackgroundInterpolatePixel, BilinearInterpolatePixel, _PixelInfo::black, BlendInterpolatePixel, _PixelInfo::blue, CatromInterpolatePixel, CatromWeights(), CMYKColorspace, _Image::colorspace, GetCacheViewVirtualPixels(), GetPixelChannels(), GetPixelInfoPixel(), GetPixelLuminance(), _PixelInfo::green, IntegerInterpolatePixel, _Image::interpolate, MagickFalse, MagickSignature, MagickTrue, MeshInterpolate(), MeshInterpolatePixel, NearestInterpolatePixel, PerceptibleReciprocal(), _PixelInfo::red, _Image::signature, SplineInterpolatePixel, SplineWeights(), UndefinedInterpolatePixel, _PointInfo::x, and _PointInfo::y.
Referenced by ClutImage(), CompositeImage(), DrawAffineImage(), FxGetSymbol(), HaldClutImage(), and ResamplePixelColor().
MagickExport MagickBooleanType IsFuzzyEquivalencePixel (const Image * source, const Quantum * p, const Image * destination, const Quantum * q)
Definition at line 5854 of file pixel.c.
References _Image::alpha_trait, BlendPixelTrait, _Image::colorspace, _Image::fuzz, GetPixelAlpha(), GetPixelBlue(), GetPixelGreen(), GetPixelRed(), HSBColorspace, HSLColorspace, HWBColorspace, MagickEpsilon, MagickFalse, MagickMax(), MagickSQ1_2, MagickTrue, QuantumRange, and QuantumScale.
Referenced by CompositeImage().
MagickExport MagickBooleanType IsFuzzyEquivalencePixelInfo (const PixelInfo * p, const PixelInfo * q)
Definition at line 5963 of file pixel.c.
References _PixelInfo::alpha, _PixelInfo::alpha_trait, _PixelInfo::black, BlendPixelTrait, _PixelInfo::blue, CMYKColorspace, _PixelInfo::colorspace, _PixelInfo::fuzz, _PixelInfo::green, HSBColorspace, HSLColorspace, HWBColorspace, IsPixelInfoEquivalent(), MagickEpsilon, MagickFalse, MagickMax(), MagickSQ1_2, MagickTrue, OpaqueAlpha, QuantumRange, QuantumScale, and _PixelInfo::red.
Referenced by ComparePixels(), DrawPrimitive(), FloodfillPaintImage(), GetImageBoundingBox(), IsEquivalentImage(), OpaquePaintImage(), and TransparentPaintImage().
static void LogPixelChannels (const Image * image) static
Definition at line 4142 of file pixel.c.
References AlphaPixelChannel, BlackPixelChannel, BlendPixelTrait, BluePixelChannel, CMYKColorspace, _Image::colorspace, ConcatenateMagickString(), CopyPixelTrait, _Image::filename, GetMagickModule, GetPixelChannelChannel(), GetPixelChannelTraits(), GRAYColorspace, GreenPixelChannel, IndexPixelChannel, LogMagickEvent(), MaxTextExtent, MetaPixelChannel, _Image::number_channels, PixelEvent, PseudoClass, ReadMaskPixelChannel, RedPixelChannel, _Image::storage_class, UpdatePixelTrait, and WriteMaskPixelChannel.
Referenced by InitializePixelChannelMap(), and SetPixelChannelMask().
static MagickRealType MagickMax (const MagickRealType x, const MagickRealType y) inline static
Definition at line 2162 of file pixel.c.
Referenced by GetPixelIntensity(), IsFuzzyEquivalencePixel(), and IsFuzzyEquivalencePixelInfo().
static MagickRealType MagickMin (const MagickRealType x, const MagickRealType y) inline static
Definition at line 2170 of file pixel.c.
Referenced by GetPixelIntensity().
static double MeshInterpolate (const PointInfo * delta, const double p, const double x, const double y) inline static
Definition at line 4376 of file pixel.c.
References _PointInfo::x, and _PointInfo::y.
Referenced by InterpolatePixelChannel(), InterpolatePixelChannels(), and InterpolatePixelInfo().
MagickExport void SetPixelChannelMask (Image * image, const ChannelType channel_mask)
Definition at line 6075 of file pixel.c.
References _Image::alpha_trait, AlphaPixelChannel, BlendPixelTrait, CopyPixelTrait, _Image::debug, GetChannelBit, GetMagickModule, GetPixelChannelChannel(), GetPixelChannels(), IndexPixelChannel, LogMagickEvent(), LogPixelChannels(), MagickFalse, PixelEvent, PseudoClass, _Image::read_mask, ReadMaskPixelChannel, SetPixelChannelTraits(), _Image::storage_class, UpdatePixelTrait, _Image::write_mask, and WriteMaskPixelChannel.
Referenced by ChannelFxImage(), FxChannelStatistics(), MontageImageList(), SetImageChannelMask(), ShadowImage(), and SyncImageSettings().
MagickExport MagickBooleanType SetPixelMetaChannels (Image * image, const size_t number_meta_channels, ExceptionInfo * exception)
Definition at line 6132 of file pixel.c.
References _Image::number_meta_channels, and SyncImagePixelCache().
Referenced by ChannelFxImage().
static void SplineWeights (const double x, double(*) weights[4]) inline static
Definition at line 4356 of file pixel.c.
Referenced by InterpolatePixelChannel(), InterpolatePixelChannels(), and InterpolatePixelInfo().