MagickCore: prepress.c File Reference
prepress.c File Reference
#include "MagickCore/studio.h"
#include "MagickCore/cache-view.h"
#include "MagickCore/exception.h"
#include "MagickCore/exception-private.h"
#include "MagickCore/hashmap.h"
#include "MagickCore/image.h"
#include "MagickCore/list.h"
#include "MagickCore/memory_.h"
#include "MagickCore/pixel-accessor.h"
#include "MagickCore/prepress.h"
#include "MagickCore/resource_.h"
#include "MagickCore/registry.h"
#include "MagickCore/semaphore.h"
#include "MagickCore/splay-tree.h"
#include "MagickCore/string_.h"
#include "MagickCore/thread-private.h"
Functions
MagickExport double GetImageTotalInkDensity (Image *image, ExceptionInfo *exception)
Function Documentation
MagickExport double GetImageTotalInkDensity (Image * image, ExceptionInfo * exception)
Definition at line 86 of file prepress.c.
References AcquireVirtualCacheView(), CMYKColorspace, _Image::colorspace, _Image::columns, _Image::debug, DestroyCacheView(), _Image::filename, GetCacheViewVirtualPixels(), GetMagickModule, GetPixelBlack(), GetPixelBlue(), GetPixelChannels(), GetPixelGreen(), GetPixelRed(), ImageError, LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, _Image::rows, _Image::signature, ThrowMagickException(), and TraceEvent.
Referenced by IdentifyImage().