MagickCore: prepress.h File Reference
prepress.h File Reference
Functions
MagickExport double GetImageTotalInkDensity (Image *image, ExceptionInfo *)
Function Documentation
MagickExport double GetImageTotalInkDensity (Image * image, ExceptionInfo *)
Definition at line 86 of file prepress.c.
References AcquireVirtualCacheView(), CMYKColorspace, _Image::colorspace, _Image::columns, _Image::debug, DestroyCacheView(), _Image::filename, GetCacheViewVirtualPixels(), GetMagickModule, GetPixelBlack(), GetPixelBlue(), GetPixelChannels(), GetPixelGreen(), GetPixelRed(), ImageError, LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, _Image::rows, _Image::signature, ThrowMagickException(), and TraceEvent.
Referenced by IdentifyImage().