MagickCore: profile.h File Reference
profile.h File Reference
#include "MagickCore/string_.h"
Typedefs
typedef struct _ProfileInfo ProfileInfo
Enumerations
enum RenderingIntent {
UndefinedIntent, SaturationIntent, PerceptualIntent, AbsoluteIntent,
RelativeIntent
}
Functions
MagickExport char * GetNextImageProfile (const Image *)
MagickExport const StringInfo * GetImageProfile (const Image *, const char *)
MagickExport MagickBooleanType CloneImageProfiles (Image *, const Image *)
MagickExport MagickBooleanType DeleteImageProfile (Image *, const char *)
MagickExport MagickBooleanType ProfileImage (Image *, const char *, const void *, const size_t, ExceptionInfo *)
MagickExport MagickBooleanType SetImageProfile (Image *, const char *, const StringInfo *, ExceptionInfo *)
MagickExport StringInfo * RemoveImageProfile (Image *, const char *)
MagickExport void DestroyImageProfiles (Image *)
MagickExport void ResetImageProfileIterator (const Image *)
Typedef Documentation
typedef struct _ProfileInfo ProfileInfo
Definition at line 27 of file profile.h.
Enumeration Type Documentation
enum RenderingIntent
Enumerator
UndefinedIntent
SaturationIntent
PerceptualIntent
AbsoluteIntent
RelativeIntent
Definition at line 30 of file profile.h.
Function Documentation
MagickExport MagickBooleanType CloneImageProfiles (Image * , const Image *)
MagickExport MagickBooleanType DeleteImageProfile (Image * , const char *)
MagickExport void DestroyImageProfiles (Image *)
MagickExport const StringInfo* GetImageProfile (const Image * , const char *)
Definition at line 258 of file profile.c.
References CopyMagickString(), _Image::debug, _Image::filename, GetMagickModule, GetValueFromSplayTree(), LogMagickEvent(), MagickFalse, MagickSignature, MaxTextExtent, _Image::profiles, _Image::signature, and TraceEvent.
Referenced by Get8BIMProperty(), GetEXIFProperty(), GetIPTCProperty(), GetXMPProperty(), IdentifyImage(), ProfileImage(), ReadImage(), and SyncImageProfiles().
MagickExport char* GetNextImageProfile (const Image *)
Definition at line 301 of file profile.c.
References _Image::debug, _Image::filename, GetMagickModule, GetNextKeyInSplayTree(), LogMagickEvent(), MagickFalse, MagickSignature, _Image::profiles, _Image::signature, and TraceEvent.
Referenced by IdentifyImage(), ProfileImage(), and ThumbnailImage().
MagickExport MagickBooleanType ProfileImage (Image * , const char * , const void * , const size_t , ExceptionInfo *)
MagickExport StringInfo* RemoveImageProfile (Image * , const char *)
Definition at line 1012 of file profile.c.
References _Image::debug, _Image::filename, GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, _Image::profiles, RemoveNodeFromSplayTree(), _Image::signature, and TraceEvent.
MagickExport void ResetImageProfileIterator (const Image *)
Definition at line 1052 of file profile.c.
References _Image::debug, _Image::filename, GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, _Image::profiles, ResetSplayTreeIterator(), _Image::signature, and TraceEvent.
Referenced by IdentifyImage(), ProfileImage(), and ThumbnailImage().
MagickExport MagickBooleanType SetImageProfile (Image * , const char * , const StringInfo * , ExceptionInfo *)
Definition at line 1260 of file profile.c.
References AddValueToSplayTree(), CloneStringInfo(), CompareSplayTreeString(), ConstantString(), CopyMagickString(), _Image::debug, DestroyProfile(), _Image::filename, FormatLocaleString(), GetImageProperty(), GetMagickModule, GetProfilesFromResourceBlock(), LocaleCompare(), LogMagickEvent(), MagickFalse, MagickSignature, MaxTextExtent, NewSplayTree(), _Image::profiles, RelinquishMagickMemory(), _Image::signature, and TraceEvent.
Referenced by GetProfilesFromResourceBlock(), ProfileImage(), and SetImageProperty().