MagickCore: property.h File Reference
property.h File Reference
Functions
MagickExport char * GetNextImageProperty (const Image *)
MagickExport char * InterpretImageProperties (ImageInfo *, Image *, const char *, ExceptionInfo *)
MagickExport char * RemoveImageProperty (Image *, const char *)
MagickExport const char * GetImageProperty (const Image *, const char *, ExceptionInfo *)
MagickExport const char * GetMagickProperty (ImageInfo *, Image *, const char *, ExceptionInfo *)
MagickExport MagickBooleanType CloneImageProperties (Image *, const Image *)
MagickExport MagickBooleanType DefineImageProperty (Image *, const char *, ExceptionInfo *)
MagickExport MagickBooleanType DeleteImageProperty (Image *, const char *)
MagickExport MagickBooleanType FormatImageProperty (Image *, const char *, const char *,...) magick_attribute((__format__(__printf__
MagickExport MagickBooleanType SetImageProperty (Image *, const char *, const char *, ExceptionInfo *)
MagickExport void DestroyImageProperties (Image *)
MagickExport void ResetImagePropertyIterator (const Image *)
Function Documentation
MagickExport MagickBooleanType CloneImageProperties (Image * , const Image *)
MagickExport MagickBooleanType DefineImageProperty (Image * , const char * , ExceptionInfo *)
MagickExport MagickBooleanType DeleteImageProperty (Image * , const char *)
MagickExport void DestroyImageProperties (Image *)
MagickExport MagickBooleanType FormatImageProperty (Image * , const char * , const char * , ...)
MagickExport const char* GetImageProperty (const Image * , const char * , ExceptionInfo *)
MagickExport const char * GetMagickProperty (ImageInfo * , Image * , const char * , ExceptionInfo *)
Definition at line 2502 of file property.c.
References _Image::alpha_trait, BasePath, BlendPixelTrait, _Image::colorspace, CommandOptionToMnemonic(), ConcatenateMagickString(), CopyMagickString(), _Image::debug, _ImageInfo::debug, _Image::depth, ExtensionPath, _Image::filename, _ImageInfo::filename, FormatLocaleString(), FormatMagickSize(), _Image::gamma, GetBlobSize(), GetImageArtifact(), GetImageKurtosis(), GetImageListLength(), GetImageMean(), GetImageOption(), GetImageRange(), GetImageType(), GetMagickCopyright(), GetMagickModule, GetMagickPrecision(), GetMagickPropertyLetter(), GetMagickVersion(), GetPathComponent(), _ImageInfo::group, HeadPath, IfMagickTrue, IsImageOpaque(), LocaleCompare(), LocaleLower(), LogMagickEvent(), _Image::magick, _Image::magick_columns, _Image::magick_filename, _Image::magick_rows, MagickBooleanOptions, MagickColorspaceOptions, MagickFalse, MagickOrientationOptions, MagickTypeOptions, MaxTextExtent, _ImageInfo::number_scenes, _Image::orientation, _Image::resolution, _Image::scene, _ImageInfo::scene, SetImageArtifact(), SetImageOption(), TraceEvent, _ImageInfo::unique, WarnNoImageInfoReturn, WarnNoImageReturn, _PointInfo::x, _PointInfo::y, and _ImageInfo::zero.
Referenced by InterpretImageFilename(), and InterpretImageProperties().
MagickExport char* GetNextImageProperty (const Image *)
MagickExport char * InterpretImageProperties (ImageInfo * , Image * , const char * , ExceptionInfo *)
MagickExport char * RemoveImageProperty (Image * , const char *)
Definition at line 3521 of file property.c.
References _Image::debug, _Image::filename, GetMagickModule, IfMagickTrue, LogMagickEvent(), MagickSignature, _Image::properties, RemoveNodeFromSplayTree(), _Image::signature, and TraceEvent.
MagickExport void ResetImagePropertyIterator (const Image *)
Definition at line 3563 of file property.c.
References _Image::debug, _Image::filename, GetMagickModule, IfMagickTrue, LogMagickEvent(), MagickSignature, _Image::properties, ResetSplayTreeIterator(), _Image::signature, and TraceEvent.
Referenced by IdentifyImage(), and InterpretImageProperties().
MagickExport MagickBooleanType SetImageProperty (Image * , const char * , const char * , ExceptionInfo *)
Definition at line 3608 of file property.c.
References AcquireImageInfo(), AddValueToSplayTree(), AllCompliance, _Image::background_color, _ChromaticityInfo::blue_primary, _Image::chromaticity, _Image::colorspace, CompareSplayTreeString(), _Image::compose, _Image::compression, ConstantString(), CopyMagickString(), _Image::debug, _Image::delay, DeleteImageProperty(), _Image::depth, DestroyImageInfo(), DestroyString(), _Image::dispose, _Image::filename, _ImageInfo::filename, FileToStringInfo(), _Image::gamma, GetMagickModule, GetPageGeometry(), _Image::gravity, GreaterValue, _ChromaticityInfo::green_primary, IfMagickTrue, _Image::intensity, _Image::interpolate, IssRGBColorspace(), _Image::iterations, LessValue, LocaleCompare(), LocaleNCompare(), LogMagickEvent(), _ImageInfo::magick, MagickColorspaceOptions, MagickComposeOptions, MagickCompressOptions, MagickDisposeOptions, MagickFalse, MagickGravityOptions, MagickIntentOptions, MagickInterpolateOptions, MagickResolutionOptions, MagickSignature, MagickTrue, MaxTextExtent, NewSplayTree(), OptionError, _Image::page, ParseAbsoluteGeometry(), ParseCommandOption(), ParseGeometry(), PerceptualIntent, _Image::properties, QueryColorCompliance(), _ChromaticityInfo::red_primary, RelinquishMagickMemory(), _Image::rendering_intent, ResetMagickMemory(), _Image::resolution, _GeometryInfo::rho, SetImageInfo(), SetImageProfile(), _GeometryInfo::sigma, SigmaValue, _Image::signature, StringToDouble(), StringToUnsignedLong(), ThrowMagickException(), _Image::ticks_per_second, _Image::tile_offset, TraceEvent, UndefinedIntent, _Image::units, _ChromaticityInfo::white_point, _PrimaryInfo::x, _PointInfo::x, _PrimaryInfo::y, _PointInfo::y, and _PrimaryInfo::z.
Referenced by DefineImageProperty(), FormatImageProperty(), Get8BIMProperty(), GetEXIFProperty(), GetIPTCProperty(), PreviewImage(), ReadImage(), SignatureImage(), and ThumbnailImage().