MagickCore: quantize.c File Reference
quantize.c File Reference
#include "MagickCore/studio.h"
#include "MagickCore/attribute.h"
#include "MagickCore/cache-view.h"
#include "MagickCore/color.h"
#include "MagickCore/color-private.h"
#include "MagickCore/colormap.h"
#include "MagickCore/colorspace.h"
#include "MagickCore/colorspace-private.h"
#include "MagickCore/enhance.h"
#include "MagickCore/exception.h"
#include "MagickCore/exception-private.h"
#include "MagickCore/histogram.h"
#include "MagickCore/image.h"
#include "MagickCore/image-private.h"
#include "MagickCore/list.h"
#include "MagickCore/memory_.h"
#include "MagickCore/monitor.h"
#include "MagickCore/monitor-private.h"
#include "MagickCore/option.h"
#include "MagickCore/pixel-accessor.h"
#include "MagickCore/pixel-private.h"
#include "MagickCore/quantize.h"
#include "MagickCore/quantum.h"
#include "MagickCore/quantum-private.h"
#include "MagickCore/resource_.h"
#include "MagickCore/string_.h"
#include "MagickCore/thread-private.h"
Data Structures
struct _RealPixelInfo
struct _NodeInfo
struct _Nodes
struct _CubeInfo
Macros
#define CacheShift 2
#define ErrorQueueLength 16
#define MaxNodes 266817
#define MaxTreeDepth 8
#define NodesInAList 1920
#define AssignImageTag "Assign/Image"
#define ClassifyImageTag "Classify/Image"
#define RedShift(pixel) (((pixel) >> CacheShift) << (0*(8-CacheShift)))
#define GreenShift(pixel) (((pixel) >> CacheShift) << (1*(8-CacheShift)))
#define BlueShift(pixel) (((pixel) >> CacheShift) << (2*(8-CacheShift)))
#define AlphaShift(pixel) (((pixel) >> CacheShift) << (3*(8-CacheShift)))
#define DitherImageTag "Dither/Image"
#define DitherImageTag "Dither/Image"
#define PosterizeImageTag "Posterize/Image"
#define PosterizePixel(pixel)
#define ReduceImageTag "Reduce/Image"
Typedefs
typedef struct _RealPixelInfo RealPixelInfo
typedef struct _NodeInfo NodeInfo
typedef struct _Nodes Nodes
typedef struct _CubeInfo CubeInfo
Functions
static CubeInfo * GetCubeInfo (const QuantizeInfo *, const size_t, const size_t)
static NodeInfo * GetNodeInfo (CubeInfo *, const size_t, const size_t, NodeInfo *)
static MagickBooleanType AssignImageColors (Image *, CubeInfo *, ExceptionInfo *)
static MagickBooleanType ClassifyImageColors (CubeInfo *, const Image *, ExceptionInfo *)
static MagickBooleanType DitherImage (Image *, CubeInfo *, ExceptionInfo *)
static MagickBooleanType SetGrayscaleImage (Image *, ExceptionInfo *)
static size_t DefineImageColormap (Image *, CubeInfo *, NodeInfo *)
static void ClosestColor (const Image *, CubeInfo *, const NodeInfo *)
static void DestroyCubeInfo (CubeInfo *)
static void PruneLevel (const Image *, CubeInfo *, const NodeInfo *)
static void PruneToCubeDepth (const Image *, CubeInfo *, const NodeInfo *)
static void ReduceImageColors (const Image *, CubeInfo *)
MagickExport QuantizeInfo * AcquireQuantizeInfo (const ImageInfo *image_info)
static void AssociateAlphaPixel (const Image *image, const CubeInfo *cube_info, const Quantum *pixel, RealPixelInfo *alpha_pixel)
static void AssociateAlphaPixelInfo (const Image *image, const CubeInfo *cube_info, const PixelInfo *pixel, RealPixelInfo *alpha_pixel)
static Quantum ClampPixel (const MagickRealType value)
static size_t ColorToNodeId (const CubeInfo *cube_info, const RealPixelInfo *pixel, size_t index)
static void SetAssociatedAlpha (const Image *image, CubeInfo *cube_info)
MagickExport QuantizeInfo * CloneQuantizeInfo (const QuantizeInfo *quantize_info)
MagickExport MagickBooleanType CompressImageColormap (Image *image, ExceptionInfo *exception)
MagickExport QuantizeInfo * DestroyQuantizeInfo (QuantizeInfo *quantize_info)
static RealPixelInfo ** DestroyPixelThreadSet (RealPixelInfo **pixels)
static RealPixelInfo ** AcquirePixelThreadSet (const size_t count)
static ssize_t CacheOffset (CubeInfo *cube_info, const RealPixelInfo *pixel)
static MagickBooleanType FloydSteinbergDither (Image *image, CubeInfo *cube_info, ExceptionInfo *exception)
static MagickBooleanType RiemersmaDither (Image *, CacheView *, CubeInfo *, const unsigned int, ExceptionInfo *exception)
static void Riemersma (Image *image, CacheView *image_view, CubeInfo *cube_info, const size_t level, const unsigned int direction, ExceptionInfo *exception)
static ssize_t MagickMax (const ssize_t x, const ssize_t y)
static ssize_t MagickMin (const ssize_t x, const ssize_t y)
MagickExport MagickBooleanType GetImageQuantizeError (Image *image, ExceptionInfo *exception)
MagickExport void GetQuantizeInfo (QuantizeInfo *quantize_info)
static ssize_t MagickRound (double x)
MagickExport MagickBooleanType PosterizeImage (Image *image, const size_t levels, const DitherMethod dither_method, ExceptionInfo *exception)
static void PruneChild (const Image *image, CubeInfo *cube_info, const NodeInfo *node_info)
static MagickBooleanType DirectToColormapImage (Image *image, ExceptionInfo *exception)
MagickExport MagickBooleanType QuantizeImage (const QuantizeInfo *quantize_info, Image *image, ExceptionInfo *exception)
MagickExport MagickBooleanType QuantizeImages (const QuantizeInfo *quantize_info, Image *images, ExceptionInfo *exception)
static void Reduce (const Image *image, CubeInfo *cube_info, const NodeInfo *node_info)
MagickExport MagickBooleanType RemapImage (const QuantizeInfo *quantize_info, Image *image, const Image *remap_image, ExceptionInfo *exception)
MagickExport MagickBooleanType RemapImages (const QuantizeInfo *quantize_info, Image *images, const Image *remap_image, ExceptionInfo *exception)
static int IntensityCompare (const void *x, const void *y)
Macro Definition Documentation
#define AlphaShift (pixel) (((pixel) >> CacheShift) << (3*(8-CacheShift)))
Referenced by CacheOffset().
#define AssignImageTag "Assign/Image"
Referenced by AssignImageColors(), DirectToColormapImage(), and QuantizeImages().
#define BlueShift (pixel) (((pixel) >> CacheShift) << (2*(8-CacheShift)))
Referenced by CacheOffset().
#define CacheShift 2
Definition at line 209 of file quantize.c.
Referenced by GetCubeInfo().
#define ClassifyImageTag "Classify/Image"
Referenced by ClassifyImageColors().
#define DitherImageTag "Dither/Image"
Referenced by FloydSteinbergDither(), OrderedPosterizeImage(), and RiemersmaDither().
#define DitherImageTag "Dither/Image"
#define ErrorQueueLength 16
Definition at line 213 of file quantize.c.
Referenced by DitherImage(), GetCubeInfo(), and RiemersmaDither().
#define GreenShift (pixel) (((pixel) >> CacheShift) << (1*(8-CacheShift)))
Referenced by CacheOffset().
#define MaxNodes 266817
Definition at line 214 of file quantize.c.
Referenced by ClassifyImageColors().
#define MaxTreeDepth 8
Definition at line 215 of file quantize.c.
Referenced by AssignImageColors(), ClassifyImageColors(), CompressImageColormap(), FloydSteinbergDither(), GetCubeInfo(), PosterizeImage(), RemapImage(), RemapImages(), and RiemersmaDither().
#define NodesInAList 1920
Definition at line 216 of file quantize.c.
Referenced by GetNodeInfo().
#define PosterizeImageTag "Posterize/Image"
Referenced by PosterizeImage().
#define PosterizePixel (pixel)
Value:
(Quantum) (QuantumRange*(MagickRound(\
  QuantumScale*pixel*(levels-1)))/MagickMax((ssize_t) levels-1,1))
Referenced by PosterizeImage().
#define RedShift (pixel) (((pixel) >> CacheShift) << (0*(8-CacheShift)))
Referenced by CacheOffset().
#define ReduceImageTag "Reduce/Image"
Referenced by ReduceImageColors().
Typedef Documentation
typedef struct _CubeInfo CubeInfo
typedef struct _NodeInfo NodeInfo
typedef struct _Nodes Nodes
typedef struct _RealPixelInfo RealPixelInfo
Function Documentation
static RealPixelInfo** AcquirePixelThreadSet (const size_t count) static
Definition at line 1432 of file quantize.c.
References AcquireQuantumMemory(), DestroyPixelThreadSet(), GetMagickResourceLimit(), ResetMagickMemory(), and ThreadResource.
Referenced by FloydSteinbergDither(), and ProfileImage().
MagickExport QuantizeInfo* AcquireQuantizeInfo (const ImageInfo * image_info)
Definition at line 370 of file quantize.c.
References AcquireMagickMemory(), _ImageInfo::dither, _QuantizeInfo::dither_method, GetImageOption(), GetQuantizeInfo(), MagickDitherOptions, MagickFalse, _QuantizeInfo::measure_error, NoDitherMethod, ParseCommandOption(), ResourceLimitFatalError, RiemersmaDitherMethod, ThrowFatalException, and _ImageInfo::verbose.
Referenced by PosterizeImage(), SetImageType(), and UniqueImageColors().
static MagickBooleanType AssignImageColors (Image * image, CubeInfo * cube_info, ExceptionInfo * exception) static
Definition at line 507 of file quantize.c.
References AcquireAuthenticCacheView(), AcquireImageColormap(), _PixelInfo::alpha, AssignImageTag, _CubeInfo::associate_alpha, AssociateAlphaPixel(), _PixelInfo::blue, _NodeInfo::child, ClampToQuantum(), ClosestColor(), CMYKColorspace, _CubeInfo::color_number, _Image::colormap, _CubeInfo::colors, _Image::colors, _QuantizeInfo::colorspace, _Image::colorspace, ColorToNodeId(), _Image::columns, DefineImageColormap(), DestroyCacheView(), _CubeInfo::distance, _QuantizeInfo::dither_method, DitherImage(), _Image::filename, GetCacheViewAuthenticPixels(), GetImageQuantizeError(), GetPixelChannels(), GetPixelInfoIntensity(), GetPixelInfoPixel(), GRAYColorspace, _PixelInfo::green, IsPixelEquivalent(), IssRGBCompatibleColorspace(), MagickFalse, MagickTrue, MaxTreeDepth, _QuantizeInfo::measure_error, NoDitherMethod, _QuantizeInfo::number_colors, _NodeInfo::parent, _Image::progress_monitor, PseudoClass, _CubeInfo::quantize_info, QuantumRange, _PixelInfo::red, ResourceLimitError, _CubeInfo::root, _Image::rows, SetImageProgress(), SetPixelAlpha(), SetPixelBlue(), SetPixelGreen(), SetPixelIndex(), SetPixelRed(), sRGBColorspace, _Image::storage_class, SyncCacheViewAuthenticPixels(), SyncImage(), _CubeInfo::target, ThrowBinaryException, TransformImageColorspace(), _CubeInfo::transparent_index, _CubeInfo::transparent_pixels, and UndefinedColorspace.
Referenced by QuantizeImage(), QuantizeImages(), RemapImage(), and RemapImages().
static void AssociateAlphaPixel (const Image * image, const CubeInfo * cube_info, const Quantum * pixel, RealPixelInfo * alpha_pixel) inline static
Definition at line 435 of file quantize.c.
References _RealPixelInfo::alpha, _CubeInfo::associate_alpha, _RealPixelInfo::blue, GetPixelAlpha(), GetPixelBlue(), GetPixelGreen(), GetPixelRed(), _RealPixelInfo::green, MagickFalse, OpaqueAlpha, QuantumScale, and _RealPixelInfo::red.
Referenced by AssignImageColors(), ClassifyImageColors(), FloydSteinbergDither(), and RiemersmaDither().
static void AssociateAlphaPixelInfo (const Image * image, const CubeInfo * cube_info, const PixelInfo * pixel, RealPixelInfo * alpha_pixel) inline static
Definition at line 457 of file quantize.c.
References _PixelInfo::alpha, _RealPixelInfo::alpha, _CubeInfo::associate_alpha, _PixelInfo::blue, _RealPixelInfo::blue, _PixelInfo::green, _RealPixelInfo::green, MagickFalse, OpaqueAlpha, QuantumScale, _PixelInfo::red, and _RealPixelInfo::red.
Referenced by FloydSteinbergDither(), and RiemersmaDither().
static ssize_t CacheOffset (CubeInfo * cube_info, const RealPixelInfo * pixel) inline static
Definition at line 1458 of file quantize.c.
References _RealPixelInfo::alpha, AlphaShift, _CubeInfo::associate_alpha, _RealPixelInfo::blue, BlueShift, ClampPixel(), _RealPixelInfo::green, GreenShift, MagickFalse, _RealPixelInfo::red, and RedShift.
Referenced by FloydSteinbergDither(), and RiemersmaDither().
static Quantum ClampPixel (const MagickRealType value) inline static
Definition at line 480 of file quantize.c.
References QuantumRange.
Referenced by CacheOffset(), ClassifyImageColors(), ColorToNodeId(), FloydSteinbergDither(), and RiemersmaDither().
static MagickBooleanType ClassifyImageColors (CubeInfo * cube_info, const Image * image, ExceptionInfo * exception)
Definition at line 768 of file quantize.c.
References AcquireVirtualCacheView(), _RealPixelInfo::alpha, _CubeInfo::associate_alpha, AssociateAlphaPixel(), _RealPixelInfo::blue, _NodeInfo::child, ClampPixel(), ClassifyImageTag, CMYKColorspace, _CubeInfo::colors, _QuantizeInfo::colorspace, _Image::colorspace, ColorToNodeId(), _Image::columns, _CubeInfo::depth, DestroyCacheView(), _Image::filename, GetCacheViewVirtualPixels(), GetMagickModule, GetNodeInfo(), GetPixelChannels(), GetPixelInfoPixel(), _RealPixelInfo::green, IsPixelEquivalent(), IssRGBCompatibleColorspace(), MagickFalse, MagickTrue, _CubeInfo::maximum_colors, MaxNodes, MaxTreeDepth, _CubeInfo::nodes, _NodeInfo::number_unique, PruneLevel(), PruneToCubeDepth(), _NodeInfo::quantize_error, _CubeInfo::quantize_info, QuantumRange, QuantumScale, _RealPixelInfo::red, ResourceLimitError, _CubeInfo::root, _Image::rows, SetAssociatedAlpha(), SetImageProgress(), sRGBColorspace, ThrowMagickException(), _NodeInfo::total_color, TransformImageColorspace(), and UndefinedColorspace.
Referenced by QuantizeImage(), QuantizeImages(), RemapImage(), and RemapImages().
MagickExport QuantizeInfo* CloneQuantizeInfo (const QuantizeInfo * quantize_info)
Definition at line 1037 of file quantize.c.
References AcquireMagickMemory(), _QuantizeInfo::colorspace, _QuantizeInfo::dither_method, GetQuantizeInfo(), _QuantizeInfo::measure_error, _QuantizeInfo::number_colors, ResourceLimitFatalError, ThrowFatalException, and _QuantizeInfo::tree_depth.
Referenced by GetCubeInfo().
static void ClosestColor (const Image * image, CubeInfo * cube_info, const NodeInfo * node_info) static
Definition at line 1085 of file quantize.c.
References _CubeInfo::associate_alpha, _NodeInfo::child, _NodeInfo::color_number, _CubeInfo::color_number, _Image::colormap, _CubeInfo::distance, MagickFalse, _NodeInfo::number_unique, QuantumScale, and _CubeInfo::target.
Referenced by AssignImageColors(), FloydSteinbergDither(), and RiemersmaDither().
static size_t ColorToNodeId (const CubeInfo * cube_info, const RealPixelInfo * pixel, size_t index) inline static
Definition at line 493 of file quantize.c.
References _RealPixelInfo::alpha, _CubeInfo::associate_alpha, _RealPixelInfo::blue, ClampPixel(), _RealPixelInfo::green, MagickFalse, and _RealPixelInfo::red.
Referenced by AssignImageColors(), ClassifyImageColors(), FloydSteinbergDither(), and RiemersmaDither().
MagickExport MagickBooleanType CompressImageColormap (Image * image, ExceptionInfo * exception)
Definition at line 1180 of file quantize.c.
References _Image::colors, _Image::debug, _Image::filename, GetMagickModule, GetQuantizeInfo(), IsPaletteImage(), LogMagickEvent(), MagickFalse, MagickSignature, MaxTreeDepth, _QuantizeInfo::number_colors, QuantizeImage(), _Image::signature, TraceEvent, and _QuantizeInfo::tree_depth.
static size_t DefineImageColormap (Image * image, CubeInfo * cube_info, NodeInfo * node_info) static
Definition at line 1229 of file quantize.c.
References _RealPixelInfo::alpha, _CubeInfo::associate_alpha, _RealPixelInfo::blue, _NodeInfo::child, ClampToQuantum(), _NodeInfo::color_number, _Image::colormap, _Image::colors, _RealPixelInfo::green, MagickFalse, _NodeInfo::number_unique, OpaqueAlpha, PerceptibleReciprocal(), QuantumRange, QuantumScale, _RealPixelInfo::red, _NodeInfo::total_color, _CubeInfo::transparent_index, and _CubeInfo::transparent_pixels.
Referenced by AssignImageColors().
static void DestroyCubeInfo (CubeInfo * cube_info)
Definition at line 1332 of file quantize.c.
References _CubeInfo::cache, DestroyQuantizeInfo(), _Nodes::next, _CubeInfo::node_queue, _Nodes::nodes, _CubeInfo::quantize_info, and RelinquishMagickMemory().
Referenced by QuantizeImage(), QuantizeImages(), RemapImage(), and RemapImages().
static RealPixelInfo** DestroyPixelThreadSet (RealPixelInfo ** pixels) static
Definition at line 1419 of file quantize.c.
References GetMagickResourceLimit(), RelinquishMagickMemory(), and ThreadResource.
Referenced by AcquirePixelThreadSet(), FloydSteinbergDither(), and ProfileImage().
MagickExport QuantizeInfo* DestroyQuantizeInfo (QuantizeInfo * quantize_info)
Definition at line 1378 of file quantize.c.
References GetMagickModule, LogMagickEvent(), MagickSignature, RelinquishMagickMemory(), _QuantizeInfo::signature, and TraceEvent.
Referenced by DestroyCubeInfo(), PosterizeImage(), SetImageType(), and UniqueImageColors().
static MagickBooleanType DirectToColormapImage (Image * image, ExceptionInfo * exception) static
Definition at line 2657 of file quantize.c.
References AcquireAuthenticCacheView(), AcquireImageColormap(), _PixelInfo::alpha, AssignImageTag, _PixelInfo::blue, _Image::colormap, _Image::colors, _Image::columns, DestroyCacheView(), _Image::filename, GetCacheViewAuthenticPixels(), GetPixelAlpha(), GetPixelBlue(), GetPixelChannels(), GetPixelGreen(), GetPixelRed(), _PixelInfo::green, MagickFalse, MagickTrue, _PixelInfo::red, ResourceLimitError, _Image::rows, SetImageProgress(), SetPixelIndex(), SyncCacheViewAuthenticPixels(), and ThrowBinaryException.
Referenced by QuantizeImage().
static MagickBooleanType DitherImage (Image * image, CubeInfo * cube_info, ExceptionInfo * exception)
Definition at line 1933 of file quantize.c.
References AcquireAuthenticCacheView(), _Image::columns, DestroyCacheView(), _QuantizeInfo::dither_method, _CubeInfo::error, ErrorQueueLength, FloydSteinbergDither(), ForgetGravity, MagickMax(), NorthGravity, _CubeInfo::offset, _CubeInfo::quantize_info, ResetMagickMemory(), Riemersma(), RiemersmaDither(), RiemersmaDitherMethod, _Image::rows, _CubeInfo::span, _CubeInfo::x, and _CubeInfo::y.
Referenced by AssignImageColors().
static MagickBooleanType FloydSteinbergDither (Image * image, CubeInfo * cube_info, ExceptionInfo * exception) static
Definition at line 1477 of file quantize.c.
References AcquireAuthenticCacheView(), AcquirePixelThreadSet(), _PixelInfo::alpha, _RealPixelInfo::alpha, _CubeInfo::associate_alpha, AssociateAlphaPixel(), AssociateAlphaPixelInfo(), _PixelInfo::blue, _RealPixelInfo::blue, _CubeInfo::cache, CacheOffset(), _NodeInfo::child, ClampPixel(), ClampToQuantum(), ClosestColor(), _CubeInfo::color_number, _Image::colormap, ColorToNodeId(), _Image::columns, DestroyCacheView(), DestroyPixelThreadSet(), _CubeInfo::distance, DitherImageTag, GetCacheViewAuthenticPixels(), GetOpenMPThreadId(), GetPixelChannels(), _PixelInfo::green, _RealPixelInfo::green, MagickFalse, MagickTrue, MaxTreeDepth, _QuantizeInfo::measure_error, _NodeInfo::parent, _Image::progress_monitor, PseudoClass, _CubeInfo::quantize_info, QuantumRange, _PixelInfo::red, _RealPixelInfo::red, _CubeInfo::root, _Image::rows, SetImageProgress(), SetPixelAlpha(), SetPixelBlue(), SetPixelGreen(), SetPixelIndex(), SetPixelRed(), _Image::storage_class, SyncCacheViewAuthenticPixels(), and _CubeInfo::target.
Referenced by DitherImage().
static CubeInfo * GetCubeInfo (const QuantizeInfo * quantize_info, const size_t depth, const size_t maximum_colors) static
Definition at line 2006 of file quantize.c.
References AcquireMagickMemory(), AcquireQuantumMemory(), _CubeInfo::cache, CacheShift, CloneQuantizeInfo(), _CubeInfo::depth, _QuantizeInfo::dither_method, ErrorQueueLength, GetNodeInfo(), _CubeInfo::maximum_colors, MaxTreeDepth, NoDitherMethod, _NodeInfo::parent, PerceptibleReciprocal(), _CubeInfo::quantize_info, QuantumRange, ResetMagickMemory(), _CubeInfo::root, and _CubeInfo::weights.
Referenced by QuantizeImage(), QuantizeImages(), RemapImage(), and RemapImages().
MagickExport MagickBooleanType GetImageQuantizeError (Image * image, ExceptionInfo * exception)
Definition at line 2189 of file quantize.c.
References AcquireVirtualCacheView(), _PixelInfo::alpha, _Image::alpha_trait, BlendPixelTrait, _PixelInfo::blue, _Image::colormap, _Image::columns, _Image::debug, DestroyCacheView(), DirectClass, _Image::error, _Image::filename, GetCacheViewVirtualPixels(), GetMagickModule, GetNumberColors(), GetPixelAlpha(), GetPixelBlue(), GetPixelChannels(), GetPixelGreen(), GetPixelIndex(), GetPixelRed(), _PixelInfo::green, LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, _ErrorInfo::mean_error_per_pixel, _ErrorInfo::normalized_maximum_error, _ErrorInfo::normalized_mean_error, QuantumScale, _PixelInfo::red, ResetMagickMemory(), _Image::rows, _Image::signature, _Image::storage_class, _Image::total_colors, and TraceEvent.
Referenced by AssignImageColors().
static NodeInfo * GetNodeInfo (CubeInfo * cube_info, const size_t id, const size_t level, NodeInfo * parent) static
Definition at line 2111 of file quantize.c.
References AcquireMagickMemory(), AcquireQuantumMemory(), _CubeInfo::free_nodes, _NodeInfo::id, _NodeInfo::level, _Nodes::next, _CubeInfo::next_node, _CubeInfo::node_queue, _Nodes::nodes, _CubeInfo::nodes, NodesInAList, _NodeInfo::parent, and ResetMagickMemory().
Referenced by ClassifyImageColors(), and GetCubeInfo().
MagickExport void GetQuantizeInfo (QuantizeInfo * quantize_info)
Definition at line 2295 of file quantize.c.
References _QuantizeInfo::colorspace, _QuantizeInfo::dither_method, GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, _QuantizeInfo::measure_error, _QuantizeInfo::number_colors, ResetMagickMemory(), RiemersmaDitherMethod, _QuantizeInfo::signature, TraceEvent, and UndefinedColorspace.
Referenced by AcquireQuantizeInfo(), CloneQuantizeInfo(), CompressImageColormap(), and PreviewImage().
static int IntensityCompare (const void * x, const void * y) static
Definition at line 3248 of file quantize.c.
References GetPixelInfoIntensity().
Referenced by SetGrayscaleImage().
static ssize_t MagickMax (const ssize_t x, const ssize_t y) inline static
Definition at line 1919 of file quantize.c.
Referenced by DitherImage().
static ssize_t MagickMin (const ssize_t x, const ssize_t y) inline static
Definition at line 1926 of file quantize.c.
Referenced by PosterizeImage().
static ssize_t MagickRound (double x) inline static
Definition at line 2340 of file quantize.c.
MagickExport MagickBooleanType PosterizeImage (Image * image, const size_t levels, const DitherMethod dither_method, ExceptionInfo * exception)
Definition at line 2350 of file quantize.c.
References AcquireAuthenticCacheView(), AcquireQuantizeInfo(), _PixelInfo::alpha, _Image::alpha_trait, BlendPixelTrait, _PixelInfo::blue, CMYKColorspace, _Image::colormap, _Image::colors, _Image::colorspace, _Image::columns, _Image::debug, DestroyCacheView(), DestroyQuantizeInfo(), _QuantizeInfo::dither_method, _Image::filename, GetCacheViewAuthenticPixels(), GetMagickModule, GetPixelAlpha(), GetPixelAlphaTraits(), GetPixelBlack(), GetPixelBlackTraits(), GetPixelBlue(), GetPixelBlueTraits(), GetPixelChannels(), GetPixelGreen(), GetPixelGreenTraits(), GetPixelRed(), GetPixelRedTraits(), _PixelInfo::green, LogMagickEvent(), MagickFalse, MagickMin(), MagickSignature, MagickTrue, MaxColormapSize, MaxTreeDepth, _QuantizeInfo::number_colors, PosterizeImageTag, PosterizePixel, _Image::progress_monitor, PseudoClass, QuantizeImage(), _PixelInfo::red, _Image::rows, SetImageProgress(), SetPixelAlpha(), SetPixelBlack(), SetPixelBlue(), SetPixelGreen(), SetPixelRed(), _Image::signature, _Image::storage_class, SyncCacheViewAuthenticPixels(), TraceEvent, _QuantizeInfo::tree_depth, and UpdatePixelTrait.
static void PruneChild (const Image * image, CubeInfo * cube_info, const NodeInfo * node_info) static
Definition at line 2499 of file quantize.c.
References _RealPixelInfo::alpha, _CubeInfo::associate_alpha, _RealPixelInfo::blue, _NodeInfo::child, _RealPixelInfo::green, _NodeInfo::id, MagickFalse, _CubeInfo::nodes, _NodeInfo::number_unique, _NodeInfo::parent, _RealPixelInfo::red, and _NodeInfo::total_color.
Referenced by PruneLevel(), PruneToCubeDepth(), and Reduce().
static void PruneLevel (const Image * image, CubeInfo * cube_info, const NodeInfo * node_info)
Definition at line 2559 of file quantize.c.
References _CubeInfo::associate_alpha, _NodeInfo::child, _CubeInfo::depth, _NodeInfo::level, MagickFalse, and PruneChild().
Referenced by ClassifyImageColors().
static void PruneToCubeDepth (const Image * image, CubeInfo * cube_info, const NodeInfo * node_info)
Definition at line 2606 of file quantize.c.
References _CubeInfo::associate_alpha, _NodeInfo::child, _CubeInfo::depth, _NodeInfo::level, MagickFalse, and PruneChild().
Referenced by ClassifyImageColors().
MagickExport MagickBooleanType QuantizeImage (const QuantizeInfo * quantize_info, Image * image, ExceptionInfo * exception)
Definition at line 2719 of file quantize.c.
References _Image::alpha_trait, AssignImageColors(), BlendPixelTrait, ClassifyImageColors(), _Image::colors, _Image::columns, _Image::debug, DestroyCubeInfo(), DirectToColormapImage(), _QuantizeInfo::dither_method, _Image::filename, GetCubeInfo(), GetMagickModule, IsImageGray(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, MaxColormapSize, NoDitherMethod, _QuantizeInfo::number_colors, PseudoClass, ReduceImageColors(), ResourceLimitError, _Image::rows, SetGrayscaleImage(), _QuantizeInfo::signature, _Image::signature, _Image::storage_class, ThrowBinaryException, TraceEvent, and _QuantizeInfo::tree_depth.
Referenced by CompressImageColormap(), PosterizeImage(), PreviewImage(), QuantizeImages(), SetImageType(), and UniqueImageColors().
MagickExport MagickBooleanType QuantizeImages (const QuantizeInfo * quantize_info, Image * images, ExceptionInfo * exception)
Definition at line 2820 of file quantize.c.
References AssignImageColors(), AssignImageTag, ClassifyImageColors(), _Image::client_data, _Image::debug, DestroyCubeInfo(), _QuantizeInfo::dither_method, _Image::filename, GetCubeInfo(), GetImageListLength(), GetMagickModule, GetNextImageInList(), LogMagickEvent(), MagickFalse, MagickSignature, MaxColormapSize, NoDitherMethod, _QuantizeInfo::number_colors, QuantizeImage(), ReduceImageColors(), ResourceLimitError, SetImageProgress(), SetImageProgressMonitor(), _QuantizeInfo::signature, _Image::signature, ThrowMagickException(), TraceEvent, and _QuantizeInfo::tree_depth.
Referenced by RemapImages().
static void Reduce (const Image * image, CubeInfo * cube_info, const NodeInfo * node_info) static
Definition at line 2959 of file quantize.c.
References _CubeInfo::associate_alpha, _NodeInfo::child, _CubeInfo::colors, MagickFalse, _CubeInfo::next_threshold, _NodeInfo::number_unique, PruneChild(), _CubeInfo::pruning_threshold, and _NodeInfo::quantize_error.
Referenced by ReduceImageColors().
static void ReduceImageColors (const Image * image, CubeInfo * cube_info)
Definition at line 3043 of file quantize.c.
References _CubeInfo::colors, MagickFalse, _CubeInfo::maximum_colors, _CubeInfo::next_threshold, _CubeInfo::pruning_threshold, _NodeInfo::quantize_error, Reduce(), ReduceImageTag, _CubeInfo::root, and SetImageProgress().
Referenced by QuantizeImage(), and QuantizeImages().
MagickExport MagickBooleanType RemapImage (const QuantizeInfo * quantize_info, Image * image, const Image * remap_image, ExceptionInfo * exception)
Definition at line 3101 of file quantize.c.
References AssignImageColors(), ClassifyImageColors(), _CubeInfo::colors, _Image::debug, DestroyCubeInfo(), _Image::filename, GetCubeInfo(), GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, MaxTreeDepth, _QuantizeInfo::number_colors, _CubeInfo::quantize_info, ResourceLimitError, _Image::signature, ThrowBinaryException, and TraceEvent.
MagickExport MagickBooleanType RemapImages (const QuantizeInfo * quantize_info, Image * images, const Image * remap_image, ExceptionInfo * exception)
Definition at line 3167 of file quantize.c.
References AssignImageColors(), ClassifyImageColors(), _CubeInfo::colors, _Image::debug, DestroyCubeInfo(), _Image::filename, GetCubeInfo(), GetMagickModule, GetNextImageInList(), LogMagickEvent(), MagickFalse, MagickSignature, MaxTreeDepth, _QuantizeInfo::number_colors, _CubeInfo::quantize_info, QuantizeImages(), ResourceLimitError, _Image::signature, ThrowBinaryException, and TraceEvent.
static void Riemersma (Image * image, CacheView * image_view, CubeInfo * cube_info, const size_t level, const unsigned int direction, ExceptionInfo * exception) static
Definition at line 1670 of file quantize.c.
References EastGravity, NorthGravity, RiemersmaDither(), SouthGravity, and WestGravity.
Referenced by DitherImage().
static MagickBooleanType RiemersmaDither (Image * image, CacheView * image_view, CubeInfo * cube_info, const unsigned int direction, ExceptionInfo * exception) static
Definition at line 1799 of file quantize.c.
References _PixelInfo::alpha, _RealPixelInfo::alpha, _CubeInfo::associate_alpha, AssociateAlphaPixel(), AssociateAlphaPixelInfo(), _PixelInfo::blue, _RealPixelInfo::blue, _CubeInfo::cache, CacheOffset(), _NodeInfo::child, ClampPixel(), ClampToQuantum(), ClosestColor(), _CubeInfo::color_number, _Image::colormap, ColorToNodeId(), _Image::columns, CopyMagickMemory(), _CubeInfo::distance, DitherImageTag, EastGravity, _CubeInfo::error, ErrorQueueLength, GetCacheViewAuthenticPixels(), _PixelInfo::green, _RealPixelInfo::green, MagickFalse, MagickTrue, MaxTreeDepth, _QuantizeInfo::measure_error, NorthGravity, _CubeInfo::offset, _NodeInfo::parent, PseudoClass, _CubeInfo::quantize_info, QuantumRange, _PixelInfo::red, _RealPixelInfo::red, _CubeInfo::root, _Image::rows, SetImageProgress(), SetPixelAlpha(), SetPixelBlue(), SetPixelGreen(), SetPixelIndex(), SetPixelRed(), SouthGravity, _CubeInfo::span, _Image::storage_class, SyncCacheViewAuthenticPixels(), _CubeInfo::target, _CubeInfo::weights, WestGravity, _CubeInfo::x, and _CubeInfo::y.
Referenced by DitherImage(), and Riemersma().
static void SetAssociatedAlpha (const Image * image, CubeInfo * cube_info) inline static
Definition at line 753 of file quantize.c.
References _Image::alpha_trait, _CubeInfo::associate_alpha, BlendPixelTrait, _QuantizeInfo::colorspace, GRAYColorspace, MagickFalse, MagickTrue, _QuantizeInfo::number_colors, _CubeInfo::quantize_info, and TransparentColorspace.
Referenced by ClassifyImageColors().
static MagickBooleanType SetGrayscaleImage (Image * image, ExceptionInfo * exception)
Definition at line 3268 of file quantize.c.
References AcquireAuthenticCacheView(), AcquireImageColormap(), AcquireQuantumMemory(), _PixelInfo::alpha, BilevelType, _PixelInfo::blue, _Image::colormap, _Image::colors, _Image::columns, DestroyCacheView(), _Image::filename, GetCacheViewAuthenticPixels(), GetPixelBlue(), GetPixelChannels(), GetPixelGreen(), GetPixelIndex(), GetPixelRed(), GRAYColorspace, GrayscaleType, _PixelInfo::green, IntensityCompare(), IsImageMonochrome(), IsPixelInfoEquivalent(), MagickFalse, MagickSignature, MagickTrue, MaxMap, PseudoClass, _PixelInfo::red, RelinquishMagickMemory(), ResourceLimitError, _Image::rows, SetPixelIndex(), _Image::signature, _Image::storage_class, SyncCacheViewAuthenticPixels(), ThrowBinaryException, TransformImageColorspace(), and _Image::type.
Referenced by QuantizeImage().