MagickCore: quantum.h File Reference
quantum.h File Reference
#include "MagickCore/image.h"
#include "MagickCore/semaphore.h"
Typedefs
typedef struct _QuantumInfo QuantumInfo
Enumerations
enum EndianType { UndefinedEndian, LSBEndian, MSBEndian }
enum QuantumAlphaType { UndefinedQuantumAlpha, AssociatedQuantumAlpha, DisassociatedQuantumAlpha }
enum QuantumFormatType { UndefinedQuantumFormat, FloatingPointQuantumFormat, SignedQuantumFormat, UnsignedQuantumFormat }
enum QuantumType {
UndefinedQuantum, AlphaQuantum, BGRAQuantum, BGROQuantum,
BGRQuantum, BlackQuantum, BlueQuantum, CbYCrAQuantum,
CbYCrQuantum, CbYCrYQuantum, CMYKAQuantum, CMYKOQuantum,
CMYKQuantum, CyanQuantum, GrayAlphaQuantum, GrayQuantum,
GreenQuantum, IndexAlphaQuantum, IndexQuantum, MagentaQuantum,
OpacityQuantum, RedQuantum, RGBAQuantum, RGBOQuantum,
RGBPadQuantum, RGBQuantum, YellowQuantum
}
Functions
static Quantum ClampToQuantum (const MagickRealType value)
MagickExport EndianType GetQuantumEndian (const QuantumInfo *)
MagickExport MagickBooleanType SetQuantumDepth (const Image *, QuantumInfo *, const size_t)
MagickExport MagickBooleanType SetQuantumEndian (const Image *, QuantumInfo *, const EndianType)
MagickExport MagickBooleanType SetQuantumFormat (const Image *, QuantumInfo *, const QuantumFormatType)
MagickExport MagickBooleanType SetQuantumPad (const Image *, QuantumInfo *, const size_t)
MagickExport QuantumFormatType GetQuantumFormat (const QuantumInfo *)
MagickExport QuantumInfo * AcquireQuantumInfo (const ImageInfo *, Image *)
MagickExport QuantumInfo * DestroyQuantumInfo (QuantumInfo *)
MagickExport QuantumType GetQuantumType (Image *, ExceptionInfo *)
MagickExport size_t ExportQuantumPixels (const Image *, CacheView *, QuantumInfo *, const QuantumType, unsigned char *, ExceptionInfo *)
MagickExport size_t GetQuantumExtent (const Image *, const QuantumInfo *, const QuantumType)
MagickExport size_t ImportQuantumPixels (const Image *, CacheView *, QuantumInfo *, const QuantumType, const unsigned char *, ExceptionInfo *)
MagickExport unsigned char * GetQuantumPixels (const QuantumInfo *)
MagickExport void GetQuantumInfo (const ImageInfo *, QuantumInfo *)
MagickExport void SetQuantumAlphaType (QuantumInfo *, const QuantumAlphaType)
MagickExport void SetQuantumImageType (Image *, const QuantumType)
MagickExport void SetQuantumMinIsWhite (QuantumInfo *, const MagickBooleanType)
MagickExport void SetQuantumPack (QuantumInfo *, const MagickBooleanType)
MagickExport void SetQuantumQuantum (QuantumInfo *, const size_t)
MagickExport void SetQuantumScale (QuantumInfo *, const double)
Typedef Documentation
typedef struct _QuantumInfo QuantumInfo
Definition at line 81 of file quantum.h.
Enumeration Type Documentation
enum EndianType
Enumerator
UndefinedEndian
LSBEndian
MSBEndian
Definition at line 28 of file quantum.h.
enum QuantumAlphaType
Enumerator
UndefinedQuantumAlpha
AssociatedQuantumAlpha
DisassociatedQuantumAlpha
Definition at line 35 of file quantum.h.
enum QuantumFormatType
Enumerator
UndefinedQuantumFormat
FloatingPointQuantumFormat
SignedQuantumFormat
UnsignedQuantumFormat
Definition at line 42 of file quantum.h.
enum QuantumType
Enumerator
UndefinedQuantum
AlphaQuantum
BGRAQuantum
BGROQuantum
BGRQuantum
BlackQuantum
BlueQuantum
CbYCrAQuantum
CbYCrQuantum
CbYCrYQuantum
CMYKAQuantum
CMYKOQuantum
CMYKQuantum
CyanQuantum
GrayAlphaQuantum
GrayQuantum
GreenQuantum
IndexAlphaQuantum
IndexQuantum
MagentaQuantum
OpacityQuantum
RedQuantum
RGBAQuantum
RGBOQuantum
RGBPadQuantum
RGBQuantum
YellowQuantum
Definition at line 50 of file quantum.h.
Function Documentation
MagickExport QuantumInfo* AcquireQuantumInfo (const ImageInfo * , Image *)
static Quantum ClampToQuantum (const MagickRealType value) inline static
Definition at line 84 of file quantum.h.
References QuantumRange.
Referenced by AdaptiveBlurImage(), AdaptiveSharpenImage(), AddNoiseImage(), ApplyFunction(), AssignImageColors(), BlueShiftImage(), ChannelFxImage(), Classify(), ClutImage(), ColorDecisionListImage(), ColorizeImage(), ColorToNodeId(), CompositeImage(), CompositeOverImage(), CompositePixelOver(), ConcatenateColorComponent(), ConcatentateHexColorComponent(), ContrastImage(), ContrastStretchImage(), DefineImageColormap(), DrawImage(), DrawPrimitive(), EnhanceImage(), EqualizeImage(), EvaluateImage(), EvaluateImages(), ExportGrayAlphaQuantum(), ExportGrayQuantum(), ExportQuantumPixels(), FlattenPixelInfo(), FloydSteinbergDither(), FxImage(), GammaImage(), GetImageBackgroundColor(), GetImageDepth(), GetOneAuthenticPixel(), GetOneAuthenticPixelFromCache(), GetOneAuthenticPixelFromStream(), GetOneCacheViewAuthenticPixel(), GetOneCacheViewVirtualMethodPixel(), GetOneCacheViewVirtualPixel(), GetOneVirtualPixel(), GetOneVirtualPixelFromCache(), GetOneVirtualPixelFromStream(), GetVirtualPixelsFromNexus(), HaldClutImage(), HorizontalFilter(), ImportAlphaQuantum(), ImportBGRAQuantum(), ImportBGRQuantum(), ImportBlackQuantum(), ImportBlueQuantum(), ImportCMYKAQuantum(), ImportCMYKQuantum(), ImportDoublePixel(), ImportFloatPixel(), ImportGrayAlphaQuantum(), ImportGrayQuantum(), ImportGreenQuantum(), ImportIndexAlphaQuantum(), ImportIndexQuantum(), ImportOpacityQuantum(), ImportQuantumPixels(), ImportRedQuantum(), ImportRGBAQuantum(), ImportRGBQuantum(), InterpolatePixelChannels(), LevelImage(), LinearStretchImage(), ModulateImage(), MorphImages(), MorphologyPrimitive(), MorphologyPrimitiveDirect(), MotionBlurImage(), OilPaintImage(), OrderedPosterizeImage(), PerceptibleImage(), PlasmaPixel(), PolynomialImage(), PrintChannelStatistics(), QueryColorCompliance(), RadialBlurImage(), RaiseImage(), RenderPostscript(), ResamplePixelColor(), RiemersmaDither(), ScaleImage(), SelectiveBlurImage(), SeparateImage(), SepiaToneImage(), SetImageDepth(), SetPixelInfoPixel(), ShadeImage(), SimilarityImage(), SketchImage(), sRGBTransformImage(), StatisticImage(), StreamImagePixels(), TransformsRGBImage(), UniqueColorsToImage(), UnsharpMaskImage(), and VerticalFilter().
MagickExport QuantumInfo * DestroyQuantumInfo (QuantumInfo *)
Definition at line 214 of file quantum.c.
References DestroyQuantumPixels(), DestroySemaphoreInfo(), MagickSignature, _QuantumInfo::pixels, RelinquishMagickMemory(), _QuantumInfo::semaphore, and _QuantumInfo::signature.
Referenced by AcquireQuantumInfo(), and DestroyStreamInfo().
MagickExport size_t ExportQuantumPixels (const Image * , CacheView * , QuantumInfo * , const QuantumType , unsigned char * , ExceptionInfo *)
MagickExport EndianType GetQuantumEndian (const QuantumInfo *)
Definition at line 352 of file quantum.c.
References _QuantumInfo::endian, MagickSignature, and _QuantumInfo::signature.
MagickExport size_t GetQuantumExtent (const Image * , const QuantumInfo * , const QuantumType)
MagickExport QuantumFormatType GetQuantumFormat (const QuantumInfo *)
Definition at line 381 of file quantum.c.
References _QuantumInfo::format, MagickSignature, and _QuantumInfo::signature.
MagickExport void GetQuantumInfo (const ImageInfo * , QuantumInfo *)
MagickExport unsigned char* GetQuantumPixels (const QuantumInfo *)
Definition at line 483 of file quantum.c.
References GetOpenMPThreadId(), MagickSignature, _QuantumInfo::pixels, and _QuantumInfo::signature.
Referenced by ExportQuantumPixels(), and ImportQuantumPixels().
MagickExport QuantumType GetQuantumType (Image * , ExceptionInfo *)
Definition at line 515 of file quantum.c.
References _Image::alpha_trait, BlendPixelTrait, CMYKAQuantum, CMYKColorspace, CMYKQuantum, _Image::colorspace, _Image::debug, _Image::filename, GetMagickModule, GrayAlphaQuantum, GrayQuantum, IndexAlphaQuantum, IndexQuantum, IsImageGray(), LogMagickEvent(), MagickFalse, MagickSignature, PseudoClass, RGBAQuantum, RGBQuantum, _Image::signature, _Image::storage_class, and TraceEvent.
MagickExport size_t ImportQuantumPixels (const Image * , CacheView * , QuantumInfo * , const QuantumType , const unsigned char * , ExceptionInfo *)
Definition at line 3414 of file quantum-import.c.
References _QuantumInfo::alpha_type, AlphaQuantum, BGRAQuantum, BGROQuantum, BGRQuantum, BlackQuantum, BlueQuantum, CbYCrAQuantum, CbYCrQuantum, CbYCrYQuantum, ClampToQuantum(), CMYKAQuantum, CMYKOQuantum, CMYKQuantum, CyanQuantum, _Image::debug, DisassociatedQuantumAlpha, _Image::filename, GetAuthenticPixelQueue(), GetCacheViewAuthenticPixelQueue(), GetCacheViewExtent(), GetImageExtent(), GetMagickModule, GetPixelAlpha(), GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelGreen(), GetPixelMask(), GetPixelRed(), GetQuantumExtent(), GetQuantumPixels(), GrayAlphaQuantum, GrayQuantum, GreenQuantum, ImportAlphaQuantum(), ImportBGRAQuantum(), ImportBGRQuantum(), ImportBlackQuantum(), ImportBlueQuantum(), ImportCbYCrYQuantum(), ImportCMYKAQuantum(), ImportCMYKQuantum(), ImportGrayAlphaQuantum(), ImportGrayQuantum(), ImportGreenQuantum(), ImportIndexAlphaQuantum(), ImportIndexQuantum(), ImportOpacityQuantum(), ImportRedQuantum(), ImportRGBAQuantum(), ImportRGBQuantum(), IndexAlphaQuantum, IndexQuantum, LogMagickEvent(), MagentaQuantum, MagickFalse, MagickSignature, OpacityQuantum, PerceptibleReciprocal(), QuantumScale, RedQuantum, ResetQuantumState(), RGBAQuantum, RGBOQuantum, RGBQuantum, SetPixelAlpha(), SetPixelGreen(), SetPixelRed(), _QuantumInfo::signature, _Image::signature, TraceEvent, UpdatePixelTrait, and YellowQuantum.
MagickExport void SetQuantumAlphaType (QuantumInfo * , const QuantumAlphaType)
MagickExport MagickBooleanType SetQuantumDepth (const Image * , QuantumInfo * , const size_t)
MagickExport MagickBooleanType SetQuantumEndian (const Image * , QuantumInfo * , const EndianType)
MagickExport MagickBooleanType SetQuantumFormat (const Image * , QuantumInfo * , const QuantumFormatType)
MagickExport void SetQuantumImageType (Image * , const QuantumType)
MagickExport void SetQuantumMinIsWhite (QuantumInfo * , const MagickBooleanType)
MagickExport void SetQuantumPack (QuantumInfo * , const MagickBooleanType)
MagickExport MagickBooleanType SetQuantumPad (const Image * , QuantumInfo * , const size_t)
Definition at line 894 of file quantum.c.
References _Image::debug, _QuantumInfo::depth, _Image::filename, GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, _QuantumInfo::pad, SetQuantumDepth(), _QuantumInfo::signature, _Image::signature, and TraceEvent.
MagickExport void SetQuantumQuantum (QuantumInfo * , const size_t)
MagickExport void SetQuantumScale (QuantumInfo * , const double)
Definition at line 997 of file quantum.c.
References MagickSignature, _QuantumInfo::scale, and _QuantumInfo::signature.