MagickCore: quantum-private.h File Reference
quantum-private.h File Reference
#include "MagickCore/cache.h"
Data Structures
struct _QuantumState
struct _QuantumInfo
Macros
#define ExponentBias (127-15)
#define ExponentMask 0x7c00
#define ExponentShift 23
#define SignBitShift 31
#define SignificandShift 13
#define SignificandMask 0x00000400
Typedefs
typedef struct _QuantumState QuantumState
Functions
MagickPrivate void ResetQuantumState (QuantumInfo *)
static MagickSizeType GetQuantumRange (const size_t depth)
static float HalfToSinglePrecision (const unsigned short half)
static unsigned char * PopCharPixel (const unsigned char pixel, unsigned char *pixels)
static unsigned char * PopLongPixel (const EndianType endian, const unsigned int pixel, unsigned char *pixels)
static unsigned char * PopShortPixel (const EndianType endian, const unsigned short pixel, unsigned char *pixels)
static const unsigned char * PushCharPixel (const unsigned char *pixels, unsigned char *pixel)
static const unsigned char * PushLongPixel (const EndianType endian, const unsigned char *pixels, unsigned int *pixel)
static const unsigned char * PushShortPixel (const EndianType endian, const unsigned char *pixels, unsigned short *pixel)
static Quantum ScaleAnyToQuantum (const QuantumAny quantum, const QuantumAny range)
static QuantumAny ScaleQuantumToAny (const Quantum quantum, const QuantumAny range)
static unsigned short SinglePrecisionToHalf (const float value)
Macro Definition Documentation
#define ExponentBias (127-15)
Referenced by HalfToSinglePrecision(), and SinglePrecisionToHalf().
#define ExponentMask 0x7c00
Referenced by SinglePrecisionToHalf().
#define ExponentShift 23
Referenced by HalfToSinglePrecision(), and SinglePrecisionToHalf().
#define SignBitShift 31
Referenced by HalfToSinglePrecision().
#define SignificandMask 0x00000400
Referenced by HalfToSinglePrecision().
#define SignificandShift 13
Referenced by HalfToSinglePrecision(), and SinglePrecisionToHalf().
Typedef Documentation
typedef struct _QuantumState QuantumState
Function Documentation
static MagickSizeType GetQuantumRange (const size_t depth) inline static
Definition at line 91 of file quantum-private.h.
Referenced by ExportAlphaQuantum(), ExportBGRAQuantum(), ExportBGRQuantum(), ExportBlackQuantum(), ExportBlueQuantum(), ExportCbYCrYQuantum(), ExportCMYKAQuantum(), ExportCMYKQuantum(), ExportGrayAlphaQuantum(), ExportGrayQuantum(), ExportGreenQuantum(), ExportIndexAlphaQuantum(), ExportOpacityQuantum(), ExportRedQuantum(), ExportRGBAQuantum(), ExportRGBQuantum(), GetImageDepth(), GetImageStatistics(), ImportAlphaQuantum(), ImportBGRAQuantum(), ImportBGRQuantum(), ImportBlackQuantum(), ImportBlueQuantum(), ImportCbYCrYQuantum(), ImportCMYKAQuantum(), ImportCMYKQuantum(), ImportGrayAlphaQuantum(), ImportGrayQuantum(), ImportGreenQuantum(), ImportIndexAlphaQuantum(), ImportOpacityQuantum(), ImportRedQuantum(), ImportRGBAQuantum(), ImportRGBQuantum(), QueryColorCompliance(), and SetImageDepth().
static float HalfToSinglePrecision (const unsigned short half) inline static
Definition at line 100 of file quantum-private.h.
References ExponentBias, ExponentShift, SignBitShift, SignificandMask, and SignificandShift.
Referenced by ImportAlphaQuantum(), ImportBGRAQuantum(), ImportBGRQuantum(), ImportBlackQuantum(), ImportBlueQuantum(), ImportCMYKAQuantum(), ImportCMYKQuantum(), ImportGrayAlphaQuantum(), ImportGrayQuantum(), ImportGreenQuantum(), ImportIndexAlphaQuantum(), ImportIndexQuantum(), ImportOpacityQuantum(), ImportRedQuantum(), ImportRGBAQuantum(), and ImportRGBQuantum().
static unsigned char* PopCharPixel (const unsigned char pixel, unsigned char * pixels) inline static
Definition at line 175 of file quantum-private.h.
Referenced by ExportAlphaQuantum(), ExportBGRAQuantum(), ExportBGRQuantum(), ExportBlackQuantum(), ExportBlueQuantum(), ExportCMYKAQuantum(), ExportCMYKQuantum(), ExportGrayAlphaQuantum(), ExportGrayQuantum(), ExportGreenQuantum(), ExportIndexAlphaQuantum(), ExportIndexQuantum(), ExportOpacityQuantum(), ExportRedQuantum(), ExportRGBAQuantum(), and ExportRGBQuantum().
static unsigned char* PopLongPixel (const EndianType endian, const unsigned int pixel, unsigned char * pixels) inline static
Definition at line 182 of file quantum-private.h.
References LSBEndian.
Referenced by ExportAlphaQuantum(), ExportBGRAQuantum(), ExportBGRQuantum(), ExportBlackQuantum(), ExportBlueQuantum(), ExportCbYCrYQuantum(), ExportCMYKAQuantum(), ExportCMYKQuantum(), ExportGrayAlphaQuantum(), ExportGrayQuantum(), ExportGreenQuantum(), ExportIndexAlphaQuantum(), ExportIndexQuantum(), ExportOpacityQuantum(), ExportRedQuantum(), ExportRGBAQuantum(), ExportRGBQuantum(), and PopQuantumLongPixel().
static unsigned char* PopShortPixel (const EndianType endian, const unsigned short pixel, unsigned char * pixels) inline static
Definition at line 204 of file quantum-private.h.
References LSBEndian.
Referenced by ExportAlphaQuantum(), ExportBGRAQuantum(), ExportBGRQuantum(), ExportBlackQuantum(), ExportBlueQuantum(), ExportCMYKAQuantum(), ExportCMYKQuantum(), ExportGrayAlphaQuantum(), ExportGrayQuantum(), ExportGreenQuantum(), ExportIndexAlphaQuantum(), ExportIndexQuantum(), ExportOpacityQuantum(), ExportRedQuantum(), ExportRGBAQuantum(), and ExportRGBQuantum().
static const unsigned char* PushCharPixel (const unsigned char * pixels, unsigned char * pixel) inline static
Definition at line 222 of file quantum-private.h.
Referenced by ImportAlphaQuantum(), ImportBGRAQuantum(), ImportBGRQuantum(), ImportBlackQuantum(), ImportBlueQuantum(), ImportCMYKAQuantum(), ImportCMYKQuantum(), ImportGrayAlphaQuantum(), ImportGrayQuantum(), ImportGreenQuantum(), ImportIndexAlphaQuantum(), ImportIndexQuantum(), ImportOpacityQuantum(), ImportRedQuantum(), ImportRGBAQuantum(), and ImportRGBQuantum().
static const unsigned char* PushLongPixel (const EndianType endian, const unsigned char * pixels, unsigned int * pixel) inline static
Definition at line 229 of file quantum-private.h.
References LSBEndian.
Referenced by ImportAlphaQuantum(), ImportBGRAQuantum(), ImportBGRQuantum(), ImportBlackQuantum(), ImportBlueQuantum(), ImportCbYCrYQuantum(), ImportCMYKAQuantum(), ImportCMYKQuantum(), ImportGrayAlphaQuantum(), ImportGrayQuantum(), ImportGreenQuantum(), ImportIndexAlphaQuantum(), ImportIndexQuantum(), ImportOpacityQuantum(), ImportRedQuantum(), ImportRGBAQuantum(), ImportRGBQuantum(), and PushQuantumLongPixel().
static const unsigned char* PushShortPixel (const EndianType endian, const unsigned char * pixels, unsigned short * pixel) inline static
Definition at line 252 of file quantum-private.h.
References LSBEndian.
Referenced by ImportAlphaQuantum(), ImportBGRAQuantum(), ImportBGRQuantum(), ImportBlackQuantum(), ImportBlueQuantum(), ImportCMYKAQuantum(), ImportCMYKQuantum(), ImportGrayAlphaQuantum(), ImportGrayQuantum(), ImportGreenQuantum(), ImportIndexAlphaQuantum(), ImportIndexQuantum(), ImportOpacityQuantum(), ImportRedQuantum(), ImportRGBAQuantum(), and ImportRGBQuantum().
MagickPrivate void ResetQuantumState (QuantumInfo *)
Definition at line 570 of file quantum.c.
References _QuantumState::bits, _QuantumState::inverse_scale, MagickEpsilon, MagickSignature, _QuantumState::mask, _QuantumState::pixel, _QuantumInfo::scale, _QuantumInfo::signature, and _QuantumInfo::state.
Referenced by ExportQuantumPixels(), GetQuantumInfo(), and ImportQuantumPixels().
static Quantum ScaleAnyToQuantum (const QuantumAny quantum, const QuantumAny range) inline static
Definition at line 271 of file quantum-private.h.
References QuantumRange.
Referenced by GetImageDepth(), GetImageStatistics(), ImportAlphaQuantum(), ImportBGRAQuantum(), ImportBGRQuantum(), ImportBlackQuantum(), ImportBlueQuantum(), ImportCbYCrYQuantum(), ImportCMYKAQuantum(), ImportCMYKQuantum(), ImportGrayAlphaQuantum(), ImportGrayQuantum(), ImportGreenQuantum(), ImportIndexAlphaQuantum(), ImportOpacityQuantum(), ImportRedQuantum(), ImportRGBAQuantum(), ImportRGBQuantum(), QueryColorCompliance(), and SetImageDepth().
static QuantumAny ScaleQuantumToAny (const Quantum quantum, const QuantumAny range) inline static
Definition at line 281 of file quantum-private.h.
References QuantumRange.
Referenced by ExportAlphaQuantum(), ExportBGRAQuantum(), ExportBGRQuantum(), ExportBlackQuantum(), ExportBlueQuantum(), ExportCbYCrYQuantum(), ExportCMYKAQuantum(), ExportCMYKQuantum(), ExportGrayAlphaQuantum(), ExportGrayQuantum(), ExportGreenQuantum(), ExportIndexAlphaQuantum(), ExportOpacityQuantum(), ExportRedQuantum(), ExportRGBAQuantum(), ExportRGBQuantum(), GetImageDepth(), GetImageStatistics(), and SetImageDepth().
static unsigned short SinglePrecisionToHalf (const float value) inline static
Definition at line 630 of file quantum-private.h.
References ExponentBias, ExponentMask, ExponentShift, and SignificandShift.
Referenced by ExportAlphaQuantum(), ExportBGRAQuantum(), ExportBGRQuantum(), ExportBlackQuantum(), ExportBlueQuantum(), ExportCMYKAQuantum(), ExportCMYKQuantum(), ExportGrayAlphaQuantum(), ExportGrayQuantum(), ExportGreenQuantum(), ExportIndexAlphaQuantum(), ExportIndexQuantum(), ExportOpacityQuantum(), ExportRedQuantum(), ExportRGBAQuantum(), and ExportRGBQuantum().