MagickCore: quantum.c File Reference
quantum.c File Reference
#include "MagickCore/studio.h"
#include "MagickCore/attribute.h"
#include "MagickCore/blob.h"
#include "MagickCore/blob-private.h"
#include "MagickCore/color-private.h"
#include "MagickCore/exception.h"
#include "MagickCore/exception-private.h"
#include "MagickCore/cache.h"
#include "MagickCore/constitute.h"
#include "MagickCore/delegate.h"
#include "MagickCore/geometry.h"
#include "MagickCore/list.h"
#include "MagickCore/magick.h"
#include "MagickCore/memory_.h"
#include "MagickCore/monitor.h"
#include "MagickCore/option.h"
#include "MagickCore/pixel.h"
#include "MagickCore/pixel-accessor.h"
#include "MagickCore/property.h"
#include "MagickCore/quantum.h"
#include "MagickCore/quantum-private.h"
#include "MagickCore/resource_.h"
#include "MagickCore/semaphore.h"
#include "MagickCore/statistic.h"
#include "MagickCore/stream.h"
#include "MagickCore/string_.h"
#include "MagickCore/string-private.h"
#include "MagickCore/thread-private.h"
#include "MagickCore/utility.h"
Macros
#define QuantumSignature 0xab
Functions
static void DestroyQuantumPixels (QuantumInfo *)
static size_t MagickMax (const size_t x, const size_t y)
MagickExport QuantumInfo * AcquireQuantumInfo (const ImageInfo *image_info, Image *image)
static MagickBooleanType AcquireQuantumPixels (QuantumInfo *quantum_info, const size_t extent)
MagickExport QuantumInfo * DestroyQuantumInfo (QuantumInfo *quantum_info)
MagickExport size_t GetQuantumExtent (const Image *image, const QuantumInfo *quantum_info, const QuantumType quantum_type)
MagickExport EndianType GetQuantumEndian (const QuantumInfo *quantum_info)
MagickExport QuantumFormatType GetQuantumFormat (const QuantumInfo *quantum_info)
MagickExport void GetQuantumInfo (const ImageInfo *image_info, QuantumInfo *quantum_info)
MagickExport unsigned char * GetQuantumPixels (const QuantumInfo *quantum_info)
MagickExport QuantumType GetQuantumType (Image *image, ExceptionInfo *exception)
MagickPrivate void ResetQuantumState (QuantumInfo *quantum_info)
MagickExport void SetQuantumAlphaType (QuantumInfo *quantum_info, const QuantumAlphaType type)
MagickExport MagickBooleanType SetQuantumDepth (const Image *image, QuantumInfo *quantum_info, const size_t depth)
MagickExport MagickBooleanType SetQuantumEndian (const Image *image, QuantumInfo *quantum_info, const EndianType endian)
MagickExport MagickBooleanType SetQuantumFormat (const Image *image, QuantumInfo *quantum_info, const QuantumFormatType format)
MagickExport void SetQuantumImageType (Image *image, const QuantumType quantum_type)
MagickExport void SetQuantumPack (QuantumInfo *quantum_info, const MagickBooleanType pack)
MagickExport MagickBooleanType SetQuantumPad (const Image *image, QuantumInfo *quantum_info, const size_t pad)
MagickExport void SetQuantumMinIsWhite (QuantumInfo *quantum_info, const MagickBooleanType min_is_white)
MagickExport void SetQuantumQuantum (QuantumInfo *quantum_info, const size_t quantum)
MagickExport void SetQuantumScale (QuantumInfo *quantum_info, const double scale)
Macro Definition Documentation
#define QuantumSignature 0xab
Definition at line 74 of file quantum.c.
Referenced by AcquireQuantumPixels(), and DestroyQuantumPixels().
Function Documentation
MagickExport QuantumInfo* AcquireQuantumInfo (const ImageInfo * image_info, Image * image)
Definition at line 114 of file quantum.c.
References AcquireMagickMemory(), _Image::depth, DestroyQuantumInfo(), _QuantumInfo::endian, _Image::endian, GetQuantumInfo(), MagickFalse, MagickSignature, ResourceLimitFatalError, SetQuantumDepth(), _QuantumInfo::signature, and ThrowFatalException.
Referenced by StreamImage().
static MagickBooleanType AcquireQuantumPixels (QuantumInfo * quantum_info, const size_t extent) static
Definition at line 162 of file quantum.c.
References AcquireQuantumMemory(), _QuantumInfo::extent, GetMagickResourceLimit(), MagickFalse, MagickSignature, MagickTrue, _QuantumInfo::number_threads, _QuantumInfo::pixels, QuantumSignature, ResetMagickMemory(), _QuantumInfo::signature, and ThreadResource.
Referenced by SetQuantumDepth().
MagickExport QuantumInfo* DestroyQuantumInfo (QuantumInfo * quantum_info)
Definition at line 214 of file quantum.c.
References DestroyQuantumPixels(), DestroySemaphoreInfo(), MagickSignature, _QuantumInfo::pixels, RelinquishMagickMemory(), _QuantumInfo::semaphore, and _QuantumInfo::signature.
Referenced by AcquireQuantumInfo(), DestroyStreamInfo(), and StreamImage().
static void DestroyQuantumPixels (QuantumInfo * quantum_info) static
Definition at line 249 of file quantum.c.
References _QuantumInfo::extent, MagickSignature, _QuantumInfo::number_threads, _QuantumInfo::pixels, QuantumSignature, RelinquishMagickMemory(), and _QuantumInfo::signature.
Referenced by DestroyQuantumInfo(), and SetQuantumDepth().
MagickExport EndianType GetQuantumEndian (const QuantumInfo * quantum_info)
Definition at line 352 of file quantum.c.
References _QuantumInfo::endian, MagickSignature, and _QuantumInfo::signature.
MagickExport size_t GetQuantumExtent (const Image * image, const QuantumInfo * quantum_info, const QuantumType quantum_type)
Definition at line 303 of file quantum.c.
References BGRAQuantum, BGRQuantum, CMYKAQuantum, CMYKQuantum, _Image::columns, _QuantumInfo::depth, GrayAlphaQuantum, IndexAlphaQuantum, MagickFalse, MagickSignature, _QuantumInfo::pack, RGBAQuantum, RGBOQuantum, RGBQuantum, and _QuantumInfo::signature.
Referenced by ExportQuantumPixels(), and ImportQuantumPixels().
MagickExport QuantumFormatType GetQuantumFormat (const QuantumInfo * quantum_info)
Definition at line 381 of file quantum.c.
References _QuantumInfo::format, MagickSignature, and _QuantumInfo::signature.
MagickExport void GetQuantumInfo (const ImageInfo * image_info, QuantumInfo * quantum_info)
Definition at line 412 of file quantum.c.
References AllocateSemaphoreInfo(), _QuantumInfo::endian, _ImageInfo::endian, _QuantumInfo::format, GetImageOption(), LocaleCompare(), MagickFalse, MagickQuantumFormatOptions, MagickSignature, MagickTrue, _QuantumInfo::maximum, _QuantumInfo::min_is_white, _QuantumInfo::minimum, _QuantumInfo::pack, ParseCommandOption(), _QuantumInfo::quantum, QuantumRange, ResetMagickMemory(), ResetQuantumState(), _QuantumInfo::scale, _QuantumInfo::semaphore, _QuantumInfo::signature, and StringToDouble().
Referenced by AcquireQuantumInfo().
MagickExport unsigned char* GetQuantumPixels (const QuantumInfo * quantum_info)
Definition at line 483 of file quantum.c.
References GetOpenMPThreadId(), MagickSignature, _QuantumInfo::pixels, and _QuantumInfo::signature.
Referenced by ExportQuantumPixels(), and ImportQuantumPixels().
MagickExport QuantumType GetQuantumType (Image * image, ExceptionInfo * exception)
Definition at line 515 of file quantum.c.
References _Image::alpha_trait, BlendPixelTrait, CMYKAQuantum, CMYKColorspace, CMYKQuantum, _Image::colorspace, _Image::debug, _Image::filename, GetMagickModule, GrayAlphaQuantum, GrayQuantum, IndexAlphaQuantum, IndexQuantum, IsImageGray(), LogMagickEvent(), MagickFalse, MagickSignature, PseudoClass, RGBAQuantum, RGBQuantum, _Image::signature, _Image::storage_class, and TraceEvent.
static size_t MagickMax (const size_t x, const size_t y) inline static
Definition at line 107 of file quantum.c.
MagickPrivate void ResetQuantumState (QuantumInfo * quantum_info)
Definition at line 570 of file quantum.c.
References _QuantumState::bits, _QuantumState::inverse_scale, MagickEpsilon, MagickSignature, _QuantumState::mask, _QuantumState::pixel, _QuantumInfo::scale, _QuantumInfo::signature, and _QuantumInfo::state.
Referenced by ExportQuantumPixels(), GetQuantumInfo(), and ImportQuantumPixels().
MagickExport void SetQuantumAlphaType (QuantumInfo * quantum_info, const QuantumAlphaType type)
Definition at line 618 of file quantum.c.
References _QuantumInfo::alpha_type, MagickSignature, and _QuantumInfo::signature.
MagickExport MagickBooleanType SetQuantumDepth (const Image * image, QuantumInfo * quantum_info, const size_t depth)
Definition at line 653 of file quantum.c.
References AcquireQuantumPixels(), _Image::columns, _Image::debug, _QuantumInfo::depth, DestroyQuantumPixels(), _Image::filename, FloatingPointQuantumFormat, _QuantumInfo::format, GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, MaxPixelChannels, _QuantumInfo::pad, _QuantumInfo::pixels, _QuantumInfo::signature, _Image::signature, and TraceEvent.
Referenced by AcquireQuantumInfo(), SetQuantumEndian(), SetQuantumFormat(), and SetQuantumPad().
MagickExport MagickBooleanType SetQuantumEndian (const Image * image, QuantumInfo * quantum_info, const EndianType endian)
Definition at line 713 of file quantum.c.
References _Image::debug, _QuantumInfo::depth, _QuantumInfo::endian, _Image::filename, GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, SetQuantumDepth(), _QuantumInfo::signature, _Image::signature, and TraceEvent.
MagickExport MagickBooleanType SetQuantumFormat (const Image * image, QuantumInfo * quantum_info, const QuantumFormatType format)
Definition at line 753 of file quantum.c.
References _Image::debug, _QuantumInfo::depth, _Image::filename, _QuantumInfo::format, GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, SetQuantumDepth(), _QuantumInfo::signature, _Image::signature, and TraceEvent.
MagickExport void SetQuantumImageType (Image * image, const QuantumType quantum_type)
Definition at line 792 of file quantum.c.
References BilevelType, BlackQuantum, CMYKAQuantum, CMYKQuantum, ColorSeparationType, CyanQuantum, _Image::debug, _Image::depth, _Image::filename, GetMagickModule, GrayAlphaQuantum, GrayQuantum, GrayscaleType, IndexAlphaQuantum, IndexQuantum, LogMagickEvent(), MagentaQuantum, MagickFalse, MagickSignature, PaletteType, _Image::signature, TraceEvent, TrueColorType, _Image::type, and YellowQuantum.
MagickExport void SetQuantumMinIsWhite (QuantumInfo * quantum_info, const MagickBooleanType min_is_white)
Definition at line 932 of file quantum.c.
References MagickSignature, _QuantumInfo::min_is_white, and _QuantumInfo::signature.
MagickExport void SetQuantumPack (QuantumInfo * quantum_info, const MagickBooleanType pack)
Definition at line 858 of file quantum.c.
References MagickSignature, _QuantumInfo::pack, and _QuantumInfo::signature.
MagickExport MagickBooleanType SetQuantumPad (const Image * image, QuantumInfo * quantum_info, const size_t pad)
Definition at line 894 of file quantum.c.
References _Image::debug, _QuantumInfo::depth, _Image::filename, GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, _QuantumInfo::pad, SetQuantumDepth(), _QuantumInfo::signature, _Image::signature, and TraceEvent.
MagickExport void SetQuantumQuantum (QuantumInfo * quantum_info, const size_t quantum)
Definition at line 965 of file quantum.c.
References MagickSignature, _QuantumInfo::quantum, and _QuantumInfo::signature.
MagickExport void SetQuantumScale (QuantumInfo * quantum_info, const double scale)
Definition at line 997 of file quantum.c.
References MagickSignature, _QuantumInfo::scale, and _QuantumInfo::signature.