MagickCore: random_.h File Reference
random_.h File Reference
#include "MagickCore/string_.h"
Typedefs
typedef struct _RandomInfo RandomInfo
Functions
MagickExport double GetRandomValue (RandomInfo *)
MagickExport double GetPseudoRandomValue (RandomInfo *)
MagickExport RandomInfo * AcquireRandomInfo (void)
MagickExport RandomInfo * DestroyRandomInfo (RandomInfo *)
MagickExport StringInfo * GetRandomKey (RandomInfo *, const size_t)
MagickExport unsigned long GetRandomSecretKey (const RandomInfo *)
MagickExport void SetRandomKey (RandomInfo *, const size_t, unsigned char *)
MagickExport void SetRandomSecretKey (const unsigned long)
MagickExport void SetRandomTrueRandom (const MagickBooleanType)
Typedef Documentation
typedef struct _RandomInfo RandomInfo
Definition at line 30 of file random_.h.
Function Documentation
MagickExport RandomInfo* AcquireRandomInfo (void)
MagickExport RandomInfo * DestroyRandomInfo (RandomInfo *)
Definition at line 279 of file random.c.
References DestroySemaphoreInfo(), DestroySignatureInfo(), DestroyStringInfo(), GetMagickModule, LockSemaphoreInfo(), LogMagickEvent(), MagickSignature, _RandomInfo::nonce, RelinquishMagickMemory(), _RandomInfo::reservoir, ResetMagickMemory(), _RandomInfo::seed, _RandomInfo::semaphore, _RandomInfo::signature, _RandomInfo::signature_info, TraceEvent, and UnlockSemaphoreInfo().
Referenced by DestroyFxInfo(), DestroyPixelCache(), DestroyRandomInfoThreadSet(), DistributePixelCacheClient(), PlasmaImage(), ResourceComponentTerminus(), and ShredFile().
MagickExport double GetPseudoRandomValue (RandomInfo *)
Definition at line 604 of file random.c.
References _RandomInfo::normalize, and _RandomInfo::seed.
Referenced by FxEvaluateSubexpression(), GenerateDifferentialNoise(), PlasmaPixel(), RandomThresholdImage(), RandomX(), RandomY(), SketchImage(), and SpreadImage().
MagickExport StringInfo* GetRandomKey (RandomInfo * , const size_t)
Definition at line 648 of file random.c.
References AcquireStringInfo(), GetStringInfoDatum(), and SetRandomKey().
Referenced by AcquireRandomInfo(), AcquireUniqueFileResource(), DistributePixelCacheClient(), and ShredFile().
MagickExport unsigned long GetRandomSecretKey (const RandomInfo *)
Definition at line 681 of file random.c.
References _RandomInfo::secret_key.
Referenced by AddNoiseImage(), EvaluateImage(), EvaluateImages(), RandomThresholdImage(), SketchImage(), and SpreadImage().
MagickExport double GetRandomValue (RandomInfo *)
MagickExport void SetRandomKey (RandomInfo * , const size_t , unsigned char *)
MagickExport void SetRandomSecretKey (const unsigned long)
MagickExport void SetRandomTrueRandom (const MagickBooleanType)
Definition at line 921 of file random.c.
References gather_true_random.