MagickCore: registry.c File Reference
registry.c File Reference
#include "MagickCore/studio.h"
#include "MagickCore/exception.h"
#include "MagickCore/exception-private.h"
#include "MagickCore/image.h"
#include "MagickCore/list.h"
#include "MagickCore/memory_.h"
#include "MagickCore/registry.h"
#include "MagickCore/registry-private.h"
#include "MagickCore/splay-tree.h"
#include "MagickCore/string_.h"
#include "MagickCore/utility.h"
Data Structures
struct _RegistryInfo
Typedefs
typedef struct _RegistryInfo RegistryInfo
Functions
MagickExport MagickBooleanType DefineImageRegistry (const RegistryType type, const char *option, ExceptionInfo *exception)
MagickExport MagickBooleanType DeleteImageRegistry (const char *key)
MagickExport void * GetImageRegistry (const RegistryType type, const char *key, ExceptionInfo *exception)
MagickExport char * GetNextImageRegistry (void)
MagickPrivate MagickBooleanType RegistryComponentGenesis (void)
MagickPrivate void RegistryComponentTerminus (void)
MagickExport void * RemoveImageRegistry (const char *key)
MagickExport void ResetImageRegistryIterator (void)
static void * DestroyRegistryNode (void *registry_info)
MagickExport MagickBooleanType SetImageRegistry (const RegistryType type, const char *key, const void *value, ExceptionInfo *exception)
Variables
static SplayTreeInfo * registry = (SplayTreeInfo *) NULL
static SemaphoreInfo * registry_semaphore = (SemaphoreInfo *) NULL
static volatile MagickBooleanType instantiate_registry = MagickFalse
Typedef Documentation
typedef struct _RegistryInfo RegistryInfo
Function Documentation
MagickExport MagickBooleanType DefineImageRegistry (const RegistryType type, const char * option, ExceptionInfo * exception)
Definition at line 109 of file registry.c.
References CopyMagickString(), MaxTextExtent, and SetImageRegistry().
MagickExport MagickBooleanType DeleteImageRegistry (const char * key)
Definition at line 153 of file registry.c.
References DeleteNodeFromSplayTree(), GetMagickModule, IsEventLogging(), LogMagickEvent(), MagickFalse, registry, and TraceEvent.
static void* DestroyRegistryNode (void * registry_info) static
Definition at line 430 of file registry.c.
References DestroyImageInfo(), DestroyImageList(), ImageInfoRegistryType, ImageRegistryType, RelinquishMagickMemory(), StringRegistryType, _RegistryInfo::type, and _RegistryInfo::value.
Referenced by SetImageRegistry().
MagickExport void* GetImageRegistry (const RegistryType type, const char * key, ExceptionInfo * exception)
Definition at line 189 of file registry.c.
References CloneImageInfo(), CloneImageList(), ConstantString(), GetMagickModule, GetValueFromSplayTree(), ImageInfoRegistryType, ImageRegistryType, IsEventLogging(), LogMagickEvent(), MagickFalse, registry, RegistryError, StringRegistryType, ThrowMagickException(), TraceEvent, _RegistryInfo::type, and _RegistryInfo::value.
Referenced by GetHostname(), GetPathTemplate(), IdentifyImage(), and ShredFile().
MagickExport char* GetNextImageRegistry (void)
Definition at line 274 of file registry.c.
References GetMagickModule, GetNextKeyInSplayTree(), IsEventLogging(), LogMagickEvent(), MagickFalse, registry, and TraceEvent.
Referenced by IdentifyImage().
MagickPrivate MagickBooleanType RegistryComponentGenesis (void)
Definition at line 301 of file registry.c.
References AcquireSemaphoreInfo(), MagickTrue, and registry_semaphore.
Referenced by MagickCoreGenesis().
MagickPrivate void RegistryComponentTerminus (void)
Definition at line 325 of file registry.c.
References AcquireSemaphoreInfo(), DestroySemaphoreInfo(), DestroySplayTree(), GetMagickModule, instantiate_registry, IsEventLogging(), LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, registry, registry_semaphore, TraceEvent, and UnlockSemaphoreInfo().
Referenced by MagickCoreTerminus().
MagickExport void* RemoveImageRegistry (const char * key)
Definition at line 362 of file registry.c.
References GetMagickModule, IsEventLogging(), LogMagickEvent(), MagickFalse, registry, RemoveNodeFromSplayTree(), and TraceEvent.
MagickExport void ResetImageRegistryIterator (void)
Definition at line 391 of file registry.c.
References GetMagickModule, IsEventLogging(), LogMagickEvent(), MagickFalse, registry, ResetSplayTreeIterator(), and TraceEvent.
Referenced by IdentifyImage().
MagickExport MagickBooleanType SetImageRegistry (const RegistryType type, const char * key, const void * value, ExceptionInfo * exception)
Definition at line 458 of file registry.c.
References AcquireMagickMemory(), AcquireSemaphoreInfo(), AddValueToSplayTree(), CloneImageInfo(), CloneImageList(), CompareSplayTreeString(), ConstantString(), DestroyRegistryNode(), GetMagickModule, ImageInfoRegistryType, ImageRegistryType, instantiate_registry, IsEventLogging(), LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, NewSplayTree(), registry, registry_semaphore, RegistryError, RelinquishMagickMemory(), ResetMagickMemory(), ResourceLimitFatalError, _RegistryInfo::signature, _Image::signature, _ImageInfo::signature, StringRegistryType, ThrowFatalException, ThrowMagickException(), TraceEvent, _RegistryInfo::type, UnlockSemaphoreInfo(), and _RegistryInfo::value.
Referenced by DefineImageRegistry().
Variable Documentation
volatile MagickBooleanType instantiate_registry = MagickFalse static
Definition at line 80 of file registry.c.
Referenced by RegistryComponentTerminus(), and SetImageRegistry().
SplayTreeInfo* registry = (SplayTreeInfo *) NULL static
Definition at line 74 of file registry.c.
Referenced by DeleteImageRegistry(), DistributePixelCacheClient(), GetImageRegistry(), GetNextImageRegistry(), IdentifyImage(), RegistryComponentTerminus(), RemoveImageRegistry(), ResetImageRegistryIterator(), and SetImageRegistry().
SemaphoreInfo* registry_semaphore = (SemaphoreInfo *) NULL static
Definition at line 77 of file registry.c.
Referenced by RegistryComponentGenesis(), RegistryComponentTerminus(), and SetImageRegistry().