MagickCore: registry.h File Reference
registry.h File Reference
Enumerations
enum RegistryType { UndefinedRegistryType, ImageRegistryType, ImageInfoRegistryType, StringRegistryType }
Functions
MagickExport char * GetNextImageRegistry (void)
MagickExport MagickBooleanType DefineImageRegistry (const RegistryType, const char *, ExceptionInfo *)
MagickExport MagickBooleanType DeleteImageRegistry (const char *)
MagickExport MagickBooleanType SetImageRegistry (const RegistryType, const char *, const void *, ExceptionInfo *)
MagickExport void * GetImageRegistry (const RegistryType, const char *, ExceptionInfo *)
MagickExport void * RemoveImageRegistry (const char *)
MagickExport void ResetImageRegistryIterator (void)
Enumeration Type Documentation
enum RegistryType
Enumerator
UndefinedRegistryType
ImageRegistryType
ImageInfoRegistryType
StringRegistryType
Definition at line 25 of file registry.h.
Function Documentation
MagickExport MagickBooleanType DefineImageRegistry (const RegistryType , const char * , ExceptionInfo *)
MagickExport MagickBooleanType DeleteImageRegistry (const char *)
MagickExport void* GetImageRegistry (const RegistryType , const char * , ExceptionInfo *)
MagickExport char* GetNextImageRegistry (void)
Definition at line 274 of file registry.c.
References GetMagickModule, GetNextKeyInSplayTree(), IsEventLogging(), LogMagickEvent(), MagickFalse, registry, and TraceEvent.
Referenced by IdentifyImage().
MagickExport void * RemoveImageRegistry (const char *)
MagickExport void ResetImageRegistryIterator (void)
Definition at line 391 of file registry.c.
References GetMagickModule, IsEventLogging(), LogMagickEvent(), MagickFalse, registry, ResetSplayTreeIterator(), and TraceEvent.
Referenced by IdentifyImage().
MagickExport MagickBooleanType SetImageRegistry (const RegistryType , const char * , const void * , ExceptionInfo *)
Definition at line 458 of file registry.c.
References AcquireMagickMemory(), AcquireSemaphoreInfo(), AddValueToSplayTree(), CloneImageInfo(), CloneImageList(), CompareSplayTreeString(), ConstantString(), DestroyRegistryNode(), GetMagickModule, ImageInfoRegistryType, ImageRegistryType, instantiate_registry, IsEventLogging(), LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, NewSplayTree(), registry, registry_semaphore, RegistryError, RelinquishMagickMemory(), ResetMagickMemory(), ResourceLimitFatalError, _RegistryInfo::signature, _Image::signature, _ImageInfo::signature, StringRegistryType, ThrowFatalException, ThrowMagickException(), TraceEvent, _RegistryInfo::type, UnlockSemaphoreInfo(), and _RegistryInfo::value.
Referenced by DefineImageRegistry().