MagickCore: resample.c File Reference
resample.c File Reference
#include "MagickCore/studio.h"
#include "MagickCore/artifact.h"
#include "MagickCore/color-private.h"
#include "MagickCore/cache.h"
#include "MagickCore/draw.h"
#include "MagickCore/exception-private.h"
#include "MagickCore/gem.h"
#include "MagickCore/image.h"
#include "MagickCore/image-private.h"
#include "MagickCore/log.h"
#include "MagickCore/magick.h"
#include "MagickCore/memory_.h"
#include "MagickCore/pixel.h"
#include "MagickCore/pixel-accessor.h"
#include "MagickCore/quantum.h"
#include "MagickCore/random_.h"
#include "MagickCore/resample.h"
#include "MagickCore/resize.h"
#include "MagickCore/resize-private.h"
#include "MagickCore/resource_.h"
#include "MagickCore/token.h"
#include "MagickCore/transform.h"
#include "MagickCore/signature-private.h"
#include "MagickCore/utility.h"
#include "MagickCore/utility-private.h"
#include "MagickCore/option.h"
Data Structures
struct _ResampleFilter
Macros
#define EWA 1 /* Normal EWA handling - raw or clamped */
#define EWA_CLAMP 1 /* EWA Clamping from Nicolas Robidoux */
#define FILTER_LUT 1 /* Use a LUT rather then direct filter calls */
#define DEBUG_ELLIPSE 0 /* output ellipse info for debug */
#define DEBUG_HIT_MISS 0 /* output hit/miss pixels (as gnuplot commands) */
#define DEBUG_NO_PIXEL_HIT 0 /* Make pixels that fail to hit anything - RED */
#define WLUT_WIDTH 1024 /* size of the filter cache */
#define DEBUG_HIT_MISS 0 /* only valid if DEBUG_ELLIPSE is enabled */
Functions
MagickExport ResampleFilter * AcquireResampleFilter (const Image *image, ExceptionInfo *exception)
MagickExport ResampleFilter * DestroyResampleFilter (ResampleFilter *resample_filter)
MagickExport MagickBooleanType ResamplePixelColor (ResampleFilter *resample_filter, const double u0, const double v0, PixelInfo *pixel, ExceptionInfo *exception)
static void ClampUpAxes (const double dux, const double dvx, const double duy, const double dvy, double *major_mag, double *minor_mag, double *major_unit_x, double *major_unit_y, double *minor_unit_x, double *minor_unit_y)
MagickExport void ScaleResampleFilter (ResampleFilter *resample_filter, const double dux, const double duy, const double dvx, const double dvy)
MagickExport void SetResampleFilter (ResampleFilter *resample_filter, const FilterTypes filter)
MagickExport MagickBooleanType SetResampleFilterInterpolateMethod (ResampleFilter *resample_filter, const PixelInterpolateMethod method)
MagickExport MagickBooleanType SetResampleFilterVirtualPixelMethod (ResampleFilter *resample_filter, const VirtualPixelMethod method)
Macro Definition Documentation
#define DEBUG_ELLIPSE 0 /* output ellipse info for debug */
Definition at line 81 of file resample.c.
#define DEBUG_HIT_MISS 0 /* output hit/miss pixels (as gnuplot commands) */
Definition at line 82 of file resample.c.
#define DEBUG_HIT_MISS 0 /* only valid if DEBUG_ELLIPSE is enabled */
Definition at line 82 of file resample.c.
#define DEBUG_NO_PIXEL_HIT 0 /* Make pixels that fail to hit anything - RED */
Definition at line 83 of file resample.c.
#define EWA 1 /* Normal EWA handling - raw or clamped */
Definition at line 74 of file resample.c.
#define EWA_CLAMP 1 /* EWA Clamping from Nicolas Robidoux */
Definition at line 76 of file resample.c.
#define FILTER_LUT 1 /* Use a LUT rather then direct filter calls */
Definition at line 78 of file resample.c.
#define WLUT_WIDTH 1024 /* size of the filter cache */
Definition at line 86 of file resample.c.
Referenced by ResamplePixelColor(), ScaleResampleFilter(), and SetResampleFilter().
Function Documentation
MagickExport ResampleFilter* AcquireResampleFilter (const Image * image, ExceptionInfo * exception)
Definition at line 207 of file resample.c.
References AcquireMagickMemory(), AcquireVirtualCacheView(), _ResampleFilter::average_defined, _Image::columns, _ResampleFilter::debug, _Image::debug, _ResampleFilter::exception, _Image::filename, _Image::filter, GetImageVirtualPixelMethod(), GetMagickModule, _ResampleFilter::image, _ResampleFilter::image_area, _Image::interpolate, IsEventLogging(), LogMagickEvent(), MagickFalse, MagickSignature, ReferenceImage(), ResetMagickMemory(), ResourceLimitFatalError, _Image::rows, SetResampleFilter(), SetResampleFilterInterpolateMethod(), SetResampleFilterVirtualPixelMethod(), _ExceptionInfo::signature, _ResampleFilter::signature, _Image::signature, ThrowFatalException, TraceEvent, and _ResampleFilter::view.
Referenced by AcquireResampleFilterThreadSet(), and CompositeImage().
static void ClampUpAxes (const double dux, const double dvx, const double duy, const double dvy, double * major_mag, double * minor_mag, double * major_unit_x, double * major_unit_y, double * minor_unit_x, double * minor_unit_y) inline static
Definition at line 709 of file resample.c.
Referenced by ScaleResampleFilter().
MagickExport ResampleFilter* DestroyResampleFilter (ResampleFilter * resample_filter)
Definition at line 263 of file resample.c.
References _ResampleFilter::debug, DestroyCacheView(), DestroyImage(), DestroyResizeFilter(), _Image::filename, GetMagickModule, _ResampleFilter::image, LogMagickEvent(), MagickFalse, MagickSignature, RelinquishMagickMemory(), _ResampleFilter::signature, TraceEvent, and _ResampleFilter::view.
Referenced by CompositeImage(), and DestroyResampleFilterThreadSet().
MagickExport MagickBooleanType ResamplePixelColor (ResampleFilter * resample_filter, const double u0, const double v0, PixelInfo * pixel, ExceptionInfo * exception)
Definition at line 316 of file resample.c.
References _ResampleFilter::A, AcquireVirtualCacheView(), _PixelInfo::alpha, _PixelInfo::alpha_trait, _ResampleFilter::average_defined, _ResampleFilter::average_pixel, AverageInterpolatePixel, _ResampleFilter::B, _Image::background_color, BackgroundVirtualPixelMethod, _PixelInfo::black, BlackVirtualPixelMethod, BlendPixelTrait, _PixelInfo::blue, BoxFilter, _ResampleFilter::C, CheckerTileVirtualPixelMethod, ClampToQuantum(), CMYKColorspace, _PixelInfo::colorspace, _Image::columns, DestroyCacheView(), DestroyImage(), DitherVirtualPixelMethod, _ResampleFilter::do_interpolate, EdgeVirtualPixelMethod, _ResampleFilter::exception, _ResampleFilter::filter_lut, FormatLocaleFile(), GetCacheViewVirtualPixels(), GetPixelAlpha(), GetPixelBlack(), GetPixelBlue(), GetPixelChannels(), GetPixelGreen(), GetPixelInfo(), GetPixelInfoPixel(), GetPixelRed(), GetResizeFilterWeight(), GrayVirtualPixelMethod, _PixelInfo::green, HorizontalTileEdgeVirtualPixelMethod, HorizontalTileVirtualPixelMethod, _ResampleFilter::image, IntegerInterpolatePixel, _ResampleFilter::interpolate, InterpolatePixelInfo(), _ResampleFilter::limit_reached, MagickEpsilon, MagickFalse, MagickSignature, MagickTrue, MaskVirtualPixelMethod, MirrorVirtualPixelMethod, QuantumRange, QuantumScale, RandomVirtualPixelMethod, _PixelInfo::red, ResizeImage(), _Image::rows, _ResampleFilter::signature, _ResampleFilter::slope, TileVirtualPixelMethod, TransparentVirtualPixelMethod, _ResampleFilter::Ulimit, UndefinedVirtualPixelMethod, _ResampleFilter::Uwidth, VerticalTileEdgeVirtualPixelMethod, VerticalTileVirtualPixelMethod, _ResampleFilter::view, _ResampleFilter::virtual_pixel, _ResampleFilter::Vlimit, WhiteVirtualPixelMethod, and WLUT_WIDTH.
Referenced by CompositeImage(), and DistortImage().
MagickExport void ScaleResampleFilter (ResampleFilter * resample_filter, const double dux, const double duy, const double dvx, const double dvy)
Definition at line 1038 of file resample.c.
References _ResampleFilter::A, _ResampleFilter::B, _ResampleFilter::C, ClampUpAxes(), _ResampleFilter::filter, FormatLocaleFile(), _ResampleFilter::image_area, _ResampleFilter::limit_reached, MagickEpsilon, MagickFalse, MagickHuge, MagickPI, MagickSignature, MagickTrue, PointFilter, RadiansToDegrees(), _ResampleFilter::signature, _ResampleFilter::slope, _ResampleFilter::support, _ResampleFilter::Ulimit, _ResampleFilter::Uwidth, _ResampleFilter::Vlimit, and WLUT_WIDTH.
Referenced by CompositeImage(), and SetResampleFilter().
MagickExport void SetResampleFilter (ResampleFilter * resample_filter, const FilterTypes filter)
Definition at line 1241 of file resample.c.
References AcquireResizeFilter(), CommandOptionToMnemonic(), DestroyResizeFilter(), _ResampleFilter::do_interpolate, _ResampleFilter::exception, _ResampleFilter::filter, _ResampleFilter::filter_lut, GetImageArtifact(), GetMagickModule, GetMagickPrecision(), GetResizeFilterSupport(), GetResizeFilterWeight(), IfStringTrue, _ResampleFilter::image, MagickFalse, MagickFilterOptions, MagickSignature, MagickTrue, ModuleError, PointFilter, RobidouxFilter, ScaleResampleFilter(), _ResampleFilter::signature, _ResampleFilter::support, ThrowMagickException(), UndefinedFilter, and WLUT_WIDTH.
Referenced by AcquireResampleFilter(), AcquireResampleFilterThreadSet(), and CompositeImage().
MagickExport MagickBooleanType SetResampleFilterInterpolateMethod (ResampleFilter * resample_filter, const PixelInterpolateMethod method)
Definition at line 1404 of file resample.c.
References _ResampleFilter::debug, _Image::filename, GetMagickModule, _ResampleFilter::image, _ResampleFilter::interpolate, LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, _ResampleFilter::signature, and TraceEvent.
Referenced by AcquireResampleFilter().
MagickExport MagickBooleanType SetResampleFilterVirtualPixelMethod (ResampleFilter * resample_filter, const VirtualPixelMethod method)
Definition at line 1443 of file resample.c.
References _ResampleFilter::debug, _Image::filename, GetMagickModule, _ResampleFilter::image, LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, SetCacheViewVirtualPixelMethod(), _ResampleFilter::signature, TraceEvent, UndefinedVirtualPixelMethod, _ResampleFilter::view, and _ResampleFilter::virtual_pixel.
Referenced by AcquireResampleFilter(), and AcquireResampleFilterThreadSet().