MagickCore: resample.h File Reference
resample.h File Reference
#include "MagickCore/cache-view.h"
Macros
#define BesselFilter JincFilter
#define WelshFilter WelchFilter
#define HanningFilter HannFilter
Typedefs
typedef struct _ResampleFilter ResampleFilter
Enumerations
enum FilterTypes {
UndefinedFilter, PointFilter, BoxFilter, TriangleFilter,
HermiteFilter, HannFilter, HammingFilter, BlackmanFilter,
GaussianFilter, QuadraticFilter, CubicFilter, CatromFilter,
MitchellFilter, JincFilter, SincFilter, SincFastFilter,
KaiserFilter, WelchFilter, ParzenFilter, BohmanFilter,
BartlettFilter, LagrangeFilter, LanczosFilter, LanczosSharpFilter,
Lanczos2Filter, Lanczos2SharpFilter, RobidouxFilter, RobidouxSharpFilter,
CosineFilter, SplineFilter, LanczosRadiusFilter, SentinelFilter
}
Functions
MagickExport MagickBooleanType ResamplePixelColor (ResampleFilter *, const double, const double, PixelInfo *, ExceptionInfo *)
MagickExport MagickBooleanType SetResampleFilterInterpolateMethod (ResampleFilter *, const PixelInterpolateMethod)
MagickExport MagickBooleanType SetResampleFilterVirtualPixelMethod (ResampleFilter *, const VirtualPixelMethod)
MagickExport ResampleFilter * AcquireResampleFilter (const Image *, ExceptionInfo *)
MagickExport ResampleFilter * DestroyResampleFilter (ResampleFilter *)
MagickExport void ScaleResampleFilter (ResampleFilter *, const double, const double, const double, const double)
MagickExport void SetResampleFilter (ResampleFilter *, const FilterTypes)
Macro Definition Documentation
#define BesselFilter JincFilter
Definition at line 75 of file resample.h.
#define HanningFilter HannFilter
Definition at line 77 of file resample.h.
#define WelshFilter WelchFilter
Definition at line 76 of file resample.h.
Typedef Documentation
typedef struct _ResampleFilter ResampleFilter
Definition at line 79 of file resample.h.
Enumeration Type Documentation
enum FilterTypes
Enumerator
UndefinedFilter
PointFilter
BoxFilter
TriangleFilter
HermiteFilter
HannFilter
HammingFilter
BlackmanFilter
GaussianFilter
QuadraticFilter
CubicFilter
CatromFilter
MitchellFilter
JincFilter
SincFilter
SincFastFilter
KaiserFilter
WelchFilter
ParzenFilter
BohmanFilter
BartlettFilter
LagrangeFilter
LanczosFilter
LanczosSharpFilter
Lanczos2Filter
Lanczos2SharpFilter
RobidouxFilter
RobidouxSharpFilter
CosineFilter
SplineFilter
LanczosRadiusFilter
SentinelFilter
Definition at line 32 of file resample.h.
Function Documentation
MagickExport ResampleFilter* AcquireResampleFilter (const Image * , ExceptionInfo *)
MagickExport ResampleFilter * DestroyResampleFilter (ResampleFilter *)
Definition at line 263 of file resample.c.
References _ResampleFilter::debug, DestroyCacheView(), DestroyImage(), DestroyResizeFilter(), _Image::filename, GetMagickModule, _ResampleFilter::image, LogMagickEvent(), MagickFalse, MagickSignature, RelinquishMagickMemory(), _ResampleFilter::signature, TraceEvent, and _ResampleFilter::view.
Referenced by CompositeImage(), and DestroyResampleFilterThreadSet().
MagickExport MagickBooleanType ResamplePixelColor (ResampleFilter * , const double , const double , PixelInfo * , ExceptionInfo *)
MagickExport void ScaleResampleFilter (ResampleFilter * , const double , const double , const double , const double)
MagickExport void SetResampleFilter (ResampleFilter * , const FilterTypes)
Definition at line 1241 of file resample.c.
References AcquireResizeFilter(), CommandOptionToMnemonic(), DestroyResizeFilter(), _ResampleFilter::do_interpolate, _ResampleFilter::exception, _ResampleFilter::filter, _ResampleFilter::filter_lut, GetImageArtifact(), GetMagickModule, GetMagickPrecision(), GetResizeFilterSupport(), GetResizeFilterWeight(), IfStringTrue, _ResampleFilter::image, MagickFalse, MagickFilterOptions, MagickSignature, MagickTrue, ModuleError, PointFilter, RobidouxFilter, ScaleResampleFilter(), _ResampleFilter::signature, _ResampleFilter::support, ThrowMagickException(), UndefinedFilter, and WLUT_WIDTH.
Referenced by AcquireResampleFilter(), AcquireResampleFilterThreadSet(), and CompositeImage().
MagickExport MagickBooleanType SetResampleFilterInterpolateMethod (ResampleFilter * , const PixelInterpolateMethod)
MagickExport MagickBooleanType SetResampleFilterVirtualPixelMethod (ResampleFilter * , const VirtualPixelMethod)
Definition at line 1443 of file resample.c.
References _ResampleFilter::debug, _Image::filename, GetMagickModule, _ResampleFilter::image, LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, SetCacheViewVirtualPixelMethod(), _ResampleFilter::signature, TraceEvent, UndefinedVirtualPixelMethod, _ResampleFilter::view, and _ResampleFilter::virtual_pixel.
Referenced by AcquireResampleFilter(), and AcquireResampleFilterThreadSet().