MagickCore: resize.c File Reference
resize.c File Reference
#include "MagickCore/studio.h"
#include "MagickCore/artifact.h"
#include "MagickCore/blob.h"
#include "MagickCore/cache.h"
#include "MagickCore/cache-view.h"
#include "MagickCore/channel.h"
#include "MagickCore/color.h"
#include "MagickCore/color-private.h"
#include "MagickCore/draw.h"
#include "MagickCore/exception.h"
#include "MagickCore/exception-private.h"
#include "MagickCore/gem.h"
#include "MagickCore/image.h"
#include "MagickCore/image-private.h"
#include "MagickCore/list.h"
#include "MagickCore/memory_.h"
#include "MagickCore/memory-private.h"
#include "MagickCore/magick.h"
#include "MagickCore/pixel-accessor.h"
#include "MagickCore/property.h"
#include "MagickCore/monitor.h"
#include "MagickCore/monitor-private.h"
#include "MagickCore/option.h"
#include "MagickCore/pixel.h"
#include "MagickCore/pixel-private.h"
#include "MagickCore/quantum-private.h"
#include "MagickCore/resample.h"
#include "MagickCore/resample-private.h"
#include "MagickCore/resize.h"
#include "MagickCore/resize-private.h"
#include "MagickCore/resource_.h"
#include "MagickCore/string_.h"
#include "MagickCore/string-private.h"
#include "MagickCore/thread-private.h"
#include "MagickCore/token.h"
#include "MagickCore/utility.h"
#include "MagickCore/utility-private.h"
#include "MagickCore/version.h"
Data Structures
struct _ResizeFilter
struct _ContributionInfo
Macros
#define InterpolativeResizeImageTag "Resize/Image"
#define MagnifyImageTag "Magnify/Image"
#define ResampleImageTag "Resample/Image"
#define ResizeImageTag "Resize/Image"
#define SampleImageTag "Sample/Image"
#define ScaleImageTag "Scale/Image"
#define SampleFactor 5
Typedefs
typedef struct _ContributionInfo ContributionInfo
Functions
static double I0 (double x)
static double BesselOrderOne (double)
static double Sinc (const double, const ResizeFilter *)
static double SincFast (const double, const ResizeFilter *)
static double Blackman (const double x, const ResizeFilter *magick_unused(resize_filter))
static double Bohman (const double x, const ResizeFilter *magick_unused(resize_filter))
static double Box (const double magick_unused(x), const ResizeFilter *magick_unused(resize_filter))
static double Cosine (const double x, const ResizeFilter *magick_unused(resize_filter))
static double CubicBC (const double x, const ResizeFilter *resize_filter)
static double Gaussian (const double x, const ResizeFilter *resize_filter)
static double Hann (const double x, const ResizeFilter *magick_unused(resize_filter))
static double Hamming (const double x, const ResizeFilter *magick_unused(resize_filter))
static double Jinc (const double x, const ResizeFilter *magick_unused(resize_filter))
static double Kaiser (const double x, const ResizeFilter *resize_filter)
static double Lagrange (const double x, const ResizeFilter *resize_filter)
static double Quadratic (const double x, const ResizeFilter *magick_unused(resize_filter))
static double Sinc (const double x, const ResizeFilter *magick_unused(resize_filter))
static double SincFast (const double x, const ResizeFilter *magick_unused(resize_filter))
static double Triangle (const double x, const ResizeFilter *magick_unused(resize_filter))
static double Welch (const double x, const ResizeFilter *magick_unused(resize_filter))
MagickPrivate ResizeFilter * AcquireResizeFilter (const Image *image, const FilterTypes filter, const MagickBooleanType cylindrical, ExceptionInfo *exception)
MagickExport Image * AdaptiveResizeImage (const Image *image, const size_t columns, const size_t rows, ExceptionInfo *exception)
static double J1 (double x)
static double P1 (double x)
static double Q1 (double x)
MagickPrivate ResizeFilter * DestroyResizeFilter (ResizeFilter *resize_filter)
MagickPrivate double GetResizeFilterSupport (const ResizeFilter *resize_filter)
MagickPrivate double GetResizeFilterWeight (const ResizeFilter *resize_filter, const double x)
MagickExport Image * InterpolativeResizeImage (const Image *image, const size_t columns, const size_t rows, const PixelInterpolateMethod method, ExceptionInfo *exception)
MagickExport Image * LiquidRescaleImage (const Image *image, const size_t magick_unused(columns), const size_t magick_unused(rows), const double magick_unused(delta_x), const double magick_unused(rigidity), ExceptionInfo *exception)
MagickExport Image * MagnifyImage (const Image *image, ExceptionInfo *exception)
MagickExport Image * MinifyImage (const Image *image, ExceptionInfo *exception)
MagickExport Image * ResampleImage (const Image *image, const double x_resolution, const double y_resolution, const FilterTypes filter, ExceptionInfo *exception)
static ContributionInfo ** DestroyContributionThreadSet (ContributionInfo **contribution)
static ContributionInfo ** AcquireContributionThreadSet (const size_t count)
static double MagickMax (const double x, const double y)
static double MagickMin (const double x, const double y)
static MagickBooleanType HorizontalFilter (const ResizeFilter *resize_filter, const Image *image, Image *resize_image, const double x_factor, const MagickSizeType span, MagickOffsetType *offset, ExceptionInfo *exception)
static MagickBooleanType VerticalFilter (const ResizeFilter *resize_filter, const Image *image, Image *resize_image, const double y_factor, const MagickSizeType span, MagickOffsetType *offset, ExceptionInfo *exception)
MagickExport Image * ResizeImage (const Image *image, const size_t columns, const size_t rows, const FilterTypes filter, ExceptionInfo *exception)
MagickExport Image * SampleImage (const Image *image, const size_t columns, const size_t rows, ExceptionInfo *exception)
MagickExport Image * ScaleImage (const Image *image, const size_t columns, const size_t rows, ExceptionInfo *exception)
MagickExport Image * ThumbnailImage (const Image *image, const size_t columns, const size_t rows, ExceptionInfo *exception)
Macro Definition Documentation
#define InterpolativeResizeImageTag "Resize/Image"
Referenced by InterpolativeResizeImage().
#define MagnifyImageTag "Magnify/Image"
Referenced by MagnifyImage().
#define ResampleImageTag "Resample/Image"
#define ResizeImageTag "Resize/Image"
Referenced by HorizontalFilter(), and VerticalFilter().
#define SampleFactor 5
Referenced by ThumbnailImage().
#define SampleImageTag "Sample/Image"
Referenced by SampleImage().
#define ScaleImageTag "Scale/Image"
Referenced by ScaleImage().
Typedef Documentation
typedef struct _ContributionInfo ContributionInfo
Function Documentation
static ContributionInfo** AcquireContributionThreadSet (const size_t count) static
Definition at line 2307 of file resize.c.
References AcquireAlignedMemory(), AcquireQuantumMemory(), DestroyContributionThreadSet(), GetMagickResourceLimit(), MagickAssumeAligned, ResetMagickMemory(), and ThreadResource.
Referenced by HorizontalFilter(), and VerticalFilter().
MagickPrivate ResizeFilter* AcquireResizeFilter (const Image * image, const FilterTypes filter, const MagickBooleanType cylindrical, ExceptionInfo * exception)
Definition at line 691 of file resize.c.
References AcquireMagickMemory(), Blackman(), BlackmanFilter, _ResizeFilter::blur, Bohman(), BohmanFilter, Box(), BoxFilter, CatromFilter, _ResizeFilter::coefficient, CommandOptionToMnemonic(), Cosine(), CosineFilter, CubicBC(), CubicFilter, _Image::debug, DeleteImageArtifact(), _Image::filename, _ResizeFilter::filter, FormatLocaleFile(), Gaussian(), GaussianFilter, GetImageArtifact(), GetMagickModule, GetMagickPrecision(), GetResizeFilterSupport(), GetResizeFilterWeight(), Hamming(), HammingFilter, Hann(), HannFilter, HermiteFilter, I0(), IfMagickTrue, IfStringTrue, Jinc(), JincFilter, Kaiser(), KaiserFilter, Lagrange(), LagrangeFilter, Lanczos2Filter, Lanczos2SharpFilter, LanczosFilter, LanczosRadiusFilter, LanczosSharpFilter, LogMagickEvent(), Magick2PI, MagickEpsilon, MagickFalse, MagickFilterOptions, MagickPI, MagickSignature, MagickSQ1_2, MitchellFilter, ParseCommandOption(), PerceptibleReciprocal(), PointFilter, Quadratic(), QuadraticFilter, ResetMagickMemory(), ResourceLimitFatalError, RobidouxFilter, RobidouxSharpFilter, _ResizeFilter::scale, SentinelFilter, _ResizeFilter::signature, _ExceptionInfo::signature, _Image::signature, Sinc(), SincFast(), SincFastFilter, SincFilter, SplineFilter, StringToDouble(), StringToLong(), _ResizeFilter::support, ThrowFatalException, TraceEvent, Triangle(), TriangleFilter, UndefinedFilter, Welch(), WelchFilter, _ResizeFilter::window, and _ResizeFilter::window_support.
MagickExport Image* AdaptiveResizeImage (const Image * image, const size_t columns, const size_t rows, ExceptionInfo * exception)
Definition at line 1220 of file resize.c.
References InterpolativeResizeImage(), and MeshInterpolatePixel.
static double BesselOrderOne (double x)
Definition at line 1421 of file resize.c.
References J1(), MagickPI, P1(), and Q1().
Referenced by Jinc().
static double Blackman (const double x, const ResizeFilter * magick_unusedresize_filter) static
Definition at line 144 of file resize.c.
References MagickPI.
Referenced by AcquireResizeFilter().
static double Bohman (const double x, const ResizeFilter * magick_unusedresize_filter) static
Definition at line 158 of file resize.c.
References MagickPI.
Referenced by AcquireResizeFilter().
static double Box (const double magick_unusedx, const ResizeFilter * magick_unusedresize_filter) static
Definition at line 174 of file resize.c.
Referenced by AcquireResizeFilter(), and GetResizeFilterWeight().
static double Cosine (const double x, const ResizeFilter * magick_unusedresize_filter) static
Definition at line 185 of file resize.c.
References MagickPI2.
Referenced by AcquireResizeFilter().
static double CubicBC (const double x, const ResizeFilter * resize_filter) static
Definition at line 195 of file resize.c.
References _ResizeFilter::coefficient.
Referenced by AcquireResizeFilter().
static ContributionInfo** DestroyContributionThreadSet (ContributionInfo ** contribution) static
Definition at line 2292 of file resize.c.
References GetMagickResourceLimit(), RelinquishAlignedMemory(), RelinquishMagickMemory(), and ThreadResource.
Referenced by AcquireContributionThreadSet(), HorizontalFilter(), and VerticalFilter().
MagickPrivate ResizeFilter* DestroyResizeFilter (ResizeFilter * resize_filter)
Definition at line 1464 of file resize.c.
References MagickSignature, RelinquishMagickMemory(), and _ResizeFilter::signature.
Referenced by DestroyResampleFilter(), ResizeImage(), and SetResampleFilter().
static double Gaussian (const double x, const ResizeFilter * resize_filter) static
Definition at line 235 of file resize.c.
References _ResizeFilter::coefficient.
Referenced by AcquireResizeFilter().
MagickPrivate double GetResizeFilterSupport (const ResizeFilter * resize_filter)
Definition at line 1496 of file resize.c.
References _ResizeFilter::blur, MagickSignature, _ResizeFilter::signature, and _ResizeFilter::support.
MagickPrivate double GetResizeFilterWeight (const ResizeFilter * resize_filter, const double x)
Definition at line 1531 of file resize.c.
References _ResizeFilter::blur, Box(), _ResizeFilter::filter, MagickEpsilon, MagickSignature, _ResizeFilter::scale, _ResizeFilter::signature, _ResizeFilter::window, and _ResizeFilter::window_support.
Referenced by AcquireResizeFilter(), HorizontalFilter(), ResamplePixelColor(), SetResampleFilter(), and VerticalFilter().
static double Hamming (const double x, const ResizeFilter * magick_unusedresize_filter) static
Definition at line 281 of file resize.c.
References MagickPI.
Referenced by AcquireResizeFilter().
static double Hann (const double x, const ResizeFilter * magick_unusedresize_filter) static
Definition at line 270 of file resize.c.
References MagickPI.
Referenced by AcquireResizeFilter().
static MagickBooleanType HorizontalFilter (const ResizeFilter * resize_filter, const Image * image, Image * resize_image, const double x_factor, const MagickSizeType span, MagickOffsetType * offset, ExceptionInfo * exception) static
Definition at line 2348 of file resize.c.
References AcquireAuthenticCacheView(), AcquireContributionThreadSet(), AcquireVirtualCacheView(), BlendPixelTrait, ClampToQuantum(), _Image::columns, CopyPixelTrait, DestroyCacheView(), DestroyContributionThreadSet(), DirectClass, _Image::filename, GetCacheViewVirtualPixels(), GetMagickModule, GetOpenMPThreadId(), GetPixelAlpha(), GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelReadMask(), GetResizeFilterSupport(), GetResizeFilterWeight(), MagickEpsilon, MagickFalse, MagickMax(), MagickMin(), MagickTrue, PerceptibleReciprocal(), _Image::progress_monitor, QuantumScale, QueueCacheViewAuthenticPixels(), ResizeImageTag, ResourceLimitError, _Image::rows, SetImageProgress(), SetImageStorageClass(), SetPixelChannel(), _Image::storage_class, SyncCacheViewAuthenticPixels(), ThrowMagickException(), and UndefinedPixelTrait.
Referenced by ResizeImage().
static double I0 (double x) static
Definition at line 1271 of file resize.c.
References MagickEpsilon.
Referenced by AcquireResizeFilter(), and Kaiser().
MagickExport Image* InterpolativeResizeImage (const Image * image, const size_t columns, const size_t rows, const PixelInterpolateMethod method, ExceptionInfo * exception)
Definition at line 1590 of file resize.c.
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), CloneImage(), _Image::columns, _Image::debug, DestroyCacheView(), DestroyImage(), DirectClass, _Image::filename, GetMagickModule, GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelReadMask(), InterpolatePixelChannels(), InterpolativeResizeImageTag, LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, _Image::progress_monitor, QueueCacheViewAuthenticPixels(), _Image::rows, SetImageProgress(), SetImageStorageClass(), _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), TraceEvent, UndefinedPixelTrait, _PointInfo::x, and _PointInfo::y.
Referenced by AdaptiveResizeImage().
static double J1 (double x) static
Definition at line 1296 of file resize.c.
Referenced by BesselOrderOne().
static double Jinc (const double x, const ResizeFilter * magick_unusedresize_filter) static
Definition at line 292 of file resize.c.
References BesselOrderOne(), and MagickPI.
Referenced by AcquireResizeFilter().
static double Kaiser (const double x, const ResizeFilter * resize_filter) static
Definition at line 308 of file resize.c.
References _ResizeFilter::coefficient, and I0().
Referenced by AcquireResizeFilter().
static double Lagrange (const double x, const ResizeFilter * resize_filter) static
Definition at line 326 of file resize.c.
References _ResizeFilter::support, and _ResizeFilter::window_support.
Referenced by AcquireResizeFilter().
MagickExport Image* LiquidRescaleImage (const Image * image, const size_t magick_unusedcolumns, const size_t magick_unusedrows, const double magick_unuseddelta_x, const double magick_unusedrigidity, ExceptionInfo * exception)
Definition at line 1923 of file resize.c.
References _Image::debug, _Image::filename, GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, MissingDelegateError, _ExceptionInfo::signature, _Image::signature, ThrowMagickException(), and TraceEvent.
static double MagickMax (const double x, const double y) inline static
Definition at line 2334 of file resize.c.
Referenced by HorizontalFilter(), and VerticalFilter().
static double MagickMin (const double x, const double y) inline static
Definition at line 2341 of file resize.c.
Referenced by HorizontalFilter(), and VerticalFilter().
MagickExport Image* MagnifyImage (const Image * image, ExceptionInfo * exception)
Definition at line 1965 of file resize.c.
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), CloneImage(), _Image::columns, _Image::debug, DestroyCacheView(), DestroyImage(), _Image::filename, GetCacheViewVirtualPixels(), GetMagickModule, GetPixelChannels(), GetPixelIntensity(), LogMagickEvent(), MagickEpsilon, MagickFalse, MagickSignature, MagickTrue, MagnifyImageTag, _Image::progress_monitor, QueueCacheViewAuthenticPixels(), _Image::rows, SetImageProgress(), _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), and TraceEvent.
MagickExport Image* MinifyImage (const Image * image, ExceptionInfo * exception)
Definition at line 2156 of file resize.c.
References _Image::columns, _Image::debug, _Image::filename, GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, ResizeImage(), _Image::rows, _ExceptionInfo::signature, _Image::signature, SplineFilter, and TraceEvent.
static double P1 (double x) static
Definition at line 1342 of file resize.c.
Referenced by BesselOrderOne().
static double Q1 (double x) static
Definition at line 1382 of file resize.c.
Referenced by BesselOrderOne().
static double Quadratic (const double x, const ResizeFilter * magick_unusedresize_filter) static
Definition at line 359 of file resize.c.
Referenced by AcquireResizeFilter().
MagickExport Image* ResampleImage (const Image * image, const double x_resolution, const double y_resolution, const FilterTypes filter, ExceptionInfo * exception)
Definition at line 2206 of file resize.c.
References _Image::columns, _Image::debug, _Image::filename, GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, ResizeImage(), _Image::resolution, _Image::rows, _ExceptionInfo::signature, _Image::signature, TraceEvent, _PointInfo::x, and _PointInfo::y.
MagickExport Image* ResizeImage (const Image * image, const size_t columns, const size_t rows, const FilterTypes filter, ExceptionInfo * exception)
Definition at line 2768 of file resize.c.
References AcquireResizeFilter(), _Image::alpha_trait, BlendPixelTrait, CloneImage(), _Image::columns, _Image::debug, DestroyImage(), DestroyResizeFilter(), _Image::filename, GetMagickModule, HorizontalFilter(), ImageError, LanczosFilter, LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, MitchellFilter, PointFilter, PseudoClass, _Image::rows, _ExceptionInfo::signature, _Image::signature, _Image::storage_class, ThrowImageException, TraceEvent, _Image::type, UndefinedFilter, and VerticalFilter().
Referenced by MinifyImage(), MorphImages(), ReadImage(), ResampleImage(), ResamplePixelColor(), ThumbnailImage(), and TransformImage().
MagickExport Image* SampleImage (const Image * image, const size_t columns, const size_t rows, ExceptionInfo * exception)
Definition at line 2899 of file resize.c.
References AcquireAuthenticCacheView(), AcquireQuantumMemory(), AcquireVirtualCacheView(), CloneImage(), _Image::columns, _Image::debug, DestroyCacheView(), DestroyImage(), _Image::filename, GetCacheViewVirtualPixels(), GetImageArtifact(), GetMagickModule, GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelReadMask(), ImageError, LogMagickEvent(), MagickEpsilon, MagickFalse, MagickSignature, MagickTrue, ParseGeometry(), _Image::progress_monitor, QueueCacheViewAuthenticPixels(), RelinquishMagickMemory(), ResourceLimitError, _GeometryInfo::rho, _Image::rows, SampleImageTag, SetImageProgress(), SetPixelChannel(), _GeometryInfo::sigma, SigmaValue, _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), ThrowImageException, TraceEvent, _Image::type, UndefinedPixelTrait, _PointInfo::x, and _PointInfo::y.
Referenced by ThumbnailImage().
MagickExport Image* ScaleImage (const Image * image, const size_t columns, const size_t rows, ExceptionInfo * exception)
Definition at line 3104 of file resize.c.
References AcquireAuthenticCacheView(), AcquireQuantumMemory(), AcquireVirtualCacheView(), AlphaPixelChannel, BlendPixelTrait, ClampToQuantum(), CloneImage(), _Image::columns, CompositePixelChannel, _Image::debug, DestroyCacheView(), DestroyImage(), DirectClass, _Image::filename, GetCacheViewVirtualPixels(), GetMagickModule, GetPixelAlpha(), GetPixelChannelChannel(), GetPixelChannelOffset(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelReadMask(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, MaxPixelChannels, PerceptibleReciprocal(), QuantumScale, QueueCacheViewAuthenticPixels(), RelinquishMagickMemory(), ResourceLimitError, _Image::rows, ScaleImageTag, SetImageProgress(), SetImageStorageClass(), SetPixelChannel(), _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), ThrowImageException, TraceEvent, _Image::type, UndefinedPixelTrait, _PointInfo::x, and _PointInfo::y.
static double Sinc (const double , const ResizeFilter *)
Referenced by AcquireResizeFilter().
static double Sinc (const double x, const ResizeFilter * magick_unusedresize_filter) static
Definition at line 372 of file resize.c.
References MagickPI.
static double SincFast (const double , const ResizeFilter *)
Referenced by AcquireResizeFilter().
static double SincFast (const double x, const ResizeFilter * magick_unusedresize_filter) static
Definition at line 387 of file resize.c.
References MagickPI.
MagickExport Image* ThumbnailImage (const Image * image, const size_t columns, const size_t rows, ExceptionInfo * exception)
Definition at line 3582 of file resize.c.
References _Image::alpha_trait, BlendPixelTrait, _Image::columns, ConcatenateMagickString(), CopyMagickString(), _Image::debug, DeleteImageProfile(), DeleteImageProperty(), _Image::depth, DestroyImage(), _Image::filename, _Image::filter, FormatLocaleString(), FormatMagickSize(), GetBlobSize(), GetImageListLength(), GetMagickModule, GetMagickVersion(), GetNextImageProfile(), GetPathAttributes(), IfMagickTrue, _Image::interlace, LocaleCompare(), LocaleLower(), LogMagickEvent(), _Image::magick, _Image::magick_columns, _Image::magick_filename, _Image::magick_rows, MagickFalse, MagickSignature, MaxTextExtent, NoInterlace, OpaqueAlphaChannel, _Image::page, ParseAbsoluteGeometry(), ResetImageProfileIterator(), ResizeImage(), _Image::rows, SampleFactor, SampleImage(), SetImageAlphaChannel(), SetImageProperty(), _ExceptionInfo::signature, _Image::signature, and TraceEvent.
Referenced by MontageImageList(), and PreviewImage().
static double Triangle (const double x, const ResizeFilter * magick_unusedresize_filter) static
Definition at line 481 of file resize.c.
Referenced by AcquireResizeFilter().
static MagickBooleanType VerticalFilter (const ResizeFilter * resize_filter, const Image * image, Image * resize_image, const double y_factor, const MagickSizeType span, MagickOffsetType * offset, ExceptionInfo * exception) static
Definition at line 2560 of file resize.c.
References AcquireAuthenticCacheView(), AcquireContributionThreadSet(), AcquireVirtualCacheView(), BlendPixelTrait, ClampToQuantum(), _Image::columns, CopyPixelTrait, DestroyCacheView(), DestroyContributionThreadSet(), DirectClass, _Image::filename, GetCacheViewVirtualPixels(), GetMagickModule, GetOpenMPThreadId(), GetPixelAlpha(), GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelReadMask(), GetResizeFilterSupport(), GetResizeFilterWeight(), MagickEpsilon, MagickFalse, MagickMax(), MagickMin(), MagickTrue, PerceptibleReciprocal(), _Image::progress_monitor, QuantumScale, QueueCacheViewAuthenticPixels(), ResizeImageTag, ResourceLimitError, _Image::rows, SetImageProgress(), SetImageStorageClass(), SetPixelChannel(), _Image::storage_class, SyncCacheViewAuthenticPixels(), ThrowMagickException(), and UndefinedPixelTrait.
Referenced by ResizeImage().
static double Welch (const double x, const ResizeFilter * magick_unusedresize_filter) static
Definition at line 494 of file resize.c.
Referenced by AcquireResizeFilter().