MagickCore: resize-private.h File Reference
resize-private.h File Reference
Typedefs
typedef struct _ResizeFilter ResizeFilter
Functions
MagickPrivate double GetResizeFilterSupport (const ResizeFilter *)
MagickPrivate double GetResizeFilterWeight (const ResizeFilter *, const double)
MagickPrivate ResizeFilter * AcquireResizeFilter (const Image *, const FilterTypes, const MagickBooleanType, ExceptionInfo *)
MagickPrivate ResizeFilter * DestroyResizeFilter (ResizeFilter *)
Typedef Documentation
typedef struct _ResizeFilter ResizeFilter
Definition at line 25 of file resize-private.h.
Function Documentation
MagickPrivate ResizeFilter* AcquireResizeFilter (const Image * , const FilterTypes , const MagickBooleanType , ExceptionInfo *)
Referenced by ResizeImage(), and SetResampleFilter().
MagickPrivate ResizeFilter * DestroyResizeFilter (ResizeFilter *)
Definition at line 1464 of file resize.c.
References MagickSignature, RelinquishMagickMemory(), and _ResizeFilter::signature.
Referenced by DestroyResampleFilter(), ResizeImage(), and SetResampleFilter().
MagickPrivate double GetResizeFilterSupport (const ResizeFilter *)
Referenced by AcquireResizeFilter(), HorizontalFilter(), SetResampleFilter(), and VerticalFilter().
MagickPrivate double GetResizeFilterWeight (const ResizeFilter * , const double)
Definition at line 1531 of file resize.c.
References _ResizeFilter::blur, Box(), _ResizeFilter::filter, MagickEpsilon, MagickSignature, _ResizeFilter::scale, _ResizeFilter::signature, _ResizeFilter::window, and _ResizeFilter::window_support.
Referenced by AcquireResizeFilter(), HorizontalFilter(), ResamplePixelColor(), SetResampleFilter(), and VerticalFilter().