MagickCore: segment.c File Reference
segment.c File Reference
#include "MagickCore/studio.h"
#include "MagickCore/cache.h"
#include "MagickCore/color.h"
#include "MagickCore/colormap.h"
#include "MagickCore/colorspace.h"
#include "MagickCore/colorspace-private.h"
#include "MagickCore/exception.h"
#include "MagickCore/exception-private.h"
#include "MagickCore/image.h"
#include "MagickCore/image-private.h"
#include "MagickCore/memory_.h"
#include "MagickCore/monitor.h"
#include "MagickCore/monitor-private.h"
#include "MagickCore/pixel-accessor.h"
#include "MagickCore/pixel-private.h"
#include "MagickCore/quantize.h"
#include "MagickCore/quantum.h"
#include "MagickCore/quantum-private.h"
#include "MagickCore/resource_.h"
#include "MagickCore/segment.h"
#include "MagickCore/string_.h"
#include "MagickCore/thread-private.h"
Data Structures
struct _ExtentPacket
struct _Cluster
struct _IntervalTree
struct _ZeroCrossing
Macros
#define MaxDimension 3
#define DeltaTau 0.5f
#define WeightingExponent 2.5
#define SegmentPower(ratio) pow(ratio,(double) (1.0/(weighting_exponent-1.0)));
#define Tau 5.2f
#define SegmentImageTag "Segment/Image"
Typedefs
typedef struct _ExtentPacket ExtentPacket
typedef struct _Cluster Cluster
typedef struct _IntervalTree IntervalTree
typedef struct _ZeroCrossing ZeroCrossing
Functions
static double OptimalTau (const ssize_t *, const double, const double, const double, const double, short *)
static ssize_t DefineRegion (const short *, ExtentPacket *)
static void InitializeHistogram (const Image *, ssize_t **, ExceptionInfo *)
static void ScaleSpace (const ssize_t *, const double, double *)
static void ZeroCrossHistogram (double *, const double, short *)
static MagickBooleanType Classify (Image *image, short **extrema, const double cluster_threshold, const double weighting_exponent, const MagickBooleanType verbose, ExceptionInfo *exception)
static ssize_t MagickAbsoluteValue (const ssize_t x)
static ssize_t MagickMax (const ssize_t x, const ssize_t y)
static ssize_t MagickMin (const ssize_t x, const ssize_t y)
static void ConsolidateCrossings (ZeroCrossing *zero_crossing, const size_t number_crossings)
static void DerivativeHistogram (const double *histogram, double *derivative)
MagickExport MagickBooleanType GetImageDynamicThreshold (const Image *image, const double cluster_threshold, const double smooth_threshold, PixelInfo *pixel, ExceptionInfo *exception)
static void InitializeList (IntervalTree **list, ssize_t *number_nodes, IntervalTree *node)
static void MeanStability (IntervalTree *node)
static void Stability (IntervalTree *node)
static IntervalTree * InitializeIntervalTree (const ZeroCrossing *zero_crossing, const size_t number_crossings)
static void ActiveNodes (IntervalTree **list, ssize_t *number_nodes, IntervalTree *node)
static void FreeNodes (IntervalTree *node)
MagickExport MagickBooleanType SegmentImage (Image *image, const ColorspaceType colorspace, const MagickBooleanType verbose, const double cluster_threshold, const double smooth_threshold, ExceptionInfo *exception)
Variables
static const int Blue = 2
static const int Green = 1
static const int Red = 0
static const int SafeMargin = 3
static const int TreeLength = 600
Macro Definition Documentation
#define DeltaTau 0.5f
Definition at line 112 of file segment.c.
Referenced by GetImageDynamicThreshold(), and SegmentImage().
#define MaxDimension 3
Definition at line 111 of file segment.c.
Referenced by Classify(), GetImageDynamicThreshold(), and SegmentImage().
#define SegmentImageTag "Segment/Image"
Referenced by Classify(), and GetImageDynamicThreshold().
#define SegmentPower (ratio) pow(ratio,(double) (1.0/(weighting_exponent-1.0)));
Definition at line 118 of file segment.c.
Referenced by Classify().
#define Tau 5.2f
Definition at line 120 of file segment.c.
Referenced by GetImageDynamicThreshold(), and SegmentImage().
#define WeightingExponent 2.5
Definition at line 117 of file segment.c.
Referenced by SegmentImage().
Typedef Documentation
typedef struct _Cluster Cluster
typedef struct _ExtentPacket ExtentPacket
typedef struct _IntervalTree IntervalTree
typedef struct _ZeroCrossing ZeroCrossing
Function Documentation
static void ActiveNodes (IntervalTree ** list, ssize_t * number_nodes, IntervalTree * node) static
Definition at line 1483 of file segment.c.
References _IntervalTree::child, _IntervalTree::mean_stability, _IntervalTree::sibling, and _IntervalTree::stability.
Referenced by OptimalTau().
static MagickBooleanType Classify (Image * image, short ** extrema, const double cluster_threshold, const double weighting_exponent, const MagickBooleanType verbose, ExceptionInfo * exception) static
Definition at line 246 of file segment.c.
References AcquireAuthenticCacheView(), AcquireImageColormap(), AcquireMagickMemory(), AcquireQuantumMemory(), AcquireVirtualCacheView(), _Cluster::blue, Blue, _PixelInfo::blue, _ExtentPacket::center, ClampToQuantum(), _Image::colormap, _Image::colors, _Image::columns, _Cluster::count, DefineRegion(), DestroyCacheView(), _Image::filename, FormatLocaleFile(), GetCacheViewAuthenticPixels(), GetCacheViewVirtualPixels(), GetPixelBlue(), GetPixelChannels(), GetPixelGreen(), GetPixelRed(), _Cluster::green, Green, _PixelInfo::green, _Cluster::id, ImageError, _ExtentPacket::index, _ExtentPacket::left, MagickFalse, MagickTrue, MaxDimension, _Cluster::next, _Image::progress_monitor, _Cluster::red, Red, _PixelInfo::red, RelinquishMagickMemory(), ResetMagickMemory(), ResourceLimitError, _ExtentPacket::right, _Image::rows, SafeMargin, SegmentImageTag, SegmentPower, SetImageProgress(), SetPixelIndex(), SyncCacheViewAuthenticPixels(), SyncImage(), and ThrowBinaryException.
Referenced by SegmentImage().
static void ConsolidateCrossings (ZeroCrossing * zero_crossing, const size_t number_crossings) static
Definition at line 721 of file segment.c.
References _ZeroCrossing::crossings, MagickMax(), and MagickMin().
Referenced by OptimalTau().
static ssize_t DefineRegion (const short * extrema, ExtentPacket * extents) static
Definition at line 838 of file segment.c.
References _ExtentPacket::center, _ExtentPacket::index, _ExtentPacket::left, MagickFalse, MagickTrue, and _ExtentPacket::right.
Referenced by Classify(), and GetImageDynamicThreshold().
static void DerivativeHistogram (const double * histogram, double * derivative) static
Definition at line 894 of file segment.c.
Referenced by OptimalTau().
static void FreeNodes (IntervalTree * node) static
Definition at line 1500 of file segment.c.
References _IntervalTree::child, RelinquishMagickMemory(), and _IntervalTree::sibling.
Referenced by OptimalTau().
MagickExport MagickBooleanType GetImageDynamicThreshold (const Image * image, const double cluster_threshold, const double smooth_threshold, PixelInfo * pixel, ExceptionInfo * exception)
Definition at line 951 of file segment.c.
References AcquireMagickMemory(), AcquireQuantumMemory(), _Cluster::blue, Blue, _PixelInfo::blue, _ExtentPacket::center, _Image::columns, _Cluster::count, _Image::debug, DefineRegion(), DeltaTau, _Image::filename, GetMagickModule, GetPixelBlue(), GetPixelChannels(), GetPixelGreen(), GetPixelInfo(), GetPixelRed(), GetVirtualPixels(), _Cluster::green, Green, _PixelInfo::green, _Cluster::id, _ExtentPacket::index, InitializeHistogram(), _ExtentPacket::left, LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, MaxDimension, _Cluster::next, OptimalTau(), _Cluster::red, Red, _PixelInfo::red, RelinquishMagickMemory(), ResetMagickMemory(), ResourceLimitError, _ExtentPacket::right, _Image::rows, SafeMargin, SegmentImageTag, SetImageProgress(), _Image::signature, Tau, ThrowMagickException(), and TraceEvent.
static void InitializeHistogram (const Image * image, ssize_t ** histogram, ExceptionInfo * exception) static
Definition at line 1240 of file segment.c.
References Blue, _Image::columns, GetPixelBlue(), GetPixelChannels(), GetPixelGreen(), GetPixelRed(), GetVirtualPixels(), Green, Red, and _Image::rows.
Referenced by GetImageDynamicThreshold(), and SegmentImage().
static IntervalTree* InitializeIntervalTree (const ZeroCrossing * zero_crossing, const size_t number_crossings) static
Definition at line 1358 of file segment.c.
References AcquireMagickMemory(), AcquireQuantumMemory(), _IntervalTree::child, InitializeList(), _IntervalTree::left, MeanStability(), RelinquishMagickMemory(), _IntervalTree::right, _IntervalTree::sibling, Stability(), _IntervalTree::tau, _ZeroCrossing::tau, and TreeLength.
Referenced by OptimalTau().
static void InitializeList (IntervalTree ** list, ssize_t * number_nodes, IntervalTree * node) static
Definition at line 1305 of file segment.c.
References _IntervalTree::child, and _IntervalTree::sibling.
Referenced by InitializeIntervalTree().
static ssize_t MagickAbsoluteValue (const ssize_t x) inline static
Definition at line 700 of file segment.c.
Referenced by ScaleSpace().
static ssize_t MagickMax (const ssize_t x, const ssize_t y) inline static
Definition at line 707 of file segment.c.
Referenced by ConsolidateCrossings().
static ssize_t MagickMin (const ssize_t x, const ssize_t y) inline static
Definition at line 714 of file segment.c.
Referenced by ConsolidateCrossings().
static void MeanStability (IntervalTree * node) static
Definition at line 1316 of file segment.c.
References _IntervalTree::child, _IntervalTree::mean_stability, _IntervalTree::sibling, and _IntervalTree::stability.
Referenced by InitializeIntervalTree().
static double OptimalTau (const ssize_t * histogram, const double max_tau, const double min_tau, const double delta_tau, const double smooth_threshold, short * extrema) static
Definition at line 1509 of file segment.c.
References AcquireQuantumMemory(), ActiveNodes(), _IntervalTree::child, ConsolidateCrossings(), _ZeroCrossing::crossings, DerivativeHistogram(), FreeNodes(), _ZeroCrossing::histogram, InitializeIntervalTree(), _IntervalTree::left, MagickFalse, MagickTrue, RelinquishMagickMemory(), ResourceLimitFatalError, _IntervalTree::right, ScaleSpace(), _IntervalTree::tau, _ZeroCrossing::tau, ThrowFatalException, TreeLength, and ZeroCrossHistogram().
Referenced by GetImageDynamicThreshold(), and SegmentImage().
static void ScaleSpace (const ssize_t * histogram, const double tau, double * scale_histogram)
Definition at line 1717 of file segment.c.
References AcquireQuantumMemory(), MagickAbsoluteValue(), MagickEpsilon, MagickPI, PerceptibleReciprocal(), RelinquishMagickMemory(), ResourceLimitFatalError, and ThrowFatalException.
Referenced by OptimalTau().
MagickExport MagickBooleanType SegmentImage (Image * image, const ColorspaceType colorspace, const MagickBooleanType verbose, const double cluster_threshold, const double smooth_threshold, ExceptionInfo * exception)
Definition at line 1796 of file segment.c.
References AcquireQuantumMemory(), Blue, Classify(), _Image::colorspace, _Image::debug, DeltaTau, _Image::filename, GetMagickModule, Green, InitializeHistogram(), LogMagickEvent(), MagickFalse, MagickSignature, MaxDimension, OptimalTau(), Red, RelinquishMagickMemory(), ResourceLimitError, _Image::signature, Tau, ThrowBinaryException, TraceEvent, TransformImageColorspace(), and WeightingExponent.
Referenced by PreviewImage().
static void Stability (IntervalTree * node) static
Definition at line 1346 of file segment.c.
References _IntervalTree::child, _IntervalTree::sibling, _IntervalTree::stability, and _IntervalTree::tau.
Referenced by InitializeIntervalTree().
static void ZeroCrossHistogram (double * second_derivative, const double smooth_threshold, short * crossings)
Definition at line 1897 of file segment.c.
Referenced by OptimalTau().
Variable Documentation
const int Blue = 2 static
Definition at line 183 of file segment.c.
Referenced by Classify(), GetImageDynamicThreshold(), InitializeHistogram(), and SegmentImage().
const int Green = 1 static
Definition at line 184 of file segment.c.
Referenced by Classify(), GetImageDynamicThreshold(), InitializeHistogram(), and SegmentImage().
const int Red = 0 static
Definition at line 185 of file segment.c.
Referenced by Classify(), GetImageDynamicThreshold(), InitializeHistogram(), and SegmentImage().
const int SafeMargin = 3 static
Definition at line 186 of file segment.c.
Referenced by Classify(), and GetImageDynamicThreshold().
const int TreeLength = 600 static
Definition at line 187 of file segment.c.
Referenced by InitializeIntervalTree(), and OptimalTau().