MagickCore: segment.h File Reference
segment.h File Reference
Functions
MagickExport MagickBooleanType GetImageDynamicThreshold (const Image *, const double, const double, PixelInfo *, ExceptionInfo *)
MagickExport MagickBooleanType SegmentImage (Image *, const ColorspaceType, const MagickBooleanType, const double, const double, ExceptionInfo *)
Function Documentation
MagickExport MagickBooleanType GetImageDynamicThreshold (const Image * , const double , const double , PixelInfo * , ExceptionInfo *)
MagickExport MagickBooleanType SegmentImage (Image * , const ColorspaceType , const MagickBooleanType , const double , const double , ExceptionInfo *)
Definition at line 1796 of file segment.c.
References AcquireQuantumMemory(), Blue, Classify(), _Image::colorspace, _Image::debug, DeltaTau, _Image::filename, GetMagickModule, Green, InitializeHistogram(), LogMagickEvent(), MagickFalse, MagickSignature, MaxDimension, OptimalTau(), Red, RelinquishMagickMemory(), ResourceLimitError, _Image::signature, Tau, ThrowBinaryException, TraceEvent, TransformImageColorspace(), and WeightingExponent.
Referenced by PreviewImage().