MagickCore: semaphore.h File Reference
semaphore.h File Reference
Typedefs
typedef struct SemaphoreInfo SemaphoreInfo
Functions
MagickExport SemaphoreInfo * AllocateSemaphoreInfo (void)
MagickExport void AcquireSemaphoreInfo (SemaphoreInfo **)
MagickExport void DestroySemaphoreInfo (SemaphoreInfo **)
MagickExport void LockSemaphoreInfo (SemaphoreInfo *)
MagickExport void RelinquishSemaphoreInfo (SemaphoreInfo *)
MagickExport void UnlockSemaphoreInfo (SemaphoreInfo *)
Typedef Documentation
typedef struct SemaphoreInfo SemaphoreInfo
Definition at line 25 of file semaphore.h.
Function Documentation
MagickExport void AcquireSemaphoreInfo (SemaphoreInfo **)
MagickExport SemaphoreInfo* AllocateSemaphoreInfo (void)
Definition at line 189 of file semaphore.c.
References AcquireSemaphoreMemory(), GetMagickThreadId(), SemaphoreInfo::id, MagickSignature, SemaphoreInfo::mutex, pthread_mutex_init, pthread_mutexattr_destroy, pthread_mutexattr_init, SemaphoreInfo::reference_count, ResetMagickMemory(), ResourceLimitFatalError, SemaphoreInfo::signature, and ThrowFatalException.
Referenced by AcquireImage(), AcquireRandomInfo(), AcquireSemaphoreInfo(), CloneImage(), GetBlobInfo(), GetExceptionInfo(), GetQuantumInfo(), NewHashmap(), NewLinkedList(), and NewSplayTree().
MagickExport void DestroySemaphoreInfo (SemaphoreInfo **)
MagickExport void LockSemaphoreInfo (SemaphoreInfo *)
MagickExport void RelinquishSemaphoreInfo (SemaphoreInfo *)
MagickExport void UnlockSemaphoreInfo (SemaphoreInfo *)
Definition at line 467 of file semaphore.c.
References FormatLocaleFile(), SemaphoreInfo::id, IsMagickThreadEqual(), MagickFalse, MagickSignature, SemaphoreInfo::mutex, pthread_mutex_unlock, SemaphoreInfo::reference_count, and SemaphoreInfo::signature.
Referenced by AcquireMagickMemory(), AcquireMagickResource(), AcquireUniqueFileResource(), AddValueToSplayTree(), AppendValueToLinkedList(), CacheComponentTerminus(), CatchException(), ClearLinkedList(), ClearMagickException(), CloneSplayTree(), CloseMagickLog(), CoderComponentTerminus(), ColorComponentTerminus(), ConfigureComponentTerminus(), DelegateComponentTerminus(), DeleteNodeByValueFromSplayTree(), DeleteNodeFromSplayTree(), DestroyBlob(), DestroyExceptionInfo(), DestroyHashmap(), DestroyImage(), DestroyLinkedList(), DestroyMagickMemory(), DestroyPixelCache(), DestroyPixelStream(), DestroyRandomInfo(), DestroySplayTree(), GenerateEntropicChaos(), GetCoderInfoList(), GetCoderList(), GetColorCompliance(), GetColorInfoList(), GetColorList(), GetConfigureInfo(), GetConfigureInfoList(), GetConfigureList(), GetDelegateInfo(), GetDelegateInfoList(), GetDelegateList(), GetImageMagick(), GetImageReferenceCount(), GetLastValueInLinkedList(), GetLocaleInfoList(), GetLocaleList(), GetLogInfo(), GetLogInfoList(), GetLogList(), GetMagicInfo(), GetMagicInfoList(), GetMagickInfo(), GetMagickInfoList(), GetMagickList(), GetMagickResource(), GetMagickResourceLimit(), GetMagicList(), GetMimeInfo(), GetMimeInfoList(), GetMimeList(), GetNextKeyInHashmap(), GetNextKeyInSplayTree(), GetNextValueInHashmap(), GetNextValueInLinkedList(), GetNextValueInSplayTree(), GetPolicyInfo(), GetPolicyInfoList(), GetPolicyList(), GetTypeInfoByFamily(), GetTypeInfoList(), GetTypeList(), GetValueFromHashmap(), GetValueFromLinkedList(), GetValueFromSplayTree(), IncreaseHashmapCapacity(), InheritException(), InitializeCoderList(), InitializeColorList(), InitializeConfigureList(), InitializeDelegateList(), InitializeLocaleList(), InitializeLogList(), InitializeMagickList(), InitializeMagicList(), InitializeMimeList(), InitializePolicyList(), InitializeTypeList(), InsertValueInLinkedList(), InsertValueInSortedLinkedList(), IsRightsAuthorized(), LinkedListToArray(), ListMagickResourceInfo(), LocaleComponentTerminus(), LogComponentTerminus(), LogMagickEventList(), MagicComponentTerminus(), MagickComponentTerminus(), MimeComponentTerminus(), ModifyImage(), PersistPixelCache(), PolicyComponentTerminus(), PutEntryInHashmap(), ReadImage(), ReadPixelCacheMetacontent(), ReadPixelCachePixels(), ReferenceBlob(), ReferenceImage(), ReferencePixelCache(), RegistryComponentTerminus(), RelinquishMagickMemory(), RelinquishMagickResource(), RelinquishSemaphoreInfo(), RemoveElementByValueFromLinkedList(), RemoveElementFromLinkedList(), RemoveEntryFromHashmap(), RemoveLastElementFromLinkedList(), RemoveNodeByValueFromSplayTree(), RemoveNodeFromSplayTree(), RenderX11(), ResetHashmapIterator(), ResetLinkedListIterator(), ResetSplayTree(), ResetSplayTreeIterator(), ResizeMagickMemory(), ResourceComponentTerminus(), SetImageRegistry(), SetLogEventMask(), SetLogFormat(), SetMagickResourceLimit(), SetRandomKey(), ThrowException(), TypeComponentTerminus(), UnregisterMagickInfo(), WriteImage(), WritePixelCacheMetacontent(), and WritePixelCachePixels().