MagickCore: signature.c File Reference
signature.c File Reference
#include "MagickCore/studio.h"
#include "MagickCore/cache.h"
#include "MagickCore/exception.h"
#include "MagickCore/exception-private.h"
#include "MagickCore/property.h"
#include "MagickCore/image.h"
#include "MagickCore/memory_.h"
#include "MagickCore/pixel-accessor.h"
#include "MagickCore/quantum.h"
#include "MagickCore/quantum-private.h"
#include "MagickCore/signature.h"
#include "MagickCore/signature-private.h"
#include "MagickCore/string_.h"
Data Structures
struct _SignatureInfo
Macros
#define SignatureBlocksize 64
#define SignatureDigestsize 32
#define Sigma0(x) (RotateRight(x,7) ^ RotateRight(x,18) ^ Trunc32((x) >> 3))
#define Sigma1(x) (RotateRight(x,17) ^ RotateRight(x,19) ^ Trunc32((x) >> 10))
#define Suma0(x) (RotateRight(x,2) ^ RotateRight(x,13) ^ RotateRight(x,22))
#define Suma1(x) (RotateRight(x,6) ^ RotateRight(x,11) ^ RotateRight(x,25))
Functions
static void TransformSignature (SignatureInfo *)
MagickPrivate SignatureInfo * AcquireSignatureInfo (void)
MagickPrivate SignatureInfo * DestroySignatureInfo (SignatureInfo *signature_info)
MagickPrivate void FinalizeSignature (SignatureInfo *signature_info)
MagickPrivate unsigned int GetSignatureBlocksize (const SignatureInfo *signature_info)
MagickPrivate const StringInfo * GetSignatureDigest (const SignatureInfo *signature_info)
MagickPrivate unsigned int GetSignatureDigestsize (const SignatureInfo *signature_info)
MagickPrivate void InitializeSignature (SignatureInfo *signature_info)
MagickPrivate void SetSignatureDigest (SignatureInfo *signature_info, const StringInfo *digest)
MagickExport MagickBooleanType SignatureImage (Image *image, ExceptionInfo *exception)
static unsigned int Ch (unsigned int x, unsigned int y, unsigned int z)
static unsigned int Maj (unsigned int x, unsigned int y, unsigned int z)
static unsigned int Trunc32 (unsigned int x)
static unsigned int RotateRight (unsigned int x, unsigned int n)
MagickPrivate void UpdateSignature (SignatureInfo *signature_info, const StringInfo *message)
Macro Definition Documentation
#define Sigma0 (x) (RotateRight(x,7) ^ RotateRight(x,18) ^ Trunc32((x) >> 3))
Referenced by TransformSignature().
#define Sigma1 (x) (RotateRight(x,17) ^ RotateRight(x,19) ^ Trunc32((x) >> 10))
Referenced by TransformSignature().
#define SignatureBlocksize 64
Definition at line 58 of file signature.c.
Referenced by AcquireSignatureInfo().
#define SignatureDigestsize 32
Definition at line 59 of file signature.c.
Referenced by AcquireSignatureInfo(), and FinalizeSignature().
#define Suma0 (x) (RotateRight(x,2) ^ RotateRight(x,13) ^ RotateRight(x,22))
Referenced by TransformSignature().
#define Suma1 (x) (RotateRight(x,6) ^ RotateRight(x,11) ^ RotateRight(x,25))
Referenced by TransformSignature().
Function Documentation
MagickPrivate SignatureInfo* AcquireSignatureInfo (void)
Definition at line 116 of file signature.c.
References _SignatureInfo::accumulator, AcquireMagickMemory(), AcquireQuantumMemory(), AcquireStringInfo(), _SignatureInfo::blocksize, _SignatureInfo::digest, _SignatureInfo::digestsize, InitializeSignature(), _SignatureInfo::lsb_first, MagickFalse, MagickSignature, MagickTrue, _SignatureInfo::message, ResetMagickMemory(), ResourceLimitFatalError, _SignatureInfo::signature, SignatureBlocksize, SignatureDigestsize, ThrowFatalException, and _SignatureInfo::timestamp.
static unsigned int Ch (unsigned int x, unsigned int y, unsigned int z) inline static
Definition at line 589 of file signature.c.
Referenced by TransformSignature().
MagickPrivate SignatureInfo* DestroySignatureInfo (SignatureInfo * signature_info)
Definition at line 168 of file signature.c.
References _SignatureInfo::accumulator, DestroyStringInfo(), _SignatureInfo::digest, GetMagickModule, LogMagickEvent(), MagickSignature, _SignatureInfo::message, RelinquishMagickMemory(), _SignatureInfo::signature, and TraceEvent.
Referenced by AcquireRandomInfo(), DestroyRandomInfo(), HashStringInfoType(), HashStringType(), and SignatureImage().
MagickPrivate void FinalizeSignature (SignatureInfo * signature_info)
Definition at line 207 of file signature.c.
References _SignatureInfo::accumulator, _SignatureInfo::digest, GetMagickModule, GetStringInfoDatum(), GetStringInfoLength(), _SignatureInfo::high_order, LogMagickEvent(), _SignatureInfo::low_order, MagickSignature, _SignatureInfo::message, ResetMagickMemory(), _SignatureInfo::signature, SignatureDigestsize, TraceEvent, and TransformSignature().
MagickPrivate unsigned int GetSignatureBlocksize (const SignatureInfo * signature_info)
Definition at line 297 of file signature.c.
References _SignatureInfo::blocksize, GetMagickModule, LogMagickEvent(), MagickSignature, _SignatureInfo::signature, and TraceEvent.
MagickPrivate const StringInfo* GetSignatureDigest (const SignatureInfo * signature_info)
Definition at line 328 of file signature.c.
References _SignatureInfo::digest, GetMagickModule, LogMagickEvent(), MagickSignature, _SignatureInfo::signature, and TraceEvent.
Referenced by AcquireRandomInfo(), HashStringInfoType(), HashStringType(), SetRandomKey(), and SignatureImage().
MagickPrivate unsigned int GetSignatureDigestsize (const SignatureInfo * signature_info)
Definition at line 359 of file signature.c.
References _SignatureInfo::digestsize, GetMagickModule, LogMagickEvent(), MagickSignature, _SignatureInfo::signature, and TraceEvent.
Referenced by AcquireRandomInfo(), and SetRandomKey().
MagickPrivate void InitializeSignature (SignatureInfo * signature_info)
Definition at line 390 of file signature.c.
References _SignatureInfo::accumulator, GetMagickModule, _SignatureInfo::high_order, LogMagickEvent(), _SignatureInfo::low_order, MagickSignature, _SignatureInfo::offset, _SignatureInfo::signature, and TraceEvent.
static unsigned int Maj (unsigned int x, unsigned int y, unsigned int z) inline static
Definition at line 594 of file signature.c.
Referenced by TransformSignature().
static unsigned int RotateRight (unsigned int x, unsigned int n) static
Definition at line 604 of file signature.c.
References Trunc32().
MagickPrivate void SetSignatureDigest (SignatureInfo * signature_info, const StringInfo * digest)
Definition at line 433 of file signature.c.
References _SignatureInfo::digest, MagickSignature, SetStringInfo(), and _SignatureInfo::signature.
MagickExport MagickBooleanType SignatureImage (Image * image, ExceptionInfo * exception)
Definition at line 471 of file signature.c.
References AcquireSignatureInfo(), AcquireStringInfo(), AcquireVirtualCacheView(), _Image::columns, _Image::debug, DeleteImageProperty(), DestroyCacheView(), DestroySignatureInfo(), DestroyString(), DestroyStringInfo(), _Image::filename, FinalizeSignature(), GetCacheViewVirtualPixels(), GetMagickModule, GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelReadMask(), GetSignatureDigest(), GetStringInfoDatum(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, QuantumScale, _Image::rows, SetImageProperty(), SetStringInfoLength(), _Image::signature, StringInfoToHexString(), TraceEvent, UndefinedPixelTrait, and UpdateSignature().
Referenced by GetMagickPropertyLetter(), and IdentifyImage().
static void TransformSignature (SignatureInfo * signature_info) static
Definition at line 609 of file signature.c.
References _SignatureInfo::accumulator, Ch(), GetStringInfoDatum(), _SignatureInfo::lsb_first, MagickFalse, Maj(), _SignatureInfo::message, ResetMagickMemory(), Sigma0, Sigma1, Suma0, Suma1, and Trunc32().
Referenced by FinalizeSignature(), and UpdateSignature().
static unsigned int Trunc32 (unsigned int x) inline static
Definition at line 599 of file signature.c.
Referenced by RotateRight(), TransformSignature(), and UpdateSignature().
MagickPrivate void UpdateSignature (SignatureInfo * signature_info, const StringInfo * message)
Definition at line 776 of file signature.c.
References CopyMagickMemory(), GetStringInfoDatum(), GetStringInfoLength(), _SignatureInfo::high_order, _SignatureInfo::low_order, MagickSignature, _SignatureInfo::message, _SignatureInfo::offset, SetStringInfoDatum(), _SignatureInfo::signature, TransformSignature(), and Trunc32().
Referenced by AcquireRandomInfo(), HashStringInfoType(), HashStringType(), SetRandomKey(), and SignatureImage().