MagickCore: signature.h File Reference
signature.h File Reference
Functions
MagickExport MagickBooleanType SignatureImage (Image *, ExceptionInfo *)
Function Documentation
MagickExport MagickBooleanType SignatureImage (Image * , ExceptionInfo *)
Definition at line 471 of file signature.c.
References AcquireSignatureInfo(), AcquireStringInfo(), AcquireVirtualCacheView(), _Image::columns, _Image::debug, DeleteImageProperty(), DestroyCacheView(), DestroySignatureInfo(), DestroyString(), DestroyStringInfo(), _Image::filename, FinalizeSignature(), GetCacheViewVirtualPixels(), GetMagickModule, GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelReadMask(), GetSignatureDigest(), GetStringInfoDatum(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, QuantumScale, _Image::rows, SetImageProperty(), SetStringInfoLength(), _Image::signature, StringInfoToHexString(), TraceEvent, UndefinedPixelTrait, and UpdateSignature().
Referenced by GetMagickPropertyLetter(), and IdentifyImage().