MagickCore: statistic.h File Reference
statistic.h File Reference
Data Structures
struct _ChannelStatistics
Typedefs
typedef struct _ChannelStatistics ChannelStatistics
Enumerations
enum MagickEvaluateOperator {
UndefinedEvaluateOperator, AbsEvaluateOperator, AddEvaluateOperator, AddModulusEvaluateOperator,
AndEvaluateOperator, CosineEvaluateOperator, DivideEvaluateOperator, ExponentialEvaluateOperator,
GaussianNoiseEvaluateOperator, ImpulseNoiseEvaluateOperator, LaplacianNoiseEvaluateOperator, LeftShiftEvaluateOperator,
LogEvaluateOperator, MaxEvaluateOperator, MeanEvaluateOperator, MedianEvaluateOperator,
MinEvaluateOperator, MultiplicativeNoiseEvaluateOperator, MultiplyEvaluateOperator, OrEvaluateOperator,
PoissonNoiseEvaluateOperator, PowEvaluateOperator, RightShiftEvaluateOperator, SetEvaluateOperator,
SineEvaluateOperator, SubtractEvaluateOperator, SumEvaluateOperator, ThresholdBlackEvaluateOperator,
ThresholdEvaluateOperator, ThresholdWhiteEvaluateOperator, UniformNoiseEvaluateOperator, XorEvaluateOperator
}
enum MagickFunction {
UndefinedFunction, PolynomialFunction, SinusoidFunction, ArcsinFunction,
ArctanFunction
}
enum StatisticType {
UndefinedStatistic, GradientStatistic, MaximumStatistic, MeanStatistic,
MedianStatistic, MinimumStatistic, ModeStatistic, NonpeakStatistic,
StandardDeviationStatistic
}
Functions
MagickExport ChannelStatistics * GetImageStatistics (const Image *, ExceptionInfo *)
MagickExport Image * EvaluateImages (const Image *, const MagickEvaluateOperator, ExceptionInfo *)
MagickExport Image * PolynomialImage (const Image *, const size_t, const double *, ExceptionInfo *)
MagickExport Image * StatisticImage (const Image *, const StatisticType, const size_t, const size_t, ExceptionInfo *)
MagickExport MagickBooleanType EvaluateImage (Image *, const MagickEvaluateOperator, const double, ExceptionInfo *)
MagickExport MagickBooleanType FunctionImage (Image *, const MagickFunction, const size_t, const double *, ExceptionInfo *)
MagickExport MagickBooleanType GetImageExtrema (const Image *, size_t *, size_t *, ExceptionInfo *)
MagickExport MagickBooleanType GetImageMean (const Image *, double *, double *, ExceptionInfo *)
MagickExport MagickBooleanType GetImageKurtosis (const Image *, double *, double *, ExceptionInfo *)
MagickExport MagickBooleanType GetImageRange (const Image *, double *, double *, ExceptionInfo *)
Typedef Documentation
typedef struct _ChannelStatistics ChannelStatistics
Enumeration Type Documentation
enum MagickEvaluateOperator
Enumerator
UndefinedEvaluateOperator
AbsEvaluateOperator
AddEvaluateOperator
AddModulusEvaluateOperator
AndEvaluateOperator
CosineEvaluateOperator
DivideEvaluateOperator
ExponentialEvaluateOperator
GaussianNoiseEvaluateOperator
ImpulseNoiseEvaluateOperator
LaplacianNoiseEvaluateOperator
LeftShiftEvaluateOperator
LogEvaluateOperator
MaxEvaluateOperator
MeanEvaluateOperator
MedianEvaluateOperator
MinEvaluateOperator
MultiplicativeNoiseEvaluateOperator
MultiplyEvaluateOperator
OrEvaluateOperator
PoissonNoiseEvaluateOperator
PowEvaluateOperator
RightShiftEvaluateOperator
SetEvaluateOperator
SineEvaluateOperator
SubtractEvaluateOperator
SumEvaluateOperator
ThresholdBlackEvaluateOperator
ThresholdEvaluateOperator
ThresholdWhiteEvaluateOperator
UniformNoiseEvaluateOperator
XorEvaluateOperator
Definition at line 45 of file statistic.h.
enum MagickFunction
Enumerator
UndefinedFunction
PolynomialFunction
SinusoidFunction
ArcsinFunction
ArctanFunction
Definition at line 81 of file statistic.h.
enum StatisticType
Enumerator
UndefinedStatistic
GradientStatistic
MaximumStatistic
MeanStatistic
MedianStatistic
MinimumStatistic
ModeStatistic
NonpeakStatistic
StandardDeviationStatistic
Definition at line 90 of file statistic.h.
Function Documentation
MagickExport MagickBooleanType EvaluateImage (Image * , const MagickEvaluateOperator , const double , ExceptionInfo *)
MagickExport Image* EvaluateImages (const Image * , const MagickEvaluateOperator , ExceptionInfo *)
MagickExport MagickBooleanType FunctionImage (Image * , const MagickFunction , const size_t , const double * , ExceptionInfo *)
MagickExport MagickBooleanType GetImageExtrema (const Image * , size_t * , size_t * , ExceptionInfo *)
MagickExport MagickBooleanType GetImageKurtosis (const Image * , double * , double * , ExceptionInfo *)
MagickExport MagickBooleanType GetImageMean (const Image * , double * , double * , ExceptionInfo *)
MagickExport MagickBooleanType GetImageRange (const Image * , double * , double * , ExceptionInfo *)
Definition at line 1369 of file statistic.c.
References AcquireVirtualCacheView(), _Image::columns, _Image::debug, DestroyCacheView(), _Image::filename, GetCacheViewVirtualPixels(), GetMagickModule, GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelReadMask(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, _Image::rows, _Image::signature, TraceEvent, UndefinedPixelTrait, and UpdatePixelTrait.
Referenced by FxChannelStatistics(), GetImageExtrema(), GetMagickProperty(), and MinMaxStretchImage().
MagickExport ChannelStatistics* GetImageStatistics (const Image * , ExceptionInfo *)
Definition at line 1508 of file statistic.c.
References AcquireQuantumMemory(), _ChannelStatistics::area, _Image::columns, CompositePixelChannel, _Image::debug, _ChannelStatistics::depth, EvaluateMax(), _Image::filename, GetImageChannels(), GetMagickModule, GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelReadMask(), GetQuantumRange(), GetVirtualPixels(), _ChannelStatistics::kurtosis, LogMagickEvent(), MAGICKCORE_QUANTUM_DEPTH, MagickFalse, MagickHuge, MagickMin(), MagickSignature, MagickTrue, _ChannelStatistics::maxima, MaxPixelChannels, _ChannelStatistics::mean, _ChannelStatistics::minima, PerceptibleReciprocal(), ResetMagickMemory(), ResourceLimitFatalError, _Image::rows, ScaleAnyToQuantum(), ScaleQuantumToAny(), _Image::signature, _ChannelStatistics::skewness, _ChannelStatistics::standard_deviation, _ChannelStatistics::sum, _ChannelStatistics::sum_cubed, _ChannelStatistics::sum_fourth_power, _ChannelStatistics::sum_squared, ThrowFatalException, TraceEvent, UndefinedPixelTrait, and _ChannelStatistics::variance.
Referenced by GetImageMean(), GetNormalizedCrossCorrelationDistortion(), and IdentifyImage().
MagickExport Image * PolynomialImage (const Image * , const size_t , const double * , ExceptionInfo *)
MagickExport Image * StatisticImage (const Image * , const StatisticType , const size_t , const size_t , ExceptionInfo *)
Definition at line 2372 of file statistic.c.
References AcquireAuthenticCacheView(), AcquirePixelListThreadSet(), AcquireVirtualCacheView(), ClampToQuantum(), CloneImage(), _Image::columns, CopyPixelTrait, _Image::debug, DestroyCacheView(), DestroyImage(), DestroyPixelListThreadSet(), DirectClass, _Image::filename, GetCacheViewVirtualPixels(), GetMagickModule, GetMaximumPixelList(), GetMeanPixelList(), GetMedianPixelList(), GetMinimumPixelList(), GetModePixelList(), GetNonpeakPixelList(), GetOpenMPThreadId(), GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelReadMask(), GetStandardDeviationPixelList(), GradientStatistic, InsertPixelList(), LogMagickEvent(), MagickAbsoluteValue(), MagickFalse, MagickMax(), MagickSignature, MagickTrue, MaximumStatistic, MeanStatistic, MedianStatistic, MinimumStatistic, ModeStatistic, NonpeakStatistic, _Image::progress_monitor, QueueCacheViewAuthenticPixels(), ResetPixelList(), ResourceLimitError, _Image::rows, SetImageProgress(), SetImageStorageClass(), SetPixelChannel(), _ExceptionInfo::signature, _Image::signature, StandardDeviationStatistic, StatisticImageTag, SyncCacheViewAuthenticPixels(), ThrowImageException, TraceEvent, and UndefinedPixelTrait.
Referenced by DeskewImage(), and PreviewImage().