MagickCore: static.h File Reference
static.h File Reference
Functions
MagickExport MagickBooleanType InvokeStaticImageFilter (const char *, Image **, const int, const char **, ExceptionInfo *)
ModuleExport size_t RegisterAAIImage (void)
ModuleExport size_t RegisterARTImage (void)
ModuleExport size_t RegisterAVIImage (void)
ModuleExport size_t RegisterAVSImage (void)
ModuleExport size_t RegisterBIEImage (void)
ModuleExport size_t RegisterBMPImage (void)
ModuleExport size_t RegisterBRAILLEImage (void)
ModuleExport size_t RegisterCALSImage (void)
ModuleExport size_t RegisterCAPTIONImage (void)
ModuleExport size_t RegisterCINImage (void)
ModuleExport size_t RegisterCIPImage (void)
ModuleExport size_t RegisterCLIPImage (void)
ModuleExport size_t RegisterCLIPBOARDImage (void)
ModuleExport size_t RegisterCMYKImage (void)
ModuleExport size_t RegisterCUTImage (void)
ModuleExport size_t RegisterDCMImage (void)
ModuleExport size_t RegisterDCXImage (void)
ModuleExport size_t RegisterDDSImage (void)
ModuleExport size_t RegisterDEBUGImage (void)
ModuleExport size_t RegisterDIBImage (void)
ModuleExport size_t RegisterDJVUImage (void)
ModuleExport size_t RegisterDNGImage (void)
ModuleExport size_t RegisterDPSImage (void)
ModuleExport size_t RegisterDPXImage (void)
ModuleExport size_t RegisterEMFImage (void)
ModuleExport size_t RegisterEPDFImage (void)
ModuleExport size_t RegisterEPIImage (void)
ModuleExport size_t RegisterEPSImage (void)
ModuleExport size_t RegisterEPS2Image (void)
ModuleExport size_t RegisterEPSFImage (void)
ModuleExport size_t RegisterEPSIImage (void)
ModuleExport size_t RegisterEPTImage (void)
ModuleExport size_t RegisterEXRImage (void)
ModuleExport size_t RegisterFAXImage (void)
ModuleExport size_t RegisterFDImage (void)
ModuleExport size_t RegisterFITSImage (void)
ModuleExport size_t RegisterFPXImage (void)
ModuleExport size_t RegisterG3Image (void)
ModuleExport size_t RegisterGIFImage (void)
ModuleExport size_t RegisterGIF87Image (void)
ModuleExport size_t RegisterGRADIENTImage (void)
ModuleExport size_t RegisterGRANITEImage (void)
ModuleExport size_t RegisterGRAYImage (void)
ModuleExport size_t RegisterHALDImage (void)
ModuleExport size_t RegisterHDRImage (void)
ModuleExport size_t RegisterHImage (void)
ModuleExport size_t RegisterHISTOGRAMImage (void)
ModuleExport size_t RegisterHRZImage (void)
ModuleExport size_t RegisterHTMLImage (void)
ModuleExport size_t RegisterICBImage (void)
ModuleExport size_t RegisterICONImage (void)
ModuleExport size_t RegisterINFOImage (void)
ModuleExport size_t RegisterINLINEImage (void)
ModuleExport size_t RegisterIPLImage (void)
ModuleExport size_t RegisterJBGImage (void)
ModuleExport size_t RegisterJBIGImage (void)
ModuleExport size_t RegisterJPGImage (void)
ModuleExport size_t RegisterJPEGImage (void)
ModuleExport size_t RegisterJP2Image (void)
ModuleExport size_t RegisterLABELImage (void)
ModuleExport size_t RegisterMACImage (void)
ModuleExport size_t RegisterMAGICKImage (void)
ModuleExport size_t RegisterMAPImage (void)
ModuleExport size_t RegisterMATImage (void)
ModuleExport size_t RegisterMATTEImage (void)
ModuleExport size_t RegisterMETAImage (void)
ModuleExport size_t RegisterMIFFImage (void)
ModuleExport size_t RegisterMNGImage (void)
ModuleExport size_t RegisterMONOImage (void)
ModuleExport size_t RegisterMPCImage (void)
ModuleExport size_t RegisterMPEGImage (void)
ModuleExport size_t RegisterMPRImage (void)
ModuleExport size_t RegisterMSLImage (void)
ModuleExport size_t RegisterMTVImage (void)
ModuleExport size_t RegisterMVGImage (void)
ModuleExport size_t RegisterNETSCAPEImage (void)
ModuleExport size_t RegisterNULLImage (void)
ModuleExport size_t RegisterP7Image (void)
ModuleExport size_t RegisterPBMImage (void)
ModuleExport size_t RegisterOTBImage (void)
ModuleExport size_t RegisterPALMImage (void)
ModuleExport size_t RegisterPANGOImage (void)
ModuleExport size_t RegisterPATTERNImage (void)
ModuleExport size_t RegisterPCDImage (void)
ModuleExport size_t RegisterPCDSImage (void)
ModuleExport size_t RegisterPCLImage (void)
ModuleExport size_t RegisterPCTImage (void)
ModuleExport size_t RegisterPCXImage (void)
ModuleExport size_t RegisterPDBImage (void)
ModuleExport size_t RegisterPDFImage (void)
ModuleExport size_t RegisterPESImage (void)
ModuleExport size_t RegisterPICImage (void)
ModuleExport size_t RegisterPICTImage (void)
ModuleExport size_t RegisterPIXImage (void)
ModuleExport size_t RegisterPGMImage (void)
ModuleExport size_t RegisterPLASMAImage (void)
ModuleExport size_t RegisterPMImage (void)
ModuleExport size_t RegisterPNGImage (void)
ModuleExport size_t RegisterPNMImage (void)
ModuleExport size_t RegisterPPMImage (void)
ModuleExport size_t RegisterPREVIEWImage (void)
ModuleExport size_t RegisterPSImage (void)
ModuleExport size_t RegisterPS2Image (void)
ModuleExport size_t RegisterPS3Image (void)
ModuleExport size_t RegisterPSDImage (void)
ModuleExport size_t RegisterPTIFImage (void)
ModuleExport size_t RegisterPWPImage (void)
ModuleExport size_t RegisterRASImage (void)
ModuleExport size_t RegisterRAWImage (void)
ModuleExport size_t RegisterRGBImage (void)
ModuleExport size_t RegisterRGBAImage (void)
ModuleExport size_t RegisterRLAImage (void)
ModuleExport size_t RegisterRLEImage (void)
ModuleExport size_t RegisterSCRImage (void)
ModuleExport size_t RegisterSCTImage (void)
ModuleExport size_t RegisterSFWImage (void)
ModuleExport size_t RegisterSGIImage (void)
ModuleExport size_t RegisterSHTMLImage (void)
ModuleExport size_t RegisterSTEGANOImage (void)
ModuleExport size_t RegisterSUNImage (void)
ModuleExport size_t RegisterSVGImage (void)
ModuleExport size_t RegisterTEXTImage (void)
ModuleExport size_t RegisterTGAImage (void)
ModuleExport size_t RegisterTHUMBNAILImage (void)
ModuleExport size_t RegisterTIFImage (void)
ModuleExport size_t RegisterTIFFImage (void)
ModuleExport size_t RegisterTILEImage (void)
ModuleExport size_t RegisterTIMImage (void)
ModuleExport size_t RegisterTTFImage (void)
ModuleExport size_t RegisterTXTImage (void)
ModuleExport size_t RegisterUILImage (void)
ModuleExport size_t RegisterURLImage (void)
ModuleExport size_t RegisterUYVYImage (void)
ModuleExport size_t RegisterVDAImage (void)
ModuleExport size_t RegisterVICARImage (void)
ModuleExport size_t RegisterVIDImage (void)
ModuleExport size_t RegisterVIFFImage (void)
ModuleExport size_t RegisterVSTImage (void)
ModuleExport size_t RegisterWBMPImage (void)
ModuleExport size_t RegisterWEBPImage (void)
ModuleExport size_t RegisterWMFImage (void)
ModuleExport size_t RegisterWPGImage (void)
ModuleExport size_t RegisterXImage (void)
ModuleExport size_t RegisterXBMImage (void)
ModuleExport size_t RegisterXCImage (void)
ModuleExport size_t RegisterXCFImage (void)
ModuleExport size_t RegisterXPMImage (void)
ModuleExport size_t RegisterXPSImage (void)
ModuleExport size_t RegisterXTRNImage (void)
ModuleExport size_t RegisterXVImage (void)
ModuleExport size_t RegisterXWDImage (void)
ModuleExport size_t RegisterYCBCRImage (void)
ModuleExport size_t RegisterYUVImage (void)
ModuleExport void UnregisterAAIImage (void)
ModuleExport void UnregisterARTImage (void)
ModuleExport void UnregisterAVIImage (void)
ModuleExport void UnregisterAVSImage (void)
ModuleExport void UnregisterBIEImage (void)
ModuleExport void UnregisterBMPImage (void)
ModuleExport void UnregisterBRAILLEImage (void)
ModuleExport void UnregisterCALSImage (void)
ModuleExport void UnregisterCAPTIONImage (void)
ModuleExport void UnregisterCINImage (void)
ModuleExport void UnregisterCIPImage (void)
ModuleExport void UnregisterCLIPImage (void)
ModuleExport void UnregisterCLIPBOARDImage (void)
ModuleExport void UnregisterCMYKImage (void)
ModuleExport void UnregisterCUTImage (void)
ModuleExport void UnregisterDCMImage (void)
ModuleExport void UnregisterDCXImage (void)
ModuleExport void UnregisterDDSImage (void)
ModuleExport void UnregisterDEBUGImage (void)
ModuleExport void UnregisterDIBImage (void)
ModuleExport void UnregisterDJVUImage (void)
ModuleExport void UnregisterDNGImage (void)
ModuleExport void UnregisterDPSImage (void)
ModuleExport void UnregisterDPXImage (void)
ModuleExport void UnregisterEMFImage (void)
ModuleExport void UnregisterEPDFImage (void)
ModuleExport void UnregisterEPIImage (void)
ModuleExport void UnregisterEPSImage (void)
ModuleExport void UnregisterEPS2Image (void)
ModuleExport void UnregisterEPSFImage (void)
ModuleExport void UnregisterEPSIImage (void)
ModuleExport void UnregisterEPTImage (void)
ModuleExport void UnregisterEXRImage (void)
ModuleExport void UnregisterFAXImage (void)
ModuleExport void UnregisterFDImage (void)
ModuleExport void UnregisterFITSImage (void)
ModuleExport void UnregisterFPXImage (void)
ModuleExport void UnregisterG3Image (void)
ModuleExport void UnregisterGIFImage (void)
ModuleExport void UnregisterGIF87Image (void)
ModuleExport void UnregisterGRADIENTImage (void)
ModuleExport void UnregisterGRANITEImage (void)
ModuleExport void UnregisterGRAYImage (void)
ModuleExport void UnregisterHALDImage (void)
ModuleExport void UnregisterHDRImage (void)
ModuleExport void UnregisterHImage (void)
ModuleExport void UnregisterHISTOGRAMImage (void)
ModuleExport void UnregisterHRZImage (void)
ModuleExport void UnregisterHTMLImage (void)
ModuleExport void UnregisterICBImage (void)
ModuleExport void UnregisterICONImage (void)
ModuleExport void UnregisterINFOImage (void)
ModuleExport void UnregisterINLINEImage (void)
ModuleExport void UnregisterIPLImage (void)
ModuleExport void UnregisterJBGImage (void)
ModuleExport void UnregisterJBIGImage (void)
ModuleExport void UnregisterJPGImage (void)
ModuleExport void UnregisterJPEGImage (void)
ModuleExport void UnregisterJP2Image (void)
ModuleExport void UnregisterLABELImage (void)
ModuleExport void UnregisterLOCALEImage (void)
ModuleExport void UnregisterMACImage (void)
ModuleExport void UnregisterMAGICKImage (void)
ModuleExport void UnregisterMAPImage (void)
ModuleExport void UnregisterMATImage (void)
ModuleExport void UnregisterMATTEImage (void)
ModuleExport void UnregisterMETAImage (void)
ModuleExport void UnregisterMIFFImage (void)
ModuleExport void UnregisterMNGImage (void)
ModuleExport void UnregisterMONOImage (void)
ModuleExport void UnregisterMPCImage (void)
ModuleExport void UnregisterMPEGImage (void)
ModuleExport void UnregisterMPRImage (void)
ModuleExport void UnregisterMSLImage (void)
ModuleExport void UnregisterMTVImage (void)
ModuleExport void UnregisterMVGImage (void)
ModuleExport void UnregisterNETSCAPEImage (void)
ModuleExport void UnregisterNULLImage (void)
ModuleExport void UnregisterP7Image (void)
ModuleExport void UnregisterPBMImage (void)
ModuleExport void UnregisterOTBImage (void)
ModuleExport void UnregisterPALMImage (void)
ModuleExport void UnregisterPANGOImage (void)
ModuleExport void UnregisterPATTERNImage (void)
ModuleExport void UnregisterPCDImage (void)
ModuleExport void UnregisterPCDSImage (void)
ModuleExport void UnregisterPCLImage (void)
ModuleExport void UnregisterPCTImage (void)
ModuleExport void UnregisterPCXImage (void)
ModuleExport void UnregisterPDBImage (void)
ModuleExport void UnregisterPDFImage (void)
ModuleExport void UnregisterPESImage (void)
ModuleExport void UnregisterPICImage (void)
ModuleExport void UnregisterPICTImage (void)
ModuleExport void UnregisterPIXImage (void)
ModuleExport void UnregisterPLASMAImage (void)
ModuleExport void UnregisterPGMImage (void)
ModuleExport void UnregisterPMImage (void)
ModuleExport void UnregisterPNGImage (void)
ModuleExport void UnregisterPNMImage (void)
ModuleExport void UnregisterPPMImage (void)
ModuleExport void UnregisterPREVIEWImage (void)
ModuleExport void UnregisterPSImage (void)
ModuleExport void UnregisterPS2Image (void)
ModuleExport void UnregisterPS3Image (void)
ModuleExport void UnregisterPSDImage (void)
ModuleExport void UnregisterPTIFImage (void)
ModuleExport void UnregisterPWPImage (void)
ModuleExport void UnregisterRASImage (void)
ModuleExport void UnregisterRAWImage (void)
ModuleExport void UnregisterRGBImage (void)
ModuleExport void UnregisterRGBAImage (void)
ModuleExport void UnregisterRLAImage (void)
ModuleExport void UnregisterRLEImage (void)
ModuleExport void UnregisterSCRImage (void)
ModuleExport void UnregisterSCTImage (void)
ModuleExport void UnregisterSFWImage (void)
ModuleExport void UnregisterSGIImage (void)
ModuleExport void UnregisterSHTMLImage (void)
ModuleExport void UnregisterSTEGANOImage (void)
ModuleExport void UnregisterSUNImage (void)
ModuleExport void UnregisterSVGImage (void)
ModuleExport void UnregisterTEXTImage (void)
ModuleExport void UnregisterTGAImage (void)
ModuleExport void UnregisterTHUMBNAILImage (void)
ModuleExport void UnregisterTIFImage (void)
ModuleExport void UnregisterTIFFImage (void)
ModuleExport void UnregisterTILEImage (void)
ModuleExport void UnregisterTIMImage (void)
ModuleExport void UnregisterTTFImage (void)
ModuleExport void UnregisterTXTImage (void)
ModuleExport void UnregisterUILImage (void)
ModuleExport void UnregisterURLImage (void)
ModuleExport void UnregisterUYVYImage (void)
ModuleExport void UnregisterVDAImage (void)
ModuleExport void UnregisterVICARImage (void)
ModuleExport void UnregisterVIDImage (void)
ModuleExport void UnregisterVIFFImage (void)
ModuleExport void UnregisterVSTImage (void)
ModuleExport void UnregisterWBMPImage (void)
ModuleExport void UnregisterWEBPImage (void)
ModuleExport void UnregisterWMFImage (void)
ModuleExport void UnregisterWPGImage (void)
ModuleExport void UnregisterXImage (void)
ModuleExport void UnregisterXBMImage (void)
ModuleExport void UnregisterXCImage (void)
ModuleExport void UnregisterXCFImage (void)
ModuleExport void UnregisterXPMImage (void)
ModuleExport void UnregisterXPSImage (void)
ModuleExport void UnregisterXTRNImage (void)
ModuleExport void UnregisterXVImage (void)
ModuleExport void UnregisterXWDImage (void)
ModuleExport void UnregisterYCBCRImage (void)
ModuleExport void UnregisterYUVImage (void)
Function Documentation
MagickExport MagickBooleanType InvokeStaticImageFilter (const char * , Image ** , const int , const char ** , ExceptionInfo *)
ModuleExport size_t RegisterAAIImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterARTImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterAVIImage (void)
ModuleExport size_t RegisterAVSImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterBIEImage (void)
ModuleExport size_t RegisterBMPImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterBRAILLEImage (void)
ModuleExport size_t RegisterCALSImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterCAPTIONImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterCINImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterCIPImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterCLIPBOARDImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterCLIPImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterCMYKImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterCUTImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterDCMImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterDCXImage (void)
ModuleExport size_t RegisterDDSImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterDEBUGImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterDIBImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterDJVUImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterDNGImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterDPSImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterDPXImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterEMFImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterEPDFImage (void)
ModuleExport size_t RegisterEPIImage (void)
ModuleExport size_t RegisterEPS2Image (void)
ModuleExport size_t RegisterEPSFImage (void)
ModuleExport size_t RegisterEPSIImage (void)
ModuleExport size_t RegisterEPSImage (void)
ModuleExport size_t RegisterEPTImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterEXRImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterFAXImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterFDImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterFITSImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterFPXImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterG3Image (void)
ModuleExport size_t RegisterGIF87Image (void)
ModuleExport size_t RegisterGIFImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterGRADIENTImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterGRANITEImage (void)
ModuleExport size_t RegisterGRAYImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterHALDImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterHDRImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterHImage (void)
ModuleExport size_t RegisterHISTOGRAMImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterHRZImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterHTMLImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterICBImage (void)
ModuleExport size_t RegisterICONImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterINFOImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterINLINEImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterIPLImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterJBGImage (void)
ModuleExport size_t RegisterJBIGImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterJP2Image (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterJPEGImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterJPGImage (void)
ModuleExport size_t RegisterLABELImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterMACImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterMAGICKImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterMAPImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterMATImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterMATTEImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterMETAImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterMIFFImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterMNGImage (void)
ModuleExport size_t RegisterMONOImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterMPCImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterMPEGImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterMPRImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterMSLImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterMTVImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterMVGImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterNETSCAPEImage (void)
ModuleExport size_t RegisterNULLImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterOTBImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterP7Image (void)
ModuleExport size_t RegisterPALMImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterPANGOImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterPATTERNImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterPBMImage (void)
ModuleExport size_t RegisterPCDImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterPCDSImage (void)
ModuleExport size_t RegisterPCLImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterPCTImage (void)
ModuleExport size_t RegisterPCXImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterPDBImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterPDFImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterPESImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterPGMImage (void)
ModuleExport size_t RegisterPICImage (void)
ModuleExport size_t RegisterPICTImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterPIXImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterPLASMAImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterPMImage (void)
ModuleExport size_t RegisterPNGImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterPNMImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterPPMImage (void)
ModuleExport size_t RegisterPREVIEWImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterPS2Image (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterPS3Image (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterPSDImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterPSImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterPTIFImage (void)
ModuleExport size_t RegisterPWPImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterRASImage (void)
ModuleExport size_t RegisterRAWImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterRGBAImage (void)
ModuleExport size_t RegisterRGBImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterRLAImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterRLEImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterSCRImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterSCTImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterSFWImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterSGIImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterSHTMLImage (void)
ModuleExport size_t RegisterSTEGANOImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterSUNImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterSVGImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterTEXTImage (void)
ModuleExport size_t RegisterTGAImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterTHUMBNAILImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterTIFFImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterTIFImage (void)
ModuleExport size_t RegisterTILEImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterTIMImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterTTFImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterTXTImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterUILImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterURLImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterUYVYImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterVDAImage (void)
ModuleExport size_t RegisterVICARImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterVIDImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterVIFFImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterVSTImage (void)
ModuleExport size_t RegisterWBMPImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterWEBPImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterWMFImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterWPGImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterXBMImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterXCFImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterXCImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterXImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterXPMImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterXPSImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterXTRNImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterXVImage (void)
ModuleExport size_t RegisterXWDImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterYCBCRImage (void)
Referenced by RegisterStaticModules().
ModuleExport size_t RegisterYUVImage (void)
Referenced by RegisterStaticModules().
ModuleExport void UnregisterAAIImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterARTImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterAVIImage (void)
ModuleExport void UnregisterAVSImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterBIEImage (void)
ModuleExport void UnregisterBMPImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterBRAILLEImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterCALSImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterCAPTIONImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterCINImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterCIPImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterCLIPBOARDImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterCLIPImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterCMYKImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterCUTImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterDCMImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterDCXImage (void)
ModuleExport void UnregisterDDSImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterDEBUGImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterDIBImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterDJVUImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterDNGImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterDPSImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterDPXImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterEMFImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterEPDFImage (void)
ModuleExport void UnregisterEPIImage (void)
ModuleExport void UnregisterEPS2Image (void)
ModuleExport void UnregisterEPSFImage (void)
ModuleExport void UnregisterEPSIImage (void)
ModuleExport void UnregisterEPSImage (void)
ModuleExport void UnregisterEPTImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterEXRImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterFAXImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterFDImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterFITSImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterFPXImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterG3Image (void)
ModuleExport void UnregisterGIF87Image (void)
ModuleExport void UnregisterGIFImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterGRADIENTImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterGRANITEImage (void)
ModuleExport void UnregisterGRAYImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterHALDImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterHDRImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterHImage (void)
ModuleExport void UnregisterHISTOGRAMImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterHRZImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterHTMLImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterICBImage (void)
ModuleExport void UnregisterICONImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterINFOImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterINLINEImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterIPLImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterJBGImage (void)
ModuleExport void UnregisterJBIGImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterJP2Image (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterJPEGImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterJPGImage (void)
ModuleExport void UnregisterLABELImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterLOCALEImage (void)
ModuleExport void UnregisterMACImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterMAGICKImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterMAPImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterMATImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterMATTEImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterMETAImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterMIFFImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterMNGImage (void)
ModuleExport void UnregisterMONOImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterMPCImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterMPEGImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterMPRImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterMSLImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterMTVImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterMVGImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterNETSCAPEImage (void)
ModuleExport void UnregisterNULLImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterOTBImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterP7Image (void)
ModuleExport void UnregisterPALMImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterPANGOImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterPATTERNImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterPBMImage (void)
ModuleExport void UnregisterPCDImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterPCDSImage (void)
ModuleExport void UnregisterPCLImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterPCTImage (void)
ModuleExport void UnregisterPCXImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterPDBImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterPDFImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterPESImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterPGMImage (void)
ModuleExport void UnregisterPICImage (void)
ModuleExport void UnregisterPICTImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterPIXImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterPLASMAImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterPMImage (void)
ModuleExport void UnregisterPNGImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterPNMImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterPPMImage (void)
ModuleExport void UnregisterPREVIEWImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterPS2Image (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterPS3Image (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterPSDImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterPSImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterPTIFImage (void)
ModuleExport void UnregisterPWPImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterRASImage (void)
ModuleExport void UnregisterRAWImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterRGBAImage (void)
ModuleExport void UnregisterRGBImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterRLAImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterRLEImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterSCRImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterSCTImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterSFWImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterSGIImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterSHTMLImage (void)
ModuleExport void UnregisterSTEGANOImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterSUNImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterSVGImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterTEXTImage (void)
ModuleExport void UnregisterTGAImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterTHUMBNAILImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterTIFFImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterTIFImage (void)
ModuleExport void UnregisterTILEImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterTIMImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterTTFImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterTXTImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterUILImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterURLImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterUYVYImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterVDAImage (void)
ModuleExport void UnregisterVICARImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterVIDImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterVIFFImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterVSTImage (void)
ModuleExport void UnregisterWBMPImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterWEBPImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterWMFImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterWPGImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterXBMImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterXCFImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterXCImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterXImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterXPMImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterXPSImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterXTRNImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterXVImage (void)
ModuleExport void UnregisterXWDImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterYCBCRImage (void)
Referenced by UnregisterStaticModules().
ModuleExport void UnregisterYUVImage (void)
Referenced by UnregisterStaticModules().