MagickCore: static.c File Reference
static.c File Reference
#include "MagickCore/studio.h"
#include "MagickCore/exception-private.h"
#include "MagickCore/image.h"
#include "MagickCore/module.h"
#include "MagickCore/policy.h"
#include "MagickCore/static.h"
#include "MagickCore/string_.h"
Functions
MagickExport void RegisterStaticModules (void)
MagickExport void UnregisterStaticModules (void)
Function Documentation
MagickExport void RegisterStaticModules (void)
Definition at line 168 of file static.c.
References RegisterAAIImage(), RegisterARTImage(), RegisterAVSImage(), RegisterBMPImage(), RegisterCALSImage(), RegisterCAPTIONImage(), RegisterCINImage(), RegisterCIPImage(), RegisterCLIPBOARDImage(), RegisterCLIPImage(), RegisterCMYKImage(), RegisterCUTImage(), RegisterDCMImage(), RegisterDDSImage(), RegisterDEBUGImage(), RegisterDIBImage(), RegisterDJVUImage(), RegisterDNGImage(), RegisterDPSImage(), RegisterDPXImage(), RegisterEMFImage(), RegisterEPTImage(), RegisterEXRImage(), RegisterFAXImage(), RegisterFDImage(), RegisterFITSImage(), RegisterFPXImage(), RegisterGIFImage(), RegisterGRADIENTImage(), RegisterGRAYImage(), RegisterHALDImage(), RegisterHDRImage(), RegisterHISTOGRAMImage(), RegisterHRZImage(), RegisterHTMLImage(), RegisterICONImage(), RegisterINFOImage(), RegisterINLINEImage(), RegisterIPLImage(), RegisterJBIGImage(), RegisterJP2Image(), RegisterJPEGImage(), RegisterLABELImage(), RegisterMACImage(), RegisterMAGICKImage(), RegisterMAPImage(), RegisterMATImage(), RegisterMATTEImage(), RegisterMETAImage(), RegisterMIFFImage(), RegisterMONOImage(), RegisterMPCImage(), RegisterMPEGImage(), RegisterMPRImage(), RegisterMSLImage(), RegisterMTVImage(), RegisterMVGImage(), RegisterNULLImage(), RegisterOTBImage(), RegisterPALMImage(), RegisterPANGOImage(), RegisterPATTERNImage(), RegisterPCDImage(), RegisterPCLImage(), RegisterPCXImage(), RegisterPDBImage(), RegisterPDFImage(), RegisterPESImage(), RegisterPICTImage(), RegisterPIXImage(), RegisterPLASMAImage(), RegisterPNGImage(), RegisterPNMImage(), RegisterPREVIEWImage(), RegisterPS2Image(), RegisterPS3Image(), RegisterPSDImage(), RegisterPSImage(), RegisterPWPImage(), RegisterRAWImage(), RegisterRGBImage(), RegisterRLAImage(), RegisterRLEImage(), RegisterSCRImage(), RegisterSCTImage(), RegisterSFWImage(), RegisterSGIImage(), RegisterSTEGANOImage(), RegisterSUNImage(), RegisterSVGImage(), RegisterTGAImage(), RegisterTHUMBNAILImage(), RegisterTIFFImage(), RegisterTILEImage(), RegisterTIMImage(), RegisterTTFImage(), RegisterTXTImage(), RegisterUILImage(), RegisterURLImage(), RegisterUYVYImage(), RegisterVICARImage(), RegisterVIDImage(), RegisterVIFFImage(), RegisterWBMPImage(), RegisterWEBPImage(), RegisterWMFImage(), RegisterWPGImage(), RegisterXBMImage(), RegisterXCFImage(), RegisterXCImage(), RegisterXImage(), RegisterXPMImage(), RegisterXPSImage(), RegisterXTRNImage(), RegisterXWDImage(), RegisterYCBCRImage(), and RegisterYUVImage().
MagickExport void UnregisterStaticModules (void)
Definition at line 344 of file static.c.
References UnregisterAAIImage(), UnregisterARTImage(), UnregisterAVSImage(), UnregisterBMPImage(), UnregisterBRAILLEImage(), UnregisterCALSImage(), UnregisterCAPTIONImage(), UnregisterCINImage(), UnregisterCIPImage(), UnregisterCLIPBOARDImage(), UnregisterCLIPImage(), UnregisterCMYKImage(), UnregisterCUTImage(), UnregisterDCMImage(), UnregisterDDSImage(), UnregisterDEBUGImage(), UnregisterDIBImage(), UnregisterDJVUImage(), UnregisterDNGImage(), UnregisterDPSImage(), UnregisterDPXImage(), UnregisterEMFImage(), UnregisterEPTImage(), UnregisterEXRImage(), UnregisterFAXImage(), UnregisterFDImage(), UnregisterFITSImage(), UnregisterFPXImage(), UnregisterGIFImage(), UnregisterGRADIENTImage(), UnregisterGRAYImage(), UnregisterHALDImage(), UnregisterHDRImage(), UnregisterHISTOGRAMImage(), UnregisterHRZImage(), UnregisterHTMLImage(), UnregisterICONImage(), UnregisterINFOImage(), UnregisterINLINEImage(), UnregisterIPLImage(), UnregisterJBIGImage(), UnregisterJP2Image(), UnregisterJPEGImage(), UnregisterLABELImage(), UnregisterMACImage(), UnregisterMAGICKImage(), UnregisterMAPImage(), UnregisterMATImage(), UnregisterMATTEImage(), UnregisterMETAImage(), UnregisterMIFFImage(), UnregisterMONOImage(), UnregisterMPCImage(), UnregisterMPEGImage(), UnregisterMPRImage(), UnregisterMSLImage(), UnregisterMTVImage(), UnregisterMVGImage(), UnregisterNULLImage(), UnregisterOTBImage(), UnregisterPALMImage(), UnregisterPANGOImage(), UnregisterPATTERNImage(), UnregisterPCDImage(), UnregisterPCLImage(), UnregisterPCXImage(), UnregisterPDBImage(), UnregisterPDFImage(), UnregisterPESImage(), UnregisterPICTImage(), UnregisterPIXImage(), UnregisterPLASMAImage(), UnregisterPNGImage(), UnregisterPNMImage(), UnregisterPREVIEWImage(), UnregisterPS2Image(), UnregisterPS3Image(), UnregisterPSDImage(), UnregisterPSImage(), UnregisterPWPImage(), UnregisterRAWImage(), UnregisterRGBImage(), UnregisterRLAImage(), UnregisterRLEImage(), UnregisterSCRImage(), UnregisterSCTImage(), UnregisterSFWImage(), UnregisterSGIImage(), UnregisterSTEGANOImage(), UnregisterSUNImage(), UnregisterSVGImage(), UnregisterTGAImage(), UnregisterTHUMBNAILImage(), UnregisterTIFFImage(), UnregisterTILEImage(), UnregisterTIMImage(), UnregisterTTFImage(), UnregisterTXTImage(), UnregisterUILImage(), UnregisterURLImage(), UnregisterUYVYImage(), UnregisterVICARImage(), UnregisterVIDImage(), UnregisterVIFFImage(), UnregisterWBMPImage(), UnregisterWEBPImage(), UnregisterWMFImage(), UnregisterWPGImage(), UnregisterXBMImage(), UnregisterXCFImage(), UnregisterXCImage(), UnregisterXImage(), UnregisterXPMImage(), UnregisterXPSImage(), UnregisterXTRNImage(), UnregisterXWDImage(), UnregisterYCBCRImage(), and UnregisterYUVImage().
Referenced by MagickCoreTerminus().