MagickCore: statistic.c File Reference
statistic.c File Reference
#include "MagickCore/studio.h"
#include "MagickCore/property.h"
#include "MagickCore/animate.h"
#include "MagickCore/blob.h"
#include "MagickCore/blob-private.h"
#include "MagickCore/cache.h"
#include "MagickCore/cache-private.h"
#include "MagickCore/cache-view.h"
#include "MagickCore/client.h"
#include "MagickCore/color.h"
#include "MagickCore/color-private.h"
#include "MagickCore/colorspace.h"
#include "MagickCore/colorspace-private.h"
#include "MagickCore/composite.h"
#include "MagickCore/composite-private.h"
#include "MagickCore/compress.h"
#include "MagickCore/constitute.h"
#include "MagickCore/display.h"
#include "MagickCore/draw.h"
#include "MagickCore/enhance.h"
#include "MagickCore/exception.h"
#include "MagickCore/exception-private.h"
#include "MagickCore/gem.h"
#include "MagickCore/gem-private.h"
#include "MagickCore/geometry.h"
#include "MagickCore/list.h"
#include "MagickCore/image-private.h"
#include "MagickCore/magic.h"
#include "MagickCore/magick.h"
#include "MagickCore/memory_.h"
#include "MagickCore/module.h"
#include "MagickCore/monitor.h"
#include "MagickCore/monitor-private.h"
#include "MagickCore/option.h"
#include "MagickCore/paint.h"
#include "MagickCore/pixel-accessor.h"
#include "MagickCore/profile.h"
#include "MagickCore/quantize.h"
#include "MagickCore/quantum-private.h"
#include "MagickCore/random_.h"
#include "MagickCore/random-private.h"
#include "MagickCore/resource_.h"
#include "MagickCore/segment.h"
#include "MagickCore/semaphore.h"
#include "MagickCore/signature-private.h"
#include "MagickCore/statistic.h"
#include "MagickCore/string_.h"
#include "MagickCore/thread-private.h"
#include "MagickCore/timer.h"
#include "MagickCore/utility.h"
#include "MagickCore/version.h"
Data Structures
struct _PixelChannels
struct _SkipNode
struct _SkipList
struct _PixelList
Macros
#define EvaluateImageTag "Evaluate/Image"
#define FunctionImageTag "Function/Image "
#define PolynomialImageTag "Polynomial/Image"
#define StatisticImageTag "Statistic/Image"
Typedefs
typedef struct _PixelChannels PixelChannels
typedef struct _SkipNode SkipNode
typedef struct _SkipList SkipList
typedef struct _PixelList PixelList
Functions
static PixelChannels ** DestroyPixelThreadSet (PixelChannels **pixels)
static PixelChannels ** AcquirePixelThreadSet (const Image *image, const size_t number_images)
static double EvaluateMax (const double x, const double y)
static int IntensityCompare (const void *x, const void *y)
static double MagickMin (const double x, const double y)
static double ApplyEvaluateOperator (RandomInfo *random_info, const Quantum pixel, const MagickEvaluateOperator op, const double value)
MagickExport Image * EvaluateImages (const Image *images, const MagickEvaluateOperator op, ExceptionInfo *exception)
MagickExport MagickBooleanType EvaluateImage (Image *image, const MagickEvaluateOperator op, const double value, ExceptionInfo *exception)
static Quantum ApplyFunction (Quantum pixel, const MagickFunction function, const size_t number_parameters, const double *parameters, ExceptionInfo *exception)
MagickExport MagickBooleanType FunctionImage (Image *image, const MagickFunction function, const size_t number_parameters, const double *parameters, ExceptionInfo *exception)
MagickExport MagickBooleanType GetImageExtrema (const Image *image, size_t *minima, size_t *maxima, ExceptionInfo *exception)
MagickExport MagickBooleanType GetImageMean (const Image *image, double *mean, double *standard_deviation, ExceptionInfo *exception)
MagickExport MagickBooleanType GetImageKurtosis (const Image *image, double *kurtosis, double *skewness, ExceptionInfo *exception)
MagickExport MagickBooleanType GetImageRange (const Image *image, double *minima, double *maxima, ExceptionInfo *exception)
static size_t GetImageChannels (const Image *image)
MagickExport ChannelStatistics * GetImageStatistics (const Image *image, ExceptionInfo *exception)
MagickExport Image * PolynomialImage (const Image *images, const size_t number_terms, const double *terms, ExceptionInfo *exception)
static PixelList * DestroyPixelList (PixelList *pixel_list)
static PixelList ** DestroyPixelListThreadSet (PixelList **pixel_list)
static PixelList * AcquirePixelList (const size_t width, const size_t height)
static PixelList ** AcquirePixelListThreadSet (const size_t width, const size_t height)
static void AddNodePixelList (PixelList *pixel_list, const size_t color)
static void GetMaximumPixelList (PixelList *pixel_list, Quantum *pixel)
static void GetMeanPixelList (PixelList *pixel_list, Quantum *pixel)
static void GetMedianPixelList (PixelList *pixel_list, Quantum *pixel)
static void GetMinimumPixelList (PixelList *pixel_list, Quantum *pixel)
static void GetModePixelList (PixelList *pixel_list, Quantum *pixel)
static void GetNonpeakPixelList (PixelList *pixel_list, Quantum *pixel)
static void GetStandardDeviationPixelList (PixelList *pixel_list, Quantum *pixel)
static void InsertPixelList (const Quantum pixel, PixelList *pixel_list)
static double MagickAbsoluteValue (const double x)
static size_t MagickMax (const size_t x, const size_t y)
static void ResetPixelList (PixelList *pixel_list)
MagickExport Image * StatisticImage (const Image *image, const StatisticType type, const size_t width, const size_t height, ExceptionInfo *exception)
Macro Definition Documentation
#define EvaluateImageTag "Evaluate/Image"
#define FunctionImageTag "Function/Image "
Referenced by FunctionImage().
#define PolynomialImageTag "Polynomial/Image"
Referenced by PolynomialImage().
#define StatisticImageTag "Statistic/Image"
Referenced by StatisticImage().
Typedef Documentation
typedef struct _PixelChannels PixelChannels
typedef struct _PixelList PixelList
typedef struct _SkipList SkipList
typedef struct _SkipNode SkipNode
Function Documentation
static PixelList* AcquirePixelList (const size_t width, const size_t height) static
Definition at line 1989 of file statistic.c.
References AcquireMagickMemory(), AcquireQuantumMemory(), DestroyPixelList(), _PixelList::length, MagickSignature, _SkipList::nodes, ResetMagickMemory(), _PixelList::signature, and _PixelList::skip_list.
Referenced by AcquirePixelListThreadSet().
static PixelList** AcquirePixelListThreadSet (const size_t width, const size_t height) static
Definition at line 2009 of file statistic.c.
References AcquirePixelList(), AcquireQuantumMemory(), DestroyPixelListThreadSet(), GetMagickResourceLimit(), ResetMagickMemory(), and ThreadResource.
Referenced by StatisticImage().
static PixelChannels** AcquirePixelThreadSet (const Image * image, const size_t number_images) static
Definition at line 151 of file statistic.c.
References AcquireQuantumMemory(), _Image::columns, DestroyPixelThreadSet(), GetMagickResourceLimit(), MaxPixelChannels, ResetMagickMemory(), and ThreadResource.
Referenced by EvaluateImages(), and PolynomialImage().
static void AddNodePixelList (PixelList * pixel_list, const size_t color) static
Definition at line 2036 of file statistic.c.
References _SkipNode::count, _SkipList::level, _SkipNode::next, _SkipList::nodes, _PixelList::seed, _SkipNode::signature, _PixelList::signature, and _PixelList::skip_list.
Referenced by InsertPixelList().
static double ApplyEvaluateOperator (RandomInfo * random_info, const Quantum pixel, const MagickEvaluateOperator op, const double value) static
Definition at line 235 of file statistic.c.
References AbsEvaluateOperator, AddEvaluateOperator, AddModulusEvaluateOperator, AndEvaluateOperator, CosineEvaluateOperator, DivideEvaluateOperator, EvaluateMax(), ExponentialEvaluateOperator, GaussianNoise, GaussianNoiseEvaluateOperator, GenerateDifferentialNoise(), ImpulseNoise, ImpulseNoiseEvaluateOperator, LaplacianNoise, LaplacianNoiseEvaluateOperator, LeftShiftEvaluateOperator, LogEvaluateOperator, MagickEpsilon, MagickMin(), MagickPI, MaxEvaluateOperator, MeanEvaluateOperator, MedianEvaluateOperator, MinEvaluateOperator, MultiplicativeGaussianNoise, MultiplicativeNoiseEvaluateOperator, MultiplyEvaluateOperator, OrEvaluateOperator, PoissonNoise, PoissonNoiseEvaluateOperator, PowEvaluateOperator, QuantumRange, QuantumScale, RightShiftEvaluateOperator, SetEvaluateOperator, SineEvaluateOperator, SubtractEvaluateOperator, SumEvaluateOperator, ThresholdBlackEvaluateOperator, ThresholdEvaluateOperator, ThresholdWhiteEvaluateOperator, UndefinedEvaluateOperator, UniformNoise, UniformNoiseEvaluateOperator, and XorEvaluateOperator.
Referenced by EvaluateImage(), and EvaluateImages().
static Quantum ApplyFunction (Quantum pixel, const MagickFunction function, const size_t number_parameters, const double * parameters, ExceptionInfo * exception) static
Definition at line 887 of file statistic.c.
References ArcsinFunction, ArctanFunction, ClampToQuantum(), MagickPI, PolynomialFunction, QuantumRange, QuantumScale, SinusoidFunction, and UndefinedFunction.
Referenced by FunctionImage().
static PixelList* DestroyPixelList (PixelList * pixel_list) static
Definition at line 1965 of file statistic.c.
References _SkipList::nodes, RelinquishMagickMemory(), and _PixelList::skip_list.
Referenced by AcquirePixelList(), and DestroyPixelListThreadSet().
static PixelList** DestroyPixelListThreadSet (PixelList ** pixel_list) static
Definition at line 1976 of file statistic.c.
References DestroyPixelList(), GetMagickResourceLimit(), RelinquishMagickMemory(), and ThreadResource.
Referenced by AcquirePixelListThreadSet(), and StatisticImage().
static PixelChannels** DestroyPixelThreadSet (PixelChannels ** pixels) static
Definition at line 138 of file statistic.c.
References GetMagickResourceLimit(), RelinquishMagickMemory(), and ThreadResource.
Referenced by AcquirePixelThreadSet(), EvaluateImages(), and PolynomialImage().
MagickExport MagickBooleanType EvaluateImage (Image * image, const MagickEvaluateOperator op, const double value, ExceptionInfo * exception)
Definition at line 753 of file statistic.c.
References AcquireAuthenticCacheView(), AcquireRandomInfoThreadSet(), ApplyEvaluateOperator(), ClampToQuantum(), _Image::columns, CopyPixelTrait, _Image::debug, DestroyCacheView(), DestroyRandomInfoThreadSet(), DirectClass, EvaluateImageTag, _Image::filename, GetCacheViewAuthenticPixels(), GetMagickModule, GetOpenMPThreadId(), GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelReadMask(), GetRandomSecretKey(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, _Image::progress_monitor, random_info, _Image::rows, SetImageProgress(), SetImageStorageClass(), _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), TraceEvent, and UndefinedPixelTrait.
MagickExport Image* EvaluateImages (const Image * images, const MagickEvaluateOperator op, ExceptionInfo * exception)
Definition at line 423 of file statistic.c.
References AcquireAuthenticCacheView(), AcquirePixelThreadSet(), AcquireRandomInfoThreadSet(), AcquireVirtualCacheView(), AddEvaluateOperator, ApplyEvaluateOperator(), _PixelChannels::channel, ClampToQuantum(), CloneImage(), _Image::columns, _Image::debug, DestroyCacheView(), DestroyImage(), DestroyPixelThreadSet(), DestroyRandomInfoThreadSet(), DirectClass, EvaluateImageTag, _Image::filename, GetCacheViewVirtualPixels(), GetImageListLength(), GetMagickModule, GetNextImageInList(), GetOpenMPThreadId(), GetPixelChannel(), GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelReadMask(), GetRandomSecretKey(), IntensityCompare(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, MaxPixelChannels, MeanEvaluateOperator, MedianEvaluateOperator, MultiplyEvaluateOperator, _Image::progress_monitor, QuantumScale, QueueCacheViewAuthenticPixels(), random_info, ResourceLimitError, _Image::rows, SetImageProgress(), SetImageStorageClass(), _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), ThrowMagickException(), TraceEvent, UndefinedPixelTrait, and UpdatePixelTrait.
static double EvaluateMax (const double x, const double y) inline static
Definition at line 193 of file statistic.c.
Referenced by ApplyEvaluateOperator(), and GetImageStatistics().
MagickExport MagickBooleanType FunctionImage (Image * image, const MagickFunction function, const size_t number_parameters, const double * parameters, ExceptionInfo * exception)
Definition at line 985 of file statistic.c.
References AcquireAuthenticCacheView(), ApplyFunction(), _Image::columns, _Image::debug, DestroyCacheView(), DirectClass, _Image::filename, FunctionImageTag, GetCacheViewAuthenticPixels(), GetMagickModule, GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelReadMask(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, _Image::progress_monitor, _Image::rows, SetImageProgress(), SetImageStorageClass(), _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), TraceEvent, UndefinedPixelTrait, and UpdatePixelTrait.
Referenced by BrightnessContrastImage().
static size_t GetImageChannels (const Image * image) static
Definition at line 1489 of file statistic.c.
References GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), and UndefinedPixelTrait.
Referenced by GetImageStatistics().
MagickExport MagickBooleanType GetImageExtrema (const Image * image, size_t * minima, size_t * maxima, ExceptionInfo * exception)
Definition at line 1105 of file statistic.c.
References _Image::debug, _Image::filename, GetImageRange(), GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, _Image::signature, and TraceEvent.
MagickExport MagickBooleanType GetImageKurtosis (const Image * image, double * kurtosis, double * skewness, ExceptionInfo * exception)
Definition at line 1232 of file statistic.c.
References AcquireVirtualCacheView(), _Image::columns, _Image::debug, DestroyCacheView(), _Image::filename, GetCacheViewVirtualPixels(), GetMagickModule, GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelReadMask(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, _Image::rows, _Image::signature, TraceEvent, UndefinedPixelTrait, and UpdatePixelTrait.
Referenced by FxChannelStatistics(), and GetMagickProperty().
MagickExport MagickBooleanType GetImageMean (const Image * image, double * mean, double * standard_deviation, ExceptionInfo * exception)
Definition at line 1155 of file statistic.c.
References CompositePixelChannel, _Image::debug, _Image::filename, GetImageStatistics(), GetMagickModule, GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, _ChannelStatistics::mean, RelinquishMagickMemory(), _Image::signature, _ChannelStatistics::standard_deviation, TraceEvent, UndefinedPixelTrait, UpdatePixelTrait, and _ChannelStatistics::variance.
Referenced by AutoGammaImage(), FxChannelStatistics(), and GetMagickProperty().
MagickExport MagickBooleanType GetImageRange (const Image * image, double * minima, double * maxima, ExceptionInfo * exception)
Definition at line 1369 of file statistic.c.
References AcquireVirtualCacheView(), _Image::columns, _Image::debug, DestroyCacheView(), _Image::filename, GetCacheViewVirtualPixels(), GetMagickModule, GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelReadMask(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, _Image::rows, _Image::signature, TraceEvent, UndefinedPixelTrait, and UpdatePixelTrait.
Referenced by FxChannelStatistics(), GetImageExtrema(), GetMagickProperty(), and MinMaxStretchImage().
MagickExport ChannelStatistics* GetImageStatistics (const Image * image, ExceptionInfo * exception)
Definition at line 1508 of file statistic.c.
References AcquireQuantumMemory(), _ChannelStatistics::area, _Image::columns, CompositePixelChannel, _Image::debug, _ChannelStatistics::depth, EvaluateMax(), _Image::filename, GetImageChannels(), GetMagickModule, GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelReadMask(), GetQuantumRange(), GetVirtualPixels(), _ChannelStatistics::kurtosis, LogMagickEvent(), MAGICKCORE_QUANTUM_DEPTH, MagickFalse, MagickHuge, MagickMin(), MagickSignature, MagickTrue, _ChannelStatistics::maxima, MaxPixelChannels, _ChannelStatistics::mean, _ChannelStatistics::minima, PerceptibleReciprocal(), ResetMagickMemory(), ResourceLimitFatalError, _Image::rows, ScaleAnyToQuantum(), ScaleQuantumToAny(), _Image::signature, _ChannelStatistics::skewness, _ChannelStatistics::standard_deviation, _ChannelStatistics::sum, _ChannelStatistics::sum_cubed, _ChannelStatistics::sum_fourth_power, _ChannelStatistics::sum_squared, ThrowFatalException, TraceEvent, UndefinedPixelTrait, and _ChannelStatistics::variance.
Referenced by GetImageMean(), GetNormalizedCrossCorrelationDistortion(), and IdentifyImage().
static void GetMaximumPixelList (PixelList * pixel_list, Quantum * pixel) inline static
Definition at line 2095 of file statistic.c.
References _SkipNode::count, _PixelList::length, _SkipNode::next, _SkipList::nodes, and _PixelList::skip_list.
Referenced by StatisticImage().
static void GetMeanPixelList (PixelList * pixel_list, Quantum * pixel) inline static
Definition at line 2124 of file statistic.c.
References _SkipNode::count, _PixelList::length, _SkipNode::next, _SkipList::nodes, and _PixelList::skip_list.
Referenced by StatisticImage().
static void GetMedianPixelList (PixelList * pixel_list, Quantum * pixel) inline static
Definition at line 2155 of file statistic.c.
References _SkipNode::count, _PixelList::length, _SkipNode::next, _SkipList::nodes, and _PixelList::skip_list.
Referenced by StatisticImage().
static void GetMinimumPixelList (PixelList * pixel_list, Quantum * pixel) inline static
Definition at line 2180 of file statistic.c.
References _SkipNode::count, _PixelList::length, _SkipNode::next, _SkipList::nodes, and _PixelList::skip_list.
Referenced by StatisticImage().
static void GetModePixelList (PixelList * pixel_list, Quantum * pixel) inline static
Definition at line 2209 of file statistic.c.
References _SkipNode::count, _PixelList::length, _SkipNode::next, _SkipList::nodes, and _PixelList::skip_list.
Referenced by StatisticImage().
static void GetNonpeakPixelList (PixelList * pixel_list, Quantum * pixel) inline static
Definition at line 2243 of file statistic.c.
References _SkipNode::count, _PixelList::length, _SkipNode::next, _SkipList::nodes, and _PixelList::skip_list.
Referenced by StatisticImage().
static void GetStandardDeviationPixelList (PixelList * pixel_list, Quantum * pixel) inline static
Definition at line 2278 of file statistic.c.
References _SkipNode::count, _PixelList::length, _SkipNode::next, _SkipList::nodes, and _PixelList::skip_list.
Referenced by StatisticImage().
static void InsertPixelList (const Quantum pixel, PixelList * pixel_list) inline static
Definition at line 2318 of file statistic.c.
References AddNodePixelList(), _SkipNode::count, _SkipList::nodes, _SkipNode::signature, _PixelList::signature, and _PixelList::skip_list.
Referenced by StatisticImage().
static int IntensityCompare (const void * x, const void * y) static
Definition at line 204 of file statistic.c.
References _PixelChannels::channel, and MaxPixelChannels.
Referenced by EvaluateImages().
static double MagickAbsoluteValue (const double x) inline static
Definition at line 2336 of file statistic.c.
Referenced by StatisticImage().
static size_t MagickMax (const size_t x, const size_t y) inline static
Definition at line 2343 of file statistic.c.
Referenced by StatisticImage().
static double MagickMin (const double x, const double y) inline static
Definition at line 228 of file statistic.c.
Referenced by ApplyEvaluateOperator(), and GetImageStatistics().
MagickExport Image* PolynomialImage (const Image * images, const size_t number_terms, const double * terms, ExceptionInfo * exception)
Definition at line 1711 of file statistic.c.
References AcquireAuthenticCacheView(), AcquirePixelThreadSet(), AcquireVirtualCacheView(), _PixelChannels::channel, ClampToQuantum(), CloneImage(), _Image::columns, _Image::debug, DestroyCacheView(), DestroyImage(), DestroyPixelThreadSet(), DirectClass, _Image::filename, GetCacheViewVirtualPixels(), GetImageListLength(), GetMagickModule, GetNextImageInList(), GetOpenMPThreadId(), GetPixelChannel(), GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelReadMask(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, MaxPixelChannels, PolynomialImageTag, _Image::progress_monitor, QuantumRange, QuantumScale, QueueCacheViewAuthenticPixels(), ResourceLimitError, _Image::rows, SetImageProgress(), SetImageStorageClass(), _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), ThrowMagickException(), TraceEvent, UndefinedPixelTrait, and UpdatePixelTrait.
static void ResetPixelList (PixelList * pixel_list) static
Definition at line 2350 of file statistic.c.
References _SkipList::level, _SkipNode::next, _SkipList::nodes, _PixelList::seed, _PixelList::signature, and _PixelList::skip_list.
Referenced by StatisticImage().
MagickExport Image* StatisticImage (const Image * image, const StatisticType type, const size_t width, const size_t height, ExceptionInfo * exception)
Definition at line 2372 of file statistic.c.
References AcquireAuthenticCacheView(), AcquirePixelListThreadSet(), AcquireVirtualCacheView(), ClampToQuantum(), CloneImage(), _Image::columns, CopyPixelTrait, _Image::debug, DestroyCacheView(), DestroyImage(), DestroyPixelListThreadSet(), DirectClass, _Image::filename, GetCacheViewVirtualPixels(), GetMagickModule, GetMaximumPixelList(), GetMeanPixelList(), GetMedianPixelList(), GetMinimumPixelList(), GetModePixelList(), GetNonpeakPixelList(), GetOpenMPThreadId(), GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelReadMask(), GetStandardDeviationPixelList(), GradientStatistic, InsertPixelList(), LogMagickEvent(), MagickAbsoluteValue(), MagickFalse, MagickMax(), MagickSignature, MagickTrue, MaximumStatistic, MeanStatistic, MedianStatistic, MinimumStatistic, ModeStatistic, NonpeakStatistic, _Image::progress_monitor, QueueCacheViewAuthenticPixels(), ResetPixelList(), ResourceLimitError, _Image::rows, SetImageProgress(), SetImageStorageClass(), SetPixelChannel(), _ExceptionInfo::signature, _Image::signature, StandardDeviationStatistic, StatisticImageTag, SyncCacheViewAuthenticPixels(), ThrowImageException, TraceEvent, and UndefinedPixelTrait.
Referenced by DeskewImage(), and PreviewImage().