MagickCore: stream.h File Reference
stream.h File Reference
Typedefs
typedef struct _StreamInfo StreamInfo
typedef size_t(* StreamHandler)(const Image *, const void *, const size_t)
Functions
MagickExport Image * ReadStream (const ImageInfo *, StreamHandler, ExceptionInfo *)
MagickExport Image * StreamImage (const ImageInfo *, StreamInfo *, ExceptionInfo *)
MagickExport MagickBooleanType OpenStream (const ImageInfo *, StreamInfo *, const char *, ExceptionInfo *)
MagickExport MagickBooleanType WriteStream (const ImageInfo *, Image *, StreamHandler, ExceptionInfo *)
MagickExport StreamInfo * AcquireStreamInfo (const ImageInfo *, ExceptionInfo *)
MagickExport StreamInfo * DestroyStreamInfo (StreamInfo *)
MagickExport void SetStreamInfoMap (StreamInfo *, const char *)
MagickExport void SetStreamInfoStorageType (StreamInfo *, const StorageType)
Typedef Documentation
typedef size_t(* StreamHandler)(const Image *, const void *, const size_t)
Definition at line 29 of file stream.h.
typedef struct _StreamInfo StreamInfo
Definition at line 25 of file stream.h.
Function Documentation
MagickExport StreamInfo* AcquireStreamInfo (const ImageInfo * , ExceptionInfo *)
MagickExport StreamInfo * DestroyStreamInfo (StreamInfo *)
Definition at line 268 of file stream.c.
References CloseBlob(), DestroyImage(), DestroyQuantumInfo(), DestroyString(), GetMagickModule, LogMagickEvent(), MagickSignature, _StreamInfo::map, _StreamInfo::pixels, _StreamInfo::quantum_info, RelinquishAlignedMemory(), RelinquishMagickMemory(), _StreamInfo::signature, _StreamInfo::stream, and TraceEvent.
MagickExport MagickBooleanType OpenStream (const ImageInfo * , StreamInfo * , const char * , ExceptionInfo *)
MagickExport Image* ReadStream (const ImageInfo * , StreamHandler , ExceptionInfo *)
MagickExport void SetStreamInfoMap (StreamInfo * , const char *)
MagickExport void SetStreamInfoStorageType (StreamInfo * , const StorageType)
Definition at line 1104 of file stream.c.
References MagickSignature, _StreamInfo::signature, and _StreamInfo::storage_type.
MagickExport Image * StreamImage (const ImageInfo * , StreamInfo * , ExceptionInfo *)
Definition at line 1235 of file stream.c.
References AcquireQuantumInfo(), _ImageInfo::client_data, CloneImageInfo(), _ImageInfo::debug, DestroyImage(), DestroyImageInfo(), DestroyQuantumInfo(), _StreamInfo::exception, _ImageInfo::filename, GetMagickModule, _StreamInfo::image_info, LogMagickEvent(), MagickFalse, MagickSignature, _StreamInfo::quantum_info, ReadStream(), _StreamInfo::signature, _ImageInfo::signature, TraceEvent, and WriteStreamImage().
MagickExport MagickBooleanType WriteStream (const ImageInfo * , Image * , StreamHandler , ExceptionInfo *)
Definition at line 2733 of file stream.c.
References CloneImageInfo(), _ImageInfo::debug, DestroyImageInfo(), _ImageInfo::filename, GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, _Image::signature, _ImageInfo::signature, _ImageInfo::stream, TraceEvent, and WriteImage().