MagickCore: string.c File Reference
string.c File Reference
#include "MagickCore/studio.h"
#include "MagickCore/blob.h"
#include "MagickCore/blob-private.h"
#include "MagickCore/exception.h"
#include "MagickCore/exception-private.h"
#include "MagickCore/list.h"
#include "MagickCore/locale_.h"
#include "MagickCore/log.h"
#include "MagickCore/memory_.h"
#include "MagickCore/nt-base-private.h"
#include "MagickCore/property.h"
#include "MagickCore/resource_.h"
#include "MagickCore/signature-private.h"
#include "MagickCore/string_.h"
#include "MagickCore/string-private.h"
#include "MagickCore/utility-private.h"
Functions
MagickExport char * AcquireString (const char *source)
MagickExport StringInfo * AcquireStringInfo (const size_t length)
MagickExport StringInfo * BlobToStringInfo (const void *blob, const size_t length)
MagickExport char * CloneString (char **destination, const char *source)
MagickExport StringInfo * CloneStringInfo (const StringInfo *string_info)
static size_t MagickMin (const size_t x, const size_t y)
MagickExport int CompareStringInfo (const StringInfo *target, const StringInfo *source)
MagickExport size_t ConcatenateMagickString (char *destination, const char *source, const size_t length)
MagickExport MagickBooleanType ConcatenateString (char **destination, const char *source)
MagickExport void ConcatenateStringInfo (StringInfo *string_info, const StringInfo *source)
MagickExport StringInfo * ConfigureFileToStringInfo (const char *filename)
MagickExport char * ConstantString (const char *source)
MagickExport size_t CopyMagickString (char *destination, const char *source, const size_t length)
MagickExport char * DestroyString (char *string)
MagickExport StringInfo * DestroyStringInfo (StringInfo *string_info)
MagickExport char ** DestroyStringList (char **list)
MagickExport char * EscapeString (const char *source, const char escape)
MagickExport char * FileToString (const char *filename, const size_t extent, ExceptionInfo *exception)
MagickExport StringInfo * FileToStringInfo (const char *filename, const size_t extent, ExceptionInfo *exception)
MagickExport ssize_t FormatMagickSize (const MagickSizeType size, const MagickBooleanType bi, char *format)
MagickExport ssize_t FormatMagickTime (const time_t time, const size_t length, char *timestamp)
MagickExport char * GetEnvironmentValue (const char *name)
MagickExport unsigned char * GetStringInfoDatum (const StringInfo *string_info)
MagickExport size_t GetStringInfoLength (const StringInfo *string_info)
MagickExport const char * GetStringInfoPath (const StringInfo *string_info)
MagickExport double InterpretSiPrefixValue (const char *restrict string, char **restrict sentinal)
MagickExport MagickBooleanType IsStringTrue (const char *value)
MagickExport MagickBooleanType IsStringNotFalse (const char *value)
MagickExport int LocaleCompare (const char *p, const char *q)
MagickExport void LocaleLower (char *string)
MagickExport int LocaleNCompare (const char *p, const char *q, const size_t length)
MagickExport void LocaleUpper (char *string)
MagickExport void PrintStringInfo (FILE *file, const char *id, const StringInfo *string_info)
MagickExport void ResetStringInfo (StringInfo *string_info)
MagickExport void SetStringInfo (StringInfo *string_info, const StringInfo *source)
MagickExport void SetStringInfoDatum (StringInfo *string_info, const unsigned char *source)
MagickExport void SetStringInfoLength (StringInfo *string_info, const size_t length)
MagickExport void SetStringInfoPath (StringInfo *string_info, const char *path)
MagickExport StringInfo * SplitStringInfo (StringInfo *string_info, const size_t offset)
MagickExport char * StringInfoToString (const StringInfo *string_info)
MagickExport char * StringInfoToHexString (const StringInfo *string_info)
MagickExport char ** StringToArgv (const char *text, int *argc)
MagickExport double * StringToArrayOfDoubles (const char *string, ssize_t *count, ExceptionInfo *exception)
MagickExport char * StringToken (const char *delimiters, char **string)
MagickExport char ** StringToList (const char *text)
MagickExport StringInfo * StringToStringInfo (const char *string)
MagickExport void StripString (char *message)
MagickExport MagickBooleanType SubstituteString (char **string, const char *search, const char *replace)
Variables
static const unsigned char asciimap []
Function Documentation
MagickExport char* AcquireString (const char * source)
Definition at line 119 of file string.c.
References AcquireQuantumMemory(), MaxTextExtent, ResourceLimitFatalError, and ThrowFatalException.
Referenced by CanonicalXMLContent(), ClipImagePath(), CloneMontageInfo(), CloneString(), ColorMatrixImage(), ConcatenateString(), DrawImage(), DrawPatternPath(), EncodePredefinedEntities(), EscapeParenthesis(), ExpandFilenames(), FormatMagickCaption(), GenerateEntropicChaos(), GetCommandOptions(), GetDrawInfo(), GetEXIFProperty(), GetHostname(), GetMontageInfo(), GetPageGeometry(), InterpretImageProperties(), ListFiles(), LoadCoderList(), LoadColorList(), LoadConfigureList(), LoadDelegateList(), LoadLocaleList(), LoadLogList(), LoadMagicList(), LoadMimeList(), LoadPolicyList(), LoadTypeList(), MontageImageList(), PolaroidImage(), QueryColorCompliance(), SelectiveBlurImage(), StringToArgv(), SystemCommand(), TracePSClippath(), TraceSVGClippath(), TranslateEvent(), TranslateFilename(), VignetteImage(), and XMLTreeInfoToXML().
MagickExport StringInfo* AcquireStringInfo (const size_t length)
Definition at line 165 of file string.c.
References AcquireMagickMemory(), AcquireQuantumMemory(), _StringInfo::datum, _StringInfo::length, MagickSignature, MaxTextExtent, ResetMagickMemory(), ResourceLimitFatalError, _StringInfo::signature, and ThrowFatalException.
Referenced by AcquireRandomInfo(), AcquireSignatureInfo(), BlobToStringInfo(), CloneStringInfo(), ConfigureFileToStringInfo(), ConnectPixelCacheServer(), FileToStringInfo(), GenerateEntropicChaos(), GetConfigureOptions(), GetLocaleOptions(), GetMagickSignature(), GetProfilesFromResourceBlock(), GetRandomKey(), ProfileImage(), SignatureImage(), SplitStringInfo(), and StringToStringInfo().
MagickExport StringInfo* BlobToStringInfo (const void * blob, const size_t length)
Definition at line 213 of file string.c.
References AcquireQuantumMemory(), AcquireStringInfo(), _StringInfo::datum, DestroyStringInfo(), _StringInfo::length, and MaxTextExtent.
MagickExport char* CloneString (char ** destination, const char * source)
Definition at line 265 of file string.c.
References AcquireString(), DestroyString(), GetMagickModule, LogMagickEvent(), MaxTextExtent, ResizeQuantumMemory(), ResourceLimitFatalError, ThrowFatalException, and TraceEvent.
Referenced by AnnotateImage(), CloneDrawInfo(), CloneImage(), CloneImageInfo(), CloneImageProperties(), DrawClipPath(), DrawImage(), DrawPatternPath(), DrawPrimitive(), GetDrawInfo(), GetPathTemplate(), IdentifyImage(), MontageImageList(), PolaroidImage(), PreviewImage(), RenderPostscript(), RenderType(), SetImageInfo(), SetImageOption(), and SetStreamInfoMap().
MagickExport StringInfo* CloneStringInfo (const StringInfo * string_info)
Definition at line 318 of file string.c.
References AcquireStringInfo(), _StringInfo::datum, GetMagickModule, _StringInfo::length, LogMagickEvent(), MagickSignature, _StringInfo::signature, and TraceEvent.
Referenced by CloneImageInfo(), CloneImageProfiles(), and SetImageProfile().
MagickExport int CompareStringInfo (const StringInfo * target, const StringInfo * source)
Definition at line 366 of file string.c.
References _StringInfo::datum, GetMagickModule, _StringInfo::length, LogMagickEvent(), MagickMin(), MagickSignature, _StringInfo::signature, and TraceEvent.
Referenced by CompareSplayTreeStringInfo(), and ProfileImage().
MagickExport size_t ConcatenateMagickString (char * destination, const char * source, const size_t length)
Definition at line 415 of file string.c.
Referenced by AcquireUniqueSymbolicLink(), ClipImagePath(), ConcatenateColorComponent(), ConcatentateHexColorComponent(), ExpandFilename(), ExpandFilenames(), FormatMagickCaption(), GetColorTuple(), GetConfigurePaths(), GetExecutionPath(), GetImageViewException(), GetMagickProperty(), GetMagickPropertyLetter(), GetNumberColors(), GetPageGeometry(), IdentifyImage(), InterpretImageFilename(), ListDelegateInfo(), ListMagickInfo(), LoadCoderList(), LoadColorList(), LoadConfigureList(), LoadDelegateList(), LoadLocaleList(), LoadLogList(), LoadMagicList(), LoadMimeList(), LoadPolicyList(), LoadTypeList(), LogPixelChannels(), MontageImageList(), SystemCommand(), ThrowMagickExceptionList(), and ThumbnailImage().
MagickExport MagickBooleanType ConcatenateString (char ** destination, const char * source)
Definition at line 481 of file string.c.
References AcquireString(), MagickTrue, MaxTextExtent, ResizeQuantumMemory(), ResourceLimitFatalError, and ThrowFatalException.
Referenced by CanonicalXMLContent(), ColorMatrixImage(), ExpandFilenames(), GetIPTCProperty(), ParseCharacterContent(), SelectiveBlurImage(), TracePSClippath(), and TraceSVGClippath().
MagickExport void ConcatenateStringInfo (StringInfo * string_info, const StringInfo * source)
Definition at line 541 of file string.c.
References _StringInfo::datum, GetMagickModule, _StringInfo::length, LogMagickEvent(), MagickSignature, ResourceLimitFatalError, SetStringInfoLength(), _StringInfo::signature, ThrowFatalException, and TraceEvent.
Referenced by GenerateEntropicChaos(), and GetMagickSignature().
MagickExport StringInfo* ConfigureFileToStringInfo (const char * filename)
Definition at line 582 of file string.c.
References AcquireQuantumMemory(), AcquireStringInfo(), CopyMagickString(), _StringInfo::datum, DestroyString(), _StringInfo::length, MagickMin(), _StreamInfo::map, MapBlob(), MaxTextExtent, O_BINARY, open_utf8(), _StringInfo::path, ReadMode, and UnmapBlob().
Referenced by GetConfigureOptions(), and GetLocaleOptions().
MagickExport char* ConstantString (const char * source)
Definition at line 689 of file string.c.
References AcquireQuantumMemory(), ResourceLimitFatalError, and ThrowFatalException.
Referenced by AcquireFxInfo(), AcquireFxThreadSet(), AcquireStreamInfo(), AcquireUniqueFileResource(), AddChildToXMLTree(), CloneImageArtifacts(), CloneImageOptions(), CloneImageProfiles(), CloneImageProperties(), CloneImageView(), ExpandFilenames(), FxChannelStatistics(), FxEvaluateSubexpression(), FxGetSymbol(), GenerateEntropicChaos(), GetCoderList(), GetColorList(), GetConfigureList(), GetConfigureOption(), GetConfigurePaths(), GetDelegateList(), GetEnvironmentValue(), GetExceptionMessage(), GetImageRegistry(), GetLocaleList(), GetLogList(), GetMagickHomeURL(), GetMagickList(), GetMagicList(), GetMimeList(), GetPathTemplate(), GetPolicyList(), GetPolicyValue(), GetThresholdMapFile(), GetTypeList(), GetXMLTreeAttributes(), GetXMPProperty(), InitializeLocaleList(), InterpretImageProperties(), LoadCoderList(), LoadCoderLists(), LoadColorList(), LoadConfigureList(), LoadDelegateList(), LoadLocaleList(), LoadLogList(), LoadLogLists(), LoadMagicList(), LoadMimeList(), LoadPolicyList(), LoadTypeList(), MagickToMime(), NewImageView(), NewImageViewRegion(), NewXMLTree(), NewXMLTreeTag(), ParseEntities(), ParseInternalDoctype(), ParseOpenTag(), ParseProcessingInstructions(), ProfileImage(), SetImageArtifact(), SetImageOption(), SetImageProfile(), SetImageProperty(), SetImageRegistry(), SetImageViewDescription(), SetLogFormat(), SetMagickInfo(), SetXMLTreeAttribute(), SetXMLTreeContent(), and ThrowException().
MagickExport size_t CopyMagickString (char * destination, const char * source, const size_t length)
Definition at line 744 of file string.c.
Referenced by AcquireDistributeCacheInfo(), AcquireImage(), AcquireNextImage(), AppendImageFormat(), BlobToImage(), ClipImagePath(), CloneImage(), CloneImageInfo(), CloneImageProperties(), CloneMontageInfo(), ConfigureFileToStringInfo(), DefineImageArtifact(), DefineImageOption(), DefineImageProperty(), DefineImageRegistry(), DistributePixelCacheClient(), DrawImage(), DrawPrimitive(), ExpandFilename(), ExpandFilenames(), FileToStringInfo(), FormatMagickCaption(), FxEvaluateSubexpression(), FxGetSymbol(), Get8BIMProperty(), GetColorCompliance(), GetCommandOptionFlags(), GetConfigureOptions(), GetConfigurePaths(), GetExceptionMessage(), GetExecutionPath(), GetGeometry(), GetImageMagick(), GetImageProfile(), GetImageViewException(), GetIPTCProperty(), GetLocaleOptions(), GetMagickProperty(), GetMagickToken(), GetMontageInfo(), GetNumberColors(), GetPageGeometry(), GetPathComponent(), GetPathComponents(), GetPolicyInfo(), GlobExpression(), IdentifyImage(), ImagesToBlob(), ImageToBlob(), InjectImageBlob(), InterpretImageFilename(), InvokeDelegate(), IsTaintImage(), ListDelegateInfo(), ListMagickInfo(), ListMagickResourceInfo(), LoadCoderList(), LoadColorList(), LoadConfigureList(), LoadDelegateList(), LoadLocaleList(), LoadLogList(), LoadMagicList(), LoadMagicLists(), LoadMimeList(), LoadPolicyList(), LoadTypeList(), LoadTypeLists(), MagickCoreGenesis(), MontageImageList(), OpenBlob(), OpenStream(), ParseCommandOption(), ParseEntities(), ParseGeometry(), ParseProcessingInstructions(), PersistPixelCache(), PingImages(), PreviewImage(), QueryColorCompliance(), QueryColorname(), ReadImage(), ReadImages(), RelinquishUniqueFileResource(), SetClientName(), SetClientPath(), SetImageInfo(), SetImageProfile(), SetImageProperty(), SetLogName(), SetStringInfoPath(), StringToList(), ThrowMagickExceptionList(), ThumbnailImage(), TranslateEvent(), TranslateFilename(), WriteImage(), and WriteImages().
MagickExport char* DestroyString (char * string)
Definition at line 814 of file string.c.
References RelinquishMagickMemory().
Referenced by AcquireDistributeCacheInfo(), AcquireFxThreadSet(), AcquireImage(), AddPathToXMLTree(), AnnotateImage(), CanonicalXMLContent(), ClipImagePath(), CloneString(), ColorMatrixImage(), ConfigureFileToStringInfo(), DestroyCoderNode(), DestroyColorElement(), DestroyConfigureElement(), DestroyDelegate(), DestroyDrawInfo(), DestroyExceptionElement(), DestroyFxInfo(), DestroyImage(), DestroyImageInfo(), DestroyImageView(), DestroyLocaleNode(), DestroyLogElement(), DestroyMagicElement(), DestroyMagickNode(), DestroyMimeElement(), DestroyMontageInfo(), DestroyPolicyElement(), DestroyStreamInfo(), DestroyStringList(), DestroyTemporaryResources(), DestroyThresholdMap(), DestroyTypeNode(), DestroyXMLTree(), DestroyXMLTreeAttributes(), DrawImage(), EncodePredefinedEntities(), ExpandFilename(), ExpandFilenames(), FormatMagickCaption(), GenerateEntropicChaos(), Get8BIMProperty(), GetConfigurePaths(), GetDelegateCommand(), GetEXIFProperty(), GetHostname(), GetImageInfo(), GetIPTCProperty(), GetMultilineTypeMetrics(), GetPathTemplate(), GetXMLTreePath(), GetXMPProperty(), IdentifyImage(), InitializeLocaleList(), InitializeMagickList(), InterpretImageProperties(), InvokeDelegate(), ListDelegateInfo(), ListMagickInfo(), LoadLogList(), LoadMimeList(), LoadTypeList(), LoadTypeLists(), MagickCoreGenesis(), MontageImageList(), NewXMLTree(), ParseCharacterContent(), ParseInternalDoctype(), PolaroidImage(), ProfileImage(), QueryColorCompliance(), ReadImage(), RenderPostscript(), ResourceComponentGenesis(), SelectiveBlurImage(), SetImageProperty(), SetLogFormat(), SetMagickPrecision(), SetMagickResourceLimit(), SetXMLTreeAttribute(), SetXMLTreeContent(), SignatureImage(), StringToArgv(), SyncImageSettings(), SystemCommand(), TracePSClippath(), and TraceSVGClippath().
MagickExport StringInfo* DestroyStringInfo (StringInfo * string_info)
Definition at line 841 of file string.c.
References _StringInfo::datum, GetMagickModule, LogMagickEvent(), MagickSignature, RelinquishMagickMemory(), _StringInfo::signature, and TraceEvent.
Referenced by AcquireRandomInfo(), AcquireUniqueFileResource(), BlobToStringInfo(), ConnectPixelCacheServer(), DestroyImageInfo(), DestroyOptions(), DestroyProfile(), DestroyRandomInfo(), DestroySignatureInfo(), DistributePixelCacheClient(), FileToStringInfo(), GenerateEntropicChaos(), GetMagickSignature(), GetProfilesFromResourceBlock(), HashStringType(), ProfileImage(), ShredFile(), and SignatureImage().
MagickExport char** DestroyStringList (char ** list)
Definition at line 876 of file string.c.
References DestroyString(), and RelinquishMagickMemory().
MagickExport char* EscapeString (const char * source, const char escape)
Definition at line 917 of file string.c.
References AcquireQuantumMemory(), GetMagickModule, LogMagickEvent(), MaxTextExtent, ResourceLimitFatalError, ThrowFatalException, and TraceEvent.
MagickExport char* FileToString (const char * filename, const size_t extent, ExceptionInfo * exception)
Definition at line 989 of file string.c.
References FileToBlob(), GetMagickModule, LogMagickEvent(), and TraceEvent.
Referenced by AcquireFxThreadSet(), DrawImage(), ExpandFilenames(), InterpretImageProperties(), LoadCoderList(), LoadColorList(), LoadConfigureList(), LoadDelegateList(), LoadLocaleList(), LoadLogList(), LoadMagicList(), LoadMimeList(), LoadPolicyList(), LoadTypeList(), and LoadTypeLists().
MagickExport StringInfo* FileToStringInfo (const char * filename, const size_t extent, ExceptionInfo * exception)
Definition at line 1028 of file string.c.
References AcquireStringInfo(), CopyMagickString(), _StringInfo::datum, DestroyStringInfo(), FileToBlob(), GetMagickModule, _StringInfo::length, LogMagickEvent(), MaxTextExtent, _StringInfo::path, and TraceEvent.
Referenced by SetImageProperty().
MagickExport ssize_t FormatMagickSize (const MagickSizeType size, const MagickBooleanType bi, char * format)
Definition at line 1076 of file string.c.
References FormatLocaleString(), MagickFalse, and MaxTextExtent.
Referenced by AcquireMagickResource(), GetMagickProperty(), GetMagickPropertyLetter(), IdentifyImage(), ListLogInfo(), ListMagickResourceInfo(), OpenPixelCache(), RelinquishMagickResource(), SetPixelCacheExtent(), and ThumbnailImage().
MagickExport ssize_t FormatMagickTime (const time_t time, const size_t length, char * timestamp)
Definition at line 1157 of file string.c.
References FormatLocaleString(), and ResetMagickMemory().
Referenced by ReadImage(), and TranslateEvent().
MagickExport char* GetEnvironmentValue (const char * name)
Definition at line 1231 of file string.c.
References ConstantString().
Referenced by ExpandFilename(), GetConfigurePaths(), GetImageInfo(), GetPathTemplate(), InitializeLocaleList(), LoadTypeLists(), MagickCoreGenesis(), ResourceComponentGenesis(), SetMagickPrecision(), and ShredFile().
MagickExport unsigned char* GetStringInfoDatum (const StringInfo * string_info)
Definition at line 1264 of file string.c.
References _StringInfo::datum, MagickSignature, and _StringInfo::signature.
Referenced by AcquireRandomInfo(), AcquireUniqueFileResource(), ConnectPixelCacheServer(), DistributePixelCacheClient(), FinalizeSignature(), GenerateEntropicChaos(), Get8BIMProperty(), GetEXIFProperty(), GetIPTCProperty(), GetMagickSignature(), GetProfilesFromResourceBlock(), GetRandomKey(), GetThresholdMap(), HashStringInfoType(), HashStringType(), IdentifyImage(), IncrementRandomNonce(), ListThresholdMaps(), LoadCoderLists(), LoadColorLists(), LoadConfigureLists(), LoadDelegateLists(), LoadLocaleLists(), LoadLogLists(), LoadMagicLists(), LoadMimeLists(), LoadPolicyLists(), LoadTypeLists(), ProfileImage(), SetRandomKey(), ShredFile(), SignatureImage(), SyncImageProfiles(), TransformSignature(), and UpdateSignature().
MagickExport size_t GetStringInfoLength (const StringInfo * string_info)
Definition at line 1293 of file string.c.
References _StringInfo::length, MagickSignature, and _StringInfo::signature.
Referenced by AcquireRandomInfo(), AcquireUniqueFileResource(), FinalizeSignature(), Get8BIMProperty(), GetEXIFProperty(), GetIPTCProperty(), GetMagickSignature(), GetProfilesFromResourceBlock(), IdentifyImage(), IncrementRandomNonce(), ProfileImage(), SyncImageProfiles(), and UpdateSignature().
MagickExport const char* GetStringInfoPath (const StringInfo * string_info)
Definition at line 1322 of file string.c.
References MagickSignature, _StringInfo::path, and _StringInfo::signature.
Referenced by GetThresholdMap(), ListThresholdMaps(), LoadCoderLists(), LoadColorLists(), LoadConfigureLists(), LoadDelegateLists(), LoadLocaleLists(), LoadLogLists(), LoadMagicLists(), LoadMimeLists(), LoadPolicyLists(), and LoadTypeLists().
MagickExport double InterpretSiPrefixValue (const char *restrict string, char **restrict sentinal)
Definition at line 1356 of file string.c.
References InterpretLocaleValue(), and MagickEpsilon.
Referenced by FxEvaluateSubexpression(), and SiPrefixToDoubleInterval().
MagickExport MagickBooleanType IsStringNotFalse (const char * value)
Definition at line 1487 of file string.c.
References LocaleCompare(), MagickFalse, and MagickTrue.
MagickExport MagickBooleanType IsStringTrue (const char * value)
Definition at line 1445 of file string.c.
References LocaleCompare(), MagickFalse, and MagickTrue.
Referenced by GetImageInfo(), IdentifyImage(), LoadCoderList(), LoadColorList(), LoadConfigureList(), LoadDelegateList(), LoadMagicList(), LoadMimeList(), LoadPolicyList(), LoadTypeList(), MorphologyApply(), and WriteImage().
MagickExport int LocaleCompare (const char * p, const char * q)
Definition at line 1532 of file string.c.
Referenced by AppendImageFormat(), CoderCompare(), CoderInfoCompare(), ColorCompare(), ColorInfoCompare(), CompareHashmapString(), CompareHashmapStringInfo(), CompareSplayTreeString(), ConfigureCompare(), ConfigureInfoCompare(), DelegateCompare(), DelegateInfoCompare(), DrawImage(), ExpandFilenames(), ExportCharPixel(), ExportDoublePixel(), ExportFloatPixel(), ExportLongLongPixel(), ExportLongPixel(), ExportQuantumPixel(), ExportShortPixel(), FileCompare(), FileToBlob(), FileToImage(), FxEvaluateSubexpression(), FxGetSymbol(), Get8BIMProperty(), GetCoderInfo(), GetColorCompliance(), GetCommandOptionFlags(), GetCommandOptionInfo(), GetConfigureInfo(), GetDelegateInfo(), GetEXIFProperty(), GetLocaleInfo_(), GetLogInfo(), GetMagickInfo(), GetMagickProperty(), GetPolicyInfo(), GetQuantumInfo(), GetThresholdMapFile(), GetTypeInfo(), GetTypeInfoByFamily(), GetXMPProperty(), GlobExpression(), HuffmanEncodeImage(), IdentifyImage(), ImageToFile(), ImportCharPixel(), ImportDoublePixel(), ImportFloatPixel(), ImportLongLongPixel(), ImportLongPixel(), ImportQuantumPixel(), ImportShortPixel(), InvokeDelegate(), InvokeDynamicImageFilter(), IsStringNotFalse(), IsStringTrue(), IsTaintImage(), ListCoderInfo(), ListColorInfo(), ListConfigureInfo(), ListDelegateInfo(), ListFiles(), ListLocaleInfo(), ListLogInfo(), ListMagicInfo(), ListPolicyInfo(), ListTypeInfo(), LoadCoderList(), LoadColorList(), LoadConfigureList(), LoadDelegateList(), LoadLocaleList(), LoadLogList(), LoadMagicList(), LoadPolicyList(), LoadTypeList(), LocaleInfoCompare(), LocaleTagCompare(), LogCompare(), LogInfoCompare(), MagicCompare(), MagicInfoCompare(), MagickCompare(), MagickInfoCompare(), MontageImageList(), OpenBlob(), ParseCommandOption(), ParseKernelArray(), PingImages(), ProfileImage(), QueryColorCompliance(), ReadImage(), ReadImages(), RelinquishUniqueFileResource(), SetImageInfo(), SetImageOption(), SetImageProfile(), SetImageProperty(), StreamImagePixels(), ThrowException(), ThumbnailImage(), TranslateEvent(), TypeCompare(), TypeInfoCompare(), UnregisterMagickInfo(), and WriteImage().
MagickExport void LocaleLower (char * string)
Definition at line 1585 of file string.c.
Referenced by GetColorTuple(), GetMagickProperty(), MagickToMime(), QueryColorCompliance(), and ThumbnailImage().
MagickExport int LocaleNCompare (const char * p, const char * q, const size_t length)
Definition at line 1632 of file string.c.
Referenced by DrawPrimitive(), FxChannelStatistics(), FxEvaluateSubexpression(), FxGetSymbol(), FxOperatorPrecedence(), GetGeometry(), GetImageProperty(), GetMagickToken(), GetPageGeometry(), GetProfilesFromResourceBlock(), InterpretImageFilename(), InterpretImageProperties(), LoadCoderList(), LoadColorList(), LoadConfigureList(), LoadDelegateList(), LoadLocaleList(), LoadLogList(), LoadMagicList(), LoadPolicyList(), LoadTypeList(), OpenBlob(), ParseGeometry(), ParseLogHandlers(), QueryColorCompliance(), and SetImageProperty().
MagickExport void LocaleUpper (char * string)
Definition at line 1690 of file string.c.
Referenced by InvokeDelegate(), and SetImageInfo().
static size_t MagickMin (const size_t x, const size_t y) inline static
Definition at line 359 of file string.c.
Referenced by CompareStringInfo(), ConfigureFileToStringInfo(), PrintStringInfo(), SetStringInfo(), and StringToList().
MagickExport void PrintStringInfo (FILE * file, const char * id, const StringInfo * string_info)
Definition at line 1727 of file string.c.
References _StringInfo::datum, FormatLocaleFile(), GetMagickModule, _StringInfo::length, LogMagickEvent(), MagickMin(), MagickSignature, _StringInfo::signature, and TraceEvent.
Referenced by IdentifyImage().
MagickExport void ResetStringInfo (StringInfo * string_info)
Definition at line 1811 of file string.c.
References _StringInfo::datum, GetMagickModule, _StringInfo::length, LogMagickEvent(), MagickSignature, ResetMagickMemory(), _StringInfo::signature, and TraceEvent.
Referenced by AcquireRandomInfo(), and ShredFile().
MagickExport void SetStringInfo (StringInfo * string_info, const StringInfo * source)
Definition at line 1843 of file string.c.
References _StringInfo::datum, GetMagickModule, _StringInfo::length, LogMagickEvent(), MagickMin(), MagickSignature, ResetMagickMemory(), _StringInfo::signature, and TraceEvent.
Referenced by AcquireRandomInfo(), SetRandomKey(), SetSignatureDigest(), and SplitStringInfo().
MagickExport void SetStringInfoDatum (StringInfo * string_info, const unsigned char * source)
Definition at line 1884 of file string.c.
References _StringInfo::datum, GetMagickModule, _StringInfo::length, LogMagickEvent(), MagickSignature, _StringInfo::signature, and TraceEvent.
Referenced by AcquireRandomInfo(), GenerateEntropicChaos(), GetConfigureOptions(), GetLocaleOptions(), GetProfilesFromResourceBlock(), ProfileImage(), StringToStringInfo(), and UpdateSignature().
MagickExport void SetStringInfoLength (StringInfo * string_info, const size_t length)
Definition at line 1918 of file string.c.
References AcquireQuantumMemory(), _StringInfo::datum, GetMagickModule, _StringInfo::length, LogMagickEvent(), MagickSignature, MaxTextExtent, ResizeQuantumMemory(), ResourceLimitFatalError, _StringInfo::signature, ThrowFatalException, and TraceEvent.
Referenced by AcquireRandomInfo(), ConcatenateStringInfo(), GenerateEntropicChaos(), GetConfigureOptions(), GetLocaleOptions(), GetMagickSignature(), SignatureImage(), and SplitStringInfo().
MagickExport void SetStringInfoPath (StringInfo * string_info, const char * path)
Definition at line 1961 of file string.c.
References CopyMagickString(), GetMagickModule, LogMagickEvent(), MagickSignature, MaxTextExtent, _StringInfo::path, _StringInfo::signature, and TraceEvent.
Referenced by GetConfigureOptions(), and GetLocaleOptions().
MagickExport StringInfo* SplitStringInfo (StringInfo * string_info, const size_t offset)
Definition at line 1992 of file string.c.
References AcquireStringInfo(), _StringInfo::datum, GetMagickModule, _StringInfo::length, LogMagickEvent(), MagickSignature, MaxTextExtent, SetStringInfo(), SetStringInfoLength(), _StringInfo::signature, and TraceEvent.
MagickExport char* StringInfoToHexString (const StringInfo * string_info)
Definition at line 2074 of file string.c.
References AcquireQuantumMemory(), _StringInfo::datum, _StringInfo::length, MaxTextExtent, ResourceLimitFatalError, and ThrowFatalException.
Referenced by SignatureImage().
MagickExport char* StringInfoToString (const StringInfo * string_info)
Definition at line 2033 of file string.c.
References AcquireQuantumMemory(), _StringInfo::datum, _StringInfo::length, and MaxTextExtent.
Referenced by GetXMPProperty().
MagickExport char** StringToArgv (const char * text, int * argc)
Definition at line 2162 of file string.c.
References AcquireQuantumMemory(), AcquireString(), DestroyString(), MaxTextExtent, RelinquishMagickMemory(), ResourceLimitFatalError, and ThrowFatalException.
Referenced by ExpandFilenames(), GetHostname(), ProfileImage(), and SystemCommand().
MagickExport double* StringToArrayOfDoubles (const char * string, ssize_t * count, ExceptionInfo * exception)
Definition at line 2277 of file string.c.
References AcquireQuantumMemory(), MagickSignature, ResourceLimitFatalError, _ExceptionInfo::signature, StringToDouble(), and ThrowFatalException.
MagickExport char* StringToken (const char * delimiters, char ** string)
Definition at line 2370 of file string.c.
Referenced by FxEvaluateSubexpression().
MagickExport char** StringToList (const char * text)
Definition at line 2433 of file string.c.
References AcquireQuantumMemory(), CopyMagickString(), FormatLocaleString(), MagickMin(), MaxTextExtent, ResourceLimitFatalError, and ThrowFatalException.
Referenced by AnnotateImage(), GetDelegateCommand(), GetMultilineTypeMetrics(), IdentifyImage(), InvokeDelegate(), ListDelegateInfo(), and ListMagickInfo().
MagickExport StringInfo* StringToStringInfo (const char * string)
Definition at line 2568 of file string.c.
References AcquireStringInfo(), GetMagickModule, LogMagickEvent(), SetStringInfoDatum(), and TraceEvent.
Referenced by GenerateEntropicChaos(), and HashStringType().
MagickExport void StripString (char * message)
Definition at line 2603 of file string.c.
Referenced by FxGetSymbol(), and ListDelegateInfo().
MagickExport MagickBooleanType SubstituteString (char ** string, const char * search, const char * replace)
Definition at line 2665 of file string.c.
References CopyMagickMemory(), MagickFalse, MagickTrue, MaxTextExtent, ResizeQuantumMemory(), ResourceLimitFatalError, and ThrowFatalException.
Referenced by AcquireFxInfo(), GetEXIFProperty(), GetHostname(), LoadDelegateList(), LoadMimeList(), LoadTypeList(), ProfileImage(), and QueryColorCompliance().
Variable Documentation
const unsigned char asciimap[] static
Initial value:
=
  {
    0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b,
    0x0c, 0x0d, 0x0e, 0x0f, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17,
    0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x1d, 0x1e, 0x1f, 0x20, 0x21, 0x22, 0x23,
    0x24, 0x25, 0x26, 0x27, 0x28, 0x29, 0x2a, 0x2b, 0x2c, 0x2d, 0x2e, 0x2f,
    0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x3a, 0x3b,
    0x3c, 0x3d, 0x3e, 0x3f, 0x40, 0x61, 0x62, 0x63, 0x64, 0x65, 0x66, 0x67,
    0x68, 0x69, 0x6a, 0x6b, 0x6c, 0x6d, 0x6e, 0x6f, 0x70, 0x71, 0x72, 0x73,
    0x74, 0x75, 0x76, 0x77, 0x78, 0x79, 0x7a, 0x5b, 0x5c, 0x5d, 0x5e, 0x5f,
    0x60, 0x61, 0x62, 0x63, 0x64, 0x65, 0x66, 0x67, 0x68, 0x69, 0x6a, 0x6b,
    0x6c, 0x6d, 0x6e, 0x6f, 0x70, 0x71, 0x72, 0x73, 0x74, 0x75, 0x76, 0x77,
    0x78, 0x79, 0x7a, 0x7b, 0x7c, 0x7d, 0x7e, 0x7f, 0x80, 0x81, 0x82, 0x83,
    0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8a, 0x8b, 0x8c, 0x8d, 0x8e, 0x8f,
    0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9a, 0x9b,
    0x9c, 0x9d, 0x9e, 0x9f, 0xa0, 0xa1, 0xa2, 0xa3, 0xa4, 0xa5, 0xa6, 0xa7,
    0xa8, 0xa9, 0xaa, 0xab, 0xac, 0xad, 0xae, 0xaf, 0xb0, 0xb1, 0xb2, 0xb3,
    0xb4, 0xb5, 0xb6, 0xb7, 0xb8, 0xb9, 0xba, 0xbb, 0xbc, 0xbd, 0xbe, 0xbf,
    0xc0, 0xe1, 0xe2, 0xe3, 0xe4, 0xc5, 0xe6, 0xe7, 0xe8, 0xe9, 0xea, 0xeb,
    0xec, 0xed, 0xee, 0xef, 0xf0, 0xf1, 0xf2, 0xf3, 0xf4, 0xf5, 0xf6, 0xf7,
    0xf8, 0xf9, 0xfa, 0xdb, 0xdc, 0xdd, 0xde, 0xdf, 0xe0, 0xe1, 0xe2, 0xe3,
    0xe4, 0xe5, 0xe6, 0xe7, 0xe8, 0xe9, 0xea, 0xeb, 0xec, 0xed, 0xee, 0xef,
    0xf0, 0xf1, 0xf2, 0xf3, 0xf4, 0xf5, 0xf6, 0xf7, 0xf8, 0xf9, 0xfa, 0xfb,
    0xfc, 0xfd, 0xfe, 0xff,
  }
Definition at line 64 of file string.c.