MagickCore: _ResizeFilter Struct Reference
_ResizeFilter Struct Reference
Data Fields
double(* filter)(const double, const ResizeFilter *)
double(*)(*) window (const double, const ResizeFilter *)
double(*)(*) support
double(*)(*) window_support
double(*)(*) scale
double(*)(*) blur
double(*)(*) coefficient [7]
size_t signature
Detailed Description
Definition at line 87 of file resize.c.
Field Documentation
double(*)(*) _ResizeFilter::blur
Definition at line 92 of file resize.c.
Referenced by AcquireResizeFilter(), GetResizeFilterSupport(), and GetResizeFilterWeight().
double(*)(*) _ResizeFilter::coefficient[7]
Definition at line 92 of file resize.c.
Referenced by AcquireResizeFilter(), CubicBC(), Gaussian(), and Kaiser().
double(* _ResizeFilter::filter)(const double, const ResizeFilter *)
Definition at line 90 of file resize.c.
Referenced by AcquireResizeFilter(), and GetResizeFilterWeight().
double(*)(*) _ResizeFilter::scale
Definition at line 92 of file resize.c.
Referenced by AcquireResizeFilter(), and GetResizeFilterWeight().
size_t _ResizeFilter::signature
Definition at line 99 of file resize.c.
Referenced by AcquireResizeFilter(), DestroyResizeFilter(), GetResizeFilterSupport(), and GetResizeFilterWeight().
double(*)(*) _ResizeFilter::support
Definition at line 92 of file resize.c.
Referenced by AcquireResizeFilter(), GetResizeFilterSupport(), and Lagrange().
double(*)(*) _ResizeFilter::window(const double, const ResizeFilter *)
Definition at line 91 of file resize.c.
Referenced by AcquireResizeFilter(), and GetResizeFilterWeight().
double(*)(*) _ResizeFilter::window_support
Definition at line 92 of file resize.c.
Referenced by AcquireResizeFilter(), GetResizeFilterWeight(), and Lagrange().
The documentation for this struct was generated from the following file:
resize.c