MagickCore: threshold.h File Reference
threshold.h File Reference
Typedefs
typedef struct _ThresholdMap ThresholdMap
Functions
MagickExport Image * AdaptiveThresholdImage (const Image *, const size_t, const size_t, const double, ExceptionInfo *)
MagickExport ThresholdMap * DestroyThresholdMap (ThresholdMap *)
MagickExport ThresholdMap * GetThresholdMap (const char *, ExceptionInfo *)
MagickExport MagickBooleanType BilevelImage (Image *, const double, ExceptionInfo *)
MagickExport MagickBooleanType BlackThresholdImage (Image *, const char *, ExceptionInfo *)
MagickExport MagickBooleanType ClampImage (Image *, ExceptionInfo *)
MagickExport MagickBooleanType ListThresholdMaps (FILE *, ExceptionInfo *)
MagickExport MagickBooleanType OrderedPosterizeImage (Image *, const char *, ExceptionInfo *)
MagickExport MagickBooleanType PerceptibleImage (Image *, const double, ExceptionInfo *)
MagickExport MagickBooleanType RandomThresholdImage (Image *, const char *, ExceptionInfo *)
MagickExport MagickBooleanType WhiteThresholdImage (Image *, const char *, ExceptionInfo *)
Typedef Documentation
typedef struct _ThresholdMap ThresholdMap
Definition at line 25 of file threshold.h.
Function Documentation
MagickExport Image* AdaptiveThresholdImage (const Image * , const size_t , const size_t , const double , ExceptionInfo *)
Definition at line 175 of file threshold.c.
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), AdaptiveThresholdImageTag, CloneImage(), _Image::columns, CopyPixelTrait, _Image::debug, DestroyCacheView(), DestroyImage(), DirectClass, _Image::filename, GetCacheViewVirtualPixels(), GetMagickModule, GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelReadMask(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, MaxPixelChannels, _Image::progress_monitor, QuantumRange, QueueCacheViewAuthenticPixels(), _Image::rows, SetImageProgress(), SetImageStorageClass(), SetPixelChannel(), _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), TraceEvent, _Image::type, and UndefinedPixelTrait.
MagickExport MagickBooleanType BilevelImage (Image * , const double , ExceptionInfo *)
MagickExport MagickBooleanType BlackThresholdImage (Image * , const char * , ExceptionInfo *)
MagickExport MagickBooleanType ClampImage (Image * , ExceptionInfo *)
MagickExport ThresholdMap* DestroyThresholdMap (ThresholdMap *)
MagickExport ThresholdMap * GetThresholdMap (const char * , ExceptionInfo *)
Definition at line 866 of file threshold.c.
References DestroyConfigureOptions(), GetConfigureOptions(), GetNextValueInLinkedList(), GetStringInfoDatum(), GetStringInfoPath(), GetThresholdMapFile(), MinimalThresholdMap, and ThresholdsFilename.
Referenced by OrderedPosterizeImage().
MagickExport MagickBooleanType ListThresholdMaps (FILE * , ExceptionInfo *)
MagickExport MagickBooleanType OrderedPosterizeImage (Image * , const char * , ExceptionInfo *)
MagickExport MagickBooleanType PerceptibleImage (Image * , const double , ExceptionInfo *)
MagickExport MagickBooleanType RandomThresholdImage (Image * , const char * , ExceptionInfo *)
MagickExport MagickBooleanType WhiteThresholdImage (Image * , const char * , ExceptionInfo *)
Definition at line 1804 of file threshold.c.
References AcquireAuthenticCacheView(), _PixelInfo::alpha, _PixelInfo::black, _PixelInfo::blue, _Image::channel_mask, _GeometryInfo::chi, ChiValue, CMYKColorspace, _Image::colorspace, _PixelInfo::colorspace, _Image::columns, _Image::debug, DefaultChannels, DestroyCacheView(), DirectClass, _Image::filename, GetCacheViewAuthenticPixels(), GetMagickModule, GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelInfo(), GetPixelInfoChannel(), GetPixelIntensity(), GetPixelReadMask(), _PixelInfo::green, IsGrayColorspace(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, ParseGeometry(), PercentValue, _Image::progress_monitor, _GeometryInfo::psi, PsiValue, QuantumRange, _PixelInfo::red, _GeometryInfo::rho, _Image::rows, SetImageProgress(), SetImageStorageClass(), _GeometryInfo::sigma, SigmaValue, _Image::signature, sRGBColorspace, SyncCacheViewAuthenticPixels(), ThresholdImageTag, TraceEvent, TransformImageColorspace(), UpdatePixelTrait, _GeometryInfo::xi, and XiValue.