MagickCore: threshold.c File Reference
threshold.c File Reference
#include "MagickCore/studio.h"
#include "MagickCore/property.h"
#include "MagickCore/blob.h"
#include "MagickCore/cache-view.h"
#include "MagickCore/color.h"
#include "MagickCore/color-private.h"
#include "MagickCore/colormap.h"
#include "MagickCore/colorspace.h"
#include "MagickCore/colorspace-private.h"
#include "MagickCore/configure.h"
#include "MagickCore/constitute.h"
#include "MagickCore/decorate.h"
#include "MagickCore/draw.h"
#include "MagickCore/enhance.h"
#include "MagickCore/exception.h"
#include "MagickCore/exception-private.h"
#include "MagickCore/effect.h"
#include "MagickCore/fx.h"
#include "MagickCore/gem.h"
#include "MagickCore/geometry.h"
#include "MagickCore/image-private.h"
#include "MagickCore/list.h"
#include "MagickCore/log.h"
#include "MagickCore/memory_.h"
#include "MagickCore/monitor.h"
#include "MagickCore/monitor-private.h"
#include "MagickCore/montage.h"
#include "MagickCore/option.h"
#include "MagickCore/pixel-accessor.h"
#include "MagickCore/quantize.h"
#include "MagickCore/quantum.h"
#include "MagickCore/random_.h"
#include "MagickCore/random-private.h"
#include "MagickCore/resize.h"
#include "MagickCore/resource_.h"
#include "MagickCore/segment.h"
#include "MagickCore/shear.h"
#include "MagickCore/signature-private.h"
#include "MagickCore/string_.h"
#include "MagickCore/string-private.h"
#include "MagickCore/thread-private.h"
#include "MagickCore/threshold.h"
#include "MagickCore/token.h"
#include "MagickCore/transform.h"
#include "MagickCore/xml-tree.h"
#include "MagickCore/xml-tree-private.h"
Data Structures
struct _ThresholdMap
Macros
#define ThresholdsFilename "thresholds.xml"
#define AdaptiveThresholdImageTag "AdaptiveThreshold/Image"
#define ThresholdImageTag "Threshold/Image"
#define ThresholdImageTag "Threshold/Image"
#define ClampImageTag "Clamp/Image"
#define DitherImageTag "Dither/Image"
#define PerceptibleImageTag "Perceptible/Image"
#define ThresholdImageTag "Threshold/Image"
#define ThresholdImageTag "Threshold/Image"
Functions
static ThresholdMap * GetThresholdMapFile (const char *, const char *, const char *, ExceptionInfo *)
MagickExport Image * AdaptiveThresholdImage (const Image *image, const size_t width, const size_t height, const double bias, ExceptionInfo *exception)
MagickExport MagickBooleanType BilevelImage (Image *image, const double threshold, ExceptionInfo *exception)
MagickExport MagickBooleanType BlackThresholdImage (Image *image, const char *thresholds, ExceptionInfo *exception)
static Quantum ClampPixel (const MagickRealType value)
MagickExport MagickBooleanType ClampImage (Image *image, ExceptionInfo *exception)
MagickExport ThresholdMap * DestroyThresholdMap (ThresholdMap *map)
MagickExport ThresholdMap * GetThresholdMap (const char *map_id, ExceptionInfo *exception)
MagickBooleanType ListThresholdMapFile (FILE *file, const char *xml, const char *filename, ExceptionInfo *exception)
MagickExport MagickBooleanType ListThresholdMaps (FILE *file, ExceptionInfo *exception)
MagickExport MagickBooleanType OrderedPosterizeImage (Image *image, const char *threshold_map, ExceptionInfo *exception)
static Quantum PerceptibleThreshold (const Quantum quantum, const double epsilon)
MagickExport MagickBooleanType PerceptibleImage (Image *image, const double epsilon, ExceptionInfo *exception)
MagickExport MagickBooleanType RandomThresholdImage (Image *image, const char *thresholds, ExceptionInfo *exception)
MagickExport MagickBooleanType WhiteThresholdImage (Image *image, const char *thresholds, ExceptionInfo *exception)
Variables
static const char * MinimalThresholdMap
Macro Definition Documentation
#define AdaptiveThresholdImageTag "AdaptiveThreshold/Image"
Referenced by AdaptiveThresholdImage().
#define ClampImageTag "Clamp/Image"
Referenced by ClampImage().
#define DitherImageTag "Dither/Image"
#define PerceptibleImageTag "Perceptible/Image"
Referenced by PerceptibleImage().
#define ThresholdImageTag "Threshold/Image"
Referenced by BilevelImage(), BlackThresholdImage(), RandomThresholdImage(), and WhiteThresholdImage().
#define ThresholdImageTag "Threshold/Image"
#define ThresholdImageTag "Threshold/Image"
#define ThresholdImageTag "Threshold/Image"
#define ThresholdsFilename "thresholds.xml"
Definition at line 93 of file threshold.c.
Referenced by GetThresholdMap(), and ListThresholdMaps().
Function Documentation
MagickExport Image* AdaptiveThresholdImage (const Image * image, const size_t width, const size_t height, const double bias, ExceptionInfo * exception)
Definition at line 175 of file threshold.c.
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), AdaptiveThresholdImageTag, CloneImage(), _Image::columns, CopyPixelTrait, _Image::debug, DestroyCacheView(), DestroyImage(), DirectClass, _Image::filename, GetCacheViewVirtualPixels(), GetMagickModule, GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelReadMask(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, MaxPixelChannels, _Image::progress_monitor, QuantumRange, QueueCacheViewAuthenticPixels(), _Image::rows, SetImageProgress(), SetImageStorageClass(), SetPixelChannel(), _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), TraceEvent, _Image::type, and UndefinedPixelTrait.
MagickExport MagickBooleanType BilevelImage (Image * image, const double threshold, ExceptionInfo * exception)
Definition at line 398 of file threshold.c.
References AcquireAuthenticCacheView(), _Image::channel_mask, _Image::colorspace, _Image::columns, _Image::debug, DefaultChannels, DestroyCacheView(), DirectClass, _Image::filename, GetCacheViewAuthenticPixels(), GetMagickModule, GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelIntensity(), GetPixelReadMask(), IsGrayColorspace(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, _Image::progress_monitor, QuantumRange, _Image::rows, SetImageColorspace(), SetImageProgress(), SetImageStorageClass(), _Image::signature, sRGBColorspace, SyncCacheViewAuthenticPixels(), ThresholdImageTag, TraceEvent, and UpdatePixelTrait.
Referenced by PreviewImage(), and SetImageType().
MagickExport MagickBooleanType BlackThresholdImage (Image * image, const char * thresholds, ExceptionInfo * exception)
Definition at line 524 of file threshold.c.
References AcquireAuthenticCacheView(), _PixelInfo::alpha, _PixelInfo::black, _PixelInfo::blue, _Image::channel_mask, _GeometryInfo::chi, ChiValue, CMYKColorspace, _Image::colorspace, _PixelInfo::colorspace, _Image::columns, _Image::debug, DefaultChannels, DestroyCacheView(), DirectClass, _Image::filename, GetCacheViewAuthenticPixels(), GetMagickModule, GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelInfo(), GetPixelInfoChannel(), GetPixelIntensity(), GetPixelReadMask(), _PixelInfo::green, IsGrayColorspace(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, ParseGeometry(), PercentValue, _Image::progress_monitor, _GeometryInfo::psi, PsiValue, QuantumRange, _PixelInfo::red, _GeometryInfo::rho, _Image::rows, SetImageColorspace(), SetImageProgress(), SetImageStorageClass(), _GeometryInfo::sigma, SigmaValue, _Image::signature, sRGBColorspace, SyncCacheViewAuthenticPixels(), ThresholdImageTag, TraceEvent, UpdatePixelTrait, _GeometryInfo::xi, and XiValue.
MagickExport MagickBooleanType ClampImage (Image * image, ExceptionInfo * exception)
Definition at line 701 of file threshold.c.
References AcquireAuthenticCacheView(), ClampImageTag, ClampPixel(), _Image::colormap, _Image::colors, _Image::columns, _Image::debug, DestroyCacheView(), _Image::filename, GetCacheViewAuthenticPixels(), GetMagickModule, GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelReadMask(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, _Image::progress_monitor, PseudoClass, _PixelInfo::red, _Image::rows, SetImageProgress(), _Image::signature, _Image::storage_class, SyncCacheViewAuthenticPixels(), SyncImage(), TraceEvent, and UpdatePixelTrait.
static Quantum ClampPixel (const MagickRealType value) inline static
Definition at line 688 of file threshold.c.
References QuantumRange.
Referenced by ClampImage().
MagickExport ThresholdMap* DestroyThresholdMap (ThresholdMap * map)
Definition at line 827 of file threshold.c.
References _ThresholdMap::description, DestroyString(), _ThresholdMap::levels, _ThresholdMap::map_id, and RelinquishMagickMemory().
Referenced by GetThresholdMapFile(), and OrderedPosterizeImage().
MagickExport ThresholdMap* GetThresholdMap (const char * map_id, ExceptionInfo * exception)
Definition at line 866 of file threshold.c.
References DestroyConfigureOptions(), GetConfigureOptions(), GetNextValueInLinkedList(), GetStringInfoDatum(), GetStringInfoPath(), GetThresholdMapFile(), MinimalThresholdMap, and ThresholdsFilename.
Referenced by OrderedPosterizeImage().
static ThresholdMap * GetThresholdMapFile (const char * xml, const char * filename, const char * map_id, ExceptionInfo * exception) static
Definition at line 925 of file threshold.c.
References AcquireMagickMemory(), AcquireQuantumMemory(), ConfigureEvent, ConstantString(), _ThresholdMap::description, DestroyThresholdMap(), DestroyXMLTree(), _ThresholdMap::divisor, GetMagickModule, GetNextXMLTreeTag(), GetXMLTreeAttribute(), GetXMLTreeChild(), GetXMLTreeContent(), _ThresholdMap::height, _ThresholdMap::levels, LocaleCompare(), LogMagickEvent(), _ThresholdMap::map_id, NewXMLTree(), OptionError, ResourceLimitFatalError, StringToLong(), StringToUnsignedLong(), ThrowFatalException, ThrowMagickException(), and _ThresholdMap::width.
Referenced by GetThresholdMap().
MagickBooleanType ListThresholdMapFile (FILE * file, const char * xml, const char * filename, ExceptionInfo * exception)
Definition at line 1130 of file threshold.c.
References ConfigureEvent, DestroyXMLTree(), FormatLocaleFile(), GetMagickModule, GetNextXMLTreeTag(), GetXMLTreeAttribute(), GetXMLTreeChild(), GetXMLTreeContent(), LogMagickEvent(), MagickFalse, MagickTrue, NewXMLTree(), OptionError, and ThrowMagickException().
Referenced by ListThresholdMaps().
MagickExport MagickBooleanType ListThresholdMaps (FILE * file, ExceptionInfo * exception)
Definition at line 1214 of file threshold.c.
References DestroyConfigureOptions(), FormatLocaleFile(), GetConfigureOptions(), GetNextValueInLinkedList(), GetStringInfoDatum(), GetStringInfoPath(), ListThresholdMapFile(), MagickFalse, MagickTrue, and ThresholdsFilename.
MagickExport MagickBooleanType OrderedPosterizeImage (Image * image, const char * threshold_map, ExceptionInfo * exception)
Definition at line 1291 of file threshold.c.
References AcquireAuthenticCacheView(), ClampToQuantum(), _Image::columns, CompositePixelChannel, _Image::debug, DestroyCacheView(), DestroyThresholdMap(), DirectClass, DitherImageTag, _ThresholdMap::divisor, _Image::filename, GetCacheViewAuthenticPixels(), GetMagickModule, GetMagickToken(), GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelReadMask(), GetThresholdMap(), _ThresholdMap::height, _ThresholdMap::levels, LogMagickEvent(), MagickEpsilon, MagickFalse, MagickSignature, MagickTrue, MaxPixelChannels, MaxTextExtent, OptionError, _Image::progress_monitor, QuantumRange, QuantumScale, _Image::rows, SetImageProgress(), SetImageStorageClass(), _ExceptionInfo::signature, _Image::signature, StringToDouble(), SyncCacheViewAuthenticPixels(), ThrowMagickException(), TraceEvent, UpdatePixelTrait, and _ThresholdMap::width.
MagickExport MagickBooleanType PerceptibleImage (Image * image, const double epsilon, ExceptionInfo * exception)
Definition at line 1489 of file threshold.c.
References AcquireAuthenticCacheView(), ClampToQuantum(), _Image::colormap, _Image::colors, _Image::columns, _Image::debug, DestroyCacheView(), _Image::filename, GetCacheViewAuthenticPixels(), GetMagickModule, GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelReadMask(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, PerceptibleImageTag, PerceptibleThreshold(), _Image::progress_monitor, PseudoClass, _PixelInfo::red, _Image::rows, SetImageProgress(), _Image::signature, _Image::storage_class, SyncCacheViewAuthenticPixels(), SyncImage(), TraceEvent, and UndefinedPixelTrait.
static Quantum PerceptibleThreshold (const Quantum quantum, const double epsilon) inline static
Definition at line 1477 of file threshold.c.
Referenced by PerceptibleImage().
MagickExport MagickBooleanType RandomThresholdImage (Image * image, const char * thresholds, ExceptionInfo * exception)
Definition at line 1629 of file threshold.c.
References AcquireAuthenticCacheView(), AcquireRandomInfoThreadSet(), _Image::columns, _Image::debug, DestroyCacheView(), DestroyRandomInfoThreadSet(), DirectClass, _Image::filename, GetCacheViewAuthenticPixels(), GetMagickModule, GetOpenMPThreadId(), GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelInfo(), GetPixelReadMask(), GetPseudoRandomValue(), GetRandomSecretKey(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, ParseGeometry(), _Image::progress_monitor, QuantumRange, random_info, _GeometryInfo::rho, _Image::rows, SetImageProgress(), SetImageStorageClass(), _GeometryInfo::sigma, SigmaValue, _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), ThresholdImageTag, TraceEvent, and UpdatePixelTrait.
MagickExport MagickBooleanType WhiteThresholdImage (Image * image, const char * thresholds, ExceptionInfo * exception)
Definition at line 1804 of file threshold.c.
References AcquireAuthenticCacheView(), _PixelInfo::alpha, _PixelInfo::black, _PixelInfo::blue, _Image::channel_mask, _GeometryInfo::chi, ChiValue, CMYKColorspace, _Image::colorspace, _PixelInfo::colorspace, _Image::columns, _Image::debug, DefaultChannels, DestroyCacheView(), DirectClass, _Image::filename, GetCacheViewAuthenticPixels(), GetMagickModule, GetPixelChannelChannel(), GetPixelChannels(), GetPixelChannelTraits(), GetPixelInfo(), GetPixelInfoChannel(), GetPixelIntensity(), GetPixelReadMask(), _PixelInfo::green, IsGrayColorspace(), LogMagickEvent(), MagickFalse, MagickSignature, MagickTrue, ParseGeometry(), PercentValue, _Image::progress_monitor, _GeometryInfo::psi, PsiValue, QuantumRange, _PixelInfo::red, _GeometryInfo::rho, _Image::rows, SetImageProgress(), SetImageStorageClass(), _GeometryInfo::sigma, SigmaValue, _Image::signature, sRGBColorspace, SyncCacheViewAuthenticPixels(), ThresholdImageTag, TraceEvent, TransformImageColorspace(), UpdatePixelTrait, _GeometryInfo::xi, and XiValue.
Variable Documentation
const char* MinimalThresholdMap static
Initial value:
=
    "<?xml version=\"1.0\"?>"
    "<thresholds>"
    "  <threshold map=\"threshold\" alias=\"1x1\">"
    "    <description>Threshold 1x1 (non-dither)</description>"
    "    <levels width=\"1\" height=\"1\" divisor=\"2\">"
    "        1"
    "    </levels>"
    "  </threshold>"
    "  <threshold map=\"checks\" alias=\"2x1\">"
    "    <description>Checkerboard 2x1 (dither)</description>"
    "    <levels width=\"2\" height=\"2\" divisor=\"3\">"
    "       1 2"
    "       2 1"
    "    </levels>"
    "  </threshold>"
    "</thresholds>"
Definition at line 117 of file threshold.c.
Referenced by GetThresholdMap().