MagickCore: timer.c File Reference
timer.c File Reference
#include "MagickCore/studio.h"
#include "MagickCore/exception.h"
#include "MagickCore/exception-private.h"
#include "MagickCore/log.h"
#include "MagickCore/memory_.h"
#include "MagickCore/nt-base-private.h"
#include "MagickCore/timer.h"
Macros
#define CLK_TCK sysconf(_SC_CLK_TCK)
Functions
static double UserTime (void)
static void StopTimer (TimerInfo *)
MagickExport TimerInfo * AcquireTimerInfo (void)
MagickExport MagickBooleanType ContinueTimer (TimerInfo *time_info)
MagickExport TimerInfo * DestroyTimerInfo (TimerInfo *timer_info)
static double ElapsedTime (void)
MagickExport double GetElapsedTime (TimerInfo *time_info)
MagickExport void GetTimerInfo (TimerInfo *time_info)
MagickExport double GetUserTime (TimerInfo *time_info)
MagickExport void ResetTimer (TimerInfo *time_info)
MagickExport void StartTimer (TimerInfo *time_info, const MagickBooleanType reset)
Macro Definition Documentation
#define CLK_TCK sysconf(_SC_CLK_TCK)
Definition at line 58 of file timer.c.
Referenced by ElapsedTime(), and UserTime().
Function Documentation
MagickExport TimerInfo* AcquireTimerInfo (void)
Definition at line 89 of file timer.c.
References AcquireMagickMemory(), GetTimerInfo(), MagickSignature, ResetMagickMemory(), ResourceLimitFatalError, _TimerInfo::signature, and ThrowFatalException.
MagickExport MagickBooleanType ContinueTimer (TimerInfo * time_info)
Definition at line 126 of file timer.c.
References _TimerInfo::elapsed, MagickFalse, MagickSignature, MagickTrue, RunningTimerState, _TimerInfo::signature, _Timer::start, _TimerInfo::state, _Timer::stop, StoppedTimerState, _Timer::total, UndefinedTimerState, and _TimerInfo::user.
Referenced by LogMagickEventList().
MagickExport TimerInfo* DestroyTimerInfo (TimerInfo * timer_info)
Definition at line 164 of file timer.c.
References MagickSignature, RelinquishMagickMemory(), and _TimerInfo::signature.
static double ElapsedTime (void) static
Definition at line 192 of file timer.c.
References CLK_TCK.
Referenced by StartTimer(), and StopTimer().
MagickExport double GetElapsedTime (TimerInfo * time_info)
Definition at line 232 of file timer.c.
References _TimerInfo::elapsed, MagickSignature, RunningTimerState, _TimerInfo::signature, _TimerInfo::state, StopTimer(), _Timer::total, and UndefinedTimerState.
Referenced by IdentifyImage(), and TranslateEvent().
MagickExport void GetTimerInfo (TimerInfo * time_info)
Definition at line 265 of file timer.c.
References MagickSignature, MagickTrue, ResetMagickMemory(), _TimerInfo::signature, StartTimer(), _TimerInfo::state, and UndefinedTimerState.
Referenced by AcquireImage(), AcquireTimerInfo(), CloneImage(), IdentifyImage(), LoadLogList(), and LoadLogLists().
MagickExport double GetUserTime (TimerInfo * time_info)
Definition at line 301 of file timer.c.
References MagickSignature, RunningTimerState, _TimerInfo::signature, _TimerInfo::state, StopTimer(), _Timer::total, UndefinedTimerState, and _TimerInfo::user.
Referenced by IdentifyImage(), and TranslateEvent().
MagickExport void ResetTimer (TimerInfo * time_info)
Definition at line 334 of file timer.c.
References _TimerInfo::elapsed, MagickSignature, _TimerInfo::signature, _Timer::stop, StopTimer(), and _TimerInfo::user.
Referenced by PingImage().
MagickExport void StartTimer (TimerInfo * time_info, const MagickBooleanType reset)
Definition at line 369 of file timer.c.
References _TimerInfo::elapsed, ElapsedTime(), MagickFalse, MagickSignature, RunningTimerState, _TimerInfo::signature, _Timer::start, _TimerInfo::state, _Timer::total, _TimerInfo::user, and UserTime().
Referenced by GetTimerInfo().
static void StopTimer (TimerInfo * time_info) static
Definition at line 411 of file timer.c.
References _TimerInfo::elapsed, ElapsedTime(), MagickEpsilon, MagickSignature, RunningTimerState, _TimerInfo::signature, _Timer::start, _TimerInfo::state, _Timer::stop, StoppedTimerState, _Timer::total, _TimerInfo::user, and UserTime().
Referenced by GetElapsedTime(), GetUserTime(), and ResetTimer().
static double UserTime (void) static
Definition at line 446 of file timer.c.
References CLK_TCK.
Referenced by StartTimer(), and StopTimer().