MagickCore: timer.h File Reference
timer.h File Reference
Data Structures
struct _Timer
struct _TimerInfo
Typedefs
typedef struct _Timer Timer
typedef struct _TimerInfo TimerInfo
Enumerations
enum TimerState { UndefinedTimerState, StoppedTimerState, RunningTimerState }
Functions
MagickExport double GetElapsedTime (TimerInfo *)
MagickExport double GetUserTime (TimerInfo *)
MagickExport MagickBooleanType ContinueTimer (TimerInfo *)
MagickExport TimerInfo * AcquireTimerInfo (void)
MagickExport TimerInfo * DestroyTimerInfo (TimerInfo *)
MagickExport void GetTimerInfo (TimerInfo *)
MagickExport void ResetTimer (TimerInfo *)
MagickExport void StartTimer (TimerInfo *, const MagickBooleanType)
Typedef Documentation
typedef struct _Timer Timer
typedef struct _TimerInfo TimerInfo
Enumeration Type Documentation
enum TimerState
Enumerator
UndefinedTimerState
StoppedTimerState
RunningTimerState
Definition at line 25 of file timer.h.
Function Documentation
MagickExport TimerInfo* AcquireTimerInfo (void)
MagickExport MagickBooleanType ContinueTimer (TimerInfo *)
Definition at line 126 of file timer.c.
References _TimerInfo::elapsed, MagickFalse, MagickSignature, MagickTrue, RunningTimerState, _TimerInfo::signature, _Timer::start, _TimerInfo::state, _Timer::stop, StoppedTimerState, _Timer::total, UndefinedTimerState, and _TimerInfo::user.
Referenced by LogMagickEventList().
MagickExport TimerInfo * DestroyTimerInfo (TimerInfo *)
Definition at line 164 of file timer.c.
References MagickSignature, RelinquishMagickMemory(), and _TimerInfo::signature.
MagickExport double GetElapsedTime (TimerInfo *)
MagickExport void GetTimerInfo (TimerInfo *)
MagickExport double GetUserTime (TimerInfo *)
Definition at line 301 of file timer.c.
References MagickSignature, RunningTimerState, _TimerInfo::signature, _TimerInfo::state, StopTimer(), _Timer::total, UndefinedTimerState, and _TimerInfo::user.
Referenced by IdentifyImage(), and TranslateEvent().
MagickExport void ResetTimer (TimerInfo *)
MagickExport void StartTimer (TimerInfo * , const MagickBooleanType)
Definition at line 369 of file timer.c.
References _TimerInfo::elapsed, ElapsedTime(), MagickFalse, MagickSignature, RunningTimerState, _TimerInfo::signature, _Timer::start, _TimerInfo::state, _Timer::total, _TimerInfo::user, and UserTime().
Referenced by GetTimerInfo().