MagickCore: token.h File Reference
token.h File Reference
Typedefs
typedef struct _TokenInfo TokenInfo
Functions
MagickExport int Tokenizer (TokenInfo *, const unsigned int, char *, const size_t, const char *, const char *, const char *, const char *, const char, char *, int *, char *)
MagickExport MagickBooleanType GlobExpression (const char *, const char *, const MagickBooleanType)
MagickExport TokenInfo * AcquireTokenInfo (void)
MagickExport TokenInfo * DestroyTokenInfo (TokenInfo *)
MagickExport void GetMagickToken (const char *, const char **, char *)
Typedef Documentation
typedef struct _TokenInfo TokenInfo
Definition at line 28 of file token.h.
Function Documentation
MagickExport TokenInfo* AcquireTokenInfo (void)
MagickExport TokenInfo * DestroyTokenInfo (TokenInfo *)
Definition at line 129 of file token.c.
References GetMagickModule, LogMagickEvent(), MagickSignature, RelinquishMagickMemory(), _TokenInfo::signature, and TraceEvent.
MagickExport void GetMagickToken (const char * , const char ** , char *)
Definition at line 169 of file token.c.
References CopyMagickString(), DirectorySeparator, LocaleNCompare(), MaxTextExtent, and StringToDouble().
Referenced by AcquireKernelInfo(), ChannelFxImage(), ColorDecisionListImage(), DrawImage(), LoadCoderList(), LoadColorList(), LoadConfigureList(), LoadDelegateList(), LoadLocaleList(), LoadLogList(), LoadMagicList(), LoadPolicyList(), LoadTypeList(), OrderedPosterizeImage(), ParseAffineGeometry(), ParseKernelArray(), ParseKernelName(), ParsePixelChannelOption(), and TracePath().
MagickExport MagickBooleanType GlobExpression (const char * , const char * , const MagickBooleanType)
Definition at line 320 of file token.c.
References AcquireExceptionInfo(), AcquireImageInfo(), CopyMagickString(), DestroyExceptionInfo(), DestroyImageInfo(), _ImageInfo::filename, GetUTFCode(), GetUTFOctets(), GlobExpression(), LocaleCompare(), MagickFalse, MagickTrue, MaxTextExtent, and SetImageInfo().
Referenced by GetCoderInfoList(), GetCoderList(), GetColorInfoList(), GetColorList(), GetConfigureInfoList(), GetConfigureList(), GetDelegateInfoList(), GetDelegateList(), GetLocaleInfoList(), GetLocaleList(), GetLogInfoList(), GetLogList(), GetMagicInfoList(), GetMagickInfoList(), GetMagickList(), GetMagicList(), GetMimeInfo(), GetMimeInfoList(), GetMimeList(), GetPolicyInfoList(), GetPolicyList(), GetTypeInfoList(), GetTypeList(), GlobExpression(), InterpretImageProperties(), IsRightsAuthorized(), ListFiles(), LoadColorList(), and ProfileImage().
MagickExport int Tokenizer (TokenInfo * , const unsigned int, char * , const size_t , const char * , const char * , const char * , const char * , const char , char * , int * , char *)
Definition at line 833 of file token.c.
References _TokenInfo::flag, IN_OZONE, IN_QUOTE, IN_TOKEN, IN_WHITE, MagickFalse, MagickTrue, _TokenInfo::offset, _TokenInfo::quote, sindex(), _TokenInfo::state, and StoreToken().