MagickCore: token.c File Reference
token.c File Reference
#include "MagickCore/studio.h"
#include "MagickCore/exception.h"
#include "MagickCore/exception-private.h"
#include "MagickCore/image.h"
#include "MagickCore/memory_.h"
#include "MagickCore/string_.h"
#include "MagickCore/string-private.h"
#include "MagickCore/token.h"
#include "MagickCore/token-private.h"
#include "MagickCore/utility.h"
#include "MagickCore/utility-private.h"
Data Structures
struct _TokenInfo
Macros
#define IN_WHITE 0
#define IN_TOKEN 1
#define IN_QUOTE 2
#define IN_OZONE 3
Functions
MagickExport TokenInfo * AcquireTokenInfo (void)
MagickExport TokenInfo * DestroyTokenInfo (TokenInfo *token_info)
MagickExport void GetMagickToken (const char *start, const char **end, char *token)
MagickExport MagickBooleanType GlobExpression (const char *expression, const char *pattern, const MagickBooleanType case_insensitive)
MagickPrivate MagickBooleanType IsGlob (const char *path)
static ssize_t sindex (int c, const char *string)
static void StoreToken (TokenInfo *token_info, char *string, size_t max_token_length, int c)
MagickExport int Tokenizer (TokenInfo *token_info, const unsigned flag, char *token, const size_t max_token_length, const char *line, const char *white, const char *break_set, const char *quote, const char escape, char *breaker, int *next, char *quoted)
Macro Definition Documentation
#define IN_OZONE 3
Definition at line 790 of file token.c.
Referenced by Tokenizer().
#define IN_QUOTE 2
Definition at line 789 of file token.c.
Referenced by StoreToken(), and Tokenizer().
#define IN_TOKEN 1
Definition at line 788 of file token.c.
Referenced by Tokenizer().
#define IN_WHITE 0
Definition at line 787 of file token.c.
Referenced by Tokenizer().
Function Documentation
MagickExport TokenInfo* AcquireTokenInfo (void)
Definition at line 94 of file token.c.
References AcquireMagickMemory(), MagickSignature, ResourceLimitFatalError, _TokenInfo::signature, and ThrowFatalException.
MagickExport TokenInfo* DestroyTokenInfo (TokenInfo * token_info)
Definition at line 129 of file token.c.
References GetMagickModule, LogMagickEvent(), MagickSignature, RelinquishMagickMemory(), _TokenInfo::signature, and TraceEvent.
MagickExport void GetMagickToken (const char * start, const char ** end, char * token)
Definition at line 169 of file token.c.
References CopyMagickString(), DirectorySeparator, LocaleNCompare(), MaxTextExtent, and StringToDouble().
Referenced by AcquireKernelInfo(), ChannelFxImage(), ColorDecisionListImage(), DrawImage(), LoadCoderList(), LoadColorList(), LoadConfigureList(), LoadDelegateList(), LoadLocaleList(), LoadLogList(), LoadMagicList(), LoadPolicyList(), LoadTypeList(), OrderedPosterizeImage(), ParseAffineGeometry(), ParseKernelArray(), ParseKernelName(), ParsePixelChannelOption(), and TracePath().
MagickExport MagickBooleanType GlobExpression (const char * expression, const char * pattern, const MagickBooleanType case_insensitive)
Definition at line 320 of file token.c.
References AcquireExceptionInfo(), AcquireImageInfo(), CopyMagickString(), DestroyExceptionInfo(), DestroyImageInfo(), _ImageInfo::filename, GetUTFCode(), GetUTFOctets(), GlobExpression(), LocaleCompare(), MagickFalse, MagickTrue, MaxTextExtent, and SetImageInfo().
Referenced by GetCoderInfoList(), GetCoderList(), GetColorInfoList(), GetColorList(), GetConfigureInfoList(), GetConfigureList(), GetDelegateInfoList(), GetDelegateList(), GetLocaleInfoList(), GetLocaleList(), GetLogInfoList(), GetLogList(), GetMagicInfoList(), GetMagickInfoList(), GetMagickList(), GetMagicList(), GetMimeInfo(), GetMimeInfoList(), GetMimeList(), GetPolicyInfoList(), GetPolicyList(), GetTypeInfoList(), GetTypeList(), GlobExpression(), InterpretImageProperties(), IsRightsAuthorized(), ListFiles(), LoadColorList(), and ProfileImage().
MagickPrivate MagickBooleanType IsGlob (const char * path)
Definition at line 594 of file token.c.
References IsPathAccessible(), MagickFalse, and MagickTrue.
Referenced by ExpandFilenames(), and InterpretImageProperties().
static ssize_t sindex (int c, const char * string) static
Definition at line 792 of file token.c.
Referenced by Tokenizer().
static void StoreToken (TokenInfo * token_info, char * string, size_t max_token_length, int c) static
Definition at line 803 of file token.c.
References _TokenInfo::flag, IN_QUOTE, _TokenInfo::offset, and _TokenInfo::state.
Referenced by Tokenizer().
MagickExport int Tokenizer (TokenInfo * token_info, const unsigned flag, char * token, const size_t max_token_length, const char * line, const char * white, const char * break_set, const char * quote, const char escape, char * breaker, int * next, char * quoted)
Definition at line 833 of file token.c.
References _TokenInfo::flag, IN_OZONE, IN_QUOTE, IN_TOKEN, IN_WHITE, MagickFalse, MagickTrue, _TokenInfo::offset, _TokenInfo::quote, sindex(), _TokenInfo::state, and StoreToken().