MagickCore: type.h File Reference
type.h File Reference
Data Structures
struct _TypeInfo
Typedefs
typedef struct _TypeInfo TypeInfo
Enumerations
enum StretchType {
UndefinedStretch, NormalStretch, UltraCondensedStretch, ExtraCondensedStretch,
CondensedStretch, SemiCondensedStretch, SemiExpandedStretch, ExpandedStretch,
ExtraExpandedStretch, UltraExpandedStretch, AnyStretch
}
enum StyleType {
UndefinedStyle, NormalStyle, ItalicStyle, ObliqueStyle,
AnyStyle
}
Functions
MagickExport char ** GetTypeList (const char *, size_t *, ExceptionInfo *)
MagickExport MagickBooleanType ListTypeInfo (FILE *, ExceptionInfo *)
MagickExport const TypeInfo * GetTypeInfo (const char *, ExceptionInfo *)
MagickExport const TypeInfo * GetTypeInfoByFamily (const char *, const StyleType, const StretchType, const size_t, ExceptionInfo *)
MagickExport const TypeInfo ** GetTypeInfoList (const char *, size_t *, ExceptionInfo *)
Typedef Documentation
typedef struct _TypeInfo TypeInfo
Enumeration Type Documentation
enum StretchType
Enumerator
UndefinedStretch
NormalStretch
UltraCondensedStretch
ExtraCondensedStretch
CondensedStretch
SemiCondensedStretch
SemiExpandedStretch
ExpandedStretch
ExtraExpandedStretch
UltraExpandedStretch
AnyStretch
Definition at line 25 of file type.h.
enum StyleType
Enumerator
UndefinedStyle
NormalStyle
ItalicStyle
ObliqueStyle
AnyStyle
Definition at line 40 of file type.h.
Function Documentation
MagickExport const TypeInfo* GetTypeInfo (const char * , ExceptionInfo *)
MagickExport const TypeInfo * GetTypeInfoByFamily (const char * , const StyleType , const StretchType , const size_t , ExceptionInfo *)
MagickExport const TypeInfo ** GetTypeInfoList (const char * , size_t * , ExceptionInfo *)
Definition at line 459 of file type.c.
References AcquireQuantumMemory(), GetMagickModule, GetNextValueInSplayTree(), GetNumberOfNodesInSplayTree(), GetTypeInfo(), GlobExpression(), LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, _TypeInfo::name, ResetSplayTreeIterator(), _TypeInfo::stealth, TraceEvent, type_list, type_semaphore, TypeInfoCompare(), and UnlockSemaphoreInfo().
Referenced by ListTypeInfo().
MagickExport char** GetTypeList (const char * , size_t * , ExceptionInfo *)
Definition at line 552 of file type.c.
References AcquireQuantumMemory(), ConstantString(), GetMagickModule, GetNextValueInSplayTree(), GetNumberOfNodesInSplayTree(), GetTypeInfo(), GlobExpression(), LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, _TypeInfo::name, ResetSplayTreeIterator(), _TypeInfo::stealth, TraceEvent, type_list, type_semaphore, TypeCompare(), and UnlockSemaphoreInfo().
MagickExport MagickBooleanType ListTypeInfo (FILE * , ExceptionInfo *)
Definition at line 832 of file type.c.
References CommandOptionToMnemonic(), _TypeInfo::family, FormatLocaleFile(), FormatLocaleString(), GetTypeInfoList(), _TypeInfo::glyphs, LocaleCompare(), MagickFalse, MagickStretchOptions, MagickStyleOptions, MagickTrue, MaxTextExtent, _TypeInfo::name, _TypeInfo::path, RelinquishMagickMemory(), and _TypeInfo::weight.