MagickCore: type.c File Reference
type.c File Reference
#include "MagickCore/studio.h"
#include "MagickCore/blob.h"
#include "MagickCore/client.h"
#include "MagickCore/configure.h"
#include "MagickCore/draw.h"
#include "MagickCore/exception.h"
#include "MagickCore/exception-private.h"
#include "MagickCore/hashmap.h"
#include "MagickCore/log.h"
#include "MagickCore/memory_.h"
#include "MagickCore/nt-feature.h"
#include "MagickCore/nt-base-private.h"
#include "MagickCore/option.h"
#include "MagickCore/semaphore.h"
#include "MagickCore/splay-tree.h"
#include "MagickCore/string_.h"
#include "MagickCore/string-private.h"
#include "MagickCore/type.h"
#include "MagickCore/type-private.h"
#include "MagickCore/token.h"
#include "MagickCore/utility.h"
#include "MagickCore/utility-private.h"
#include "MagickCore/xml-tree.h"
Macros
#define MagickTypeFilename "type.xml"
Functions
static MagickBooleanType InitializeTypeList (ExceptionInfo *)
static MagickBooleanType LoadTypeLists (const char *, ExceptionInfo *)
MagickExport const TypeInfo * GetTypeInfo (const char *name, ExceptionInfo *exception)
static size_t MagickMax (const size_t x, const size_t y)
static size_t MagickMin (const size_t x, const size_t y)
MagickExport const TypeInfo * GetTypeInfoByFamily (const char *family, const StyleType style, const StretchType stretch, const size_t weight, ExceptionInfo *exception)
static int TypeInfoCompare (const void *x, const void *y)
MagickExport const TypeInfo ** GetTypeInfoList (const char *pattern, size_t *number_fonts, ExceptionInfo *exception)
static int TypeCompare (const void *x, const void *y)
MagickExport char ** GetTypeList (const char *pattern, size_t *number_fonts, ExceptionInfo *exception)
MagickExport MagickBooleanType ListTypeInfo (FILE *file, ExceptionInfo *exception)
static void * DestroyTypeNode (void *type_info)
static MagickBooleanType LoadTypeList (const char *xml, const char *filename, const size_t depth, ExceptionInfo *exception)
MagickPrivate MagickBooleanType TypeComponentGenesis (void)
MagickPrivate void TypeComponentTerminus (void)
Variables
static const char * TypeMap
static SemaphoreInfo * type_semaphore = (SemaphoreInfo *) NULL
static volatile MagickBooleanType instantiate_type = MagickFalse
static SplayTreeInfo * type_list = (SplayTreeInfo *) NULL
Macro Definition Documentation
#define MagickTypeFilename "type.xml"
Definition at line 101 of file type.c.
Referenced by InitializeTypeList().
Function Documentation
static void* DestroyTypeNode (void * type_info) static
Definition at line 927 of file type.c.
References _TypeInfo::description, DestroyString(), _TypeInfo::encoding, _TypeInfo::family, _TypeInfo::format, _TypeInfo::foundry, _TypeInfo::glyphs, _TypeInfo::metrics, _TypeInfo::name, _TypeInfo::path, and RelinquishMagickMemory().
Referenced by LoadTypeList().
MagickExport const TypeInfo* GetTypeInfo (const char * name, ExceptionInfo * exception)
Definition at line 158 of file type.c.
References GetNextValueInSplayTree(), GetNumberOfNodesInSplayTree(), GetValueFromSplayTree(), InitializeTypeList(), instantiate_type, LocaleCompare(), MagickFalse, ResetSplayTreeIterator(), and type_list.
Referenced by GetTypeInfoByFamily(), GetTypeInfoList(), GetTypeList(), and RenderType().
MagickExport const TypeInfo* GetTypeInfoByFamily (const char * family, const StyleType style, const StretchType stretch, const size_t weight, ExceptionInfo * exception)
Definition at line 227 of file type.c.
References AnyStretch, AnyStyle, _TypeInfo::family, GetMagickModule, GetNextValueInSplayTree(), GetTypeInfo(), ItalicStyle, LocaleCompare(), LockSemaphoreInfo(), MagickMax(), MagickMin(), NormalStretch, ObliqueStyle, ResetSplayTreeIterator(), _TypeInfo::stretch, _TypeInfo::style, ThrowMagickException(), type_list, type_semaphore, TypeError, UltraExpandedStretch, UndefinedStretch, UndefinedStyle, UnlockSemaphoreInfo(), and _TypeInfo::weight.
Referenced by RenderType().
MagickExport const TypeInfo** GetTypeInfoList (const char * pattern, size_t * number_fonts, ExceptionInfo * exception)
Definition at line 459 of file type.c.
References AcquireQuantumMemory(), GetMagickModule, GetNextValueInSplayTree(), GetNumberOfNodesInSplayTree(), GetTypeInfo(), GlobExpression(), LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, _TypeInfo::name, ResetSplayTreeIterator(), _TypeInfo::stealth, TraceEvent, type_list, type_semaphore, TypeInfoCompare(), and UnlockSemaphoreInfo().
Referenced by ListTypeInfo().
MagickExport char** GetTypeList (const char * pattern, size_t * number_fonts, ExceptionInfo * exception)
Definition at line 552 of file type.c.
References AcquireQuantumMemory(), ConstantString(), GetMagickModule, GetNextValueInSplayTree(), GetNumberOfNodesInSplayTree(), GetTypeInfo(), GlobExpression(), LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, _TypeInfo::name, ResetSplayTreeIterator(), _TypeInfo::stealth, TraceEvent, type_list, type_semaphore, TypeCompare(), and UnlockSemaphoreInfo().
static MagickBooleanType InitializeTypeList (ExceptionInfo * exception) static
Definition at line 783 of file type.c.
References AcquireSemaphoreInfo(), instantiate_type, LoadTypeLists(), LockSemaphoreInfo(), MagickFalse, MagickTrue, MagickTypeFilename, NTLoadTypeLists(), type_semaphore, and UnlockSemaphoreInfo().
Referenced by GetTypeInfo().
MagickExport MagickBooleanType ListTypeInfo (FILE * file, ExceptionInfo * exception)
Definition at line 832 of file type.c.
References CommandOptionToMnemonic(), _TypeInfo::family, FormatLocaleFile(), FormatLocaleString(), GetTypeInfoList(), _TypeInfo::glyphs, LocaleCompare(), MagickFalse, MagickStretchOptions, MagickStyleOptions, MagickTrue, MaxTextExtent, _TypeInfo::name, _TypeInfo::path, RelinquishMagickMemory(), and _TypeInfo::weight.
static MagickBooleanType LoadTypeList (const char * xml, const char * filename, const size_t depth, ExceptionInfo * exception) static
Definition at line 954 of file type.c.
References AcquireExceptionInfo(), AcquireMagickMemory(), AcquireString(), AddValueToSplayTree(), CompareSplayTreeString(), ConcatenateMagickString(), ConfigureError, ConfigureEvent, ConstantString(), CopyMagickString(), _TypeInfo::description, DestroyExceptionInfo(), DestroyString(), DestroyTypeNode(), DirectorySeparator, _TypeInfo::encoding, _TypeInfo::face, _TypeInfo::family, FileToString(), _TypeInfo::format, _TypeInfo::foundry, GetMagickModule, GetMagickToken(), GetPathComponent(), _TypeInfo::glyphs, HeadPath, IsPathAccessible(), IsStringTrue(), LocaleCompare(), LocaleNCompare(), LogMagickEvent(), MagickFalse, MagickSignature, MagickStretchOptions, MagickStyleOptions, MagickTrue, MaxTextExtent, _TypeInfo::metrics, _TypeInfo::name, NewSplayTree(), ParseCommandOption(), _TypeInfo::path, RelinquishMagickMemory(), ResetMagickMemory(), ResourceLimitError, ResourceLimitFatalError, _TypeInfo::signature, _TypeInfo::stealth, _TypeInfo::stretch, StringToUnsignedLong(), _TypeInfo::style, SubstituteString(), ThrowFatalException, ThrowFileException, ThrowMagickException(), and _TypeInfo::weight.
Referenced by LoadTypeLists().
static MagickBooleanType LoadTypeLists (const char * filename, ExceptionInfo * exception)
Definition at line 1290 of file type.c.
References CopyMagickString(), DestroyConfigureOptions(), DestroyString(), DirectorySeparator, FileToString(), FormatLocaleString(), GetConfigureOptions(), GetEnvironmentValue(), GetNextValueInLinkedList(), GetNumberOfNodesInSplayTree(), GetStringInfoDatum(), GetStringInfoPath(), LoadTypeList(), MagickFalse, MagickTrue, MaxTextExtent, and TypeMap.
Referenced by InitializeTypeList().
static size_t MagickMax (const size_t x, const size_t y) inline static
Definition at line 213 of file type.c.
Referenced by GetTypeInfoByFamily().
static size_t MagickMin (const size_t x, const size_t y) inline static
Definition at line 220 of file type.c.
Referenced by GetTypeInfoByFamily().
static int TypeCompare (const void * x, const void * y) static
Definition at line 537 of file type.c.
References LocaleCompare().
Referenced by GetTypeList().
MagickPrivate MagickBooleanType TypeComponentGenesis (void)
Definition at line 1365 of file type.c.
References AcquireSemaphoreInfo(), MagickTrue, and type_semaphore.
Referenced by MagickCoreGenesis().
MagickPrivate void TypeComponentTerminus (void)
Definition at line 1389 of file type.c.
References AcquireSemaphoreInfo(), DestroySemaphoreInfo(), DestroySplayTree(), instantiate_type, LockSemaphoreInfo(), MagickFalse, type_semaphore, and UnlockSemaphoreInfo().
Referenced by MagickCoreTerminus().
static int TypeInfoCompare (const void * x, const void * y) static
Definition at line 442 of file type.c.
References LocaleCompare().
Referenced by GetTypeInfoList().
Variable Documentation
volatile MagickBooleanType instantiate_type = MagickFalse static
Definition at line 121 of file type.c.
Referenced by GetTypeInfo(), InitializeTypeList(), and TypeComponentTerminus().
SplayTreeInfo* type_list = (SplayTreeInfo *) NULL static
Definition at line 124 of file type.c.
Referenced by GetTypeInfo(), GetTypeInfoByFamily(), GetTypeInfoList(), and GetTypeList().
SemaphoreInfo* type_semaphore = (SemaphoreInfo *) NULL static
Definition at line 118 of file type.c.
Referenced by GetTypeInfoByFamily(), GetTypeInfoList(), GetTypeList(), InitializeTypeList(), TypeComponentGenesis(), and TypeComponentTerminus().
const char* TypeMap static
Initial value:
= (const char *)
    "<?xml version=\"1.0\"?>"
    "<typemap>"
    "  <type stealth=\"True\" name=\"fixed\" family=\"helvetica\"/>"
    "  <type stealth=\"True\" name=\"helvetica\" family=\"helvetica\"/>"
    "</typemap>"
Definition at line 107 of file type.c.
Referenced by LoadTypeLists().