MagickCore: utility.h File Reference
utility.h File Reference
Enumerations
enum PathType {
UndefinedPath, MagickPath, RootPath, HeadPath,
TailPath, BasePath, ExtensionPath, SubimagePath,
CanonicalPath
}
Functions
MagickExport char * Base64Encode (const unsigned char *, const size_t, size_t *)
MagickExport int SystemCommand (const MagickBooleanType, const MagickBooleanType, const char *, ExceptionInfo *)
MagickExport MagickBooleanType AcquireUniqueFilename (char *)
MagickExport MagickBooleanType AcquireUniqueSymbolicLink (const char *, char *)
MagickExport MagickBooleanType ExpandFilenames (int *, char ***)
MagickExport MagickBooleanType GetPathAttributes (const char *, void *)
MagickExport MagickBooleanType IsPathAccessible (const char *)
MagickExport size_t MultilineCensus (const char *)
MagickExport unsigned char * Base64Decode (const char *, size_t *)
MagickExport void AppendImageFormat (const char *, char *)
MagickExport void GetPathComponent (const char *, PathType, char *)
Enumeration Type Documentation
enum PathType
Enumerator
UndefinedPath
MagickPath
RootPath
HeadPath
TailPath
BasePath
ExtensionPath
SubimagePath
CanonicalPath
Definition at line 25 of file utility.h.
Function Documentation
MagickExport MagickBooleanType AcquireUniqueFilename (char *)
MagickExport MagickBooleanType AcquireUniqueSymbolicLink (const char * , char *)
MagickExport void AppendImageFormat (const char * , char *)
MagickExport unsigned char* Base64Decode (const char * , size_t *)
Definition at line 339 of file utility.c.
References AcquireQuantumMemory(), Base64, GetMagickModule, LogMagickEvent(), RelinquishMagickMemory(), and TraceEvent.
Referenced by ReadInlineImage().
MagickExport char* Base64Encode (const unsigned char * , const size_t , size_t *)
Definition at line 493 of file utility.c.
References AcquireQuantumMemory(), Base64, GetMagickModule, LogMagickEvent(), and TraceEvent.
Referenced by CanonicalXMLContent().
MagickExport MagickBooleanType ExpandFilenames (int * , char ***)
MagickExport MagickBooleanType GetPathAttributes (const char * , void *)
MagickExport void GetPathComponent (const char * , PathType , char *)
Definition at line 1198 of file utility.c.
References BasePath, CanonicalPath, CopyMagickMemory(), CopyMagickString(), ExtensionPath, GetMagickModule, HeadPath, IsBasenameSeparator, IsGeometry(), IsMagickConflict(), IsPathAccessible(), IsPathDirectory(), IsSceneGeometry(), LogMagickEvent(), MagickFalse, MagickPath, MaxTextExtent, RootPath, SubimagePath, TailPath, TraceEvent, and UndefinedPath.
Referenced by AddPathToXMLTree(), AppendImageFormat(), ChopPathComponents(), ExpandFilenames(), GetMagickProperty(), GetMagickPropertyLetter(), GetXMLTreePath(), IdentifyImage(), LoadCoderList(), LoadColorList(), LoadConfigureList(), LoadDelegateList(), LoadLocaleList(), LoadLogList(), LoadMagicList(), LoadMimeList(), LoadPolicyList(), LoadTypeList(), MagickCoreGenesis(), OpenBlob(), ReadImage(), SetImageInfo(), ThrowMagickExceptionList(), and WriteImage().
MagickExport MagickBooleanType IsPathAccessible (const char *)
Definition at line 1434 of file utility.c.
References access_utf8(), GetPathAttributes(), MagickFalse, MagickTrue, and S_ISREG.
Referenced by GetExecutionPath(), GetMagickHomeURL(), GetPathComponent(), InterpretImageProperties(), IsGlob(), LoadTypeList(), LogMagickEventList(), MagickCoreGenesis(), ReadImage(), RenderType(), and WriteImage().
MagickExport size_t MultilineCensus (const char *)
Definition at line 1749 of file utility.c.
Referenced by MontageImageList().
MagickExport int SystemCommand (const MagickBooleanType , const MagickBooleanType , const char * , ExceptionInfo *)
Definition at line 1924 of file utility.c.
References AcquireString(), ConcatenateMagickString(), DelegateError, DelegatePolicyDomain, DestroyString(), ExecutePolicyRights, FormatLocaleFile(), GetMagickModule, IsRightsAuthorized(), MACSystemCommand(), MagickFalse, MaxTextExtent, PolicyError, RelinquishMagickMemory(), StringToArgv(), and ThrowMagickException().
Referenced by InvokeDelegate().