MagickCore: version.h File Reference
version.h File Reference
Macros
#define MagickPackageName "ImageMagick"
#define MagickCopyright "Copyright (C) 1999-2013 ImageMagick Studio LLC"
#define MagickSVNRevision "12412:12483M"
#define MagickLibVersion 0x700
#define MagickLibVersionText "7.0.0"
#define MagickLibVersionNumber 1,0,0
#define MagickLibAddendum "-0"
#define MagickLibInterface 1
#define MagickLibMinInterface 1
#define MagickReleaseDate "2013-06-19"
#define MagickChangeDate "20120427"
#define MagickAuthoritativeURL "http://www.imagemagick.org"
#define MagickFeatures "DPC HDRI OpenMP"
#define MagickDelegates "bzlib fontconfig freetype jng jp2 jpeg lcms lzma png ps tiff x xml zlib"
#define MagickHomeURL "file:///usr/share/doc/ImageMagick-7/index.html"
#define MagickQuantumDepth "Q?"
#define MagickQuantumRange "?"
#define MagickVersion
Functions
MagickExport char * GetMagickHomeURL (void)
MagickExport const char * GetMagickCopyright (void)
MagickExport const char * GetMagickDelegates (void)
MagickExport const char * GetMagickFeatures (void)
MagickExport const char * GetMagickPackageName (void)
MagickExport const char * GetMagickQuantumDepth (size_t *)
MagickExport const char * GetMagickQuantumRange (size_t *)
MagickExport const char * GetMagickReleaseDate (void)
MagickExport const char * GetMagickVersion (size_t *)
MagickExport void ListMagickVersion (FILE *)
Macro Definition Documentation
#define MagickAuthoritativeURL "http://www.imagemagick.org"
Definition at line 39 of file version.h.
#define MagickChangeDate "20120427"
Definition at line 38 of file version.h.
#define MagickCopyright "Copyright (C) 1999-2013 ImageMagick Studio LLC"
Definition at line 29 of file version.h.
Referenced by GetMagickCopyright().
#define MagickDelegates "bzlib fontconfig freetype jng jp2 jpeg lcms lzma png ps tiff x xml zlib"
Definition at line 41 of file version.h.
Referenced by GetMagickDelegates().
#define MagickFeatures "DPC HDRI OpenMP"
Definition at line 40 of file version.h.
Referenced by GetMagickFeatures().
#define MagickHomeURL "file:///usr/share/doc/ImageMagick-7/index.html"
Definition at line 42 of file version.h.
Referenced by GetMagickHomeURL().
#define MagickLibAddendum "-0"
Definition at line 34 of file version.h.
#define MagickLibInterface 1
Definition at line 35 of file version.h.
Referenced by GetMagickSignature().
#define MagickLibMinInterface 1
Definition at line 36 of file version.h.
#define MagickLibVersion 0x700
Definition at line 31 of file version.h.
Referenced by GetMagickVersion().
#define MagickLibVersionNumber 1,0,0
Definition at line 33 of file version.h.
#define MagickLibVersionText "7.0.0"
Definition at line 32 of file version.h.
Referenced by TranslateEvent(), and TranslateFilename().
#define MagickPackageName "ImageMagick"
Definition at line 28 of file version.h.
Referenced by GetMagickPackageName().
#define MagickQuantumDepth "Q?"
Definition at line 56 of file version.h.
Referenced by GetMagickQuantumDepth().
#define MagickQuantumRange "?"
Definition at line 57 of file version.h.
Referenced by GetMagickQuantumRange().
#define MagickReleaseDate "2013-06-19"
Definition at line 37 of file version.h.
Referenced by GetMagickReleaseDate().
#define MagickSVNRevision "12412:12483M"
Definition at line 30 of file version.h.
#define MagickVersion
Value:
MagickPackageName " " MagickLibVersionText MagickLibAddendum " " \
  MagickReleaseDate " " MagickQuantumDepth " " MagickAuthoritativeURL
Definition at line 59 of file version.h.
Referenced by GetMagickVersion().
Function Documentation
MagickExport const char* GetMagickCopyright (void)
MagickExport const char * GetMagickDelegates (void)
MagickExport const char * GetMagickFeatures (void)
MagickExport char* GetMagickHomeURL (void)
Definition at line 147 of file version.c.
References AcquireExceptionInfo(), ConstantString(), DestroyExceptionInfo(), DirectorySeparator, FormatLocaleString(), GetConfigurePaths(), GetNextValueInLinkedList(), IsPathAccessible(), MagickFalse, MagickHomeURL, MagickURLFilename, and MaxTextExtent.
MagickExport const char * GetMagickPackageName (void)
MagickExport const char * GetMagickQuantumDepth (size_t *)
MagickExport const char * GetMagickQuantumRange (size_t *)
MagickExport const char * GetMagickReleaseDate (void)
MagickExport const char * GetMagickVersion (size_t *)
Definition at line 410 of file version.c.
References MagickLibVersion, and MagickVersion.
Referenced by GetMagickProperty(), IdentifyImage(), ListMagickVersion(), and ThumbnailImage().
MagickExport void ListMagickVersion (FILE *)
Definition at line 441 of file version.c.
References FormatLocaleFile(), GetMagickCopyright(), GetMagickDelegates(), GetMagickFeatures(), and GetMagickVersion().