MagickCore: version.c File Reference
version.c File Reference
#include "MagickCore/studio.h"
#include "MagickCore/configure.h"
#include "MagickCore/exception.h"
#include "MagickCore/exception-private.h"
#include "MagickCore/hashmap.h"
#include "MagickCore/locale_.h"
#include "MagickCore/option.h"
#include "MagickCore/string_.h"
#include "MagickCore/utility.h"
#include "MagickCore/utility-private.h"
#include "MagickCore/version.h"
Macros
#define MagickURLFilename "index.html"
Functions
MagickExport const char * GetMagickCopyright (void)
MagickExport const char * GetMagickDelegates (void)
MagickExport const char * GetMagickFeatures (void)
MagickExport char * GetMagickHomeURL (void)
MagickExport const char * GetMagickPackageName (void)
MagickExport const char * GetMagickQuantumDepth (size_t *depth)
MagickExport const char * GetMagickQuantumRange (size_t *range)
MagickExport const char * GetMagickReleaseDate (void)
static unsigned int CRC32 (const unsigned char *message, const size_t length)
MagickExport unsigned int GetMagickSignature (const StringInfo *nonce)
MagickExport const char * GetMagickVersion (size_t *version)
MagickExport void ListMagickVersion (FILE *file)
Macro Definition Documentation
#define MagickURLFilename "index.html"
Definition at line 54 of file version.c.
Referenced by GetMagickHomeURL().
Function Documentation
static unsigned int CRC32 (const unsigned char * message, const size_t length) static
Definition at line 311 of file version.c.
References MagickFalse, and MagickTrue.
Referenced by GetMagickSignature().
MagickExport const char* GetMagickCopyright (void)
Definition at line 74 of file version.c.
References MagickCopyright.
Referenced by GetMagickProperty(), and ListMagickVersion().
MagickExport const char* GetMagickDelegates (void)
Definition at line 99 of file version.c.
References MagickDelegates.
Referenced by ListMagickVersion().
MagickExport const char* GetMagickFeatures (void)
Definition at line 124 of file version.c.
References MagickFeatures.
Referenced by ListMagickVersion().
MagickExport char* GetMagickHomeURL (void)
Definition at line 147 of file version.c.
References AcquireExceptionInfo(), ConstantString(), DestroyExceptionInfo(), DirectorySeparator, FormatLocaleString(), GetConfigurePaths(), GetNextValueInLinkedList(), IsPathAccessible(), MagickFalse, MagickHomeURL, MagickURLFilename, and MaxTextExtent.
MagickExport const char* GetMagickPackageName (void)
Definition at line 198 of file version.c.
References MagickPackageName.
MagickExport const char* GetMagickQuantumDepth (size_t * depth)
Definition at line 225 of file version.c.
References MAGICKCORE_QUANTUM_DEPTH, and MagickQuantumDepth.
MagickExport const char* GetMagickQuantumRange (size_t * range)
Definition at line 254 of file version.c.
References MagickQuantumRange, and QuantumRange.
MagickExport const char* GetMagickReleaseDate (void)
Definition at line 281 of file version.c.
References MagickReleaseDate.
MagickExport unsigned int GetMagickSignature (const StringInfo * nonce)
Definition at line 354 of file version.c.
References AcquireStringInfo(), ConcatenateStringInfo(), CRC32(), DestroyStringInfo(), GetStringInfoDatum(), GetStringInfoLength(), MAGICKCORE_QUANTUM_DEPTH, MagickLibInterface, MaxTextExtent, and SetStringInfoLength().
Referenced by ConnectPixelCacheServer(), and DistributePixelCacheClient().
MagickExport const char* GetMagickVersion (size_t * version)
Definition at line 410 of file version.c.
References MagickLibVersion, and MagickVersion.
Referenced by GetMagickProperty(), IdentifyImage(), ListMagickVersion(), and ThumbnailImage().
MagickExport void ListMagickVersion (FILE * file)
Definition at line 441 of file version.c.
References FormatLocaleFile(), GetMagickCopyright(), GetMagickDelegates(), GetMagickFeatures(), and GetMagickVersion().