MagickCore: xml-tree.h File Reference
xml-tree.h File Reference
Typedefs
typedef struct _XMLTreeInfo XMLTreeInfo
Functions
MagickExport char * XMLTreeInfoToXML (XMLTreeInfo *)
MagickExport const char * GetXMLTreeAttribute (XMLTreeInfo *, const char *)
MagickExport const char * GetXMLTreeContent (XMLTreeInfo *)
MagickExport const char * GetXMLTreeTag (XMLTreeInfo *)
MagickExport XMLTreeInfo * AddChildToXMLTree (XMLTreeInfo *, const char *, const size_t)
MagickExport XMLTreeInfo * DestroyXMLTree (XMLTreeInfo *)
MagickExport XMLTreeInfo * GetNextXMLTreeTag (XMLTreeInfo *)
MagickExport XMLTreeInfo * GetXMLTreeChild (XMLTreeInfo *, const char *)
MagickExport XMLTreeInfo * GetXMLTreeSibling (XMLTreeInfo *)
MagickExport XMLTreeInfo * NewXMLTree (const char *, ExceptionInfo *)
MagickExport XMLTreeInfo * NewXMLTreeTag (const char *)
MagickExport XMLTreeInfo * SetXMLTreeContent (XMLTreeInfo *, const char *)
Typedef Documentation
typedef struct _XMLTreeInfo XMLTreeInfo
Definition at line 25 of file xml-tree.h.
Function Documentation
MagickExport XMLTreeInfo* AddChildToXMLTree (XMLTreeInfo * , const char * , const size_t)
MagickExport XMLTreeInfo * DestroyXMLTree (XMLTreeInfo *)
MagickExport XMLTreeInfo * GetNextXMLTreeTag (XMLTreeInfo *)
MagickExport const char* GetXMLTreeAttribute (XMLTreeInfo * , const char *)
MagickExport XMLTreeInfo * GetXMLTreeChild (XMLTreeInfo * , const char *)
MagickExport const char * GetXMLTreeContent (XMLTreeInfo *)
MagickExport XMLTreeInfo * GetXMLTreeSibling (XMLTreeInfo *)
MagickExport const char * GetXMLTreeTag (XMLTreeInfo *)
Definition at line 958 of file xml-tree.c.
References GetMagickModule, LogMagickEvent(), MagickSignature, _XMLTreeInfo::signature, _XMLTreeInfo::tag, and TraceEvent.
Referenced by GetXMPProperty().
MagickExport XMLTreeInfo * NewXMLTree (const char * , ExceptionInfo *)
MagickExport XMLTreeInfo * NewXMLTreeTag (const char *)
MagickExport XMLTreeInfo * SetXMLTreeContent (XMLTreeInfo * , const char *)
Definition at line 2303 of file xml-tree.c.
References ConstantString(), _XMLTreeInfo::content, DestroyString(), GetMagickModule, LogMagickEvent(), MagickSignature, _XMLTreeInfo::signature, and TraceEvent.
MagickExport char* XMLTreeInfoToXML (XMLTreeInfo *)
Definition at line 2479 of file xml-tree.c.
References AcquireString(), _XMLTreeRoot::attributes, FormatLocaleString(), GetMagickModule, LogMagickEvent(), MagickSignature, MaxTextExtent, _XMLTreeInfo::ordered, _XMLTreeInfo::parent, _XMLTreeRoot::processing_instructions, ResizeQuantumMemory(), _XMLTreeRoot::root, _XMLTreeInfo::signature, _XMLTreeInfo::tag, TraceEvent, and XMLTreeTagToXML().