MagickCore: xml-tree.c File Reference
xml-tree.c File Reference
#include "MagickCore/studio.h"
#include "MagickCore/blob.h"
#include "MagickCore/exception.h"
#include "MagickCore/exception-private.h"
#include "MagickCore/log.h"
#include "MagickCore/memory_.h"
#include "MagickCore/semaphore.h"
#include "MagickCore/string_.h"
#include "MagickCore/string-private.h"
#include "MagickCore/token-private.h"
#include "MagickCore/xml-tree.h"
#include "MagickCore/xml-tree-private.h"
#include "MagickCore/utility.h"
#include "MagickCore/utility-private.h"
Data Structures
struct _XMLTreeInfo
struct _XMLTreeRoot
Macros
#define NumberPredefinedEntities 10
#define XMLWhitespace "\t\r\n "
Typedefs
typedef struct _XMLTreeRoot XMLTreeRoot
Functions
MagickExport XMLTreeInfo * AddChildToXMLTree (XMLTreeInfo *xml_info, const char *tag, const size_t offset)
MagickPrivate XMLTreeInfo * AddPathToXMLTree (XMLTreeInfo *xml_info, const char *path, const size_t offset)
MagickPrivate char * CanonicalXMLContent (const char *content, const MagickBooleanType pedantic)
static char ** DestroyXMLTreeAttributes (char **attributes)
MagickExport XMLTreeInfo * DestroyXMLTree (XMLTreeInfo *xml_info)
MagickExport XMLTreeInfo * GetNextXMLTreeTag (XMLTreeInfo *xml_info)
MagickExport const char * GetXMLTreeAttribute (XMLTreeInfo *xml_info, const char *tag)
MagickPrivate MagickBooleanType GetXMLTreeAttributes (const XMLTreeInfo *xml_info, SplayTreeInfo *attributes)
MagickExport XMLTreeInfo * GetXMLTreeChild (XMLTreeInfo *xml_info, const char *tag)
MagickExport const char * GetXMLTreeContent (XMLTreeInfo *xml_info)
MagickPrivate XMLTreeInfo * GetXMLTreeOrdered (XMLTreeInfo *xml_info)
MagickPrivate XMLTreeInfo * GetXMLTreePath (XMLTreeInfo *xml_info, const char *path)
MagickPrivate const char ** GetXMLTreeProcessingInstructions (XMLTreeInfo *xml_info, const char *target)
MagickExport XMLTreeInfo * GetXMLTreeSibling (XMLTreeInfo *xml_info)
MagickExport const char * GetXMLTreeTag (XMLTreeInfo *xml_info)
MagickPrivate XMLTreeInfo * InsertTagIntoXMLTree (XMLTreeInfo *xml_info, XMLTreeInfo *child, const size_t offset)
static char * ConvertUTF16ToUTF8 (const char *content, size_t *length)
static char * ParseEntities (char *xml, char **entities, int state)
static void ParseCharacterContent (XMLTreeRoot *root, char *xml, const size_t length, const char state)
static XMLTreeInfo * ParseCloseTag (XMLTreeRoot *root, char *tag, char *magick_unused(xml), ExceptionInfo *exception)
static MagickBooleanType ValidateEntities (char *tag, char *xml, char **entities)
static void ParseProcessingInstructions (XMLTreeRoot *root, char *xml, size_t length)
static MagickBooleanType ParseInternalDoctype (XMLTreeRoot *root, char *xml, size_t length, ExceptionInfo *exception)
static void ParseOpenTag (XMLTreeRoot *root, char *tag, char **attributes)
MagickExport XMLTreeInfo * NewXMLTree (const char *xml, ExceptionInfo *exception)
MagickExport XMLTreeInfo * NewXMLTreeTag (const char *tag)
MagickPrivate XMLTreeInfo * PruneTagFromXMLTree (XMLTreeInfo *xml_info)
MagickPrivate XMLTreeInfo * SetXMLTreeAttribute (XMLTreeInfo *xml_info, const char *tag, const char *value)
MagickExport XMLTreeInfo * SetXMLTreeContent (XMLTreeInfo *xml_info, const char *content)
static char * EncodePredefinedEntities (const char *source, ssize_t offset, char **destination, size_t *length, size_t *extent, MagickBooleanType pedantic)
static char * XMLTreeTagToXML (XMLTreeInfo *xml_info, char **source, size_t *length, size_t *extent, size_t start, char ***attributes)
MagickExport char * XMLTreeInfoToXML (XMLTreeInfo *xml_info)
Variables
static char * sentinel [] = { (char *) NULL }
Macro Definition Documentation
#define NumberPredefinedEntities 10
Definition at line 68 of file xml-tree.c.
Referenced by DestroyXMLTree(), and NewXMLTreeTag().
#define XMLWhitespace "\t\r\n "
Definition at line 69 of file xml-tree.c.
Referenced by NewXMLTree(), ParseInternalDoctype(), and ParseProcessingInstructions().
Typedef Documentation
typedef struct _XMLTreeRoot XMLTreeRoot
Definition at line 101 of file xml-tree.c.
Function Documentation
MagickExport XMLTreeInfo* AddChildToXMLTree (XMLTreeInfo * xml_info, const char * tag, const size_t offset)
Definition at line 164 of file xml-tree.c.
References AcquireMagickMemory(), _XMLTreeInfo::attributes, _XMLTreeInfo::child, ConstantString(), _XMLTreeInfo::content, _XMLTreeInfo::debug, InsertTagIntoXMLTree(), IsEventLogging(), MagickSignature, ResetMagickMemory(), sentinel, _XMLTreeInfo::signature, and _XMLTreeInfo::tag.
Referenced by AddPathToXMLTree(), and ParseOpenTag().
MagickPrivate XMLTreeInfo* AddPathToXMLTree (XMLTreeInfo * xml_info, const char * path, const size_t offset)
Definition at line 212 of file xml-tree.c.
References AddChildToXMLTree(), CanonicalPath, _XMLTreeInfo::child, DestroyString(), GetMagickModule, GetPathComponent(), GetPathComponents(), GetXMLTreeChild(), GetXMLTreeOrdered(), LogMagickEvent(), MagickSignature, MaxTextExtent, RelinquishMagickMemory(), _XMLTreeInfo::signature, StringToLong(), SubimagePath, _XMLTreeInfo::tag, and TraceEvent.
MagickPrivate char* CanonicalXMLContent (const char * content, const MagickBooleanType pedantic)
Definition at line 296 of file xml-tree.c.
References AcquireString(), Base64Encode(), ConcatenateString(), ConvertLatin1ToUTF8(), DestroyString(), FormatLocaleString(), MagickFalse, MaxTextExtent, RelinquishMagickMemory(), and ResizeQuantumMemory().
Referenced by EncodePredefinedEntities().
static char* ConvertUTF16ToUTF8 (const char * content, size_t * length) static
Definition at line 1088 of file xml-tree.c.
References AcquireQuantumMemory(), CopyMagickMemory(), MaxTextExtent, and ResizeQuantumMemory().
Referenced by NewXMLTree().
MagickExport XMLTreeInfo* DestroyXMLTree (XMLTreeInfo * xml_info)
Definition at line 459 of file xml-tree.c.
References _XMLTreeInfo::attributes, _XMLTreeRoot::attributes, _XMLTreeInfo::child, _XMLTreeInfo::content, DestroyString(), DestroyXMLTreeAttributes(), _XMLTreeRoot::entities, GetMagickModule, LogMagickEvent(), MagickSignature, NumberPredefinedEntities, _XMLTreeInfo::ordered, _XMLTreeInfo::parent, _XMLTreeRoot::processing_instructions, RelinquishMagickMemory(), _XMLTreeInfo::signature, _XMLTreeInfo::tag, and TraceEvent.
Referenced by ColorDecisionListImage(), GetThresholdMapFile(), GetXMPProperty(), ListThresholdMapFile(), and LoadMimeList().
static char** DestroyXMLTreeAttributes (char ** attributes) static
Definition at line 435 of file xml-tree.c.
References DestroyString(), RelinquishMagickMemory(), and sentinel.
Referenced by DestroyXMLTree(), and NewXMLTree().
static char* EncodePredefinedEntities (const char * source, ssize_t offset, char ** destination, size_t * length, size_t * extent, MagickBooleanType pedantic) static
Definition at line 2339 of file xml-tree.c.
References AcquireString(), CanonicalXMLContent(), _XMLTreeInfo::content, DestroyString(), FormatLocaleString(), MaxTextExtent, _XMLTreeInfo::offset, and ResizeQuantumMemory().
Referenced by XMLTreeTagToXML().
MagickExport XMLTreeInfo* GetNextXMLTreeTag (XMLTreeInfo * xml_info)
Definition at line 553 of file xml-tree.c.
References GetMagickModule, LogMagickEvent(), MagickSignature, _XMLTreeInfo::next, _XMLTreeInfo::signature, and TraceEvent.
Referenced by GetThresholdMapFile(), GetXMPProperty(), ListThresholdMapFile(), and LoadMimeList().
MagickExport const char* GetXMLTreeAttribute (XMLTreeInfo * xml_info, const char * tag)
Definition at line 587 of file xml-tree.c.
References _XMLTreeInfo::attributes, _XMLTreeRoot::attributes, GetMagickModule, LogMagickEvent(), MagickSignature, _XMLTreeInfo::parent, _XMLTreeRoot::root, _XMLTreeInfo::signature, _XMLTreeInfo::tag, and TraceEvent.
Referenced by GetThresholdMapFile(), ListThresholdMapFile(), LoadMimeList(), and XMLTreeTagToXML().
MagickPrivate MagickBooleanType GetXMLTreeAttributes (const XMLTreeInfo * xml_info, SplayTreeInfo * attributes)
Definition at line 655 of file xml-tree.c.
References AddValueToSplayTree(), _XMLTreeInfo::attributes, ConstantString(), GetMagickModule, LogMagickEvent(), MagickSignature, MagickTrue, _XMLTreeInfo::signature, and TraceEvent.
MagickExport XMLTreeInfo* GetXMLTreeChild (XMLTreeInfo * xml_info, const char * tag)
Definition at line 702 of file xml-tree.c.
References _XMLTreeInfo::child, GetMagickModule, LogMagickEvent(), MagickSignature, _XMLTreeInfo::sibling, _XMLTreeInfo::signature, _XMLTreeInfo::tag, and TraceEvent.
Referenced by AddPathToXMLTree(), ColorDecisionListImage(), GetThresholdMapFile(), GetXMLTreePath(), GetXMPProperty(), ListThresholdMapFile(), and LoadMimeList().
MagickExport const char* GetXMLTreeContent (XMLTreeInfo * xml_info)
Definition at line 741 of file xml-tree.c.
References _XMLTreeInfo::content, GetMagickModule, LogMagickEvent(), MagickSignature, _XMLTreeInfo::signature, and TraceEvent.
Referenced by ColorDecisionListImage(), GetThresholdMapFile(), GetXMPProperty(), and ListThresholdMapFile().
MagickPrivate XMLTreeInfo* GetXMLTreeOrdered (XMLTreeInfo * xml_info)
Definition at line 772 of file xml-tree.c.
References GetMagickModule, LogMagickEvent(), MagickSignature, _XMLTreeInfo::ordered, _XMLTreeInfo::signature, and TraceEvent.
MagickPrivate XMLTreeInfo* GetXMLTreePath (XMLTreeInfo * xml_info, const char * path)
Definition at line 806 of file xml-tree.c.
References CanonicalPath, DestroyString(), GetMagickModule, GetPathComponent(), GetPathComponents(), GetXMLTreeChild(), GetXMLTreeOrdered(), LogMagickEvent(), MagickSignature, MaxTextExtent, RelinquishMagickMemory(), _XMLTreeInfo::signature, StringToLong(), SubimagePath, _XMLTreeInfo::tag, and TraceEvent.
MagickPrivate const char** GetXMLTreeProcessingInstructions (XMLTreeInfo * xml_info, const char * target)
Definition at line 880 of file xml-tree.c.
References GetMagickModule, LogMagickEvent(), MagickSignature, _XMLTreeInfo::parent, _XMLTreeRoot::processing_instructions, _XMLTreeRoot::root, sentinel, _XMLTreeInfo::signature, and TraceEvent.
MagickExport XMLTreeInfo* GetXMLTreeSibling (XMLTreeInfo * xml_info)
Definition at line 927 of file xml-tree.c.
References GetMagickModule, LogMagickEvent(), MagickSignature, _XMLTreeInfo::sibling, _XMLTreeInfo::signature, and TraceEvent.
Referenced by GetXMPProperty().
MagickExport const char* GetXMLTreeTag (XMLTreeInfo * xml_info)
Definition at line 958 of file xml-tree.c.
References GetMagickModule, LogMagickEvent(), MagickSignature, _XMLTreeInfo::signature, _XMLTreeInfo::tag, and TraceEvent.
Referenced by GetXMPProperty().
MagickPrivate XMLTreeInfo* InsertTagIntoXMLTree (XMLTreeInfo * xml_info, XMLTreeInfo * child, const size_t offset)
Definition at line 995 of file xml-tree.c.
References _XMLTreeInfo::child, _XMLTreeInfo::next, _XMLTreeInfo::offset, _XMLTreeInfo::ordered, _XMLTreeInfo::parent, _XMLTreeInfo::sibling, and _XMLTreeInfo::tag.
MagickExport XMLTreeInfo* NewXMLTree (const char * xml, ExceptionInfo * exception)
Definition at line 1705 of file xml-tree.c.
References AcquireQuantumMemory(), _XMLTreeInfo::attributes, _XMLTreeRoot::attributes, ConstantString(), ConvertUTF16ToUTF8(), DestroyString(), DestroyXMLTreeAttributes(), _XMLTreeRoot::entities, GetMagickModule, MagickFalse, NewXMLTreeTag(), _XMLTreeRoot::node, OptionWarning, ParseCharacterContent(), ParseCloseTag(), ParseEntities(), ParseInternalDoctype(), ParseOpenTag(), ParseProcessingInstructions(), ResizeQuantumMemory(), ResourceLimitError, _XMLTreeRoot::root, sentinel, _XMLTreeInfo::tag, ThrowMagickException(), and XMLWhitespace.
Referenced by ColorDecisionListImage(), GetThresholdMapFile(), GetXMPProperty(), ListThresholdMapFile(), and LoadMimeList().
MagickExport XMLTreeInfo* NewXMLTreeTag (const char * tag)
Definition at line 2080 of file xml-tree.c.
References AcquireMagickMemory(), _XMLTreeInfo::attributes, _XMLTreeRoot::attributes, ConstantString(), _XMLTreeInfo::content, CopyMagickMemory(), _XMLTreeRoot::debug, _XMLTreeRoot::entities, IsEventLogging(), MagickSignature, _XMLTreeRoot::node, NumberPredefinedEntities, _XMLTreeRoot::processing_instructions, ResetMagickMemory(), _XMLTreeRoot::root, sentinel, _XMLTreeRoot::signature, and _XMLTreeInfo::tag.
Referenced by NewXMLTree().
static void ParseCharacterContent (XMLTreeRoot * root, char * xml, const size_t length, const char state) static
Definition at line 1329 of file xml-tree.c.
References ConcatenateString(), _XMLTreeInfo::content, DestroyString(), _XMLTreeRoot::entities, _XMLTreeRoot::node, ParseEntities(), and _XMLTreeInfo::tag.
Referenced by NewXMLTree().
static XMLTreeInfo* ParseCloseTag (XMLTreeRoot * root, char * tag, char * magick_unusedxml, ExceptionInfo * exception) static
Definition at line 1354 of file xml-tree.c.
References GetMagickModule, _XMLTreeRoot::node, OptionWarning, _XMLTreeInfo::parent, _XMLTreeRoot::root, _XMLTreeInfo::tag, and ThrowMagickException().
Referenced by NewXMLTree().
static char* ParseEntities (char * xml, char ** entities, int state) static
Definition at line 1165 of file xml-tree.c.
References AcquireQuantumMemory(), ConstantString(), CopyMagickMemory(), CopyMagickString(), _XMLTreeInfo::offset, ResizeQuantumMemory(), ResourceLimitFatalError, and ThrowFatalException.
Referenced by NewXMLTree(), ParseCharacterContent(), and ParseInternalDoctype().
static MagickBooleanType ParseInternalDoctype (XMLTreeRoot * root, char * xml, size_t length, ExceptionInfo * exception) static
Definition at line 1472 of file xml-tree.c.
References AcquireMagickMemory(), AcquireQuantumMemory(), _XMLTreeRoot::attributes, ConstantString(), CopyMagickMemory(), DestroyString(), _XMLTreeRoot::entities, GetMagickModule, MagickFalse, MagickTrue, OptionWarning, ParseEntities(), ParseProcessingInstructions(), RelinquishMagickMemory(), ResizeQuantumMemory(), ResourceLimitError, ResourceLimitFatalError, sentinel, _XMLTreeRoot::standalone, ThrowFatalException, ThrowMagickException(), ValidateEntities(), and XMLWhitespace.
Referenced by NewXMLTree().
static void ParseOpenTag (XMLTreeRoot * root, char * tag, char ** attributes) static
Definition at line 1691 of file xml-tree.c.
References AddChildToXMLTree(), _XMLTreeInfo::attributes, ConstantString(), _XMLTreeInfo::content, _XMLTreeRoot::node, and _XMLTreeInfo::tag.
Referenced by NewXMLTree().
static void ParseProcessingInstructions (XMLTreeRoot * root, char * xml, size_t length) static
Definition at line 1395 of file xml-tree.c.
References AcquireMagickMemory(), AcquireQuantumMemory(), ConstantString(), CopyMagickString(), MagickTrue, _XMLTreeRoot::processing_instructions, ResizeQuantumMemory(), ResourceLimitFatalError, _XMLTreeRoot::root, _XMLTreeRoot::standalone, _XMLTreeInfo::tag, ThrowFatalException, and XMLWhitespace.
Referenced by NewXMLTree(), and ParseInternalDoctype().
MagickPrivate XMLTreeInfo* PruneTagFromXMLTree (XMLTreeInfo * xml_info)
Definition at line 2137 of file xml-tree.c.
References _XMLTreeInfo::child, GetMagickModule, LogMagickEvent(), MagickSignature, _XMLTreeInfo::next, _XMLTreeInfo::ordered, _XMLTreeInfo::parent, _XMLTreeInfo::sibling, _XMLTreeInfo::signature, _XMLTreeInfo::tag, and TraceEvent.
MagickPrivate XMLTreeInfo* SetXMLTreeAttribute (XMLTreeInfo * xml_info, const char * tag, const char * value)
Definition at line 2210 of file xml-tree.c.
References AcquireQuantumMemory(), _XMLTreeInfo::attributes, ConstantString(), CopyMagickMemory(), DestroyString(), GetMagickModule, LogMagickEvent(), MagickSignature, ResizeQuantumMemory(), ResourceLimitFatalError, sentinel, _XMLTreeInfo::signature, ThrowFatalException, and TraceEvent.
MagickExport XMLTreeInfo* SetXMLTreeContent (XMLTreeInfo * xml_info, const char * content)
Definition at line 2303 of file xml-tree.c.
References ConstantString(), _XMLTreeInfo::content, DestroyString(), GetMagickModule, LogMagickEvent(), MagickSignature, _XMLTreeInfo::signature, and TraceEvent.
static MagickBooleanType ValidateEntities (char * tag, char * xml, char ** entities) static
Definition at line 1368 of file xml-tree.c.
References MagickFalse, and MagickTrue.
Referenced by ParseInternalDoctype().
MagickExport char* XMLTreeInfoToXML (XMLTreeInfo * xml_info)
Definition at line 2479 of file xml-tree.c.
References AcquireString(), _XMLTreeRoot::attributes, FormatLocaleString(), GetMagickModule, LogMagickEvent(), MagickSignature, MaxTextExtent, _XMLTreeInfo::ordered, _XMLTreeInfo::parent, _XMLTreeRoot::processing_instructions, ResizeQuantumMemory(), _XMLTreeRoot::root, _XMLTreeInfo::signature, _XMLTreeInfo::tag, TraceEvent, and XMLTreeTagToXML().
static char* XMLTreeTagToXML (XMLTreeInfo * xml_info, char ** source, size_t * length, size_t * extent, size_t start, char *** attributes) static
Definition at line 2373 of file xml-tree.c.
References _XMLTreeInfo::attributes, _XMLTreeInfo::child, _XMLTreeInfo::content, EncodePredefinedEntities(), FormatLocaleString(), GetXMLTreeAttribute(), MagickFalse, MagickTrue, MaxTextExtent, _XMLTreeInfo::offset, _XMLTreeInfo::ordered, _XMLTreeInfo::parent, ResizeQuantumMemory(), and _XMLTreeInfo::tag.
Referenced by XMLTreeInfoToXML().
Variable Documentation
char* sentinel[] = { (char *) NULL } static
Definition at line 134 of file xml-tree.c.
Referenced by AddChildToXMLTree(), DestroyXMLTreeAttributes(), GetCommandOptionFlags(), GetXMLTreeProcessingInstructions(), IdentifyImage(), NewXMLTree(), NewXMLTreeTag(), ParseCommandOption(), ParseInternalDoctype(), and SetXMLTreeAttribute().