MagickCore: xwindow.c File Reference
xwindow.c File Reference
#include "MagickCore/studio.h"
#include "MagickCore/animate.h"
#include "MagickCore/artifact.h"
#include "MagickCore/blob.h"
#include "MagickCore/cache.h"
#include "MagickCore/client.h"
#include "MagickCore/color.h"
#include "MagickCore/color-private.h"
#include "MagickCore/colormap.h"
#include "MagickCore/composite.h"
#include "MagickCore/constitute.h"
#include "MagickCore/display.h"
#include "MagickCore/distort.h"
#include "MagickCore/exception.h"
#include "MagickCore/exception-private.h"
#include "MagickCore/geometry.h"
#include "MagickCore/identify.h"
#include "MagickCore/image.h"
#include "MagickCore/image-private.h"
#include "MagickCore/list.h"
#include "MagickCore/locale_.h"
#include "MagickCore/log.h"
#include "MagickCore/magick.h"
#include "MagickCore/memory_.h"
#include "MagickCore/monitor.h"
#include "MagickCore/nt-base-private.h"
#include "MagickCore/option.h"
#include "MagickCore/pixel-accessor.h"
#include "MagickCore/PreRvIcccm.h"
#include "MagickCore/quantize.h"
#include "MagickCore/quantum.h"
#include "MagickCore/quantum-private.h"
#include "MagickCore/resource_.h"
#include "MagickCore/resize.h"
#include "MagickCore/statistic.h"
#include "MagickCore/string_.h"
#include "MagickCore/string-private.h"
#include "MagickCore/transform.h"
#include "MagickCore/token.h"
#include "MagickCore/utility.h"
#include "MagickCore/utility-private.h"
#include "MagickCore/widget.h"
#include "MagickCore/widget-private.h"
#include "MagickCore/xwindow.h"
#include "MagickCore/xwindow-private.h"
#include "MagickCore/version.h"
Functions
MagickExport Image * XImportImage (const ImageInfo *image_info, XImportInfo *ximage_info, ExceptionInfo *exception)
MagickPrivate MagickBooleanType XRenderImage (Image *image, const DrawInfo *draw_info, const PointInfo *offset, TypeMetric *metrics, ExceptionInfo *exception)
MagickPrivate MagickBooleanType XComponentGenesis (void)
MagickExport void XGetImportInfo (XImportInfo *ximage_info)
Function Documentation
MagickPrivate MagickBooleanType XComponentGenesis (void)
Definition at line 10019 of file xwindow.c.
References MagickTrue.
Referenced by MagickCoreGenesis().
MagickExport void XGetImportInfo (XImportInfo * ximage_info)
Definition at line 10046 of file xwindow.c.
References _XImportInfo::borders, _XImportInfo::descend, _XImportInfo::frame, MagickFalse, MagickTrue, _XImportInfo::screen, and _XImportInfo::silent.
MagickExport Image* XImportImage (const ImageInfo * image_info, XImportInfo * ximage_info, ExceptionInfo * exception)
Definition at line 9941 of file xwindow.c.
References _ImageInfo::debug, _ImageInfo::filename, GetMagickModule, LogMagickEvent(), MagickFalse, MagickSignature, _ExceptionInfo::signature, _ImageInfo::signature, and TraceEvent.
MagickPrivate MagickBooleanType XRenderImage (Image * image, const DrawInfo * draw_info, const PointInfo * offset, TypeMetric * metrics, ExceptionInfo * exception)
Definition at line 9987 of file xwindow.c.
References _Image::filename, GetMagickModule, MagickFalse, MissingDelegateError, and ThrowMagickException().
Referenced by RenderX11().