MagickWand: drawing-wand.c File Reference
drawing-wand.c File Reference
#include "MagickWand/studio.h"
#include "MagickWand/MagickWand.h"
#include "MagickWand/magick-wand-private.h"
#include "MagickWand/wand.h"
#include "MagickCore/string-private.h"
Data Structures
struct _DrawingWand
struct _DrawVTable
Macros
#define DRAW_BINARY_IMPLEMENTATION 0
#define CurrentContext (wand->graphic_context[wand->index])
#define DrawingWandId "DrawingWand"
#define ThrowDrawException(severity, tag, reason)
Enumerations
enum PathOperation {
PathDefaultOperation, PathCloseOperation, PathCurveToOperation, PathCurveToQuadraticBezierOperation,
PathCurveToQuadraticBezierSmoothOperation, PathCurveToSmoothOperation, PathEllipticArcOperation, PathLineToHorizontalOperation,
PathLineToOperation, PathLineToVerticalOperation, PathMoveToOperation
}
enum PathMode { DefaultPathMode, AbsolutePathMode, RelativePathMode }
Functions
static int MvgPrintf (DrawingWand *, wand_attribute((format(const char *,...)
static int MvgAutoWrapPrintf (DrawingWand *wand, const char *format,...)
static void MvgAppendColor (DrawingWand *wand, const PixelInfo *packet)
static void MvgAppendPointsCommand (DrawingWand *wand, const char *command, const size_t number_coordinates, const PointInfo *coordinates)
static void AdjustAffine (DrawingWand *wand, const AffineMatrix *affine)
WandExport void ClearDrawingWand (DrawingWand *wand)
WandExport DrawingWand * CloneDrawingWand (const DrawingWand *wand)
WandExport DrawingWand * DestroyDrawingWand (DrawingWand *wand)
WandExport void DrawAffine (DrawingWand *wand, const AffineMatrix *affine)
WandExport DrawingWand * DrawAllocateWand (const DrawInfo *draw_info, Image *image)
WandExport void DrawAnnotation (DrawingWand *wand, const double x, const double y, const unsigned char *text)
WandExport void DrawArc (DrawingWand *wand, const double sx, const double sy, const double ex, const double ey, const double sd, const double ed)
WandExport void DrawBezier (DrawingWand *wand, const size_t number_coordinates, const PointInfo *coordinates)
WandExport void DrawCircle (DrawingWand *wand, const double ox, const double oy, const double px, const double py)
WandExport MagickBooleanType DrawClearException (DrawingWand *wand)
WandExport MagickBooleanType DrawComposite (DrawingWand *wand, const CompositeOperator compose, const double x, const double y, const double width, const double height, MagickWand *magick_wand)
WandExport void DrawColor (DrawingWand *wand, const double x, const double y, const PaintMethod paint_method)
WandExport void DrawComment (DrawingWand *wand, const char *comment)
WandExport void DrawEllipse (DrawingWand *wand, const double ox, const double oy, const double rx, const double ry, const double start, const double end)
WandExport void DrawGetBorderColor (const DrawingWand *wand, PixelWand *border_color)
WandExport char * DrawGetClipPath (const DrawingWand *wand)
WandExport FillRule DrawGetClipRule (const DrawingWand *wand)
WandExport ClipPathUnits DrawGetClipUnits (const DrawingWand *wand)
WandExport char * DrawGetException (const DrawingWand *wand, ExceptionType *severity)
WandExport ExceptionType DrawGetExceptionType (const DrawingWand *wand)
WandExport void DrawGetFillColor (const DrawingWand *wand, PixelWand *fill_color)
WandExport double DrawGetFillAlpha (const DrawingWand *wand)
WandExport FillRule DrawGetFillRule (const DrawingWand *wand)
WandExport char * DrawGetFont (const DrawingWand *wand)
WandExport char * DrawGetFontFamily (const DrawingWand *wand)
WandExport MagickBooleanType DrawGetFontResolution (const DrawingWand *wand, double *x, double *y)
WandExport double DrawGetFontSize (const DrawingWand *wand)
WandExport StretchType DrawGetFontStretch (const DrawingWand *wand)
WandExport StyleType DrawGetFontStyle (const DrawingWand *wand)
WandExport size_t DrawGetFontWeight (const DrawingWand *wand)
WandExport GravityType DrawGetGravity (const DrawingWand *wand)
WandExport double DrawGetAlpha (const DrawingWand *wand)
WandExport MagickBooleanType DrawGetStrokeAntialias (const DrawingWand *wand)
WandExport void DrawGetStrokeColor (const DrawingWand *wand, PixelWand *stroke_color)
WandExport double * DrawGetStrokeDashArray (const DrawingWand *wand, size_t *number_elements)
WandExport double DrawGetStrokeDashOffset (const DrawingWand *wand)
WandExport LineCap DrawGetStrokeLineCap (const DrawingWand *wand)
WandExport LineJoin DrawGetStrokeLineJoin (const DrawingWand *wand)
WandExport size_t DrawGetStrokeMiterLimit (const DrawingWand *wand)
WandExport double DrawGetStrokeAlpha (const DrawingWand *wand)
WandExport double DrawGetStrokeWidth (const DrawingWand *wand)
WandExport AlignType DrawGetTextAlignment (const DrawingWand *wand)
WandExport MagickBooleanType DrawGetTextAntialias (const DrawingWand *wand)
WandExport DecorationType DrawGetTextDecoration (const DrawingWand *wand)
WandExport char * DrawGetTextEncoding (const DrawingWand *wand)
WandExport double DrawGetTextKerning (DrawingWand *wand)
WandExport double DrawGetTextInterlineSpacing (DrawingWand *wand)
WandExport double DrawGetTextInterwordSpacing (DrawingWand *wand)
WandExport char * DrawGetVectorGraphics (DrawingWand *wand)
WandExport void DrawGetTextUnderColor (const DrawingWand *wand, PixelWand *under_color)
WandExport void DrawLine (DrawingWand *wand, const double sx, const double sy, const double ex, const double ey)
WandExport void DrawMatte (DrawingWand *wand, const double x, const double y, const PaintMethod paint_method)
WandExport void DrawPathClose (DrawingWand *wand)
static void DrawPathCurveTo (DrawingWand *wand, const PathMode mode, const double x1, const double y1, const double x2, const double y2, const double x, const double y)
WandExport void DrawPathCurveToAbsolute (DrawingWand *wand, const double x1, const double y1, const double x2, const double y2, const double x, const double y)
WandExport void DrawPathCurveToRelative (DrawingWand *wand, const double x1, const double y1, const double x2, const double y2, const double x, const double y)
static void DrawPathCurveToQuadraticBezier (DrawingWand *wand, const PathMode mode, const double x1, double y1, const double x, const double y)
WandExport void DrawPathCurveToQuadraticBezierAbsolute (DrawingWand *wand, const double x1, const double y1, const double x, const double y)
WandExport void DrawPathCurveToQuadraticBezierRelative (DrawingWand *wand, const double x1, const double y1, const double x, const double y)
static void DrawPathCurveToQuadraticBezierSmooth (DrawingWand *wand, const PathMode mode, const double x, const double y)
WandExport void DrawPathCurveToQuadraticBezierSmoothAbsolute (DrawingWand *wand, const double x, const double y)
WandExport void DrawPathCurveToQuadraticBezierSmoothRelative (DrawingWand *wand, const double x, const double y)
static void DrawPathCurveToSmooth (DrawingWand *wand, const PathMode mode, const double x2, const double y2, const double x, const double y)
WandExport void DrawPathCurveToSmoothAbsolute (DrawingWand *wand, const double x2, const double y2, const double x, const double y)
WandExport void DrawPathCurveToSmoothRelative (DrawingWand *wand, const double x2, const double y2, const double x, const double y)
static void DrawPathEllipticArc (DrawingWand *wand, const PathMode mode, const double rx, const double ry, const double x_axis_rotation, const MagickBooleanType large_arc_flag, const MagickBooleanType sweep_flag, const double x, const double y)
WandExport void DrawPathEllipticArcAbsolute (DrawingWand *wand, const double rx, const double ry, const double x_axis_rotation, const MagickBooleanType large_arc_flag, const MagickBooleanType sweep_flag, const double x, const double y)
WandExport void DrawPathEllipticArcRelative (DrawingWand *wand, const double rx, const double ry, const double x_axis_rotation, const MagickBooleanType large_arc_flag, const MagickBooleanType sweep_flag, const double x, const double y)
WandExport void DrawPathFinish (DrawingWand *wand)
static void DrawPathLineTo (DrawingWand *wand, const PathMode mode, const double x, const double y)
WandExport void DrawPathLineToAbsolute (DrawingWand *wand, const double x, const double y)
WandExport void DrawPathLineToRelative (DrawingWand *wand, const double x, const double y)
static void DrawPathLineToHorizontal (DrawingWand *wand, const PathMode mode, const double x)
WandExport void DrawPathLineToHorizontalAbsolute (DrawingWand *wand, const double x)
WandExport void DrawPathLineToHorizontalRelative (DrawingWand *wand, const double x)
static void DrawPathLineToVertical (DrawingWand *wand, const PathMode mode, const double y)
WandExport void DrawPathLineToVerticalAbsolute (DrawingWand *wand, const double y)
WandExport void DrawPathLineToVerticalRelative (DrawingWand *wand, const double y)
static void DrawPathMoveTo (DrawingWand *wand, const PathMode mode, const double x, const double y)
WandExport void DrawPathMoveToAbsolute (DrawingWand *wand, const double x, const double y)
WandExport void DrawPathMoveToRelative (DrawingWand *wand, const double x, const double y)
WandExport void DrawPathStart (DrawingWand *wand)
WandExport void DrawPoint (DrawingWand *wand, const double x, const double y)
WandExport void DrawPolygon (DrawingWand *wand, const size_t number_coordinates, const PointInfo *coordinates)
WandExport void DrawPolyline (DrawingWand *wand, const size_t number_coordinates, const PointInfo *coordinates)
WandExport void DrawPopClipPath (DrawingWand *wand)
WandExport void DrawPopDefs (DrawingWand *wand)
WandExport MagickBooleanType DrawPopPattern (DrawingWand *wand)
WandExport void DrawPushClipPath (DrawingWand *wand, const char *clip_mask_id)
WandExport void DrawPushDefs (DrawingWand *wand)
WandExport MagickBooleanType DrawPushPattern (DrawingWand *wand, const char *pattern_id, const double x, const double y, const double width, const double height)
WandExport void DrawRectangle (DrawingWand *wand, const double x1, const double y1, const double x2, const double y2)
WandExport MagickBooleanType DrawRender (DrawingWand *wand)
WandExport void DrawResetVectorGraphics (DrawingWand *wand)
WandExport void DrawRotate (DrawingWand *wand, const double degrees)
WandExport void DrawRoundRectangle (DrawingWand *wand, double x1, double y1, double x2, double y2, double rx, double ry)
WandExport void DrawScale (DrawingWand *wand, const double x, const double y)
WandExport void DrawSetBorderColor (DrawingWand *wand, const PixelWand *border_wand)
WandExport MagickBooleanType DrawSetClipPath (DrawingWand *wand, const char *clip_mask)
WandExport void DrawSetClipRule (DrawingWand *wand, const FillRule fill_rule)
WandExport void DrawSetClipUnits (DrawingWand *wand, const ClipPathUnits clip_units)
WandExport void DrawSetFillColor (DrawingWand *wand, const PixelWand *fill_wand)
WandExport void DrawSetFillAlpha (DrawingWand *wand, const double fill_alpha)
WandExport MagickBooleanType DrawSetFontResolution (DrawingWand *wand, const double x_resolution, const double y_resolution)
WandExport void DrawSetAlpha (DrawingWand *wand, const double alpha)
WandExport MagickBooleanType DrawSetFillPatternURL (DrawingWand *wand, const char *fill_url)
WandExport void DrawSetFillRule (DrawingWand *wand, const FillRule fill_rule)
WandExport MagickBooleanType DrawSetFont (DrawingWand *wand, const char *font_name)
WandExport MagickBooleanType DrawSetFontFamily (DrawingWand *wand, const char *font_family)
WandExport void DrawSetFontSize (DrawingWand *wand, const double pointsize)
WandExport void DrawSetFontStretch (DrawingWand *wand, const StretchType font_stretch)
WandExport void DrawSetFontStyle (DrawingWand *wand, const StyleType style)
WandExport void DrawSetFontWeight (DrawingWand *wand, const size_t font_weight)
WandExport void DrawSetGravity (DrawingWand *wand, const GravityType gravity)
WandExport void DrawSetStrokeColor (DrawingWand *wand, const PixelWand *stroke_wand)
WandExport MagickBooleanType DrawSetStrokePatternURL (DrawingWand *wand, const char *stroke_url)
WandExport void DrawSetStrokeAntialias (DrawingWand *wand, const MagickBooleanType stroke_antialias)
WandExport MagickBooleanType DrawSetStrokeDashArray (DrawingWand *wand, const size_t number_elements, const double *dash_array)
WandExport void DrawSetStrokeDashOffset (DrawingWand *wand, const double dash_offset)
WandExport void DrawSetStrokeLineCap (DrawingWand *wand, const LineCap linecap)
WandExport void DrawSetStrokeLineJoin (DrawingWand *wand, const LineJoin linejoin)
WandExport void DrawSetStrokeMiterLimit (DrawingWand *wand, const size_t miterlimit)
WandExport void DrawSetStrokeAlpha (DrawingWand *wand, const double stroke_alpha)
WandExport void DrawSetStrokeWidth (DrawingWand *wand, const double stroke_width)
WandExport void DrawSetTextAlignment (DrawingWand *wand, const AlignType alignment)
WandExport void DrawSetTextAntialias (DrawingWand *wand, const MagickBooleanType text_antialias)
WandExport void DrawSetTextDecoration (DrawingWand *wand, const DecorationType decoration)
WandExport void DrawSetTextEncoding (DrawingWand *wand, const char *encoding)
WandExport void DrawSetTextKerning (DrawingWand *wand, const double kerning)
WandExport void DrawSetTextInterlineSpacing (DrawingWand *wand, const double interline_spacing)
WandExport void DrawSetTextInterwordSpacing (DrawingWand *wand, const double interword_spacing)
WandExport void DrawSetTextUnderColor (DrawingWand *wand, const PixelWand *under_wand)
static MagickBooleanType IsPoint (const char *point)
WandExport MagickBooleanType DrawSetVectorGraphics (DrawingWand *wand, const char *xml)
WandExport void DrawSkewX (DrawingWand *wand, const double degrees)
WandExport void DrawSkewY (DrawingWand *wand, const double degrees)
WandExport void DrawTranslate (DrawingWand *wand, const double x, const double y)
WandExport void DrawSetViewbox (DrawingWand *wand, const double x1, const double y1, const double x2, const double y2)
WandExport MagickBooleanType IsDrawingWand (const DrawingWand *wand)
WandExport DrawingWand * NewDrawingWand (void)
WandExport DrawInfo * PeekDrawingWand (const DrawingWand *wand)
WandExport MagickBooleanType PopDrawingWand (DrawingWand *wand)
WandExport MagickBooleanType PushDrawingWand (DrawingWand *wand)
Macro Definition Documentation
#define CurrentContext (wand->graphic_context[wand->index])
Definition at line 60 of file drawing-wand.c.
Referenced by AdjustAffine(), ClearDrawingWand(), DestroyDrawingWand(), DrawAllocateWand(), DrawGetAlpha(), DrawGetBorderColor(), DrawGetClipPath(), DrawGetClipRule(), DrawGetClipUnits(), DrawGetFillAlpha(), DrawGetFillColor(), DrawGetFillRule(), DrawGetFont(), DrawGetFontFamily(), DrawGetFontResolution(), DrawGetFontSize(), DrawGetFontStretch(), DrawGetFontStyle(), DrawGetFontWeight(), DrawGetGravity(), DrawGetStrokeAlpha(), DrawGetStrokeAntialias(), DrawGetStrokeColor(), DrawGetStrokeDashArray(), DrawGetStrokeDashOffset(), DrawGetStrokeLineCap(), DrawGetStrokeLineJoin(), DrawGetStrokeMiterLimit(), DrawGetStrokeWidth(), DrawGetTextAlignment(), DrawGetTextAntialias(), DrawGetTextDecoration(), DrawGetTextEncoding(), DrawGetTextInterlineSpacing(), DrawGetTextInterwordSpacing(), DrawGetTextKerning(), DrawGetTextUnderColor(), DrawGetVectorGraphics(), DrawRender(), DrawSetAlpha(), DrawSetBorderColor(), DrawSetClipPath(), DrawSetClipRule(), DrawSetClipUnits(), DrawSetFillAlpha(), DrawSetFillColor(), DrawSetFillPatternURL(), DrawSetFillRule(), DrawSetFont(), DrawSetFontFamily(), DrawSetFontResolution(), DrawSetFontSize(), DrawSetFontStretch(), DrawSetFontStyle(), DrawSetFontWeight(), DrawSetGravity(), DrawSetStrokeAlpha(), DrawSetStrokeAntialias(), DrawSetStrokeColor(), DrawSetStrokeDashArray(), DrawSetStrokeDashOffset(), DrawSetStrokeLineCap(), DrawSetStrokeLineJoin(), DrawSetStrokeMiterLimit(), DrawSetStrokePatternURL(), DrawSetStrokeWidth(), DrawSetTextAlignment(), DrawSetTextAntialias(), DrawSetTextDecoration(), DrawSetTextEncoding(), DrawSetTextInterlineSpacing(), DrawSetTextInterwordSpacing(), DrawSetTextKerning(), DrawSetTextUnderColor(), DrawSetVectorGraphics(), NewDrawingWand(), PeekDrawingWand(), PopDrawingWand(), and PushDrawingWand().
#define DRAW_BINARY_IMPLEMENTATION 0
Definition at line 58 of file drawing-wand.c.
#define DrawingWandId "DrawingWand"
Definition at line 61 of file drawing-wand.c.
Referenced by IsDrawingWand(), and NewDrawingWand().
#define ThrowDrawException (severity, tag, reason)
Value:
(void) ThrowMagickException(\
  wand->exception,GetMagickModule(),severity,tag,"`%s'",reason);
Definition at line 62 of file drawing-wand.c.
Referenced by ClearDrawingWand(), DrawComposite(), DrawPopPattern(), DrawPushPattern(), DrawRender(), DrawSetClipPath(), DrawSetFillPatternURL(), DrawSetStrokeDashArray(), DrawSetStrokePatternURL(), MvgAutoWrapPrintf(), MvgPrintf(), PopDrawingWand(), and PushDrawingWand().
Enumeration Type Documentation
enum PathMode
Enumerator
DefaultPathMode
AbsolutePathMode
RelativePathMode
Definition at line 83 of file drawing-wand.c.
enum PathOperation
Enumerator
PathDefaultOperation
PathCloseOperation
PathCurveToOperation
PathCurveToQuadraticBezierOperation
PathCurveToQuadraticBezierSmoothOperation
PathCurveToSmoothOperation
PathEllipticArcOperation
PathLineToHorizontalOperation
PathLineToOperation
PathLineToVerticalOperation
PathMoveToOperation
Definition at line 68 of file drawing-wand.c.
Function Documentation
static void AdjustAffine (DrawingWand * wand, const AffineMatrix * affine) static
Definition at line 433 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::name, _DrawingWand::signature, and WandSignature.
Referenced by DrawAffine(), and DrawSetClipUnits().
WandExport void ClearDrawingWand (DrawingWand * wand)
Definition at line 479 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, DefaultPathMode, _DrawingWand::destroy, _DrawingWand::exception, _DrawingWand::filter_off, _DrawingWand::graphic_context, _DrawingWand::image, _DrawingWand::indent_depth, _DrawingWand::index, _DrawingWand::mvg, _DrawingWand::mvg_alloc, _DrawingWand::mvg_length, _DrawingWand::mvg_width, _DrawingWand::name, _DrawingWand::path_mode, _DrawingWand::path_operation, PathDefaultOperation, _DrawingWand::pattern_bounds, _DrawingWand::pattern_id, _DrawingWand::pattern_offset, _DrawingWand::signature, ThrowDrawException, and WandSignature.
WandExport DrawingWand* CloneDrawingWand (const DrawingWand * wand)
Definition at line 549 of file drawing-wand.c.
References AcquireWandId(), _DrawingWand::debug, _DrawingWand::destroy, _DrawingWand::exception, _DrawingWand::filter_off, _DrawingWand::graphic_context, _DrawingWand::id, _DrawingWand::image, _DrawingWand::indent_depth, _DrawingWand::index, MaxTextExtent, _DrawingWand::mvg, _DrawingWand::mvg_alloc, _DrawingWand::mvg_length, _DrawingWand::mvg_width, _DrawingWand::name, _DrawingWand::path_mode, _DrawingWand::path_operation, _DrawingWand::pattern_bounds, _DrawingWand::pattern_id, _DrawingWand::pattern_offset, _DrawingWand::signature, ThrowWandFatalException, and WandSignature.
WandExport DrawingWand* DestroyDrawingWand (DrawingWand * wand)
Definition at line 627 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::destroy, _DrawingWand::exception, _DrawingWand::graphic_context, _DrawingWand::id, _DrawingWand::image, _DrawingWand::index, _DrawingWand::mvg, _DrawingWand::name, _DrawingWand::pattern_id, RelinquishWandId(), _DrawingWand::signature, and WandSignature.
WandExport void DrawAffine (DrawingWand * wand, const AffineMatrix * affine)
Definition at line 677 of file drawing-wand.c.
References AdjustAffine(), _DrawingWand::debug, MvgPrintf(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport DrawingWand* DrawAllocateWand (const DrawInfo * draw_info, Image * image)
Definition at line 714 of file drawing-wand.c.
References CurrentContext, _DrawingWand::destroy, _DrawingWand::image, and NewDrawingWand().
WandExport void DrawAnnotation (DrawingWand * wand, const double x, const double y, const unsigned char * text)
Definition at line 763 of file drawing-wand.c.
References _DrawingWand::debug, MvgPrintf(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport void DrawArc (DrawingWand * wand, const double sx, const double sy, const double ex, const double ey, const double sd, const double ed)
Definition at line 818 of file drawing-wand.c.
References _DrawingWand::debug, MvgPrintf(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport void DrawBezier (DrawingWand * wand, const size_t number_coordinates, const PointInfo * coordinates)
Definition at line 856 of file drawing-wand.c.
References _DrawingWand::debug, MvgAppendPointsCommand(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport void DrawCircle (DrawingWand * wand, const double ox, const double oy, const double px, const double py)
Definition at line 898 of file drawing-wand.c.
References _DrawingWand::debug, MvgPrintf(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport MagickBooleanType DrawClearException (DrawingWand * wand)
Definition at line 930 of file drawing-wand.c.
References _DrawingWand::debug, _DrawingWand::exception, _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport void DrawColor (DrawingWand * wand, const double x, const double y, const PaintMethod paint_method)
Definition at line 1101 of file drawing-wand.c.
References _DrawingWand::debug, MvgPrintf(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport void DrawComment (DrawingWand * wand, const char * comment)
Definition at line 1136 of file drawing-wand.c.
References MvgPrintf().
WandExport MagickBooleanType DrawComposite (DrawingWand * wand, const CompositeOperator compose, const double x, const double y, const double width, const double height, MagickWand * magick_wand)
Definition at line 981 of file drawing-wand.c.
References _DrawingWand::debug, _DrawingWand::exception, GetImageFromMagickWand(), MaxTextExtent, MvgPrintf(), _DrawingWand::name, _DrawingWand::signature, ThrowDrawException, and WandSignature.
WandExport void DrawEllipse (DrawingWand * wand, const double ox, const double oy, const double rx, const double ry, const double start, const double end)
Definition at line 1176 of file drawing-wand.c.
References _DrawingWand::debug, MvgPrintf(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport double DrawGetAlpha (const DrawingWand * wand)
Definition at line 1815 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport void DrawGetBorderColor (const DrawingWand * wand, PixelWand * border_color)
Definition at line 1213 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::name, PixelSetPixelColor(), _DrawingWand::signature, and WandSignature.
WandExport char* DrawGetClipPath (const DrawingWand * wand)
Definition at line 1247 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport FillRule DrawGetClipRule (const DrawingWand * wand)
Definition at line 1281 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport ClipPathUnits DrawGetClipUnits (const DrawingWand * wand)
Definition at line 1312 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport char* DrawGetException (const DrawingWand * wand, ExceptionType * severity)
Definition at line 1347 of file drawing-wand.c.
References _DrawingWand::debug, _DrawingWand::exception, MaxTextExtent, _DrawingWand::name, _DrawingWand::signature, ThrowWandFatalException, and WandSignature.
WandExport ExceptionType DrawGetExceptionType (const DrawingWand * wand)
Definition at line 1403 of file drawing-wand.c.
References _DrawingWand::debug, _DrawingWand::exception, _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport double DrawGetFillAlpha (const DrawingWand * wand)
Definition at line 1470 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport void DrawGetFillColor (const DrawingWand * wand, PixelWand * fill_color)
Definition at line 1437 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::name, PixelSetPixelColor(), _DrawingWand::signature, and WandSignature.
Referenced by MagickMontageImage().
WandExport FillRule DrawGetFillRule (const DrawingWand * wand)
Definition at line 1505 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport char* DrawGetFont (const DrawingWand * wand)
Definition at line 1538 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::name, _DrawingWand::signature, and WandSignature.
Referenced by MagickMontageImage().
WandExport char* DrawGetFontFamily (const DrawingWand * wand)
Definition at line 1572 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport MagickBooleanType DrawGetFontResolution (const DrawingWand * wand, double * x, double * y)
Definition at line 1610 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport double DrawGetFontSize (const DrawingWand * wand)
Definition at line 1658 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::name, _DrawingWand::signature, and WandSignature.
Referenced by MagickMontageImage().
WandExport StretchType DrawGetFontStretch (const DrawingWand * wand)
Definition at line 1689 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport StyleType DrawGetFontStyle (const DrawingWand * wand)
Definition at line 1720 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport size_t DrawGetFontWeight (const DrawingWand * wand)
Definition at line 1751 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport GravityType DrawGetGravity (const DrawingWand * wand)
Definition at line 1783 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport double DrawGetStrokeAlpha (const DrawingWand * wand)
Definition at line 2123 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport MagickBooleanType DrawGetStrokeAntialias (const DrawingWand * wand)
Definition at line 1853 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport void DrawGetStrokeColor (const DrawingWand * wand, PixelWand * stroke_color)
Definition at line 1887 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::name, PixelSetPixelColor(), _DrawingWand::signature, and WandSignature.
Referenced by MagickMontageImage().
WandExport double* DrawGetStrokeDashArray (const DrawingWand * wand, size_t * number_elements)
Definition at line 1925 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport double DrawGetStrokeDashOffset (const DrawingWand * wand)
Definition at line 1990 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport LineCap DrawGetStrokeLineCap (const DrawingWand * wand)
Definition at line 2023 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport LineJoin DrawGetStrokeLineJoin (const DrawingWand * wand)
Definition at line 2057 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport size_t DrawGetStrokeMiterLimit (const DrawingWand * wand)
Definition at line 2092 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport double DrawGetStrokeWidth (const DrawingWand * wand)
Definition at line 2159 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport AlignType DrawGetTextAlignment (const DrawingWand * wand)
Definition at line 2191 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport MagickBooleanType DrawGetTextAntialias (const DrawingWand * wand)
Definition at line 2223 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport DecorationType DrawGetTextDecoration (const DrawingWand * wand)
Definition at line 2255 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport char* DrawGetTextEncoding (const DrawingWand * wand)
Definition at line 2288 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport double DrawGetTextInterlineSpacing (DrawingWand * wand)
Definition at line 2353 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport double DrawGetTextInterwordSpacing (DrawingWand * wand)
Definition at line 2384 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport double DrawGetTextKerning (DrawingWand * wand)
Definition at line 2321 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport void DrawGetTextUnderColor (const DrawingWand * wand, PixelWand * under_color)
Definition at line 2667 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::name, PixelSetPixelColor(), _DrawingWand::signature, and WandSignature.
WandExport char* DrawGetVectorGraphics (DrawingWand * wand)
Definition at line 2418 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::image, MaxTextExtent, _DrawingWand::mvg, _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport void DrawLine (DrawingWand * wand, const double sx, const double sy, const double ex, const double ey)
Definition at line 2710 of file drawing-wand.c.
References _DrawingWand::debug, MvgPrintf(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport void DrawMatte (DrawingWand * wand, const double x, const double y, const PaintMethod paint_method)
Definition at line 2759 of file drawing-wand.c.
References _DrawingWand::debug, MvgPrintf(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport void DrawPathClose (DrawingWand * wand)
Definition at line 2795 of file drawing-wand.c.
References AbsolutePathMode, _DrawingWand::debug, MvgAutoWrapPrintf(), _DrawingWand::name, _DrawingWand::path_mode, _DrawingWand::signature, and WandSignature.
static void DrawPathCurveTo (DrawingWand * wand, const PathMode mode, const double x1, const double y1, const double x2, const double y2, const double x, const double y) static
Definition at line 2846 of file drawing-wand.c.
References AbsolutePathMode, _DrawingWand::debug, MvgAutoWrapPrintf(), _DrawingWand::name, _DrawingWand::path_mode, _DrawingWand::path_operation, PathCurveToOperation, _DrawingWand::signature, and WandSignature.
Referenced by DrawPathCurveToAbsolute(), and DrawPathCurveToRelative().
WandExport void DrawPathCurveToAbsolute (DrawingWand * wand, const double x1, const double y1, const double x2, const double y2, const double x, const double y)
Definition at line 2867 of file drawing-wand.c.
References AbsolutePathMode, _DrawingWand::debug, DrawPathCurveTo(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
static void DrawPathCurveToQuadraticBezier (DrawingWand * wand, const PathMode mode, const double x1, double y1, const double x, const double y) static
Definition at line 2962 of file drawing-wand.c.
References AbsolutePathMode, _DrawingWand::debug, MvgAutoWrapPrintf(), _DrawingWand::name, _DrawingWand::path_mode, _DrawingWand::path_operation, PathCurveToQuadraticBezierOperation, _DrawingWand::signature, and WandSignature.
Referenced by DrawPathCurveToQuadraticBezierAbsolute(), and DrawPathCurveToQuadraticBezierRelative().
WandExport void DrawPathCurveToQuadraticBezierAbsolute (DrawingWand * wand, const double x1, const double y1, const double x, const double y)
Definition at line 2981 of file drawing-wand.c.
References AbsolutePathMode, _DrawingWand::debug, DrawPathCurveToQuadraticBezier(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport void DrawPathCurveToQuadraticBezierRelative (DrawingWand * wand, const double x1, const double y1, const double x, const double y)
Definition at line 3025 of file drawing-wand.c.
References _DrawingWand::debug, DrawPathCurveToQuadraticBezier(), _DrawingWand::name, RelativePathMode, _DrawingWand::signature, and WandSignature.
static void DrawPathCurveToQuadraticBezierSmooth (DrawingWand * wand, const PathMode mode, const double x, const double y) static
Definition at line 3074 of file drawing-wand.c.
References AbsolutePathMode, _DrawingWand::debug, MvgAutoWrapPrintf(), _DrawingWand::name, _DrawingWand::path_mode, _DrawingWand::path_operation, PathCurveToQuadraticBezierSmoothOperation, _DrawingWand::signature, and WandSignature.
Referenced by DrawPathCurveToQuadraticBezierSmoothAbsolute(), and DrawPathCurveToQuadraticBezierSmoothRelative().
WandExport void DrawPathCurveToQuadraticBezierSmoothAbsolute (DrawingWand * wand, const double x, const double y)
Definition at line 3093 of file drawing-wand.c.
References AbsolutePathMode, _DrawingWand::debug, DrawPathCurveToQuadraticBezierSmooth(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport void DrawPathCurveToQuadraticBezierSmoothRelative (DrawingWand * wand, const double x, const double y)
Definition at line 3140 of file drawing-wand.c.
References DrawPathCurveToQuadraticBezierSmooth(), and RelativePathMode.
WandExport void DrawPathCurveToRelative (DrawingWand * wand, const double x1, const double y1, const double x2, const double y2, const double x, const double y)
Definition at line 2917 of file drawing-wand.c.
References _DrawingWand::debug, DrawPathCurveTo(), _DrawingWand::name, RelativePathMode, _DrawingWand::signature, and WandSignature.
static void DrawPathCurveToSmooth (DrawingWand * wand, const PathMode mode, const double x2, const double y2, const double x, const double y) static
Definition at line 3188 of file drawing-wand.c.
References AbsolutePathMode, _DrawingWand::debug, MvgAutoWrapPrintf(), _DrawingWand::name, _DrawingWand::path_mode, _DrawingWand::path_operation, PathCurveToSmoothOperation, _DrawingWand::signature, and WandSignature.
Referenced by DrawPathCurveToSmoothAbsolute(), and DrawPathCurveToSmoothRelative().
WandExport void DrawPathCurveToSmoothAbsolute (DrawingWand * wand, const double x2, const double y2, const double x, const double y)
Definition at line 3207 of file drawing-wand.c.
References AbsolutePathMode, _DrawingWand::debug, DrawPathCurveToSmooth(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport void DrawPathCurveToSmoothRelative (DrawingWand * wand, const double x2, const double y2, const double x, const double y)
Definition at line 3257 of file drawing-wand.c.
References _DrawingWand::debug, DrawPathCurveToSmooth(), _DrawingWand::name, RelativePathMode, _DrawingWand::signature, and WandSignature.
static void DrawPathEllipticArc (DrawingWand * wand, const PathMode mode, const double rx, const double ry, const double x_axis_rotation, const MagickBooleanType large_arc_flag, const MagickBooleanType sweep_flag, const double x, const double y) static
Definition at line 3316 of file drawing-wand.c.
References AbsolutePathMode, _DrawingWand::debug, MvgAutoWrapPrintf(), _DrawingWand::name, _DrawingWand::path_mode, _DrawingWand::path_operation, PathEllipticArcOperation, _DrawingWand::signature, and WandSignature.
Referenced by DrawPathEllipticArcAbsolute(), and DrawPathEllipticArcRelative().
WandExport void DrawPathEllipticArcAbsolute (DrawingWand * wand, const double rx, const double ry, const double x_axis_rotation, const MagickBooleanType large_arc_flag, const MagickBooleanType sweep_flag, const double x, const double y)
Definition at line 3339 of file drawing-wand.c.
References AbsolutePathMode, _DrawingWand::debug, DrawPathEllipticArc(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport void DrawPathEllipticArcRelative (DrawingWand * wand, const double rx, const double ry, const double x_axis_rotation, const MagickBooleanType large_arc_flag, const MagickBooleanType sweep_flag, const double x, const double y)
Definition at line 3399 of file drawing-wand.c.
References DrawPathEllipticArc(), and RelativePathMode.
WandExport void DrawPathFinish (DrawingWand * wand)
Definition at line 3430 of file drawing-wand.c.
References _DrawingWand::debug, DefaultPathMode, MvgPrintf(), _DrawingWand::name, _DrawingWand::path_mode, _DrawingWand::path_operation, PathDefaultOperation, _DrawingWand::signature, and WandSignature.
static void DrawPathLineTo (DrawingWand * wand, const PathMode mode, const double x, const double y) static
Definition at line 3470 of file drawing-wand.c.
References AbsolutePathMode, _DrawingWand::debug, MvgAutoWrapPrintf(), _DrawingWand::name, _DrawingWand::path_mode, _DrawingWand::path_operation, PathLineToOperation, _DrawingWand::signature, and WandSignature.
Referenced by DrawPathLineToAbsolute(), and DrawPathLineToRelative().
WandExport void DrawPathLineToAbsolute (DrawingWand * wand, const double x, const double y)
Definition at line 3489 of file drawing-wand.c.
References AbsolutePathMode, _DrawingWand::debug, DrawPathLineTo(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
static void DrawPathLineToHorizontal (DrawingWand * wand, const PathMode mode, const double x) static
Definition at line 3565 of file drawing-wand.c.
References AbsolutePathMode, _DrawingWand::debug, MvgAutoWrapPrintf(), _DrawingWand::name, _DrawingWand::path_mode, _DrawingWand::path_operation, PathLineToHorizontalOperation, _DrawingWand::signature, and WandSignature.
Referenced by DrawPathLineToHorizontalAbsolute(), and DrawPathLineToHorizontalRelative().
WandExport void DrawPathLineToHorizontalAbsolute (DrawingWand * wand, const double x)
Definition at line 3584 of file drawing-wand.c.
References AbsolutePathMode, _DrawingWand::debug, DrawPathLineToHorizontal(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport void DrawPathLineToHorizontalRelative (DrawingWand * wand, const double x)
Definition at line 3621 of file drawing-wand.c.
References DrawPathLineToHorizontal(), and RelativePathMode.
WandExport void DrawPathLineToRelative (DrawingWand * wand, const double x, const double y)
Definition at line 3528 of file drawing-wand.c.
References _DrawingWand::debug, DrawPathLineTo(), _DrawingWand::name, RelativePathMode, _DrawingWand::signature, and WandSignature.
static void DrawPathLineToVertical (DrawingWand * wand, const PathMode mode, const double y) static
Definition at line 3655 of file drawing-wand.c.
References AbsolutePathMode, _DrawingWand::debug, MvgAutoWrapPrintf(), _DrawingWand::name, _DrawingWand::path_mode, _DrawingWand::path_operation, PathLineToVerticalOperation, _DrawingWand::signature, and WandSignature.
Referenced by DrawPathLineToVerticalAbsolute(), and DrawPathLineToVerticalRelative().
WandExport void DrawPathLineToVerticalAbsolute (DrawingWand * wand, const double y)
Definition at line 3674 of file drawing-wand.c.
References AbsolutePathMode, _DrawingWand::debug, DrawPathLineToVertical(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport void DrawPathLineToVerticalRelative (DrawingWand * wand, const double y)
Definition at line 3710 of file drawing-wand.c.
References _DrawingWand::debug, DrawPathLineToVertical(), _DrawingWand::name, RelativePathMode, _DrawingWand::signature, and WandSignature.
static void DrawPathMoveTo (DrawingWand * wand, const PathMode mode, const double x, const double y) static
Definition at line 3748 of file drawing-wand.c.
References AbsolutePathMode, _DrawingWand::debug, MvgAutoWrapPrintf(), _DrawingWand::name, _DrawingWand::path_mode, _DrawingWand::path_operation, PathMoveToOperation, _DrawingWand::signature, and WandSignature.
Referenced by DrawPathMoveToAbsolute(), and DrawPathMoveToRelative().
WandExport void DrawPathMoveToAbsolute (DrawingWand * wand, const double x, const double y)
Definition at line 3767 of file drawing-wand.c.
References AbsolutePathMode, _DrawingWand::debug, DrawPathMoveTo(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport void DrawPathMoveToRelative (DrawingWand * wand, const double x, const double y)
Definition at line 3806 of file drawing-wand.c.
References _DrawingWand::debug, DrawPathMoveTo(), _DrawingWand::name, RelativePathMode, _DrawingWand::signature, and WandSignature.
WandExport void DrawPathStart (DrawingWand * wand)
Definition at line 3842 of file drawing-wand.c.
References _DrawingWand::debug, DefaultPathMode, MvgPrintf(), _DrawingWand::name, _DrawingWand::path_mode, _DrawingWand::path_operation, PathDefaultOperation, _DrawingWand::signature, and WandSignature.
WandExport void DrawPoint (DrawingWand * wand, const double x, const double y)
Definition at line 3879 of file drawing-wand.c.
References _DrawingWand::debug, MvgPrintf(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport void DrawPolygon (DrawingWand * wand, const size_t number_coordinates, const PointInfo * coordinates)
Definition at line 3916 of file drawing-wand.c.
References _DrawingWand::debug, MvgAppendPointsCommand(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport void DrawPolyline (DrawingWand * wand, const size_t number_coordinates, const PointInfo * coordinates)
Definition at line 3954 of file drawing-wand.c.
References _DrawingWand::debug, MvgAppendPointsCommand(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport void DrawPopClipPath (DrawingWand * wand)
Definition at line 3986 of file drawing-wand.c.
References _DrawingWand::debug, _DrawingWand::indent_depth, MvgPrintf(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport void DrawPopDefs (DrawingWand * wand)
Definition at line 4019 of file drawing-wand.c.
References _DrawingWand::debug, _DrawingWand::indent_depth, MvgPrintf(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport MagickBooleanType DrawPopPattern (DrawingWand * wand)
Definition at line 4052 of file drawing-wand.c.
References _DrawingWand::debug, _DrawingWand::filter_off, _DrawingWand::image, _DrawingWand::indent_depth, MaxTextExtent, _DrawingWand::mvg, MvgPrintf(), _DrawingWand::name, _DrawingWand::pattern_bounds, _DrawingWand::pattern_id, _DrawingWand::pattern_offset, _DrawingWand::signature, ThrowDrawException, and WandSignature.
WandExport void DrawPushClipPath (DrawingWand * wand, const char * clip_mask_id)
Definition at line 4115 of file drawing-wand.c.
References _DrawingWand::debug, _DrawingWand::indent_depth, MvgPrintf(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport void DrawPushDefs (DrawingWand * wand)
Definition at line 4150 of file drawing-wand.c.
References _DrawingWand::debug, _DrawingWand::indent_depth, MvgPrintf(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport MagickBooleanType DrawPushPattern (DrawingWand * wand, const char * pattern_id, const double x, const double y, const double width, const double height)
Definition at line 4199 of file drawing-wand.c.
References _DrawingWand::debug, _DrawingWand::filter_off, _DrawingWand::indent_depth, _DrawingWand::mvg_length, MvgPrintf(), _DrawingWand::name, _DrawingWand::pattern_bounds, _DrawingWand::pattern_id, _DrawingWand::pattern_offset, _DrawingWand::signature, ThrowDrawException, and WandSignature.
WandExport void DrawRectangle (DrawingWand * wand, const double x1, const double y1, const double x2, const double y2)
Definition at line 4257 of file drawing-wand.c.
References _DrawingWand::debug, MvgPrintf(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport MagickBooleanType DrawRender (DrawingWand * wand)
Definition at line 4289 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::exception, _DrawingWand::image, _DrawingWand::mvg, _DrawingWand::name, _DrawingWand::signature, ThrowDrawException, and WandSignature.
WandExport void DrawResetVectorGraphics (DrawingWand * wand)
Definition at line 4331 of file drawing-wand.c.
References _DrawingWand::debug, _DrawingWand::mvg, _DrawingWand::mvg_alloc, _DrawingWand::mvg_length, _DrawingWand::mvg_width, _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport void DrawRotate (DrawingWand * wand, const double degrees)
Definition at line 4368 of file drawing-wand.c.
References _DrawingWand::debug, MvgPrintf(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport void DrawRoundRectangle (DrawingWand * wand, double x1, double y1, double x2, double y2, double rx, double ry)
Definition at line 4414 of file drawing-wand.c.
References _DrawingWand::debug, MvgPrintf(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport void DrawScale (DrawingWand * wand, const double x, const double y)
Definition at line 4452 of file drawing-wand.c.
References _DrawingWand::debug, MvgPrintf(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport void DrawSetAlpha (DrawingWand * wand, const double alpha)
Definition at line 4815 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::filter_off, MvgPrintf(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport void DrawSetBorderColor (DrawingWand * wand, const PixelWand * border_wand)
Definition at line 4486 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::filter_off, MvgAppendColor(), MvgPrintf(), _DrawingWand::name, PixelGetQuantumPacket(), _DrawingWand::signature, and WandSignature.
WandExport MagickBooleanType DrawSetClipPath (DrawingWand * wand, const char * clip_mask)
Definition at line 4539 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::filter_off, _DrawingWand::image, MvgPrintf(), _DrawingWand::name, _DrawingWand::signature, ThrowDrawException, and WandSignature.
WandExport void DrawSetClipRule (DrawingWand * wand, const FillRule fill_rule)
Definition at line 4586 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::filter_off, MvgPrintf(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport void DrawSetClipUnits (DrawingWand * wand, const ClipPathUnits clip_units)
Definition at line 4627 of file drawing-wand.c.
References AdjustAffine(), CurrentContext, _DrawingWand::debug, _DrawingWand::filter_off, MvgPrintf(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport void DrawSetFillAlpha (DrawingWand * wand, const double fill_alpha)
Definition at line 4729 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::filter_off, MvgPrintf(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport void DrawSetFillColor (DrawingWand * wand, const PixelWand * fill_wand)
Definition at line 4679 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::filter_off, MvgAppendColor(), MvgPrintf(), _DrawingWand::name, PixelGetQuantumPacket(), _DrawingWand::signature, and WandSignature.
WandExport MagickBooleanType DrawSetFillPatternURL (DrawingWand * wand, const char * fill_url)
Definition at line 4861 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::image, MaxTextExtent, MvgPrintf(), _DrawingWand::name, _DrawingWand::signature, ThrowDrawException, and WandSignature.
WandExport void DrawSetFillRule (DrawingWand * wand, const FillRule fill_rule)
Definition at line 4921 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::filter_off, MvgPrintf(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport MagickBooleanType DrawSetFont (DrawingWand * wand, const char * font_name)
Definition at line 4961 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::filter_off, MvgPrintf(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport MagickBooleanType DrawSetFontFamily (DrawingWand * wand, const char * font_family)
Definition at line 5004 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::filter_off, MvgPrintf(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport MagickBooleanType DrawSetFontResolution (DrawingWand * wand, const double x_resolution, const double y_resolution)
Definition at line 4774 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, MaxTextExtent, _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport void DrawSetFontSize (DrawingWand * wand, const double pointsize)
Definition at line 5046 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::filter_off, MvgPrintf(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport void DrawSetFontStretch (DrawingWand * wand, const StretchType font_stretch)
Definition at line 5089 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::filter_off, MvgPrintf(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport void DrawSetFontStyle (DrawingWand * wand, const StyleType style)
Definition at line 5130 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::filter_off, MvgPrintf(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport void DrawSetFontWeight (DrawingWand * wand, const size_t font_weight)
Definition at line 5170 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::filter_off, MvgPrintf(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport void DrawSetGravity (DrawingWand * wand, const GravityType gravity)
Definition at line 5213 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::filter_off, MvgPrintf(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport void DrawSetStrokeAlpha (DrawingWand * wand, const double stroke_alpha)
Definition at line 5695 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::filter_off, MvgPrintf(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport void DrawSetStrokeAntialias (DrawingWand * wand, const MagickBooleanType stroke_antialias)
Definition at line 5365 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::filter_off, MvgPrintf(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport void DrawSetStrokeColor (DrawingWand * wand, const PixelWand * stroke_wand)
Definition at line 5253 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::filter_off, MvgAppendColor(), MvgPrintf(), _DrawingWand::name, PixelGetQuantumPacket(), _DrawingWand::signature, and WandSignature.
WandExport MagickBooleanType DrawSetStrokeDashArray (DrawingWand * wand, const size_t number_elements, const double * dash_array)
Definition at line 5414 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::filter_off, MvgPrintf(), _DrawingWand::name, _DrawingWand::signature, ThrowDrawException, and WandSignature.
WandExport void DrawSetStrokeDashOffset (DrawingWand * wand, const double dash_offset)
Definition at line 5528 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::filter_off, MvgPrintf(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport void DrawSetStrokeLineCap (DrawingWand * wand, const LineCap linecap)
Definition at line 5570 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::filter_off, MvgPrintf(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport void DrawSetStrokeLineJoin (DrawingWand * wand, const LineJoin linejoin)
Definition at line 5612 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::filter_off, MvgPrintf(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport void DrawSetStrokeMiterLimit (DrawingWand * wand, const size_t miterlimit)
Definition at line 5656 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, MvgPrintf(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport MagickBooleanType DrawSetStrokePatternURL (DrawingWand * wand, const char * stroke_url)
Definition at line 5304 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::image, MaxTextExtent, MvgPrintf(), _DrawingWand::name, _DrawingWand::signature, ThrowDrawException, and WandSignature.
WandExport void DrawSetStrokeWidth (DrawingWand * wand, const double stroke_width)
Definition at line 5740 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::filter_off, MvgPrintf(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport void DrawSetTextAlignment (DrawingWand * wand, const AlignType alignment)
Definition at line 5780 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::filter_off, MvgPrintf(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport void DrawSetTextAntialias (DrawingWand * wand, const MagickBooleanType text_antialias)
Definition at line 5823 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::filter_off, MvgPrintf(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport void DrawSetTextDecoration (DrawingWand * wand, const DecorationType decoration)
Definition at line 5865 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::filter_off, MvgPrintf(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport void DrawSetTextEncoding (DrawingWand * wand, const char * encoding)
Definition at line 5910 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::filter_off, MvgPrintf(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport void DrawSetTextInterlineSpacing (DrawingWand * wand, const double interline_spacing)
Definition at line 5990 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::filter_off, MvgPrintf(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport void DrawSetTextInterwordSpacing (DrawingWand * wand, const double interword_spacing)
Definition at line 6031 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::filter_off, MvgPrintf(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport void DrawSetTextKerning (DrawingWand * wand, const double kerning)
Definition at line 5950 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::filter_off, MvgPrintf(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport void DrawSetTextUnderColor (DrawingWand * wand, const PixelWand * under_wand)
Definition at line 6073 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::filter_off, MvgAppendColor(), MvgPrintf(), _DrawingWand::name, PixelGetQuantumPacket(), _DrawingWand::signature, and WandSignature.
WandExport MagickBooleanType DrawSetVectorGraphics (DrawingWand * wand, const char * xml)
Definition at line 6136 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::exception, IsPoint(), MaxTextExtent, _DrawingWand::mvg, _DrawingWand::mvg_alloc, _DrawingWand::mvg_length, _DrawingWand::name, _DrawingWand::signature, ThrowWandFatalException, and WandSignature.
WandExport void DrawSetViewbox (DrawingWand * wand, const double x1, const double y1, const double x2, const double y2)
Definition at line 6542 of file drawing-wand.c.
References _DrawingWand::debug, MvgPrintf(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport void DrawSkewX (DrawingWand * wand, const double degrees)
Definition at line 6426 of file drawing-wand.c.
References _DrawingWand::debug, MvgPrintf(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport void DrawSkewY (DrawingWand * wand, const double degrees)
Definition at line 6460 of file drawing-wand.c.
References _DrawingWand::debug, MvgPrintf(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport void DrawTranslate (DrawingWand * wand, const double x, const double y)
Definition at line 6498 of file drawing-wand.c.
References _DrawingWand::debug, MvgPrintf(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
WandExport MagickBooleanType IsDrawingWand (const DrawingWand * wand)
Definition at line 6574 of file drawing-wand.c.
References DrawingWandId, _DrawingWand::name, _DrawingWand::signature, and WandSignature.
static MagickBooleanType IsPoint (const char * point) inline static
Definition at line 6123 of file drawing-wand.c.
Referenced by DrawSetVectorGraphics().
static void MvgAppendColor (DrawingWand * wand, const PixelInfo * packet) static
Definition at line 389 of file drawing-wand.c.
References _DrawingWand::image, MaxTextExtent, and MvgPrintf().
Referenced by DrawSetBorderColor(), DrawSetFillColor(), DrawSetStrokeColor(), and DrawSetTextUnderColor().
static void MvgAppendPointsCommand (DrawingWand * wand, const char * command, const size_t number_coordinates, const PointInfo * coordinates) static
Definition at line 415 of file drawing-wand.c.
References MvgAutoWrapPrintf(), and MvgPrintf().
Referenced by DrawBezier(), DrawPolygon(), and DrawPolyline().
static int MvgAutoWrapPrintf (DrawingWand * wand, const char * format, ...) static
Definition at line 359 of file drawing-wand.c.
References MaxTextExtent, _DrawingWand::mvg_width, MvgPrintf(), and ThrowDrawException.
Referenced by DrawPathClose(), DrawPathCurveTo(), DrawPathCurveToQuadraticBezier(), DrawPathCurveToQuadraticBezierSmooth(), DrawPathCurveToSmooth(), DrawPathEllipticArc(), DrawPathLineTo(), DrawPathLineToHorizontal(), DrawPathLineToVertical(), DrawPathMoveTo(), and MvgAppendPointsCommand().
static int MvgPrintf (DrawingWand * , wand_attribute((format (const char *, ...) static
Definition at line 269 of file drawing-wand.c.
References MaxTextExtent, ThrowDrawException, and WandSignature.
Referenced by DrawAffine(), DrawAnnotation(), DrawArc(), DrawCircle(), DrawColor(), DrawComment(), DrawComposite(), DrawEllipse(), DrawLine(), DrawMatte(), DrawPathFinish(), DrawPathStart(), DrawPoint(), DrawPopClipPath(), DrawPopDefs(), DrawPopPattern(), DrawPushClipPath(), DrawPushDefs(), DrawPushPattern(), DrawRectangle(), DrawRotate(), DrawRoundRectangle(), DrawScale(), DrawSetAlpha(), DrawSetBorderColor(), DrawSetClipPath(), DrawSetClipRule(), DrawSetClipUnits(), DrawSetFillAlpha(), DrawSetFillColor(), DrawSetFillPatternURL(), DrawSetFillRule(), DrawSetFont(), DrawSetFontFamily(), DrawSetFontSize(), DrawSetFontStretch(), DrawSetFontStyle(), DrawSetFontWeight(), DrawSetGravity(), DrawSetStrokeAlpha(), DrawSetStrokeAntialias(), DrawSetStrokeColor(), DrawSetStrokeDashArray(), DrawSetStrokeDashOffset(), DrawSetStrokeLineCap(), DrawSetStrokeLineJoin(), DrawSetStrokeMiterLimit(), DrawSetStrokePatternURL(), DrawSetStrokeWidth(), DrawSetTextAlignment(), DrawSetTextAntialias(), DrawSetTextDecoration(), DrawSetTextEncoding(), DrawSetTextInterlineSpacing(), DrawSetTextInterwordSpacing(), DrawSetTextKerning(), DrawSetTextUnderColor(), DrawSetViewbox(), DrawSkewX(), DrawSkewY(), DrawTranslate(), MvgAppendColor(), MvgAppendPointsCommand(), MvgAutoWrapPrintf(), PopDrawingWand(), and PushDrawingWand().
WandExport DrawingWand* NewDrawingWand (void)
Definition at line 6604 of file drawing-wand.c.
References AcquireWandId(), CurrentContext, _DrawingWand::debug, DefaultPathMode, _DrawingWand::destroy, DrawingWandId, _DrawingWand::exception, _DrawingWand::filter_off, _DrawingWand::graphic_context, _DrawingWand::id, _DrawingWand::image, _DrawingWand::indent_depth, _DrawingWand::index, MaxTextExtent, _DrawingWand::mvg, _DrawingWand::mvg_alloc, _DrawingWand::mvg_length, _DrawingWand::mvg_width, _DrawingWand::name, _DrawingWand::path_mode, _DrawingWand::path_operation, PathDefaultOperation, _DrawingWand::pattern_bounds, _DrawingWand::pattern_id, _DrawingWand::pattern_offset, _DrawingWand::signature, ThrowWandFatalException, and WandSignature.
Referenced by DrawAllocateWand().
WandExport DrawInfo* PeekDrawingWand (const DrawingWand * wand)
Definition at line 6679 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::mvg, _DrawingWand::name, _DrawingWand::signature, and WandSignature.
Referenced by MagickAffineTransformImage(), MagickAnnotateImage(), MagickDrawImage(), MagickPolaroidImage(), MagickQueryFontMetrics(), and MagickQueryMultilineFontMetrics().
WandExport MagickBooleanType PopDrawingWand (DrawingWand * wand)
Definition at line 6719 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::graphic_context, _DrawingWand::image, _DrawingWand::indent_depth, _DrawingWand::index, MvgPrintf(), _DrawingWand::name, _DrawingWand::signature, ThrowDrawException, and WandSignature.
WandExport MagickBooleanType PushDrawingWand (DrawingWand * wand)
Definition at line 6774 of file drawing-wand.c.
References CurrentContext, _DrawingWand::debug, _DrawingWand::graphic_context, _DrawingWand::indent_depth, _DrawingWand::index, MvgPrintf(), _DrawingWand::name, _DrawingWand::signature, ThrowDrawException, and WandSignature.