MagickWand: import.c File Reference
import.c File Reference
#include "MagickWand/studio.h"
#include "MagickWand/MagickWand.h"
#include "MagickWand/mogrify-private.h"
#include "MagickCore/string-private.h"
#include "MagickCore/xwindow-private.h"
Functions
static MagickBooleanType ImportUsage (void)
static ssize_t MagickMax (const ssize_t x, const ssize_t y)
WandExport MagickBooleanType ImportImageCommand (ImageInfo *image_info, int argc, char **argv, char **wand_unused(metadata), ExceptionInfo *exception)
Function Documentation
WandExport MagickBooleanType ImportImageCommand (ImageInfo * image_info, int argc, char ** argv, char ** wand_unusedmetadata, ExceptionInfo * exception)
Definition at line 218 of file import.c.
References AppendImageStack, FinalizeImageSettings, FireImageStack, _DrawingWand::image, ImportUsage(), MagickMax(), MaxImageStackDepth, MaxTextExtent, MogrifyImageInfo(), NewImageStack, PopImageStack, PushImageStack, ReadCommandlLine, and SetNotifyHandlers.
static MagickBooleanType ImportUsage (void) static
Definition at line 93 of file import.c.
Referenced by ImportImageCommand().
static ssize_t MagickMax (const ssize_t x, const ssize_t y) inline static
Definition at line 211 of file import.c.
Referenced by ImportImageCommand().