MagickWand: magick-image.c File Reference
magick-image.c File Reference
#include "MagickWand/studio.h"
#include "MagickWand/MagickWand.h"
#include "MagickWand/magick-wand-private.h"
#include "MagickWand/wand.h"
#include "MagickWand/pixel-wand-private.h"
Macros
#define ThrowWandException(severity, tag, context)
#define MagickWandId "MagickWand"
Functions
static MagickWand * CloneMagickWandFromImages (const MagickWand *wand, Image *images)
WandExport Image * GetImageFromMagickWand (const MagickWand *wand)
WandExport MagickBooleanType MagickAdaptiveBlurImage (MagickWand *wand, const double radius, const double sigma)
WandExport MagickBooleanType MagickAdaptiveResizeImage (MagickWand *wand, const size_t columns, const size_t rows)
WandExport MagickBooleanType MagickAdaptiveSharpenImage (MagickWand *wand, const double radius, const double sigma)
WandExport MagickBooleanType MagickAdaptiveThresholdImage (MagickWand *wand, const size_t width, const size_t height, const double bias)
static MagickBooleanType InsertImageInWand (MagickWand *wand, Image *images)
WandExport MagickBooleanType MagickAddImage (MagickWand *wand, const MagickWand *add_wand)
WandExport MagickBooleanType MagickAddNoiseImage (MagickWand *wand, const NoiseType noise_type, const double attenuate)
WandExport MagickBooleanType MagickAffineTransformImage (MagickWand *wand, const DrawingWand *drawing_wand)
WandExport MagickBooleanType MagickAnnotateImage (MagickWand *wand, const DrawingWand *drawing_wand, const double x, const double y, const double angle, const char *text)
WandExport MagickBooleanType MagickAnimateImages (MagickWand *wand, const char *server_name)
WandExport MagickWand * MagickAppendImages (MagickWand *wand, const MagickBooleanType stack)
WandExport MagickBooleanType MagickAutoGammaImage (MagickWand *wand)
WandExport MagickBooleanType MagickAutoLevelImage (MagickWand *wand)
WandExport MagickBooleanType MagickBlackThresholdImage (MagickWand *wand, const PixelWand *threshold)
WandExport MagickBooleanType MagickBlueShiftImage (MagickWand *wand, const double factor)
WandExport MagickBooleanType MagickBlurImage (MagickWand *wand, const double radius, const double sigma)
WandExport MagickBooleanType MagickBorderImage (MagickWand *wand, const PixelWand *bordercolor, const size_t width, const size_t height, const CompositeOperator compose)
WandExport MagickBooleanType MagickBrightnessContrastImage (MagickWand *wand, const double brightness, const double contrast)
WandExport MagickWand * MagickChannelFxImage (MagickWand *wand, const char *expression)
WandExport MagickBooleanType MagickCharcoalImage (MagickWand *wand, const double radius, const double sigma)
WandExport MagickBooleanType MagickChopImage (MagickWand *wand, const size_t width, const size_t height, const ssize_t x, const ssize_t y)
WandExport MagickBooleanType MagickClampImage (MagickWand *wand)
WandExport MagickBooleanType MagickClipImage (MagickWand *wand)
WandExport MagickBooleanType MagickClipImagePath (MagickWand *wand, const char *pathname, const MagickBooleanType inside)
WandExport MagickBooleanType MagickClutImage (MagickWand *wand, const MagickWand *clut_wand, const PixelInterpolateMethod method)
WandExport MagickWand * MagickCoalesceImages (MagickWand *wand)
WandExport MagickBooleanType MagickColorDecisionListImage (MagickWand *wand, const char *color_correction_collection)
WandExport MagickBooleanType MagickColorizeImage (MagickWand *wand, const PixelWand *colorize, const PixelWand *blend)
WandExport MagickBooleanType MagickColorMatrixImage (MagickWand *wand, const KernelInfo *color_matrix)
WandExport MagickWand * MagickCombineImages (MagickWand *wand, const ColorspaceType colorspace)
WandExport MagickBooleanType MagickCommentImage (MagickWand *wand, const char *comment)
WandExport MagickWand * MagickCompareImagesLayers (MagickWand *wand, const LayerMethod method)
WandExport MagickWand * MagickCompareImages (MagickWand *wand, const MagickWand *reference, const MetricType metric, double *distortion)
WandExport MagickBooleanType MagickCompositeImage (MagickWand *wand, const MagickWand *source_wand, const CompositeOperator compose, const MagickBooleanType clip_to_self, const ssize_t x, const ssize_t y)
WandExport MagickBooleanType MagickCompositeLayers (MagickWand *wand, const MagickWand *source_wand, const CompositeOperator compose, const ssize_t x, const ssize_t y)
WandExport MagickBooleanType MagickContrastImage (MagickWand *wand, const MagickBooleanType sharpen)
WandExport MagickBooleanType MagickContrastStretchImage (MagickWand *wand, const double black_point, const double white_point)
WandExport MagickBooleanType MagickConvolveImage (MagickWand *wand, const KernelInfo *kernel)
WandExport MagickBooleanType MagickCropImage (MagickWand *wand, const size_t width, const size_t height, const ssize_t x, const ssize_t y)
WandExport MagickBooleanType MagickCycleColormapImage (MagickWand *wand, const ssize_t displace)
WandExport MagickBooleanType MagickConstituteImage (MagickWand *wand, const size_t columns, const size_t rows, const char *map, const StorageType storage, const void *pixels)
WandExport MagickBooleanType MagickDecipherImage (MagickWand *wand, const char *passphrase)
WandExport MagickWand * MagickDeconstructImages (MagickWand *wand)
WandExport MagickBooleanType MagickDeskewImage (MagickWand *wand, const double threshold)
WandExport MagickBooleanType MagickDespeckleImage (MagickWand *wand)
WandExport Image * MagickDestroyImage (Image *image)
WandExport MagickBooleanType MagickDisplayImage (MagickWand *wand, const char *server_name)
WandExport MagickBooleanType MagickDisplayImages (MagickWand *wand, const char *server_name)
WandExport MagickBooleanType MagickDistortImage (MagickWand *wand, const DistortImageMethod method, const size_t number_arguments, const double *arguments, const MagickBooleanType bestfit)
WandExport MagickBooleanType MagickDrawImage (MagickWand *wand, const DrawingWand *drawing_wand)
WandExport MagickBooleanType MagickEdgeImage (MagickWand *wand, const double radius)
WandExport MagickBooleanType MagickEmbossImage (MagickWand *wand, const double radius, const double sigma)
WandExport MagickBooleanType MagickEncipherImage (MagickWand *wand, const char *passphrase)
WandExport MagickBooleanType MagickEnhanceImage (MagickWand *wand)
WandExport MagickBooleanType MagickEqualizeImage (MagickWand *wand)
WandExport MagickWand * MagickEvaluateImages (MagickWand *wand, const MagickEvaluateOperator op)
WandExport MagickBooleanType MagickEvaluateImage (MagickWand *wand, const MagickEvaluateOperator op, const double value)
WandExport MagickBooleanType MagickExportImagePixels (MagickWand *wand, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, const char *map, const StorageType storage, void *pixels)
WandExport MagickBooleanType MagickExtentImage (MagickWand *wand, const size_t width, const size_t height, const ssize_t x, const ssize_t y)
WandExport MagickBooleanType MagickFlipImage (MagickWand *wand)
WandExport MagickBooleanType MagickFloodfillPaintImage (MagickWand *wand, const PixelWand *fill, const double fuzz, const PixelWand *bordercolor, const ssize_t x, const ssize_t y, const MagickBooleanType invert)
WandExport MagickBooleanType MagickFlopImage (MagickWand *wand)
WandExport MagickBooleanType MagickForwardFourierTransformImage (MagickWand *wand, const MagickBooleanType magnitude)
WandExport MagickBooleanType MagickFrameImage (MagickWand *wand, const PixelWand *matte_color, const size_t width, const size_t height, const ssize_t inner_bevel, const ssize_t outer_bevel, const CompositeOperator compose)
WandExport MagickBooleanType MagickFunctionImage (MagickWand *wand, const MagickFunction function, const size_t number_arguments, const double *arguments)
WandExport MagickWand * MagickFxImage (MagickWand *wand, const char *expression)
WandExport MagickBooleanType MagickGammaImage (MagickWand *wand, const double gamma)
WandExport MagickBooleanType MagickGaussianBlurImage (MagickWand *wand, const double radius, const double sigma)
WandExport MagickWand * MagickGetImage (MagickWand *wand)
WandExport MagickBooleanType MagickGetImageAlphaChannel (MagickWand *wand)
WandExport MagickWand * MagickGetImageMask (MagickWand *wand)
WandExport MagickBooleanType MagickGetImageBackgroundColor (MagickWand *wand, PixelWand *background_color)
WandExport unsigned char * MagickGetImageBlob (MagickWand *wand, size_t *length)
WandExport unsigned char * MagickGetImagesBlob (MagickWand *wand, size_t *length)
WandExport MagickBooleanType MagickGetImageBluePrimary (MagickWand *wand, double *x, double *y)
WandExport MagickBooleanType MagickGetImageBorderColor (MagickWand *wand, PixelWand *border_color)
WandExport ChannelFeatures * MagickGetImageFeatures (MagickWand *wand, const size_t distance)
WandExport MagickBooleanType MagickGetImageKurtosis (MagickWand *wand, double *kurtosis, double *skewness)
WandExport MagickBooleanType MagickGetImageMean (MagickWand *wand, double *mean, double *standard_deviation)
WandExport MagickBooleanType MagickGetImageRange (MagickWand *wand, double *minima, double *maxima)
WandExport ChannelStatistics * MagickGetImageStatistics (MagickWand *wand)
WandExport MagickBooleanType MagickGetImageColormapColor (MagickWand *wand, const size_t index, PixelWand *color)
WandExport size_t MagickGetImageColors (MagickWand *wand)
WandExport ColorspaceType MagickGetImageColorspace (MagickWand *wand)
WandExport CompositeOperator MagickGetImageCompose (MagickWand *wand)
WandExport CompressionType MagickGetImageCompression (MagickWand *wand)
WandExport size_t MagickGetImageCompressionQuality (MagickWand *wand)
WandExport size_t MagickGetImageDelay (MagickWand *wand)
WandExport size_t MagickGetImageDepth (MagickWand *wand)
WandExport DisposeType MagickGetImageDispose (MagickWand *wand)
WandExport MagickBooleanType MagickGetImageDistortion (MagickWand *wand, const MagickWand *reference, const MetricType metric, double *distortion)
WandExport double * MagickGetImageDistortions (MagickWand *wand, const MagickWand *reference, const MetricType metric)
WandExport EndianType MagickGetImageEndian (MagickWand *wand)
WandExport char * MagickGetImageFilename (MagickWand *wand)
WandExport char * MagickGetImageFormat (MagickWand *wand)
WandExport double MagickGetImageFuzz (MagickWand *wand)
WandExport double MagickGetImageGamma (MagickWand *wand)
WandExport GravityType MagickGetImageGravity (MagickWand *wand)
WandExport MagickBooleanType MagickGetImageGreenPrimary (MagickWand *wand, double *x, double *y)
WandExport size_t MagickGetImageHeight (MagickWand *wand)
WandExport PixelWand ** MagickGetImageHistogram (MagickWand *wand, size_t *number_colors)
WandExport InterlaceType MagickGetImageInterlaceScheme (MagickWand *wand)
WandExport PixelInterpolateMethod MagickGetImageInterpolateMethod (MagickWand *wand)
WandExport size_t MagickGetImageIterations (MagickWand *wand)
WandExport MagickBooleanType MagickGetImageLength (MagickWand *wand, MagickSizeType *length)
WandExport MagickBooleanType MagickGetImageMatteColor (MagickWand *wand, PixelWand *matte_color)
WandExport OrientationType MagickGetImageOrientation (MagickWand *wand)
WandExport MagickBooleanType MagickGetImagePage (MagickWand *wand, size_t *width, size_t *height, ssize_t *x, ssize_t *y)
WandExport MagickBooleanType MagickGetImagePixelColor (MagickWand *wand, const ssize_t x, const ssize_t y, PixelWand *color)
WandExport MagickBooleanType MagickGetImageRedPrimary (MagickWand *wand, double *x, double *y)
WandExport MagickWand * MagickGetImageRegion (MagickWand *wand, const size_t width, const size_t height, const ssize_t x, const ssize_t y)
WandExport RenderingIntent MagickGetImageRenderingIntent (MagickWand *wand)
WandExport MagickBooleanType MagickGetImageResolution (MagickWand *wand, double *x, double *y)
WandExport size_t MagickGetImageScene (MagickWand *wand)
WandExport char * MagickGetImageSignature (MagickWand *wand)
WandExport size_t MagickGetImageTicksPerSecond (MagickWand *wand)
WandExport ImageType MagickGetImageType (MagickWand *wand)
WandExport ResolutionType MagickGetImageUnits (MagickWand *wand)
WandExport VirtualPixelMethod MagickGetImageVirtualPixelMethod (MagickWand *wand)
WandExport MagickBooleanType MagickGetImageWhitePoint (MagickWand *wand, double *x, double *y)
WandExport size_t MagickGetImageWidth (MagickWand *wand)
WandExport size_t MagickGetNumberImages (MagickWand *wand)
WandExport double MagickGetImageTotalInkDensity (MagickWand *wand)
WandExport MagickBooleanType MagickHaldClutImage (MagickWand *wand, const MagickWand *hald_wand)
WandExport MagickBooleanType MagickHasNextImage (MagickWand *wand)
WandExport MagickBooleanType MagickHasPreviousImage (MagickWand *wand)
WandExport char * MagickIdentifyImage (MagickWand *wand)
WandExport MagickBooleanType MagickImplodeImage (MagickWand *wand, const double amount, const PixelInterpolateMethod method)
WandExport MagickBooleanType MagickImportImagePixels (MagickWand *wand, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, const char *map, const StorageType storage, const void *pixels)
WandExport MagickBooleanType MagickInterpolativeResizeImage (MagickWand *wand, const size_t columns, const size_t rows, const PixelInterpolateMethod method)
WandExport MagickBooleanType MagickInverseFourierTransformImage (MagickWand *magnitude_wand, MagickWand *phase_wand, const MagickBooleanType magnitude)
WandExport MagickBooleanType MagickLabelImage (MagickWand *wand, const char *label)
WandExport MagickBooleanType MagickLevelImage (MagickWand *wand, const double black_point, const double gamma, const double white_point)
WandExport MagickBooleanType MagickLinearStretchImage (MagickWand *wand, const double black_point, const double white_point)
WandExport MagickBooleanType MagickLiquidRescaleImage (MagickWand *wand, const size_t columns, const size_t rows, const double delta_x, const double rigidity)
WandExport MagickBooleanType MagickMagnifyImage (MagickWand *wand)
WandExport MagickWand * MagickMergeImageLayers (MagickWand *wand, const LayerMethod method)
WandExport MagickBooleanType MagickMinifyImage (MagickWand *wand)
WandExport MagickBooleanType MagickModulateImage (MagickWand *wand, const double brightness, const double saturation, const double hue)
WandExport MagickWand * MagickMontageImage (MagickWand *wand, const DrawingWand *drawing_wand, const char *tile_geometry, const char *thumbnail_geometry, const MontageMode mode, const char *frame)
WandExport MagickWand * MagickMorphImages (MagickWand *wand, const size_t number_frames)
WandExport MagickBooleanType MagickMorphologyImage (MagickWand *wand, MorphologyMethod method, const ssize_t iterations, KernelInfo *kernel)
WandExport MagickBooleanType MagickMotionBlurImage (MagickWand *wand, const double radius, const double sigma, const double angle)
WandExport MagickBooleanType MagickNegateImage (MagickWand *wand, const MagickBooleanType gray)
WandExport MagickBooleanType MagickNewImage (MagickWand *wand, const size_t width, const size_t height, const PixelWand *background)
WandExport MagickBooleanType MagickNextImage (MagickWand *wand)
WandExport MagickBooleanType MagickNormalizeImage (MagickWand *wand)
WandExport MagickBooleanType MagickOilPaintImage (MagickWand *wand, const double radius, const double sigma)
WandExport MagickBooleanType MagickOpaquePaintImage (MagickWand *wand, const PixelWand *target, const PixelWand *fill, const double fuzz, const MagickBooleanType invert)
WandExport MagickWand * MagickOptimizeImageLayers (MagickWand *wand)
WandExport MagickBooleanType MagickOptimizeImageTransparency (MagickWand *wand)
WandExport MagickBooleanType MagickOrderedPosterizeImage (MagickWand *wand, const char *threshold_map)
WandExport MagickBooleanType MagickPingImage (MagickWand *wand, const char *filename)
WandExport MagickBooleanType MagickPingImageBlob (MagickWand *wand, const void *blob, const size_t length)
WandExport MagickBooleanType MagickPingImageFile (MagickWand *wand, FILE *file)
WandExport MagickBooleanType MagickPolaroidImage (MagickWand *wand, const DrawingWand *drawing_wand, const char *caption, const double angle, const PixelInterpolateMethod method)
WandExport MagickBooleanType MagickPosterizeImage (MagickWand *wand, const size_t levels, const DitherMethod dither)
WandExport MagickWand * MagickPreviewImages (MagickWand *wand, const PreviewType preview)
WandExport MagickBooleanType MagickPreviousImage (MagickWand *wand)
WandExport MagickBooleanType MagickQuantizeImage (MagickWand *wand, const size_t number_colors, const ColorspaceType colorspace, const size_t treedepth, const DitherMethod dither_method, const MagickBooleanType measure_error)
WandExport MagickBooleanType MagickQuantizeImages (MagickWand *wand, const size_t number_colors, const ColorspaceType colorspace, const size_t treedepth, const DitherMethod dither_method, const MagickBooleanType measure_error)
WandExport MagickBooleanType MagickRadialBlurImage (MagickWand *wand, const double angle)
WandExport MagickBooleanType MagickRaiseImage (MagickWand *wand, const size_t width, const size_t height, const ssize_t x, const ssize_t y, const MagickBooleanType raise)
WandExport MagickBooleanType MagickRandomThresholdImage (MagickWand *wand, const double low, const double high)
WandExport MagickBooleanType MagickReadImage (MagickWand *wand, const char *filename)
WandExport MagickBooleanType MagickReadImageBlob (MagickWand *wand, const void *blob, const size_t length)
WandExport MagickBooleanType MagickReadImageFile (MagickWand *wand, FILE *file)
WandExport MagickBooleanType MagickRemapImage (MagickWand *wand, const MagickWand *remap_wand, const DitherMethod dither_method)
WandExport MagickBooleanType MagickRemoveImage (MagickWand *wand)
WandExport MagickBooleanType MagickResampleImage (MagickWand *wand, const double x_resolution, const double y_resolution, const FilterTypes filter)
WandExport MagickBooleanType MagickResetImagePage (MagickWand *wand, const char *page)
WandExport MagickBooleanType MagickResizeImage (MagickWand *wand, const size_t columns, const size_t rows, const FilterTypes filter)
WandExport MagickBooleanType MagickRollImage (MagickWand *wand, const ssize_t x, const ssize_t y)
WandExport MagickBooleanType MagickRotateImage (MagickWand *wand, const PixelWand *background, const double degrees)
WandExport MagickBooleanType MagickSampleImage (MagickWand *wand, const size_t columns, const size_t rows)
WandExport MagickBooleanType MagickScaleImage (MagickWand *wand, const size_t columns, const size_t rows)
MagickExport MagickBooleanType MagickSegmentImage (MagickWand *wand, const ColorspaceType colorspace, const MagickBooleanType verbose, const double cluster_threshold, const double smooth_threshold)
WandExport MagickBooleanType MagickSelectiveBlurImage (MagickWand *wand, const double radius, const double sigma, const double threshold)
WandExport MagickBooleanType MagickSeparateImage (MagickWand *wand, const ChannelType channel)
WandExport MagickBooleanType MagickSepiaToneImage (MagickWand *wand, const double threshold)
WandExport MagickBooleanType MagickSetImage (MagickWand *wand, const MagickWand *set_wand)
WandExport MagickBooleanType MagickSetImageAlphaChannel (MagickWand *wand, const AlphaChannelOption alpha_type)
WandExport MagickBooleanType MagickSetImageBackgroundColor (MagickWand *wand, const PixelWand *background)
WandExport MagickBooleanType MagickSetImageBluePrimary (MagickWand *wand, const double x, const double y)
WandExport MagickBooleanType MagickSetImageBorderColor (MagickWand *wand, const PixelWand *border)
WandExport MagickBooleanType MagickSetImageMask (MagickWand *wand, const MagickWand *clip_mask)
WandExport MagickBooleanType MagickSetImageColor (MagickWand *wand, const PixelWand *color)
WandExport MagickBooleanType MagickSetImageColormapColor (MagickWand *wand, const size_t index, const PixelWand *color)
WandExport MagickBooleanType MagickSetImageColorspace (MagickWand *wand, const ColorspaceType colorspace)
WandExport MagickBooleanType MagickSetImageCompose (MagickWand *wand, const CompositeOperator compose)
WandExport MagickBooleanType MagickSetImageCompression (MagickWand *wand, const CompressionType compression)
WandExport MagickBooleanType MagickSetImageCompressionQuality (MagickWand *wand, const size_t quality)
WandExport MagickBooleanType MagickSetImageDelay (MagickWand *wand, const size_t delay)
WandExport MagickBooleanType MagickSetImageDepth (MagickWand *wand, const size_t depth)
WandExport MagickBooleanType MagickSetImageDispose (MagickWand *wand, const DisposeType dispose)
WandExport MagickBooleanType MagickSetImageEndian (MagickWand *wand, const EndianType endian)
WandExport MagickBooleanType MagickSetImageExtent (MagickWand *wand, const size_t columns, const size_t rows)
WandExport MagickBooleanType MagickSetImageFilename (MagickWand *wand, const char *filename)
WandExport MagickBooleanType MagickSetImageFormat (MagickWand *wand, const char *format)
WandExport MagickBooleanType MagickSetImageFuzz (MagickWand *wand, const double fuzz)
WandExport MagickBooleanType MagickSetImageGamma (MagickWand *wand, const double gamma)
WandExport MagickBooleanType MagickSetImageGravity (MagickWand *wand, const GravityType gravity)
WandExport MagickBooleanType MagickSetImageGreenPrimary (MagickWand *wand, const double x, const double y)
WandExport MagickBooleanType MagickSetImageInterlaceScheme (MagickWand *wand, const InterlaceType interlace)
WandExport MagickBooleanType MagickSetImagePixelInterpolateMethod (MagickWand *wand, const PixelInterpolateMethod method)
WandExport MagickBooleanType MagickSetImageIterations (MagickWand *wand, const size_t iterations)
WandExport MagickBooleanType MagickSetImageMatte (MagickWand *wand, const MagickBooleanType matte)
WandExport MagickBooleanType MagickSetImageMatteColor (MagickWand *wand, const PixelWand *matte)
WandExport MagickBooleanType MagickSetImageAlpha (MagickWand *wand, const double alpha)
WandExport MagickBooleanType MagickSetImageOrientation (MagickWand *wand, const OrientationType orientation)
WandExport MagickBooleanType MagickSetImagePage (MagickWand *wand, const size_t width, const size_t height, const ssize_t x, const ssize_t y)
WandExport MagickProgressMonitor MagickSetImageProgressMonitor (MagickWand *wand, const MagickProgressMonitor progress_monitor, void *client_data)
WandExport MagickBooleanType MagickSetImageRedPrimary (MagickWand *wand, const double x, const double y)
WandExport MagickBooleanType MagickSetImageRenderingIntent (MagickWand *wand, const RenderingIntent rendering_intent)
WandExport MagickBooleanType MagickSetImageResolution (MagickWand *wand, const double x_resolution, const double y_resolution)
WandExport MagickBooleanType MagickSetImageScene (MagickWand *wand, const size_t scene)
WandExport MagickBooleanType MagickSetImageTicksPerSecond (MagickWand *wand, const ssize_t ticks_per_second)
WandExport MagickBooleanType MagickSetImageType (MagickWand *wand, const ImageType image_type)
WandExport MagickBooleanType MagickSetImageUnits (MagickWand *wand, const ResolutionType units)
WandExport VirtualPixelMethod MagickSetImageVirtualPixelMethod (MagickWand *wand, const VirtualPixelMethod method)
WandExport MagickBooleanType MagickSetImageWhitePoint (MagickWand *wand, const double x, const double y)
WandExport MagickBooleanType MagickShadeImage (MagickWand *wand, const MagickBooleanType gray, const double asimuth, const double elevation)
WandExport MagickBooleanType MagickShadowImage (MagickWand *wand, const double alpha, const double sigma, const ssize_t x, const ssize_t y)
WandExport MagickBooleanType MagickSharpenImage (MagickWand *wand, const double radius, const double sigma)
WandExport MagickBooleanType MagickShaveImage (MagickWand *wand, const size_t columns, const size_t rows)
WandExport MagickBooleanType MagickShearImage (MagickWand *wand, const PixelWand *background, const double x_shear, const double y_shear)
WandExport MagickBooleanType MagickSigmoidalContrastImage (MagickWand *wand, const MagickBooleanType sharpen, const double alpha, const double beta)
WandExport MagickWand * MagickSimilarityImage (MagickWand *wand, const MagickWand *reference, const MetricType metric, const double similarity_threshold, RectangleInfo *offset, double *similarity)
WandExport MagickBooleanType MagickSketchImage (MagickWand *wand, const double radius, const double sigma, const double angle)
WandExport MagickWand * MagickSmushImages (MagickWand *wand, const MagickBooleanType stack, const ssize_t offset)
WandExport MagickBooleanType MagickSolarizeImage (MagickWand *wand, const double threshold)
WandExport MagickBooleanType MagickSparseColorImage (MagickWand *wand, const SparseColorMethod method, const size_t number_arguments, const double *arguments)
WandExport MagickBooleanType MagickSpliceImage (MagickWand *wand, const size_t width, const size_t height, const ssize_t x, const ssize_t y)
WandExport MagickBooleanType MagickSpreadImage (MagickWand *wand, const double radius, const PixelInterpolateMethod method)
WandExport MagickBooleanType MagickStatisticImage (MagickWand *wand, const StatisticType type, const size_t width, const size_t height)
WandExport MagickWand * MagickSteganoImage (MagickWand *wand, const MagickWand *watermark_wand, const ssize_t offset)
WandExport MagickWand * MagickStereoImage (MagickWand *wand, const MagickWand *offset_wand)
WandExport MagickBooleanType MagickStripImage (MagickWand *wand)
WandExport MagickBooleanType MagickSwirlImage (MagickWand *wand, const double degrees, const PixelInterpolateMethod method)
WandExport MagickWand * MagickTextureImage (MagickWand *wand, const MagickWand *texture_wand)
WandExport MagickBooleanType MagickThresholdImage (MagickWand *wand, const double threshold)
WandExport MagickBooleanType MagickThresholdImageChannel (MagickWand *wand, const ChannelType channel, const double threshold)
WandExport MagickBooleanType MagickThumbnailImage (MagickWand *wand, const size_t columns, const size_t rows)
WandExport MagickBooleanType MagickTintImage (MagickWand *wand, const PixelWand *tint, const PixelWand *blend)
WandExport MagickWand * MagickTransformImage (MagickWand *wand, const char *crop, const char *geometry)
WandExport MagickBooleanType MagickTransformImageColorspace (MagickWand *wand, const ColorspaceType colorspace)
WandExport MagickBooleanType MagickTransparentPaintImage (MagickWand *wand, const PixelWand *target, const double alpha, const double fuzz, const MagickBooleanType invert)
WandExport MagickBooleanType MagickTransposeImage (MagickWand *wand)
WandExport MagickBooleanType MagickTransverseImage (MagickWand *wand)
WandExport MagickBooleanType MagickTrimImage (MagickWand *wand, const double fuzz)
WandExport MagickBooleanType MagickUniqueImageColors (MagickWand *wand)
WandExport MagickBooleanType MagickUnsharpMaskImage (MagickWand *wand, const double radius, const double sigma, const double gain, const double threshold)
WandExport MagickBooleanType MagickVignetteImage (MagickWand *wand, const double radius, const double sigma, const ssize_t x, const ssize_t y)
WandExport MagickBooleanType MagickWaveImage (MagickWand *wand, const double amplitude, const double wave_length, const PixelInterpolateMethod method)
WandExport MagickBooleanType MagickWhiteThresholdImage (MagickWand *wand, const PixelWand *threshold)
WandExport MagickBooleanType MagickWriteImage (MagickWand *wand, const char *filename)
WandExport MagickBooleanType MagickWriteImageFile (MagickWand *wand, FILE *file)
WandExport MagickBooleanType MagickWriteImages (MagickWand *wand, const char *filename, const MagickBooleanType adjoin)
WandExport MagickBooleanType MagickWriteImagesFile (MagickWand *wand, FILE *file)
Macro Definition Documentation
#define MagickWandId "MagickWand"
Definition at line 64 of file magick-image.c.
Referenced by CloneMagickWand(), CloneMagickWandFromImages(), IsMagickWand(), and NewMagickWand().
#define ThrowWandException (severity, tag, context)
Value:
{ \
  (void) ThrowMagickException(wand->exception,GetMagickModule(),severity, \
    tag,"`%s'",context); \
  return(MagickFalse); \
}
Definition at line 58 of file magick-image.c.
Referenced by MagickAdaptiveBlurImage(), MagickAdaptiveResizeImage(), MagickAdaptiveSharpenImage(), MagickAdaptiveThresholdImage(), MagickAddImage(), MagickAddNoiseImage(), MagickAffineTransformImage(), MagickAnnotateImage(), MagickAutoGammaImage(), MagickAutoLevelImage(), MagickBlackThresholdImage(), MagickBlueShiftImage(), MagickBlurImage(), MagickBorderImage(), MagickBrightnessContrastImage(), MagickCharcoalImage(), MagickChopImage(), MagickClampImage(), MagickClipImage(), MagickClipImagePath(), MagickClutImage(), MagickColorDecisionListImage(), MagickColorizeImage(), MagickColorMatrixImage(), MagickCommentImage(), MagickCompositeImage(), MagickCompositeLayers(), MagickContrastImage(), MagickContrastStretchImage(), MagickConvolveImage(), MagickCropImage(), MagickCycleColormapImage(), MagickDecipherImage(), MagickDeskewImage(), MagickDespeckleImage(), MagickDisplayImage(), MagickDistortImage(), MagickDrawImage(), MagickEdgeImage(), MagickEmbossImage(), MagickEncipherImage(), MagickEnhanceImage(), MagickEqualizeImage(), MagickEvaluateImage(), MagickExportImagePixels(), MagickExtentImage(), MagickFlipImage(), MagickFloodfillPaintImage(), MagickFlopImage(), MagickForwardFourierTransformImage(), MagickFrameImage(), MagickFunctionImage(), MagickGammaImage(), MagickGaussianBlurImage(), MagickGetImageAlphaChannel(), MagickGetImageBackgroundColor(), MagickGetImageBluePrimary(), MagickGetImageBorderColor(), MagickGetImageColormapColor(), MagickGetImageDelay(), MagickGetImageDepth(), MagickGetImageDistortion(), MagickGetImageGreenPrimary(), MagickGetImageHeight(), MagickGetImageIterations(), MagickGetImageKurtosis(), MagickGetImageLength(), MagickGetImageMatteColor(), MagickGetImageMean(), MagickGetImagePage(), MagickGetImagePixelColor(), MagickGetImageRange(), MagickGetImageRedPrimary(), MagickGetImageResolution(), MagickGetImageScene(), MagickGetImageTicksPerSecond(), MagickGetImageWhitePoint(), MagickGetImageWidth(), MagickHaldClutImage(), MagickHasNextImage(), MagickHasPreviousImage(), MagickImplodeImage(), MagickImportImagePixels(), MagickInterpolativeResizeImage(), MagickInverseFourierTransformImage(), MagickLabelImage(), MagickLevelImage(), MagickLinearStretchImage(), MagickLiquidRescaleImage(), MagickMagnifyImage(), MagickMinifyImage(), MagickModulateImage(), MagickMorphologyImage(), MagickMotionBlurImage(), MagickNegateImage(), MagickNextImage(), MagickNormalizeImage(), MagickOilPaintImage(), MagickOpaquePaintImage(), MagickOrderedPosterizeImage(), MagickPolaroidImage(), MagickPosterizeImage(), MagickPreviousImage(), MagickQuantizeImage(), MagickQuantizeImages(), MagickRadialBlurImage(), MagickRaiseImage(), MagickRandomThresholdImage(), MagickRemapImage(), MagickRemoveImage(), MagickResampleImage(), MagickResetImagePage(), MagickResizeImage(), MagickRollImage(), MagickRotateImage(), MagickSampleImage(), MagickScaleImage(), MagickSegmentImage(), MagickSelectiveBlurImage(), MagickSeparateImage(), MagickSepiaToneImage(), MagickSetImage(), MagickSetImageAlpha(), MagickSetImageAlphaChannel(), MagickSetImageBackgroundColor(), MagickSetImageBluePrimary(), MagickSetImageBorderColor(), MagickSetImageColormapColor(), MagickSetImageColorspace(), MagickSetImageCompose(), MagickSetImageCompression(), MagickSetImageCompressionQuality(), MagickSetImageDelay(), MagickSetImageDepth(), MagickSetImageDispose(), MagickSetImageEndian(), MagickSetImageExtent(), MagickSetImageFilename(), MagickSetImageFormat(), MagickSetImageFuzz(), MagickSetImageGamma(), MagickSetImageGravity(), MagickSetImageGreenPrimary(), MagickSetImageInterlaceScheme(), MagickSetImageIterations(), MagickSetImageMask(), MagickSetImageMatte(), MagickSetImageMatteColor(), MagickSetImageOrientation(), MagickSetImagePage(), MagickSetImagePixelInterpolateMethod(), MagickSetImageRedPrimary(), MagickSetImageRenderingIntent(), MagickSetImageResolution(), MagickSetImageScene(), MagickSetImageTicksPerSecond(), MagickSetImageType(), MagickSetImageUnits(), MagickSetImageWhitePoint(), MagickShadeImage(), MagickShadowImage(), MagickSharpenImage(), MagickShaveImage(), MagickShearImage(), MagickSigmoidalContrastImage(), MagickSketchImage(), MagickSolarizeImage(), MagickSparseColorImage(), MagickSpliceImage(), MagickSpreadImage(), MagickStatisticImage(), MagickStripImage(), MagickSwirlImage(), MagickThresholdImageChannel(), MagickThumbnailImage(), MagickTintImage(), MagickTransformImageColorspace(), MagickTransparentPaintImage(), MagickTransposeImage(), MagickTransverseImage(), MagickTrimImage(), MagickUniqueImageColors(), MagickUnsharpMaskImage(), MagickVignetteImage(), MagickWaveImage(), MagickWhiteThresholdImage(), MagickWriteImage(), MagickWriteImageFile(), MagickWriteImages(), and MagickWriteImagesFile().
Function Documentation
static MagickWand* CloneMagickWandFromImages (const MagickWand * wand, Image * images) static
Definition at line 92 of file magick-image.c.
References AcquireWandId(), _MagickWand::debug, _MagickWand::exception, _MagickWand::id, _MagickWand::image_info, _MagickWand::images, MagickWandId, MaxTextExtent, _MagickWand::name, _MagickWand::signature, ThrowWandFatalException, and WandSignature.
Referenced by MagickAppendImages(), MagickChannelFxImage(), MagickCoalesceImages(), MagickCombineImages(), MagickCompareImages(), MagickCompareImagesLayers(), MagickDeconstructImages(), MagickEvaluateImages(), MagickFxImage(), MagickGetImage(), MagickGetImageMask(), MagickGetImageRegion(), MagickMergeImageLayers(), MagickMontageImage(), MagickMorphImages(), MagickOptimizeImageLayers(), MagickPreviewImages(), MagickSimilarityImage(), MagickSmushImages(), MagickSteganoImage(), MagickStereoImage(), MagickTextureImage(), and MagickTransformImage().
WandExport Image* GetImageFromMagickWand (const MagickWand * wand)
Definition at line 143 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
Referenced by DrawComposite(), NewPixelIterator(), and NewPixelRegionIterator().
static MagickBooleanType InsertImageInWand (MagickWand * wand, Image * images) inline static
Definition at line 398 of file magick-image.c.
References _MagickWand::images, and _MagickWand::insert_before.
Referenced by MagickAddImage(), MagickConstituteImage(), MagickNewImage(), MagickPingImage(), MagickPingImageBlob(), MagickPingImageFile(), MagickReadImage(), MagickReadImageBlob(), and MagickReadImageFile().
WandExport MagickBooleanType MagickAdaptiveBlurImage (MagickWand * wand, const double radius, const double sigma)
Definition at line 191 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickAdaptiveResizeImage (MagickWand * wand, const size_t columns, const size_t rows)
Definition at line 236 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickAdaptiveSharpenImage (MagickWand * wand, const double radius, const double sigma)
Definition at line 288 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickAdaptiveThresholdImage (MagickWand * wand, const size_t width, const size_t height, const double bias)
Definition at line 339 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickAddImage (MagickWand * wand, const MagickWand * add_wand)
Definition at line 441 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, InsertImageInWand(), _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickAddNoiseImage (MagickWand * wand, const NoiseType noise_type, const double attenuate)
Definition at line 492 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickAffineTransformImage (MagickWand * wand, const DrawingWand * drawing_wand)
Definition at line 537 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, PeekDrawingWand(), _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickAnimateImages (MagickWand * wand, const char * server_name)
Definition at line 657 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::image_info, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickAnnotateImage (MagickWand * wand, const DrawingWand * drawing_wand, const double x, const double y, const double angle, const char * text)
Definition at line 598 of file magick-image.c.
References _MagickWand::debug, DegreesToRadians, _MagickWand::exception, _MagickWand::images, MaxTextExtent, _MagickWand::name, PeekDrawingWand(), _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickWand* MagickAppendImages (MagickWand * wand, const MagickBooleanType stack)
Definition at line 704 of file magick-image.c.
References CloneMagickWandFromImages(), _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickAutoGammaImage (MagickWand * wand)
Definition at line 745 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickAutoLevelImage (MagickWand * wand)
Definition at line 783 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickBlackThresholdImage (MagickWand * wand, const PixelWand * threshold)
Definition at line 825 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, MaxTextExtent, _MagickWand::name, PixelGetAlphaQuantum(), PixelGetBlueQuantum(), PixelGetGreenQuantum(), PixelGetRedQuantum(), _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickBlueShiftImage (MagickWand * wand, const double factor)
Definition at line 874 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickBlurImage (MagickWand * wand, const double radius, const double sigma)
Definition at line 924 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickBorderImage (MagickWand * wand, const PixelWand * bordercolor, const size_t width, const size_t height, const CompositeOperator compose)
Definition at line 976 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, PixelGetQuantumPacket(), _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickBrightnessContrastImage (MagickWand * wand, const double brightness, const double contrast)
Definition at line 1034 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickWand* MagickChannelFxImage (MagickWand * wand, const char * expression)
Definition at line 1088 of file magick-image.c.
References CloneMagickWandFromImages(), _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickCharcoalImage (MagickWand * wand, const double radius, const double sigma)
Definition at line 1134 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickChopImage (MagickWand * wand, const size_t width, const size_t height, const ssize_t x, const ssize_t y)
Definition at line 1187 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickClampImage (MagickWand * wand)
Definition at line 1238 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickClipImage (MagickWand * wand)
Definition at line 1272 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickClipImagePath (MagickWand * wand, const char * pathname, const MagickBooleanType inside)
Definition at line 1319 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickClutImage (MagickWand * wand, const MagickWand * clut_wand, const PixelInterpolateMethod method)
Definition at line 1362 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickWand* MagickCoalesceImages (MagickWand * wand)
Definition at line 1405 of file magick-image.c.
References CloneMagickWandFromImages(), _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickColorDecisionListImage (MagickWand * wand, const char * color_correction_collection)
Definition at line 1465 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickColorizeImage (MagickWand * wand, const PixelWand * colorize, const PixelWand * blend)
Definition at line 1509 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, MaxTextExtent, _MagickWand::name, PixelGetAlphaQuantum(), PixelGetBlackQuantum(), PixelGetBlueQuantum(), PixelGetGreenQuantum(), PixelGetPixel(), PixelGetRedQuantum(), _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickColorMatrixImage (MagickWand * wand, const KernelInfo * color_matrix)
Definition at line 1583 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickWand* MagickCombineImages (MagickWand * wand, const ColorspaceType colorspace)
Definition at line 1632 of file magick-image.c.
References CloneMagickWandFromImages(), _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickCommentImage (MagickWand * wand, const char * comment)
Definition at line 1675 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickWand* MagickCompareImages (MagickWand * wand, const MagickWand * reference, const MetricType metric, double * distortion)
Definition at line 1767 of file magick-image.c.
References CloneMagickWandFromImages(), _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickWand* MagickCompareImagesLayers (MagickWand * wand, const LayerMethod method)
Definition at line 1718 of file magick-image.c.
References CloneMagickWandFromImages(), _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickCompositeImage (MagickWand * wand, const MagickWand * source_wand, const CompositeOperator compose, const MagickBooleanType clip_to_self, const ssize_t x, const ssize_t y)
Definition at line 1834 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickCompositeLayers (MagickWand * wand, const MagickWand * source_wand, const CompositeOperator compose, const ssize_t x, const ssize_t y)
Definition at line 1906 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickConstituteImage (MagickWand * wand, const size_t columns, const size_t rows, const char * map, const StorageType storage, const void * pixels)
Definition at line 2214 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, InsertImageInWand(), _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickContrastImage (MagickWand * wand, const MagickBooleanType sharpen)
Definition at line 1953 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickContrastStretchImage (MagickWand * wand, const double black_point, const double white_point)
Definition at line 1999 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickConvolveImage (MagickWand * wand, const KernelInfo * kernel)
Definition at line 2041 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickCropImage (MagickWand * wand, const size_t width, const size_t height, const ssize_t x, const ssize_t y)
Definition at line 2093 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickCycleColormapImage (MagickWand * wand, const ssize_t displace)
Definition at line 2146 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickDecipherImage (MagickWand * wand, const char * passphrase)
Definition at line 2256 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickWand* MagickDeconstructImages (MagickWand * wand)
Definition at line 2292 of file magick-image.c.
References CloneMagickWandFromImages(), _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickDeskewImage (MagickWand * wand, const double threshold)
Definition at line 2338 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickDespeckleImage (MagickWand * wand)
Definition at line 2380 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport Image* MagickDestroyImage (Image * image)
Definition at line 2421 of file magick-image.c.
WandExport MagickBooleanType MagickDisplayImage (MagickWand * wand, const char * server_name)
Definition at line 2451 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _DrawingWand::image, _MagickWand::image_info, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickDisplayImages (MagickWand * wand, const char * server_name)
Definition at line 2500 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::image_info, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickDistortImage (MagickWand * wand, const DistortImageMethod method, const size_t number_arguments, const double * arguments, const MagickBooleanType bestfit)
Definition at line 2575 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickDrawImage (MagickWand * wand, const DrawingWand * drawing_wand)
Definition at line 2621 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::image_info, _MagickWand::images, _MagickWand::name, PeekDrawingWand(), _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickEdgeImage (MagickWand * wand, const double radius)
Definition at line 2678 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickEmbossImage (MagickWand * wand, const double radius, const double sigma)
Definition at line 2729 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickEncipherImage (MagickWand * wand, const char * passphrase)
Definition at line 2773 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickEnhanceImage (MagickWand * wand)
Definition at line 2808 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickEqualizeImage (MagickWand * wand)
Definition at line 2850 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickEvaluateImage (MagickWand * wand, const MagickEvaluateOperator op, const double value)
Definition at line 2916 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickWand* MagickEvaluateImages (MagickWand * wand, const MagickEvaluateOperator op)
Definition at line 2898 of file magick-image.c.
References CloneMagickWandFromImages(), _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickExportImagePixels (MagickWand * wand, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, const char * map, const StorageType storage, void * pixels)
Definition at line 2983 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickExtentImage (MagickWand * wand, const size_t width, const size_t height, const ssize_t x, const ssize_t y)
Definition at line 3035 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickFlipImage (MagickWand * wand)
Definition at line 3084 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickFloodfillPaintImage (MagickWand * wand, const PixelWand * fill, const double fuzz, const PixelWand * bordercolor, const ssize_t x, const ssize_t y, const MagickBooleanType invert)
Definition at line 3144 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::image_info, _MagickWand::images, _MagickWand::name, PixelGetMagickColor(), PixelGetQuantumPacket(), _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickFlopImage (MagickWand * wand)
Definition at line 3199 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickForwardFourierTransformImage (MagickWand * wand, const MagickBooleanType magnitude)
Definition at line 3245 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickFrameImage (MagickWand * wand, const PixelWand * matte_color, const size_t width, const size_t height, const ssize_t inner_bevel, const ssize_t outer_bevel, const CompositeOperator compose)
Definition at line 3305 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, PixelGetQuantumPacket(), _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickFunctionImage (MagickWand * wand, const MagickFunction function, const size_t number_arguments, const double * arguments)
Definition at line 3370 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickWand* MagickFxImage (MagickWand * wand, const char * expression)
Definition at line 3412 of file magick-image.c.
References CloneMagickWandFromImages(), _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickGammaImage (MagickWand * wand, const double gamma)
Definition at line 3460 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickGaussianBlurImage (MagickWand * wand, const double radius, const double sigma)
Definition at line 3507 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickWand* MagickGetImage (MagickWand * wand)
Definition at line 3548 of file magick-image.c.
References CloneMagickWandFromImages(), _MagickWand::debug, _MagickWand::exception, _DrawingWand::image, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickGetImageAlphaChannel (MagickWand * wand)
Definition at line 3593 of file magick-image.c.
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickGetImageBackgroundColor (MagickWand * wand, PixelWand * background_color)
Definition at line 3672 of file magick-image.c.
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, PixelSetPixelColor(), _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport unsigned char* MagickGetImageBlob (MagickWand * wand, size_t * length)
Definition at line 3717 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::image_info, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickGetImageBluePrimary (MagickWand * wand, double * x, double * y)
Definition at line 3811 of file magick-image.c.
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickGetImageBorderColor (MagickWand * wand, PixelWand * border_color)
Definition at line 3850 of file magick-image.c.
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, PixelSetPixelColor(), _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickGetImageColormapColor (MagickWand * wand, const size_t index, PixelWand * color)
Definition at line 4123 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, PixelSetPixelColor(), _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport size_t MagickGetImageColors (MagickWand * wand)
Definition at line 4165 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport ColorspaceType MagickGetImageColorspace (MagickWand * wand)
Definition at line 4202 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport CompositeOperator MagickGetImageCompose (MagickWand * wand)
Definition at line 4240 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport CompressionType MagickGetImageCompression (MagickWand * wand)
Definition at line 4277 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport size_t MagickGetImageCompressionQuality (MagickWand * wand)
Definition at line 4314 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport size_t MagickGetImageDelay (MagickWand * wand)
Definition at line 4351 of file magick-image.c.
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport size_t MagickGetImageDepth (MagickWand * wand)
Definition at line 4384 of file magick-image.c.
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport DisposeType MagickGetImageDispose (MagickWand * wand)
Definition at line 4417 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickGetImageDistortion (MagickWand * wand, const MagickWand * reference, const MetricType metric, double * distortion)
Definition at line 4463 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport double* MagickGetImageDistortions (MagickWand * wand, const MagickWand * reference, const MetricType metric)
Definition at line 4510 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport EndianType MagickGetImageEndian (MagickWand * wand)
Definition at line 4555 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport ChannelFeatures* MagickGetImageFeatures (MagickWand * wand, const size_t distance)
Definition at line 3901 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport char* MagickGetImageFilename (MagickWand * wand)
Definition at line 4593 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport char* MagickGetImageFormat (MagickWand * wand)
Definition at line 4631 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport double MagickGetImageFuzz (MagickWand * wand)
Definition at line 4668 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport double MagickGetImageGamma (MagickWand * wand)
Definition at line 4705 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport GravityType MagickGetImageGravity (MagickWand * wand)
Definition at line 4742 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickGetImageGreenPrimary (MagickWand * wand, double * x, double * y)
Definition at line 4784 of file magick-image.c.
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport size_t MagickGetImageHeight (MagickWand * wand)
Definition at line 4820 of file magick-image.c.
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport PixelWand** MagickGetImageHistogram (MagickWand * wand, size_t * number_colors)
Definition at line 4858 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, NewPixelWands(), PixelSetColorCount(), PixelSetPixelColor(), _MagickWand::signature, and WandSignature.
WandExport InterlaceType MagickGetImageInterlaceScheme (MagickWand * wand)
Definition at line 4915 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport PixelInterpolateMethod MagickGetImageInterpolateMethod (MagickWand * wand)
Definition at line 4954 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport size_t MagickGetImageIterations (MagickWand * wand)
Definition at line 4992 of file magick-image.c.
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickGetImageKurtosis (MagickWand * wand, double * kurtosis, double * skewness)
Definition at line 3945 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickGetImageLength (MagickWand * wand, MagickSizeType * length)
Definition at line 5028 of file magick-image.c.
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickWand* MagickGetImageMask (MagickWand * wand)
Definition at line 3626 of file magick-image.c.
References CloneMagickWandFromImages(), _MagickWand::debug, _MagickWand::exception, _DrawingWand::image, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickGetImageMatteColor (MagickWand * wand, PixelWand * matte_color)
Definition at line 5066 of file magick-image.c.
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, PixelSetPixelColor(), _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickGetImageMean (MagickWand * wand, double * mean, double * standard_deviation)
Definition at line 3991 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport OrientationType MagickGetImageOrientation (MagickWand * wand)
Definition at line 5101 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickGetImagePage (MagickWand * wand, size_t * width, size_t * height, ssize_t * x, ssize_t * y)
Definition at line 5147 of file magick-image.c.
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickGetImagePixelColor (MagickWand * wand, const ssize_t x, const ssize_t y, PixelWand * color)
Definition at line 5190 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, PixelSetQuantumPixel(), _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickGetImageRange (MagickWand * wand, double * minima, double * maxima)
Definition at line 4034 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickGetImageRedPrimary (MagickWand * wand, double * x, double * y)
Definition at line 5244 of file magick-image.c.
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickWand* MagickGetImageRegion (MagickWand * wand, const size_t width, const size_t height, const ssize_t x, const ssize_t y)
Definition at line 5291 of file magick-image.c.
References CloneMagickWandFromImages(), _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport RenderingIntent MagickGetImageRenderingIntent (MagickWand * wand)
Definition at line 5339 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickGetImageResolution (MagickWand * wand, double * x, double * y)
Definition at line 5381 of file magick-image.c.
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport unsigned char* MagickGetImagesBlob (MagickWand * wand, size_t * length)
Definition at line 3763 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::image_info, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport size_t MagickGetImageScene (MagickWand * wand)
Definition at line 5417 of file magick-image.c.
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport char* MagickGetImageSignature (MagickWand * wand)
Definition at line 5451 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport ChannelStatistics* MagickGetImageStatistics (MagickWand * wand)
Definition at line 4080 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport size_t MagickGetImageTicksPerSecond (MagickWand * wand)
Definition at line 5500 of file magick-image.c.
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport double MagickGetImageTotalInkDensity (MagickWand * wand)
Definition at line 5759 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport ImageType MagickGetImageType (MagickWand * wand)
Definition at line 5541 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport ResolutionType MagickGetImageUnits (MagickWand * wand)
Definition at line 5578 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport VirtualPixelMethod MagickGetImageVirtualPixelMethod (MagickWand * wand)
Definition at line 5616 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickGetImageWhitePoint (MagickWand * wand, double * x, double * y)
Definition at line 5658 of file magick-image.c.
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport size_t MagickGetImageWidth (MagickWand * wand)
Definition at line 5694 of file magick-image.c.
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport size_t MagickGetNumberImages (MagickWand * wand)
Definition at line 5728 of file magick-image.c.
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickHaldClutImage (MagickWand * wand, const MagickWand * hald_wand)
Definition at line 5803 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickHasNextImage (MagickWand * wand)
Definition at line 5842 of file magick-image.c.
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickHasPreviousImage (MagickWand * wand)
Definition at line 5878 of file magick-image.c.
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport char* MagickIdentifyImage (MagickWand * wand)
Definition at line 5914 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, MaxTextExtent, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickImplodeImage (MagickWand * wand, const double amount, const PixelInterpolateMethod method)
Definition at line 5984 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickImportImagePixels (MagickWand * wand, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, const char * map, const StorageType storage, const void * pixels)
Definition at line 6054 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickInterpolativeResizeImage (MagickWand * wand, const size_t columns, const size_t rows, const PixelInterpolateMethod method)
Definition at line 6101 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickInverseFourierTransformImage (MagickWand * magnitude_wand, MagickWand * phase_wand, const MagickBooleanType magnitude)
Definition at line 6152 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickLabelImage (MagickWand * wand, const char * label)
Definition at line 6205 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickLevelImage (MagickWand * wand, const double black_point, const double gamma, const double white_point)
Definition at line 6263 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickLinearStretchImage (MagickWand * wand, const double black_point, const double white_point)
Definition at line 6310 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickLiquidRescaleImage (MagickWand * wand, const size_t columns, const size_t rows, const double delta_x, const double rigidity)
Definition at line 6357 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickMagnifyImage (MagickWand * wand)
Definition at line 6401 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickWand* MagickMergeImageLayers (MagickWand * wand, const LayerMethod method)
Definition at line 6462 of file magick-image.c.
References CloneMagickWandFromImages(), _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickMinifyImage (MagickWand * wand)
Definition at line 6503 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickModulateImage (MagickWand * wand, const double brightness, const double saturation, const double hue)
Definition at line 6557 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, MaxTextExtent, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickWand* MagickMontageImage (MagickWand * wand, const DrawingWand * drawing_wand, const char * tile_geometry, const char * thumbnail_geometry, const MontageMode mode, const char * frame)
Definition at line 6618 of file magick-image.c.
References CloneMagickWandFromImages(), _MagickWand::debug, DestroyPixelWand(), DrawGetFillColor(), DrawGetFont(), DrawGetFontSize(), DrawGetStrokeColor(), _MagickWand::exception, _MagickWand::image_info, _MagickWand::images, _MagickWand::name, NewPixelWand(), PixelGetQuantumPacket(), _MagickWand::signature, and WandSignature.
WandExport MagickWand* MagickMorphImages (MagickWand * wand, const size_t number_frames)
Definition at line 6718 of file magick-image.c.
References CloneMagickWandFromImages(), _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickMorphologyImage (MagickWand * wand, MorphologyMethod method, const ssize_t iterations, KernelInfo * kernel)
Definition at line 6768 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickMotionBlurImage (MagickWand * wand, const double radius, const double sigma, const double angle)
Definition at line 6824 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickNegateImage (MagickWand * wand, const MagickBooleanType gray)
Definition at line 6873 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickNewImage (MagickWand * wand, const size_t width, const size_t height, const PixelWand * background)
Definition at line 6920 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::image_info, InsertImageInWand(), _MagickWand::name, PixelGetMagickColor(), _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickNextImage (MagickWand * wand)
Definition at line 6975 of file magick-image.c.
References _MagickWand::debug, _MagickWand::image_pending, _MagickWand::images, _MagickWand::insert_before, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
Referenced by CLINoImageOperator(), and CLISimpleOperatorImages().
WandExport MagickBooleanType MagickNormalizeImage (MagickWand * wand)
Definition at line 7024 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickOilPaintImage (MagickWand * wand, const double radius, const double sigma)
Definition at line 7068 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickOpaquePaintImage (MagickWand * wand, const PixelWand * target, const PixelWand * fill, const double fuzz, const MagickBooleanType invert)
Definition at line 7125 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, PixelGetMagickColor(), _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickWand* MagickOptimizeImageLayers (MagickWand * wand)
Definition at line 7175 of file magick-image.c.
References CloneMagickWandFromImages(), _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickOptimizeImageTransparency (MagickWand * wand)
Definition at line 7220 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickOrderedPosterizeImage (MagickWand * wand, const char * threshold_map)
Definition at line 7277 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickPingImage (MagickWand * wand, const char * filename)
Definition at line 7320 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::image_info, InsertImageInWand(), MaxTextExtent, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickPingImageBlob (MagickWand * wand, const void * blob, const size_t length)
Definition at line 7370 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::image_info, InsertImageInWand(), _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickPingImageFile (MagickWand * wand, FILE * file)
Definition at line 7417 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::image_info, InsertImageInWand(), _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickPolaroidImage (MagickWand * wand, const DrawingWand * drawing_wand, const char * caption, const double angle, const PixelInterpolateMethod method)
Definition at line 7471 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, PeekDrawingWand(), _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickPosterizeImage (MagickWand * wand, const size_t levels, const DitherMethod dither)
Definition at line 7527 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickWand* MagickPreviewImages (MagickWand * wand, const PreviewType preview)
Definition at line 7571 of file magick-image.c.
References CloneMagickWandFromImages(), _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickPreviousImage (MagickWand * wand)
Definition at line 7625 of file magick-image.c.
References _MagickWand::debug, _MagickWand::image_pending, _MagickWand::images, _MagickWand::insert_before, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickQuantizeImage (MagickWand * wand, const size_t number_colors, const ColorspaceType colorspace, const size_t treedepth, const DitherMethod dither_method, const MagickBooleanType measure_error)
Definition at line 7698 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickQuantizeImages (MagickWand * wand, const size_t number_colors, const ColorspaceType colorspace, const size_t treedepth, const DitherMethod dither_method, const MagickBooleanType measure_error)
Definition at line 7776 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickRadialBlurImage (MagickWand * wand, const double angle)
Definition at line 7829 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickRaiseImage (MagickWand * wand, const size_t width, const size_t height, const ssize_t x, const ssize_t y, const MagickBooleanType raise)
Definition at line 7880 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickRandomThresholdImage (MagickWand * wand, const double low, const double high)
Definition at line 7932 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, MaxTextExtent, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickReadImage (MagickWand * wand, const char * filename)
Definition at line 7977 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::image_info, InsertImageInWand(), MaxTextExtent, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickReadImageBlob (MagickWand * wand, const void * blob, const size_t length)
Definition at line 8028 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::image_info, InsertImageInWand(), _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickReadImageFile (MagickWand * wand, FILE * file)
Definition at line 8069 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::image_info, InsertImageInWand(), _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickRemapImage (MagickWand * wand, const MagickWand * remap_wand, const DitherMethod dither_method)
Definition at line 8120 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::image_info, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickRemoveImage (MagickWand * wand)
Definition at line 8168 of file magick-image.c.
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickResampleImage (MagickWand * wand, const double x_resolution, const double y_resolution, const FilterTypes filter)
Definition at line 8220 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickResetImagePage (MagickWand * wand, const char * page)
Definition at line 8265 of file magick-image.c.
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickResizeImage (MagickWand * wand, const size_t columns, const size_t rows, const FilterTypes filter)
Definition at line 8322 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickRollImage (MagickWand * wand, const ssize_t x, const ssize_t y)
Definition at line 8369 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickRotateImage (MagickWand * wand, const PixelWand * background, const double degrees)
Definition at line 8418 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, PixelGetQuantumPacket(), _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickSampleImage (MagickWand * wand, const size_t columns, const size_t rows)
Definition at line 8468 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickScaleImage (MagickWand * wand, const size_t columns, const size_t rows)
Definition at line 8515 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickExport MagickBooleanType MagickSegmentImage (MagickWand * wand, const ColorspaceType colorspace, const MagickBooleanType verbose, const double cluster_threshold, const double smooth_threshold)
Definition at line 8573 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickSelectiveBlurImage (MagickWand * wand, const double radius, const double sigma, const double threshold)
Definition at line 8624 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickSeparateImage (MagickWand * wand, const ChannelType channel)
Definition at line 8671 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickSepiaToneImage (MagickWand * wand, const double threshold)
Definition at line 8718 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickSetImage (MagickWand * wand, const MagickWand * set_wand)
Definition at line 8764 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickSetImageAlpha (MagickWand * wand, const double alpha)
Definition at line 9887 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickSetImageAlphaChannel (MagickWand * wand, const AlphaChannelOption alpha_type)
Definition at line 8814 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickSetImageBackgroundColor (MagickWand * wand, const PixelWand * background)
Definition at line 8851 of file magick-image.c.
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, PixelGetQuantumPacket(), _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickSetImageBluePrimary (MagickWand * wand, const double x, const double y)
Definition at line 8891 of file magick-image.c.
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickSetImageBorderColor (MagickWand * wand, const PixelWand * border)
Definition at line 8930 of file magick-image.c.
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, PixelGetQuantumPacket(), _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickSetImageColor (MagickWand * wand, const PixelWand * color)
Definition at line 9009 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, PixelGetMagickColor(), _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickSetImageColormapColor (MagickWand * wand, const size_t index, const PixelWand * color)
Definition at line 9051 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, PixelGetQuantumPacket(), _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickSetImageColorspace (MagickWand * wand, const ColorspaceType colorspace)
Definition at line 9097 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickSetImageCompose (MagickWand * wand, const CompositeOperator compose)
Definition at line 9136 of file magick-image.c.
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickSetImageCompression (MagickWand * wand, const CompressionType compression)
Definition at line 9174 of file magick-image.c.
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickSetImageCompressionQuality (MagickWand * wand, const size_t quality)
Definition at line 9212 of file magick-image.c.
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickSetImageDelay (MagickWand * wand, const size_t delay)
Definition at line 9250 of file magick-image.c.
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickSetImageDepth (MagickWand * wand, const size_t depth)
Definition at line 9288 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickSetImageDispose (MagickWand * wand, const DisposeType dispose)
Definition at line 9325 of file magick-image.c.
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickSetImageEndian (MagickWand * wand, const EndianType endian)
Definition at line 9363 of file magick-image.c.
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickSetImageExtent (MagickWand * wand, const size_t columns, const size_t rows)
Definition at line 9403 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickSetImageFilename (MagickWand * wand, const char * filename)
Definition at line 9441 of file magick-image.c.
References _MagickWand::debug, _MagickWand::images, MaxTextExtent, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickSetImageFormat (MagickWand * wand, const char * format)
Definition at line 9481 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, MaxTextExtent, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickSetImageFuzz (MagickWand * wand, const double fuzz)
Definition at line 9531 of file magick-image.c.
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickSetImageGamma (MagickWand * wand, const double gamma)
Definition at line 9569 of file magick-image.c.
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickSetImageGravity (MagickWand * wand, const GravityType gravity)
Definition at line 9608 of file magick-image.c.
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickSetImageGreenPrimary (MagickWand * wand, const double x, const double y)
Definition at line 9650 of file magick-image.c.
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickSetImageInterlaceScheme (MagickWand * wand, const InterlaceType interlace)
Definition at line 9690 of file magick-image.c.
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickSetImageIterations (MagickWand * wand, const size_t iterations)
Definition at line 9768 of file magick-image.c.
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickSetImageMask (MagickWand * wand, const MagickWand * clip_mask)
Definition at line 8968 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickSetImageMatte (MagickWand * wand, const MagickBooleanType matte)
Definition at line 9807 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickSetImageMatteColor (MagickWand * wand, const PixelWand * matte)
Definition at line 9848 of file magick-image.c.
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, PixelGetQuantumPacket(), _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickSetImageOrientation (MagickWand * wand, const OrientationType orientation)
Definition at line 9929 of file magick-image.c.
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickSetImagePage (MagickWand * wand, const size_t width, const size_t height, const ssize_t x, const ssize_t y)
Definition at line 9972 of file magick-image.c.
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickSetImagePixelInterpolateMethod (MagickWand * wand, const PixelInterpolateMethod method)
Definition at line 9730 of file magick-image.c.
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickProgressMonitor MagickSetImageProgressMonitor (MagickWand * wand, const MagickProgressMonitor progress_monitor, void * client_data)
Definition at line 10026 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickSetImageRedPrimary (MagickWand * wand, const double x, const double y)
Definition at line 10074 of file magick-image.c.
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickSetImageRenderingIntent (MagickWand * wand, const RenderingIntent rendering_intent)
Definition at line 10114 of file magick-image.c.
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickSetImageResolution (MagickWand * wand, const double x_resolution, const double y_resolution)
Definition at line 10154 of file magick-image.c.
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickSetImageScene (MagickWand * wand, const size_t scene)
Definition at line 10193 of file magick-image.c.
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickSetImageTicksPerSecond (MagickWand * wand, const ssize_t ticks_per_second)
Definition at line 10231 of file magick-image.c.
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickSetImageType (MagickWand * wand, const ImageType image_type)
Definition at line 10272 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickSetImageUnits (MagickWand * wand, const ResolutionType units)
Definition at line 10310 of file magick-image.c.
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport VirtualPixelMethod MagickSetImageVirtualPixelMethod (MagickWand * wand, const VirtualPixelMethod method)
Definition at line 10350 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickSetImageWhitePoint (MagickWand * wand, const double x, const double y)
Definition at line 10389 of file magick-image.c.
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickShadeImage (MagickWand * wand, const MagickBooleanType gray, const double asimuth, const double elevation)
Definition at line 10434 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickShadowImage (MagickWand * wand, const double alpha, const double sigma, const ssize_t x, const ssize_t y)
Definition at line 10484 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickSharpenImage (MagickWand * wand, const double radius, const double sigma)
Definition at line 10534 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickShaveImage (MagickWand * wand, const size_t columns, const size_t rows)
Definition at line 10583 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickShearImage (MagickWand * wand, const PixelWand * background, const double x_shear, const double y_shear)
Definition at line 10644 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, PixelGetQuantumPacket(), _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickSigmoidalContrastImage (MagickWand * wand, const MagickBooleanType sharpen, const double alpha, const double beta)
Definition at line 10701 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickWand* MagickSimilarityImage (MagickWand * wand, const MagickWand * reference, const MetricType metric, const double similarity_threshold, RectangleInfo * offset, double * similarity)
Definition at line 10757 of file magick-image.c.
References CloneMagickWandFromImages(), _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickSketchImage (MagickWand * wand, const double radius, const double sigma, const double angle)
Definition at line 10815 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickWand* MagickSmushImages (MagickWand * wand, const MagickBooleanType stack, const ssize_t offset)
Definition at line 10864 of file magick-image.c.
References CloneMagickWandFromImages(), _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickSolarizeImage (MagickWand * wand, const double threshold)
Definition at line 10910 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickSparseColorImage (MagickWand * wand, const SparseColorMethod method, const size_t number_arguments, const double * arguments)
Definition at line 10977 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickSpliceImage (MagickWand * wand, const size_t width, const size_t height, const ssize_t x, const ssize_t y)
Definition at line 11030 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickSpreadImage (MagickWand * wand, const double radius, const PixelInterpolateMethod method)
Definition at line 11085 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickStatisticImage (MagickWand * wand, const StatisticType type, const size_t width, const size_t height)
Definition at line 11134 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickWand* MagickSteganoImage (MagickWand * wand, const MagickWand * watermark_wand, const ssize_t offset)
Definition at line 11184 of file magick-image.c.
References CloneMagickWandFromImages(), _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickWand* MagickStereoImage (MagickWand * wand, const MagickWand * offset_wand)
Definition at line 11235 of file magick-image.c.
References CloneMagickWandFromImages(), _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickStripImage (MagickWand * wand)
Definition at line 11280 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickSwirlImage (MagickWand * wand, const double degrees, const PixelInterpolateMethod method)
Definition at line 11320 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickWand* MagickTextureImage (MagickWand * wand, const MagickWand * texture_wand)
Definition at line 11365 of file magick-image.c.
References CloneMagickWandFromImages(), _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickThresholdImage (MagickWand * wand, const double threshold)
Definition at line 11428 of file magick-image.c.
References MagickThresholdImageChannel().
WandExport MagickBooleanType MagickThresholdImageChannel (MagickWand * wand, const ChannelType channel, const double threshold)
Definition at line 11438 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
Referenced by MagickThresholdImage().
WandExport MagickBooleanType MagickThumbnailImage (MagickWand * wand, const size_t columns, const size_t rows)
Definition at line 11483 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickTintImage (MagickWand * wand, const PixelWand * tint, const PixelWand * blend)
Definition at line 11532 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, MaxTextExtent, _MagickWand::name, PixelGetAlphaQuantum(), PixelGetBlackQuantum(), PixelGetBlueQuantum(), PixelGetCyanQuantum(), PixelGetGreenQuantum(), PixelGetMagentaQuantum(), PixelGetPixel(), PixelGetRedQuantum(), PixelGetYellowQuantum(), _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickWand* MagickTransformImage (MagickWand * wand, const char * crop, const char * geometry)
Definition at line 11605 of file magick-image.c.
References CloneMagickWandFromImages(), _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickTransformImageColorspace (MagickWand * wand, const ColorspaceType colorspace)
Definition at line 11664 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickTransparentPaintImage (MagickWand * wand, const PixelWand * target, const double alpha, const double fuzz, const MagickBooleanType invert)
Definition at line 11716 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, PixelGetMagickColor(), _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickTransposeImage (MagickWand * wand)
Definition at line 11762 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickTransverseImage (MagickWand * wand)
Definition at line 11803 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickTrimImage (MagickWand * wand, const double fuzz)
Definition at line 11850 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickUniqueImageColors (MagickWand * wand)
Definition at line 11891 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickUnsharpMaskImage (MagickWand * wand, const double radius, const double sigma, const double gain, const double threshold)
Definition at line 11946 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickVignetteImage (MagickWand * wand, const double radius, const double sigma, const ssize_t x, const ssize_t y)
Definition at line 11997 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickWaveImage (MagickWand * wand, const double amplitude, const double wave_length, const PixelInterpolateMethod method)
Definition at line 12047 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickWhiteThresholdImage (MagickWand * wand, const PixelWand * threshold)
Definition at line 12095 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, MaxTextExtent, _MagickWand::name, PixelGetAlphaQuantum(), PixelGetBlueQuantum(), PixelGetGreenQuantum(), PixelGetRedQuantum(), _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickWriteImage (MagickWand * wand, const char * filename)
Definition at line 12142 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _DrawingWand::image, _MagickWand::image_info, _MagickWand::images, MaxTextExtent, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickWriteImageFile (MagickWand * wand, FILE * file)
Definition at line 12197 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _DrawingWand::image, _MagickWand::image_info, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickWriteImages (MagickWand * wand, const char * filename, const MagickBooleanType adjoin)
Definition at line 12254 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::image_info, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickWriteImagesFile (MagickWand * wand, FILE * file)
Definition at line 12300 of file magick-image.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::image_info, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.