MagickWand: magick-property.c File Reference
magick-property.c File Reference
#include "MagickWand/studio.h"
#include "MagickWand/MagickWand.h"
#include "MagickWand/magick-wand-private.h"
#include "MagickWand/wand.h"
#include "MagickCore/string-private.h"
Macros
#define ThrowWandException(severity, tag, context)
Functions
WandExport MagickBooleanType MagickDeleteImageArtifact (MagickWand *wand, const char *artifact)
WandExport MagickBooleanType MagickDeleteImageProperty (MagickWand *wand, const char *property)
WandExport MagickBooleanType MagickDeleteOption (MagickWand *wand, const char *option)
WandExport MagickBooleanType MagickGetAntialias (const MagickWand *wand)
WandExport PixelWand * MagickGetBackgroundColor (MagickWand *wand)
WandExport ColorspaceType MagickGetColorspace (MagickWand *wand)
WandExport CompressionType MagickGetCompression (MagickWand *wand)
WandExport size_t MagickGetCompressionQuality (MagickWand *wand)
WandExport const char * MagickGetCopyright (void)
WandExport char * MagickGetFilename (const MagickWand *wand)
WandExport char * MagickGetFont (MagickWand *wand)
WandExport char * MagickGetFormat (MagickWand *wand)
WandExport GravityType MagickGetGravity (MagickWand *wand)
WandExport char * MagickGetHomeURL (void)
WandExport char * MagickGetImageArtifact (MagickWand *wand, const char *artifact)
WandExport char ** MagickGetImageArtifacts (MagickWand *wand, const char *pattern, size_t *number_artifacts)
WandExport unsigned char * MagickGetImageProfile (MagickWand *wand, const char *name, size_t *length)
WandExport char ** MagickGetImageProfiles (MagickWand *wand, const char *pattern, size_t *number_profiles)
WandExport char * MagickGetImageProperty (MagickWand *wand, const char *property)
WandExport char ** MagickGetImageProperties (MagickWand *wand, const char *pattern, size_t *number_properties)
WandExport InterlaceType MagickGetInterlaceScheme (MagickWand *wand)
WandExport PixelInterpolateMethod MagickGetInterpolateMethod (MagickWand *wand)
WandExport char * MagickGetOption (MagickWand *wand, const char *key)
WandExport char ** MagickGetOptions (MagickWand *wand, const char *pattern, size_t *number_options)
WandExport OrientationType MagickGetOrientation (MagickWand *wand)
WandExport const char * MagickGetPackageName (void)
WandExport MagickBooleanType MagickGetPage (const MagickWand *wand, size_t *width, size_t *height, ssize_t *x, ssize_t *y)
WandExport double MagickGetPointsize (MagickWand *wand)
WandExport const char * MagickGetQuantumDepth (size_t *depth)
WandExport const char * MagickGetQuantumRange (size_t *range)
WandExport const char * MagickGetReleaseDate (void)
WandExport MagickBooleanType MagickGetResolution (const MagickWand *wand, double *x, double *y)
WandExport MagickSizeType MagickGetResource (const ResourceType type)
WandExport MagickSizeType MagickGetResourceLimit (const ResourceType type)
WandExport double * MagickGetSamplingFactors (MagickWand *wand, size_t *number_factors)
WandExport MagickBooleanType MagickGetSize (const MagickWand *wand, size_t *columns, size_t *rows)
WandExport MagickBooleanType MagickGetSizeOffset (const MagickWand *wand, ssize_t *offset)
WandExport ImageType MagickGetType (MagickWand *wand)
WandExport const char * MagickGetVersion (size_t *version)
WandExport MagickBooleanType MagickProfileImage (MagickWand *wand, const char *name, const void *profile, const size_t length)
WandExport unsigned char * MagickRemoveImageProfile (MagickWand *wand, const char *name, size_t *length)
WandExport MagickBooleanType MagickSetAntialias (MagickWand *wand, const MagickBooleanType antialias)
WandExport MagickBooleanType MagickSetBackgroundColor (MagickWand *wand, const PixelWand *background)
WandExport MagickBooleanType MagickSetColorspace (MagickWand *wand, const ColorspaceType colorspace)
WandExport MagickBooleanType MagickSetCompression (MagickWand *wand, const CompressionType compression)
WandExport MagickBooleanType MagickSetCompressionQuality (MagickWand *wand, const size_t quality)
WandExport MagickBooleanType MagickSetDepth (MagickWand *wand, const size_t depth)
WandExport MagickBooleanType MagickSetExtract (MagickWand *wand, const char *geometry)
WandExport MagickBooleanType MagickSetFilename (MagickWand *wand, const char *filename)
WandExport MagickBooleanType MagickSetFont (MagickWand *wand, const char *font)
WandExport MagickBooleanType MagickSetFormat (MagickWand *wand, const char *format)
WandExport MagickBooleanType MagickSetGravity (MagickWand *wand, const GravityType type)
WandExport MagickBooleanType MagickSetImageArtifact (MagickWand *wand, const char *artifact, const char *value)
WandExport MagickBooleanType MagickSetImageProfile (MagickWand *wand, const char *name, const void *profile, const size_t length)
WandExport MagickBooleanType MagickSetImageProperty (MagickWand *wand, const char *property, const char *value)
WandExport MagickBooleanType MagickSetInterlaceScheme (MagickWand *wand, const InterlaceType interlace_scheme)
WandExport MagickBooleanType MagickSetInterpolateMethod (MagickWand *wand, const PixelInterpolateMethod method)
WandExport MagickBooleanType MagickSetOption (MagickWand *wand, const char *key, const char *value)
WandExport MagickBooleanType MagickSetOrientation (MagickWand *wand, const OrientationType orientation)
WandExport MagickBooleanType MagickSetPage (MagickWand *wand, const size_t width, const size_t height, const ssize_t x, const ssize_t y)
WandExport MagickBooleanType MagickSetPassphrase (MagickWand *wand, const char *passphrase)
WandExport MagickBooleanType MagickSetPointsize (MagickWand *wand, const double pointsize)
WandExport MagickProgressMonitor MagickSetProgressMonitor (MagickWand *wand, const MagickProgressMonitor progress_monitor, void *client_data)
WandExport MagickBooleanType MagickSetResourceLimit (const ResourceType type, const MagickSizeType limit)
WandExport MagickBooleanType MagickSetResolution (MagickWand *wand, const double x_resolution, const double y_resolution)
WandExport MagickBooleanType MagickSetSamplingFactors (MagickWand *wand, const size_t number_factors, const double *sampling_factors)
WandExport MagickBooleanType MagickSetSize (MagickWand *wand, const size_t columns, const size_t rows)
WandExport MagickBooleanType MagickSetSizeOffset (MagickWand *wand, const size_t columns, const size_t rows, const ssize_t offset)
WandExport MagickBooleanType MagickSetType (MagickWand *wand, const ImageType image_type)
Macro Definition Documentation
#define ThrowWandException (severity, tag, context)
Value:
{ \
  (void) ThrowMagickException(wand->exception,GetMagickModule(),severity, \
    tag,"`%s'",context); \
  return(MagickFalse); \
}
Definition at line 58 of file magick-property.c.
Referenced by MagickProfileImage(), MagickSetImageArtifact(), MagickSetImageProfile(), and MagickSetImageProperty().
Function Documentation
WandExport MagickBooleanType MagickDeleteImageArtifact (MagickWand * wand, const char * artifact)
Definition at line 90 of file magick-property.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickDeleteImageProperty (MagickWand * wand, const char * property)
Definition at line 132 of file magick-property.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickDeleteOption (MagickWand * wand, const char * option)
Definition at line 174 of file magick-property.c.
References _MagickWand::debug, _MagickWand::image_info, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickGetAntialias (const MagickWand * wand)
Definition at line 208 of file magick-property.c.
References _MagickWand::debug, _MagickWand::image_info, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport PixelWand* MagickGetBackgroundColor (MagickWand * wand)
Definition at line 240 of file magick-property.c.
References _MagickWand::debug, _MagickWand::image_info, _MagickWand::name, NewPixelWand(), PixelSetPixelColor(), _MagickWand::signature, and WandSignature.
WandExport ColorspaceType MagickGetColorspace (MagickWand * wand)
Definition at line 277 of file magick-property.c.
References _MagickWand::debug, _MagickWand::image_info, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport CompressionType MagickGetCompression (MagickWand * wand)
Definition at line 309 of file magick-property.c.
References _MagickWand::debug, _MagickWand::image_info, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport size_t MagickGetCompressionQuality (MagickWand * wand)
Definition at line 341 of file magick-property.c.
References _MagickWand::debug, _MagickWand::image_info, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport const char* MagickGetCopyright (void)
Definition at line 370 of file magick-property.c.
WandExport char* MagickGetFilename (const MagickWand * wand)
Definition at line 397 of file magick-property.c.
References _MagickWand::debug, _MagickWand::image_info, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport char* MagickGetFont (MagickWand * wand)
Definition at line 429 of file magick-property.c.
References _MagickWand::debug, _MagickWand::image_info, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport char* MagickGetFormat (MagickWand * wand)
Definition at line 463 of file magick-property.c.
References _MagickWand::debug, _MagickWand::image_info, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport GravityType MagickGetGravity (MagickWand * wand)
Definition at line 495 of file magick-property.c.
References _MagickWand::debug, _MagickWand::image_info, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport char* MagickGetHomeURL (void)
Definition at line 533 of file magick-property.c.
WandExport char* MagickGetImageArtifact (MagickWand * wand, const char * artifact)
Definition at line 564 of file magick-property.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport char** MagickGetImageArtifacts (MagickWand * wand, const char * pattern, size_t * number_artifacts)
Definition at line 616 of file magick-property.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport unsigned char* MagickGetImageProfile (MagickWand * wand, const char * name, size_t * length)
Definition at line 704 of file magick-property.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport char** MagickGetImageProfiles (MagickWand * wand, const char * pattern, size_t * number_profiles)
Definition at line 770 of file magick-property.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport char** MagickGetImageProperties (MagickWand * wand, const char * pattern, size_t * number_properties)
Definition at line 909 of file magick-property.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport char* MagickGetImageProperty (MagickWand * wand, const char * property)
Definition at line 857 of file magick-property.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport InterlaceType MagickGetInterlaceScheme (MagickWand * wand)
Definition at line 992 of file magick-property.c.
References _MagickWand::debug, _MagickWand::image_info, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport PixelInterpolateMethod MagickGetInterpolateMethod (MagickWand * wand)
Definition at line 1024 of file magick-property.c.
References _MagickWand::debug, _MagickWand::image_info, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport char* MagickGetOption (MagickWand * wand, const char * key)
Definition at line 1071 of file magick-property.c.
References _MagickWand::debug, _MagickWand::image_info, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport char** MagickGetOptions (MagickWand * wand, const char * pattern, size_t * number_options)
Definition at line 1115 of file magick-property.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::image_info, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport OrientationType MagickGetOrientation (MagickWand * wand)
Definition at line 1197 of file magick-property.c.
References _MagickWand::debug, _MagickWand::image_info, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport const char* MagickGetPackageName (void)
Definition at line 1227 of file magick-property.c.
WandExport MagickBooleanType MagickGetPage (const MagickWand * wand, size_t * width, size_t * height, ssize_t * x, ssize_t * y)
Definition at line 1263 of file magick-property.c.
References _MagickWand::debug, _MagickWand::image_info, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport double MagickGetPointsize (MagickWand * wand)
Definition at line 1306 of file magick-property.c.
References _MagickWand::debug, _MagickWand::image_info, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport const char* MagickGetQuantumDepth (size_t * depth)
Definition at line 1339 of file magick-property.c.
WandExport const char* MagickGetQuantumRange (size_t * range)
Definition at line 1367 of file magick-property.c.
WandExport const char* MagickGetReleaseDate (void)
Definition at line 1391 of file magick-property.c.
WandExport MagickBooleanType MagickGetResolution (const MagickWand * wand, double * x, double * y)
Definition at line 1423 of file magick-property.c.
References _MagickWand::debug, _MagickWand::image_info, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickSizeType MagickGetResource (const ResourceType type)
Definition at line 1472 of file magick-property.c.
WandExport MagickSizeType MagickGetResourceLimit (const ResourceType type)
Definition at line 1499 of file magick-property.c.
WandExport double* MagickGetSamplingFactors (MagickWand * wand, size_t * number_factors)
Definition at line 1529 of file magick-property.c.
References _MagickWand::debug, _MagickWand::image_info, _MagickWand::name, _MagickWand::signature, ThrowWandFatalException, and WandSignature.
WandExport MagickBooleanType MagickGetSize (const MagickWand * wand, size_t * columns, size_t * rows)
Definition at line 1603 of file magick-property.c.
References _MagickWand::debug, _MagickWand::image_info, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickGetSizeOffset (const MagickWand * wand, ssize_t * offset)
Definition at line 1647 of file magick-property.c.
References _MagickWand::debug, _MagickWand::image_info, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport ImageType MagickGetType (MagickWand * wand)
Definition at line 1686 of file magick-property.c.
References _MagickWand::debug, _MagickWand::image_info, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport const char* MagickGetVersion (size_t * version)
Definition at line 1719 of file magick-property.c.
WandExport MagickBooleanType MagickProfileImage (MagickWand * wand, const char * name, const void * profile, const size_t length)
Definition at line 1756 of file magick-property.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport unsigned char* MagickRemoveImageProfile (MagickWand * wand, const char * name, size_t * length)
Definition at line 1796 of file magick-property.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickSetAntialias (MagickWand * wand, const MagickBooleanType antialias)
Definition at line 1856 of file magick-property.c.
References _MagickWand::debug, _MagickWand::image_info, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickSetBackgroundColor (MagickWand * wand, const PixelWand * background)
Definition at line 1893 of file magick-property.c.
References _MagickWand::debug, _MagickWand::image_info, _MagickWand::name, PixelGetQuantumPacket(), _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickSetColorspace (MagickWand * wand, const ColorspaceType colorspace)
Definition at line 1930 of file magick-property.c.
References _MagickWand::debug, _MagickWand::image_info, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickSetCompression (MagickWand * wand, const CompressionType compression)
Definition at line 1967 of file magick-property.c.
References _MagickWand::debug, _MagickWand::image_info, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickSetCompressionQuality (MagickWand * wand, const size_t quality)
Definition at line 2004 of file magick-property.c.
References _MagickWand::debug, _MagickWand::image_info, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickSetDepth (MagickWand * wand, const size_t depth)
Definition at line 2041 of file magick-property.c.
References _MagickWand::debug, _MagickWand::image_info, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickSetExtract (MagickWand * wand, const char * geometry)
Definition at line 2080 of file magick-property.c.
References _MagickWand::debug, _MagickWand::image_info, MaxTextExtent, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickSetFilename (MagickWand * wand, const char * filename)
Definition at line 2118 of file magick-property.c.
References _MagickWand::debug, _MagickWand::image_info, MaxTextExtent, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickSetFont (MagickWand * wand, const char * font)
Definition at line 2155 of file magick-property.c.
References _MagickWand::debug, _MagickWand::image_info, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickSetFormat (MagickWand * wand, const char * format)
Definition at line 2192 of file magick-property.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::image_info, MaxTextExtent, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickSetGravity (MagickWand * wand, const GravityType type)
Definition at line 2241 of file magick-property.c.
References _MagickWand::debug, _MagickWand::image_info, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickSetImageArtifact (MagickWand * wand, const char * artifact, const char * value)
Definition at line 2284 of file magick-property.c.
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickSetImageProfile (MagickWand * wand, const char * name, const void * profile, const size_t length)
Definition at line 2329 of file magick-property.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickSetImageProperty (MagickWand * wand, const char * property, const char * value)
Definition at line 2379 of file magick-property.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
WandExport MagickBooleanType MagickSetInterlaceScheme (MagickWand * wand, const InterlaceType interlace_scheme)
Definition at line 2422 of file magick-property.c.
References _MagickWand::debug, _MagickWand::image_info, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickSetInterpolateMethod (MagickWand * wand, const PixelInterpolateMethod method)
Definition at line 2459 of file magick-property.c.
References _MagickWand::debug, _MagickWand::image_info, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickSetOption (MagickWand * wand, const char * key, const char * value)
Definition at line 2503 of file magick-property.c.
References _MagickWand::debug, _MagickWand::image_info, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickSetOrientation (MagickWand * wand, const OrientationType orientation)
Definition at line 2539 of file magick-property.c.
References _MagickWand::debug, _MagickWand::image_info, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickSetPage (MagickWand * wand, const size_t width, const size_t height, const ssize_t x, const ssize_t y)
Definition at line 2583 of file magick-property.c.
References _MagickWand::debug, _MagickWand::image_info, MaxTextExtent, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickSetPassphrase (MagickWand * wand, const char * passphrase)
Definition at line 2626 of file magick-property.c.
References _MagickWand::debug, _MagickWand::image_info, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickSetPointsize (MagickWand * wand, const double pointsize)
Definition at line 2663 of file magick-property.c.
References _MagickWand::debug, _MagickWand::image_info, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickProgressMonitor MagickSetProgressMonitor (MagickWand * wand, const MagickProgressMonitor progress_monitor, void * client_data)
Definition at line 2712 of file magick-property.c.
References _MagickWand::debug, _MagickWand::image_info, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickSetResolution (MagickWand * wand, const double x_resolution, const double y_resolution)
Definition at line 2788 of file magick-property.c.
References _MagickWand::debug, _MagickWand::image_info, MaxTextExtent, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickSetResourceLimit (const ResourceType type, const MagickSizeType limit)
Definition at line 2755 of file magick-property.c.
WandExport MagickBooleanType MagickSetSamplingFactors (MagickWand * wand, const size_t number_factors, const double * sampling_factors)
Definition at line 2833 of file magick-property.c.
References _MagickWand::debug, _MagickWand::image_info, MaxTextExtent, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickSetSize (MagickWand * wand, const size_t columns, const size_t rows)
Definition at line 2893 of file magick-property.c.
References _MagickWand::debug, _MagickWand::image_info, MaxTextExtent, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickSetSizeOffset (MagickWand * wand, const size_t columns, const size_t rows, const ssize_t offset)
Definition at line 2941 of file magick-property.c.
References _MagickWand::debug, _MagickWand::image_info, MaxTextExtent, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickSetType (MagickWand * wand, const ImageType image_type)
Definition at line 2986 of file magick-property.c.
References _MagickWand::debug, _MagickWand::image_info, _MagickWand::name, _MagickWand::signature, and WandSignature.