MagickWand: magick-wand.c File Reference
magick-wand.c File Reference
#include "MagickWand/studio.h"
#include "MagickWand/MagickWand.h"
#include "MagickWand/magick-wand-private.h"
#include "MagickWand/wand.h"
Macros
#define ThrowWandException(severity, tag, context)
Functions
WandExport void ClearMagickWand (MagickWand *wand)
WandExport MagickWand * CloneMagickWand (const MagickWand *wand)
WandExport MagickWand * DestroyMagickWand (MagickWand *wand)
WandExport MagickBooleanType IsMagickWand (const MagickWand *wand)
WandExport MagickBooleanType MagickClearException (MagickWand *wand)
WandExport char * MagickGetException (const MagickWand *wand, ExceptionType *severity)
WandExport ExceptionType MagickGetExceptionType (const MagickWand *wand)
WandExport ssize_t MagickGetIteratorIndex (MagickWand *wand)
WandExport char * MagickQueryConfigureOption (const char *option)
WandExport char ** MagickQueryConfigureOptions (const char *pattern, size_t *number_options)
WandExport double * MagickQueryFontMetrics (MagickWand *wand, const DrawingWand *drawing_wand, const char *text)
WandExport double * MagickQueryMultilineFontMetrics (MagickWand *wand, const DrawingWand *drawing_wand, const char *text)
WandExport char ** MagickQueryFonts (const char *pattern, size_t *number_fonts)
WandExport char ** MagickQueryFormats (const char *pattern, size_t *number_formats)
WandExport void * MagickRelinquishMemory (void *memory)
WandExport void MagickResetIterator (MagickWand *wand)
WandExport void MagickSetFirstIterator (MagickWand *wand)
WandExport MagickBooleanType MagickSetIteratorIndex (MagickWand *wand, const ssize_t index)
WandExport void MagickSetLastIterator (MagickWand *wand)
WandExport void MagickWandGenesis (void)
WandExport void MagickWandTerminus (void)
WandExport MagickWand * NewMagickWand (void)
WandExport MagickWand * NewMagickWandFromImage (const Image *image)
Macro Definition Documentation
#define ThrowWandException (severity, tag, context)
Value:
{ \
  (void) ThrowMagickException(wand->exception,GetMagickModule(),severity, \
    tag,"`%s'",context); \
  return(MagickFalse); \
}
Definition at line 57 of file magick-wand.c.
Function Documentation
WandExport void ClearMagickWand (MagickWand * wand)
Definition at line 87 of file magick-wand.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::image_info, _MagickWand::image_pending, _MagickWand::images, _MagickWand::insert_before, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickWand* CloneMagickWand (const MagickWand * wand)
Definition at line 124 of file magick-wand.c.
References AcquireWandId(), _MagickWand::debug, _MagickWand::exception, _MagickWand::id, _MagickWand::image_info, _MagickWand::image_pending, _MagickWand::images, _MagickWand::insert_before, MagickWandId, MaxTextExtent, _MagickWand::name, _MagickWand::signature, ThrowWandFatalException, and WandSignature.
WandExport MagickWand* DestroyMagickWand (MagickWand * wand)
Definition at line 176 of file magick-wand.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::id, _MagickWand::image_info, _MagickWand::images, _MagickWand::name, RelinquishWandId(), _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType IsMagickWand (const MagickWand * wand)
Definition at line 215 of file magick-wand.c.
References MagickWandId, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickClearException (MagickWand * wand)
Definition at line 248 of file magick-wand.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport char* MagickGetException (const MagickWand * wand, ExceptionType * severity)
Definition at line 283 of file magick-wand.c.
References _MagickWand::debug, _MagickWand::exception, MaxTextExtent, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport ExceptionType MagickGetExceptionType (const MagickWand * wand)
Definition at line 340 of file magick-wand.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport ssize_t MagickGetIteratorIndex (MagickWand * wand)
Definition at line 372 of file magick-wand.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport char* MagickQueryConfigureOption (const char * option)
Definition at line 410 of file magick-wand.c.
WandExport char** MagickQueryConfigureOptions (const char * pattern, size_t * number_options)
Definition at line 463 of file magick-wand.c.
WandExport double* MagickQueryFontMetrics (MagickWand * wand, const DrawingWand * drawing_wand, const char * text)
Definition at line 522 of file magick-wand.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, PeekDrawingWand(), _MagickWand::signature, and WandSignature.
WandExport char** MagickQueryFonts (const char * pattern, size_t * number_fonts)
Definition at line 716 of file magick-wand.c.
WandExport char** MagickQueryFormats (const char * pattern, size_t * number_formats)
Definition at line 758 of file magick-wand.c.
WandExport double* MagickQueryMultilineFontMetrics (MagickWand * wand, const DrawingWand * drawing_wand, const char * text)
Definition at line 629 of file magick-wand.c.
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, PeekDrawingWand(), _MagickWand::signature, and WandSignature.
WandExport void* MagickRelinquishMemory (void * memory)
Definition at line 796 of file magick-wand.c.
WandExport void MagickResetIterator (MagickWand * wand)
Definition at line 834 of file magick-wand.c.
References _MagickWand::debug, _MagickWand::image_pending, _MagickWand::images, _MagickWand::insert_before, _MagickWand::name, _MagickWand::signature, and WandSignature.
Referenced by CLINoImageOperator(), and CLISimpleOperatorImages().
WandExport void MagickSetFirstIterator (MagickWand * wand)
Definition at line 878 of file magick-wand.c.
References _MagickWand::debug, _MagickWand::image_pending, _MagickWand::images, _MagickWand::insert_before, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport MagickBooleanType MagickSetIteratorIndex (MagickWand * wand, const ssize_t index)
Definition at line 930 of file magick-wand.c.
References _MagickWand::debug, _MagickWand::image_pending, _MagickWand::images, _MagickWand::insert_before, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport void MagickSetLastIterator (MagickWand * wand)
Definition at line 981 of file magick-wand.c.
References _MagickWand::debug, _MagickWand::image_pending, _MagickWand::images, _MagickWand::insert_before, _MagickWand::name, _MagickWand::signature, and WandSignature.
WandExport void MagickWandGenesis (void)
Definition at line 1010 of file magick-wand.c.
WandExport void MagickWandTerminus (void)
Definition at line 1034 of file magick-wand.c.
References DestroyWandIds().
WandExport MagickWand* NewMagickWand (void)
Definition at line 1061 of file magick-wand.c.
References AcquireWandId(), _MagickWand::debug, _MagickWand::exception, _MagickWand::id, _MagickWand::image_info, _MagickWand::images, MagickWandId, MaxTextExtent, _MagickWand::name, _MagickWand::signature, ThrowWandFatalException, and WandSignature.
Referenced by NewMagickWandFromImage().
WandExport MagickWand* NewMagickWandFromImage (const Image * image)
Definition at line 1116 of file magick-wand.c.
References _MagickWand::exception, _MagickWand::images, and NewMagickWand().