MagickWand: mogrify.c File Reference
mogrify.c File Reference
#include "MagickWand/studio.h"
#include "MagickWand/MagickWand.h"
#include "MagickWand/mogrify-private.h"
#include "MagickCore/image-private.h"
#include "MagickCore/monitor-private.h"
#include "MagickCore/string-private.h"
#include "MagickCore/thread-private.h"
#include "MagickCore/utility-private.h"
Macros
#define UndefinedCompressionQuality 0UL
#define DestroyMogrify()
#define ThrowMogrifyException(asperity, tag, option)
#define ThrowMogrifyInvalidArgumentException(option, argument)
#define MogrifyImageTag "Mogrify/Image"
Functions
WandExport MagickBooleanType MagickCommandGenesis (ImageInfo *image_info, MagickCommand command, int argc, char **argv, char **metadata, ExceptionInfo *exception)
static Image * GetImageCache (const ImageInfo *image_info, const char *path, ExceptionInfo *exception)
static MagickBooleanType IsPathWritable (const char *path)
static ssize_t MagickMax (const ssize_t x, const ssize_t y)
static MagickBooleanType MonitorProgress (const char *text, const MagickOffsetType offset, const MagickSizeType extent, void *wand_unused(client_data))
static Image * SparseColorOption (const Image *image, const SparseColorMethod method, const char *arguments, const MagickBooleanType color_from_image, ExceptionInfo *exception)
WandExport MagickBooleanType MogrifyImage (ImageInfo *image_info, const int argc, const char **argv, Image **image, ExceptionInfo *exception)
static MagickBooleanType MogrifyUsage (void)
WandExport MagickBooleanType MogrifyImageCommand (ImageInfo *image_info, int argc, char **argv, char **wand_unused(metadata), ExceptionInfo *exception)
WandExport MagickBooleanType MogrifyImageInfo (ImageInfo *image_info, const int argc, const char **argv, ExceptionInfo *exception)
WandExport MagickBooleanType MogrifyImageList (ImageInfo *image_info, const int argc, const char **argv, Image **images, ExceptionInfo *exception)
WandExport MagickBooleanType MogrifyImages (ImageInfo *image_info, const MagickBooleanType post, const int argc, const char **argv, Image **images, ExceptionInfo *exception)
Variables
static const char MogrifyBackgroundColor [] = "#ffffff"
static const char MogrifyBorderColor [] = "#dfdfdf"
static const char MogrifyMatteColor [] = "#bdbdbd"
Macro Definition Documentation
#define DestroyMogrify ()
Value:
{ \
  if (format != (char *) NULL) \
    format=DestroyString(format); \
  if (path != (char *) NULL) \
    path=DestroyString(path); \
  DestroyImageStack(); \
  for (i=0; i < (ssize_t) argc; i++) \
    argv[i]=DestroyString(argv[i]); \
  argv=(char **) RelinquishMagickMemory(argv); \
}
Referenced by MogrifyImageCommand().
#define MogrifyImageTag "Mogrify/Image"
Referenced by MogrifyImages().
#define ThrowMogrifyException (asperity, tag, option)
Value:
{ \
  (void) ThrowMagickException(exception,GetMagickModule(),asperity,tag,"`%s'", \
    option); \
  DestroyMogrify(); \
  return(MagickFalse); \
}
Referenced by MogrifyImageCommand().
#define ThrowMogrifyInvalidArgumentException (option, argument)
Value:
{ \
  (void) ThrowMagickException(exception,GetMagickModule(),OptionError, \
    "InvalidArgument","'%s': %s",argument,option); \
  DestroyMogrify(); \
  return(MagickFalse); \
}
Referenced by MogrifyImageCommand().
#define UndefinedCompressionQuality 0UL
Definition at line 69 of file mogrify.c.
Referenced by MogrifyImageInfo().
Function Documentation
static Image* GetImageCache (const ImageInfo * image_info, const char * path, ExceptionInfo * exception) inline static
Definition at line 343 of file mogrify.c.
References MaxTextExtent.
Referenced by MogrifyImage().
static MagickBooleanType IsPathWritable (const char * path) inline static
Definition at line 377 of file mogrify.c.
Referenced by MogrifyImageCommand().
WandExport MagickBooleanType MagickCommandGenesis (ImageInfo * image_info, MagickCommand command, int argc, char ** argv, char ** metadata, ExceptionInfo * exception)
Definition at line 117 of file mogrify.c.
static ssize_t MagickMax (const ssize_t x, const ssize_t y) inline static
Definition at line 386 of file mogrify.c.
Referenced by MogrifyImage(), MogrifyImageInfo(), and MogrifyImageList().
WandExport MagickBooleanType MogrifyImage (ImageInfo * image_info, const int argc, const char ** argv, Image ** image, ExceptionInfo * exception)
Definition at line 657 of file mogrify.c.
References DegreesToRadians, GetImageCache(), MagickMax(), MaxTextExtent, MogrifyBorderColor, MogrifyImageInfo(), MonitorProgress(), SparseColorOption(), and ThrowWandFatalException.
Referenced by MogrifyImages().
WandExport MagickBooleanType MogrifyImageCommand (ImageInfo * image_info, int argc, char ** argv, char ** wand_unusedmetadata, ExceptionInfo * exception)
Definition at line 3577 of file mogrify.c.
References AppendImageStack, DestroyMogrify, DirectorySeparator, FinalizeImageSettings, FireImageStack, IsPathWritable(), MaxImageStackDepth, MaxTextExtent, MogrifyImageInfo(), MogrifyUsage(), NewImageStack, PopImageStack, PushImageStack, ReadCommandlLine, RemoveAllImageStack, ThrowMogrifyException, and ThrowMogrifyInvalidArgumentException.
WandExport MagickBooleanType MogrifyImageInfo (ImageInfo * image_info, const int argc, const char ** argv, ExceptionInfo * exception)
Definition at line 6185 of file mogrify.c.
References MagickMax(), MaxTextExtent, MogrifyBackgroundColor, MogrifyBorderColor, MogrifyMatteColor, MonitorProgress(), and UndefinedCompressionQuality.
Referenced by AnimateImageCommand(), CompareImagesCommand(), CompositeImageCommand(), ConvertImageCommand(), DisplayImageCommand(), IdentifyImageCommand(), ImportImageCommand(), MogrifyImage(), MogrifyImageCommand(), MogrifyImageList(), MontageImageCommand(), and StreamImageCommand().
WandExport MagickBooleanType MogrifyImageList (ImageInfo * image_info, const int argc, const char ** argv, Image ** images, ExceptionInfo * exception)
Definition at line 7304 of file mogrify.c.
References MagickMax(), MaxTextExtent, MogrifyImageInfo(), and ThrowWandFatalException.
Referenced by MogrifyImages().
WandExport MagickBooleanType MogrifyImages (ImageInfo * image_info, const MagickBooleanType post, const int argc, const char ** argv, Image ** images, ExceptionInfo * exception)
Definition at line 8371 of file mogrify.c.
References MogrifyImage(), MogrifyImageList(), and MogrifyImageTag.
static MagickBooleanType MogrifyUsage (void) static
Definition at line 3229 of file mogrify.c.
Referenced by MogrifyImageCommand().
static MagickBooleanType MonitorProgress (const char * text, const MagickOffsetType offset, const MagickSizeType extent, void * wand_unusedclient_data) static
Definition at line 393 of file mogrify.c.
References MaxTextExtent.
Referenced by MogrifyImage(), and MogrifyImageInfo().
static Image* SparseColorOption (const Image * image, const SparseColorMethod method, const char * arguments, const MagickBooleanType color_from_image, ExceptionInfo * exception) static
Definition at line 431 of file mogrify.c.
References MaxTextExtent.
Referenced by MogrifyImage().
Variable Documentation
const char MogrifyBackgroundColor[] = "#ffffff" static
Definition at line 62 of file mogrify.c.
Referenced by MogrifyImageInfo().
const char MogrifyBorderColor[] = "#dfdfdf" static
Definition at line 63 of file mogrify.c.
Referenced by MogrifyImage(), and MogrifyImageInfo().
const char MogrifyMatteColor[] = "#bdbdbd" static
Definition at line 64 of file mogrify.c.
Referenced by MogrifyImageInfo().