MagickWand: pixel-wand.h File Reference
pixel-wand.h File Reference
Typedefs
typedef struct _PixelWand PixelWand
Functions
WandExport char * PixelGetColorAsNormalizedString (const PixelWand *)
WandExport char * PixelGetColorAsString (const PixelWand *)
WandExport char * PixelGetException (const PixelWand *, ExceptionType *)
WandExport double PixelGetAlpha (const PixelWand *)
WandExport double PixelGetBlack (const PixelWand *)
WandExport double PixelGetBlue (const PixelWand *)
WandExport double PixelGetCyan (const PixelWand *)
WandExport double PixelGetFuzz (const PixelWand *)
WandExport double PixelGetGreen (const PixelWand *)
WandExport double PixelGetMagenta (const PixelWand *)
WandExport double PixelGetRed (const PixelWand *)
WandExport double PixelGetYellow (const PixelWand *)
WandExport ExceptionType PixelGetExceptionType (const PixelWand *)
WandExport MagickBooleanType IsPixelWand (const PixelWand *)
WandExport MagickBooleanType IsPixelWandSimilar (PixelWand *, PixelWand *, const double)
WandExport MagickBooleanType PixelClearException (PixelWand *)
WandExport MagickBooleanType PixelSetColor (PixelWand *, const char *)
WandExport PixelInfo PixelGetPixel (const PixelWand *)
WandExport PixelWand * ClonePixelWand (const PixelWand *)
WandExport PixelWand ** ClonePixelWands (const PixelWand **, const size_t)
WandExport PixelWand * DestroyPixelWand (PixelWand *)
WandExport PixelWand ** DestroyPixelWands (PixelWand **, const size_t)
WandExport PixelWand * NewPixelWand (void)
WandExport PixelWand ** NewPixelWands (const size_t)
WandExport Quantum PixelGetAlphaQuantum (const PixelWand *)
WandExport Quantum PixelGetBlackQuantum (const PixelWand *)
WandExport Quantum PixelGetBlueQuantum (const PixelWand *)
WandExport Quantum PixelGetCyanQuantum (const PixelWand *)
WandExport Quantum PixelGetGreenQuantum (const PixelWand *)
WandExport Quantum PixelGetIndex (const PixelWand *)
WandExport Quantum PixelGetMagentaQuantum (const PixelWand *)
WandExport Quantum PixelGetRedQuantum (const PixelWand *)
WandExport Quantum PixelGetYellowQuantum (const PixelWand *)
WandExport size_t PixelGetColorCount (const PixelWand *)
WandExport void ClearPixelWand (PixelWand *)
WandExport void PixelGetHSL (const PixelWand *, double *, double *, double *)
WandExport void PixelGetMagickColor (const PixelWand *, PixelInfo *)
WandExport void PixelGetQuantumPacket (const PixelWand *, PixelInfo *)
WandExport void PixelGetQuantumPixel (const Image *, const PixelWand *, Quantum *)
WandExport void PixelSetAlpha (PixelWand *, const double)
WandExport void PixelSetAlphaQuantum (PixelWand *, const Quantum)
WandExport void PixelSetBlack (PixelWand *, const double)
WandExport void PixelSetBlackQuantum (PixelWand *, const Quantum)
WandExport void PixelSetBlue (PixelWand *, const double)
WandExport void PixelSetBlueQuantum (PixelWand *, const Quantum)
WandExport void PixelSetColorFromWand (PixelWand *, const PixelWand *)
WandExport void PixelSetColorCount (PixelWand *, const size_t)
WandExport void PixelSetCyan (PixelWand *, const double)
WandExport void PixelSetCyanQuantum (PixelWand *, const Quantum)
WandExport void PixelSetFuzz (PixelWand *, const double)
WandExport void PixelSetGreen (PixelWand *, const double)
WandExport void PixelSetGreenQuantum (PixelWand *, const Quantum)
WandExport void PixelSetHSL (PixelWand *, const double, const double, const double)
WandExport void PixelSetIndex (PixelWand *, const Quantum)
WandExport void PixelSetMagenta (PixelWand *, const double)
WandExport void PixelSetMagentaQuantum (PixelWand *, const Quantum)
WandExport void PixelSetPixelColor (PixelWand *, const PixelInfo *)
WandExport void PixelSetQuantumPixel (const Image *, const Quantum *, PixelWand *)
WandExport void PixelSetRed (PixelWand *, const double)
WandExport void PixelSetRedQuantum (PixelWand *, const Quantum)
WandExport void PixelSetYellow (PixelWand *, const double)
WandExport void PixelSetYellowQuantum (PixelWand *, const Quantum)
Typedef Documentation
typedef struct _PixelWand PixelWand
Definition at line 25 of file pixel-wand.h.
Function Documentation
WandExport void ClearPixelWand (PixelWand *)
WandExport PixelWand* ClonePixelWand (const PixelWand *)
WandExport PixelWand ** ClonePixelWands (const PixelWand ** , const size_t)
WandExport PixelWand * DestroyPixelWand (PixelWand *)
WandExport PixelWand ** DestroyPixelWands (PixelWand ** , const size_t)
WandExport MagickBooleanType IsPixelWand (const PixelWand *)
WandExport MagickBooleanType IsPixelWandSimilar (PixelWand * , PixelWand * , const double)
WandExport PixelWand * NewPixelWand (void)
WandExport PixelWand ** NewPixelWands (const size_t)
Definition at line 442 of file pixel-wand.c.
References NewPixelWand(), and ThrowWandFatalException.
Referenced by AcquirePixelsThreadSet(), ClearPixelIterator(), MagickGetImageHistogram(), NewPixelIterator(), and NewPixelRegionIterator().
WandExport MagickBooleanType PixelClearException (PixelWand *)
WandExport double PixelGetAlpha (const PixelWand *)
WandExport Quantum PixelGetAlphaQuantum (const PixelWand *)
WandExport double PixelGetBlack (const PixelWand *)
WandExport Quantum PixelGetBlackQuantum (const PixelWand *)
WandExport double PixelGetBlue (const PixelWand *)
WandExport Quantum PixelGetBlueQuantum (const PixelWand *)
WandExport char* PixelGetColorAsNormalizedString (const PixelWand *)
WandExport char * PixelGetColorAsString (const PixelWand *)
WandExport size_t PixelGetColorCount (const PixelWand *)
Definition at line 785 of file pixel-wand.c.
References _PixelWand::count, _PixelWand::debug, _PixelWand::name, _PixelWand::signature, and WandSignature.
WandExport double PixelGetCyan (const PixelWand *)
WandExport Quantum PixelGetCyanQuantum (const PixelWand *)
WandExport char * PixelGetException (const PixelWand * , ExceptionType *)
Definition at line 881 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::exception, MaxTextExtent, _PixelWand::name, _PixelWand::signature, ThrowWandFatalException, and WandSignature.
WandExport ExceptionType PixelGetExceptionType (const PixelWand *)
Definition at line 935 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::exception, _PixelWand::name, _PixelWand::signature, and WandSignature.
WandExport double PixelGetFuzz (const PixelWand *)
WandExport double PixelGetGreen (const PixelWand *)
WandExport Quantum PixelGetGreenQuantum (const PixelWand *)
WandExport void PixelGetHSL (const PixelWand * , double * , double * , double *)
WandExport Quantum PixelGetIndex (const PixelWand *)
WandExport double PixelGetMagenta (const PixelWand *)
WandExport Quantum PixelGetMagentaQuantum (const PixelWand *)
WandExport void PixelGetMagickColor (const PixelWand * , PixelInfo *)
WandExport PixelInfo PixelGetPixel (const PixelWand *)
Definition at line 1225 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
Referenced by MagickColorizeImage(), and MagickTintImage().
WandExport void PixelGetQuantumPacket (const PixelWand * , PixelInfo *)
WandExport void PixelGetQuantumPixel (const Image * , const PixelWand * , Quantum *)
WandExport double PixelGetRed (const PixelWand *)
WandExport Quantum PixelGetRedQuantum (const PixelWand *)
WandExport double PixelGetYellow (const PixelWand *)
Definition at line 1422 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
WandExport Quantum PixelGetYellowQuantum (const PixelWand *)
Definition at line 1453 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
Referenced by MagickTintImage().
WandExport void PixelSetAlpha (PixelWand * , const double)
WandExport void PixelSetAlphaQuantum (PixelWand * , const Quantum)
WandExport void PixelSetBlack (PixelWand * , const double)
WandExport void PixelSetBlackQuantum (PixelWand * , const Quantum)
WandExport void PixelSetBlue (PixelWand * , const double)
WandExport void PixelSetBlueQuantum (PixelWand * , const Quantum)
WandExport MagickBooleanType PixelSetColor (PixelWand * , const char *)
Definition at line 1687 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::exception, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
WandExport void PixelSetColorCount (PixelWand * , const size_t)
WandExport void PixelSetColorFromWand (PixelWand * , const PixelWand *)
WandExport void PixelSetCyan (PixelWand * , const double)
WandExport void PixelSetCyanQuantum (PixelWand * , const Quantum)
WandExport void PixelSetFuzz (PixelWand * , const double)
WandExport void PixelSetGreen (PixelWand * , const double)
WandExport void PixelSetGreenQuantum (PixelWand * , const Quantum)
WandExport void PixelSetHSL (PixelWand * , const double , const double , const double)
WandExport void PixelSetIndex (PixelWand * , const Quantum)
WandExport void PixelSetMagenta (PixelWand * , const double)
WandExport void PixelSetMagentaQuantum (PixelWand * , const Quantum)
WandExport void PixelSetPixelColor (PixelWand * , const PixelInfo *)
WandExport void PixelSetQuantumPixel (const Image * , const Quantum * , PixelWand *)
WandExport void PixelSetRed (PixelWand * , const double)
WandExport void PixelSetRedQuantum (PixelWand * , const Quantum)
WandExport void PixelSetYellow (PixelWand * , const double)
WandExport void PixelSetYellowQuantum (PixelWand * , const Quantum)
Definition at line 2280 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.