MagickWand: pixel-iterator.c File Reference
pixel-iterator.c File Reference
#include "MagickWand/studio.h"
#include "MagickWand/MagickWand.h"
#include "MagickWand/magick-wand-private.h"
#include "MagickWand/pixel-iterator.h"
#include "MagickWand/pixel-wand.h"
#include "MagickWand/wand.h"
Data Structures
struct _PixelIterator
Macros
#define PixelIteratorId "PixelIterator"
Functions
WandExport void ClearPixelIterator (PixelIterator *iterator)
WandExport PixelIterator * ClonePixelIterator (const PixelIterator *iterator)
WandExport PixelIterator * DestroyPixelIterator (PixelIterator *iterator)
WandExport MagickBooleanType IsPixelIterator (const PixelIterator *iterator)
WandExport PixelIterator * NewPixelIterator (MagickWand *wand)
WandExport MagickBooleanType PixelClearIteratorException (PixelIterator *iterator)
WandExport PixelIterator * NewPixelRegionIterator (MagickWand *wand, const ssize_t x, const ssize_t y, const size_t width, const size_t height)
WandExport PixelWand ** PixelGetCurrentIteratorRow (PixelIterator *iterator, size_t *number_wands)
WandExport char * PixelGetIteratorException (const PixelIterator *iterator, ExceptionType *severity)
WandExport ExceptionType PixelGetIteratorExceptionType (const PixelIterator *iterator)
WandExport ssize_t PixelGetIteratorRow (PixelIterator *iterator)
WandExport PixelWand ** PixelGetNextIteratorRow (PixelIterator *iterator, size_t *number_wands)
WandExport PixelWand ** PixelGetPreviousIteratorRow (PixelIterator *iterator, size_t *number_wands)
WandExport void PixelResetIterator (PixelIterator *iterator)
WandExport void PixelSetFirstIteratorRow (PixelIterator *iterator)
WandExport MagickBooleanType PixelSetIteratorRow (PixelIterator *iterator, const ssize_t row)
WandExport void PixelSetLastIteratorRow (PixelIterator *iterator)
WandExport MagickBooleanType PixelSyncIterator (PixelIterator *iterator)
Macro Definition Documentation
#define PixelIteratorId "PixelIterator"
Definition at line 59 of file pixel-iterator.c.
Referenced by ClonePixelIterator(), IsPixelIterator(), NewPixelIterator(), and NewPixelRegionIterator().
Function Documentation
WandExport void ClearPixelIterator (PixelIterator * iterator)
Definition at line 119 of file pixel-iterator.c.
References _PixelIterator::active, _PixelIterator::debug, DestroyPixelWands(), _PixelIterator::exception, _PixelIterator::name, NewPixelWands(), _PixelIterator::pixel_wands, _PixelIterator::region, _PixelIterator::signature, WandSignature, and _PixelIterator::y.
WandExport PixelIterator* ClonePixelIterator (const PixelIterator * iterator)
Definition at line 156 of file pixel-iterator.c.
References AcquireWandId(), _PixelIterator::active, ClonePixelWands(), _PixelIterator::debug, _PixelIterator::exception, _PixelIterator::id, MaxTextExtent, _PixelIterator::name, _PixelIterator::pixel_wands, PixelIteratorId, _PixelIterator::region, _PixelIterator::signature, ThrowWandFatalException, _PixelIterator::view, WandSignature, and _PixelIterator::y.
WandExport PixelIterator* DestroyPixelIterator (PixelIterator * iterator)
Definition at line 212 of file pixel-iterator.c.
References _PixelIterator::debug, DestroyPixelWands(), _PixelIterator::exception, _PixelIterator::id, _PixelIterator::name, _PixelIterator::pixel_wands, _PixelIterator::region, RelinquishWandId(), _PixelIterator::signature, _PixelIterator::view, and WandSignature.
WandExport MagickBooleanType IsPixelIterator (const PixelIterator * iterator)
Definition at line 251 of file pixel-iterator.c.
References _PixelIterator::name, PixelIteratorId, _PixelIterator::signature, and WandSignature.
WandExport PixelIterator* NewPixelIterator (MagickWand * wand)
Definition at line 288 of file pixel-iterator.c.
References AcquireWandId(), _PixelIterator::debug, _PixelIterator::exception, GetImageFromMagickWand(), _PixelIterator::id, MaxTextExtent, _PixelIterator::name, NewPixelWands(), _PixelIterator::pixel_wands, PixelIteratorId, _PixelIterator::region, _PixelIterator::signature, ThrowWandFatalException, _PixelIterator::view, WandSignature, and _PixelIterator::y.
WandExport PixelIterator* NewPixelRegionIterator (MagickWand * wand, const ssize_t x, const ssize_t y, const size_t width, const size_t height)
Definition at line 404 of file pixel-iterator.c.
References AcquireWandId(), _PixelIterator::debug, _PixelIterator::exception, GetImageFromMagickWand(), _PixelIterator::id, MaxTextExtent, _MagickWand::name, _PixelIterator::name, NewPixelWands(), _PixelIterator::pixel_wands, PixelIteratorId, _PixelIterator::region, _PixelIterator::signature, ThrowWandFatalException, _PixelIterator::view, WandSignature, and _PixelIterator::y.
WandExport MagickBooleanType PixelClearIteratorException (PixelIterator * iterator)
Definition at line 367 of file pixel-iterator.c.
References _PixelIterator::debug, _PixelIterator::exception, _PixelIterator::name, _PixelIterator::signature, and WandSignature.
WandExport PixelWand** PixelGetCurrentIteratorRow (PixelIterator * iterator, size_t * number_wands)
Definition at line 489 of file pixel-iterator.c.
References _PixelIterator::active, _PixelIterator::debug, _PixelIterator::exception, _PixelIterator::name, _PixelIterator::pixel_wands, PixelSetQuantumPixel(), _PixelIterator::region, _PixelIterator::signature, _PixelIterator::view, WandSignature, and _PixelIterator::y.
WandExport char* PixelGetIteratorException (const PixelIterator * iterator, ExceptionType * severity)
Definition at line 545 of file pixel-iterator.c.
References _PixelIterator::debug, _PixelIterator::exception, MaxTextExtent, _PixelIterator::name, _PixelIterator::signature, ThrowWandFatalException, and WandSignature.
WandExport ExceptionType PixelGetIteratorExceptionType (const PixelIterator * iterator)
Definition at line 601 of file pixel-iterator.c.
References _PixelIterator::debug, _PixelIterator::exception, _PixelIterator::name, _PixelIterator::signature, and WandSignature.
WandExport ssize_t PixelGetIteratorRow (PixelIterator * iterator)
Definition at line 633 of file pixel-iterator.c.
References _PixelIterator::debug, _PixelIterator::name, _PixelIterator::signature, WandSignature, and _PixelIterator::y.
WandExport PixelWand** PixelGetNextIteratorRow (PixelIterator * iterator, size_t * number_wands)
Definition at line 668 of file pixel-iterator.c.
References _PixelIterator::active, _PixelIterator::debug, _PixelIterator::exception, _PixelIterator::name, _PixelIterator::pixel_wands, PixelSetIteratorRow(), PixelSetQuantumPixel(), _PixelIterator::region, _PixelIterator::signature, _PixelIterator::view, WandSignature, and _PixelIterator::y.
WandExport PixelWand** PixelGetPreviousIteratorRow (PixelIterator * iterator, size_t * number_wands)
Definition at line 727 of file pixel-iterator.c.
References _PixelIterator::active, _PixelIterator::debug, _PixelIterator::exception, _PixelIterator::name, _PixelIterator::pixel_wands, PixelSetIteratorRow(), PixelSetQuantumPixel(), _PixelIterator::region, _PixelIterator::signature, _PixelIterator::view, WandSignature, and _PixelIterator::y.
WandExport void PixelResetIterator (PixelIterator * iterator)
Definition at line 784 of file pixel-iterator.c.
References _PixelIterator::active, _PixelIterator::debug, _PixelIterator::name, _PixelIterator::signature, WandSignature, and _PixelIterator::y.
WandExport void PixelSetFirstIteratorRow (PixelIterator * iterator)
Definition at line 816 of file pixel-iterator.c.
References _PixelIterator::active, _PixelIterator::debug, _PixelIterator::name, _PixelIterator::region, _PixelIterator::signature, WandSignature, and _PixelIterator::y.
WandExport MagickBooleanType PixelSetIteratorRow (PixelIterator * iterator, const ssize_t row)
Definition at line 849 of file pixel-iterator.c.
References _PixelIterator::active, _PixelIterator::debug, _PixelIterator::name, _PixelIterator::region, _PixelIterator::signature, WandSignature, and _PixelIterator::y.
Referenced by PixelGetNextIteratorRow(), and PixelGetPreviousIteratorRow().
WandExport void PixelSetLastIteratorRow (PixelIterator * iterator)
Definition at line 885 of file pixel-iterator.c.
References _PixelIterator::active, _PixelIterator::debug, _PixelIterator::name, _PixelIterator::region, _PixelIterator::signature, WandSignature, and _PixelIterator::y.
WandExport MagickBooleanType PixelSyncIterator (PixelIterator * iterator)
Definition at line 917 of file pixel-iterator.c.
References _PixelIterator::debug, _PixelIterator::exception, _PixelIterator::name, _PixelIterator::pixel_wands, PixelGetQuantumPixel(), _PixelIterator::region, _PixelIterator::signature, _PixelIterator::view, WandSignature, and _PixelIterator::y.