MagickWand: pixel-wand.c File Reference
pixel-wand.c File Reference
#include "MagickWand/studio.h"
#include "MagickWand/MagickWand.h"
#include "MagickWand/magick-wand-private.h"
#include "MagickWand/pixel-wand-private.h"
#include "MagickWand/wand.h"
Data Structures
struct _PixelWand
Macros
#define PixelWandId "PixelWand"
Functions
WandExport void ClearPixelWand (PixelWand *wand)
WandExport PixelWand * ClonePixelWand (const PixelWand *wand)
WandExport PixelWand ** ClonePixelWands (const PixelWand **wands, const size_t number_wands)
WandExport PixelWand * DestroyPixelWand (PixelWand *wand)
WandExport PixelWand ** DestroyPixelWands (PixelWand **wand, const size_t number_wands)
WandExport MagickBooleanType IsPixelWandSimilar (PixelWand *p, PixelWand *q, const double fuzz)
WandExport MagickBooleanType IsPixelWand (const PixelWand *wand)
WandExport PixelWand * NewPixelWand (void)
WandExport PixelWand ** NewPixelWands (const size_t number_wands)
WandExport MagickBooleanType PixelClearException (PixelWand *wand)
WandExport double PixelGetAlpha (const PixelWand *wand)
WandExport Quantum PixelGetAlphaQuantum (const PixelWand *wand)
WandExport double PixelGetBlack (const PixelWand *wand)
WandExport Quantum PixelGetBlackQuantum (const PixelWand *wand)
WandExport double PixelGetBlue (const PixelWand *wand)
WandExport Quantum PixelGetBlueQuantum (const PixelWand *wand)
WandExport char * PixelGetColorAsString (const PixelWand *wand)
WandExport char * PixelGetColorAsNormalizedString (const PixelWand *wand)
WandExport size_t PixelGetColorCount (const PixelWand *wand)
WandExport double PixelGetCyan (const PixelWand *wand)
WandExport Quantum PixelGetCyanQuantum (const PixelWand *wand)
WandExport char * PixelGetException (const PixelWand *wand, ExceptionType *severity)
WandExport ExceptionType PixelGetExceptionType (const PixelWand *wand)
WandExport double PixelGetFuzz (const PixelWand *wand)
WandExport double PixelGetGreen (const PixelWand *wand)
WandExport Quantum PixelGetGreenQuantum (const PixelWand *wand)
WandExport void PixelGetHSL (const PixelWand *wand, double *hue, double *saturation, double *lightness)
WandExport Quantum PixelGetIndex (const PixelWand *wand)
WandExport double PixelGetMagenta (const PixelWand *wand)
WandExport Quantum PixelGetMagentaQuantum (const PixelWand *wand)
WandExport void PixelGetMagickColor (const PixelWand *wand, PixelInfo *color)
WandExport PixelInfo PixelGetPixel (const PixelWand *wand)
WandExport void PixelGetQuantumPacket (const PixelWand *wand, PixelInfo *packet)
WandExport void PixelGetQuantumPixel (const Image *image, const PixelWand *wand, Quantum *pixel)
WandExport double PixelGetRed (const PixelWand *wand)
WandExport Quantum PixelGetRedQuantum (const PixelWand *wand)
WandExport double PixelGetYellow (const PixelWand *wand)
WandExport Quantum PixelGetYellowQuantum (const PixelWand *wand)
WandExport void PixelSetAlpha (PixelWand *wand, const double alpha)
WandExport void PixelSetAlphaQuantum (PixelWand *wand, const Quantum alpha)
WandExport void PixelSetBlack (PixelWand *wand, const double black)
WandExport void PixelSetBlackQuantum (PixelWand *wand, const Quantum black)
WandExport void PixelSetBlue (PixelWand *wand, const double blue)
WandExport void PixelSetBlueQuantum (PixelWand *wand, const Quantum blue)
WandExport MagickBooleanType PixelSetColor (PixelWand *wand, const char *color)
WandExport void PixelSetColorCount (PixelWand *wand, const size_t count)
WandExport void PixelSetColorFromWand (PixelWand *wand, const PixelWand *color)
WandExport void PixelSetCyan (PixelWand *wand, const double cyan)
WandExport void PixelSetCyanQuantum (PixelWand *wand, const Quantum cyan)
WandExport void PixelSetFuzz (PixelWand *wand, const double fuzz)
WandExport void PixelSetGreen (PixelWand *wand, const double green)
WandExport void PixelSetGreenQuantum (PixelWand *wand, const Quantum green)
WandExport void PixelSetHSL (PixelWand *wand, const double hue, const double saturation, const double lightness)
WandExport void PixelSetIndex (PixelWand *wand, const Quantum index)
WandExport void PixelSetMagenta (PixelWand *wand, const double magenta)
WandExport void PixelSetMagentaQuantum (PixelWand *wand, const Quantum magenta)
WandExport void PixelSetPixelColor (PixelWand *wand, const PixelInfo *color)
WandExport void PixelSetQuantumPixel (const Image *image, const Quantum *pixel, PixelWand *wand)
WandExport void PixelSetRed (PixelWand *wand, const double red)
WandExport void PixelSetRedQuantum (PixelWand *wand, const Quantum red)
WandExport void PixelSetYellow (PixelWand *wand, const double yellow)
WandExport void PixelSetYellowQuantum (PixelWand *wand, const Quantum yellow)
Macro Definition Documentation
#define PixelWandId "PixelWand"
Definition at line 58 of file pixel-wand.c.
Referenced by ClonePixelWand(), IsPixelWand(), and NewPixelWand().
Function Documentation
WandExport void ClearPixelWand (PixelWand * wand)
Definition at line 109 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::exception, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
WandExport PixelWand* ClonePixelWand (const PixelWand * wand)
Definition at line 142 of file pixel-wand.c.
References AcquireWandId(), _PixelWand::count, _PixelWand::debug, _PixelWand::exception, _PixelWand::id, MaxTextExtent, _PixelWand::name, _PixelWand::pixel, PixelWandId, _PixelWand::signature, ThrowWandFatalException, and WandSignature.
Referenced by ClonePixelWands().
WandExport PixelWand** ClonePixelWands (const PixelWand ** wands, const size_t number_wands)
Definition at line 195 of file pixel-wand.c.
References ClonePixelWand(), and ThrowWandFatalException.
Referenced by ClonePixelIterator(), and CloneWandView().
WandExport PixelWand* DestroyPixelWand (PixelWand * wand)
Definition at line 236 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::exception, _PixelWand::id, _PixelWand::name, RelinquishWandId(), _PixelWand::signature, and WandSignature.
Referenced by DestroyPixelWands(), and MagickMontageImage().
WandExport PixelWand** DestroyPixelWands (PixelWand ** wand, const size_t number_wands)
Definition at line 275 of file pixel-wand.c.
References DestroyPixelWand(), and WandSignature.
Referenced by ClearPixelIterator(), DestroyPixelIterator(), and DestroyPixelsThreadSet().
WandExport MagickBooleanType IsPixelWand (const PixelWand * wand)
Definition at line 359 of file pixel-wand.c.
References _PixelWand::name, PixelWandId, _PixelWand::signature, and WandSignature.
WandExport MagickBooleanType IsPixelWandSimilar (PixelWand * p, PixelWand * q, const double fuzz)
Definition at line 321 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
WandExport PixelWand* NewPixelWand (void)
Definition at line 388 of file pixel-wand.c.
References AcquireWandId(), _PixelWand::debug, _PixelWand::exception, _PixelWand::id, MaxTextExtent, _PixelWand::name, _PixelWand::pixel, PixelWandId, _PixelWand::signature, ThrowWandFatalException, and WandSignature.
Referenced by MagickGetBackgroundColor(), MagickMontageImage(), and NewPixelWands().
WandExport PixelWand** NewPixelWands (const size_t number_wands)
Definition at line 442 of file pixel-wand.c.
References NewPixelWand(), and ThrowWandFatalException.
Referenced by AcquirePixelsThreadSet(), ClearPixelIterator(), MagickGetImageHistogram(), NewPixelIterator(), and NewPixelRegionIterator().
WandExport MagickBooleanType PixelClearException (PixelWand * wand)
Definition at line 482 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::exception, _PixelWand::name, _PixelWand::signature, and WandSignature.
WandExport double PixelGetAlpha (const PixelWand * wand)
Definition at line 514 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
WandExport Quantum PixelGetAlphaQuantum (const PixelWand * wand)
Definition at line 545 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
Referenced by MagickBlackThresholdImage(), MagickColorizeImage(), MagickTintImage(), and MagickWhiteThresholdImage().
WandExport double PixelGetBlack (const PixelWand * wand)
Definition at line 576 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
WandExport Quantum PixelGetBlackQuantum (const PixelWand * wand)
Definition at line 607 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
Referenced by MagickColorizeImage(), and MagickTintImage().
WandExport double PixelGetBlue (const PixelWand * wand)
Definition at line 638 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
WandExport Quantum PixelGetBlueQuantum (const PixelWand * wand)
Definition at line 669 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
Referenced by MagickBlackThresholdImage(), MagickColorizeImage(), MagickTintImage(), and MagickWhiteThresholdImage().
WandExport char* PixelGetColorAsNormalizedString (const PixelWand * wand)
Definition at line 741 of file pixel-wand.c.
References _PixelWand::debug, MaxTextExtent, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
WandExport char* PixelGetColorAsString (const PixelWand * wand)
Definition at line 700 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
WandExport size_t PixelGetColorCount (const PixelWand * wand)
Definition at line 785 of file pixel-wand.c.
References _PixelWand::count, _PixelWand::debug, _PixelWand::name, _PixelWand::signature, and WandSignature.
WandExport double PixelGetCyan (const PixelWand * wand)
Definition at line 816 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
WandExport Quantum PixelGetCyanQuantum (const PixelWand * wand)
Definition at line 847 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
Referenced by MagickTintImage().
WandExport char* PixelGetException (const PixelWand * wand, ExceptionType * severity)
Definition at line 881 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::exception, MaxTextExtent, _PixelWand::name, _PixelWand::signature, ThrowWandFatalException, and WandSignature.
WandExport ExceptionType PixelGetExceptionType (const PixelWand * wand)
Definition at line 935 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::exception, _PixelWand::name, _PixelWand::signature, and WandSignature.
WandExport double PixelGetFuzz (const PixelWand * wand)
Definition at line 966 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
WandExport double PixelGetGreen (const PixelWand * wand)
Definition at line 997 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
WandExport Quantum PixelGetGreenQuantum (const PixelWand * wand)
Definition at line 1028 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
Referenced by MagickBlackThresholdImage(), MagickColorizeImage(), MagickTintImage(), and MagickWhiteThresholdImage().
WandExport void PixelGetHSL (const PixelWand * wand, double * hue, double * saturation, double * lightness)
Definition at line 1063 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
WandExport Quantum PixelGetIndex (const PixelWand * wand)
Definition at line 1097 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
WandExport double PixelGetMagenta (const PixelWand * wand)
Definition at line 1128 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
WandExport Quantum PixelGetMagentaQuantum (const PixelWand * wand)
Definition at line 1159 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
Referenced by MagickTintImage().
WandExport void PixelGetMagickColor (const PixelWand * wand, PixelInfo * color)
Definition at line 1192 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
Referenced by MagickFloodfillPaintImage(), MagickNewImage(), MagickOpaquePaintImage(), MagickSetImageColor(), and MagickTransparentPaintImage().
WandExport PixelInfo PixelGetPixel (const PixelWand * wand)
Definition at line 1225 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
Referenced by MagickColorizeImage(), and MagickTintImage().
WandExport void PixelGetQuantumPacket (const PixelWand * wand, PixelInfo * packet)
Definition at line 1258 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
Referenced by DrawSetBorderColor(), DrawSetFillColor(), DrawSetStrokeColor(), DrawSetTextUnderColor(), MagickBorderImage(), MagickFloodfillPaintImage(), MagickFrameImage(), MagickMontageImage(), MagickRotateImage(), MagickSetBackgroundColor(), MagickSetImageBackgroundColor(), MagickSetImageBorderColor(), MagickSetImageColormapColor(), MagickSetImageMatteColor(), and MagickShearImage().
WandExport void PixelGetQuantumPixel (const Image * image, const PixelWand * wand, Quantum * pixel)
Definition at line 1310 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
Referenced by DuplexTransferWandViewIterator(), PixelSyncIterator(), SetWandViewIterator(), TransferWandViewIterator(), and UpdateWandViewIterator().
WandExport double PixelGetRed (const PixelWand * wand)
Definition at line 1360 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
WandExport Quantum PixelGetRedQuantum (const PixelWand * wand)
Definition at line 1391 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
Referenced by MagickBlackThresholdImage(), MagickColorizeImage(), MagickTintImage(), and MagickWhiteThresholdImage().
WandExport double PixelGetYellow (const PixelWand * wand)
Definition at line 1422 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
WandExport Quantum PixelGetYellowQuantum (const PixelWand * wand)
Definition at line 1453 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
Referenced by MagickTintImage().
WandExport void PixelSetAlpha (PixelWand * wand, const double alpha)
Definition at line 1487 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
WandExport void PixelSetAlphaQuantum (PixelWand * wand, const Quantum alpha)
Definition at line 1521 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
WandExport void PixelSetBlack (PixelWand * wand, const double black)
Definition at line 1554 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
WandExport void PixelSetBlackQuantum (PixelWand * wand, const Quantum black)
Definition at line 1587 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
WandExport void PixelSetBlue (PixelWand * wand, const double blue)
Definition at line 1620 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
WandExport void PixelSetBlueQuantum (PixelWand * wand, const Quantum blue)
Definition at line 1653 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
WandExport MagickBooleanType PixelSetColor (PixelWand * wand, const char * color)
Definition at line 1687 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::exception, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
WandExport void PixelSetColorCount (PixelWand * wand, const size_t count)
Definition at line 1729 of file pixel-wand.c.
References _PixelWand::count, _PixelWand::debug, _PixelWand::name, _PixelWand::signature, and WandSignature.
Referenced by MagickGetImageHistogram().
WandExport void PixelSetColorFromWand (PixelWand * wand, const PixelWand * color)
Definition at line 1762 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
WandExport void PixelSetCyan (PixelWand * wand, const double cyan)
Definition at line 1796 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
WandExport void PixelSetCyanQuantum (PixelWand * wand, const Quantum cyan)
Definition at line 1829 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
WandExport void PixelSetFuzz (PixelWand * wand, const double fuzz)
Definition at line 1862 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
WandExport void PixelSetGreen (PixelWand * wand, const double green)
Definition at line 1895 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
WandExport void PixelSetGreenQuantum (PixelWand * wand, const Quantum green)
Definition at line 1928 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
WandExport void PixelSetHSL (PixelWand * wand, const double hue, const double saturation, const double lightness)
Definition at line 1963 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
WandExport void PixelSetIndex (PixelWand * wand, const Quantum index)
Definition at line 2005 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
WandExport void PixelSetMagenta (PixelWand * wand, const double magenta)
Definition at line 2038 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
WandExport void PixelSetMagentaQuantum (PixelWand * wand, const Quantum magenta)
Definition at line 2072 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
WandExport void PixelSetPixelColor (PixelWand * wand, const PixelInfo * color)
Definition at line 2105 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
Referenced by DrawGetBorderColor(), DrawGetFillColor(), DrawGetStrokeColor(), DrawGetTextUnderColor(), MagickGetBackgroundColor(), MagickGetImageBackgroundColor(), MagickGetImageBorderColor(), MagickGetImageColormapColor(), MagickGetImageHistogram(), and MagickGetImageMatteColor().
WandExport void PixelSetQuantumPixel (const Image * image, const Quantum * pixel, PixelWand * wand)
Definition at line 2140 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
Referenced by DuplexTransferWandViewIterator(), GetWandViewIterator(), MagickGetImagePixelColor(), PixelGetCurrentIteratorRow(), PixelGetNextIteratorRow(), PixelGetPreviousIteratorRow(), TransferWandViewIterator(), and UpdateWandViewIterator().
WandExport void PixelSetRed (PixelWand * wand, const double red)
Definition at line 2181 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
WandExport void PixelSetRedQuantum (PixelWand * wand, const Quantum red)
Definition at line 2214 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
WandExport void PixelSetYellow (PixelWand * wand, const double yellow)
Definition at line 2247 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
WandExport void PixelSetYellowQuantum (PixelWand * wand, const Quantum yellow)
Definition at line 2280 of file pixel-wand.c.
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.