MagickWand: wand.c File Reference
wand.c File Reference
#include "MagickWand/studio.h"
#include "MagickWand/MagickWand.h"
#include "MagickWand/magick-wand-private.h"
#include "MagickWand/wand.h"
Functions
WandExport size_t AcquireWandId (void)
WandExport void DestroyWandIds (void)
WandExport void RelinquishWandId (const size_t id)
Variables
static SplayTreeInfo * wand_ids = (SplayTreeInfo *) NULL
static MagickBooleanType instantiate_wand = MagickFalse
static SemaphoreInfo * wand_semaphore = (SemaphoreInfo *) NULL
Function Documentation
WandExport size_t AcquireWandId (void)
Definition at line 74 of file wand.c.
References _WandView::id, instantiate_wand, wand_ids, and wand_semaphore.
Referenced by AcquireMagickCLI(), CloneDrawingWand(), CloneMagickWand(), CloneMagickWandFromImages(), ClonePixelIterator(), ClonePixelWand(), CloneWandView(), NewDrawingWand(), NewMagickWand(), NewPixelIterator(), NewPixelRegionIterator(), NewPixelWand(), NewWandView(), and NewWandViewExtent().
WandExport void DestroyWandIds (void)
Definition at line 114 of file wand.c.
References instantiate_wand, wand_ids, and wand_semaphore.
Referenced by MagickWandTerminus().
WandExport void RelinquishWandId (const size_t id)
Definition at line 148 of file wand.c.
References _WandView::id, wand_ids, and wand_semaphore.
Referenced by DestroyDrawingWand(), DestroyMagickCLI(), DestroyMagickWand(), DestroyPixelIterator(), DestroyPixelWand(), and DestroyWandView().
Variable Documentation
MagickBooleanType instantiate_wand = MagickFalse static
Definition at line 51 of file wand.c.
Referenced by AcquireWandId(), and DestroyWandIds().
SplayTreeInfo* wand_ids = (SplayTreeInfo *) NULL static
Definition at line 48 of file wand.c.
Referenced by AcquireWandId(), DestroyWandIds(), and RelinquishWandId().
SemaphoreInfo* wand_semaphore = (SemaphoreInfo *) NULL static
Definition at line 54 of file wand.c.
Referenced by AcquireWandId(), DestroyWandIds(), and RelinquishWandId().