MagickWand: wand.h File Reference
wand.h File Reference
Functions
WandExport size_t AcquireWandId (void)
WandExport void DestroyWandIds (void)
WandExport void RelinquishWandId (const size_t)
Function Documentation
WandExport size_t AcquireWandId (void)
Definition at line 74 of file wand.c.
References _WandView::id, instantiate_wand, wand_ids, and wand_semaphore.
Referenced by AcquireMagickCLI(), CloneDrawingWand(), CloneMagickWand(), CloneMagickWandFromImages(), ClonePixelIterator(), ClonePixelWand(), CloneWandView(), NewDrawingWand(), NewMagickWand(), NewPixelIterator(), NewPixelRegionIterator(), NewPixelWand(), NewWandView(), and NewWandViewExtent().
WandExport void DestroyWandIds (void)
WandExport void RelinquishWandId (const size_t)
Definition at line 148 of file wand.c.
References _WandView::id, wand_ids, and wand_semaphore.
Referenced by DestroyDrawingWand(), DestroyMagickCLI(), DestroyMagickWand(), DestroyPixelIterator(), DestroyPixelWand(), and DestroyWandView().