all:
	perl demo.pl
	perl button.pl
	perl shapes.pl
	perl piddle.pl
	perl tree.pl
	perl steganography.pl
	perl shadow-text.pl
	perl compose-specials.pl
	perl pixel-fx.pl
	perl single-pixels.pl
	perl annotate.pl
	perl composite.pl

clean:
	/bin/rm -f demo.jpg button.gif model.png shadow.gif tree.gif \
	    compose-specials.jpg  single-pixels.gif  pixel-fx.gif
