all:
	perl demo.pl
	perl button.pl
	perl shapes.pl
	perl piddle.pl
	perl tree.pl
	perl steganography.pl
	perl shadow-text.pl
	perl compose-specials.pl
	perl pixel-fx.pl
	perl single-pixels.pl
	perl annotate.pl
	perl composite.pl

clean:
	/bin/rm -f demo.pam button.pam model.pam shadow.pam tree.pam \
	    compose-specials.pam  single-pixels.pam  pixel-fx.pam
