on:
  workflow_dispatch:
  schedule:
  - cron: 0 7 * * 1
  push:
    branches:
    - main
    paths:
    - .github/workflows/scorecard-analysis.yml
  pull_request:
    branches:
    - main

permissions: read-all

name: Scorecard analysis
jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      id-token: write

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
        with:
          persist-credentials: false

      - name: Run analysis
        uses: ossf/scorecard-action@2d1146689b8cda280b9bc96326124645441f03bc #v2.4.4
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: ${{ github.event_name != 'pull_request' }}

      - name: Upload to code-scanning
        if: github.event_name != 'pull_request'
        uses: github/codeql-action/upload-sarif@db488ddef3bf6cb639b32c2e9a7c0a7ea8271d28 #4.37.8
        with:
          sarif_file: results.sarif
